### ISSUE TITLE
Disciplin Buged skills/Talents

### ISSUE THREAD

**Issue by AndreasGr94** [Valhalla-Gaming/Tracker#1007]
1)Atotement:healing not work
2)Holy nova > Fixed.
3)Multystrike bonus not works
4)Levitate  not working 
5)Power word:Solace doent activate Atotement(thought atotement is bugged too atm)
6)Body and Soul Talent doesnt increase move speed

**Comment by EPS1L0N** [comment]
2) fixed

**Comment by Guybrush-Hellscream** [comment]
Updated.

**Comment by Tregeta** [comment]
3, 4, 6 fixed
