### ISSUE TITLE
Hostiles in Dalaran

### ISSUE THREAD

**Issue by GeneralCaveman** [Valhalla-Gaming/Tracker#1050]
https://github.com/HellscreamWoW/Tracker/issues/875

Very similar to the issue above. It seems that some hostile NPCs in Dalaran can be aggrod when that shouldn't be the case. Below are a couple example NPCs.

http://www.wowhead.com/npc=32706/saedelin-whitedawn
http://www.wowhead.com/npc=32709/hunaka-greenhoof

**Comment by Trekex** [comment]
Seems that I can't aggro them anymore
