### ISSUE TITLE
Warlock :Burning Rush 

### ISSUE THREAD

**Issue by eugenajazaj** [Valhalla-Gaming/Tracker#1060]
Its a talent when you can choose at level 60 , i wanted to try it and i was dead everytime i use it.
it just consumes 4% of your health and 50% increase speed all good but it seems it can't be cancelled its ike someone used it to you and not your own spell .http://www.wowhead.com/spell=111400/burning-rush

**Comment by forstix** [comment]
it show as debuff which mean you can cancel it

**Comment by Usernameisntalreadytaken** [comment]
Tried it as well, there was just no way to cancel it other than mounting and dismounting.

> it show as debuff which mean you can cancel it

Did you mean "it shows as debuff which means you **CAN'T** cancel it?
cos yeah you indeed can't
