### ISSUE TITLE
Shaman - Totem's Visual

### ISSUE THREAD

**Issue by Tregeta** [Valhalla-Gaming/Tracker#1108]
All totems except tremor thus far have no models and appear as checkered cubes.
[Grounding Totem](http://www.wowhead.com/spell=8177/grounding-totem)
[Earthbind Totem](http://www.wowhead.com/spell=2484/earthbind-totem)
[Searing Totem](http://www.wowhead.com/spell=3599/searing-totem)
[Healing Stream Totem](http://www.wowhead.com/spell=5394/healing-stream-totem)
[Magma Totem](http://www.wowhead.com/spell=8190/magma-totem)

The only one that visually worked was
[Earth Elemental Totem](http://www.wowhead.com/spell=2062/earth-elemental-totem)

**Comment by war627** [comment]
still some totems have visual bugs

**Comment by Malae1** [comment]
Please provide their names.

**Comment by war627** [comment]
talent perk given totems like  [Earthgrab Totem] [Windwalk Totem] i dont have access to lvl 100 one

**Comment by Malae1** [comment]
Then this is not a visual bug if the totems show up correctly. By this I mean they are no longer blue and white cubes.

**Comment by war627** [comment]
but i see them as blue and white cubes

**Comment by Moustachos** [comment]
Ref #2266
