### ISSUE TITLE
Mage Talent: Ice Floes.

### ISSUE THREAD

**Issue by Vynrae** [Valhalla-Gaming/Tracker#1126]
http://www.wowhead.com/spell=108839/ice-floes
+Bugged:
-Once used i can keep casting spells while moving until the timer is over, and not just one spell as it says.
-Hand animation keeps playing even after the spell ends.
+Working:
-If i click it 3 times in a row it will stack up to 3 charges, they all disapear once the timer is over.
-Its 15 seconds timer works fine.
-Its 20 seconds recharge timer works fine.
-Castable while casting another spell.
-Unaffected by global cooldown.
-The blue color effect animation on hands and feet works.

**Comment by EPS1L0N** [comment]
#2266
