### ISSUE TITLE
Mage Talent: Cauterize.

### ISSUE THREAD

**Issue by Vynrae** [Valhalla-Gaming/Tracker#1132]
http://www.wowhead.com/spell=86949/cauterize
Just by having this passive talent, i basically absorb any damage (except falling damage), so i can't know if its fatal damage effect works (i killed myself jumping off a cliff and i died immediately, no health was returned or anything).

**Comment by GeneralCaveman** [comment]
I can't find anything more recent but a couple years ago, people said that cauterize does not save you from fall damage.

**Comment by afan4e** [comment]
This spell still not working correctly, it says burn you for 28% of max health. it is gave me 1M damage.
![wowscrnshot_061416_004916](https://cloud.githubusercontent.com/assets/19918109/16025984/5061a26c-31cb-11e6-866c-6976554eccf1.jpg)
