### ISSUE TITLE
Mage Talent: Greater Invisibility.

### ISSUE THREAD

**Issue by Vynrae** [Valhalla-Gaming/Tracker#1133]
http://www.wowhead.com/spell=110959/greater-invisibility
+Bugged:
-Has no effect once used.
-Animation.
+Working:
-Cooldown.
-Replaces invisiblity: http://www.wowhead.com/spell=66/invisibility .

**Comment by Tregeta** [comment]
@nuhrii

> This talent used to make you Invisible but suddenly stopped a few days ago, still applies the damage reduction effect though. Also doesn't seem to remove damage over time effects
