### ISSUE TITLE
Mage Talent: Frost Bomb.

### ISSUE THREAD

**Issue by Vynrae** [Valhalla-Gaming/Tracker#1139]
http://www.wowhead.com/spell=112948/frost-bomb
+Bugged:
-Does not work as described in wowhead, my Ice Lance http://www.wowhead.com/spell=30455
which benefited from Shatter http://www.wowhead.com/spell=12982
and hit my targets when they were frozen (multple times) did not cause the Frost Bomb to trigger.
+Working:
-Cast range.
-Cast time.
-Damage in description (not sure about damage delt because it never occurs).
-Debuff duration.
-Mana cost (formula and usage).
-Limited to 1 target.

**Comment by GeneralCaveman** [comment]
This bug is still present with the release of Legion.
