### ISSUE TITLE
Mage Talent: Rune of Power.

### ISSUE THREAD

**Issue by Vynrae** [Valhalla-Gaming/Tracker#1141]
http://www.wowhead.com/spell=116011/rune-of-power
+Bugged:
-No damage increased when standing within the specified range.
-Animation, i get this tiny symbol instead of the picture on wow-head: http://postimg.org/image/4iq2ytadf/930f09e7/
-Number of place-able is unlimited and not 2 as wow-head mentions.
+Working:
-Cast range,
-Cast time.
-Each rune lasts 3 minutes.

**Comment by nuhrii** [comment]
As of Legion you can't ground target this spell
