### ISSUE TITLE
Envenom Skill

### ISSUE THREAD

**Issue by FlameChampion34** [Valhalla-Gaming/Tracker#115]
It does no dmg but the buff from it seem's to work.

**Comment by Collector-Hellscream** [comment]
It deals very low damage. At level 31 my Envenom deals 2 point of damage. Please reopen that issue.

**Comment by kupidons** [comment]
atm for me envenom does around 7.5k dmg (allways crit) and it doesn't do dmg over time aka works wrong. and nice seeing high priority skills beeing fixed ^^

**Comment by Tregeta** [comment]
@kupidons Envenom does not do damage over time.
