### ISSUE TITLE
Ticking Bomb - [NPC] Cultist Infiltrator

### ISSUE THREAD

**Issue by GeneralCaveman** [Valhalla-Gaming/Tracker#1169]
http://www.wowhead.com/spell=54962/ticking-bomb#summons
http://www.wowhead.com/npc=28373/cultist-infiltrator

I am not sure what exactly this thing is supposed to do.

Currently when this spell is cast by the cultist, a NPC with no view model appears and it just follows you around attacking you.

**Comment by Tregeta** [comment]
fixed next update
