### ISSUE TITLE
Lost Hunter Starter Pet

### ISSUE THREAD

**Issue by Tregeta** [Valhalla-Gaming/Tracker#1170]
At level one you get a boar as a pet, I (Snusnutheone) got d/c'd while at level 2 or 3. When I relogged my pet was missing and it has yet to come back. Tried to call it back and won't come. I'll be level 10 soon so it wont be an issue after that but just wanted to make you guys aware that it could be a possible bug.

**Comment by Max-Hellscream** [comment]
Developers note: The pet disappears when the player levels up. They have to re-summon it after each new level. This only happens on a real level up. Using the .level command will not trigger this bug.

**Comment by Moustachos** [comment]
The initial bug rather looked like a character-specific one, so I'm closing the issue.

The pet is no longer dismissed upon levelup.

**Comment by Moustachos** [comment]
Ref #2266
