### ISSUE TITLE
Hunter pet is  bugged after level 85

### ISSUE THREAD

**Issue by neloosefu** [Valhalla-Gaming/Tracker#1176]
Hi guys I know its a known issue but I remember that you said its fixed and ive noticed that pet is staying like at level 85 doesn't follow my HP and stats I hav 42k hp im level 90 and my pet is 3.6k hp level 90 pet ...I don't think its following me  with stats and all the stats, in Pandaria is useless

**Comment by kupidons** [comment]
pet's also have 1-1 dmg, guess pet stats don't work @ all

**Comment by Collector-Valhalla** [comment]
At level 100 non-tank pets (tenacity or whatever) have only 30k+ hp and tank pets have 40k+ hp. Means they pretty much die from 1 hit in pvp combat.

**Comment by Moustachos** [comment]
Ref #2266
