### ISSUE TITLE
(Pandaren)(Hunter) No hunter pet

### ISSUE THREAD

**Issue by TheUnimatrix** [Valhalla-Gaming/Tracker#1179]
I created a female Pandaren hunter and I do not have a pet at all.
The Pandaren hunter pet should be a green dragon turtle.

http://www.wow-petopia.com/look/ridingdragonturtleblack.html
http://www.wowhead.com/npc=57239/wise-turtle

**Comment by Moustachos** [comment]
Currently pandaren hunters do have this turtle pet.

**Comment by Moustachos** [comment]
Ref #2266
