### ISSUE TITLE
Fishing 

### ISSUE THREAD

**Issue by neloosefu** [Valhalla-Gaming/Tracker#1188]
Hello guys I wanna report for fishing prof that quest fish cant be fished out of the pool for quest in ogrimar (dayli quests) ive fished them like 20 mins for  every quest and the fish desnt drop other fished yes but the quest fish nope

**Comment by silverjade** [comment]
I was fishing yesterday and having issues with the fishing bobber not letting you know when you "caught" a fish. If I clicked on it it was a fifty/fifty chance of looting a caught fish or a message saying no fish was hooked. If I left it alone, the timer would run out telling me the "fish got away"

**Comment by Dev-iL** [comment]
Actually, aside from the [A Furious Catch](http://www.wowhead.com/quest=26588/a-furious-catch) quest, all ogri fishing quests are working, with the minor bug that fishing loot tables seem to be tied to the entire zone of ogri, rather than specific sub zones within ogri.

**Comment by zwei7** [comment]
This is happening in Darnasus and Dark shore as well.
