### ISSUE TITLE
Druid Spells -  Catform, Shred and much more

### ISSUE THREAD

**Issue by Illowerth** [Valhalla-Gaming/Tracker#1192]
At first I though devs are focusing on some main classes such as Warrior and Rogue and will proceed to advanced ones such as Druid and Shaman later, but since changelog claims to fix spell that is recieved far AFTER several previous totally not working well, I decided to make one common issue thred for all to me known problems with Druids at least up to level 15 - talentlessly.

**Balance**
I was using it back in Cata yet its working seems to be changed now so not sure If this is how it is supposed to work or its bugged. Back in Cata each spell granted specific Balance (strarting with Sun then it was toggling). Now it seems getting into combat and using at least one such spell is required to quickly passively generate Balance (now strarting on Moon). Once it hit 100 of the Balance, it gets to hit 100 balance of the opposite side and returns to 0. While in cata those points were spent by using spells until reset to 0 when Eclipse run out. I seem to have no Eclipse effect now. Also, while in Cata it highlighted the bar once it hit 100 together with now empowered spells of that balance side, there it seems to do nothing.

**Catform**
Seems to do no speed boost while it should. I feel like having same speed regardless the form.

**Shred**
Is supposed to deal 20% more damage while prowling. I didn't do advaced researched just repetedly used it on same foes with same level yet results were same regardless prowling or not. Seems like doesn't work.

**Prowl**
Does not automatically turn into cat form, allowing tauren to prowl unformed.

**Combo points**
Again, I am not sure if this is how it is supposed to work due to some MoP/WoD change but it used to work differently. Once combo point was generated, it was harvestable on that for only until its death. Those combo points can be inherited, so you can kill foe with combo-generating skills and finish other foe harvesting those combo point that were moved on them.

**Other spells**
Again, I don't know whether there's been some changes, but according to wowhead, I am supposed to have also these abilities (as balance Druid) which I simply don't have.
Natural Insight http://wowwiki.wikia.com/Natural_Insight
- I do have at lvl15 cca 6k Mana which is big amount but not sure whether it is 400% of original nor does this spell appear in my Spellbook.

**Comment by Illowerth** [comment]
**UPDATE**
**Moonkin Form**
It seems the stats and mechanics work, it improves my Armor and suppose also my skills as it should. Yet it does not turn me into anything. Just aestethical thing - more like a stance now. Would be nice to have moonkin model.

**Comment by HellscreamWoW** [comment]
**Catform**: Fixed
**Prowl**: Fixed
**Combo points**: Fixed
**Other spells**: As of WoD, not all spells appear in the spell book. So this issue is not an issue.

In the future, please create a separate issue for each bug you find.

**Comment by Moustachos** [comment]
#2266
