### ISSUE TITLE
[Quest] Felwood - Break the Unbreakable 

### ISSUE THREAD

**Issue by Tregeta** [Valhalla-Gaming/Tracker#1193]
[Break the Unbreakable](http://www.wowhead.com/quest=28113/break-the-unbreakable) Firewall, item does not dispel it, can't get on other side to complete.

**Comment by Trekex** [comment]
The firewall disappeared when I used the item. Should we close the issue?

**Comment by Trekex** [comment]
(But then reappeared after I beat the boss, so I had to use Hearthstone)

**Comment by Malae1** [comment]
Must have a time limit on it's disappearing and then reappears after it is up.

**Comment by Cidragon** [comment]
The firewall is working as intented. Please note that the firewall disappear for a very short time :)
