### ISSUE TITLE
Monk bugged spells

### ISSUE THREAD

**Issue by korachitai** [Valhalla-Gaming/Tracker#1226]
I'm level 30, until now i found this monk bugged spells:
Flying Serpent Kick: Doesn't stop when you activate it again, instead you fly for the full duration
Touch of Karma: not working at all
Zen Pilgrimage: not working at all
Momentum: not proccing with the right spells
Chi Burst: not working

**Comment by Malae1** [comment]
Need more info.

**Comment by Collector-Valhalla** [comment]
http://www.wowhead.com/spell=101545/flying-serpent-kick

"Sometimes" you stop when you use it. Don't know why. Also it doesn't give any slow effect or deal damage to enemies around.

**Comment by BKPepe** [comment]
Surging Mist: Doesn't heal, instead generates 1 chi
Still it doesn't work. :(

**Comment by Moustachos** [comment]
Surging Mist will be fixed on next update ;)
