### ISSUE TITLE
Combar Energy Regeneration

### ISSUE THREAD

**Issue by Cyuty** [Valhalla-Gaming/Tracker#1239]
Like title says, it dosent regenarate how it must, Vitality is the name of the passive spell, can't seem to find it in spell book.

**Comment by Malae1** [comment]
http://www.wowhead.com/spell=61329/vitality
Another thing to note is that this does not show up in your Spellbook & Abilities, similar to other passives for different classe(http://www.wowhead.com/spell=53592/guarded-by-the-light).
