### ISSUE TITLE
the might of the scourge

### ISSUE THREAD

**Issue by Danne1993** [Valhalla-Gaming/Tracker#1241]
Hello,

I just created a Death Knight but I can't finish the quest "The Might of the Scourge".
I can't join Mograine because the teleporter doesn't work, and I'm stuck unless I use the Death Gate or the TP to Orgrimmar but I can't make the whole death knight quests and get the Deathcharger mount.

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #2266
