### ISSUE TITLE
Quest bug:  Balance Must Be Preserved

### ISSUE THREAD

**Issue by vation1234** [Valhalla-Gaming/Tracker#1276]
http://www.wowhead.com/quest=9720/balance-must-be-preserved

NPC does not empty
Umbrafen Steam Pump: 70.5, 80.3
Marshlight Steam Pump: 25.4, 42.9
Serpent Steam Pump: 62.0, 40.8
Lagoon Steam Pump: 63.1, 64.1

video : https://www.youtube.com/watch?v=YUutHisDI0Y

**Comment by Cidragon** [comment]
Fixed in December 5th changelog.
