### ISSUE TITLE
Quest bug: Fresh from the hills 

### ISSUE THREAD

**Issue by skorge1** [Valhalla-Gaming/Tracker#1305]
The issue with http://www.wowhead.com/quest=28632/fresh-from-the-hills is that you cannot loot the solid ice.

**Comment by Guybrush-Hellscream** [comment]
ATM, this quest works. You can kill [Solide Ice](http://www.wowhead.com/npc=49233/solid-ice) and loot [Pure Glacier Ice](http://www.wowhead.com/item=64662/pure-glacier-ice) on it.
The only problem remaining is that Solid Ice is moving when you attack them ; they shouldn't.

**Comment by Cidragon** [comment]
This quest was fixed on November 25th changelog.
