### ISSUE TITLE
Leeching poison

### ISSUE THREAD

**Issue by Damvs** [Valhalla-Gaming/Tracker#1334]
There haven't pucture with this poison, and Shav not give 4% of hp.

http://www.wowhead.com/spell=108211/leeching-poison#modified-by

http://www.wowhead.com/spell=5938/shiv

"Poison sangsue a été modifié. Lorsqu’il est actif, il accorde désormais un effet de drain de 10%, mais n’applique plus d’effet de poison à la cible. L’effet déclenché par la technique Kriss, quand Poison sangsue est actif, n’a pas été modifié"

http://eu.battle.net/wow/fr/blog/17561381/notes-de-mise-%C3%A0-jour-de-la-61-sur-les-royaumes-de-test-02-02-2015

**Comment by Damvs** [comment]
Now  there are pucture, but Shav not give 4% of Hp

**Comment by Moustachos** [comment]
Ref #2266
