### ISSUE TITLE
Shaman Spell bug: Ancestral Spirit

### ISSUE THREAD

**Issue by skorge1** [Valhalla-Gaming/Tracker#1349]
The issue with http://www.wowhead.com/spell=2008/ancestral-spirit is that it doesn't revive the target.

**Comment by Guybrush-Hellscream** [comment]
About that spell, is this the same bug as Monk's "Resuscitate" spell?
(http://www.wowhead.com/spell=115178/resuscitate)

That means that i can res people ONLY IF they didn't release their soul. If they are already in ghost, it doesn't work because the spell doesn't find anything to res.

**Comment by skorge1** [comment]
yeah
