### ISSUE TITLE
Hunter autoshot

### ISSUE THREAD

**Issue by lucasfromhellscream** [Valhalla-Gaming/Tracker#1387]
some times when you use skills hunters will aim forever(i use bow so the animation is aiming
you guys got it lol) and so whe cant do any auto shot only cast skills if whe want to cast autshot on mobs whe have to click on the mob with the attack mouse side or re use the auto attack skill

**Comment by TheRedSkorpion** [comment]
I just want to point out a quick fix: when you get stuck without being able to auto-attack, you can deselect the ennemy by pressing Esc and right-click on him again to start attacking again.

**Comment by Moustachos** [comment]
Is it still happening?
