### ISSUE TITLE
Shaman Spell bug: Earthbind Totem

### ISSUE THREAD

**Issue by skorge1** [Valhalla-Gaming/Tracker#1411]
The issue with http://www.wowhead.com/spell=2484/earthbind-totem is that when you use it the totem turns into an http://www.wowhead.com/spell=51485/earthgrab-totem even though you didn't pick the talent.

**Comment by Tregeta** [comment]
@Beponator  

> Earthbind Totem is bugged probably after those uptades and fixes.
http://www.wowhead.com/spell=2484/earthbind-tote

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #2266
