### ISSUE TITLE
Demonic Gateway

### ISSUE THREAD

**Issue by Lisule** [Valhalla-Gaming/Tracker#1462]
http://www.wowhead.com/spell=111771/demonic-gateway  Summons each time i cast it even if i have already the gates summoned, they attack mobs an have Blood pact buffed on them http://www.wowhead.com/spell=166928/blood-pact   , plus they follow me and the animation does not look as it supposed to http://s23.postimg.org/vhhhbkrob/Wo_WScrn_Shot_072415_153554.jpg

**Comment by Tregeta** [comment]
@shadowend
> demonic gate way can be summoned but cant use it or teleport with it .
