### ISSUE TITLE
[Quest] The Tiger Palm

### ISSUE THREAD

**Issue by deadright** [Valhalla-Gaming/Tracker#1471]
Objective: reach level 3, then practice Tiger Strike on a dummy.

I tried this quest for several races, and hitting a dummy with Tiger Strike doesn't register towards finishing the quest.

**Comment by Malae1** [comment]
Can you please tell us which races you have tried?

**Comment by deadright** [comment]
I tried Draenei, Undead, and Gnome.

**Comment by Malae1** [comment]
These areas are unscripted at the moment. The human, orc, night elf, and tauren quests for the particular dummy work fine though.

**Comment by deadright** [comment]
Ah, I see, I did not know that. And in hu-orc-NE-tauro areas, you mean quests in general are better scripted, not only this one, right?

**Comment by Malae1** [comment]
Yes, these areas you should notice a fully scripted experience. There is a slight visual error in our final quest in the tauren area, else all is pristine.

**Comment by deadright** [comment]
Cool!
