### ISSUE TITLE
Paladin Spell - Shield of the Righteous

### ISSUE THREAD

**Issue by sujoy84** [Valhalla-Gaming/Tracker#1472]
How it should work: Instantly slam the target with your shield, causing (200% of Attack power) Holy damage, reducing the physical damage you take by (25 ; Min 25, Max 80)% for 3 sec, and causing Bastion of Glory.
Bastion of Glory (http://www.wowhead.com/spell=114637)
Increases the strength of your Word of Glory when used to heal yourself by 6%. Stacks up to 5 times.

How it works: The spell does damage but it does not cause Bastion of glory to stack upto 5 times.
http://www.wowhead.com/spell=53600/shield-of-the-righteous

**Comment by Moustachos** [comment]
Fixed on update update.

**Comment by Moustachos** [comment]
Ref #2266
