### ISSUE TITLE
Drain Soul bug

### ISSUE THREAD

**Issue by Burag** [Valhalla-Gaming/Tracker#1481]
Link to the spell: http://www.wowhead.com/spell=103103/drain-soul
It should deal an instant dmg of the damage over time spells which dmg is 40% strong  (dots which are already on tha enemy target)but it doesn't do that.It is tha main dmg for an affliciton warlock so pls fix it as soon as possible.

**Comment by Tregeta** [comment]
@erih
> Animation of drain soul is not updated.

**Comment by Collector-Valhalla** [comment]
Indeed. Rarely anyone play as warlock at lvl 100 PvP because of that issue.

**Comment by Tregeta** [comment]
@usernameisalreadytaken
> "If the target dies and yields honor or experience, one Soul Shard is energized."
I didn't get to try it yet on targets that yield honor, but on mobs, you just don't get any soul shard from finishing them off with Drain Soul.
