### ISSUE TITLE
Arcane Charge

### ISSUE THREAD

**Issue by MolmQQ** [Valhalla-Gaming/Tracker#1512]
The Arcane Mage stackable passive effect "Arcane Charge" should only be consumed by the spells "Evocation" and "Arcane Barrage". Right now, EVERY DAMAGING ARCANE SPELL consumes the charges, except the Arcane Charge generator, "Arcane Blast".

http://www.wowhead.com/spell=114664/arcane-charge <--- here's the tooltip, which includes it's synergy with every spell.
Edit:
"Arcane Blast" - the arcane charge generator, works properly.
"Arcane Missiles" - this should add another charge (refresh if max. charges) and have increased damage for each charge. Right now the increased damage part is working and it generates a charge but it consumes every charge AFTER the chanell is over.
http://www.wowhead.com/spell=5143/arcane-missiles

"Arcane Explosion" - should refresh the duration of the arcane charges, with 30% chance to generate another charge IF at least 1 enemy is hit. Now it just consumes the charges.
http://www.wowhead.com/spell=1449/arcane-explosion

That's it, there are bugs with "Arcane Missiles" and "Arcane Barrage" but I'll take them to another issue since this is about the arcane charge system. I can't give feedback about "Evocation" which is the other arcane charge consumer since i didn't managed to learn it yet. xP

Thank you for your work!

**Comment by Malae1** [comment]
Can you please add the exact spells instead of saying the every damage arcane spell? this will help us put the conditions.
