### ISSUE TITLE
Arcane Missiles

### ISSUE THREAD

**Issue by MolmQQ** [Valhalla-Gaming/Tracker#1519]
The Arcane Mage spell "Arcane Missiles" is a 5 wave spellshot to a single enemy. It has a chance to be activated after each of my damaging spell casts, with the limit of 3 charges.
Now comes the bad part -> it's charges are consumed by "Arcane Explosion" , "Arcane Blast" , "Arcane Barrage" , "Frost Nova" , "Cone of Cold" (every damaging mage spell) and even by a single wave of Arcane Missiles IF another wave gave you a charge of the spell before. The last thing I mentioned is another bug, Arcane Missiles waves shouldn't give charges and only one should be consumed when you cast the spell. (Please keep that in mind I'm not talking about ARCANE CHARGES now, but Arcane MISSILES charges)
http://www.wowhead.com/spell=5143/arcane-missiles <-- the spell
http://www.wowhead.com/spell=79683/arcane-missiles <-- the "charge"

Thank you for your work!

**Comment by nuhrii** [comment]
Okay each wave of Arcane Missiles all counting as seperate spell casts so tahts why you are generating missiles charges
