### ISSUE TITLE
Zone: Darkshore  Quest: No Accounting for Taste

### ISSUE THREAD

**Issue by FlameChampion34** [Valhalla-Gaming/Tracker#152]
The quest involves interaction with the Buzbox 413. Upon accepting the quest it does not allow you to harvest the bear corpse as required to complete the quest. My best guess is that a state change, that the server is suppose to acknowledge and apply to the player, isn't happening and thus not allowing the special harvest mechanic.

**Comment by Vemir** [comment]
Quest still broken as of October 7

**Comment by Tregeta** [comment]
fixed next update
