### ISSUE TITLE
Tyr's Hand missing NPCs

### ISSUE THREAD

**Issue by GeneralCaveman** [Valhalla-Gaming/Tracker#1528]
http://www.wowhead.com/npc=46094/huntsman-leopold
http://www.wowhead.com/npc=46092/scarlet-commander-marjhan
http://www.wowhead.com/npc=46096/crusader-lord-valdelmar
http://www.wowhead.com/npc=46093/mataus-the-wrathcaster

These guys seem to be currently not phased/spawned in.

(Rohan has a seperate issue already but I will post it here as well)

http://www.wowhead.com/npc=46095/rohan-the-assassin

**Comment by Malae1** [comment]
Missing

**Comment by Tregeta** [comment]
fixed next update
