### ISSUE TITLE
Quest "Hazzard Disposal" quest mob cannot be attacked

### ISSUE THREAD

**Issue by tribaljet** [Valhalla-Gaming/Tracker#1547]
Quest mob, Winna Hazzard, cannot be attacked upon quest summon item usage.

**Comment by silverjade** [comment]
Around Aug 5th I was able to do this quest (with a druid) but now on Aug 23rd when I tried it with my priest and I'm unable to attack the mob with her. The quest item didn't work either time, but I was able to attack/kill her earlier this month on druid.

**Comment by tribaljet** [comment]
I can confirm that the mob cannot be attacked, only targeted, and the quest item does not trigger the fight.

**Comment by ATalisan** [comment]
Still not working in the manner described above.

**Comment by Cidragon** [comment]
Fix quest was fixed on November 25 changelog.
