### ISSUE TITLE
Quest "Fresh From The Hills" quest items unobtainable

### ISSUE THREAD

**Issue by tribaljet** [Valhalla-Gaming/Tracker#1560]
Quest items Pure Glacier Ice cannot be obtained after attacking Solid Ice NPC object.

**Comment by GeneralCaveman** [comment]
https://github.com/HellscreamWoW/Tracker/issues/1305

**Comment by Guybrush-Hellscream** [comment]
ATM, this quest works. You can kill [Solide Ice](http://www.wowhead.com/npc=49233/solid-ice) and loot [Pure Glacier Ice](http://www.wowhead.com/item=64662/pure-glacier-ice) on it.

BUT it shouldn't work that way. The good way is that you kill Solid Ice and it immediately gives you Pure Glacier Ice in your bag, without looting it. Furthermore, another problem is that Solid Ice is moving when you attack it; it shouldn't.

**Comment by tribaljet** [comment]
It wasn't moving when I last did it so something did change, especially if the item is now obtainable.

**Comment by Cidragon** [comment]
This quest was fixed on November 25th changelog.
