### ISSUE TITLE
Hunter - Arcane Shot - Cost more than 30 focus

### ISSUE THREAD

**Issue by ghost** [Valhalla-Gaming/Tracker#1562]
Proof (.mp4): https://vid.me/bf4Q (Sorry for the bad quality, I was lagging if I didnt get the resolution down to record)

As you can see in the 10 sec video, the spell Arcane Shot cost more than 30 focus to cast, as I spam it (60 for the first and 75-80 for the second).
I don't really understand the circumstances for this bug to happen, but I know that when I dismiss my pet, it doesnt accure anymore and the cost is back to 30 focus. This bug also accured inside an instance (SW's Prison).

I haven't researched any other circumstances of this bug accuring yet, but it's certainly close to game breaking as it's the major damage output of hunters (at least for me)

Note: I am a Human Beast Master Hunter

**Comment by Moustachos** [comment]
Seems to be fixed as of current version.

**Comment by Moustachos** [comment]
Ref #2266
