### ISSUE TITLE
Quest "Invasion Point: Annihilator" quest item bug

### ISSUE THREAD

**Issue by tribaljet** [Valhalla-Gaming/Tracker#1575]
http://www.wowhead.com/quest=10397/invasion-point-annihilator

The quest item Burning Legion Gate Key has the wrong use action, currently requiring an object to be selected for the quest item to be used, whereas its use effect should enable a cast bar upon the required location that would trigger quest completion.

**Comment by GeneralCaveman** [comment]
A separate bug on the same quest. There are quite a few missing visual effects with the legion gate and the surrounding towers 

https://www.youtube.com/watch?v=NXtwxxaj7IM

**Comment by Cidragon** [comment]
Fixed in December 5th changelog
