### ISSUE TITLE
World Area Spell: Mist of the Kvaldir

### ISSUE THREAD

**Issue by Odysseas68** [Valhalla-Gaming/Tracker#1580]
Location:  Riplash Strand (Borean Tundra)
Spell: http://www.wowhead.com/spell=45636/mist-of-the-kvaldir

The normal behavior of this spell is, when you are out of the area and you don't have this spell(buff) you can't see anything inside the area. When you are in and the spell (buff) apply to you you can see the mob's. 
The behavior now is exactly the opposite. When you are out you see the mob's and when you are in you don't and as a result you can't do the quests there (about 10 quests).

**Comment by Malae1** [comment]
For reference: Before into the aura/phase - http://i.imgur.com/4Qoy3nI.jpg
After - http://i.imgur.com/6j5jvZX.jpg

**Comment by Tregeta** [comment]
fixed in next update
