### ISSUE TITLE
Riplash Strand NPC spawn bug

### ISSUE THREAD

**Issue by tribaljet** [Valhalla-Gaming/Tracker#1592]
Several quests are affected by NPCs vanishing at Riplash Strand once the player enter the area and gets the Mist of the Kvaldir buff.

Initial quests affected:
- Karuk's Oath (http://www.wowhead.com/quest=11613/karuks-oath)
- A Father's Words (http://www.wowhead.com/quest=11620/a-fathers-words)

**Comment by Malae1** [comment]
This is a phasing issue.

**Comment by Tregeta** [comment]
fixed in next update
