### ISSUE TITLE
 call pet

### ISSUE THREAD

**Issue by vation1234** [Valhalla-Gaming/Tracker#1601]
hunter
bugged call pet can not remove animals!   
 call pet 1,2,3,4 
http://www.wowhead.com/search?q=call+pet

you need to remove pet animals call, select

**Comment by Malae1** [comment]
What pets do you currently have?

**Comment by Moustachos** [comment]
Invalid report (can't figure out what you mean).

**Comment by Moustachos** [comment]
Ref #2266
