### ISSUE TITLE
Zone: Ghostlands Quest:Investigate the Amani Catacombs

### ISSUE THREAD

**Issue by crohde7707** [Valhalla-Gaming/Tracker#1605]
Similar to the issue for the  [Issue 446](https://github.com/HellscreamWoW/Tracker/issues/466), the "Investigate the Amani Catacombs" quest behaves the same way. You are able to burn all of the mummified trolls, but the moment you reach the area that would fulfill the "Investigate the Amani Catacombs" part of the quest, it resets the quest.

**Comment by Pure-Valhalla** [comment]
Quest has been fixed
