### ISSUE TITLE
Paladin Spell - Seals

### ISSUE THREAD

**Issue by leorherndon** [Valhalla-Gaming/Tracker#1619]
Once I got Seal of Truth, I switched to it. Now I can't switch back to Seal of Command. It shows the Seal of Command animation, but doesn't actually switch.

**Comment by Malae1** [comment]
Once you get Seal of Truth, you no longer should have Seal of Command available. What you're seeing is a display error.

**Comment by leorherndon** [comment]
Also, Seal of Command's holy damage is applied to all nearby enemies.

**Comment by Malae1** [comment]
http://www.wowhead.com/spell=20154/seal-of-righteousness will do the same. Seal of command is obsolete once you get Seal of Truth.
