### ISSUE TITLE
Westfall Brigade Encampment, Grizzly Hills, NPC spawn bug

### ISSUE THREAD

**Issue by tribaljet** [Valhalla-Gaming/Tracker#1645]
There are no NPCs spawned at Westfall Brigade Encampment, including flight master, repair and vendor, questgivers and regular NPCs.
Ref: http://wowwiki.wikia.com/wiki/Westfall_Brigade_Encampment

**Comment by Malae1** [comment]
Ref # 404

**Comment by Tregeta** [comment]
If you do not mind please verify if all of the npcs that were missing is now present.

**Comment by tribaljet** [comment]
Will report back in a few minutes.

**Comment by tribaljet** [comment]
All NPCs are spawned and working as expected. Closing the issue.

**Comment by Tregeta** [comment]
Thanks :smiley_cat:

**Comment by tribaljet** [comment]
Certainly :)
