### ISSUE TITLE
Cant use Teleport in DK starting area

### ISSUE THREAD

**Issue by cainkapow** [Valhalla-Gaming/Tracker#1678]
Created a DK and im upto the quest:The Might of the Scourge. 

I am supposed to sue the teleporter behind the LK to travel downstairs, however, it is not working. Ive tried a relog and a reload but neither worked

**Comment by Malae1** [comment]
Ref #213, #387

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #2266
