### ISSUE TITLE
Riverpaw gnolls in westfall

### ISSUE THREAD

**Issue by Max-Valhalla** [Valhalla-Gaming/Tracker#173]
Now these runts shuldn't be a problem,and they're not its the dmg they deal and thats just waay to much for a lvl 8-9 creature 51-59 dmg pre shot (due to comparison an elite hogger deals about 20-29 dmg and the hogger is lvl 11)

**Comment by Trekex** [comment]
They are now dealing about half the damage. I think it's fixed
