### ISSUE TITLE
Spell Druid - Glyph of Savage Roar

### ISSUE THREAD

**Issue by alexdanila90** [Valhalla-Gaming/Tracker#1797]
Expected Results: When you Rake or Shred while Prowling, you are granted Savage Roar as if it were used with 5 combo points.

Actual Results: No Savage Roar buff granted.

http://www.wowhead.com/spell=127540/glyph-of-savage-roar

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #2266
