### ISSUE TITLE
Glyph of the Stag

### ISSUE THREAD

**Issue by carminejackal** [Valhalla-Gaming/Tracker#1802]
http://www.wowhead.com/item=40900/glyph-of-the-stag

"Your stag form can now be used as a mount by party members.  Travel Form will no longer ever activate flight, and Flight Form is learned as a separate ability."

It doesn't separate flight form from travel form, haven't tested the mount part, but I suspect it doesn't work either. 

Without this working, travel form will turn druids into their flight forms if you can fly in the area, even if the druid wanted the stag (thus the use of the glyph), not the bird/bat.

**Comment by skorge1** [comment]
The mount part of the glyph doesn't work either.

**Comment by Moustachos** [comment]
Ref #2266
