### ISSUE TITLE
Faction reputation mount bug

### ISSUE THREAD

**Issue by tribaljet** [Valhalla-Gaming/Tracker#1882]
Raising reputation to exalted with a different race of the player's does not allow buying target race's mounts due to mount vendor still stating the player needs to be exalted.

**Comment by zhangliaoofwei** [comment]
it just happened to me today: I can't buy mounts from http://www.wowhead.com/npc=4730/lelanai even if I am exalted with darnassus

**Comment by Tregeta** [comment]
Issue is fixed now.
