### ISSUE TITLE
Ghostlands Quests Investigate An'Daroth and Investigate the Amani Catacombs

### ISSUE THREAD

**Issue by Gantian2** [Valhalla-Gaming/Tracker#1887]
Both of these quests seem to suffer from the same issue, part way through getting the required kills or burnt troll mummies the counter simply resets, making the quests incompletable.

**Comment by Pure-Valhalla** [comment]
Quest "Investigate the Amani Catacombs" has been fixed

**Comment by Pure-Valhalla** [comment]
Quests now work
