### ISSUE TITLE
Recap of the monk bugged skills and spells

### ISSUE THREAD

**Issue by mrjhaker400** [Valhalla-Gaming/Tracker#1917]
As i could see, many monk abilities are bugged wich make the class really unpleasant:
1.The jab:work well but the amount of energy required is uncertain sometime it need only 20 but sometimes it needs 80 (i think the problem come from the rate of regen of the energy which shows false values)
2.Stance of the fierce tiger: don't know if it works but never appears to be on
3.Tiger Palm:Don't work at all,it produce souds and anim but no damage.
4.Roll. Works but 1/2times it puts you back where you were before using it(really annoying in pvp)
5.Blackout kick. One of the only spell that works perfectly
6.Surging Mists:Don't work, do sounds and anim but no heal
7.Provoke:Works well
8.Ressucitate:Works well
9.detox: Works well
10.Zen pilgrimage: do the sounds and anim but don't teleport you(so don't work)
11.Touch of death:don't do any damage or anything.
12.Fortifying brew:Works well
13.Expel harm: Works well and serve of heal (because surging mists don't work)
14.Nimble brew:Works well
15.Spear hand strike: Works well
16.Paralysis: Works well
17:Spinning crane kick: launches anim and sounds but no damage (like its evolution Rushing Jade WInds so the monk doesn't got AOE).
18.Transcendance:Don't separate your body and your mind so don't work.
19:Touch of karma:only work for 1 hit and not 6seconds
I would like to say that i listed only my spells and not the one from other specializations and talents .
I would also notice that much glyphs don't work(zen sphere for example)or work even if we don't got them (like the underwater roll or the death roll(wich give us a speed boost while dead wich's a bug))
I hope these bugs will be fixed soon

**Comment by Malae1** [comment]
When reporting issues, if a skill works, you don't need to report it as working. However, if the skill is not working, that is what you should report as well as why it's not working and how it should work.

**Comment by stormriver25885** [comment]
Windwalker's expel harm doesn't work, it heals only 1 HP and the anim is totally the same as flying serpent kick. Both flying serpent kick and expel harm give no dammage at all. All they do is just flying for about 30 yards fast.
