### ISSUE TITLE
DK Spell : Death Grip

### ISSUE THREAD

**Issue by geeorgee** [Valhalla-Gaming/Tracker#1922]
Hey guys!

DK spell Death Grip (http://www.wowhead.com/spell=49576/death-grip). Problem is when i want to use it on caster mob. It doesn´t work. Animation is showed but im not able to pull the mob right to me. It works well on melee mobs or mobs who do not casts.

**Comment by HellscreamWoW** [comment]
Which caster mob did you try to use this spell on?

**Comment by geeorgee** [comment]
Several caster mobs. It doesn´t seems to me that it wont work on just one or few caster mobs but on every caster mob.

**Comment by EPS1L0N** [comment]
You're going to need to be more specific.. It's working fine on this random caster I found
https://www.youtube.com/watch?v=N5jCBVpAA0k

**Comment by geeorgee** [comment]
Twilight Master and Twilight Overlord in Silithus, 

(http://www.wowhead.com/npc=11883/twilight-master)
(http://www.wowhead.com/npc=15213/twilight-overlord)

**Comment by KwitUrBichn** [comment]
https://github.com/HellscreamWoW/Tracker/issues/2104
