### ISSUE TITLE
Frost Death Knight bug [Howling Blast]

### ISSUE THREAD

**Issue by avandarkwalker** [Valhalla-Gaming/Tracker#1954]
Howling Blast www.wowhead.com/spell=49184/howling-blast :does not spread Frost disease to others target except the main target. The proc for Howling Blast is proc by any kind of action or attack made by Frost DK.

**Comment by avandarkwalker** [comment]
Also, I've noticed that the damge is lower than what it should. The damge from Howling Blast is frost damge, so it wouldn't be reduced  by any kind of reduction as far as i've known. Still, i've heard about rumors that Blizz still keep some hidden stats of all Elemental resistances but it can't be possible that all mobs have so high on Elemental resistance like that. 
My DK attack power (AP) is 1267, so my damge from Howling Blast is 1267*116%=1526 and i got 34,67% mastery so it would be 1526*34,67% = 529.0642 increase in Frost damge. Strangely, even with 2055,0642 damge like that, i only crit for 2114 damge and hit for 1k4= damge on mobs. 
Maybe i'm wrong about this, maybe not, but still i think this is worth a notice from you guys :D 
Thank for all of your hard works.

**Comment by Malae1** [comment]
Thanks for the additional info.

**Comment by avandarkwalker** [comment]
np :) it's a shame that i could only do rp about DK because that's the only class that i play as main in WoW

**Comment by Moustachos** [comment]
Ref #2266
