### ISSUE TITLE
Death Knight [Death Pact]

### ISSUE THREAD

**Issue by avandarkwalker** [Valhalla-Gaming/Tracker#1958]
http://www.wowhead.com/spell=48743/death-pact Death Pact only give 25% max HP heal and doesn't add the absorbtion.

**Comment by CorentinDodon** [comment]
Death Pact give 50% HP heal but the problem is the absorption is activated first so 25% of the heal is use to destroy the absorption so there is only 25% heal.
The absorption should be activated after the 50% HP heal

**Comment by Moustachos** [comment]
Fixed on next update.

**Comment by Moustachos** [comment]
Ref #2266
