### ISSUE TITLE
Death Knight [Blood Boil]

### ISSUE THREAD

**Issue by avandarkwalker** [Valhalla-Gaming/Tracker#1961]
Blood Boil http://www.wowhead.com/spell=50842/blood-boil, doesn't spread diseases between targets that got hit by it. Also the stack are not consumed after using Death Strike.

**Comment by Tregeta** [comment]
Copy Paste from @CorentinDodon report.

The stacks given by blood boil are now consumed but they don't increase the healing effect of Death Strike

**Comment by Moustachos** [comment]
Ref #2266
