### ISSUE TITLE
Death Knight tier 4 Talents bug

### ISSUE THREAD

**Issue by avandarkwalker** [Valhalla-Gaming/Tracker#1962]
_T4 talents doesn't seems to work at all. 3 of them actually. That include
Blood Tap http://www.wowhead.com/spell=45529/blood-tap
Runic Empowerment http://www.wowhead.com/spell=81229/runic-empowerment
Runic Corruption http://www.wowhead.com/spell=51462/runic-corruption

**Comment by Tregeta** [comment]
@Collector-valhalla

> http://www.wowhead.com/spell=51462/runic-corruption
I'm not sure what the issue is or is it retail like but with this talent I'm able to easily use 4 obliterates in a row AND my best "score" so far is 10 in a row.
Maybe proc chance is too high?
Also this effect lasts for 5 seconds instead of 3.

**Comment by Moustachos** [comment]
Ref #2266
