### ISSUE TITLE
Death Knight [Might of the Frozen Waste] bug

### ISSUE THREAD

**Issue by avandarkwalker** [Valhalla-Gaming/Tracker#1966]
I discovered that MoTFW didn't make DW hit with both wp but just main one :( Also, When using 2H this spell also increase the damge of Frost Strike to 100% too.

**Comment by KwitUrBichn** [comment]
http://www.wowhead.com/spell=81333/might-of-the-frozen-wastes

**Comment by Moustachos** [comment]
Ref #2266
