### ISSUE TITLE
Death Knight [Death Rune] bug

### ISSUE THREAD

**Issue by avandarkwalker** [Valhalla-Gaming/Tracker#1967]
Death Rune doesn't seems to work at all. It is vital and essential for a DK to have Death Runes, because it would affect alot to our rotations and abilities.
http://www.wowhead.com/spell=54637/blood-of-the-north
http://www.wowhead.com/spell=56835/reaping
these seem to be the problem, because they doesn't exist in the spellbook.

**Comment by avandarkwalker** [comment]
I discoverd that if I changed my spec from primary spec to secondary spec then changed back to primay, which is frost, i gained 2 death runes but i had no way to keep it if I depleted it. In other words, changing spec helps me gain death runes but after using both of them they turn back into blood runes

**Comment by KwitUrBichn** [comment]
https://github.com/HellscreamWoW/Tracker/issues/1353

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #2266
