### ISSUE TITLE
Quest "Investigate An'daroth"

### ISSUE THREAD

**Issue by Grimoslav** [Valhalla-Gaming/Tracker#2001]
Cannot complete quest becouse Investigate An'daroth function can not be completed, no matter how i run around that place and kill all the mobs there. Also for quest we need to kill 12 Sentinel Spy, but if u kill 1 over 12 counter resets and it's bugged.

**Comment by Malae1** [comment]
Getting close the fountain will also reset it.

**Comment by Pure-Valhalla** [comment]
Quest now works.

**Comment by Cidragon** [comment]
This quest is working perfectly now.
