### ISSUE TITLE
Quest "Underlight Ore Samples"

### ISSUE THREAD

**Issue by Grimoslav** [Valhalla-Gaming/Tracker#2002]
Cannot complete quest from Ghostlands where u have to collect 6 Ore Samples even if i collected em and have em in bags.

**Comment by Malae1** [comment]
Why can you not? Missing NPC? the NPC can't be spoken to?

**Comment by Grimoslav** [comment]
Grayed out complete button and no progress at quest tracker.

**Comment by Malae1** [comment]
Personally tested, it is possible to complete the quest, you must have relogged/dc'd during.

**Comment by Tregeta** [comment]
Working now as of the current version
