### ISSUE TITLE
Mob "Oondasta" drop bug

### ISSUE THREAD

**Issue by tribaljet** [Valhalla-Gaming/Tracker#2014]
http://www.wowhead.com/npc=69161/oondasta

The mob Oondasta does not drop any of the 39 possible item drops.

**Comment by Malae1** [comment]
How did you even manage to kill the world boss?

**Comment by tribaljet** [comment]
Mainly preserverance and 70 minutes of fighting :) But seriously, it was a matter of tank and spank.

**Comment by Tregeta** [comment]
Fixed next update
