### ISSUE TITLE
Quest "The Princess Unleashed" - Shards of Myzrael - Arathi Highlands

### ISSUE THREAD

**Issue by Kalae** [Valhalla-Gaming/Tracker#2035]
http://www.wowhead.com/quest=26049/the-princess-unleashed

The quest item "Scroll of Myzrael" doesn't work. It's impossible to summon and defeat Myzrael at the Shards of Myzrael.

**Comment by GeneralCaveman** [comment]
https://github.com/HellscreamWoW/Tracker/issues/722
