### ISSUE TITLE
Dun Morogh - Quest - Decontamination

### ISSUE THREAD

**Issue by Guybrush-VR** [Valhalla-Gaming/Tracker#2067]
Title : Decontamination
Link Wowhead :  http://www.wowhead.com/quest=27635/decontamination

Side : Alliance
Start with : Gaffer Coilspring
End with : Technician Braggle

Why it doesn't work : You are supposed to hop on the Sanitron 500 to launch the process of decontamination but you can't click it. The Sanitron 500 is there but you cannot click it.

Screenshot IG :
![wowscrnshot_082215_005606](https://cloud.githubusercontent.com/assets/13908354/9420754/92a0643e-4869-11e5-9321-d59f71475330.jpg)

**Comment by Doriathrim** [comment]
Works fine
