### ISSUE TITLE
Dun Morogh - Quest - The Arts of a Monk

### ISSUE THREAD

**Issue by Guybrush-Hellscream** [Valhalla-Gaming/Tracker#2068]
Title : The Arts of a Monk
Link Wowhead : http://www.wowhead.com/quest=31138/the-arts-of-a-monk

Side : Alliance
Start with : Xi, Friend to the Small
End with : Xi, Friend to the Small

Why it doesn't work : I need to practice "Tiger Palm" (a monk spell) on a Training Dummy but after trying it on every dummies around the quest giver, i can't manage to get those 2 Tiger Palm. There might be a problem with those dummies since the spell (Tiger Palm) is working.
I didn't try the other "The Arts of a" quests (for other classes) but if there is a problem with those dummies, there might be a problem finishing those quests.

Screenshot IG : 
![wowscrnshot_082215_005726](https://cloud.githubusercontent.com/assets/13908354/9420726/294846b4-4869-11e5-8bc9-3bef726b4d9f.jpg)

**Comment by carminejackal** [comment]
this now works
