### ISSUE TITLE
Dun Morogh - Quest - Down with Crushcog!

### ISSUE THREAD

**Issue by Guybrush-VR** [Valhalla-Gaming/Tracker#2070]
Title : Down with Crushcog!
Link Wowhead : http://www.wowhead.com/quest=26364/down-with-crushcog

Side : Alliance
Start with : Jarvi Shadowstep
End with : Jarvi Shadowstep

Why it doesn't work : On this one, you need to talk to High Tinker Mekkatorque to launch the event but when you talk to him, nothing happens. Thus, you cannot defeat Crushcog because the event doesn't start. Moreover, when you use the item that Jarvi Shadowstep gives you (Orbital Targeting Device), a rabbit appears on the location where you used the item and nothing happens either.

Screenshot IG :
![high tinker](https://cloud.githubusercontent.com/assets/13908354/9420848/cfb9af96-486a-11e5-809e-9f16a2097b9b.PNG)
![wowscrnshot_082215_010833](https://cloud.githubusercontent.com/assets/13908354/9420812/64c45f10-486a-11e5-96a3-d4e787ac524d.jpg)

**Comment by nallak** [comment]
I noticed one thing with this quest,

when i use that Orbital Targeting Device ( that spawns a rabbit) near Tinker Mekkatorque he acctually duz tha motion he need to do when we supposed to kill boss to finish this quest .check pictures 
![wowscrnshot_032716_223752](https://cloud.githubusercontent.com/assets/18104784/14067789/8a90b0d6-f46d-11e5-94f3-7a751ddf98b6.jpg)
![wowscrnshot_032716_223750](https://cloud.githubusercontent.com/assets/18104784/14067788/8a8e35d6-f46d-11e5-9c39-dc915938fd1d.jpg)

maybe you guys can have a look at this script and see in which order all is set up and change the rabbit to lazer pointer ....

Grtz and thnx all for your support

**Comment by Doriathrim** [comment]
Works fine, only weird thing i found, both are higher than 80 (Level speaking)

**Comment by Cidragon** [comment]
> Works fine, only weird thing i found, both are higher than 80 (Level speaking)

This is working as intented.
