### ISSUE TITLE
Dun Morogh - Quest - Missing in Action

### ISSUE THREAD

**Issue by Guybrush-VR** [Valhalla-Gaming/Tracker#2071]
Title : Missing in Action
Link Wowhead : http://www.wowhead.com/quest=26284/missing-in-action

Side : Alliance
Start with : Jessup McCree
End with : Jessup McCree

Why it doesn't work : You need to free some dudes trapped in cages. To free them, you need to attack cages and then they open. Everything goes as planned but when the cage open, the prisonner stands still and nothing happens (they are not count in quest log so it cannot be finished).

Screenshot IG :
![wowscrnshot_082215_005113](https://cloud.githubusercontent.com/assets/13908354/9420766/b50ff886-4869-11e5-8ee9-8319ffb90984.jpg)

**Comment by nallak** [comment]
was doing that "missing in action" quest. 
seems that this one is Bugged and people can't finish this quest, however i could finish this quest. 
Yes some cages r open and cannot be used to finish quest ( maybe check for cooldown on cages) , but there where a few i could use to achiev the 6/6 for this quest.


here is the proof ( check chat window + quest giver he gives me tha follow up ) 

PS this quest should be the next quest after missing in action 
http://www.wowhead.com/quest=26285/get- ... sives-back 

grts

**Comment by Doriathrim** [comment]
Works fine
