### ISSUE TITLE
Dun Morogh - Quest - Finishin' the Job

### ISSUE THREAD

**Issue by Guybrush-VR** [Valhalla-Gaming/Tracker#2072]
Title : Finishin' the Job
Link Wowhead : http://www.wowhead.com/quest=26318/finishin-the-job

Side : Alliance
Start with : Jessup McCree
End with : Jessup McCree

Why it doesn't work : You need to do two things - Slain Boss Bruggor (which is doable) and Detonate trogg tunnel (which is NOT doable). You can't detonate the tunnel because there is no detonator, thus you cannot blow the explosive up. This detonator should be on the ground, at the end of the tunnel.

Screenshot IG :
![wowscrnshot_082215_005346](https://cloud.githubusercontent.com/assets/13908354/9420772/dc563a0e-4869-11e5-873d-36a14e6a0939.jpg)

**Comment by Doriathrim** [comment]
Works fine
