### ISSUE TITLE
Dun Morogh - Quest - Get to the Airfield

### ISSUE THREAD

**Issue by Guybrush-VR** [Valhalla-Gaming/Tracker#2095]
Title : Get to the Airfield
Link Wowhead : http://www.wowhead.com/quest=25998/get-to-the-airfield

Side : Alliance
Start with : Sergeant Bahrum
End with : Commander Stonebreaker

Why it doesn't work : You cannot reach Commander Stonebreaker to finish this quest because you can't hop on the Mathel's Flying Machine. However, if you have a flying mount yourself, you can finish it but low levels (pre-60) can't. This quest leads to more quests so those more quests cannot be achieved when you're under 60.

Screenshot IG : 
![wowscrnshot_082215_115922](https://cloud.githubusercontent.com/assets/13908354/9423522/3ed2820c-48c7-11e5-959a-532f039e8ffb.jpg)

Credits : Max-Hellscream

**Comment by Cidragon** [comment]
Fixed in December 25th changelog.
