### ISSUE TITLE
Death Knight [Frost Presence] bug

### ISSUE THREAD

**Issue by avandarkwalker** [Valhalla-Gaming/Tracker#2102]
http://www.wowhead.com/spell=48266/frost-presence 
Frost presence should give 20% extra runic power whenever a DK regenerate runic power, but it didn't in our server, right now. 
With each rune a DK spends, he will gain 10 rp (runic power) but in Frost Presence he gain 20% extra of that but right now Frost Presence doesn't give that.

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #2266
