### ISSUE TITLE
Death Knight [Death Strike] bug

### ISSUE THREAD

**Issue by avandarkwalker** [Valhalla-Gaming/Tracker#2103]
http://www.wowhead.com/spell=49998/death-strike 
Death Strike doesn't give heal when being parried or dodged.
Death Strike gives heal everytime a DK use it, whether it's dodged or parried, it always gives heal to the DK

**Comment by manic17** [comment]
More info for dodge and parry :

All players now have a 100% chance to hit, 0% chance to be dodged, 3% chance to be parried, and 0% chance to glance, when fighting creatures up to 3 levels higher (bosses included).
Tank specializations receive an additional 3% reduction in chance to be parried, so tank attacks have a 0% chance to be parried vs. creatures up to 3 levels higher.
Creatures 4+ levels higher than you still have a chance to avoid your attacks in various ways, so as to discourage you from attempting to fight enemies that are much stronger than you.
Dual Wielding still imposes a 17% chance to miss, so as to balance it with two-handed weapon use.

**Comment by Moustachos** [comment]
Ref #2266
