### ISSUE TITLE
Holy shock spell dont work

### ISSUE THREAD

**Issue by rokaro** [Valhalla-Gaming/Tracker#2126]
Hi 23.8. i learn holy spec and HOLY SHOCK spell dont do damage and heal...  its only make animation and consume mana.

**Comment by Malae1** [comment]
Ref #1425

**Comment by KHAR05** [comment]
paladin spell HOLY SHOCK is not working properly, it is casting but dont heal or damage the target and do nothing.. please help fix it. thanks.

**Comment by KHAR05** [comment]
paladin spell HOLY SHOCK is not working properly, it is casting but dont heal or damage the target and do nothing.. please help fix it. thanks.

**Comment by EPS1L0N** [comment]
#2266
