### ISSUE TITLE
Teleporter doesn't work

### ISSUE THREAD

**Issue by Max-Valhalla** [Valhalla-Gaming/Tracker#213]
During the level 55 quest The Might of the Scourge [http://www.wowhead.com/quest=12657/the-might-of-the-scourge], the teleporter behind the Lich King should be activated to reach the lower level of the Archerus. Since there is no other path to the NPC to complete the quest, this bug blocks the character from advancing.

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #2266
