### ISSUE TITLE
Wetlands - NPC - Kixxle

### ISSUE THREAD

**Issue by Guybrush-VR** [Valhalla-Gaming/Tracker#2130]
Name : Kixxle
Link Wowhead : http://www.wowhead.com/npc=8305/kixxle
 
Side : Both
Job : Potions & Herbs

What's wrong with him : He is selling the right items but without any limit. There should be limit on those items (for example max 2 Mageroyal) as you can see on wowhead link.
I think it's an important fix because people can just buy plants to upgrade their profession.

Screenshot IG : 
![wetlands - 1](https://cloud.githubusercontent.com/assets/13908354/9429395/dc874e6c-49ce-11e5-9dfd-d6d0ff5ff1b3.PNG)

Note : Similar as another NPC (#2169).

**Comment by Tregeta** [comment]
fixed next update
