### ISSUE TITLE
First Aid - Item - Linen Bandage

### ISSUE THREAD

**Issue by Guybrush-Hellscream** [Valhalla-Gaming/Tracker#2137]
Name : Linen Bandage
Link Wowhead : http://www.wowhead.com/item=1251/linen-bandage
 
Side : Alliance (but probably Horde too)

What's wrong : Linen Bandage should restore 120 health in 6 sec (that's 30 health per sec) but it actually gives FAR more with 1284 health in 6 sec (that's 214 health per sec).

Screenshot IG : 
![wowscrnshot_082315_184811](https://cloud.githubusercontent.com/assets/13908354/9429736/a277ccee-49db-11e5-9da9-75bda056a4c6.jpg)

Note : Same trouble with Silk Bandage (https://github.com/HellscreamWoW/Tracker/issues/492), Heavy Silk Bandage (https://github.com/HellscreamWoW/Tracker/issues/2138) and Mageweave Bandage (https://github.com/HellscreamWoW/Tracker/issues/2143).

**Comment by Tregeta** [comment]
fixed next update

**Comment by GAMMARAYS** [comment]
Fixed.
