### ISSUE TITLE
First Aid - Item - Heavy Silk Bandage

### ISSUE THREAD

**Issue by Guybrush-Hellscream** [Valhalla-Gaming/Tracker#2138]
Name : Heavy Silk Bandage Bandage
Link Wowhead : http://www.wowhead.com/item=6451/heavy-silk-bandage
 
Side : Alliance (but probably Horde too)

What's wrong : Heavy Silk Bandage should restore 1152 health in 6 sec (that's 192 health per sec) but it actually gives FAR more with 11760 health in 6 sec (that's 1960 health per sec).

Screenshot IG : 
![wowscrnshot_082315_185105](https://cloud.githubusercontent.com/assets/13908354/9429749/25868d1e-49dc-11e5-8e38-073294823f06.jpg)

Note : Same trouble with Linen Bandage (https://github.com/HellscreamWoW/Tracker/issues/2137), Silk Bandage (https://github.com/HellscreamWoW/Tracker/issues/492) and Mageweave Bandage (https://github.com/HellscreamWoW/Tracker/issues/2143).

**Comment by Tregeta** [comment]
fixed next update
