### ISSUE TITLE
First Aid - Item - Mageweave Bandage

### ISSUE THREAD

**Issue by Guybrush-Hellscream** [Valhalla-Gaming/Tracker#2143]
Name : Mageweave Bandage
Link Wowhead : http://www.wowhead.com/item=8544/mageweave-bandage
 
Side : Alliance (but probably Horde too)

What's wrong : Mageweave Bandage should restore 1440 health in 6 sec (that's 240 health per sec) but it actually gives FAR more with 14700 health in 6 sec (that's 2450 health per sec).

Screenshot IG : 
![wowscrnshot_082415_010530](https://cloud.githubusercontent.com/assets/13908354/9430632/66bc4fd2-49fd-11e5-86a5-58bf7bc555c9.jpg)

Note : Same trouble with Linen Bandage (https://github.com/HellscreamWoW/Tracker/issues/2137), Silk Bandage (https://github.com/HellscreamWoW/Tracker/issues/492) and Heavy Silk Bandage (https://github.com/HellscreamWoW/Tracker/issues/2138).

**Comment by Tregeta** [comment]
fixed next update
