### ISSUE TITLE
Loch Modan - Quest - Resupplying the Excavation

### ISSUE THREAD

**Issue by Guybrush-VR** [Valhalla-Gaming/Tracker#2147]
Title : Resupplying the Excavation
Link Wowhead : http://www.wowhead.com/quest=13639/resupplying-the-excavation

Side : Alliance
Start with : Jern Hornhelm
End with : Huldar

Why it doesn't work : When you come near Huldar, the quest should finishes itself but it doesn't happen.That means that you can't finish this quest nor get to the next two quests which are "Protecting the Shipment" (http://www.wowhead.com/quest=309/protecting-the-shipment) and "Keep Your Hands Off The Goods!" (http://www.wowhead.com/quest=13650/keep-your-hands-off-the-goods).

Screenshot IG : 
![wowscrnshot_082415_023257](https://cloud.githubusercontent.com/assets/13908354/9431026/e8624f90-4a08-11e5-8c3e-c2399b56f9da.jpg)

Note : If you fix this quest, you can close https://github.com/HellscreamWoW/Tracker/issues/1940 too (same topic).

**Comment by Cidragon** [comment]
Fixed in December 25th changelog.
