### ISSUE TITLE
Loch Modan - Quest - Axis of Awful

### ISSUE THREAD

**Issue by Guybrush-VR** [Valhalla-Gaming/Tracker#2148]
Title : Axis of Awful
Link Wowhead : http://www.wowhead.com/quest=26868/axis-of-awful

Side : Alliance
Start with : Cannary Caskshot
End with : Cannary Caskshot

Why it doesn't work : Two things about this quest. First, you're supposed to get 3 items (Clever Plant Disguise Kit + Potent Murloc Pheromones + Skin of Dwarven Stout) from the Cannary's Cache (http://www.wowhead.com/item=60681/cannarys-cache) that the NPC is giving you. The fact is that the bag is empty. Second thing is that you can get those three items by killing the Mosshide Representative you're supposed to tag for this quest (he shouldn't drop those items). So it might work after all but when you try to throw "Potent Murloc Pheromones" while hiding in "Clever Plant Disguise Kit", the flask is going on you not on the Mosshide (even if you target him). So can't be done atm.

Screenshot IG : 
![wowscrnshot_082415_021553](https://cloud.githubusercontent.com/assets/13908354/9431055/e4a08376-4a09-11e5-8196-1165a4b48850.jpg)
![wowscrnshot_082415_021741](https://cloud.githubusercontent.com/assets/13908354/9431056/e5ca286a-4a09-11e5-9086-371156d1f853.jpg)

Note : You can close https://github.com/HellscreamWoW/Tracker/issues/1938 when this quest is fixed (same issue).
Note 2 : There is also a bug with "Potent Murloc Pheromones" where you still have the visual debuff but you can't get it out even by relogging. It goes off while you die though, a bit like this issue https://github.com/HellscreamWoW/Tracker/issues/2092.
Note 3 : When you abandon this quest, quest items gain from killing Mosshide do not disappear.

Screenshot for Note 2 : 
![wowscrnshot_082415_025055](https://cloud.githubusercontent.com/assets/13908354/9431111/f549d2a8-4a0a-11e5-9254-571774310032.jpg)

**Comment by Cidragon** [comment]
Fixed in December 25th changelog.
