### ISSUE TITLE
Wetlands - Quest - For Peat's Sake

### ISSUE THREAD

**Issue by Guybrush-VR** [Valhalla-Gaming/Tracker#2158]
Title : For Peat's Sake
Link Wowhead : http://www.wowhead.com/quest=25939/for-peats-sake

Side : Alliance
Start with : Ferilon Leafborn
End with : Ferilon Leafborn

Why it doesn't work : You should be able to extinguish fire with "Blessed Floodlilly" but it doesn't work. You can see the animation (some sort of water flood) of this item but it doesn't work ; fire stays still. Another information, there are two types of fire : some with a rabbit in it and some without anything in it. 
This quest, when finished, should lead to "Longbraid the Grim" (http://www.wowhead.com/quest=26196/longbraid-the-grim). So you can't get this quest without finishing this one.

Screenshot IG : 
![wowscrnshot_082415_111737](https://cloud.githubusercontent.com/assets/13908354/9436738/c31303f8-4a51-11e5-96f2-caf14483484c.jpg)
![wowscrnshot_082415_104918](https://cloud.githubusercontent.com/assets/13908354/9436555/890c7c26-4a50-11e5-9c72-5aef8784f199.jpg)
![wowscrnshot_082415_104936](https://cloud.githubusercontent.com/assets/13908354/9436557/89b2cfc2-4a50-11e5-84ec-1d1bdeb5e4c3.jpg)

Note : You can close https://github.com/HellscreamWoW/Tracker/issues/601 and https://github.com/HellscreamWoW/Tracker/issues/1774 when you've fixed this quest (same trouble).

**Comment by GeneralCaveman** [comment]
https://github.com/HellscreamWoW/Tracker/issues/601

**Comment by Seregruth** [comment]
Fixed next update.
