### ISSUE TITLE
Arathi Highlands - Quest - The Princess Unleashed

### ISSUE THREAD

**Issue by Guybrush-Hellscream** [Valhalla-Gaming/Tracker#2160]
Title : The Princess Unleashed
Link Wowhead : http://www.wowhead.com/quest=26049/the-princess-unleashed

Side : Alliance
Start with : Skuerto
End with : Shards of Myzrael

Why it doesn't work : You should use "Scroll of Myzrael" close to Shards of Myzrael but it doesn't work. When you get close, you can see the beginning of "Scroll of Myzrael" animation but it instantly stops and it's written "Requires Shards of Myzrael". So I assume the trouble lies within the Shards itself.

Screenshot IG : 
![wowscrnshot_082315_173459](https://cloud.githubusercontent.com/assets/13908354/9436916/34efb506-4a53-11e5-89d1-fb7a0b8f833e.jpg)

Note : You can close https://github.com/HellscreamWoW/Tracker/issues/722 and https://github.com/HellscreamWoW/Tracker/issues/2035 when you've fixed it (same issue).

**Comment by GeneralCaveman** [comment]
https://github.com/HellscreamWoW/Tracker/issues/722

**Comment by Pure-Valhalla** [comment]
horde version 
http://www.wowhead.com/quest=26912/the-princess-unleashed


Tested on both factions and quest has been fixed.
