### ISSUE TITLE
Druid:(restoration)   [Wild Mushroom] 

### ISSUE THREAD

**Issue by vation1234** [Valhalla-Gaming/Tracker#2161]
Bugged
Do not operate heal all full.
http://www.wowhead.com/spell=145205/wild-mushroom#comments

All people need to heal life
Video
https://www.youtube.com/watch?v=iXC9GESmCHA

**Comment by vation1234** [comment]
Please fix   when???

**Comment by skorge1** [comment]
Does not heal at all with or without glyph. http://www.wowhead.com/item=104102/glyph-of-the-sprouting-mushroom

**Comment by skorge1** [comment]
The wild mushroom doesn't slow when in balance spec.

**Comment by Tregeta** [comment]
@serenity-talador

> http://www.wowhead.com/spell=88747/wild-mushroom It target ennemy in it range , even bugued npc that dont bother you normaly (especialy when you cant kill them) and work against A2 to It just hit in close combat

**Comment by Tregeta** [comment]
@tribaljet

> When a Balance Druid casts this spell, multiple Wild Mushrooms can be spawned and a player for the opposing faction that isn't flagged for PvP can get flagged when getting in (aggro) range. This flagging issue seems to happen in the event the opposing faction player reflects damage.

**Comment by Moustachos** [comment]
Ref #2266
