### ISSUE TITLE
The Hinterlands - Quest - Rescue OOX-09/HL!

### ISSUE THREAD

**Issue by Guybrush-Hellscream** [Valhalla-Gaming/Tracker#2164]
Title : Rescue OOX-09/HL!
Link Wowhead : http://www.wowhead.com/quest=836/rescue-oox-09-hl

Side : Both
Start with : Homing Robot OOX-09/HL
End with : Oglethorpe Obnoticus

Trouble : When you take this quest, it finishes itself before even escorting the ol' chicken. So you can finish this quest without escorting him (screenshot 1).
About the escort, i tried to follow him and here is what happened (in second screenshot). This is the old route for this NPC, he shouldn't do that anymore. Instead, he should do half the travel he is doing actually (third screenshot). Moreover, when i escorted him, i fought around 4 waves of Moonkin and 1 wave of troll. Instead, i should have fought one wave of Moonkin only.

Screenshot IG : 
![wowscrnshot_082415_151133](https://cloud.githubusercontent.com/assets/13908354/9444045/bb4116f0-4a84-11e5-878a-f3d2dba611a3.jpg)
![the hinterlands - 2](https://cloud.githubusercontent.com/assets/13908354/9444477/4d99ad4e-4a87-11e5-8047-d6fad887cbf0.png)
![the hinterlands - 3](https://cloud.githubusercontent.com/assets/13908354/9444478/4efac3d0-4a87-11e5-930b-d01024280835.png)

**Comment by fipsi10** [comment]
It works fine now! After you take it to the coast he will disappear and goes to Booty Bay. I went to Booty Bay and finished the quest successfully.
