### ISSUE TITLE
Duskwood - NPC - Kzixx

### ISSUE THREAD

**Issue by Guybrush-Hellscream** [Valhalla-Gaming/Tracker#2169]
Name : Kzixx
Link Wowhead : http://www.wowhead.com/npc=3134/kzixx
 
Side : Both
Job : Rare Goods

What's wrong with him : He is selling the right items but without any limit. There should be limit on those items (for example max 3 Healing Potions) as you can see on wowhead link.

Screenshot IG : 
![duskwood - 1](https://cloud.githubusercontent.com/assets/13908354/9447178/4b067396-4a96-11e5-816a-0e0bdf64f591.PNG)

Note : Similar as another NPC (#2130).

**Comment by Tregeta** [comment]
fixed
