### ISSUE TITLE
Paladin Holy Shield talent bug

### ISSUE THREAD

**Issue by tribaljet** [Valhalla-Gaming/Tracker#2180]
The Holy Shield talent is supposed to deal 2.272 holy damage to attackers but it's currently giving 1 damage alone.

**Comment by Luminescent-Hellscream** [comment]
Holy shield seems to be working ok atm deals more damage than 1 that's for sure.

**Comment by Moustachos** [comment]
Holy Shield deals the appropriate amount of damage as of current version.

**Comment by Moustachos** [comment]
Ref #2266
