### ISSUE TITLE
Magistrate Burnside

### ISSUE THREAD

**Issue by GeneralCaveman** [Valhalla-Gaming/Tracker#2199]
http://www.wowhead.com/npc=47790/magistrate-burnside

Approaching this NPC has this happen.

![wowscrnshot_082515_233059](https://cloud.githubusercontent.com/assets/12555606/9484994/55f16cde-4b81-11e5-91ea-680b6db7db81.jpg)

**Comment by Tregeta** [comment]
fixed next update
