### ISSUE TITLE
Blink glitch

### ISSUE THREAD

**Issue by GeneralCaveman** [Valhalla-Gaming/Tracker#2225]
http://www.wowhead.com/spell=1953/blink

It seems like at times, when you blink, you enter the terrain (under the map, in a hill, etc). I only noticed it happens with inclined surfaces but I am not 100% certain.

**Comment by GeneralCaveman** [comment]
I can do it pretty consistently. I have the glyph of blink on this toon if that is currently working.

![wowscrnshot_082715_205404](https://cloud.githubusercontent.com/assets/12555606/9536766/e001482c-4cfd-11e5-9cf4-1aa095cd5034.jpg)

Stand about here, face the vaults (towards the small wooden stairs in particular. Just blink and you will end up about here.

![wowscrnshot_082715_205412](https://cloud.githubusercontent.com/assets/12555606/9536785/15ba23f8-4cfe-11e5-8a1a-70e682067610.jpg)

**Comment by zwei7** [comment]
Yes I blinked in Fargodeep mines and I blinked through the floor and fell into the centre of the world....of Warcraft.
Me looking at the surface of the world from hell.
![wowscrnshot_120815_162119](https://cloud.githubusercontent.com/assets/15259298/11668985/3b2a9a1c-9dc8-11e5-9088-2e5a935f7848.jpg)

Still falling
![wowscrnshot_120815_162122](https://cloud.githubusercontent.com/assets/15259298/11668996/42368d3e-9dc8-11e5-9d32-3017306f4198.jpg)

Falling stops at this point
![wowscrnshot_120815_162123](https://cloud.githubusercontent.com/assets/15259298/11669016/50270446-9dc8-11e5-91fe-9e289eff1b2b.jpg)
