### ISSUE TITLE
Infernal Untargetable Creatures

### ISSUE THREAD

**Issue by Odysseas68** [Valhalla-Gaming/Tracker#2240]
At Townlong Steppes (65,51) "Fire Camp Osul" there are about 100 mob's like rock frozen.They don't do anything. I have take a screen shot but i don't know how to upload it. I don't know if this is a bug, but i see the same type of mob's in different size's all over the world.

**Comment by Odysseas68** [comment]
Found a similar creature 

http://www.wowhead.com/npc=19261/infernal-warbringer#screenshots

**Comment by Tregeta** [comment]
Fixed next update
