### ISSUE TITLE
Death Knight Spell: Improved Frost Presence

### ISSUE THREAD

**Issue by llamalama** [Valhalla-Gaming/Tracker#2242]
http://www.wowhead.com/spell=50385/improved-frost-presence

This should be showing up in the spell book but it is not.
Its effect is partly broken. It only reduces the cost of Frost Strike until you go though a loading screen. It will work correctly again if you relog or switch your presence to a different one and back.

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #2266
