### ISSUE TITLE
Druid Spell: Travel Form

### ISSUE THREAD

**Issue by llamalama** [Valhalla-Gaming/Tracker#2269]
http://www.wowhead.com/spell=783/travel-form

When you enter or exit the water it should automatically switch you to the right shapeshift but it is instead canceling so you have to reapply it.

Also, while swimming indoors, it should allow you to use its aquatic version but it gives the error that it can only be used outside.

**Comment by EPS1L0N** [comment]
can you give me an example of somewhere indoors that you're supposed to be able to use aquatic form

**Comment by llamalama** [comment]
There's a deep pool of water in the cave leading to Wailing Caverns in Northern Barrens.

**Comment by Moustachos** [comment]
Ref #2266
