### ISSUE TITLE
Mage Pet Spell: Growl

### ISSUE THREAD

**Issue by Odysseas68** [Valhalla-Gaming/Tracker#2280]
I noticed that I have 1 more spell from the generic hunter's pet spells called "Growl" http://www.wowhead.com/spell=2649/growl

**Comment by Odysseas68** [comment]
The Water jet ability is ok now to my pet spells but i notice that i have 1 more spell from the generic hunter's pet spells called "Growl" http://www.wowhead.com/spell=2649/growl

**Comment by Malae1** [comment]
Updated comment to reflect recent changes.
