### ISSUE TITLE
Draenor:Professions

### ISSUE THREAD

**Issue by vation1234** [Valhalla-Gaming/Tracker#2305]
Draenor Professions upon learning from their respective item/quest should teach you a set of skills to use. These can be used to level from 1. Currently they are missing these crafts. This goes for all crafting professions (cooking, first aid, blacksmithing, engineering, tailoring, enchanting, leatherworking, alchemy, jewelcrafting, and inscription).

**Comment by Malae1** [comment]
Not enough information, Please tell us more.

**Comment by Malae1** [comment]
Updated original post.

**Comment by Tregeta** [comment]
fixed
