### ISSUE TITLE
glyph chasing

### ISSUE THREAD

**Issue by blazerhoff** [Valhalla-Gaming/Tracker#2308]
http://www.wowhead.com/quest=8309/glyph-chasing  the stone doesnt reacting.

**Comment by zwei7** [comment]
Same problem. Clicking the text option won't do anything.
![wowscrnshot_120215_220009](https://cloud.githubusercontent.com/assets/15259298/11550725/684e4dcc-9940-11e5-893f-948ba936990b.jpg)

**Comment by Cidragon** [comment]
This quest has been fixed on November 25 changelog.
