### ISSUE TITLE
Winterspring - Quest - Turning the Earth

### ISSUE THREAD

**Issue by Guybrush-VR** [Valhalla-Gaming/Tracker#2310]
Title : Turning the Earth
Link Wowhead : http://www.wowhead.com/quest=28615/turning-the-earth

Side : Both
Start with : Tanrir
End with : Tanrir

Why it doesn't work : You have to use [Tanrir's Overcharged Totem](http://www.wowhead.com/item=64637/tanrirs-overcharged-totem) on Winterfall Earth Totem but you don't get credit for it. You can see the item animation but it doesn't work. Furthermore, you char is stuck with the item animation, it only vanishes when you relog.

Screenshot IG : 
![wowscrnshot_090115_105040](https://cloud.githubusercontent.com/assets/13908354/9605163/59d71c0a-50bc-11e5-985d-35607b557cc0.jpg)
![wowscrnshot_090115_105321](https://cloud.githubusercontent.com/assets/13908354/9605174/6dd89a08-50bc-11e5-8d7d-8084a1581474.jpg)

**Comment by Cidragon** [comment]
This quest was fixed on November 25th changelog.
