### ISSUE TITLE
Winterspring - Quest - The Ruins of Kel'Theril

### ISSUE THREAD

**Issue by Guybrush-VR** [Valhalla-Gaming/Tracker#2311]
Title : The Ruins of Kel'Theril
Link Wowhead : http://www.wowhead.com/quest=28479/the-ruins-of-keltheril

Side : Both
Start with : Kelek Skykeeper
End with : Kaldorei Spirit

Why it doesn't work : [Kaldorei Spirit](http://www.wowhead.com/npc=48658/kaldorei-spirit) is not spawned thus you cannot return the quest.

Screenshot IG : 
![wowscrnshot_090115_133705](https://cloud.githubusercontent.com/assets/13908354/9605349/70c01f1a-50bd-11e5-9847-c08fcbb91fec.jpg)

**Comment by Cidragon** [comment]
This quest was fixed on November 25th changelog.
