### ISSUE TITLE
Warlock spells: Immolation Aura, Wild Imps and Summon Felguard

### ISSUE THREAD

**Issue by Ssikari** [Valhalla-Gaming/Tracker#2312]
Hello
I'm a level 44 Demonology Warlock Goblin and I found three spells that are not working as intended.

Immolation Aura: This spells is not doing any damage at all
![wowscrnshot_090115_120933](https://cloud.githubusercontent.com/assets/14076134/9608063/7d9642a0-509a-11e5-9c33-6a44623e3393.jpg)
As you can see I have the aura (4 seconds left) and the wolf is still undamaged!

Wild Imps: I've been wandering through the change log and it said it was scripted, indeed it is, the Imps now spawns when you have the passive up, but they don't attack.
![wowscrnshot_090115_122451](https://cloud.githubusercontent.com/assets/14076134/9608422/3f06236e-509c-11e5-9a5b-75ae009dc54f.jpg)

They walk next to the enemy and stand still without casting any fireball, leaving them useless and really mean because they aggro a lot and I end up being marked as "In Combat" which, yeah, is mean. I also managed to see one of the Imps casting a fireball once, on Stranglethorn Vale, but never happened again.

Summon Felguard: Unlike the Low-level imp bug, you summon him and nothing happens, you can hear him saying "Who dare to summon me" but he never appears, not a visual bug since I'm not getting a his "Pet window" in my spellbook and he's not doing damage to enemies, he's just... not summoned.

Hope this info can help :)
Thank you!

**Comment by Malae1** [comment]
To get the imps to attack you need to right click with your cursor.

**Comment by Guybrush-Hellscream** [comment]
Should i put Wild Imps in the Tracker then? Because it was [fixed](http://www.hellscream-wow.com/log#2015.29.08.020000).

**Comment by Starlords** [comment]
Ok I've tested a bit more about the Wild Imps and found out that while holding a wand it bugs the Wild Imps, they stop atacking! I've tryed a sword, a dagger and a staff, all worked.

**Comment by Tregeta** [comment]
Update: Wild Imps are taking the place of the current demon instead of being a guardian.

**Comment by taiki3ro** [comment]
Hello everyone,

I didn't see any post in the Warlock Spell tracker about the Hand of Gul'Dan skill and this is the only post related somehow to my problem. If necessary, I will get a printscreen but there's not much too see because: the skill is casted, takes away the shards but does no damage and also does not summon the imps. I tried on both my PC and laptop and it does the same.
