### ISSUE TITLE
Priest Atonement Spell

### ISSUE THREAD

**Issue by Lorelai-Hellscream** [Valhalla-Gaming/Tracker#2322]
Figured this would have been reported already because it's a rather big one, but I guess either I'm the first to stop being lazy, or I can't figure out how the search function works on this thing.  The Discipline Priest's Atonement Spell (Spell ID 81749) (http://www.wowhead.com/spell=81749/atonement) doesn't work.  At all.

**Comment by Lorelai-Hellscream** [comment]
sdlkjfsdlkfjseklf  Okay, so there's already an open issue report about this.  It's just that it's labelled "Disciplin" bugs.  Or something to that effect.  So yeah.  Yay for typos.

**Comment by Malae1** [comment]
Sad batman is sad :cry: Thanks for the info and for the laughs of batman.

**Comment by Guybrush-Hellscream** [comment]
I didn't have this spell in my tracker, so either i missed the topic you're talking about or either people are indeed lazy :dancer:

**Comment by Lorelai-Hellscream** [comment]
Guybrush,
Here's a link to the open issue including all the listed spells:  https://github.com/HellscreamWoW/Tracker/issues/1007

**Comment by Guybrush-Hellscream** [comment]
Alright, thank you man, i'll update it with these informations as soon as I can! :)

**Comment by Moustachos** [comment]
Ref #2266
