### ISSUE TITLE
NPC - Krogo Darkhide lacks his LW recipes 

### ISSUE THREAD

**Issue by carminejackal** [Valhalla-Gaming/Tracker#2350]
http://www.wowhead.com/npc=64054/krogo-darkhide

This NPC sells Leatherworking patterns for blue-quality ilvl 450 PvP gear (Season 12).
Each of these patterns are purchased with 1x  Spirit of Harmony.

He has the trade goods/lw regents, but no recipes.

**Comment by Tregeta** [comment]
fixed next update
