### ISSUE TITLE
Rogue Slice & Dice and Blade Flurry

### ISSUE THREAD

**Issue by Cyuty** [Valhalla-Gaming/Tracker#2353]
I had a look and dident find it beeing put here, if it is i'am sry.Here i go:
While Slice and dice or Blade flurry is active the energy cost of all spell are with 20 energy more.
Ex:Sinister strike cost 70 instead of 50.

**Comment by Tregeta** [comment]
@Aveta

> 

http://www.wowhead.com/spell=5171/slice-and-dice
Doesn't grant the energy like it's supposed to.

**Comment by Moustachos** [comment]
Ref #2266
