### ISSUE TITLE
{Quest} Vessels of Power

### ISSUE THREAD

**Issue by Luminescent-Valhalla** [Valhalla-Gaming/Tracker#2359]
the following quest Vessels of Power can not be completed as the items required can not be picked up as you are not able to interact with them.

http://www.wowhead.com/quest=10028/vessels-of-power

**Comment by silverjade** [comment]
I just completed this quest on my alliance druid. There are some items that can't be picked up, but there are plenty of others that can be looted.

**Comment by Malae1** [comment]
So, some of these objects can be interacted with, while a few of them cannot?

**Comment by silverjade** [comment]
Yeah. Some look like the quest object but lack the glow the others have and you can't interact with them.

**Comment by Cidragon** [comment]
This quest is working as intented, not every vessels should be looteable.

relevant comment on wowhead:
"SIMPLE VERSION:
Fly around this zone and hover your mouse over the jar.
If it just says 'Draenei Vessel' its FAKE.
If it says 'Draenei Vessel: x/8' It's REAL."
