### ISSUE TITLE
Spirit Bond

### ISSUE THREAD

**Issue by Redrian-Hellscream** [Valhalla-Gaming/Tracker#2367]
http://www.wowhead.com/spell=109212/spirit-bond simply doesn't work as talent, the hunter and the pet don't get any benefit from it since the effect doesn't apply.

**Comment by Collector-Hellscream** [comment]
It also decrease spirit by 4 points. Seriously.

**Comment by zwei7** [comment]
Having the same problem. 1st world problems.

**Comment by Moustachos** [comment]
Ref #2266
