### ISSUE TITLE
couple of quests

### ISSUE THREAD

**Issue by blazerhoff** [Valhalla-Gaming/Tracker#2371]
http://www.wowhead.com/quest=313/forced-to-watch-from-afar
the npc's doesnt react about the escaping or anything

**Comment by Guybrush-Hellscream** [comment]
"Beer Basted Boar Ribs" > You can get Rhapsody from Loch Modan inn, that's a long way from Kharanos but that's doable!

"Force to Watch From Afar" > #1934, #2075

**Comment by Doriathrim** [comment]
works fine
