### ISSUE TITLE
Flame Shock + Lava Burst

### ISSUE THREAD

**Issue by omnira** [Valhalla-Gaming/Tracker#2378]
Flame shock should increase dmg of Lava Burst by 50%
http://www.wowhead.com/spell=51505/lava-burst

**Comment by Emeraldream** [comment]
Plz fast rework of that think, shaman is so useless without that spell

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #2266
