### ISSUE TITLE
Deadly Throw

### ISSUE THREAD

**Issue by Cyuty** [Valhalla-Gaming/Tracker#2384]
Bug: it does insane dmg like 11-15k crits,is instant cast instead of 0.5 sec and it consume energy more like Shuriken toss but not using talent.

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/spell=26679/deadly-throw

**Comment by Cyuty** [comment]
OMG sry i just sow that i write deadly trow, i did a mistake pls if someone can rename title is not Deadly trow is Trow normal.

**Comment by coba999** [comment]
Did not work well. Skill deals 1 damage.

**Comment by Moustachos** [comment]
Ref #2266
