### ISSUE TITLE
Revealing strike

### ISSUE THREAD

**Issue by Cyuty** [Valhalla-Gaming/Tracker#2385]
I tested alot of time's but that 25% chanse to generate one more combo with sinister strike while is active dosent happen.Instead of 2 CB it shoed be 3CB from time to time with revealing strike active.

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/spell=84617/revealing-strike (Rogue spell)

**Comment by Hangun** [comment]
This information not correct so i think should close it. sinister strike give only 1 combo point so if proc with revealing strike it will have chance to give one more combo point

**Comment by Moustachos** [comment]
Revealing Strike effect on Sinister Strike wasn't scripted, it will be fixed on next update.

**Comment by Moustachos** [comment]
Ref #2266

**Comment by Moustachos** [comment]
Ref #2266
