### ISSUE TITLE
[Priest Spell] Power Word: Shield

### ISSUE THREAD

**Issue by phikaro** [Valhalla-Gaming/Tracker#2388]
Issue is when I use the spell and buff my character, then point with my mouse arrow on the shield icon at the upper right corner, and the tooltip appears, it shows how much damage remains to absorb, but it never counts the remaining absorption. For example it stays on 125 even after I have been attacked, it does absorb it though, it's just the visual glitch that needs to be fixed.

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/spell=17/power-word-shield

**Comment by GAMMARAYS** [comment]
Fixed.
