### ISSUE TITLE
Paladin Spell - Word of Glory

### ISSUE THREAD

**Issue by leorherndon** [Valhalla-Gaming/Tracker#2395]
Word of Glory is now only consuming 1 holy power per use regardless of how many you have.

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/spell=85673/word-of-glory

**Comment by zwei7** [comment]
For me, Word of Glory is consuming all my holy stacks available. If I have 1 holy stack it heals me for the same amount as if I had all holy stacks.

**Comment by EPS1L0N** [comment]
#2266
