### ISSUE TITLE
(QUEST) Wanted: The Demon Hunter

### ISSUE THREAD

**Issue by jfdaigle** [Valhalla-Gaming/Tracker#2414]
Speaking to Feronas Sindweller only gives multiple quests.... No dialog to trigger the attack.

http://www.wowhead.com/quest=28217/wanted-the-demon-hunter
https://www.youtube.com/watch?v=TPbcEDvQ7_o

**Comment by Cidragon** [comment]
Fix quest was fixed on November 25 changelog.
