### ISSUE TITLE
Instance "Naxxramas" area access bug

### ISSUE THREAD

**Issue by tribaljet** [Valhalla-Gaming/Tracker#2416]
After killing all bosses of all quarters in instance Naxxramas, the portal that leads to the final area with boss Sapphiron and boss Kel'Thuzad does not work.

**Comment by serenity-talador** [comment]
work :)

**Comment by carminejackal** [comment]
You're now able to go to the final area and kill the final bosses after clearing the other bosses of Naxx. On both 10 & 25 man.

**Comment by tribaljet** [comment]
Indeed :)

Closed.
