### ISSUE TITLE
[Class] DisciplinePriest spell "Spectral Guise" Talent/Spell

### ISSUE THREAD

**Issue by phikaro** [Valhalla-Gaming/Tracker#2417]
The issue is that when I use it and my character becomes shadow, but my character's true form is following me around, while my true form should stay on one place.

http://www.wowhead.com/spell=112833/spectral-guise

**Comment by Malae1** [comment]
To further add, Spectral Guise creates a stationary "shadow clone" of yourself that does not move, placing the priest in an invisible state to move away from harm. If the "clone" is killed, it will bring the player outside of it's invisible state. In addition, the player can use this to escape combat if moves far enough away while the "clone" still lives (this does not apply to boss battles in raids/instances).

**Comment by EPS1L0N** [comment]
#2266
