### ISSUE TITLE
[Quest] Gurf's Dignity

### ISSUE THREAD

**Issue by phikaro** [Valhalla-Gaming/Tracker#2442]
The glitch with this quest is, that it shows wrong location on map for the npc to which you have to turn it in.

http://www.wowhead.com/quest=9564/gurfs-dignity

**Comment by ATalisan** [comment]
I get a message of: You do not meet the requirements for this quest.
As a level 16 Draenei Holy Priest

**Comment by Tregeta** [comment]
For this quest to be available, all you have to do is walk up to Gruf, and pick up "Murlocs... why here? Why now?"

**Comment by ATalisan** [comment]
I had the quest: Murlocs... Why Here? Why Now? in my log and completed
(As the Gurf's Dignity item drops from the named murloc out there)
It wouldn't allow me to accept the Gurf's Dignity quest until I completed the other one

**Comment by carminejackal** [comment]
I did both the Murlocs quest and the Beasts of the Apocalypse! (ravager quest) and couldn't accept the quest from the item on my draenei paladin tonight.

**Comment by Tregeta** [comment]
Will be rectified next update.
