### ISSUE TITLE
Unleash Elements (Enhancement)

### ISSUE THREAD

**Issue by Xondas** [Valhalla-Gaming/Tracker#2446]
http://www.wowhead.com/spell=73680/unleash-elements

Doesn't Work. 40% Fire spell damage not working and 60% atack speed not working. Doesn't do damage.

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/spell=157784/enhanced-unleash

**Comment by Xondas** [comment]
60% atack speed working now.

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #2266
