### ISSUE TITLE
Druid Spell: Ysera's Gift

### ISSUE THREAD

**Issue by llamalama** [Valhalla-Gaming/Tracker#2467]
http://www.wowhead.com/spell=145108/yseras-gift

Currently if you are near anything friendly that is pvp flagged and is at less than 100% health, this spell will auto heal them. This is only meant to happen while the druid is already pvp flagged but it is happening anyway, making the druid pvp flag involuntarily.

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #2266
