### ISSUE TITLE
[Quest][Ashenvale] King of the Foulweald

### ISSUE THREAD

**Issue by BraynStorm** [Valhalla-Gaming/Tracker#2490]
http://www.wowhead.com/quest=6621
'Foulweald Totem Mound'  object isn't spawned, should be here:  ![Foulweald Totem Mound](http://wow.zamimg.com/uploads/screenshots/normal/23694.jpg)

**Comment by zwei7** [comment]
Instead we get this fail pic saying we need a mound.
![wowscrnshot_103015_010316](https://cloud.githubusercontent.com/assets/15259298/10838816/56169ac8-7ea2-11e5-8190-981fe0bf3b13.jpg)
