### ISSUE TITLE
Druid - Shifting issues (Travel form > Any other form besides Caster/humanoid)

### ISSUE THREAD

**Issue by carminejackal** [Valhalla-Gaming/Tracker#2502]
You're supposed to be capable of shifting directly to cat (or bear) from Travel form (flight). Currently you must unshift out of Travel form (Flight) to caster and then to cat or bear form. Also a druid clicking on a flight master should automatically be unshifted out of the form he's in upon opening the flight point map and clicking the flight point to travel to.

Currently it gives the error "You are in Shapeshift form." when you attempt to go directly to cat / bear or trying to take a flight while currently in travel form (flight). However, I was capable of going from Travel Form (swimming) directly into Cat form with no problems.

**Comment by silverjade** [comment]
update: if you're right next to the ground you can go kitty from flight form, but if yer up in the air it gripes you're in shapeshift form and won't let you shift outta flight form

**Comment by Moustachos** [comment]
Ref #2266
