### ISSUE TITLE
[Quest] Threat From Above

### ISSUE THREAD

**Issue by carminejackal** [Valhalla-Gaming/Tracker#2505]
http://www.wowhead.com/quest=11096/threat-from-above
https://www.youtube.com/watch?v=xO7FyzT3sC8

There are no mobs anywhere in sight in the quest area (Barrier Hills). Thus you can't complete the quest.

**Comment by silverjade** [comment]
These are the npc you have to kill:
http://www.wowhead.com/?npc=22144
http://www.wowhead.com/?npc=22143
http://www.wowhead.com/?npc=22148

70-71 elites should be patrolling the area as well ( http://www.wowhead.com/?npc=23022 )

**Comment by Cidragon** [comment]
There are creatures on the area now :)
