### ISSUE TITLE
[Priest] Mind Blast/Devouring Plague visual Bug

### ISSUE THREAD

**Issue by carminejackal** [Valhalla-Gaming/Tracker#2523]
![wowscrnshot_091515_085947](https://cloud.githubusercontent.com/assets/13601831/9878457/6869f914-5b88-11e5-97e3-157da076f94b.jpg)

Mind Blast is showing as generating 2 orbs instead of just the one that it does actually generate. Also Devouring Plague is showing itself ready to cast when it shows 3 orbs, but in reality you just have 2 orbs and you have to cast Mind Blast again for a 3rd before D.Plague can be cast.

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/spell=8092/mind-blast
http://www.wowhead.com/spell=2944/devouring-plague

**Comment by EPS1L0N** [comment]
#2266
