### ISSUE TITLE
[Rogue] Bandit's Guile

### ISSUE THREAD

**Issue by Aveta** [Valhalla-Gaming/Tracker#2530]
http://www.wowhead.com/spell=84654/bandits-guile
The passive doesn't work at all. No buffs/visuals are applied and I don't see a difference in damage either.

**Comment by Hangun** [comment]
I think this skill should be set to high priority skill. When eviscerate of rogue fixed rogue now deals very low damage so this skill should work. It will make balance between class

**Comment by Moustachos** [comment]
Ref #2266
