### ISSUE TITLE
[Priest] Shadowy Apparitions 

### ISSUE THREAD

**Issue by carminejackal** [Valhalla-Gaming/Tracker#2532]
[Shadowy Apparitions](http://www.wowhead.com/spell=78203/shadowy-apparitions)

This currently appears to not work. It's supposed to work as stated below; yet when my sw: pain crits, nothing happens.

When your Shadow Word: Pain damage over time critically strikes, you also create a shadowy version of yourself that floats towards the target and deals (45% of Spell power) Shadow damage.

**Comment by Moustachos** [comment]
Fixed on next update.

**Comment by Moustachos** [comment]
Ref #2266

**Comment by Moustachos** [comment]
Fixed on next update.

**Comment by Moustachos** [comment]
Ref #2266
