### ISSUE TITLE
A Father's Words

### ISSUE THREAD

**Issue by DeathQueen** [Valhalla-Gaming/Tracker#2533]
http://www.wowhead.com/quest=11620/a-fathers-words
Borean Tundra - Northrend

Veehja is not there, the whole zone is not scripted

**Comment by Malae1** [comment]
Phase issue.

**Comment by Guybrush-Hellscream** [comment]
Yes, because of https://github.com/HellscreamWoW/Tracker/issues/1580

**Comment by Tregeta** [comment]
fixed in next update
