### ISSUE TITLE
Karuk's Oath

### ISSUE THREAD

**Issue by DeathQueen** [Valhalla-Gaming/Tracker#2534]
http://www.wowhead.com/quest=11613/karuks-oath
Borean Tundra - Northrend

no npc no mobs not even a critter

**Comment by Malae1** [comment]
Phase issue.

**Comment by Guybrush-Hellscream** [comment]
Yes, because of https://github.com/HellscreamWoW/Tracker/issues/1580

**Comment by DeathQueen** [comment]
i noticed the mobs are present, but they disappear after the mist begins, maybe this helps. same thing in Garosh's Landing - West of Borean Tundra

**Comment by Tregeta** [comment]
fixed in next update
