### ISSUE TITLE
Dun Morogh - Quest - Extinguish the Fires

### ISSUE THREAD

**Issue by Guybrush-VR** [Valhalla-Gaming/Tracker#2543]
Title : Extinguish the Fires
Link Wowhead : http://www.wowhead.com/quest=26078/extinguish-the-fires

Side : Alliance
Start with : Commander Stonebreaker
End with : Commander Stonebreaker

Why it doesn't work : Using [Firefighting Gear](http://www.wowhead.com/item=56803/firefighting-gear) on the choppers doesn't work. You can see the animation but you don't get credit for it.

Screenshot IG : 
![wowscrnshot_091615_124747](https://cloud.githubusercontent.com/assets/13908354/9902755/282a2cd6-5c71-11e5-989a-087776521fb3.jpg)

Note : Since you cannot complete this quest, you cannot do the following : 
- [Rallying the Defenders](http://www.wowhead.com/quest=26085/rallying-the-defenders)
- [Striking Back](http://www.wowhead.com/quest=26094/striking-back)
- [Grimaxe's Demise](http://www.wowhead.com/quest=26102/grimaxes-demise)
- [Demanding Answers](http://www.wowhead.com/quest=26112/demanding-answers)

**Comment by tribaljet** [comment]
Quest item still doesn't trigger quest progress when aimed at the fires.

**Comment by Cidragon** [comment]
Fixed in December 25th changelog.
