### ISSUE TITLE
[Priest] Glyph of Mind Harvest

### ISSUE THREAD

**Issue by carminejackal** [Valhalla-Gaming/Tracker#2553]
The first time you damage an enemy with Mind Blast, you gain 2 additional Orb, but the cooldown on Mind Blast is increased by 6 sec.

It increases the CD of Mind Blast, but it doesn't give you the 2 additional Orbs that it's supposed to.

http://www.wowhead.com/spell=162532/glyph-of-mind-harvest

**Comment by Moustachos** [comment]
Ref #2266

**Comment by Trekex** [comment]
Not working seems
