### ISSUE TITLE
[Quests] [Eastern Kingdoms] [Elwynn Forest] Bounty on Murlocs

### ISSUE THREAD

**Issue by hugomarciano** [Valhalla-Gaming/Tracker#2558]
Quest: Bounty on Murlocs
Wowhead: http://www.wowhead.com/quest=46/bounty-on-murlocs

Side: Alliance
Start: Bounty Board
End: Guard Thomas

Cause: "This quest is not available for pick up at the Bounty Board."

**Comment by Tregeta** [comment]
fixed next update
