### ISSUE TITLE
Hunter - Beast mastery

### ISSUE THREAD

**Issue by kaneles** [Valhalla-Gaming/Tracker#2563]
The Beast master Hunter has some problems with some talents and glyphs just like the Marksman spec but the thing is that it also got some core abilities bugged such as Kill command and a pasive ability Cobra Strikes.

Thank you
Stay away from da Voodoo!

**Comment by Guybrush-Hellscream** [comment]
Same answer as your other issue. Try to be more specific so that we can clearly see the problem.

**Comment by Moustachos** [comment]
Kill Command will be fixed on next update, Cobra Strikes was fixed on previous one.

**Comment by Moustachos** [comment]
Ref #2266
