### ISSUE TITLE
Item: Elixir of Shadows

### ISSUE THREAD

**Issue by llamalama** [Valhalla-Gaming/Tracker#2568]
http://www.wowhead.com/item=32446/elixir-of-shadows

Using this item should make you able to see mobs you can't normally see but it doesn't work. This item is needed to complete the quest "Secrets of the Talonpriests" and continue along the Sha'tari Skyguard rep chain.

http://www.wowhead.com/quest=11005/secrets-of-the-talonpriests

**Comment by Malae1** [comment]
Ref #2235

**Comment by Trekex** [comment]
This works atm. I killed 2 out of 3 Talonpriests. The 3rd is not spawned seems

**Comment by ATalisan** [comment]
<This should be reopened>
The item's buff should allow you to see the Time-Lost Arakkoa of Skettis which drop the Time-Lost Scrolls either the Time-Lost Arakkoa do not spawn or the Elixir does not allow you to see them. The mobs do not appear and so are not killable and thus do not drop the Time-Lost Scrolls for the Quest: Adversarial Blood.

**Comment by Trekex** [comment]
The elixir works fine. They are not spawned atm. I opened a new issue to report those spawns :)
