### ISSUE TITLE
Collection of pet bugs

### ISSUE THREAD

**Issue by Max-Valhalla** [Valhalla-Gaming/Tracker#257]
"There's a number of bugs surrounding the hunter's pet. my human hunter was given her wolf upon creation, however, every time she levels, the pet despawns and you have to resummon it. It then levels to match the hunter's level after the next couple kills made.

The call pet ability doesn't work, to summon the pet, you have to use revive pet. Revive pet is the only way I've found so far to resummon the pet to you should it despawn, it works fine also to actually revive the pet should it die. When the call pet ability is used, it tells you to dismiss your pet, even if you've already dismissed the pet using the dismiss pet ability. The dismiss pet ability does dismiss the pet in that the pet does despawn.

Trying to use the move to function doesn't work to get the pet to move to the desired location. The passive does work when selected, but stay does not. Also the settings on the pet bar abilities reset with every despawn and respawn, and you have to manually click them to get the pet to perform them, even when set to auto-cast.

Also it won't let you name the pet either, it'll act like it will, but on hitting the last confirmation box, nothing happens."

**Comment by GeneralCaveman** [comment]
I believe this is a better place to comment on this than my other post.

The despawning of the pets when the character levels also happens to Mage's Water Elemental and Warlock's Imp. It stopped doing that for my mage around level 20.

**Comment by Trekex** [comment]
Move to and Stay commands now work fine. Also renaming pet works

**Comment by Moustachos** [comment]
Every bug reported here seem to be fixed as of current version, closing.
