### ISSUE TITLE
Elwynn Forest - Quest - The Fargodeep Mine

### ISSUE THREAD

**Issue by Guybrush-VR** [Valhalla-Gaming/Tracker#2570]
Title : The Fargodeep Mine
Link Wowhead : http://www.wowhead.com/quest=62/the-fargodeep-mine

Side : Alliance
Start with : Marshal Dughan
End with : Marshal Dughan

Trouble : It's a display problem, you can still complete this quest. You have the yellow sentence confirmation that you discovered the mine but it doesn't display it on the quest log. That means that it appears you didn't discover it while you did in fact.

Note : Same problem as #2571

**Comment by Templeguy** [comment]
I can't complete the quest so it's not just the text missing.

**Comment by Guybrush-Hellscream** [comment]
I've finished it, have you discovered the mine (there is a yellow sentence above your char that confirms it) ?

**Comment by damiongans** [comment]
I did, but it did not complete the quest. So it does do the quest including the yellow text but the quest itself does not complete.

**Comment by Cidragon** [comment]
This quest is working fine now.
