### ISSUE TITLE
Elwynn Forest - Quest - The Jasperlode Mine

### ISSUE THREAD

**Issue by Guybrush-VR** [Valhalla-Gaming/Tracker#2571]
Title : The Jasperlode Mine
Link Wowhead : http://www.wowhead.com/quest=76/the-jasperlode-mine

Side : Alliance
Start with : Marshal Dughan
End with : Marshal Dughan

Trouble : It's a display problem, you can still complete this quest. You have the yellow sentence confirmation that you discovered the mine but it doesn't display it on the quest log. That means that it appears you didn't discover it while you did in fact.

Note : Same problem as #2570

**Comment by zwei7** [comment]
I can't complete it. I am at the location and the trigger won't accept I did it.
![wowscrnshot_120815_164049](https://cloud.githubusercontent.com/assets/15259298/11669396/7d597cf8-9dca-11e5-9174-ede63ab6f22e.jpg)

**Comment by Malae1** [comment]
Believe this is a display error, try to turn it in.

**Comment by Aedomus** [comment]
I can confirm this issue.

**Comment by Cidragon** [comment]
Tested today, I couldn't finish it.

**Comment by Cidragon** [comment]
This quest is working fine now but I feel like the area trigger isn't in the right place.
