### ISSUE TITLE
Warlock Spell: Rain of Fire

### ISSUE THREAD

**Issue by llamalama** [Valhalla-Gaming/Tracker#2573]
http://www.wowhead.com/spell=5740/rain-of-fire

This spell does no damage.

**Comment by GMTyrial** [comment]
This spell does damage, and channels properly.

#2266

**Comment by llamalama** [comment]
This spell is not doing any damage. Yes it is and has been channeling correctly, and yes it applies the debuff to the enemies, but the debuff is doing no damage at all.

**Comment by Malae1** [comment]
This spell is doing damage, the debuff is not suppose to do damage, your channeling of the spell does it...

**Comment by llamalama** [comment]
I tested this by going to a neutral level 5 mob and casting the spell. The debuff did apply but the mob didn't take any damage at all. Seeing as it was low level, it should have been killed in 1 hit but it didn't take any damage or even try to attack me back.

**Comment by tribaljet** [comment]
I'm not sure what's happening but I did witness the Rain of Fire AoE spell being channeled on both single targets as well as groups of mobs and their health didn't drop. Could there be any talent that would misbehave and cause such an effect?

**Comment by Tregeta** [comment]
http://www.wowhead.com/spell=5740/rain-of-fire please check the modified list, this is for the base spell...if you have any of these it may be the culprit.

**Comment by llamalama** [comment]
I reset my talents and glyphs and I tested it without having any set. My character is in its lv 90s.
I'm wondering if the effect of the passive Aftermath http://www.wowhead.com/spell=109784/aftermath is the problem. If the GMs are testing on a Destruction Warlock that is under lv 54 then they wouldn't be able to see the same problem as me if that is the case.

**Comment by Tregeta** [comment]
can you please give us you character name so that we can take a look at it to see if this passive is still somehow enabled.

**Comment by llamalama** [comment]
My warlocks' name is Shappy.

**Comment by Tregeta** [comment]
Thank you :smiley:

**Comment by VictorTyne** [comment]
I'm still having this issue as a lvl72 Destruction Warlock. Before getting Aftermath, Rain of Fire just did paltry damage. Now, I can cast it onto groups and it does no damage. It doesn't even cause mobs to attack me and doesn't give me loot rights if my pet solos something I've only hit with Rain of Fire.

**Comment by nuhrii** [comment]
As of Legion, the skill is no longer channeled and still no longer does damage
