### ISSUE TITLE
Glyph of Bull Rush

### ISSUE THREAD

**Issue by Normonder** [Valhalla-Gaming/Tracker#2581]
http://www.wowhead.com/spell=94372/glyph-of-bull-rush

i think that is not working correctly .. sometimes it gives me additional rage and sometimes no ..
better say .. it gaves me additional rage only when i applied it first time and then nothing (next attempts)

**Comment by Moustachos** [comment]
Works as intended as of current version.

**Comment by Moustachos** [comment]
Ref #2266
