### ISSUE TITLE
Ambush- Rogue

### ISSUE THREAD

**Issue by Hangun** [Valhalla-Gaming/Tracker#2582]
Rogue must not behind to ambush target.
http://www.wowhead.com/spell=8676/ambush

**Comment by Tregeta** [comment]
@Bombrick

> Has no sound at all

**Comment by Moustachos** [comment]
"Must be behind target" requirement will be removed on next update (accordingly to patch 6.0.2).

As of Ambush sound: there's just no issue with it at the moment.

**Comment by Moustachos** [comment]
Ref #2266
