### ISSUE TITLE
[Spells] [Abilities] [Monk] Tiger Palm

### ISSUE THREAD

**Issue by hugomarciano** [Valhalla-Gaming/Tracker#2588]
Spell: Tiger Palm
Class: Monk
Wowhead: http://www.wowhead.com/spell=100787/tiger-palm

Cause: "This spell does not work. The monster that I attack with this skill does not suffer any damage."

**Comment by BraynStorm** [comment]
Correction: It does 1 dmg (2 if it crits) and it applies [Tiger Palm](http://www.wowhead.com/spell=125359/tiger-power)

**Comment by Guybrush-Hellscream** [comment]
You can see it applies the armor debuff but i'm not sure it's working, if someone can confirm/infirm it?

**Comment by Kehrer-Hellscream** [comment]
Hi I made a few tests with recount, and so far I can`t see a (significant) difference in dmg (DPS) with or without Tiger paw applied. ( test was made like this: same monster same lvl same attack pattern once with and once without Tiger paw). If I`m correct with Tiger Paw it should make +-30% more dmg. Please correct me if I understood something wrong, I`ll change my tests accordingly.
