### ISSUE TITLE
Broken Hunter Spells

### ISSUE THREAD

**Issue by bubbles3008** [Valhalla-Gaming/Tracker#2600]
a little summary of bugs i found in the last 2 days.

Mastery: Sniper Training isnt shown (and not counted)

http://www.wowhead.com/spell=76659/mast ... r-training

chimera shot dont deal any damage

http://www.wowhead.com/spell=53209/chimaera-shot

Spiritbond dont heal the char or even the pet. ( by that you should also check the glyph)

http://www.wowhead.com/spell=109212/spirit-bond

Trueshot aura isnt shown and doesnt count for the char. ( only pet got the buff icon (doubtful if this even count for the pet))

http://www.wowhead.com/spell=19506/trueshot-aura

**Comment by Malae1** [comment]
Trueshot Ref #1488, Spiritbond #2367

**Comment by Moustachos** [comment]
Chimera Shot was fixed in a previous update.

Trueshot Aura works, it's just that client doesn't display it in buffs list for your character.

Spirit Bond and Mastery: Sniper Training will be fixed on next update.

**Comment by Moustachos** [comment]
Ref #2266
