### ISSUE TITLE
Field Repair Bot 74A scroll can't be found in Blackrock Depths

### ISSUE THREAD

**Issue by Demonstrike95** [Valhalla-Gaming/Tracker#2606]
Hey guys,
the scroll for the "Schematic: Field Repair Bot 74A" you need for Jeeves in engineering isn't anywhere in the Blackrock Depths.
I looked for it everywhere but no sign ... It should be normally found in front of the boss Golem Lord Argelmach in the west garrison of Blackrock.

I'd be glad if you can fix it because Jeeves is such an useful item...
Cya

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/spell=22704/field-repair-bot-74a

**Comment by deathbane1911** [comment]
in the blackrock city in a pub area there is a door that requires a key, but it doesn't drop, and there are suuposed to be 4 bosses, but they don't spawn

**Comment by nuhrii** [comment]
I just went and found the plans, its there and it works, it teaches on how to craft the field repair bot. To get threw the door to need to get private rocknit drunk by keep giving him drinks. Close this issue.
