### ISSUE TITLE
druid spells that don't work at all

### ISSUE THREAD

**Issue by Max-Valhalla** [Valhalla-Gaming/Tracker#264]
"these druid spells:
Travel form - turns the player into humanoid form... thats it
Thrash - cannot be used at all, making aoe impossible
Entangling Roots - can be casted, does not root the target
Savage Defense - costs 60 rage, but gives no buff
Prowl - i literally just went to stealth as a bear (scary)

the talent Wild Charge does absolutely nothing

as a Guardian druid, i can only use 4 spells:
Mangle - seems to work fine, besides the fact that i have no idea when its off cooldown
Maul - seem to work fine, besides the fact that i have no idea when its off cooldown (it should have no cooldown besides the GCD)
Growl - works
Rejuvenation - seems to work as intended as i have no spellpower

Travel Form - http://www.wowhead.com/spell=783/travel-form
Thrash - http://www.wowhead.com/spell=77758/thrash
Entangling Roots - http://www.wowhead.com/spell=339/entangling-roots
Savage Defense - http://www.wowhead.com/spell=62606/savage-defense
Prowl - http://www.wowhead.com/spell=5215/prowl"

**Comment by EPS1L0N** [comment]
Travel Form has been fixed
Entangling Roots has been fixed
Prowl has been fixed

unsure about the others

**Comment by Dracoknight256** [comment]
Wild Charge is also fixed

**Comment by silverjade** [comment]
Travel form turns you humanoid if you go underwater while in stag form. It should turn you into your sealion/swim form instead automatically, right now you have to click on travel form while under water to get it to turn you into the sealion. Also if you're of level to know flight form, it should also turn to flight form if you leave the ground without doing anything, unless you have "glyph of the stag" that makes flight form a separate ability.

**Comment by serenity-talador** [comment]
It seams to work now
