### ISSUE TITLE
Class: Monk passive spell - combo breaker

### ISSUE THREAD

**Issue by Dulog** [Valhalla-Gaming/Tracker#2642]
Started from lvl 10 windwalker monk has to get  passive spell - combo breaker, http://www.wowhead.com/spell=137384/combo-breaker, which allows the use of blackout kick http://www.wowhead.com/spell=100784/blackout-kick  or jab http://www.wowhead.com/spell=100780/jab free.

**Comment by Bombrick** [comment]
this is an important passive for ww monk fix fast as you can pls

**Comment by Bombrick** [comment]
Info: Doesn't show in spellbook like other passives

**Comment by Bombrick** [comment]
Also applies to Chi explosion and tiger palm

**Comment by Collector-Valhalla** [comment]
Yep. That's pretty basic/main thing for windwalker monks. They lose alot without it.

**Comment by Bombrick** [comment]
Please fix this you fixed everything for ww expect this important passive !
