### ISSUE TITLE
Glyph of the Blazing Trail

### ISSUE THREAD

**Issue by Luminescent-Valhalla** [Valhalla-Gaming/Tracker#2652]
After learning the glyph there is no Fire trail added to the charge effect at all.

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/item=85221/glyph-of-the-blazing-trail

**Comment by Luminescent-Hellscream** [comment]
http://www.wowhead.com/spell=126661/warrior-charge-drop-fire-periodic

**Comment by Moustachos** [comment]
Ref #2266
