### ISSUE TITLE
[Quests] [Eastern Kingdoms] [Dun Morogh] The View from Down Here

### ISSUE THREAD

**Issue by hugomarciano** [Valhalla-Gaming/Tracker#2655]
Quest: The View from Down Here
Wowhead: http://www.wowhead.com/quest=28868/the-view-from-down-here

Side: Alliance
Start: Snevik the Blade
End: Snevik the Blade

Bug: Despite the Viewpoint Equalizer shrink Frostmane Builders, the quest does not count them.

**Comment by Doriathrim** [comment]
works fine
