### ISSUE TITLE
[Quests] [Eastern Kingdoms] [Dun Morogh] Strike From Above

### ISSUE THREAD

**Issue by hugomarciano** [Valhalla-Gaming/Tracker#2656]
Quest: Strike From Above
Wowhead: http://www.wowhead.com/quest=25841/strike-from-above

Side: Alliance
Start: Slamp Wobblecog
End: Slamp Wobblecog

Bug: After I use the Signal Flare, nothing happens.

**Comment by Cidragon** [comment]
It's working now.
