### ISSUE TITLE
Rogue Stealth

### ISSUE THREAD

**Issue by Retchen** [Valhalla-Gaming/Tracker#2661]
I'm a Subtletly Rogue, Stealth ever worked, and now that I took my first talent (Subterfuge) the stealth doesnt work anymore.

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/spell=115191/stealth
http://www.wowhead.com/spell=108208/subterfuge

**Comment by Retchen** [comment]
Wut ?

**Comment by silverjade** [comment]
Retchen, the talent Subterfuge is bugged currently. To get stealth working again pick a different talent.

**Comment by GMTyrial** [comment]
Workaround here : https://github.com/HellscreamWoW/Tracker/issues/2005

**Comment by Moustachos** [comment]
Ref #2266
