### ISSUE TITLE
[Raid] Karazhan

### ISSUE THREAD

**Issue by Aveta** [Valhalla-Gaming/Tracker#2670]
http://www.wowhead.com/zone=3457/karazhan
Instance is completely empty. Nothing is spawned.

**Comment by serenity-talador** [comment]
instance done yesterday , every thing ok excep the chess which arent playable so you cant finish the instance and maybe un bug why minuit but i kill them way to fast i think need more try to know

**Comment by Aveta** [comment]
Yeah, it's now spawned. It was spawned about a month or two after I reported it and forgot to close the issue.
