### ISSUE TITLE
Glyph of Frost Shock

### ISSUE THREAD

**Issue by Beponator** [Valhalla-Gaming/Tracker#2680]
As a Enchanment Shaman this is highly recommended for me http://www.wowhead.com/spell=55443/glyph-of-frost-shock .It lower CD like it should but only when you strike with http://www.wowhead.com/spell=8056/frost-shock first. if i strike first with http://www.wowhead.com/spell=8050/flame-shock it shares the CD with Frost Shock and makes it 6 sec like there is no glyph.
Please fix it ,it is dps boost for ench.shaman

**Comment by Moustachos** [comment]
This isn't a bug, spells of a same category share the same cooldown.

So when you cast Frost Shock first, the same cooldown of 4 sec applies to Earth Shock and Flame Shock.

And when you cast Flame Shock or Earth Shock, they apply a 6 sec cooldown to Frost Shock, regardless of Glyph of Frost Shock, that's the same on retail.

**Comment by Moustachos** [comment]
Ref #2266
