### ISSUE TITLE
[Rogue] Smoke Bomb

### ISSUE THREAD

**Issue by Aveta** [Valhalla-Gaming/Tracker#2684]
http://www.wowhead.com/spell=76577/smoke-bomb
Spell doesn't work at all.

**Comment by Guybrush-Hellscream** [comment]
Can you elaborate?

**Comment by Aveta** [comment]
When I use the skill, nothing happens. No visual, no damage reduction and mobs can still target me.

**Comment by Guybrush-Hellscream** [comment]
Thanks!

**Comment by Moustachos** [comment]
Ref #2266
