### ISSUE TITLE
[NPC] Mordenai, Netherwing questgiver

### ISSUE THREAD

**Issue by Aveta** [Valhalla-Gaming/Tracker#2685]
http://www.wowhead.com/npc=22113/mordenai
NPC can't be interacted with at all, which makes it impossible to gain reputation with Netherwing. This makes Netherwing Drake mounts unobtainable (unless bought from the shop).

**Comment by Th3hydra** [comment]
I personally would like to get the netherwing mount in game. This was a fun quest chain other times I've played and would like to do it again. So essence, bump.

**Comment by lavalash551** [comment]
I dont understand why http://www.wowhead.com/quest=10804/kindness is simply missing...

**Comment by Tregeta** [comment]
fixed next update

**Comment by KraitX** [comment]
I have done everything for the netherwing rep up until "ally of the netherwing, Mordenai is suppose to give you a quest called "In Service of the Illidari" which he doesnt

**Comment by Tregeta** [comment]
You need the 2nd level of flying.

**Comment by KraitX** [comment]
So if you dont have the fast flying, Then the quest ! wont be available?

**Comment by Trekex** [comment]
Correct, you need it
