### ISSUE TITLE
[Druid] Travel Form

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#2694]
Swimming version of travel form should be useable in closed areas like Steamvault, Temple of Atal'hakkar, in underwater caves etc.

Also jumping out of water from swimming form should automaticly change druid to flight form. Currently it changes back to humanoid form.

**Comment by Damvs** [comment]
http://www.wowhead.com/spell=783/travel-form

**Comment by Collector-Valhalla** [comment]
http://us.battle.net/wow/en/blog/15682579/#druid

"Travel Form now automatically transitions between Aquatic, Land, and Flight forms depending on the Druid’s location."

**Comment by Moustachos** [comment]
Ref #2266

**Comment by KraitX** [comment]
Aquatic form seems quite slow, Or does it increase in speed when you train riding on lvl 60?
