### ISSUE TITLE
[Item] Toria's Perseverance

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#2695]
I have no idea what's the problem with that head piece but it decrease my agility by (and I'm serious) 2147483648 points. So my agility stat is red zero. Also my attack power is just zero and no matter what other pieces of gear I have on myself or if I'm naked that one Head item reduce my agility to the ground (or even deeper to hell).

**Comment by Malae1** [comment]
[Helmet of Vile Indignation](http://www.wowhead.com/item=118896/helmet-of-vile-indignation) is related.

**Comment by Moustachos** [comment]
Will be fixed on next update.

Ref #2266
