### ISSUE TITLE
[Druid] Rip + Predatory Swiftness

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#2696]
Those two spells doesn't work with each other. I never got a proc of Predatory Swiftness from Rip.

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/spell=16974/predatory-swiftness

**Comment by Collector-Hellscream** [comment]
Any updates on that issue? Currently 'Predatory Swiftness' procs only from 'Ferocious Bite' and 'Savage Roar'.

**Comment by EPS1L0N** [comment]
#2266
