### ISSUE TITLE
[Glyph] of Dash

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#2697]
Glyph of Dash doesn't work for Claws of Shirvallah form. It should decrease cooldown of dash from 3 minutes to 2 minutes but it doesn't.

**Comment by silverjade** [comment]
Adding to this that it doesn't work for my lvl 91 druid either. It used to work, but it doesn't any longer.

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/spell=59219/glyph-of-dash

**Comment by Moustachos** [comment]
As of current version, the Glyph of Dash is working for Claws of Shirvallah.

**Comment by Moustachos** [comment]
Ref #2266
