### ISSUE TITLE
[Bug spell] counterspell - talador server

### ISSUE THREAD

**Issue by hendenie** [Valhalla-Gaming/Tracker#2701]
http://www.wowhead.com/spell=2139

Mage

The fate(spell) interrupts the target, but the effect of the fate(spell) does not last 6 seconds. He(it) lasts no second.
Sorry for my english i use "lexilogos" for  translation =).

**Comment by Guybrush-Hellscream** [comment]
Don't worry, thanks for reporting.

**Comment by HellscreamWoW** [comment]
Talador and Hellscream use the same source. You don't need to mark your issues as Talador or Hellscream.
