### ISSUE TITLE
[Quest] Rams on the Lam

### ISSUE THREAD

**Issue by carminejackal** [Valhalla-Gaming/Tracker#2706]
http://www.wowhead.com/quest=25905/rams-on-the-lam
https://www.youtube.com/watch?v=1yp-qiVp1hQ

Currently you can't complete this quest. You're supposed to /whistle emote at the targeted stolen ram and it runs home, thus giving you credit. Currently, whistling at it does nothing.

**Comment by Lazyg33k** [comment]
still does nothing i can confirm

**Comment by zwei7** [comment]
Quest giver won't even give me the whistle to use on the rams. I didn't destroy the whistle either. Making sure to cover bases, I abandoned the quest and and accepted it again hoping to get the whistle, but nothing was given to me again.
![wowscrnshot_111815_194059](https://cloud.githubusercontent.com/assets/15259298/11259029/50e58cfa-8e2c-11e5-8c23-f08a9b5c55fa.jpg)
![wowscrnshot_111815_194103](https://cloud.githubusercontent.com/assets/15259298/11259028/50e221d2-8e2c-11e5-9fb6-889c054f6e0d.jpg)

**Comment by carminejackal** [comment]
You're not given a whistle even in retail. You're supposed to emote /whistle at them and they're supposed to run 'home'. Thus giving you credit for the quest.

**Comment by zwei7** [comment]
Sorry about that, didn't realize there was no whistle item. I tried to use /whistle after I targeted one of the stolen rams, but it was unaffected. Used it 3 times on the ram as shown below.
![wowscrnshot_111915_181725](https://cloud.githubusercontent.com/assets/15259298/11287529/4d023a16-8eea-11e5-8d55-a0b7109b6b08.jpg)

**Comment by Orkator** [comment]
Still not working^^

**Comment by guilofrano** [comment]
Just tried doing it and it still doesn't work

**Comment by Cidragon** [comment]
Fixed in December 25th changelog.
