### ISSUE TITLE
Hunter - Pet size

### ISSUE THREAD

**Issue by Netherlord** [Valhalla-Gaming/Tracker#2711]
Other than the pet not always attacking properly, there's another minor bug: the size of every pet I bring with me as a Hunter is scaled down a lot. They are miniaturized the moment I tame them.

Edit: I confirm it's not only related to the character level. Pets are way bigger in the official Blizzard servers.

**Comment by Vasharij** [comment]
This is still a problem. 
I played wow free retail a few moments ago and the pet was just fine. 
I created a hunter on retail and its dimension were normal, on this server it's tiny, like a companion.

**Comment by Moustachos** [comment]
Ref #2266
