### ISSUE TITLE
[Spell] [Paladin] Holy Shock

### ISSUE THREAD

**Issue by emil494** [Valhalla-Gaming/Tracker#2721]
Holy shock dosnt work

**Comment by Guybrush-Hellscream** [comment]
Can you elaborate?

**Comment by emil494** [comment]
It cant heal friendly or damage enemys as it should do

**Comment by emil494** [comment]
instead dose it nothing just a flash

**Comment by Guybrush-Hellscream** [comment]
Does it give you 1 holy power?

**Comment by emil494** [comment]
nope

**Comment by Guybrush-Hellscream** [comment]
Alright man, thanks!

**Comment by emil494** [comment]
np

**Comment by KHAR05** [comment]
paladin spell HOLY SHOCK is not working properly, it is casting but dont heal or damage the target and do nothing.. please help fix it. thanks.

**Comment by Luminescent-Hellscream** [comment]
Any news on this as its one of a holy paladins main abilities to generate holy power which atm we can not generate making holy paladins not viable as anykind of healer atm.

**Comment by EPS1L0N** [comment]
#2266
