### ISSUE TITLE
 [Relentless Strikes]

### ISSUE THREAD

**Issue by danirzv** [Valhalla-Gaming/Tracker#2723]
[Relentless Strikes] of rogue should restore 25energy by 20% chance per combopoint on finishing moves.
but in 5 combopoint when i tested it dident restore anything.

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/spell=58423/relentless-strikes

**Comment by Moustachos** [comment]
Will be fixed on next update.

**Comment by Moustachos** [comment]
Ref #2266
