### ISSUE TITLE
Sort Charge

### ISSUE THREAD

**Issue by Anaksunamoun** [Valhalla-Gaming/Tracker#2739]
Le sort charge du guerreir fonctionne mal je m'explique:

Quand le personnage saute et que je lance charge rien ne se passe
Quand un petit obstacle entre le personnage et l'ennemi rien ne se passe alors que normalement cela doit être contourné

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/spell=100/charge

**Comment by Moustachos** [comment]
Fixed in a recent update.

**Comment by Moustachos** [comment]
Ref #2266
