### ISSUE TITLE
Some bugs i found.

### ISSUE THREAD

**Issue by slayerjj** [Valhalla-Gaming/Tracker#2741]
Sunfire isn't doing damage and i can't speak to the npc to set Dolanaar as my returning point.

**Comment by Guybrush-Hellscream** [comment]
Try to split bugs in different issues when you list them so that we can close them individually when they're fixed.
http://www.wowhead.com/spell=164815/sunfire
Can you create a new issue about that NPC and give us as much details as you can (name, wowhead links, zone, etc)?

**Comment by slayerjj** [comment]
yeah ofc.
