### ISSUE TITLE
Bug combat avec Assommer

### ISSUE THREAD

**Issue by Damvs** [Valhalla-Gaming/Tracker#2742]
Quand on assomme un mob et puis qu'on enlève le camouflage, le mob nous agro, ce qui n'est pas normal, j'ai regarder sur les forum officiel, ça serai un bug de patch:

http://eu.battle.net/wow/fr/forum/topic/2313682185

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/spell=6770/sap
Note : When you reveal yourself after sapping an NPC, he'll attack you. It might be a retail bug due to patch 4.2.

**Comment by Moustachos** [comment]
Ref #2266
