### ISSUE TITLE
Dirty Tricks

### ISSUE THREAD

**Issue by Damvs** [Valhalla-Gaming/Tracker#2743]
Le talent Coup tordu du voleur est censé ne plus faire coûter de l'énergie pour les technique suriner et cécité, et donc cela ne fonctionne pas et coûte de l'énergie.

http://fr.wowhead.com/spell=108216/coup-tordu

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/spell=108216/dirty-tricks
Gouge and Blind still cost energy after getting Dirty Tricks.

**Comment by Moustachos** [comment]
"_Gouge and Blind no longer cost Energy_" works as of current version.

**Comment by Moustachos** [comment]
Ref #2266
