### ISSUE TITLE
Kill Command

### ISSUE THREAD

**Issue by Physeeeeee** [Valhalla-Gaming/Tracker#2752]
The hunter skill Kill Command (Beast Mastery specialization) is not working it's not doing any damage

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/spell=34026/kill-command

**Comment by zwei7** [comment]
True. Does jack all.

**Comment by Collector-Valhalla** [comment]
Without it beast mastery specialization is pretty much useless. Still deals 0 damage.

**Comment by Moustachos** [comment]
Ref #2266
