### ISSUE TITLE
Zeth'gor Must Burn! not passable

### ISSUE THREAD

**Issue by Dushku** [Valhalla-Gaming/Tracker#2770]
http://www.wowhead.com/quest=10895/zethgor-must-burn

Trying to use the quest item, it always says you need to be in a certain place even when you are.

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/item=31739/smoke-beacon

**Comment by Cidragon** [comment]
Fixed in December 5th changelog
