### ISSUE TITLE
Safeguarding the Watchers (passable, but...)

### ISSUE THREAD

**Issue by Dushku** [Valhalla-Gaming/Tracker#2773]
http://www.wowhead.com/quest=9894/safeguarding-the-watchers

The Sporeloks are too strong. I had to turn my Sporregar reputation to At War and kill all the ones around where Lord Klaq spawns just to be able to kill him and get credit for doing so. This also made Saving the Sporeloks more challenging than it normally is.

For those interested in using the mentioned workaround, killing these Sporeloks does NOT diminish your rep with Sporeggar. Don't forget to turn At War back off when you're done!

**Comment by Cidragon** [comment]
I didn't have any troubles. Can someone check this?
