### ISSUE TITLE
Pet bar is not shown

### ISSUE THREAD

**Issue by vyne121** [Valhalla-Gaming/Tracker#2783]
Pet bar is not shown but pet is summoned.

**Comment by Guybrush-Hellscream** [comment]
Which class?

**Comment by vyne121** [comment]
Hunter. After Dismiss \ Recall it was fine.

**Comment by EPS1L0N** [comment]
> Hunter. After Dismiss \ Recall it was fine.

note:
@level 10 you get a pet bar, this is a minor bug where the pet bar doesn't immediately show up when you hit level 10

**Comment by vyne121** [comment]
Was lvl ~15 when this happened.

**Comment by EPS1L0N** [comment]
when you logged in were you above level 10? or did you level to 15

**Comment by vyne121** [comment]
I'm sure I was 10+.

**Comment by Moustachos** [comment]
Ref #2266
