### ISSUE TITLE
Water Elemental (Pet, Frost Mage)

### ISSUE THREAD

**Issue by emil494** [Valhalla-Gaming/Tracker#2785]
The water elemental for frost mage dosnt do anything just stand and looks. The pet bar is also not shown.
Summon Water: Elemental: http://www.wowhead.com/spell=31687/summon-water-elemental
Water Elemental: http://www.wowhead.com/npc=510/water-elemental

**Comment by zwei7** [comment]
It is a useless pet since you can't control it and it just follows you. It can't attack anything and you can't tell it to either.

**Comment by Luminescent-Hellscream** [comment]
My action bar for elemental shows up fine for me (Using bartender) only issue i have with elemental is it does not regenerate its mana and i have to desummon him and then resummon him

**Comment by zwei7** [comment]
I have no pet bar, still should be visible even without bartender (great anime by the way). Now I can't dismiss it. When I click the portrait option "dismiss" nothing happens. Not even an error message.
![wowscrnshot_121515_235259](https://cloud.githubusercontent.com/assets/15259298/11832563/9497bef8-a387-11e5-9e5d-bdd41e861175.jpg)

So I try to summon a new water elemental to replace the current one, hoping to proc the action bar to show up. Can't summon if I got a water elemental. Can't get rid of my current one.
![wowscrnshot_121515_235458](https://cloud.githubusercontent.com/assets/15259298/11832602/f44bf38c-a387-11e5-8d36-41f0a487c1ce.jpg)

**Comment by Luminescent-Hellscream** [comment]
ok there is a fix for that i had that issue when going in instances and out again find a mob near you and do this /petattack it will force the pet to attack and when it has died you can resummon it again.

**Comment by nallak** [comment]
i use these macro's atm ( lvl 10 mage ) 

dismiss:  /script PetDismiss() 
attack:   /Petattack
stay:  /petstay
passive mode: /petpassive
defensive mode: /petdefensive

my pet attacks when its in defensive mode , also when right click on enemy target he start attacking that mob

Hope this helps untill it fixed ;)
