### ISSUE TITLE
Hunter

### ISSUE THREAD

**Issue by vlath19** [Valhalla-Gaming/Tracker#2797]
Spirit Bond isn't working is not healing because the pasive is not visible available, camouflage: it are not working when i use it, flock of crows is not dealing damage in the enemmy

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/spell=109212/spirit-bond
http://www.wowhead.com/spell=131894/a-murder-of-crows

**Comment by Moustachos** [comment]
Spirit Bond and A Murder of Crows will be fixed on next update.

**Comment by Moustachos** [comment]
Ref #2266
