### ISSUE TITLE
Teldrassil: The Burden of the Kaldorei (Quest)

### ISSUE THREAD

**Issue by Vemir** [Valhalla-Gaming/Tracker#2798]
After I filled the vial, which had no shade at the moonwell to tell the story this quest by the way; I go to turn it in at the crossroad near Darnassus, in which Corithras is no where to be found. I go into Darnassus, thinking I may need a refresh of the terretory, nope. I log out and log back in, he is still unavailable. After reloading the ui a few times as well as attempting to target him, he is still no where to be found, even though the quest marker is right where he is supposed to be.

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/quest=7383/teldrassil-the-burden-of-the-kaldorei

**Comment by silverjade** [comment]
![wowscrnshot_100815_220110](https://cloud.githubusercontent.com/assets/13601831/10384937/34f01626-6e08-11e5-93b9-bd65115ca5c7.jpg)

The NPC is at Dolanaar to give the quest, but vanishes from this location after you've filled the vial. He only reappears again if you abandon the quest.

**Comment by Cidragon** [comment]
It's working now :D
