### ISSUE TITLE
Fishing doesn't work

### ISSUE THREAD

**Issue by Sybal** [Valhalla-Gaming/Tracker#2801]
When fishing, bobber doesn't move and there is no sound, so I just have the text : "Fish has gone away" during fishing cast and it interrupts the fishing cast.

**Comment by bubbles3008** [comment]
a "little fix" that helps a bit is to logout, delete you cache folder and login. since you dont relog and dont use any portal or teleportation cast, you have around 80% working blobber movement

**Comment by zwei7** [comment]
I guess this is not top priority. I got the same problem in Darnasus.
