### ISSUE TITLE
[Spells] [Abilities] [Monk] Touch Of Death

### ISSUE THREAD

**Issue by omgwtfize** [Valhalla-Gaming/Tracker#2816]
- ability does not kill target with less health then the monks maximun health. 
- ability does not deal damage equal to that of the monks maximum health on tough targets below 10 % of health. 

- when used, the ability only deals 2 points of physical damage to the target.

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/spell=115080/touch-of-death
