### ISSUE TITLE
quest Master and Servant unpassable

### ISSUE THREAD

**Issue by Dushku** [Valhalla-Gaming/Tracker#2826]
http://www.wowhead.com/quest=11730/master-and-servant

Every time I try to use http://www.wowhead.com/item=35116/the-ultrasonic-screwdriver it says I am in the wrong zone. I've tried in Fizzcrank Pumping Station, Mid Point Station, and The Geyser Fields. Item tooltip references greater pools region (no caps) and there is no map area with this specific name.

**Comment by silverjade** [comment]
I was just able to do this quest, using mobs close to the airstrip. In the scalding pools area.

**Comment by Dushku** [comment]
Confirmed. Thanks for the clarification :)

**Comment by malex1024** [comment]
This quest was never broken, and works as of January 07, 2017. This issue should be closed.
