### ISSUE TITLE
[Spell] Eternal Flame

### ISSUE THREAD

**Issue by Luminescent-Valhalla** [Valhalla-Gaming/Tracker#2827]
Currently eternal flame does not have a cast time and is instant cast it should have a base cast time of 1.5 seconds which is lowered by the amount of haste you have. although it can not be cast while moving when stood still there is not cast its instant cast 

http://www.wowhead.com/spell=114163/eternal-flame

**Comment by nmjayan** [comment]
Note: It should be Instant cast for Prot.

Furthermore, as of now, it heals for the full amount irrespective of how much Holy Power is available (and depleted), much like is the case with Word of Glory. The HoT is also completely missing.

**Comment by Luminescent-Valhalla** [comment]
Thanks for the extra info about being instant cast on prot. Been a long time since I played prot (TBC)

**Comment by EPS1L0N** [comment]
#2266
