### ISSUE TITLE
 [Vanish]

### ISSUE THREAD

**Issue by danirzv** [Valhalla-Gaming/Tracker#2841]
[Vanish] "Allows you to vanish from sight, entering an improved stealth mode for 3 sec.  For the first 3 sec after vanishing, damage and harmful effects received will not break stealth.  Also breaks movement impairing effects."

but in server it break in first 3 sec too...
and if use it when an npc attacking you you dont get invisible (and you will no come out of combat)

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/spell=1856/vanish

**Comment by Moustachos** [comment]
Ref #2266
