### ISSUE TITLE
warlock demonologie (felguarde)

### ISSUE THREAD

**Issue by hendenie** [Valhalla-Gaming/Tracker#2868]
http://www.wowhead.com/spell=30146/summon-felguard#changelog
demonology warlock , the felguarde don't work, 
When one try of the called, him(it) do not appear.

**Comment by Malae1** [comment]
Ref #2609, #2312, #1283

**Comment by Lazyg33k** [comment]
i wondering why is still broken do you working on this one im a warlock and without him lv 60 this class is boring :( please just told me if you gona work on that ?
