### ISSUE TITLE
[Shadowmoon Valley][Legion Hold] Many missing infernals!

### ISSUE THREAD

**Issue by carminejackal** [Valhalla-Gaming/Tracker#2916]
The first pic is how it looks in game:
![](http://i.imgur.com/tafjUFA.jpg)
This second pic is how it's supposed to look (taken off wikia since I can't get a shot from retail):
![](http://i.imgur.com/1rzAlN7.jpg)

**Comment by silverjade** [comment]
It seems the Infernals are for this quest: http://www.wowhead.com/quest=10564/blast-the-infernals
