### ISSUE TITLE
[Quest] To Legion Hold

### ISSUE THREAD

**Issue by carminejackal** [Valhalla-Gaming/Tracker#2917]
http://www.wowhead.com/quest=10563/to-legion-hold
The quest requires you to hide yourself within a box next to the 'Legion Communication Device' in Legion Hold. 
![](http://wow.zamimg.com/uploads/screenshots/normal/16348.jpg)
Doing so causes http://www.wowhead.com/npc=21633/deathbringer-jovaan to spawn and go through a script. Once the script has finished you get credit for the quest. 
As seen below, the Communication Device is missing (along with 3 mobs (http://www.wowhead.com/npc=21314/terrormaster)  & 2 fel cannons):
![](http://i.imgur.com/gCMqTdF.png)
Thus you can't complete the quest.

**Comment by K-Reeboo** [comment]
As of today, issue is still pertinent, the communication device is not spawn. Cannot complete the quest.
Please reopen.

![wowscrnshot_011616_184403](https://cloud.githubusercontent.com/assets/16204587/12375114/7a6e0b1e-bc81-11e5-97e6-6b481f17ee8a.jpg)
