### ISSUE TITLE
[Quest] Akama (death bug)

### ISSUE THREAD

**Issue by carminejackal** [Valhalla-Gaming/Tracker#2932]
http://www.wowhead.com/quest=10628/akama

Completing the above quest causes a scripted event to take place. During the event, the character who turned the quest in is killed. After the event ends, the quest giver revives the character. However the game doesn't acknowledge this revival and still considers the character "dead" until relogging.

![](http://i.imgur.com/WSpMPGx.jpg)
![](http://i.imgur.com/1t7oKYD.jpg)

**Comment by Cidragon** [comment]
It's working perfectly now.
