### ISSUE TITLE
"Storm, Earth and Fire" Monk spell

### ISSUE THREAD

**Issue by lloydbuckley** [Valhalla-Gaming/Tracker#2938]
Storm, Earth and Fire is supposed to:  
Summon an elemental spirit to attack the target. The spirit mirrors your damaging abilities when attacking a target different than your own. Max 2 spirits. A single spirit taxes your body, reducing your damage and its damage by 30%. Two spirits reduce damage by 45%. Spirits last until cancelled or their target dies.

In reality it does NOTHING but leave a debuff on you that reduces your damage by 60%.

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/spell=137639/storm-earth-and-fire
