### ISSUE TITLE
Lava Burst

### ISSUE THREAD

**Issue by comandos07** [Valhalla-Gaming/Tracker#2958]
http://www.wowhead.com/spell=51505

This part from the spell is not working:

"Lava Burst will always deal a critical strike. If your Flame Shock is on the target"

**Comment by Tregeta** [comment]
@Djurdjevdan 
> Lava Burst deals more damage when you are restoration then when you are elemental. in fact it deals double the amount.
I am level 51 when I am writting this.
As restoration, my Lava Burst deals 1044 damage
As elemental, my Lava Burst deals 522 damage
I would love someone on higher levels to comfirm this is happening just in case.

**Comment by Tregeta** [comment]
#2266
