### ISSUE TITLE
[Quest] Respect for the Fallen

### ISSUE THREAD

**Issue by carminejackal** [Valhalla-Gaming/Tracker#2991]
http://www.wowhead.com/quest=13626/respect-for-the-fallen

You can't loot http://www.wowhead.com/item=45042/feeros-holy-hammer or http://www.wowhead.com/item=45043/the-purifiers-prayer-book from either corpse. 

You can't do anything to the corpses tbh (they don't seem to be targetable I think which may be part of the issue?)

**Comment by Tregeta** [comment]
fixed next update
