### ISSUE TITLE
Rams On The Lam (Quest)

### ISSUE THREAD

**Issue by emil494** [Valhalla-Gaming/Tracker#3004]
When you /whistle to the Stolen Lam are should they make a progression and run back to Amberstill Ranch. But they dont they dont.
Quest: http://www.wowhead.com/quest=25905/rams-on-the-lam
Stolen Ram: http://www.wowhead.com/npc=41539/stolen-ram

**Comment by silverjade** [comment]
https://github.com/HellscreamWoW/Tracker/issues/2706

**Comment by Lazyg33k** [comment]
still do nothing

**Comment by tribaljet** [comment]
Doing /whistle still doesn't trigger quest progress.

**Comment by Cidragon** [comment]
Fixed in December 25th changelog.
