### ISSUE TITLE
[Achievement] Fire-Watcher

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#3014]
http://www.wowhead.com/achievement=8721/fire-watcher
...and all previous from that series.
http://www.wowhead.com/item=102463/fire-watchers-oath

Item Fire-Watchers Oath cost nothing (should cost 100 timeless coins). After using it you should be able to collect bloody coins from PLAYERS only. Currently those coins drop from everything you kill on Timeless Isle.
And achievement Fire-Watcher does not reward a title.

**Comment by Collector-Valhalla** [comment]
Title reward part is now fixed.

**Comment by Tregeta** [comment]
Will refer to blood coin for rest of report, closing this one as title is achievement.
