### ISSUE TITLE
Time-lost Proto Drake

### ISSUE THREAD

**Issue by TheGallahad** [Valhalla-Gaming/Tracker#3015]
The mob was spawned but it is dead and slowly crawling somewhere. It can be found on the frozen river near K3. I feel bad for it.

**Comment by Damvs** [comment]
I find <a href="http://www.hostingpics.net/viewer.php?id=305028WoWScrnShot102515200252.jpg"><img src="http://img15.hostingpics.net/thumbs/mini_305028WoWScrnShot102515200252.jpg" alt="Heberger image" /></a> at Ulduar

**Comment by Damvs** [comment]
I find at Ulduar

**Comment by deadright** [comment]
Yeah, spawned, but unattackable :{

**Comment by yubashiri** [comment]
Seems that there are more that one spawned at once also on all points of map it can spawn. Just saw two of them laying like this unattackable within 20 sec of flying from each other. Also if you keep some time next to it you can see that some strange aura appears like every 20 seconds, like a spawning flash. (a blue light)

**Comment by Damvs** [comment]
I find 4 drake on the same location. 8o

**Comment by ahrimanlord** [comment]
me too!
even single move...:(

**Comment by Tregeta** [comment]
this will be fixed in the next update

**Comment by serenity-talador** [comment]
i meet him just now , incorrect target :/ 
![wowscrnshot_012516_165553](https://cloud.githubusercontent.com/assets/16447897/12556112/8d189df6-c384-11e5-80e8-4cf5d903dc6e.jpg)

**Comment by Tregeta** [comment]
@serenity-talador update on talador isn't live yet, Valhalla is usually ahead of updating at a more frequent date.

**Comment by avaliaran** [comment]
is this fixxed , is the time lost proto drake working now ? , and we not have to waste time on storm peaks for nothing :P
