### ISSUE TITLE
[Quest] Unholy Cow

### ISSUE THREAD

**Issue by carminejackal** [Valhalla-Gaming/Tracker#3022]
http://www.wowhead.com/quest=27060/unholy-cow
Needs scripted, an ambush happens while the player and the prince check out the scene. The player and the prince then fight off the attackers. The altar is there, but the bloody chunks leading to it aren't and since the prince doesn't follow you out to it, there's no ambush and no fight.

**Comment by Seregruth** [comment]
Quest is now obsolete.
