### ISSUE TITLE
[Quest] The Old Barracks

### ISSUE THREAD

**Issue by carminejackal** [Valhalla-Gaming/Tracker#3023]
http://www.wowhead.com/quest=27072/the-old-barracks
http://www.wowhead.com/npc=44814/crazed-cultist

This quest can't be completed due to the quest mobs being missing. Also http://www.wowhead.com/npc=50049/jack-bauden is missing as well. Thus you couldn't turn it in and get the follow up even if the cultists were present.

**Comment by Seregruth** [comment]
Quest is now obsolete.
