### ISSUE TITLE
Gorgrom the Dragon-Eater quest

### ISSUE THREAD

**Issue by Jo-King** [Valhalla-Gaming/Tracker#3029]
When I use Grisly Totem It just says requires Gorgroms corpse I even soloed Gorgrom as a rogue, took forever but it was fun, but it still said requires Gorgroms corpse.

**Comment by Guybrush-Hellscream** [comment]
Alliance : http://www.wowhead.com/quest=10802/gorgrom-the-dragon-eater
Horde : http://www.wowhead.com/quest=10723/gorgrom-the-dragon-eater

**Comment by Tregeta** [comment]
Working
