### ISSUE TITLE
Go To The Airfield [Quest]

### ISSUE THREAD

**Issue by emil494** [Valhalla-Gaming/Tracker#3030]
In the quest G To The Airfield do you have to take the Mathel's Flying Machine in Gol'Bolar Quarry to the Ironforge Airfield. But you cant take Mathel's Flying Machine up to the Ironforge Airfield couse you cant use it.
Quest: http://www.wowhead.com/quest=25998/get-to-the-airfield
Mathel's Flying Machine: http://www.wowhead.com/npc=41848/mathels-flying-machine#sounds

**Comment by Cidragon** [comment]
Fixed in December 25th changelog.
