### ISSUE TITLE
No Accounting For Taste [Quest]

### ISSUE THREAD

**Issue by emil494** [Valhalla-Gaming/Tracker#3033]
Decomposing Thistle Bear dosnt have Foul Bear Carcass Sample as I should.
Foul Bear Carcass Sample: http://www.wowhead.com/item=44911/foul-bear-carcass-sample
Quest: http://www.wowhead.com/quest=13527/no-accounting-for-taste
Decomposing Thistle Bear: http://www.wowhead.com/npc=32975/decomposing-thistle-bear

**Comment by zwei7** [comment]
I can't loot the bear to get a sample. I am trying to click but nothing.
![wowscrnshot_102315_040804](https://cloud.githubusercontent.com/assets/15259298/10687518/ab135654-793b-11e5-86e2-a5cb37c19011.jpg)

**Comment by Tregeta** [comment]
Fixed next update
