### ISSUE TITLE
Specializations

### ISSUE THREAD

**Issue by unfairplayer** [Valhalla-Gaming/Tracker#3052]
There's somewhat complicated issue I am having. The problem is that now every time I relog my Marksman Hunter is using Survival talents, despite icons remaining same and it stays that way until I activate to Survival then back to Marksman. It even has the side effect of different Talents losing their cooldown such as Powershot.

**Comment by Moustachos** [comment]
Can't reproduce this bug, looks like a character-specific issue.

Closing it, please contact a GM.

**Comment by Moustachos** [comment]
Ref #2266
