### ISSUE TITLE
Monk Talent: Momentum

### ISSUE THREAD

**Issue by Daduka** [Valhalla-Gaming/Tracker#3059]
Hello Hellscream Team,

Monk talent: Momentum doesn't works :(
Talent link: > http://www.wowhead.com/spell=115174/momentum <

Please fix this issue.

Thanks :))

Best regards,
DADA

**Comment by Daduka** [comment]
Hello Hellscream Team,

Please fix this issue it's very important! I send it 17 days ago... Please little bit faster...

Thanks for everything.

Best regards,
DADA

**Comment by GMTyrial** [comment]
Note : I was told that this works when dead, but not alive
