### ISSUE TITLE
Emergency Protocol: Section 8.2. Paragraph D (quest)

### ISSUE THREAD

**Issue by Steliosven** [Valhalla-Gaming/Tracker#3069]
Issue: when i use the Emergency Torch close to the Crashed Flying Machine.
It says requires Crashed Flying Machine.
![wowscrnshot_101915_022950](https://cloud.githubusercontent.com/assets/13372305/10567341/28fff854-760a-11e5-8ddf-50c6713a23e4.jpg)

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/quest=11796/emergency-protocol-section-8-2-paragraph-d

**Comment by K-Reeboo** [comment]
As of today, even though some wreckages does not work, quest can still be finished.
Just have to try all wreckages.

**Comment by Cidragon** [comment]
This is working fine now.
