### ISSUE TITLE
Rejuvenation

### ISSUE THREAD

**Issue by bubbles3008** [Valhalla-Gaming/Tracker#3077]
The spell seems bugged.

if you get the passive talent " mighty Rejuvenation" it should increase the time on the target to 18 secounds its only 16 secounds at the moment.

http://www.wowhead.com/spell=774/rejuvenation

the glyph that should increase the time on target by 3 secounds dont work, too.

**Comment by Moustachos** [comment]
This is working as intended, default duration of Rejuvenation is 12 sec, Might Rejuvenation passive adds 3 seconds so you get a 15 sec HoT.

What is the glyph you're talking about?

**Comment by Moustachos** [comment]
Ref #2266
