### ISSUE TITLE
[Quest] Don't Look Them in the Eyes

### ISSUE THREAD

**Issue by phikaro** [Valhalla-Gaming/Tracker#3080]
Issue: The required objects are not spawned in the cave, so I cannot complete it. :3

Link: http://www.wowhead.com/quest=25642/dont-look-them-in-the-eyes

**Comment by zwei7** [comment]
Don't see any Azure Iron ore here
![wowscrnshot_103115_030826](https://cloud.githubusercontent.com/assets/15259298/10862409/b82f31fe-7f7c-11e5-9357-b4a8ad246f9a.jpg)

**Comment by Klickeazy** [comment]
I managed to get exactly 2 ores as drops after almost half and hour of cleaning out the entire cave repeatedly. The original request requires the peons to be carrying pieces of ore which they will throw down to fight you. You get to pick them up when they die. Don't know how I got those 2 ores to drop but for 2.1k quest experience, too much to stay at it till 10 ores collect

**Comment by zwei7** [comment]
half an hour!?

**Comment by Klickeazy** [comment]
Started off mid way level 28 and ended at almost 30 when I got sick of the peons' and overseers' dying audio :P

**Comment by Tregeta** [comment]
fixed next update
