### ISSUE TITLE
[Achievements] Going Down? & Quest report

### ISSUE THREAD

**Issue by phikaro** [Valhalla-Gaming/Tracker#3097]
Issue: When accepting the quest Teldrassil: Passing Awareness, the npc buffs my character with spell "winds embrace " that slow my fall speed, so when jumping off the top of the tree with winds embrace buff, I do not get the achievement "Going Down?".

http://www.wowhead.com/quest=28731/teldrassil-passing-awareness#comments

Also when turning in the quest "Teldrassil: Passing Awareness" it does not activate Shade of the Kaldorei NPC which continues a story, here's the whole conversation taken from Wowhead comment:

Shade of the Kaldorei smiles at you knowingly as it approaches.
Shade of the Kaldorei says: With Malfurion Stormrage gone, the druids were left in disarray and in desperate need of a new leader.
Shade of the Kaldorei says: Arch Druid Fandral Staghelm roused the druids and convinced the Circle of Ancients in Darkshore that it was time for our people to rebuild.
Shade of the Kaldorei says: In an effort to regain immortality for our people, and with the approval of the Circle, Staghelm and the most powerful druids grew Teldrassil, upon whose boughs you now stand.
Shade of the Kaldorei says: Though we have our new home, our immortal lives have not been restored.
The Shade of the Kaldorei closes its eyes and fades away.

**Comment by vation1234** [comment]
the work is achievement "Going Down".

**Comment by phikaro** [comment]
What do you mean?

**Comment by Cidragon** [comment]
Everything is working now :)
