### ISSUE TITLE
[Hunter] Bugged Auto-Heals

### ISSUE THREAD

**Issue by strangefolk1** [Valhalla-Gaming/Tracker#3122]
Since the explosive shot-lone wolf-buffs fix, Hunter no longer auto-heals.
Both Kill Shot (Markmanship) and Survivalist passive (Survival) aren't working anymore.
Only healing skill working is the secondary effect on Camouflage, while the primary one isn't.

**Comment by strangefolk1** [comment]
Any news on this? It's almost two months now.

**Comment by Malae1** [comment]
Killshot ref https://github.com/HellscreamWoW/Tracker/issues/3589  [Survivalist](http://www.wowhead.com/spell=164856/survivalist)

**Comment by Moustachos** [comment]
Kill Shot's heal for Marksmanship was fixed on previous update.

Survivalist works fine.

**Comment by Moustachos** [comment]
Ref #2266
