### ISSUE TITLE
Guild Ranks

### ISSUE THREAD

**Issue by danirzv** [Valhalla-Gaming/Tracker#3126]
There is a bug with guild ranks as blow
think name of first default ranks are as blow
1.Guild master
2.Rank 2
3.Rank 3
4.Rank 4
5.Rank 5

now i create a new rank named NEW RANK and put it in the 2nd step of ranks with high access to guild. and now it is as blow:
1.Guild master
2.NEW RANK
3.Rank 2
4.Rank 3
5.Rank 4
6.Rank 5

if now you invite some one in guild that guy will start as NEW RANK !!!
and when you make some one with RANK 5 to NEW RANK it call DEMOTED!!!
but new member should be RANK 5...
and change rank from RANK 5 to NEW RANK is PROMOTED...

**Comment by danirzv** [comment]
any update?

**Comment by Malae1** [comment]
In due time

**Comment by danirzv** [comment]
after 19 days, still no update about a simple bug?!

**Comment by Malae1** [comment]
It's not that 'simple'
