### ISSUE TITLE
Companions and hunter pets

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#3131]
Companion pets should stay by your side when you mount up (and walk at same speed as you do) unless of course you're flying.

And same thing for hunter pets. They should be near you when you're mounted on ground, disappear when you start to fly and reappear when you land on ground (and they should have same speed as you do don't forget about that). 
(I'm not sure about their behavior to mobs while you are mounted but I think they don't attack npcs and have some lower aggro range if any. Some could confirm?)

That doesn't affect warlocks or frost mages. Their pets are not around while mounted.

**Comment by EPS1L0N** [comment]
> I think they don't attack npcs and have some lower aggro range if any

This is correct.
Hunter pets are set to passive when the player mounts. Abilities cannot be used while the player is mounted, including switching react state.
