### ISSUE TITLE
quest theyre-alive-maybe  in  Bloodmyst Isle.

### ISSUE THREAD

**Issue by Lazyg33k** [Valhalla-Gaming/Tracker#3133]
http://www.wowhead.com/quest=9670/theyre-alive-maybe

i think wrong mob spawn from the cocoon i got a brown bear some murlock some boss from naga i'm not sure but they not suposed to spwn from this lol

**Comment by Pure-Valhalla** [comment]
This is intended when there is an agressive mob in the cocoon. Not all of them will be the Expedition Researchers. Quest is working as intended.
