### ISSUE TITLE
Quest Don't Drink the Water in Bloodmyst Isle.

### ISSUE THREAD

**Issue by Lazyg33k** [Valhalla-Gaming/Tracker#3134]
http://www.wowhead.com/quest=9748/dont-drink-the-water

this quest not working not abble to gather water anywhere !

**Comment by zwei7** [comment]
Can't gather water at the waterfall. Quest item (flask) doesn't realize I am at the waterfall.
![wowscrnshot_112015_022404](https://cloud.githubusercontent.com/assets/15259298/11294014/e2d7525e-8f2d-11e5-8d0d-365f26f5ae94.jpg)

**Comment by Tregeta** [comment]
fixed next update.
