### ISSUE TITLE
Rogue Vanish Bug

### ISSUE THREAD

**Issue by jenloe** [Valhalla-Gaming/Tracker#3136]
For the first 3 seconds of vanish if you take damage its not suppose to break stealth, it does break stealth in that 3 second period. Its also suppose to have improved stealthed buff for that 3 second period it does not.

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/spell=1856/vanish

**Comment by Moustachos** [comment]
Ref #2266
