### ISSUE TITLE
Death from above and Shadow Reflection

### ISSUE THREAD

**Issue by Hangun** [Valhalla-Gaming/Tracker#3168]
_When i used Death from Above it s only cause damage when whirl around but not leap into the air and not use Eviscerate on the way back down: 
http://www.wowhead.com/spell=152150/death-from-above.
_ Shadow Reflection doesnt summon shadow instead it only summon one golem do about 9 damage each sec:
http://www.wowhead.com/spell=152151/shadow-reflection.

**Comment by Tregeta** [comment]
Fixed Death from Above

**Comment by Moustachos** [comment]
Ref #2266
