### ISSUE TITLE
[Hunter] Chimaera Shot not work

### ISSUE THREAD

**Issue by sgrvsml** [Valhalla-Gaming/Tracker#3171]
The damage done is far below what it should do.

**Comment by silverjade** [comment]
Could you give more in depth detail? What dmg should it be doing? What dmg is it doing?

**Comment by sgrvsml** [comment]
OK sorry. The spell says it does 1 296 p . damage to each one of two targets . But in reality  only my auto shot is activated .

I 'm level 61 and use a heirloom as a weapon.

**Comment by EPS1L0N** [comment]
#2266
