### ISSUE TITLE
[Quest] Ears of Our Enemies & Can't Get Ear-nough...

### ISSUE THREAD

**Issue by carminejackal** [Valhalla-Gaming/Tracker#3175]
http://www.wowhead.com/quest=11866/ears-of-our-enemies
http://www.wowhead.com/item=35188/nesingwary-lackey-ear
http://us.battle.net/wow/en/item/35188

The drop rate is lower than it should be. Also the quest giver doesn't offer http://www.wowhead.com/quest=11867/cant-get-ear-nough after the completion of Ears of Our Enemies.

**Comment by Tregeta** [comment]
drop rate was adjusted

**Comment by Tregeta** [comment]
fixed next update
