### ISSUE TITLE
[Alchemy] can not be uploaded to 600

### ISSUE THREAD

**Issue by ricardoesl** [Valhalla-Gaming/Tracker#3183]
http://www.wowhead.com/spell=114752 http://www.wowhead.com/spell=114751 They do not work because you can create, but do not give new recipes of Pandaria. Reason that not alchemy can climb to more than 635

and created more than 1,000 each potions and do not give me new recipes or potions bottles of Pandaria

**Comment by Tregeta** [comment]
fixed previous update
