### ISSUE TITLE
Feral Spirit

### ISSUE THREAD

**Issue by Beponator** [Valhalla-Gaming/Tracker#3195]
http://www.wowhead.com/spell=51533/feral-spirit it should heal the caster and them each hit.

**Comment by Tregeta** [comment]
@Dkwhitenoise
> Feral spirit - wolves are bugged. After u used a spell, one wolf is bugged and he vaporize. Then u have just one wolf.
http://www.wowhead.com/spell=51533/feral-spirit#summons
value 2

**Comment by Moustachos** [comment]
Ref #2266
