### ISSUE TITLE
Métier enchanteur

### ISSUE THREAD

**Issue by Golluminette** [Valhalla-Gaming/Tracker#3207]
Bonjour.
Je n'arrive pas à désenchanter certains objets alors que j'ai largement le niveau requis et le message d'erreur suivant s'affiche :
Doit avoir équipé : %s

**Comment by Lazyg33k** [comment]
traduction 
Hello.
I can not disenchant some items so that I broadly the required level and the following error message :
Must have equipped: % s

**Comment by Damvs** [comment]
Same with my inscription :(

**Comment by Tregeta** [comment]
Fixed previous update
