### ISSUE TITLE
Mage bugs

### ISSUE THREAD

**Issue by Frajzla** [Valhalla-Gaming/Tracker#3211]
Glowing hands animation after i cast spell, frozen orb is going up and down not foward and mirror image isint working. thank you

**Comment by Guybrush-Hellscream** [comment]
What's not working with Mirror Image?

**Comment by Frajzla** [comment]
When you cast it, only animation is shown but no mirror images, and no
cooldown on it

**Comment by nuhrii** [comment]
As of Legion Frozen Orb does nothing
