### ISSUE TITLE
Balance | Lunar / Solar Energy

### ISSUE THREAD

**Issue by Milendra** [Valhalla-Gaming/Tracker#3213]
Balance Specialization 

Multiple thing, but i think the main problem is the "Balance" meter

During the Lunar Energy part, i can still use "moonfire" without any problem, and "Lunar Peak" does apply to the "Moonfire" (as well as the dot) as intended. As for the Solar Energy part, when "Moonfire" becomes "Sunfire", the latter deals no damage at all, nor applies any dots. 

I also noticed that (and you can see it as well in the screenshots) that my Balance meter was completely de-synchronized, using "MoonFire" during "Solar Peak"

![wowscrnshot_102615_120441](https://cloud.githubusercontent.com/assets/15317889/10721138/03208826-7bda-11e5-887c-25d29151cc8e.jpg)
![wowscrnshot_102615_120447](https://cloud.githubusercontent.com/assets/15317889/10721139/03220548-7bda-11e5-9c0c-d28089bbfffd.jpg)

**Comment by EPS1L0N** [comment]
note for others: it gets more and more out of sync with the server the longer you are in combat, pretty big issue for long fights

**Comment by EPS1L0N** [comment]
#2266
