### ISSUE TITLE
Repeatable quests for : Steamwheedle Preservation Society

### ISSUE THREAD

**Issue by bubbles3008** [Valhalla-Gaming/Tracker#3215]
the quests for the fraction:  Steamwheedle Preservation Societyin Nagrand should be repeatable. as i quit this quests once, they wasnt available anymore. may you have a look on it

http://de.wowhead.com/achievement=9472/werterhaltungsgesellschaft-des-dampfdruckkartells#english-comments

**Comment by Guybrush-Hellscream** [comment]
http://www.wowhead.com/achievement=9472/steamwheedle-preservation-society#english-comments

**Comment by Tregeta** [comment]
fixed next update
