### ISSUE TITLE
Wandering Isle - quest [The Lesson of the Iron Bough]

### ISSUE THREAD

**Issue by Max-Valhalla** [Valhalla-Gaming/Tracker#322]
"http://www.wowwiki.com/Quest:The_Lesson_of_the_Iron_Bough
After completing this quest the weapon is remove."

**Comment by carminejackal** [comment]
Also currently you can't loot the weapons from the weapon racks and thus can't equip them to complete this quest. I tried relogging, deleting cache, and disabling all addons, and while the racks 'glow' you can't interact with them.

**Comment by Tregeta** [comment]
Fixed next update
