### ISSUE TITLE
Mage bugs!

### ISSUE THREAD

**Issue by Eluniver** [Valhalla-Gaming/Tracker#3221]
Triggering the Ice Floes talent allows us to cast and move indefinitely, making all of our spells for the duration of the effect able to be cast while moving! (even if I only have 1 Ice Floe triggered)
Also, the Arcane Explosion spell does not refresh the duration of my Arcane Charges, instead it consumes them, disrupting my DPS output. Thank you in advance!

Edit: I've also noticed, now that I have my Arcane Missiles, that they also consume all of my Arcane Charges, instead of just consuming one. I do not get the symbol prompt ( The 1/3 of violet at the top of my screen). Also, Arcane Missiles proc way too often!

**Comment by Guybrush-Hellscream** [comment]
Ice Floes : http://www.wowhead.com/spell=108839/ice-floes
Arcane Explosion : http://www.wowhead.com/spell=1449/arcane-explosion
Arcane Missiles : http://www.wowhead.com/spell=5143/arcane-missiles

**Comment by EPS1L0N** [comment]
Ice Floes has been fixed #2266
