### ISSUE TITLE
[Quest] [New Tinkertown] A Job for the Multi-Bot

### ISSUE THREAD

**Issue by phikaro** [Valhalla-Gaming/Tracker#3232]
Issue: When the robot cleans up the toxic, then the toxic its self does not disappear from the lake as on retail. And if I wait a bit longer, like 5-10 minutes and then the robot disappears, before I even finish the whole quest, I have to re accept it and do it again, I think the robot disappears if I become afk. Also when turning in the quest, the robot does not disappear, it continues to follow me around like a pet.

Link: http://www.wowhead.com/quest=26205/a-job-for-the-multi-bot

Edit: The robot is disappearing on retail as well, but on retail there is an option in dialog window when talking to the questgiver, to lend you another robot, instead of having to re-accept the quest. But on HellscreamWoW there is no such option when talking to the questgiver.

**Comment by Cidragon** [comment]
This is working as intented now.
