### ISSUE TITLE
[Quest] [New Tinkertown] Down with Crushcog!

### ISSUE THREAD

**Issue by phikaro** [Valhalla-Gaming/Tracker#3239]
Issue: Stuck on this quest, as I do not get the option in dialog window to start the event when talking to High Tinker Mekkatorque.

http://www.wowhead.com/quest=26364/down-with-crushcog

**Comment by pourisse** [comment]
Same problem here, on Midgar, can't speak with Mekkatorque so can't launch the script and finish the quest
