### ISSUE TITLE
Mor'Vek in Ungoro Crater

### ISSUE THREAD

**Issue by Max-Valhalla** [Valhalla-Gaming/Tracker#325]
See comments for update on quest.

**Comment by MrBleh** [comment]
Can grab the quest fine, but it seems that It can't be completed, no matter how long I attack the things. 

http://www.wowhead.com/quest=13850/toxic-tolerance

**Comment by Tregeta** [comment]
Is it not giving credit for  
	Splashed with Venomhide blood (20)?

**Comment by MrBleh** [comment]
It is but I have no idea how. After my comment I was still killing dinos and I afk. When I came back I was dead (obviously) but had 1/20 venomhinde blood. So i tried some more, but I cant get it by just fighting. Haven't tried dying more tho.

**Comment by Tregeta** [comment]
As the video from https://www.youtube.com/watch?v=fiWl-rRXXk8 suggests it takes quite a bit of time to get these samples to hit, let us know if you're still having difficulties with this quest after viewing.

**Comment by MrBleh** [comment]
I've seen it, and have been trying the same for a while now, and even though in the video you can get like 1/2 per dino, I still haven't got any. and I'm a mistweaver monk, unequiping the weapon and killing them with auto attacks only

**Comment by MrBleh** [comment]
I'm an idiot, and I'm sorry. I have been attacking regular ravasaurs for hours. Again, so sorry. It works fine
