### ISSUE TITLE
Hunter Talent - Thrill of the Hunt

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#3270]
http://www.wowhead.com/spell=109306/thrill-of-the-hunt

Issue is same as warriors Sudden Death talent. 
Chance to trigger Thrill of the Hunt effect is 100% (should be 6% per 10 focus used) and it's not consumed after 3 charges (3 arcane shots or aimed shots or multi-shots). Instead it last 15 seconds but since it has 100% chance to proc it actually last as long as hunter attacks.

**Comment by Tregeta** [comment]
@Strale2
> So apart that it works like there is 6% chance per focus spent (instead per 10 focus spent) and it doesn't proc on Black Arrow ability,
This ability is not triggering spell alert which I have enabled. Spell alerts are working properly for debuffs like stun, silence or disorientation but they never show up to let me know my ability is ready.

**Comment by Moustachos** [comment]
Ref #2266
