### ISSUE TITLE
Quest: Check in on the Edunes

### ISSUE THREAD

**Issue by zwei7** [Valhalla-Gaming/Tracker#3310]
This quest is automatically complete once you accept the quest from this NPC
![wowscrnshot_102915_164952](https://cloud.githubusercontent.com/assets/15259298/10831636/309cfdae-7e5d-11e5-9123-eb8cf38d9759.jpg)

**Comment by Cidragon** [comment]
It's working as intended.
Video proof: https://www.youtube.com/watch?v=4bNcS0uK_mw
