### ISSUE TITLE
[NPC] Rai'Vosh 

### ISSUE THREAD

**Issue by Luminescent-Hellscream** [Valhalla-Gaming/Tracker#3326]
Currently the Rare Mob Rai'Vosh is missing from his location in Shadowmoon Vally (WoD Version) 

www.wowhead.com/npc=82374/raivosh

http://i.imgur.com/UkciPCX.jpg

**Comment by Tregeta** [comment]
fixed next update

**Comment by Traveler-Valhalla** [comment]
#7916
