### ISSUE TITLE
Graveyard at Shattershore in Blastedlands is broken!

### ISSUE THREAD

**Issue by Max-Valhalla** [Valhalla-Gaming/Tracker#334]
When you die and release your spirit, it spawns you underground and you fall endlessly. If you click return to graveyard on the top of your screen it just restarts your fall. I am now a ghost that just falls into the void forever :( pleas fix.

**Comment by MythicBird** [comment]
Same issue here.

**Comment by Trekex** [comment]
This seems to not happen anymore
