### ISSUE TITLE
(QUEST) Standards and Practices

### ISSUE THREAD

**Issue by jfdaigle** [Valhalla-Gaming/Tracker#3350]
Quest item doesn't work.  Says " Requires Burning Blade pyre in the Burning Blade Ruins"  All 3 places don't work.

http://www.wowhead.com/quest=9910/standards-and-practices

https://www.youtube.com/watch?v=IBJIr4egFEw

**Comment by Cidragon** [comment]
Fixed in December 5th changelog.
