### ISSUE TITLE
[Rogue] Kidney Shot with Internal Bleeding talent

### ISSUE THREAD

**Issue by Aveta** [Valhalla-Gaming/Tracker#3384]
http://www.wowhead.com/spell=408/kidney-shot and the related talent http://www.wowhead.com/spell=154904/internal-bleeding
Sometimes when using the skill the bleed is applied, the skill goes on cooldown, BUT the target isn't stunned (we're talking about target that's not resistant to stuns) and the combo points aren't spent.

**Comment by Malae1** [comment]
Last Spell related #1321, #3375. For the others, we ask that you create separate issues entirely for these so that they can be handled one at a time, editing posts will take up more time than needed.

**Comment by Aveta** [comment]
Sure thing, going to do it now.

**Comment by EPS1L0N** [comment]
not related to #1321

**Comment by Moustachos** [comment]
Can't reproduce this issue.

**Comment by Moustachos** [comment]
Ref #2266
