### ISSUE TITLE
They Took Our Men!

### ISSUE THREAD

**Issue by Steliosven** [Valhalla-Gaming/Tracker#3394]
In the quest <a href=''http://www.wowhead.com/quest=12843/they-took-our-men''>They Took Our Men!</a> the goblins are not in cages to free them.
![wowscrnshot_103115_233311](https://cloud.githubusercontent.com/assets/13372305/10866118/e8368aec-802a-11e5-9417-3e4a0a3891bb.jpg)

**Comment by excreed424** [comment]
This quest works now.
