### ISSUE TITLE
[Rogue] Rupture

### ISSUE THREAD

**Issue by Aveta** [Valhalla-Gaming/Tracker#3397]
http://www.wowhead.com/spell=1943/rupture
The spell is very clunky when using. Sometimes I hear the sound of the ability, but it isn't actually applied and it doesn't consume the combo points, forcing me to attempt usage at least one time more. Having to use it twice or thrice before it actually works is pretty common.

**Comment by Moustachos** [comment]
Can't reproduce on current version.

**Comment by Moustachos** [comment]
Ref #2266
