### ISSUE TITLE
Dun Morogh

### ISSUE THREAD

**Issue by Max-Valhalla** [Valhalla-Gaming/Tracker#343]
"Quest: Pushing Forward --> http://www.wowhead.com/quest=25792/pushing-forward
Bug: U can use the quest item Rune of Fire --> http://www.wowhead.com/item=56009/rune-of-fire on the totems but u don't receive the the credit for that

Quest: Entombed in Ice --> http://www.wowhead.com/quest=25978/entombed-in-ice
Bug: Frozen Mountaineers are there on the ground but there are no Icy Tombs on top of them http://www.wowhead.com/npc=41768/icy-tomb

Quest:  Oh, A Hunter's Life For Me --> http://www.wowhead.com/quest=24530/oh-a-hunters-life-for-me
Bug: U receive the credit for learning Steady Shot --> http://www.wowhead.com/spell=56641/steady-shot but u don't receive the credit for using the spell on Training Dummies."

**Comment by Guybrush-Hellscream** [comment]
Pushing Forward : works but the wrong way (by killing totems)
The View from Down Here : works
Priceless Treasures : works
The Public Servant : works

**Comment by Doriathrim** [comment]
Pushing Forward: Works fine
Entombed in Ice: Works fine
Oh, A Hunter's Life For Me: This quest was marked obsolete by Blizzard and cannot be obtained or completed.
