### ISSUE TITLE
Posthaste

### ISSUE THREAD

**Issue by Max-Valhalla** [Valhalla-Gaming/Tracker#346]
"Spell: Posthaste --> http://www.wowhead.com/spell=109215/posthaste#changelog
Bug: Don't receive the speed increase after Disengage

Spell: Kill Command --> http://www.wowhead.com/spell=34026/kill-command
Bug: Doesn't do any damage....but it take's the focus and cooldown

Glyph: Glyph of Liberation --> http://www.wowhead.com/spell=132106/glyph-of-liberation
Bug : Doesn't heal u after u Disengage"

**Comment by Reloque** [comment]
All of these are hunter-exclusive.
Posthaste is a talent
Kill Command is only for Beastmaster specialization

**Comment by Moustachos** [comment]
Ref #2266
