### ISSUE TITLE
More Warbeads Quest

### ISSUE THREAD

**Issue by TheGallahad** [Valhalla-Gaming/Tracker#3481]
according to http://www.wowhead.com/quest=10477/more-warbeads this quest gives 500rep but it only gives 250rep.

**Comment by ATalisan** [comment]
Confirmed still only giving 250 reputation when it should be rewarding 500.
Alliance side, Kurenai Reputation.

**Comment by Cidragon** [comment]
Fixed in December 5th changelog.
