### ISSUE TITLE
Shadowy Insight and SW:Death

### ISSUE THREAD

**Issue by ky0jr** [Valhalla-Gaming/Tracker#3496]
Shadowy Insight doesn't reset cooldown but instant cast work
SW:Death doesn't generate shadow orb and the reset cooldown doesn't work

**Comment by Malae1** [comment]
Ref #2266

**Comment by Tregeta** [comment]
@Collector-Valhalla

> http://www.wowhead.com/spell=162452/shadowy-insight 
Procs from [Devouring Plague](http://www.wowhead.com/spell=2944/devouring-plague) aswell. It shouldn't. 
Also cooldown of [Mind Blast](http://www.wowhead.com/spell=8092/mind-blast) does not reset.

**Comment by Moustachos** [comment]
Shadow Word: Death part of the issue will be fixed on next update.

**Comment by Collector-Valhalla** [comment]
Also that Shadowy Insight buff is not consumed after using Mind Blast. It should be.
