### ISSUE TITLE
Quest "Wisps of the Woods" quest object bug

### ISSUE THREAD

**Issue by tribaljet** [Valhalla-Gaming/Tracker#3499]
http://www.wowhead.com/quest=28383/wisps-of-the-woods

Quest object Swiftwind Switch doesn't guide quest NPCs Talonbranch Wisps to NPC Lyros Swiftwind, the item just makes a cast animation and nothing more.

**Comment by Nimes-Hellscream** [comment]
Quest item given - Swiftwind Switch - ID: 64300
http://www.wowhead.com/item=64300/swiftwind-switch

NPC's that is effects - Talonbranch Wisps - ID: 48454
http://www.wowhead.com/npc=48454/talonbranch-wisp

**Comment by Cidragon** [comment]
Fix quest was fixed on November 25 changelog.
