### ISSUE TITLE
(Rogue) Spell Bug. 

### ISSUE THREAD

**Issue by Ulquira** [Valhalla-Gaming/Tracker#3503]
I found a pair un error rogue .

Spell http://www.wowhead.com/spell=5938/shiv the second which gives a bonus of some active poison. This does not work in any Peppermint .

They also sugieron the reivison the flood of steel. Which does not apply the appropriate percentage of damage in my opinion .

Thank you. Keep up the nice work!

:+1:

**Comment by Malae1** [comment]
When did rogues get a peppermint?

**Comment by Ulquira** [comment]
Sorry, translator use since I do not speak very good English. haha lol

**Comment by Moustachos** [comment]
Until you specify which effect isn't working (= on which poison), I'm closing the issue.

**Comment by Moustachos** [comment]
Ref #2266
