### ISSUE TITLE
"The Crone" Karazhan Opera Encounter

### ISSUE THREAD

**Issue by GeneralCaveman** [Valhalla-Gaming/Tracker#3539]
http://www.wowhead.com/npc=18168/the-crone#comments

For the "Oz" Opera encounter, once you kill all of the other NPCs, The Crone does appear. However she is not able to be aggro'd and is an invalid target for spells. This makes the encounter not be able to be completed and stops the player from further accessing the dungeon. You also can't backtrack so the only way off the stage is teleporting some way or another.

![wowscrnshot_111215_030358](https://cloud.githubusercontent.com/assets/12555606/11113336/0317978a-88ea-11e5-8651-d8337d550c5d.jpg)

**Comment by Traveler-Valhalla** [comment]
guys this is fixed now

**Comment by GM-Pyromanic** [comment]
Thank you for letting us know I will go ahead and close the report should the encounter become broken in the future please open a new report for the issue.
