### ISSUE TITLE
[Class][Spell] Shaman Totems.

### ISSUE THREAD

**Issue by Althin** [Valhalla-Gaming/Tracker#3541]
I. "Stone Bulwark Totem"  [ http://www.wowhead.com/spell=108270/stone-bulwark-totem] - This totem should give us bubble with absorb for some damage. For now it gives nothing.
II. "Earthgrab Totem" [http://www.wowhead.com/spell=51485/earthgrab-totem] - This totem should grab enemies in the roots. At this moment this totem don't work.
III. "Searing Totem" [http://www.wowhead.com/spell=3599/searing-totem]- This totem should attack only target that is attacked by his owner or target that got Flame Shock. Actually totem engage everything that is all around, no matter it is neutral or unfriendly target.

Those problems are on 35 lvl, I will update this if I found more bugs. Greetings Althin :)

**Comment by Rushor** [comment]
open up one one ticket/issue

**Comment by Althin** [comment]
Healing Stream works now.

**Comment by EPS1L0N** [comment]
> Healing Stream works now. Rushor, better is open more bugs in one ticket for Devs.

one bug per ticket is easier to deal with and easier to organize but we don't really mind, a bug is a bug.

**Comment by HellscreamWoW** [comment]
@Rushor We have an interesting story for you. If you'd like to hear it, PM Max on the Hellscream forum.
http://hellscream-wow.com/forum

**Comment by Malae1** [comment]
Ref #2266

**Comment by zwei7** [comment]
The searing totem sometimes doesn't even attack enemies in range that are killing me and I have them targeted. It's main priority is to attack critters (rabbits, frog, rats, etc).

**Comment by Moustachos** [comment]
Ref #2266
