### ISSUE TITLE
Skills: 0 Dmg in PvP (DK)

### ISSUE THREAD

**Issue by iccX** [Valhalla-Gaming/Tracker#3586]
Howling Blast 0 dmg
Blood Boil 0 dmg
Death and Decay 0 dmg
Death Coil around 700 dmg at lvl 100
Might of the Frozen Wastes dual wield (Weapon strikes don`t strike with offhand as it should)
Icy Touch 0 dmg
Breath of Sindragosa 0 dmg.

I really think you should fix this before or at the same time u fix Rune of the Fallen Crusader otherwise DK will be useless

**Comment by Tregeta** [comment]
Spells now do damage in pvp
