### ISSUE TITLE
Kill Shot

### ISSUE THREAD

**Issue by unfairplayer** [Valhalla-Gaming/Tracker#3589]
I believe to have noticed a bug regarding the Kill Shot ability of Marksmanship Hunters. It's supposed to have limited reset if target is not killed (6 second cooldown on resetting) and heal the player for 15% if the target is killed. I didn't notice any of these occurring properly except for maybe a really few times when it seemed to reset once. The problem seems to be happening since server updated to patch 6.2.2.

**Comment by Malae1** [comment]
[Kill Shot](http://www.wowhead.com/spell=53351/kill-shot)

**Comment by Moustachos** [comment]
Ref #2266
