### ISSUE TITLE
Missing MOBs: Badlands, Uldaman, Excavation Center

### ISSUE THREAD

**Issue by zwei7** [Valhalla-Gaming/Tracker#3593]
When entering the area just outside the Uldaman Dungeon, most MOBs are missing. It is an underground cavern with campfire and tents. I think dwarves should be here.
![wowscrnshot_111515_105950](https://cloud.githubusercontent.com/assets/15259298/11169517/06bd75c6-8b88-11e5-87e1-a1745fd4d9f1.jpg)

Mobs are located in 2 places only as shown by my location below.
![wowscrnshot_111515_115450](https://cloud.githubusercontent.com/assets/15259298/11169828/939a8184-8b90-11e5-93f2-b0d3f9794523.jpg)
![wowscrnshot_111515_115634](https://cloud.githubusercontent.com/assets/15259298/11169829/95c3305a-8b90-11e5-96d8-1545be0754f6.jpg)

**Comment by Tregeta** [comment]
fixed next update
