### ISSUE TITLE
Improved Flame Shock

### ISSUE THREAD

**Issue by Amnezie** [Valhalla-Gaming/Tracker#3595]
Improved Flame Shock ( http://www.wowhead.com/spell=157804/improved-flame-shock ) don't reset the lava lash cooldown.

**Comment by KwitUrBichn** [comment]
There is only a 15% chance of this happening. Is it never happening?

**Comment by Amnezie** [comment]
Well never happened and i play a 100 shaman for months

**Comment by Moustachos** [comment]
Ref #2266
