### ISSUE TITLE
Warrior Bonus Armor Stats

### ISSUE THREAD

**Issue by RealFlex** [Valhalla-Gaming/Tracker#3606]
Bonus Armor from items is not show/add any stats. i have 3 items with bonus Armor and in my character info Bonus Armor stats is 0

**Comment by RealFlex** [comment]
also Bonus Armor must Increases Attack Power

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #2266
