### ISSUE TITLE
Quest: Ysondre's Farewell

### ISSUE THREAD

**Issue by zwei7** [Valhalla-Gaming/Tracker#3644]
The chicken will not move for you to escort it. The quest is also auto completed upon accepting it.
http://www.wowhead.com/quest=25438/ysondres-farewell
![wowscrnshot_111715_154826](https://cloud.githubusercontent.com/assets/15259298/11224995/c989d61c-8d45-11e5-9d0b-3693eaed2a7b.jpg)

**Comment by Cidragon** [comment]
This is the wrong quest. Please check #3513
