### ISSUE TITLE
Quest: Follow that Gyro-copter 

### ISSUE THREAD

**Issue by zwei7** [Valhalla-Gaming/Tracker#3654]
The Quest NPC you are supposed to turn this into is missing.
http://www.wowhead.com/quest=24491/follow-that-gyro-copter
They should be here.
![wowscrnshot_111815_174550](https://cloud.githubusercontent.com/assets/15259298/11256866/6115186c-8e1c-11e5-8968-bcb2c961ff3c.jpg)

**Comment by Malae1** [comment]
Looks to be phased.

**Comment by Guybrush-VR** [comment]
Indeed, it was phasing! Fixed in next update. :palm_tree:
