### ISSUE TITLE
Shield of the Righteous

### ISSUE THREAD

**Issue by Max-Valhalla** [Valhalla-Gaming/Tracker#366]
"http://www.wowhead.com/spell=53600/shield-of-the-righteous

Shield of the righteous has stopped working since the big patch.  It can not be cast nor does it use holy power."

**Comment by ticklex** [comment]
1st part (damage) of that spell works now, but 2nd part: "...reducing the physical damage you take by (25 ; Min 25, Max 80)% for 3 sec, and causing Bastion of Glory..." doesnt.

**Comment by Moustachos** [comment]
Ref #2266
