### ISSUE TITLE
SORTS -Moniale- "Déferlante de masse"

### ISSUE THREAD

**Issue by AlphaDraconis** [Valhalla-Gaming/Tracker#3691]
Le sort ne fonctionne pas, ne heal pas.

**Comment by Malae1** [comment]
Please link us to the spell from WoWhead.

**Comment by AlphaDraconis** [comment]
http://fr.wowhead.com/spell=116694/deferlante-de-brume

**Comment by Malae1** [comment]
Ref #3060, #345
