### ISSUE TITLE
Winterspring Quest - Get Them While They're Young

### ISSUE THREAD

**Issue by Klickeazy** [Valhalla-Gaming/Tracker#3710]
The cubs cannot be interacted with to pickup
http://www.wowhead.com/quest=29032/get-them-while-theyre-young

**Comment by carminejackal** [comment]
From past experience, you have to kill the cub to collect it for the quest. However, you should be capable of collecting them w/o harming them.

**Comment by K-Reeboo** [comment]
Hi,
Though if you kill a 'Young frostsaber' drop the quest item 'Frostsaber Cub'.
So quest can be done this way.
I agree that on retail, you have to pick up the cubs without killing any animal.

**Comment by Tregeta** [comment]
fixed next update
