### ISSUE TITLE
Raid: The Eye (Tempest keep)

### ISSUE THREAD

**Issue by Djurdjevdan** [Valhalla-Gaming/Tracker#3714]
While fighting Keal'thas he can cast mind control on you. If you are soloing, it will restart instance. If you do instanve again, after every phase you will automaticly run to the same place where you got mind controled. Even after you defeat Keal and Heartstone out (for me to Dalaran Silver Covenet) your character will run again automaticly triugh walls and in the air probably to tempest keep. I fixed it by reloging. Fortunatly, I was a druid so I could've change to flight form in midle of air and not falling to death.

**Comment by kupidons** [comment]
i have done tempest keep multiple times and never i have been mc'd

**Comment by Djurdjevdan** [comment]
I was dpsing him slowly. That's why i got it.

**Comment by Pure-Valhalla** [comment]
Just tested this on my player account and this does not happen anymore.
