### ISSUE TITLE
Sort [éclat solaire] et [éruption stellaire]

### ISSUE THREAD

**Issue by filoufrip** [Valhalla-Gaming/Tracker#3717]
[Éclat solaire] ne fait aucun dégâts quel qu'il soit .

[Éruption stellaire] possède un temps d'incantation qu'il ne devrait pas avoir .

**Comment by Malae1** [comment]
Please provide links to the spells from wowhead.

**Comment by Moustachos** [comment]
Fixed in a previous update.
