### ISSUE TITLE
Shadow dance

### ISSUE THREAD

**Issue by danirzv** [Valhalla-Gaming/Tracker#3718]
as image blow [Shadow Dance] should get placed in top of spell bars and beside of [Stealth] spell, but it is not there in game, and i should put it in my spell bars...
http://gkrage.com/wp-content/uploads/2014/04/rogue-keybinds.jpg

http://www.wowhead.com/spell=51713/shadow-dance

**Comment by Moustachos** [comment]
Even on retail Shadow Dance isn't supposed to be a stance, so it's not near Stealth spell and it's not a bug that you have to put it in your actionbar.

**Comment by Moustachos** [comment]
Ref #2266
