### ISSUE TITLE
Dungeon: Dire Maul (Broken Commons) Mobs

### ISSUE THREAD

**Issue by zwei7** [Valhalla-Gaming/Tracker#3751]
In the "Broke Commons" section of Dire Maul, some Mobs are targetable/selectable, but unable to be attacked. they also do not agro when you go near them.

I have taken screenshots in the order you first meet them. The first being closest to the entrance of the Broken Commons.

Gordok Warlock
![wowscrnshot_112915_004409](https://cloud.githubusercontent.com/assets/15259298/11455515/675b081c-9632-11e5-8aa5-538363145cfe.jpg)

Gordok Captain 
![wowscrnshot_112915_004304](https://cloud.githubusercontent.com/assets/15259298/11455516/6b7dfc38-9632-11e5-86f0-e97ef6ed36da.jpg)

Gordock Reaver AND Gordok Worlock
![wowscrnshot_112915_003952](https://cloud.githubusercontent.com/assets/15259298/11455519/808919aa-9632-11e5-9518-3d6cf54009c4.jpg)

Gordok Warlock
![wowscrnshot_112915_004842](https://cloud.githubusercontent.com/assets/15259298/11455537/fe0eb8b2-9632-11e5-911e-9b55cb348338.jpg)

Gordock Reaver
![wowscrnshot_112915_010347](https://cloud.githubusercontent.com/assets/15259298/11455610/b8b9b12e-9635-11e5-96ca-edc49681fda1.jpg)

Gordok Warlock
![wowscrnshot_112915_010813](https://cloud.githubusercontent.com/assets/15259298/11455612/bf1984ae-9635-11e5-85b2-a3e3c461a77b.jpg)

Gordock Reaver
![wowscrnshot_112915_011006](https://cloud.githubusercontent.com/assets/15259298/11455628/f2451e38-9635-11e5-9c0a-c2dd1d0cf015.jpg)

Gordock Reaver
![wowscrnshot_112915_011006](https://cloud.githubusercontent.com/assets/15259298/11455634/5f261ab6-9636-11e5-95a0-bdcfd9a91983.jpg)

Gordok Captain 
![wowscrnshot_112915_011412](https://cloud.githubusercontent.com/assets/15259298/11455654/3bc498d0-9637-11e5-9382-6967c2eb1746.jpg)

Gordok Warlock
![wowscrnshot_112915_011437](https://cloud.githubusercontent.com/assets/15259298/11455655/3d3865a2-9637-11e5-9be0-572006255626.jpg)

**Comment by Tregeta** [comment]
Fixed in previous update.
