### ISSUE TITLE
SORTS - Druide

### ISSUE THREAD

**Issue by AlphaDraconis** [Valhalla-Gaming/Tracker#3755]
Fureur primitive fonctionne même sans faire de coup critiques en forme de félin.
Esquive ne marche pas.

**Comment by Malae1** [comment]
Link please to spells.

**Comment by Pure-Valhalla** [comment]
English translation: 
"Primal Fury works even without making a critical blow in cat form. 
Dodge does not."

adding link:
http://www.wowhead.com/spell=16961/primal-fury

**Comment by Moustachos** [comment]
Fixed in a previous update.
