### ISSUE TITLE
MOB: Infernal Hurricane?

### ISSUE THREAD

**Issue by zwei7** [Valhalla-Gaming/Tracker#3767]
What are these untargetable invincible mobs doing in the water in Thousand needles? It is an infernal drowning inside a hurricane? These kill you too. The infernal walk walk towards you with a hurricane around it and will melee attack you.
![wowscrnshot_112915_160152](https://cloud.githubusercontent.com/assets/15259298/11460032/afda2872-96b2-11e5-9f43-b699f640983d.jpg)

I found another in Tanaris. This infernal is in a typhoon.
![wowscrnshot_113015_014725](https://cloud.githubusercontent.com/assets/15259298/11465872/ce18a5f4-970a-11e5-902e-e952dc4a7cad.jpg)

**Comment by Malae1** [comment]
The Cyclone is meant to attack you, though you should not see the elemental.

**Comment by Tregeta** [comment]
fixed next update
