### ISSUE TITLE
Draenei starting zone class learners

### ISSUE THREAD

**Issue by Awkakelen** [Valhalla-Gaming/Tracker#3784]
Hello. There's a problem in Ammen Vale, because, as fg. draenei warrior you have access to other classes' quests. There is screen.
![wowscrnshot_113015_175314](https://cloud.githubusercontent.com/assets/12753422/11478083/4303d1b0-978b-11e5-9d94-56b7334ee23e.jpg)

**Comment by zwei7** [comment]
Hellscream as opened up every quest for everyone all at once so we can test them all out to report bugs. It is intentional.
