### ISSUE TITLE
Hunter: PET: talent

### ISSUE THREAD

**Issue by bubbles3008** [Valhalla-Gaming/Tracker#3801]
talents cant be changed......

**Comment by Trekex** [comment]
I can change spec on MM, but not on BM. (Dunno on Survival)
Also my pet gets spells from other specializations. This happens only in BM (again dunno on Survival).
![wowscrnshot_042916_105244](https://cloud.githubusercontent.com/assets/14263412/14912015/ab601090-0df9-11e6-8140-c66beb84889b.jpg)
![wowscrnshot_042916_110134](https://cloud.githubusercontent.com/assets/14263412/14912023/c14f67d4-0df9-11e6-9ecd-6700d0d6e491.jpg)
As you see I have Great Stamina, Last Stand, Blood of the Rhino and Spiked Collar while I shouldn't. (Maybe it's visual only? Idk)

**Comment by Moustachos** [comment]
Ref #2266
