### ISSUE TITLE
Vendor: Challenger Soong

### ISSUE THREAD

**Issue by Reallyaceman** [Valhalla-Gaming/Tracker#3804]
Hello, there is a problem with Challenger Soong at location Shrine of Seven Stars.
Only mages can access him and get the full MoP armour Challenge Set
No one else is able to access him at the time.
http://www.wowhead.com/npc=64028/challenger-soong

**Comment by Malae1** [comment]
This vendor is actually far more than just the report here. To access the items you must have completed all challenge mode dungeons at Gold level in MoP content, though this is now disabled on retail, we have not yet disabled the vendor here.

**Comment by Tregeta** [comment]
Vendor option has now been disabled in next update.
