### ISSUE TITLE
[Quest] [Hellfire Peninsula] Fel Spirits

### ISSUE THREAD

**Issue by GMTyrial** [Valhalla-Gaming/Tracker#3850]
http://www.wowhead.com/quest=10909/fel-spirits

According to players, only 3 of the spawns work for the quest. So players have to keep farming the same 3 spawns to complete the quest

EDIT: The player has reported a workaround to round up all of them and then use the item in AoE. I don't know this quest well enough to know if this is a real bug or not

**Comment by malex1024** [comment]
The reported workaround works. This issue should be closed.
