### ISSUE TITLE
[Profession] Draenor Tailoring

### ISSUE THREAD

**Issue by Chevanei** [Valhalla-Gaming/Tracker#3866]
Bonsoir,

j'ai obtenu http://fr.wowhead.com/item=115357/couture-de-draenor que j'ai donc utilisé, j'ai donc rencontré un problème : lors de l'apprentissage ma couture s'est débloqué jusqu'au niveau 700, mais je n'ai pas obtenu les crafts qui était avec le bouquin c'est-à-dire les crafts journaliers et les crafts simples. 

Merci de votre compréhension, bien à vous.
Telaran

**Comment by GMTyrial** [comment]
Translation : 

Good evening,

I got http://www.wowhead.com/item=115357/draenor-tailoring have I used, so I met a problem when learning my sewing was unlocked up 'at 700, but I did not get the crafts that were with the book that is to say the daily crafts and simple crafts.

Thank you for your understanding of your own.
Telaran

**Comment by Althin** [comment]
Still bugged

**Comment by viktorianus** [comment]
Still no recipes taught when used.

**Comment by Tregeta** [comment]
Fixed
