### ISSUE TITLE
[Skill] [Death knight] Icy Touch

### ISSUE THREAD

**Issue by Gjenferd** [Valhalla-Gaming/Tracker#3902]
It doesn't deal damage, just applies frost fever

**Comment by GMTyrial** [comment]
http://www.wowhead.com/spell=45477/icy-touch

**Comment by GMTyrial** [comment]
Needs to be added #2266

**Comment by Moustachos** [comment]
It's properly dealing damage as of current version.

**Comment by Moustachos** [comment]
Ref #2266
