### ISSUE TITLE
Battleground reward 

### ISSUE THREAD

**Issue by RealFlex** [Valhalla-Gaming/Tracker#3925]
Not every Battleground win give you CP reward atm .. its more like only 1 win per day give CP. Also not Strongboxes. 
http://www.wowhead.com/currency=390/conquest-points

**Comment by Collector-Valhalla** [comment]
Hunters get leather items from strongboxes. Warlocks get items with spirit. Ferals get items with bonus armor.

**Comment by Collector-Valhalla** [comment]
Stronboxes should give you gear based on specialization? Currently as a feral druid and frost death knight I get gear with bonus armor.

**Comment by Tregeta** [comment]
@Collector-Valhalla even on retail you'll get gear for a specialization you don't use.
