### ISSUE TITLE
NPC: Innkeeper Allison <Innkeeper>

### ISSUE THREAD

**Issue by zwei7** [Valhalla-Gaming/Tracker#3933]
This NPC presents 2 duplicate options to buy/sell
http://www.wowhead.com/npc=6740/innkeeper-allison
![wowscrnshot_121215_025034](https://cloud.githubusercontent.com/assets/15259298/11760888/7fc24386-a07b-11e5-889c-43ffa185a5e1.jpg)

**Comment by GeneralCaveman** [comment]
This has since been fixed.
