### ISSUE TITLE
DK dmg problem

### ISSUE THREAD

**Issue by iccX** [Valhalla-Gaming/Tracker#3974]
Before the Rune of Fallen Crusader fix frost dk  was doing insanely low dmg, around 40k crit with 695 ilvl.
After fix i do 20k crit with 695 ilvl. Is this a joke? i`m not laughing.
I posted a month ago several not working skills and still not even one has been fixed.

**Comment by Malae1** [comment]
Not related to rune of the fallen crusader.

**Comment by Moustachos** [comment]
Invalid report.
