### ISSUE TITLE
[Spell] [Priest] [Talent] Twist of Fate

### ISSUE THREAD

**Issue by Warjakh** [Valhalla-Gaming/Tracker#3983]
Twist of fate has a 100% up-time even when the target is above 35% hp. 

http://www.wowhead.com/spell=109142/twist-of-fate

![](http://i.imgur.com/fuJEjNt.png)

**Comment by GAMMARAYS** [comment]
Fixed.

**Comment by Moustachos** [comment]
Ref #2266
