### ISSUE TITLE
Versatility

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#3992]
http://wowwiki.wikia.com/wiki/Versatility

"1% of versatility stat should increase damage and healing done (and absorb effects) by 1% and decrease damage taken by 0.5%."

![wowscrnshot_121515_174421](https://cloud.githubusercontent.com/assets/14946340/11817093/ac3c4a44-a353-11e5-827b-1e55cc771ac0.jpg)

^ I'm here with 15.98% versatility so my damage/healing are correctly increased by 15.98% BUT decreased damage taken part is at 4%. Should be at 7.99%.

![wowscrnshot_121515_175146](https://cloud.githubusercontent.com/assets/14946340/11817286/915f1f70-a354-11e5-8850-b48ce9fede2e.jpg)

^ Without Claws of Shirvallah form (versatility increased by 5%) my damage/healing done are correctly at 10.98% BUT decreased damage taken is at 1.50%. Should be at 5.49%.

![wowscrnshot_121515_175521](https://cloud.githubusercontent.com/assets/14946340/11817397/0933f0c0-a355-11e5-9916-fb5b50816014.jpg)

^ Without Claws of Shirvallah form and Mark of the Wild buff (5% and 3%) my damage/healing are correctly at 7.98% BUT decreased damage taken is at 0%. Should be at 3.99%.

**Comment by Collector-Hellscream** [comment]
Just noticed that. I think that for ferals at least (dunno about other classes/specs) damage reduction part from versatility works only from buffs and not from gear.

**Comment by EPS1L0N** [comment]
it seems to only be a visual bug with the character panel

**Comment by EPS1L0N** [comment]
recheck it after the next update if you could please

**Comment by Collector-Valhalla** [comment]
oke. happy valentines day btw. <3

**Comment by Collector-Valhalla** [comment]
works for me thank you
