### ISSUE TITLE
Druid Talent. Incarnation: Tree of Life

### ISSUE THREAD

**Issue by skorge1** [Valhalla-Gaming/Tracker#3998]
The issue with http://www.wowhead.com/spell=33891/incarnation-tree-of-life is that when you use this ability the spells that should be affected aren't. For example Entangling Roots isn't instant cast in this form. The healing from rejuvenation and Regrowth are not increased and is not instant also overall healing doesn't get increased by 15%. Another issue is that after 30 seconds the form does not expire  so you can stay in it as long as you want,which is a bug. Another issue is that when you activate this form you are allowed to switch out of it and back into it usually but on hellscream WoW this is not the case. Once you go out of this form you cannot go back into it. You have to wait until the cooldown is finished. Another issue is that you don't get 120% increased armor. I hope this has helped.

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #2266

**Comment by skorge1** [comment]
It is not fixed because regrowth is not instant cast.
