### ISSUE TITLE
Quest: Resident Danger

### ISSUE THREAD

**Issue by FlameChampion34** [Valhalla-Gaming/Tracker#40]
Upon accepting this quest, the quest giver "Sentinel Kyra Starsong" is supposed to say: "Some of our huntresses have already made their way to Ban'ethil Barrow Den. They will find you when you get inside. Go ahead and speak to Citarre to secure a ride there.'

http://www.wowhead.com/quest=13945

**Comment by phikaro** [comment]
Already fixed!! xD
