### ISSUE TITLE
Battle for Gilneas ress

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#4013]
There's something wrong with ressurecting after death in Battle for Gilneas battleground.
Your ghost should be send to nearest graveyard of nearest captured base. If none of the bases are captured your ghost should be send to starting point. And if base/flag is captured while you still waiting for your ressurection your ghost should be send to another ress spot. 
Currenty your ghost go to flag/base graveyard that is not under control of any faction or shows on your corpse.

**Comment by Luminescent-Hellscream** [comment]
I have noticed as few time when being sent to a Graveyard closet one to where the horde start in this bg near the mines that there is a resurrection npc there but soon as you spawn she drops in the ground.

**Comment by Tregeta** [comment]
Should be fixed now
