### ISSUE TITLE
[Daily Quest] [Mulgore] Craving Crayfish

### ISSUE THREAD

**Issue by Nemrods** [Valhalla-Gaming/Tracker#4022]
This quest demands to drop Stonebull Crayfish, either by fishing or looting.
The fishing rate is quite low, so it's better to dive and grab it. But the monster is impossible to collect.
However it's possible to get them by fishing.
The quest : http://www.wowhead.com/quest=29349/craving-crayfish#criteria-of

**Comment by Tregeta** [comment]
fixed next update
