### ISSUE TITLE
The Woodland Protector(Quest)

### ISSUE THREAD

**Issue by terenctb69** [Valhalla-Gaming/Tracker#4029]
After accepting the quest, you are supposed to find the NPC Dyrad Tarindelle in the spider caves. The quest objective on the show the NPC but the NPC is not to be found.

**Comment by phikaro** [comment]
Same here, the npc Tarindrella is not showing up after reaching the cave, it was working fine before, but one of the new updates broke it.

Link: http://www.wowhead.com/quest=28725/the-woodland-protector

**Comment by Valhalla-Gaming** [comment]
Fixed
