### ISSUE TITLE
Request Stop (flying from Flight Masters)

### ISSUE THREAD

**Issue by Luminescent-Valhalla** [Valhalla-Gaming/Tracker#4037]
Upon hitting request stop while taking a flight path does nothing.

how it should work: When you hit request stop it should drop you off at the next flight master.

**Comment by Tregeta** [comment]
It looks like it works on my end.

**Comment by Luminescent-Hellscream** [comment]
Thanks for the info I will check again and video my findings if it does work now I will close the report

**Comment by Luminescent-Valhalla** [comment]
seems to have been a addon causing the issue after disabling all my addon request stop worked as normal.
