### ISSUE TITLE
Priest Shadowform visual bug

### ISSUE THREAD

**Issue by llamalama** [Valhalla-Gaming/Tracker#4043]
http://www.wowhead.com/spell=15473/shadowform
http://us.battle.net/wow/en/blog/19806402/fury-of-hellfire-62-patch-notes-6-22-2015#priest

As of patch 6.2 the shadow effect of Shadowform was removed from mounts by default and moved to a minor glyph.

**Comment by GAMMARAYS** [comment]
Fixed.

**Comment by Moustachos** [comment]
Ref #2266
