### ISSUE TITLE
[Quest] [Felwood] It's time to oil up

### ISSUE THREAD

**Issue by Nemrods** [Valhalla-Gaming/Tracker#4049]
The quest item darla's grapple can be used without the floating irontre oil can to craft a irontree oilcan.
But the Irotree oil can don't trigger on the Shredder so the quest can't be completed.

More info : http://www.wowhead.com/quest=28333/its-time-to-oil-up

**Comment by Cidragon** [comment]
Fix quest was fixed on November 25 changelog.
