### ISSUE TITLE
[Felwood] [Quest] "Stupid Drizle!" quest NPC isn't spawned

### ISSUE THREAD

**Issue by K-Reeboo** [Valhalla-Gaming/Tracker#4052]
A previous now closed issue was created for this bug, [#1558](https://github.com/HellscreamWoW/Tracker/issues/1558)

Though, as of today, NPC has disappeared again :(

![wowscrnshot_122515_093024](https://cloud.githubusercontent.com/assets/16204587/12003380/33a39a94-aaea-11e5-8d35-c0472a05d859.jpg)

**Comment by Cidragon** [comment]
Fix quest was fixed on November 25 changelog.
