### ISSUE TITLE
getting combo point

### ISSUE THREAD

**Issue by serenity-talador** [Valhalla-Gaming/Tracker#4067]
"balayage" doesnt give combo point for each target hitted , few days ago it used to work , i'm not sure but "lambeau" has the same problem

**Comment by Tregeta** [comment]
Please provide a link to the spells.

**Comment by Luminescent-Hellscream** [comment]
[Shred(Lambeau)](wowhead.com/spell=5221)
[Swipe(Balayage)](http://www.wowhead.com/spell=106785)

**Comment by serenity-talador** [comment]
Fixed
