### ISSUE TITLE
[Winterspring] [Quest] : More Beads for Salfa (should be repeatable)

### ISSUE THREAD

**Issue by K-Reeboo** [Valhalla-Gaming/Tracker#4068]
The NPC Salfa does not propose this quest again after completing the first one ([Winterfall Activity](http://www.wowhead.com/quest=28522/winterfall-activity))

This quest should be repeatable, enable us to raise Timbermaw Hold reputation.

http://www.wowhead.com/quest=28523/more-beads-for-salfa

**Comment by lavalash551** [comment]
Sad enough its the only quest you can push reputation to exhalted. And without it, no diplomat - title :(

**Comment by Tregeta** [comment]
fixed next update

**Comment by Huldre** [comment]
Clicking complete the quest does nothing, so it can't be turned in.
