### ISSUE TITLE
followers retraining

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#4071]
http://www.wowhead.com/item=122273/follower-trait-retraining-guide
^ reroll traits
Works correctly.

http://www.wowhead.com/item=118354/follower-retraining-certificate
^ reroll traits and abilities
Works only for traits. Doesn't work for abilities.

http://www.wowhead.com/item=122272/follower-ability-retraining-manual
^ reroll abilities
Doesn't work at all.

**Comment by Moustachos** [comment]
Both items are working just fine (just tried them), but you might be in one of the following cases:
- the item rerolled the very same abilities for your follower (can happen, even on retail)
- the targetted follower has "forced" (= default) abilities or traits, so even after a reroll they'll come back, that's also the intended behavior (for example, you can't reroll the "Mentor" trait of Harrison Jones)

**Comment by VictorTyne** [comment]
I've used all three of these items multiple times, and only once has it worked properly. So either I've been unlucky enough to have it re-roll to the very same abilities or whatever pool it's pulling possible abilities from is way too shallow.
