### ISSUE TITLE
Steamwheedle Preservation Society

### ISSUE THREAD

**Issue by kupidons** [Valhalla-Gaming/Tracker#4072]
http://www.wowhead.com/faction=1711/steamwheedle-preservation-society
quests aren't repeatable

**Comment by kupidons** [comment]
A Rare find and Fragments of the Past

**Comment by Luminescent-Valhalla** [comment]
Confirmed quest can only be done once they should be repeatable all day long this makes getting rep with them a royal pain in the butt

**Comment by Tregeta** [comment]
fixed next update
