### ISSUE TITLE
Something on map during bgs

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#4075]
![wowscrnshot_122715_161858](https://cloud.githubusercontent.com/assets/14946340/12011290/fe0ab234-acc7-11e5-82b0-dcad3895aff4.jpg)

Dunno what that is. Annoying for sure.

**Comment by Collector-Valhalla** [comment]
This 'thing' shows outside of bgs too.

![wowscrnshot_011616_130007](https://cloud.githubusercontent.com/assets/14946340/12372294/412b0260-bc51-11e5-8afc-5387ada9659b.jpg)

**Comment by Tregeta** [comment]
What are thooose??

**Comment by Luminescent-Hellscream** [comment]
Those are the icon blizzard use for the carts in battlegrounds

**Comment by Tregeta** [comment]
It was a reference to: https://youtu.be/IK0t38Al4_E?t=8s

**Comment by Collector-Valhalla** [comment]
lol

**Comment by Luminescent-Hellscream** [comment]
think i have found the issue for these randomly appearing on the map they seem to be releated to certain mobs like [Chief-saylis](http://www.wowhead.com/npc=62352/chief-salyis) and also when i use the mamoth with vendors from dalaran they show up on the map also 

[Chief-Saylis SS](http://i.imgur.com/LJZGPXA.jpg)
[Traveler's Tundra Mammoth SS](http://i.imgur.com/fBYB2aa.jpg)

**Comment by Trekex** [comment]
I noticed that they appeared only after an Alterac Valley BG started. I wasn't in BG and all was fine, then AV started an I saw those carts on map. When other Bg's start they do not appear if they're not on map already, so I think it is AV related. (Not checked with all the others, but with almost all)
![wowscrnshot_012116_192115](https://cloud.githubusercontent.com/assets/14263412/12520236/a9c3c248-c143-11e5-8418-cf2ea8f9658d.jpg)

**Comment by Collector-Valhalla** [comment]
What's World Invisible Trigger? D:

![wowscrnshot_012316_210148](https://cloud.githubusercontent.com/assets/14946340/12532627/d9cd2a58-c218-11e5-8e7c-11795cd56465.jpg)

Which base is taken? D:

![wowscrnshot_011916_214403](https://cloud.githubusercontent.com/assets/14946340/12532632/ee897672-c218-11e5-9421-0687d48a8e97.jpg)

**Comment by Tregeta** [comment]
What are your current addons Collector?

**Comment by Collector-Valhalla** [comment]
ElvUI, SimpleComboPoints, NeedToKnow, SaySapped, Addon Control Panel

**Comment by Tregeta** [comment]
And what happens when you use: NPC Scan or HandyNotes?

**Comment by Collector-Valhalla** [comment]
I have HandyNotes but disabled for many months now. Currently I don't have those things on map but I can enable that addon and update this comment if I notice those carts again.

**Comment by Tobaccoz** [comment]
This happens to me aswell and I barely have any addon.

**Comment by EPS1L0N** [comment]
the mine carts are invading, our days are limited.

**Comment by Collector-Valhalla** [comment]
Not always. For example that screenshot in Northrend shows 'Kvaldir Raiders' (that are untargetable) or smt like that. Relog and clearing cache "sometimes" helps. Cart icons in AV shows on players, bases/towers and mobs (like stormpike soldier... or smt like that).

I think that World Invisible Trigger shows only on some script things (sorry I'm not a scientist) that activates during some events (like there in naxx when mobs spawn) and I think I saw it also in arathi basin bg instead of flag/base.

**Comment by EPS1L0N** [comment]
I'm having trouble reproducing it, is there any sure fire way to make it happen?

**Comment by Collector-Valhalla** [comment]
For me it seems to be "random" but most of players say it's happening in battlegrounds.

**Comment by Trekex** [comment]
As I said, for me it happens even out of BG's when certain start.

**Comment by Collector-Valhalla** [comment]
With HandyNotes
![wowscrnshot_012616_004145](https://cloud.githubusercontent.com/assets/14946340/12568421/1d79abf6-c3c6-11e5-8f42-35582d44c70e.jpg)

Without HandyNotes
![wowscrnshot_012616_004256](https://cloud.githubusercontent.com/assets/14946340/12568420/1d783096-c3c6-11e5-882e-28f9959bff05.jpg)

Thing is called Sprouting Podling...
![wowscrnshot_012616_004300](https://cloud.githubusercontent.com/assets/14946340/12568422/1d7a44b2-c3c6-11e5-9278-b4945a0bd766.jpg)

...and is level 1 humanoid
![wowscrnshot_012616_004308](https://cloud.githubusercontent.com/assets/14946340/12568454/5773b810-c3c6-11e5-96e0-3d6e9e0fb07a.jpg)

I'm not the only one with this problem and I have no clue what's cause of it.
