### ISSUE TITLE
[Quest][Silithus] Scouring the desert

### ISSUE THREAD

**Issue by Nemrods** [Valhalla-Gaming/Tracker#4081]
This quest doesn't work. When we click on the geysers, the buff appears but nothing happens when we returned to the npc.

More info here : http://www.wowhead.com/quest=9422/scouring-the-desert

**Comment by MeleeMaster** [comment]
The quest works. You have to stand on the Silithyst Extractor that machine that emits a blue light and then you talk to the NPC.

**Comment by Cidragon** [comment]
This quest is working as intented :)
