### ISSUE TITLE
Doorway to the Abyss

### ISSUE THREAD

**Issue by deathbane1911** [Valhalla-Gaming/Tracker#4083]
there is no rune of spite, so you cannot complete the quest

**Comment by KraitX** [comment]
Yeah the rune is there but it has no interaction with the burning legion gate key

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/4004

**Comment by Cidragon** [comment]
Fixed in December 5th changelog
