### ISSUE TITLE
Sac d'or rebondi

### ISSUE THREAD

**Issue by Golluminette** [Valhalla-Gaming/Tracker#4085]
Lors de la quête de calligraphie "Documents falsifiés", le "Sac d'or rebondi" ne peut pas être ouvert. Message : "Vous ne pouvez pas prendre ce butin"
http://fr.wowhead.com/quest=27686/documents-falsifies
http://fr.wowhead.com/item=62062/sac-dor-rebondi

**Comment by Tregeta** [comment]
http://www.wowhead.com/item=62062/bulging-sack-of-gold Bag gives error upon trying to open. "You can't loot that item right now."

**Comment by Tregeta** [comment]
fixed next update
