### ISSUE TITLE
[Quest][Tanaris] Poached, Scrambled or raw?

### ISSUE THREAD

**Issue by Nemrods** [Valhalla-Gaming/Tracker#4087]
This quest is given by the venomhide hatchling from the primary quest "They grow up so fast" (http://www.wowhead.com/quest=13906/they-grow-up-so-fast).
The quest demands to collect 12 Silithid eggs in the noxious lair in Tanaris.

Actually, there are only 2 eggs available to collect inside the lair and there are very few ennemies inside and outside.

The quest is doable but I presume there are some problems here with mob and eggs.

**Comment by Aveta** [comment]
There are more eggs on the ground around the lair.

**Comment by Cidragon** [comment]
There are several eggs now :)
