### ISSUE TITLE
Barrage is casting

### ISSUE THREAD

**Issue by sausagepl** [Valhalla-Gaming/Tracker#4094]
So the talent barrage is casting and as i now its no supossed to and it shoots just at one target not at multitargets so pls be so kind and fix this and the rest of the hunter because its not playable like this thx peace

**Comment by Aprophys** [comment]
Barrage is an channeling spell http://www.wowhead.com/spell=120360/barrage
and i see many hunters even in BG they hit more than 1 player/or even an mob.

**Comment by sausagepl** [comment]
I was in a dungeon now and it worked then i tried on a mob outside and
again not working
Dňa 30.12.2015 11:08 používateľ "Aprophys" <notifications@github.com>
napísal:

**Comment by Tregeta** [comment]
Which is it? it's either working or not.

**Comment by Collector-Hellscream** [comment]
I'll add that in one of the patches (6.2 I think) barrage was changed to NOT hit targets that are in stealth. Currently it still hits rogues or ferals.

**Comment by sausagepl** [comment]
It works exatly like powershoot but it should shoot like a mashine gun i
think 2.8 sek at 3 targets i think
Dňa 30.12.2015 16:18 používateľ "Collector" <notifications@github.com>
napísal:

**Comment by sausagepl** [comment]
I will be loged in to the char in abot 1.5 hrs so we can take a look a the
problem when you want
Dňa 30.12.2015 20:15 používateľ "marian poliak" <ericstasieluk1409@gmail.com>
napísal:

**Comment by Tregeta** [comment]
Reset your talents, it's likely the spell isn't scripted properly, but if it is that should fix it. Please remember to relog and clear your cache.

**Comment by sausagepl** [comment]
Ok i am online i will try
Dňa 30.12.2015 22:23 používateľ "Tregeta" <notifications@github.com>
napísal:

**Comment by Moustachos** [comment]
Ref #2266
