### ISSUE TITLE
Thunderlord Butcher

### ISSUE THREAD

**Issue by andrija2567** [Valhalla-Gaming/Tracker#4116]
http://www.wowhead.com/npc=78964/thunderlord-butcher
![wowscrnshot_010316_204503](https://cloud.githubusercontent.com/assets/12571057/12081153/8dcc60c6-b271-11e5-8efb-29b755f2bb19.jpg)
I think they shouldnt be here
Edit:
![wowscrnshot_010516_124216](https://cloud.githubusercontent.com/assets/12571057/12114402/d605496e-b3a9-11e5-8436-b0116c437964.jpg)

**Comment by Tregeta** [comment]
Please provide us a better detail of where you are exactly via the map so that we may check our data.

**Comment by Tregeta** [comment]
fixed
