### ISSUE TITLE
Grimfrost Drudge

### ISSUE THREAD

**Issue by andrija2567** [Valhalla-Gaming/Tracker#4119]
![wowscrnshot_010316_204740](https://cloud.githubusercontent.com/assets/12571057/12081217/e02420ce-b272-11e5-8048-01335e8001f8.jpg)
ogre is attacking me while being on the ground

**Comment by Tregeta** [comment]
Looks like you're being attacked by a wolf there...can you please show us a better photo with perhaps a combat log of damage taken?

**Comment by Tregeta** [comment]
fixed
