### ISSUE TITLE
Driftwatcher Rylak

### ISSUE THREAD

**Issue by andrija2567** [Valhalla-Gaming/Tracker#4120]
http://www.wowhead.com/npc=72849/driftwatcher-rylak
![wowscrnshot_010316_204325](https://cloud.githubusercontent.com/assets/12571057/12081231/38dc2b94-b273-11e5-8b0b-021a33c0f334.jpg)
cant attack it,he also doesnt attack me

**Comment by Tregeta** [comment]
fixed
