### ISSUE TITLE
Voidwalker lacks Threatening Presence

### ISSUE THREAD

**Issue by Zellvia** [Valhalla-Gaming/Tracker#4125]
The warlock pet Voidwalker does not have the Threatening Presence ability which generates additional threat, as it should have in retail (reference: http://www.wowhead.com/spell=112042/threatening-presence).

**Comment by Collector-Valhalla** [comment]
Fixed?

![wowscrnshot_043016_230949](https://cloud.githubusercontent.com/assets/14946340/14938604/2f370434-0f29-11e6-83c4-74e9cc6ff238.jpg)

**Comment by Tregeta** [comment]
Did the pet generate threat?

**Comment by Collector-Valhalla** [comment]
no idea ;p
