### ISSUE TITLE
Stormwind Stockades are Pre-Cataclysm

### ISSUE THREAD

**Issue by Max-Valhalla** [Valhalla-Gaming/Tracker#413]
"The entire dungeon needs to be redone so as to reflect the changes brought about by Cataclysm. See http://www.wowwiki.com/The_Stockade#In_Cataclysm

*note to players: As it currently stands, the only mob with significant loot is the rare Bruegal Ironknuckle. I have confirmed that he drops Jimmied Handcuffs, but he should also drop Iron Knuckles and Prison Shank."

**Comment by tribaljet** [comment]
This remains true for the time being.

**Comment by Tregeta** [comment]
fixed next update
