### ISSUE TITLE
Binding Shot PvP

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#4135]
http://www.wowhead.com/spell=109248/binding-shot

"Breaking the tether of Binding Shot will stun the target for 5 sec (3 sec PvP)."

Currently that ability stuns players for more than 10 sec. After 5 sec stun (in PvP should be 3 sec) player gets stun again and when effect is near end player gets third stun.

**Comment by anyadhatan** [comment]
Yeah this is really annyoing in pvp.

**Comment by Collector-Valhalla** [comment]
I think it's fixed now.
