### ISSUE TITLE
Paladin (Holy Shield)(prot)(talent)

### ISSUE THREAD

**Issue by anyadhatan** [Valhalla-Gaming/Tracker#4137]
Prot paladin 100lv talent which is called Holy Shield doesnt works at all,i am got 15% bonus block from Holy Shield but the problem is I am not blocking spells, tested in duel.

Its suppossed to block spells too.

http://www.wowhead.com/spell=152261/holy-shield

"Increases your block chance by 15%, and allows you to block spells. Additionally, when you block, you deal 1 Holy damage to your attacker."

**Comment by Luminescent-Hellscream** [comment]
Ref #4044

**Comment by EPS1L0N** [comment]
> problem is I am not blocking spells, tested in duel.

* The chance that you will "block" a spell is equal to your block chance.
* The amount that you block is your shield block amount (shown when you hover over your block stat)

![CombatLog](http://puu.sh/mnwMe/f93a95e1da.jpg)

**Comment by anyadhatan** [comment]
Thanks for picture, next time i will check deeper the spells in combat log ,sorry.
