### ISSUE TITLE
[Rogue] Instant Poison

### ISSUE THREAD

**Issue by Aveta** [Valhalla-Gaming/Tracker#4148]
http://www.wowhead.com/spell=157584/instant-poison
Instant Poison is supposed to be treated like any Lethal Poison, meaning that any other Lethal Poison will remove it. Currently it's not the case and you can stack it with other Lethal Poisons like Wound Poison, which is the other Lethal Poison available to Combat Rogue.

**Comment by Tregeta** [comment]
fixed in next update
