### ISSUE TITLE
Monks (possibly other classes) not able to procure Conquest Point Weapon

### ISSUE THREAD

**Issue by lloydbuckley** [Valhalla-Gaming/Tracker#4157]
Even with required base Conquest Points (3500) and required season currency (7250), not able to purchase Season 2 weapon from NPC [Amelia Clark](http://www.wowhead.com/npc=93907/amelia-clarke). In this case, the weapon in question is [Wild Gladiator's Pike](http://www.wowhead.com/item=124683/wild-gladiators-pike).

Referred as issue with core after discussion with GM Puure and reference from Max.

**Comment by Pure-Valhalla** [comment]
![pike 2](https://cloud.githubusercontent.com/assets/14964856/12222998/09b656c8-b791-11e5-9da0-90690da7be6a.jpg)

Tucker's stats:
![tucker](https://cloud.githubusercontent.com/assets/14964856/12223002/2ee14b9c-b791-11e5-9967-d67ecaa957bc.png)
