### ISSUE TITLE
Hunter's pet Frostsaber cats missing Roar of Courage

### ISSUE THREAD

**Issue by Vasharij** [Valhalla-Gaming/Tracker#4161]
After taming a Frostsaber Huntress in Winterspring I noticed that they don't have Roar of Courage among their abilities, it doesn't appear neither in the actions bar, neither in the spellbook. Then I tamed Shy-Rotam and I have the same problem: Roar of Courage isn't there.

I never tamed a Cat before so I don't know if it's a problem common to all cats.

http://www.wow-petopia.com/family/cat.html

**Comment by llamalama** [comment]
http://www.wowhead.com/spell=93435/roar-of-courage

Requires level 81. You might be too low level for it to appear.

**Comment by Tregeta** [comment]
Please let us know if you are indeed 81 at the time of reporting this, if so we will look into it.

**Comment by Vasharij** [comment]
Sorry, my mistake. I'm not 81, I thought they had to have it like the abilities my other pets have.

**Comment by Tregeta** [comment]
I'll go ahead and test this just to be safe.
