### ISSUE TITLE
CAS system initialization error 

### ISSUE THREAD

**Issue by deedub221** [Valhalla-Gaming/Tracker#4168]
whenever I try and install the game through the launcher I get an error stating that my CAS system had an initialization error. I am not sure if the game is installing after this error is displayed as the progress bar does not move. Is there a way I can fix this issue, I have looked around, tried running as administrator and it still does nothing. This is an attachment with the error that displays. 
![46f74009f962bd015d376c7ad8d3f15a](https://cloud.githubusercontent.com/assets/16653618/12242960/b5b2d828-b8e7-11e5-9395-6ec7bd56324c.png)

**Comment by Tregeta** [comment]
Forum related.
