### ISSUE TITLE
druide glyph "arent for your spé"

### ISSUE THREAD

**Issue by serenity-talador** [Valhalla-Gaming/Tracker#4175]
http://fr.wowhead.com/spell=47180/glyphe-de-forme-de-felin 
and 
http://fr.wowhead.com/spell=67598/glyphe-de-morsure-feroce

are said that arent for the farouch spe when i try to put then as glyph :/
a war encoured the same issue with some of his glyph (dont know which)

**Comment by Tregeta** [comment]
http://www.wowhead.com/spell=47180/glyph-of-cat-form
http://www.wowhead.com/spell=47180/glyph-of-cat-form

**Comment by Moustachos** [comment]
This issue seems to be fixed as of current version.

**Comment by Moustachos** [comment]
Ref #2266

**Comment by serenity-talador** [comment]
Not yet in talador maybe due to the different updates differences

**Comment by serenity-talador** [comment]
Re-tested now , no updates differences this two glyph arent debugs "not for the feral spe"
