### ISSUE TITLE
stone core slabhide

### ISSUE THREAD

**Issue by serenity-talador** [Valhalla-Gaming/Tracker#4176]
http://www.wowhead.com/zone=5088/le-coeur-de-pierre
http://www.wowhead.com/npc=43214/slabhide
inst targetable just flying

**Comment by Aveta** [comment]
Seems to be working fine for me, he just needs to fly to his spot. Just go through the corridor thing and wait until he catches up.

**Comment by serenity-talador** [comment]
i will try it soon :)

**Comment by serenity-talador** [comment]
worked :)
