### ISSUE TITLE
mecabecane compos

### ISSUE THREAD

**Issue by serenity-talador** [Valhalla-Gaming/Tracker#4177]
neither of the vendors that sells the compo like wowhead.com/item=44501/piston-fa-onne-par-les-gobelins

for the mecabecane are available or sell something

**Comment by Tregeta** [comment]
Looks like it's there to me.
![piston](http://i.imgur.com/7mzRMSu.jpg)

**Comment by serenity-talador** [comment]
My bad i just struggle to find big keech , however http://www.wowhead.com/npc=31247/roxi-ramrocket#teaches-recipe dont cells them but it's not that important :)
