### ISSUE TITLE
Rogue Spell: Envenom 

### ISSUE THREAD

**Issue by skorge1** [Valhalla-Gaming/Tracker#4178]
The issue with http://www.wowhead.com/spell=32645/envenom is that is doing a damage of 2 on enemies. It also removes http://www.wowhead.com/spell=96648/deadly-poison from the target.
![wowscrnshot_011216_181625](https://cloud.githubusercontent.com/assets/12928658/12272919/c711c6b0-b95a-11e5-8f78-271e1fa027e9.jpg)

**Comment by Cyuty** [comment]
The only time envenom work's is if you use deadly poison and does like 50% or normal dmg.

**Comment by Moustachos** [comment]
Envenom's damage was fixed on last update.

**Comment by Moustachos** [comment]
Ref #2266
