### ISSUE TITLE
druid finishing move ant predatory switfness

### ISSUE THREAD

**Issue by serenity-talador** [Valhalla-Gaming/Tracker#4179]
http://www.wowhead.com/spell=16974/predatory-swiftness
proc correctly on http://www.wowhead.com/spell=22568 and http://www.wowhead.com/spell=52610

but not on http://www.wowhead.com/spell=22570/maim and http://www.wowhead.com/spell=1079/rip event with 5 combo points

**Comment by Collector-Hellscream** [comment]
#2696

**Comment by EPS1L0N** [comment]
#2266
