### ISSUE TITLE
[NPC] Provisioner Lorkran

### ISSUE THREAD

**Issue by Anderzenn** [Valhalla-Gaming/Tracker#4180]
When you right click him nothing happens.

Wowhead: http://www.wowhead.com/npc=26868/provisioner-lorkran

**Comment by Tregeta** [comment]
Clear your cache, this creature works.

**Comment by jfdaigle** [comment]
right click doesn't work...I cleared cache 3 times... this npc as quest giver/finisher, but once the quest is done, you can't talk to him/buy goods anymore.

**Comment by Tregeta** [comment]
Will be fixed next update, conditions removed.
