### ISSUE TITLE
Unh DK Death Coil

### ISSUE THREAD

**Issue by sandokana** [Valhalla-Gaming/Tracker#4182]
Death Coil for unh DKs deals less damage than it should according to spell tooltip. ( hits for 1k rather than 7k)

**Comment by Tregeta** [comment]
What level are you?

**Comment by sandokana** [comment]
I am lvl 100. 670 PvE item lvl and deal 1k.

**Comment by Tregeta** [comment]
Ty

**Comment by Moustachos** [comment]
Fixed on next update.

**Comment by Moustachos** [comment]
Ref #2266
