### ISSUE TITLE
Exit game, connection issue

### ISSUE THREAD

**Issue by Vynrae** [Valhalla-Gaming/Tracker#4190]
When a player presses on Exit Game instead of Logout, he is not disconnected immediately from the game but rather after around 1-2 minutes.

**Comment by EPS1L0N** [comment]
couldn't reproduce

**Comment by Luminescent-Hellscream** [comment]
I can also confirm this I saw it happen when I had both my accounts logged
on I exited on one client and took around 2 mins for it to show I had
logged off in-game
