### ISSUE TITLE
BUG, Weapon's From the Conquest Point

### ISSUE THREAD

**Issue by aminbogy** [Valhalla-Gaming/Tracker#4192]
Hi,

i have 3950 CP and 7450 CP Season, but still i cant buy weapons from the vendor,
i have this Error: you do not have the required items for that purchase.
and the weapons need 1750 CP + 7250 CP Season, so i think it is bug
please fix it as soon posible we need buy gear's.

**Comment by Tregeta** [comment]
Should be fixed on update Ref #4157
