### ISSUE TITLE
Hunter

### ISSUE THREAD

**Issue by Kreten7** [Valhalla-Gaming/Tracker#4193]
Hunter mastery doesnt give Sniper training!
Pet damage and hp are very,low,kill shoot have 1 charge instead of 2 and that spell doesnt heal like chimera shoot,camuflague doesnt give stealth.

**Comment by Tregeta** [comment]
camo is reported already, healing from shots also reported. Mastery

**Comment by Moustachos** [comment]
Ref #2266
