### ISSUE TITLE
Death knight Ability spell "dancing rune weapon"

### ISSUE THREAD

**Issue by corky12831** [Valhalla-Gaming/Tracker#4195]
dancing rune weapon does not seem to be working as intended at least in the few attempts i have had to use it.

**Comment by Tregeta** [comment]
Copy/Paste from @CorentinDodon report.

http://www.wowhead.com/spell=49028/dancing-rune-weapon

The spell Dancing Rune Weapon does not grant an additional 20% parry chance.

**Comment by Moustachos** [comment]
Ref #2266
