### ISSUE TITLE
Hunter - MM - Kill Shot Cooldown

### ISSUE THREAD

**Issue by SnakepitLofe** [Valhalla-Gaming/Tracker#4198]
Skill: Kill Shot (http://www.wowhead.com/spell=53351/kill-shot) 
Retail emphasis: 10 sec cooldown (one instant cooldown if it doesn't kill a target).
Problem's gist: Excessive long cooldown. After using Kill Shot and killing a target with it, it is supposed to start cooldown instantly and become available again in 10 sec after killing the target, HOWEVER, the icon fades after using the skill for about 5 seconds (more or less) and only after that cooldown begins. Hence, cooldown results to long around 15 seconds.

Even though Kill Shot was reported in Issue #3589 ( https://github.com/Valhalla-Gaming/Tracker/issues/3589 ), hindered cooldown was not mentioned there.

**Comment by sausagepl** [comment]
enemies with less than 20% health.  If the target dies, the Hunter will regain 15% of maximum health.

If Kill Shot fails to kill the target, the cooldown is reset.

kill shot is still buged and thats how its suposed to work

**Comment by Moustachos** [comment]
Will be fixed on next update.

**Comment by Moustachos** [comment]
Ref #2266
