### ISSUE TITLE
PvP scaling

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#4199]
*Currently PvP items scales only inside battlegrounds.* **They should scale in 'PvP combat' so also in duels or world PvP. In PvP zones (like wintergrasp) too but I'm not sure about that.**

Here's copy paste for patch 6.2 (before season 3 I think):
*"Level 100 Gear Scaling in PvP Combat
Level 100 characters engaging in PvP combat now have the following gear changes.
All gear between item levels 560 and 690 will now scale up to 690 in PvP combat.
Non-PvP gear above item level 715 will scale down to 715 in PvP combat.
PvP gear above item level 715 will not be capped in PvP combat."*

* So also non-PvP items should scale.

EDIT: Added some nice styling. Looks pretty fancy.

**Comment by Tregeta** [comment]
should be fixed now
