### ISSUE TITLE
Warlock Ember gains

### ISSUE THREAD

**Issue by Nienz** [Valhalla-Gaming/Tracker#4203]
so just tested destor warlocks after the recent update, and i noticed that if i have a dot heal on me each tick grants 1 Ember and i can literally spam chaol bolts 24/7 if i have a HoT on me, tested again seems all heals on me grants Embers

**Comment by Vynrae** [comment]
The successor if ice lance mages :p

**Comment by Zedron** [comment]
grrrrr

**Comment by EPS1L0N** [comment]
grrrr

**Comment by EPS1L0N** [comment]
Having trouble reproducing it, it could be a talent or glyph, or the specific HoT that healed you. Could you post what your talents + glyphs are? And the HoT that was healing you would help

[![IHotEmbers](http://img.youtube.com/vi/TdTEQhw-sQ4/0.jpg)](https://www.youtube.com/watch?v=TdTEQhw-sQ4 "HoTEmbers")

**Comment by Nienz** [comment]
Sry for the delay diff timezone i guess anyway nice tune in the vid :D but these are the talents and glyphs im using, and side note on heals on me, tested with resto druid, disco priest and holy paladins so far, each of em makes the Ember gains 100%

http://imgur.com/U3RBcZP

http://imgur.com/sr9sN07

**Comment by Collector-Valhalla** [comment]
I also healed you with Rejuvenation in feral spec.

**Comment by Nienz** [comment]
And another note i may add is i have 4set pvp bonuses and the 2set bonus makes me gain ! ember whenever im stunned.. silenced, interupted or feared, might be what causes the gains

**Comment by Nienz** [comment]
Oke i found out what caused the Ember gains, its the 2set pvp bonus, just removed all gear cus i was xmogging them and embers stopped regen

**Comment by EPS1L0N** [comment]
thanks for the info
