### ISSUE TITLE
BUG, Trinket

### ISSUE THREAD

**Issue by aminbogy** [Valhalla-Gaming/Tracker#4204]
Hi,
This Trinket is BUG, When hunter use it with Barrage , he can kill 5.6 player ALONE, please fix it

Name of that Trinket is : Infallible Tracking Charm

**Comment by Nienz** [comment]
its not the trinket itself that is bugged, its the Binding Shot from hunters

**Comment by Trekex** [comment]
Both the Trinket and the Spell have been already reported. (And there is no connection between them..).
#4200
#4135

**Comment by Aprophys** [comment]
This was allready posted
https://github.com/Valhalla-Gaming/Tracker/issues/4200
 the trinket procs/deals dmg with every shot like autoshot etc, and this is the problem
