### ISSUE TITLE
Block problem in pvp(as prot paladin)

### ISSUE THREAD

**Issue by anyadhatan** [Valhalla-Gaming/Tracker#4205]
Hello devs!

My problem is about block that doesnt works in pvp as prot paladin, i never see "block " or "blocked amount dmg" on combat log. On pve its works, but WEIRD about block doesnt works in pvp.
Would you devs looking it deeper about block problem?(Make prot paladin and test in pvp only not in pve)
Please fix it,from other pp i heard warrior prot has problem with block in pvp too,but in pve works.

**Comment by Tregeta** [comment]
Please provide us a few screenshots of your combat logs in pvp.

**Comment by anyadhatan** [comment]
Cant make screenhot because there is no bg,but i spoke to Warjakh (he will test prot paladin in pvp with other GM or Admin ingame)
