### ISSUE TITLE
Needy and Greedy

### ISSUE THREAD

**Issue by Trekex** [Valhalla-Gaming/Tracker#4207]
The two Achievements are bugged. I rolled a 100 with Need and no Achievement. (Not completely sure with Greed, but I think it is the same).
![wowscrnshot_011416_231123](https://cloud.githubusercontent.com/assets/14263412/12339268/5d4cadce-bb14-11e5-8e5e-9eba148d55a5.jpg)

**Comment by Aprophys** [comment]
It works for me http://i.imgur.com/vUugNPD.jpg

**Comment by Tregeta** [comment]
Please check the item to see if it's item level was indeed higher than the 185.

**Comment by Trekex** [comment]
Sorry, my fault. It was 185+, but not superior. :(
