### ISSUE TITLE
[Priest] Saving Grace

### ISSUE THREAD

**Issue by Aprophys** [Valhalla-Gaming/Tracker#4209]
Saving Grace deals dmg for the player who casts it.
http://i.imgur.com/fpl1Kd3.jpg

**Comment by Tregeta** [comment]
Please refrain from such hostilities in your report. Your report will be edited.

**Comment by Tregeta** [comment]
@Vynrae
> As mentioned here it's healing should be reduced by 25%, which is not the case on Valhall

**Comment by Tregeta** [comment]
Touch of the grave is causing the damage. Ref #4666
Closing Ref #2266
