### ISSUE TITLE
character blocked

### ISSUE THREAD

**Issue by serenity-talador** [Valhalla-Gaming/Tracker#4216]
Hello , after died in the tanan jungle i've been traped as a ghost or a falling alive character that will die , being ghost falling and so on , so if a hm could just tp me somewhere it could be fine because nothing worked , deco reco , back to the cimeterie , innstone 
The character name on talador :
Barrabas

if there is a need to be co when you tp settle an appointment i will be there :)

thx you for your work !

**Comment by Tregeta** [comment]
Please seek out a GM on the forum for the requested assistance.
