### ISSUE TITLE
fists of fury on multiple targets

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#4235]
http://www.wowhead.com/spell=113656/fists-of-fury

When you use Fists of Fury with mutiple targets around casting/channeling of it stops when you kill your first target and it still deals damage and stuns for rest of the duration but you can move and use other abilities.

**Comment by Collector-Valhalla** [comment]
Also it doesn't deal damage in PvP combat. Might be connected to issue #4188.

**Comment by Collector-Valhalla** [comment]
And there's a nice "trick" you can do with that ability. Immediately when you cast it you can move - to stop channeling - and use all other abilities (or just roll away) while damage and stun of Fists of Fury persist.

**Comment by skorge1** [comment]
This ability is not fixed. It still does what is stated above. Stopping when a target inside dead instead of finishing the cast. Also it doesn't stun players/creatures for the full 4 seconds.

**Comment by Moustachos** [comment]
> This ability is not fixed. It still does what is stated above. Stopping when a target inside dead instead of finishing the cast. Also it doesn't stun players/creatures for the full 4 seconds. It was poorly scripted.

This is a completely different issue from initial one, read more carefully.

It will be fixed on next update.

Ref #2266
