### ISSUE TITLE
Mana Regen

### ISSUE THREAD

**Issue by war627** [Valhalla-Gaming/Tracker#4250]
missing on spell book and not working
http://www.wowhead.com/spell=111546/chaotic-energy

**Comment by Tregeta** [comment]
It's hidden from your spellbook. This is a change that has been done in WoD.

**Comment by Nienz** [comment]
ye about that one, my warlock is lvl 100 but the mana regen isnt working as it should, tooltip says 35k/ 5s but it's actually alot less cus i do 4 incinirates and im out of mana and takes a really long time before im even at 50% mana

**Comment by Tregeta** [comment]
Spell is working, base mana regen is not correct.
