### ISSUE TITLE
[Quest][Shadowmoon Valley] : To Catch A Thistlehead

### ISSUE THREAD

**Issue by K-Reeboo** [Valhalla-Gaming/Tracker#4258]
Quest description : [http://www.wowhead.com/quest=10570/to-catch-a-thistlehead](http://www.wowhead.com/quest=10570/to-catch-a-thistlehead)
Quest video : [https://www.youtube.com/watch?v=qyiS0FaqjtA](https://www.youtube.com/watch?v=qyiS0FaqjtA)

Cannot use the quest item at required location.
Also, guess this one is scripted too (as we can see on the video)

Screenshot of present state on server : 
![wowscrnshot_011716_105639](https://cloud.githubusercontent.com/assets/16204587/12378382/87980c80-bd09-11e5-84e7-70f93152bb33.jpg)

**Comment by Tregeta** [comment]
Fixed next update
