### ISSUE TITLE
new trinkets

### ISSUE THREAD

**Issue by rusheddown** [Valhalla-Gaming/Tracker#4259]
when trying to equip both the orb of voidsight and jugment of the naaru i get an error saying you have the maximum number of those gems socketed into equipped items. i logged and cleared my cash but it still does the same thing.

**Comment by Aveta** [comment]
You can't equip more than one of the "Demonbane" trinkets, aka those 100-110 ones.

**Comment by Tregeta** [comment]
What Aveta said is true, only one at a time.
