### ISSUE TITLE
Razormane Pathfinder

### ISSUE THREAD

**Issue by unfairplayer** [Valhalla-Gaming/Tracker#4261]
There is a minor problem regarding the NPC Razormane Pathfinder. They are located in the Southern Barrens above Razorfen Kraul. The issue is that the ability Boar Net, which is meant to be aimed at a hostile unit, is sometimes cast on self. The pattern appears to be first at self, then at hostile, then again at self and so on. They don't seem to be using their Disengage ability either.

http://www.wowhead.com/npc=37560/razormane-pathfinder#abilities

**Comment by Tregeta** [comment]
fixed next update
