### ISSUE TITLE
[Ashenvale/Quest] - Gorat's Vengeance

### ISSUE THREAD

**Issue by RealiseWay** [Valhalla-Gaming/Tracker#4268]
If i arrived to Gorat NPC and i want use quest item, nothing happend.
wowhead: http://www.wowhead.com/quest=13621/gorats-vengeance#videos
video: https://www.youtube.com/watch?v=uOUpa8LLbmE

**Comment by Tobaccoz** [comment]
I suggest you to follow leveling guide on the forum made by Silverjade, all bugged quests are easily tracked there including this one.
https://valhalla-realms.com/forum/viewtopic.php?f=27&t=1782&start=40#p15566

**Comment by RealiseWay** [comment]
thank you

**Comment by Braemen** [comment]
#1744

**Comment by Seregruth** [comment]
Already reported #1744
