### ISSUE TITLE
[Quest] Axis of Awful from Thelsamar, Loch Modan

### ISSUE THREAD

**Issue by nmjayan** [Valhalla-Gaming/Tracker#4269]
[**Axis of Awful**](http://www.wowhead.com/quest=26868/axis-of-awful): Cannary's Cache is no longer empty, but the item [Potent Murloc Pheromones](http://www.wowhead.com/item=60503/potent-murloc-pheromones) does not work on the intended target. It works on you (maybe) and gives you a weird visual effect (indicating that YOU STINK; no debuff, though) that seems not to go away (until Death do us part!). Quest still cannot be completed, albeit for a different reason.

**Comment by Cidragon** [comment]
Fixed in December 25th changelog.
