### ISSUE TITLE
Provoke

### ISSUE THREAD

**Issue by Tobaccoz** [Valhalla-Gaming/Tracker#4271]
http://www.wowhead.com/spell=115546/provoke
Provoke doesn't kill totems, and it should.

**Comment by Moustachos** [comment]
Could you provide a source?

**Comment by Tobaccoz** [comment]
My bad, I meant Grounding totem - source wowhead, cant find article atm.

**Comment by Moustachos** [comment]
Apparently it's not supposed to be redirected to grounding totem anymore: http://www.arenajunkies.com/topic/295426-cant-growl-grounding-totem-anymore/
