### ISSUE TITLE
BUG , Ability Druid

### ISSUE THREAD

**Issue by aminbogy** [Valhalla-Gaming/Tracker#4279]
Hi,
Druids have BUG on this Ability :  [Ferocious Bite]
and when he use he attack + 130k , so its bug, please fix it faster, When we have any Druids in the Battle we cant win, just for BUG

**Comment by serenity-talador** [comment]
you are sure there is a bug ? i havent encounter that , can you be more specific ? which talents etc ?

**Comment by Tregeta** [comment]
This happens in retail also, as far as we can tell this is not a bug. We're still looking into it, but so far we have not been able to find anything wrong with the numbers, ergo working as intended.
