### ISSUE TITLE
CP Reset Weekly

### ISSUE THREAD

**Issue by aminbogy** [Valhalla-Gaming/Tracker#4285]
Hi,
how you do fixes? when you fix some thing then get BUG another things,
for now CP Reset weekly is bug, i wait for 10 DAYS and im FULL CP  and still didn't reset any thing, we need to reset it, is really important, for 10 days i lost CP from the Battle and Follower's missions and cant get more CP for gears, i agree all bugs but this is really FUNNY , 1 server without RESET CP and HONOR? how ?!!!

**Comment by Tobaccoz** [comment]
Nerd kid, this is issue/bug tracker, you post bugs explained so devs can fix them, not same raging shit about them.

**Comment by Luminescent-Hellscream** [comment]
Any fix can cause others to break even if it's a small simple fix welcome
to private servers

**Comment by aminbogy** [comment]
its a bad update when after it we get BUG's more than befor that update,
AND Tobaccoz , we are here for help server , and yeah im so much angry and sad when my cp is full and its didn't reset after 10 DAYS, we need better server after any update not bad server!!!

**Comment by Luminescent-Hellscream** [comment]
Last time when fixing things it can cause other things to break it's not
only our server it happens to all private servers and the track is not the
place for this so please do us a favor close this report and report the
issue not a nerd rage.

**Comment by aminbogy** [comment]
Dev's will close this post and i hope they fix it soon as possible,
