### ISSUE TITLE
Honor Hold Quartermaster

### ISSUE THREAD

**Issue by jpazminos** [Valhalla-Gaming/Tracker#4292]
The honor hold quartermaster http://www.wowhead.com/npc=17657 doesnt sell any reputation items

**Comment by Tregeta** [comment]
What items is it missing for you?

**Comment by jpazminos** [comment]
The http://www.wowhead.com/item=25825 and  http://www.wowhead.com/item=23999 among other items that it sells, its  really helpful for newbies or rep seekers

**Comment by Tregeta** [comment]
Please show us a photo of this vendor as it's currently working just fine for myself.

**Comment by jpazminos** [comment]
As you can see doesnt sell anything ![wowscrnshot_012416_205136](https://cloud.githubusercontent.com/assets/16790785/12540845/948bf432-c2dc-11e5-895b-cdad970c3e46.jpg)

**Comment by Tregeta** [comment]
Fixed next update
