### ISSUE TITLE
Shadowfang Keep, No NPCs or MOBs at all?

### ISSUE THREAD

**Issue by DarcianTheMage** [Valhalla-Gaming/Tracker#4293]
So I went to Shadowfang Keep as a level 14 Blood Elf Mage, and I realised that there was not a single NPC or MOB anywhere in the whole instance... I don't know why this happened, maybe because of my level? Anyway, it was weird so I had to put it on the tracker :3

**Comment by Tregeta** [comment]
We despawned the instance to fix a bug, Ref for the issue is also #3735
