### ISSUE TITLE
[Spell] [Talent] [Paladin] Pursuit of Justice

### ISSUE THREAD

**Issue by nmjayan** [Valhalla-Gaming/Tracker#4295]
[Pursuit of Justice](www.wowhead.com/spell=26023/pursuit-of-justice) should increase movement speed by 15% plus 5% per Holy Power. This is working correctly while running, but is bugged for mounts (of all kinds), and gives only a flat 10% increase, rather than a 15-30% increase.

**Comment by Tregeta** [comment]
Increases movement speed by 15%, plus an additional 5% for each charge of Holy Power up to 3.

**Comment by Moustachos** [comment]
Since patch 5.0.4 Pursuit of Justice no longer affects mounted speed, so this is the intended behavior.

**Comment by Moustachos** [comment]
Ref #2266
