### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by jovanpro** [Valhalla-Gaming/Tracker#4296]
I can't connect to the server. It comes to Successful then choose a realm and there is only Development without realm. Is the server down or what? Because I could log in earlier.

**Comment by sebbeyknow** [comment]
I got the same problem

**Comment by jovanpro** [comment]
The server could be down but on the website it says it's up :/ Any help?

**Comment by Collector-Valhalla** [comment]
Ask for help on [forum](https://valhalla-realms.com/forum/index.php). Here you report in-game bugs.

**Comment by Pure-Valhalla** [comment]
I just tried and got this.....

![wowscrnshot_012016_112607](https://cloud.githubusercontent.com/assets/14964856/12457208/f04a65e6-bf68-11e5-8a7c-bd0bf90a0ad1.jpg)

check development and click suggest realm. A blank ream selection will come up. Click cancel and it will bring you back to the log in screen and you should be able to log in.

**Comment by jovanpro** [comment]
Still.. There is just a blank realm selection again.

**Comment by Pure-Valhalla** [comment]
A server was "bugged", the issue should now be resolved.
