### ISSUE TITLE
Fire mage

### ISSUE THREAD

**Issue by Randomime** [Valhalla-Gaming/Tracker#4300]
The whole idea of a fire mage is burst. Which in wod case is much much pyros, which you get from hotstreak, which on Valhalla isn't working. And from what I saw, it should be procing...ALOT! And the second source of burst is combustion which in the current state does NOTHING but reset inferno blast....which is nothing since hotstreak doesnt work. PLS fix this as soon as possible and the mage class will be playable.

**Comment by war627** [comment]
just link the bugs and a short description not something like this
