### ISSUE TITLE
Blood Death Knight

### ISSUE THREAD

**Issue by Chimba** [Valhalla-Gaming/Tracker#4305]
Blood Death Knight in 6.2.3 should have a passive skill called "Riposte" which should give an equal amount of parry from critical strike from gear. As blood player should get an equal amount of attack power from bonus armor stat thanks to "Bladed Armor" passive skill. Also the parry chance should increase with Strenght.
I've read this stuff on websites with guides. Sorry if I'm wrong. :)

**Comment by Tregeta** [comment]
Ref #1655, Ref #843
