### ISSUE TITLE
Rams on the lam

### ISSUE THREAD

**Issue by DrKamiCraze** [Valhalla-Gaming/Tracker#4307]
This is a quest that is broken, and infact is important, because I dont believe you can get ram mounts without doing it. When you whistle at the stolen ram, It does NOT go back to its "home" nor do you get a point. This issue has been posted TWICE now and no one has fixed it. If its unfixable, atleast just remove it so we can get rams. Thank you.

**Comment by Tregeta** [comment]
Have you also tried to buy a mount on a dwarf or a dwarf DK?

**Comment by Trekex** [comment]
Actually you can buy rams from the vendor. (I am a Dwarf)

**Comment by Cidragon** [comment]
Fixed in December 25th changelog.
