### ISSUE TITLE
[spell] resolve

### ISSUE THREAD

**Issue by lavalash551** [Valhalla-Gaming/Tracker#4318]
http://www.wowhead.com/spell=158298/resolve
This spell should increase healing and absorbtion while being in a combat and getting damage.
I have got it in my spell book but it doesnt seem to do something. If you get damage, a buff appears:
http://www.wowhead.com/spell=158300/resolve
This buff is missing and if you fight the same mob as paladin tank and paladin dps in both cases the self heal is nearly the same in the same gear, So it doesnt work and needs to be fixed because this spell is used by all 5 tank classes and one of the most important passive.

**Comment by lavalash551** [comment]
Ehm, this spell is used by paldins, monks,warriors, death knights and druids - not only by paladins!

**Comment by Tregeta** [comment]
We are aware it is, we cannot set multiple milestones.

**Comment by Collector-Valhalla** [comment]
http://blues.wowraider.net/blue/us2/13271747932/Tank-Specs-in-PvP?1404947985

Does it work in pvp combat? I'm still searching for some more info but according to blue post above resolve doesn't work in pvp combat and tank specs have increased damage taken by 25%.

Is it right/true/retail-like etc?

**Comment by nmjayan** [comment]
Read through the whole thing. Towards the end, it says that Resolve does work (or might work) in PvP. Also, this is not confirmed info, just a random set of posts.

**Comment by Collector-Valhalla** [comment]
i tried sry

**Comment by nmjayan** [comment]
No, it's OK. This doesn't mean it works, either. It just needs to be cross-checked with retail or an equally reliable source.
