### ISSUE TITLE
[spell] Rising Sun Kick

### ISSUE THREAD

**Issue by lavalash551** [Valhalla-Gaming/Tracker#4321]
http://www.wowhead.com/spell=107428/rising-sun-kick
how it should work: 
You kick upwards, dealing [11.0 * ((1.0 * (1 + $versadmg)) * (0.857143 * (Mainhand Min DPS + 1 * (Offhand Min DPS /2)) + Attack power / 3.5 - 1))] to [11.0 * ((1.0 * (1 + $versadmg)) * (0.857143 * (Mainhand Max DPS + 1 * (Offhand Max DPS /2)) + Attack power / 3.5 + 1))] damage and causing all enemies within 8 yards to take 20% increased damage from your abilities for 15 sec.
How it works:
It does 1 damage point and there is neither a debuff on targets that increase damage taken by 20% nor healing reduced.

**Comment by Collector-Valhalla** [comment]
Deals 2 points of damage if you crit.

hihi
