### ISSUE TITLE
shirvallah animation

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#4326]
http://www.wowhead.com/spell=171745/claws-of-shirvallah

...

Also idk if this was bugged on "other place" that I played or is it same on retail but when you cast fishing you go back to humanoid form instead of being in that kitty form.

And when you press M to view map nothing happens with shirvallah animation.

EDIT: checked wowhead for more info and removed part with /dance animation. Apparently shirvallah can't dance.

**Comment by Moustachos** [comment]
Claws of Shirvallah is also removed when fishing on retail and there's no animation when you open the map either.
