### ISSUE TITLE
The WoodLand Protector (NPC NOT SPAWNING)

### ISSUE THREAD

**Issue by PheonixArrow** [Valhalla-Gaming/Tracker#4328]
"Seek out the dryad known as Tarindrella within the Shadowthread Cave at the northern end of Shadowglen" .
Now the issue is the Dryad Tarindrella won't show up inside the cave please, she just won't spawn please spawn her there, please fix it fast because it is a major quest if you don't complete it you can't do any other quests and you are stuck
Example
https://www.youtube.com/watch?v=3xayCF0VgEs
http://www.wowhead.com/quest=28725/the-woodland-protector

**Comment by carminejackal** [comment]
I can confirm, Tarindrella isn't spawning upon reaching/entering the cave.

**Comment by Valhalla-Gaming** [comment]
Fixed
