### ISSUE TITLE
[spell] Spinning Crane Kick

### ISSUE THREAD

**Issue by lavalash551** [Valhalla-Gaming/Tracker#4332]
http://www.wowhead.com/spell=101546/spinning-crane-kick
How it should work:
You spin while kicking in the air, 

 Mistweaver
healing up to 6 allies within 10 yards for [4 * (49.375% of Spell power)] over 2.25 sec

 Brewmaster and  Windwalker
dealing [(4 * 0.9 * ((1.0 * (1 + $versadmg)) * (0.857143 * (Mainhand Min DPS + 1 * (Offhand Min DPS /2)) + Attack power / 3.5 - 1)) + 4 * 0.9 * ((1.0 * (1 + $versadmg)) * (0.857143 * (Mainhand Max DPS + 1 * (Offhand Max DPS /2)) + Attack power / 3.5 + 1))) / 2] damage over 2.25 sec to enemies within 8 yards

Generates 1 Chi if it strikes 3 or more targets.

 Brewmaster
Channeling Spinning Crane Kick does not prevent avoiding attacks

 Empowered Spinning Crane Kick (Level 92+)
Requires Windwalker
Spinning Crane Kick now deals damage twice as fast, but its duration is reduced by 50%.
How it works:
You can see only the visual effect, but does no damage and doesnt generates any chi.

**Comment by Tregeta** [comment]
fixed next update
