### ISSUE TITLE
[NPC] Bunthen Plainswind

### ISSUE THREAD

**Issue by rover4fun** [Valhalla-Gaming/Tracker#4339]
http://www.wowhead.com/npc=11798/bunthen-plainswind
Druid-only fly master seems to not recognize druids correctly.
![wowscrnshot_012316_230622](https://cloud.githubusercontent.com/assets/16857913/12533400/eeb71376-c226-11e5-9faf-c0f0f7f20ea2.jpg)

**Comment by Tregeta** [comment]
Ref #2057
