### ISSUE TITLE
[Raid] Tempest Keep - Kael'thas phase 3

### ISSUE THREAD

**Issue by Aveta** [Valhalla-Gaming/Tracker#4355]
Seems to have been broken with latest update. In phase 3, Kael resurrects his advisors. Before recent update it was going fine, but today I noticed the advisors don't get their hp restored, I can't attack them, their names are greyed out AND they attack and use skills on me. Since now Kael doesn't attack until advisors are killed, you can't complete the raid. (;o;)
![wowscrnshot_012416_192338](https://cloud.githubusercontent.com/assets/14302942/12538650/01210a90-c2df-11e5-922c-5054894d70f7.jpg)

**Comment by serenity-talador** [comment]
Except if there was a maj in the last 3 days , it worked perfectly for me

**Comment by Aveta** [comment]
It was working perfectly before. It's the Sunday update that broke it as my bf did it in Saturday when it still worked.

**Comment by Pure-Valhalla** [comment]
Confirmed that it was broke.
I just tested this on my player account and it is working again.

**Comment by serenity-talador** [comment]
Tested just now doesnt work on talador :/ 
![wowscrnshot_020916_154343](https://cloud.githubusercontent.com/assets/16447897/12919385/18a95fac-cf44-11e5-8839-14ed95125c96.jpg)

**Comment by Aveta** [comment]
You will have to wait until update that was implemented on Valhalla last Saturday iirc.
