### ISSUE TITLE
The Reckoning

### ISSUE THREAD

**Issue by Necrolized** [Valhalla-Gaming/Tracker#4366]
Can't Talk with King Jokkum in Dun Niffelem

http://www.wowhead.com/quest=13047/the-reckoning

**Comment by Tregeta** [comment]
Do you have reputation to speak with him?

**Comment by Necrolized** [comment]
Just checked, and no. Can't get the rep tho. The quest leading to the moment you can farm the rep are bugged too.

**Comment by Tregeta** [comment]
Thank you, I'll verify on my end with reputation.

**Comment by Tregeta** [comment]
It does appear you do need reputation to speak with him to turn in the quest.
