### ISSUE TITLE
[Spell] Lay on Hands

### ISSUE THREAD

**Issue by Luminescent-Valhalla** [Valhalla-Gaming/Tracker#4378]
Since the last update Lay on hands no longer works once you activate it the spell goes on CD as though it has been used but does not heal at all, Before the last update Lay on Hands was working fine.

**Comment by nmjayan** [comment]
Note that this correctly generates the Forbearance debuff even now.

**Comment by Luminescent-Valhalla** [comment]
Issue has been resolved closing report.
