### ISSUE TITLE
[Monk] [Talent] Rushing Jade wind

### ISSUE THREAD

**Issue by Bombrick** [Valhalla-Gaming/Tracker#4385]
Rushing jade wind doesn't work , It gives animation sound and replaces blackout kick but doesn't do damage.

**Comment by Tregeta** [comment]
http://www.wowhead.com/spell=116847/rushing-jade-wind

Dev Note: It is not blackout kick that it replaces but Spinning Crane Kick

**Comment by Bombrick** [comment]
yeah sorry forgot
