### ISSUE TITLE
[Quest] The Earthbinder

### ISSUE THREAD

**Issue by nmjayan** [Valhalla-Gaming/Tracker#4386]
[This](http://www.wowhead.com/quest=10349/the-earthbinder) quest cannot be turned in. [The NPC](http://www.wowhead.com/npc=19294/earthbinder-galandria-nightbreeze) cannot be interacted with.

**Comment by Tregeta** [comment]
Not able to reproduce, clear cache, wait for event to happen.

**Comment by nmjayan** [comment]
This seems to be working, as of now.

**Comment by Tregeta** [comment]
Different quest, open a new issue.
