### ISSUE TITLE
Shard of Third Moon

### ISSUE THREAD

**Issue by canadianpali** [Valhalla-Gaming/Tracker#4388]
http://www.wowhead.com/item=133598/purified-shard-of-the-third-moon this item inshop absorbs more then 100k and one inshop dosnt have a cooldown

**Comment by canadianpali** [comment]
http://www.wowhead.com/item=133598/purified-shard-of-the-third-moon this item inshop absorbs more then 100k and one inshop dosnt have a cooldown

**Comment by Tregeta** [comment]
It does have a cooldown, and it seems to expire as intended when the absorb amount is reached. 

Unable to reproduce.
