### ISSUE TITLE
Ring Of Frost Bug

### ISSUE THREAD

**Issue by payamsalehi33** [Valhalla-Gaming/Tracker#4390]
Hi
There Is One Bug Of Mage
Ring Of Frost Is Bug I Cant Use It
Please fix it !!

**Comment by payamsalehi33** [comment]
Hi
There Is One Bug Of Mage
Ring Of Frost Is Bug I Cant Use It
Please fix it !!

**Comment by Tregeta** [comment]
Tell us what the bug is... Guessing on what it is will tell us nothing.
