### ISSUE TITLE
Warrior Spell - Avatar

### ISSUE THREAD

**Issue by niksunstz1** [Valhalla-Gaming/Tracker#4393]
When i change my talent to Avatar and use the magic it works but when i use it second time it uses bladestorm even though i am with the Avatar talent ...

**Comment by Moustachos** [comment]
Can't reproduce, does it still happen to you?

In which circumstances?

**Comment by EPS1L0N** [comment]
this was fixed a while ago, had to do with dual talent spec's interfering with each other

**Comment by EPS1L0N** [comment]
#2266
