### ISSUE TITLE
Paladin Holy Power bugs 

### ISSUE THREAD

**Issue by Bombrick** [Valhalla-Gaming/Tracker#4395]
Paladin spells use one holy power as it is 3 holy power .

**Comment by Tregeta** [comment]
Not enough information, need spell names.

**Comment by Bombrick** [comment]
> Not enough information, need spell names.
for all spells which consumes holy power  there are so many I can't list them all

**Comment by Tregeta** [comment]
Without the information to go on, this issue will now be closed. Should you feel you have the time to provide such details we will reopen and flag appropriately.
