### ISSUE TITLE
Shaman Spell Bug: Enhanced Chain Lightning

### ISSUE THREAD

**Issue by niveks1** [Valhalla-Gaming/Tracker#4396]
This spell don`t work http://www.wowhead.com/spell=157765/enhanced-chain-lightning

**Comment by Tregeta** [comment]
Which part? more information needed....

**Comment by niveks1** [comment]
When chain lightning or lava beam strikes 3 or more targets the next Earthquake should be instant but it is not, and earthquake damage should be increased by 300% but it doesn't

**Comment by Tregeta** [comment]
Thank you.

**Comment by Moustachos** [comment]
Ref #2266
