### ISSUE TITLE
[Priest][Talent][Spell] some issues

### ISSUE THREAD

**Issue by Aprophys** [Valhalla-Gaming/Tracker#4399]
Surge of Light dont procc http://www.wowhead.com/spell=114255/surge-of-light
Mindbender http://www.wowhead.com/spell=123040/mindbender 
and Shadowfient http://www.wowhead.com/spell=34433/shadowfiend 
dont make any damage and dosnt restore mana
Powerword Solace dont restore mana http://www.wowhead.com/spell=129250/power-word-solace
Spirit shell dont gives u a shield http://www.wowhead.com/spell=109964/spirit-shell
Devine Star http://www.wowhead.com/spell=110744/divine-star and 
Halo http://www.wowhead.com/spell=120517/halo dont work 
Powerword: Shield http://www.wowhead.com/spell=17/power-word-shield
block dmg it should be absorb

**Comment by Bombrick** [comment]
> block dmg it should be absorb
It's actually block and absorb in the same time :<

**Comment by Aprophys** [comment]
block dmg it should be absorb

i allready report it

**Comment by Aprophys** [comment]
abd he monk guard talent/spell its the same and its to much

its sems the formulars arent wod like
if u see any wod pvp streams u will see fast whats goin wrong here

**Comment by Tregeta** [comment]
Spirit Shell should be fixed.
