### ISSUE TITLE
[NPC] [Azshara] [Duplicate] Talrendis Ancient 

### ISSUE THREAD

**Issue by PacoTheLegend** [Valhalla-Gaming/Tracker#4400]
There are two Talrendis Ancient mobs really close to each other in the Ancient Grove.

Wowhead: http://www.wowhead.com/npc=35198/talrendis-ancient

Screenshot:
![wowscrnshot_012516_223342](https://cloud.githubusercontent.com/assets/16710281/12629955/fc3cad8a-c541-11e5-9471-f3daddd6d547.jpg)

**Comment by Tregeta** [comment]
Fixed
