### ISSUE TITLE
[NPC] [Azshara] [Duplicate] Labor Captain Grabbit

### ISSUE THREAD

**Issue by PacoTheLegend** [Valhalla-Gaming/Tracker#4401]
Two NPCs very close to each other. Each of them gives different quests.

Wowhead: http://www.wowhead.com/npc=35086/labor-captain-grabbit

Screenshots:
![wowscrnshot_012516_223131](https://cloud.githubusercontent.com/assets/16710281/12630158/05c6459a-c543-11e5-88fd-ade308efb99f.jpg)
![wowscrnshot_012516_223135](https://cloud.githubusercontent.com/assets/16710281/12630159/07b3d0d4-c543-11e5-8617-7c1d360e9fae.jpg)

**Comment by Tregeta** [comment]
fixed
