### ISSUE TITLE
Balance druid bg starfall bug

### ISSUE THREAD

**Issue by 90isti90** [Valhalla-Gaming/Tracker#4402]
The balance druid starfall spell when casted dos no animation and no dmg  in batelground,it shows the spell is used ath the buf and its cd but dos noting. Ty for corecting it in advance :)

**Comment by Aveta** [comment]
Just a question: did you have Moonfire/Sunfire applied on people? Glyph of Untamed Stars doesn't work, so Starfall only damages things affected by those.
If you had and it still didn't work then forget the question.

**Comment by 90isti90** [comment]
Yes i had the dots aplide

**Comment by skorge1** [comment]
Also when i use starfall with or without the glyph is it shown as a debuff instead of a buff.

**Comment by Moustachos** [comment]
Couldn't reproduce the initial issue, looks like an isolated bug.

> Also when i use starfall with or without the glyph is it shown as a debuff instead of a buff.

Will be fixed on next update.

**Comment by Moustachos** [comment]
Ref #2266
