### ISSUE TITLE
[Spell] [Paladin] Lay on Hands

### ISSUE THREAD

**Issue by nmjayan** [Valhalla-Gaming/Tracker#4408]
[This spell](http://www.wowhead.com/spell=633/lay-on-hands) ought to heal a friendly target for an amount equal to the paladin's maximum health, but currently does nothing but cause forbearance for a minute. Used to work correctly until recently.

**Comment by Luminescent-Valhalla** [comment]
I reported this the day it stopped working

Ref : #4378
