### ISSUE TITLE
Divine Aegis

### ISSUE THREAD

**Issue by miloskovac** [Valhalla-Gaming/Tracker#4410]
Divine Aegis is broken on priests. It should make critical heals absrob (that if a spell crits, it heals normaly instead of double but the other half is absorb), and it heals double on crit and make replica of the heal amount in absorb (120k and so).
Please consider that fighting the priest on higher ilvl is imposible and even few ppl cant bring the priests down.
Also plz take a look at the shadow priests cascade spell. It dmg for way too much and can easily kill 5+ well geared ppl in seconds.

**Comment by Collector-Valhalla** [comment]
http://www.wowhead.com/spell=47515/divine-aegis#comments
"...there is a hidden absorption cap equal to 20% of your maximum health..."
"Two divine aegis buffs can stack if they come from two different players."
"...only multistrikes of critical heals trigger it."

**Comment by Collector-Valhalla** [comment]
http://us.battle.net/wow/en/blog/16561637/603-hotfixes

I have found here line - **Divine Aegis should now correctly absorb only 50% as much in PvP.**

**Comment by Moustachos** [comment]
Ref #2266
