### ISSUE TITLE
Sebelia & Iris Moondreamer no dialouge options

### ISSUE THREAD

**Issue by GeneralCaveman** [Valhalla-Gaming/Tracker#4413]
http://www.wowhead.com/npc=40843/sebelia
http://www.wowhead.com/npc=71304/iris-moondreamer

These two NPCs are able to be interacted with but interacting with them does not bring up their respective dialogue options.

**Comment by Tregeta** [comment]
Sebelia updated next patch

**Comment by Tregeta** [comment]
fixed next update
