### ISSUE TITLE
Enchanced Aimed shot

### ISSUE THREAD

**Issue by Ibuprofen5961** [Valhalla-Gaming/Tracker#4419]
Should give u 20 focus when aim shot crits but it does not

http://www.wowhead.com/spell=157724/enhanced-aimed-shot

**Comment by Trekex** [comment]
I think that for me it works... I'll check better, but I'm mostly sure

**Comment by Moustachos** [comment]
Works fine.

**Comment by Moustachos** [comment]
Ref #2266
