### ISSUE TITLE
DK lvl 75 talents

### ISSUE THREAD

**Issue by vlath19** [Valhalla-Gaming/Tracker#4431]
the 3 lvl 75 deathknight talents don't work 
when you spend runic power blood tap isn't generate a Blood Charge to be consumed, runic empowement isn't activate a random fully depleted rune like it says and runic corruption isn't increase the runes regeneration
http://www.wowhead.com/spell=45529/blood-tap
http://www.wowhead.com/spell=81229/runic-empowerment
http://www.wowhead.com/spell=51462/runic-corruption

**Comment by Tregeta** [comment]
Ref #1962
