### ISSUE TITLE
Maelstorm weapon don't work

### ISSUE THREAD

**Issue by aymenbf** [Valhalla-Gaming/Tracker#4435]
I don't get maelstorm weapon stacks which means no instant heals no instant lightning bolts , plus tremor totem don't work too can you please fix this as soon as possible :)

**Comment by Tregeta** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/3596 & https://github.com/Valhalla-Gaming/Tracker/issues/2802
