### ISSUE TITLE
Quatermaster Brazie

### ISSUE THREAD

**Issue by lavalash551** [Valhalla-Gaming/Tracker#4443]
http://www.wowhead.com/npc=47328/quartermaster-brazie
NPC sells only 4 items but should sell 22.
I took a screen shot to prove.
![wowscrnshot_013116_143339](https://cloud.githubusercontent.com/assets/16776049/12702395/22de7520-c828-11e5-9228-0ae6a5b4bb8d.jpg)

**Comment by Tregeta** [comment]
Fixed Error in conditions that were incorrectly displaying the items. Will be applied on next restart or update.
