### ISSUE TITLE
things i can do in stealth

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#4455]
I have no idea if that affects mages and rogues but as a feral druid I am able to cast things like [Rejuvenation](http://www.wowhead.com/spell=774/rejuvenation) and [Healing Touch](http://www.wowhead.com/spell=5185/healing-touch) IN stealth. Also if I use [Rake](http://www.wowhead.com/spell=1822/rake) in stealth and it gets [dodged](http://www.slate.com/content/dam/slate/articles/news_and_politics/the_slate_quiz/authorPortraits/pronounce_doge4.jpg.CROP.promovar-mediumlarge.jpg) I'm still in stealth (maybe it's retail like idk). Same thing happens when I one shot some mob with rake or shred in stealth (I don't know about players).  I have no idea if there's some more things I can do in [Prowl](http://www.wowhead.com/spell=5215/prowl). 

There's already reported that you can cap flags/bases in stealth. #3861

EDIT: I can also cast buff without breaking the prowl.

**Comment by EPS1L0N** [comment]
> Also if I use Rake in stealth and it gets dodged I'm still in stealth (maybe it's retail like idk)

nah, doesn't do that on blizz

**Comment by Djurdjevdan** [comment]
There are lot more things to so while in steath and GMs know it. Let us try not to use it in pvp.

**Comment by Luminescent-Valhalla** [comment]
Same with mage invisibility also.

**Comment by EPS1L0N** [comment]
retest the mage invisibility part again if you could please, we just updated a few hours ago

**Comment by Luminescent-Valhalla** [comment]
I can confirm mates can no longer cast while using invisibility

**Comment by EPS1L0N** [comment]
thanks
