### ISSUE TITLE
Build Your Barracks

### ISSUE THREAD

**Issue by GeneralCaveman** [Valhalla-Gaming/Tracker#4461]
http://www.wowhead.com/quest=34587/build-your-barracks

After collecting/learning the blueprints and building my barracks, the quest was unable to be turned in. I then reacquired the quest and was able to collect the plans again but the issue is the "Learn Blueprints" part of the objective is currently 1/1 but isn't greyed out like what normally happens when you complete an objective.

![wowscrnshot_020116_185736](https://cloud.githubusercontent.com/assets/12555606/12735411/af5feeb4-c915-11e5-875d-fccba0040d7e.jpg)

I am not sure what the cause of this was as I have been able to build barracks on other toons so it might not be easy to replicate.

As a temporary thing, is there anyway to auto-complete or reset this quest completely on my toon "Cavewoman"? As I am currently unable to continue the questlines for garrisons with this bug.

**Comment by Tregeta** [comment]
It is possible to, you will need to speak with an in-game GM.

**Comment by habagatamihan** [comment]
I think it's fixed now. I was able to complete the quest.
![image](https://cloud.githubusercontent.com/assets/17206201/23826380/165957a0-06d6-11e7-97ec-f13c66745b79.png)
