### ISSUE TITLE
Paladin talents lvl 30 & 90 don't work

### ISSUE THREAD

**Issue by hiretax** [Valhalla-Gaming/Tracker#4462]
Holy prism, light's hammer, execution sentence, sacred shield and eternal flame don't do anything. I only want that you at least fix one of lvl 30 and one of lvl 90, so paladin won't be the worst class!

**Comment by Tregeta** [comment]
Already reported.

Eternal Flame 	#2827
Execution Sentence  #1470, #1748
Holy Prism #1468, #1748
Light's Hammer #1469, #1748, #3754
Sacred Shield 	#1385
