### ISSUE TITLE
capturing in stealth

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#4463]
That area around carts in silvershard mines and bases in eye of the storm can be captured by players in stealth. I think that should not be possible and only players outsite stealth should be able to do that. But I'm not sure.

**Comment by EPS1L0N** [comment]
> I think that should not be possible and only players outsite stealth should be able to do that. But I'm not sure.

correct

**Comment by Luminescent-Valhalla** [comment]
confirmed capping on 25th jan 2016 was still not working as it should forgot i had this screenshot 

[Druid stealth cap](http://i.imgur.com/n0RplC2.jpg)

**Comment by EPS1L0N** [comment]
@Luminescent-Valhalla that is a different issue, that is #3861 which you already commented on looks like
