### ISSUE TITLE
[Borean Toundra] [NPC] Maigra Keenfeather

### ISSUE THREAD

**Issue by K-Reeboo** [Valhalla-Gaming/Tracker#4464]
The NPC, shown on screen, should propose to train us for Riding and Cold Weather Flying.
Actually clicking her does nothing, no gossip window or trade window opens

![wowscrnshot_020216_021451](https://cloud.githubusercontent.com/assets/16204587/12742354/ea89e692-c952-11e5-93bf-cd0dbe9c1b90.jpg)

**Comment by Tregeta** [comment]
fixed
