### ISSUE TITLE
[Warrior] [Glyph] Shield Slam

### ISSUE THREAD

**Issue by Myrmidonx** [Valhalla-Gaming/Tracker#4477]
The glyph doesn't work

www.wowhead.com/spell=58375/glyph-of-shield-slam

**Comment by Moustachos** [comment]
The glyph is working.

However, the
> if you are in Defensive Stance.

Restriction,wasn't implemented, it will be fixed on next update.

**Comment by Moustachos** [comment]
Ref #2266
