### ISSUE TITLE
Quest: Dealing with Zeb'Sora

### ISSUE THREAD

**Issue by thnder** [Valhalla-Gaming/Tracker#4479]
The Ranger Valanna in Ghostland - Lake Elrendar dont't give the quest in object

**Comment by thnder** [comment]
Whit this all the chain is locked ( Quest Report to Captain Helios from the same NPC )

**Comment by carminejackal** [comment]
I was able to get this quest on my orc mage. Did you turn in Help Ranger Valanna! prior to attempting to get this quest?

**Comment by thnder** [comment]
you are roght i've done yesterday after your suggestion
Thx
