### ISSUE TITLE
Warrior Shield Barrier bug abuse

### ISSUE THREAD

**Issue by miloskovac** [Valhalla-Gaming/Tracker#4480]
Hello ppl.
Warriors abuse bug on shield barrier to absorm 50k every 1.5 sec making them lituraly imposible to kill.

**Comment by Tobaccoz** [comment]
It also costs 40 instead of 20 rage.

**Comment by Myrmidonx** [comment]
id like to know if you are a pvp geared char, cause im not seeing a -bug- there

the skill is working as intended -imho-
(despite the resolve issue)

**Comment by Luminescent-Valhalla** [comment]
[shield barrier](http://www.wowhead.com/spell=112048/shield-barrier#comments:id=2071980)

Also "Consumes up to 40 additional Rage to increase the amount absorbed." meaning this spell can actually consume upto 60 rage for larger shields.

**Comment by Tregeta** [comment]
@OriginalDeath

> Shield barrier only absorbs ''1'', when it should be absorbing a lot more.

**Comment by Moustachos** [comment]
Works as intended, absorb amount matches the tooltip.

**Comment by Moustachos** [comment]
Ref #2266
