### ISSUE TITLE
Monk guard ability

### ISSUE THREAD

**Issue by miloskovac** [Valhalla-Gaming/Tracker#4481]
Hello ppl.
Monks spam the spell Guard ad its always the same amount of absorb...and it should b the more dmg they take the more aborb they get. They get max absorb even on full hp.

**Comment by Moustachos** [comment]
Yes you're right, currently Guard is absorbing the same amount of damage regardless of taken damage because Resolve mechanic (the passive affecting Guard's amount) isn't implemented yet.

We're aware of that issue and Resolve is one of our spell priorities.
