### ISSUE TITLE
Lonewolf bugged

### ISSUE THREAD

**Issue by aymenbf** [Valhalla-Gaming/Tracker#4486]
When i use lonewolf and i go to bg or arena i loose the 30% dmg bonus of lone wolf only the buff effect stay, the bonus dissapear so i have to pick another talent and i go back to lonewolf to get it back ! i tested the dmg while the 30% dmg bonus dissapeared it's bugged i don't get the dmg bonus

**Comment by Trekex** [comment]
Just call your pet and dismiss it. The buff comes back.

**Comment by Trekex** [comment]
Also when you die in BG and res the [Lone Wolf](http://www.wowhead.com/spell=155228/lone-wolf) buff disappears. I do not know if on retail it stays.
