### ISSUE TITLE
Druid Spell: Hurricane/Astral Storm

### ISSUE THREAD

**Issue by skorge1** [Valhalla-Gaming/Tracker#4490]
First i would like to point our that damage for http://www.wowhead.com/spell=16914/hurricane is fine but the issue is when your eclipse goes into the lunar stage (hurricane) does not change into  http://www.wowhead.com/spell=106996/astral-storm. is suppose to change damage and visual effect.

**Comment by Moustachos** [comment]
It's not a bug, since WoD you must get http://www.wowhead.com/item=118061/glyph-of-the-solstice to have Astral Storm.

**Comment by Moustachos** [comment]
Ref #2266
