### ISSUE TITLE
Paladin mastery bug

### ISSUE THREAD

**Issue by avandarkwalker** [Valhalla-Gaming/Tracker#4498]
Mastery doesn't work on any paladin spec at all
http://www.wowhead.com/spell=76669/mastery-illuminated-healing doesn't give shield when healing
http://www.wowhead.com/spell=76671/mastery-divine-bulwark this doesn't give anything 
http://www.wowhead.com/spell=76672/mastery-hand-of-light no extra damge as it should be

**Comment by Luminescent-Valhalla** [comment]
Mastery: Illuminated Healing Already reported 
ref : #4076

**Comment by Moustachos** [comment]
Ref #2266
