### ISSUE TITLE
warrior [weapon master] bug arms spec

### ISSUE THREAD

**Issue by avandarkwalker** [Valhalla-Gaming/Tracker#4503]
http://www.wowhead.com/spell=76838/mastery-weapons-master 
doesn't increase damge of Mortal Strike, Colossus Smash and Execute

**Comment by sandokana** [comment]
I think this mastery works fine. Tested it with my warr.

**Comment by avandarkwalker** [comment]
yes my mistake about that part but it doesn't increase the damge of execute as it should 



—

**Comment by Moustachos** [comment]
This mastery also works fine for Execute, just checked.

**Comment by Moustachos** [comment]
Ref #2266
