### ISSUE TITLE
Druid: Flight form

### ISSUE THREAD

**Issue by Djurdjevdan** [Valhalla-Gaming/Tracker#4510]
We finaly got flight form and travel form seperated. However when you select flight form, it happens nothing. By nothing i mean you can shapeshift into something else and the only difference you will see is flight icon on top right. So basicly it dose nothing. On the other hand travel form still shapeshift you into bird instead of stag even with Glyph of Stag.

**Comment by Tregeta** [comment]
Stag glyph ref #1802

**Comment by Moustachos** [comment]
Ref #2266
