### ISSUE TITLE
[Glyph] Rogue Glyphs

### ISSUE THREAD

**Issue by Aveta** [Valhalla-Gaming/Tracker#4528]
I checked a bunch of my glyphs after noticing the Glyph of Poisons http://www.wowhead.com/spell=58038/glyph-of-poisons suddenly started giving me instant poison application for my weapons and discovered that after one of the recent updates all of the following glyphs had their effectiveness doubled:
http://www.wowhead.com/spell=56813/glyph-of-ambush (+10 yards instead of 5)
http://www.wowhead.com/spell=56801/glyph-of-cheap-shot (+1s instead of 0,5)
http://www.wowhead.com/spell=56799/glyph-of-evasion (+10s instead of 5)
http://www.wowhead.com/spell=56804/glyph-of-feint (+4 s instead of 2)
http://www.wowhead.com/spell=58033/glyph-of-safe-fall (checked when porting to Deepholm, I lost about 50% of my HP before with the fall, now it's only 25%)
I guess this is why Glyph of Stealth blocks it now - because it puts Stealth on a negative CD.
I used only glyphs I own, so there can be more.
I decided to put them all in one issue as they have the exact same bug.

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #2266
