### ISSUE TITLE
Prot warrior dmg reduction

### ISSUE THREAD

**Issue by miloskovac** [Valhalla-Gaming/Tracker#4530]
Hello ppl.
Besides the Shield barrier not working properly, dmg reduction on warriors is unbeliveble.
Also they have dmg reduction on all dmg, not just physical, frost also and shadow also.
Plz review the dmg reduction system.

**Comment by Collector-Valhalla** [comment]
> Plz review the dmg reduction system.

Please check if bleeds are affected by enemies armor. They shouldn't.
http://wowwiki.wikia.com/wiki/Bleed

**Comment by EPS1L0N** [comment]
bleeds are not reduced by armor.
