### ISSUE TITLE
Passive auras

### ISSUE THREAD

**Issue by miloskovac** [Valhalla-Gaming/Tracker#4533]
Hello ppl.
Passive auras r sometimes missing after some1 in group buff ppl.
On my dk it is a Unholy aura missing if some dudu buff mark of wild, on my hunter trueaura (10% ap) when some dk blow horn...

**Comment by Luminescent-Valhalla** [comment]
@miloskovac 

 Death Knight Frost | Unholy
 Unholy Aura

 Druid Balance
Moonkin Form/ Moonkin Aura

 Priest Shadow
 Shadowform/ Mind Quickening

 Rogue
 Swiftblade's Cunning

Make sure when it happens if one of thse buffs above is shown on your character if so then its working as intended

**Comment by Tregeta** [comment]
Buffs are consolidated into different types. You can learn more about which share the same aura type here : http://www.wowhead.com/guide=1100/buffs-and-debuffs
