### ISSUE TITLE
Gronntooth War Horn

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#4541]
http://www.wowhead.com/item=133595/gronntooth-war-horn
http://www.wowhead.com/spell=201404/demonbane

Procs from every hit/ability.

**Comment by Collector-Valhalla** [comment]
fixed?

**Comment by Trekex** [comment]
• Fixed proc rates for Gronntooth War Horn and Orb of Voidsight

Changleog say so. I think they forgot to close this?
