### ISSUE TITLE
Fishing not working

### ISSUE THREAD

**Issue by Th3hydra** [Valhalla-Gaming/Tracker#4543]
I tried fishing and every time I cast out and click the bobber when i'm supposed to, (after the splash and animation) and it tells me that I've interrupted the channel. I have a post on the forums about this, but figured I should make a bug report to make it official. I've tried multiple fishing locations that are appropriate for my fishing level and tried the shiny bauber to see if it was a level issue. Nothing is working. 
if it helps I'm a level 18 tauren monk and even tried it on my level 46 druid tauren. Still nothing. I've fished in Thunder bluff, Ogrimar, and trisfal, still nothing. I've also cleared my cache to see if that was the issue and still nothing.

**Comment by Hawnicide** [comment]
I also am experiencing this problem. The last time i fished (1/30/16) everything was working fine, however when I tried this evening I received the the same "interrupted" message when ever i tried to land a fish. Hopefully the time table helps!

**Comment by viktorianus** [comment]
I learned fishing but can't catch fish. And fishing disappears after relogging so the issue is getting worse.

**Comment by Moustachos** [comment]
Please retry after next update and tell us if it's still happening.

**Comment by GamerCrazy2** [comment]
This is Still happeneing 5 months later :/
