### ISSUE TITLE
Rogue assasination mastery

### ISSUE THREAD

**Issue by Cyuty** [Valhalla-Gaming/Tracker#4547]
Potent poisons shoed increase dmg of poison and envenom but it dosent work. I even cap mastery full buff to 99.89% and dmg was the same.

Off-topic:Fixing envenom and mastery will make class playing to 90% and it will be great.But rogue beeing in the last prior classes to be fix it will be some time when we see the changelog with some fix.
Devs are doing a great job and every changelog gives me a big doze of drogs. Lova Ya!!

**Comment by Tregeta** [comment]
http://www.wowhead.com/spell=76803/mastery-potent-poisons

http://www.wowhead.com/spell=32645/envenom

**Comment by Moustachos** [comment]
As of current version Mastery: Potent Poisons properly increases poisons aswell as Envenom's damage.

Envenom's damage was fixed on last update.

**Comment by Moustachos** [comment]
Ref #2266
