### ISSUE TITLE
Incinerate (Destruction Warlock)

### ISSUE THREAD

**Issue by hiretax** [Valhalla-Gaming/Tracker#4549]
Incinerate should use 5% of base mana, but this spell is using 20% of mana base in Valhalla! So you have low mana quickly. 
http://www.wowhead.com/spell=29722/incinerate

**Comment by Tregeta** [comment]
Could be related to https://github.com/Valhalla-Gaming/Tracker/issues/4250

**Comment by nuhrii** [comment]
As of the legion update, it is acting as if it has the Fire and Brimstone Talent selected even when it has not been selected
