### ISSUE TITLE
Combustion

### ISSUE THREAD

**Issue by Gantian2** [Valhalla-Gaming/Tracker#4560]
Casting combustion doesn't create a DoT as described in the spell description. However, it does reset the cooldown on Inferno Blast.

**Comment by nuhrii** [comment]
As of Legion Combustion has changed to apply a new effect, its supposed to give 100% critical strike chance and increase your mastery by you critical strike stat. However it says it gives to 100% critical strike chance, but I don't crit while its active 100% of the time, and for some reason its giving 100% extra Leech and Advoidance
