### ISSUE TITLE
DK weapons not detected

### ISSUE THREAD

**Issue by GikaaZ** [Valhalla-Gaming/Tracker#4565]
After the quest "Seeds of Chaos" in Icecrown, my 79 toon called Shio can't use any abilities which require to have melee weapons equiped. I tried to relog, respec, put the weapons on and off and even tried different weapons but nothing seems to work.
The quest mentioned before had me mounted on a skeltal gryphon which threw me off after some flight time; after my fall the whole issue happened and its been going for a week more or less now.

**Comment by Tregeta** [comment]
Is it possible for you to buy some gray vendor weapons and try to attack?

**Comment by GikaaZ** [comment]
As I said, I tried different weapons and none of them are workig. While attacking the character has the weapons equipped but makes the punching animation instead.

**Comment by Tregeta** [comment]
It's possible it still recognizes you in a vehicle somehow, we will need to look further into this. Thank you for bringing it to our attention.

**Comment by GikaaZ** [comment]
Can I expect getting my character fixed anytime soon, or shall I just start a new toon? Thank you for your assistance

**Comment by Tregeta** [comment]
We've been unable to reproduce the error, even cloning your character to our local did not produce this bug. Have you tried dying? Hearthstone? Clearing your Cache folder? Let us know, if it continues to persist after these, we'll see about a character swap//re-level

**Comment by GikaaZ** [comment]
I have tried suicide, I've cleared my cache folder and I've used my hearthstone, but nothing seems to work. 
![wowscrnshot_020916_165302](https://cloud.githubusercontent.com/assets/17123282/12921523/fdac6488-cf4d-11e5-8131-f012c79ab151.jpg)
![wowscrnshot_020916_165323](https://cloud.githubusercontent.com/assets/17123282/12921527/01406a4a-cf4e-11e5-94c1-ae6e71707bc8.jpg)
![wowscrnshot_020916_165330](https://cloud.githubusercontent.com/assets/17123282/12921529/02df92e0-cf4e-11e5-9a1d-bae3cbe98baa.jpg)


Of course I tried attacking in case it was just my skills graph bugging out but it didn't work either way.

**Comment by Warjakh** [comment]
When you're in-game next, let us know so we can fix this issue for you. 
Warjakh: https://valhalla-realms.com/forum/memberlist.php?mode=viewprofile&u=56056

**Comment by GikaaZ** [comment]
Fixed! Thanks for your support

**Comment by Tregeta** [comment]
Glad to have you resolved, and we thank you for the report.
