### ISSUE TITLE
[Azshara] Spitelash Nagas

### ISSUE THREAD

**Issue by PacoTheLegend** [Valhalla-Gaming/Tracker#4566]
The Spitelash Nagas in Azshara (which are level 11-16) are dropping more money than they're supposed to (2-3 silver each) and also dropping level 40-50 gear, which can sell for up to a couple gold in vendors, which is significant in low levels.

Screenshot:
![wowscrnshot_020816_141635](https://cloud.githubusercontent.com/assets/16710281/12887996/adab9b68-ce6f-11e5-91cf-e09bb8b19773.jpg)

**Comment by Tregeta** [comment]
fixed next update
