### ISSUE TITLE
Siegebreaker

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#4570]
For some reason [Siegebreaker](http://www.wowhead.com/spell=176289/siegebreaker) hits 3 times in 1 second **without multistrike**.

![siegebreaker](https://cloud.githubusercontent.com/assets/14946340/12892296/cacd457c-ce8b-11e5-9fec-9bf7d05e3481.png)

**Comment by Tobaccoz** [comment]
Also damage seems to be too high, you might check it aswell

**Comment by Tregeta** [comment]
We have confirmed the damage rating being to high.

**Comment by Egnivia** [comment]
[https://www.youtube.com/watch?v=on1uIXPhsyM](url)
Season 1 equip 104k with main hand.. So i guess damage is fine.. just triple hit is buggy.

**Comment by Collector-Valhalla** [comment]
It's not always happening. Not every warrior can hit me 3 times with one siegebreaker. So I'll add here unedited photos too from rated arena: http://imgur.com/a/dQ89e

![siegebreaker arena](https://cloud.githubusercontent.com/assets/14946340/13028154/cec02f44-d266-11e5-9a9b-09f4effa8a86.png)

**Comment by Egnivia** [comment]
It must be proc of multistrike.. because there is proc of touch of the grave.. and it is after spell or AA.

**Comment by EPS1L0N** [comment]
your screenshots show multistrikes

**Comment by Collector-Valhalla** [comment]
Same thing happens with few other spells I guess. With shamans stormstrike for sure.

**Comment by skorge1** [comment]
http://www.wowhead.com/spell=176289/siegebreaker is suppose to knock the target away and stun them but instead it just stuns and the target doesn't move.

**Comment by miloskovac** [comment]
Also, can u ppl check the critical ratio of the hits......warr hitted 8 crits in a row (that we can c on the photo).
Also multistrike should hit for 30% of the dmg, not 75% of the main spell dmg.

**Comment by Tregeta** [comment]
The 3rd hit is the multistrke.

**Comment by EPS1L0N** [comment]
a critical multistrike is 30% dmg * 2 (at the time of screenshot, now 1.5). = 60% of the damage

**Comment by Tregeta** [comment]
@skorge1
> http://www.wowhead.com/spell=176289/siegebreaker is suppose to knock the target away and stun them but instead it just stuns and the target doesn't move.

I've been informed that this issue is now knocking players 20 yards away. Are you able to confirm that?

**Comment by Collector-Valhalla** [comment]
It does knock you back. Pretty far.

**Comment by Tregeta** [comment]
Thanks at the confirmation Collector.

**Comment by Chimba** [comment]
well this talent shouldnt be used if playing in fury spec. it should be more like cc spell not oneshot spell. tooltip says that it should deal 450% weapon damage. so 2h cp weapons have ~2k dmg so fury has ~4k dmg. So 4.5 x 4 ~20k dmg. Those 100k+ values are just ridiculous...

**Comment by EPS1L0N** [comment]
All spells which do weapon pct damage are doing more than they are supposed to,

> so 2h cp weapons have ~2k dmg so fury has ~4k dmg.

also the damage these spells do isn't purely weapon damage. they scale with attack power of course.

**Comment by Bombrick** [comment]
Please fix this spell I think damage is way too high a warrior hit me 80k mainhand + 70k offhand OUTSIDE pvp with no multistrike I never thought of this being normal

**Comment by Egnivia** [comment]
The most dmg i did with siegebreaker is 120k after fixes warr..
Cp weps, avatar, enrage, gromblood potion and crit..

**Comment by EPS1L0N** [comment]
#2266
