### ISSUE TITLE
[NPC] & [Quest] Old Whitebark & Old Whitebark's Pendant / Whitebark's Memory

### ISSUE THREAD

**Issue by carminejackal** [Valhalla-Gaming/Tracker#4583]
The mob Old Whitebark (http://www.wowhead.com/npc=15409/old-whitebark) is missing. 

He drops http://www.wowhead.com/item=23228/old-whitebarks-pendant which starts the following quest: http://www.wowhead.com/quest=8474/old-whitebarks-pendant , upon completion of that quest the follow-up quest (http://www.wowhead.com/quest=10166/whitebarks-memory ) is given where you summon the spirit of Old Whitebark to fight.

**Comment by Tregeta** [comment]
fixed next update
