### ISSUE TITLE
Instakill

### ISSUE THREAD

**Issue by lillandril** [Valhalla-Gaming/Tracker#4585]
I get instakill when I go in the Undercity , it said that I died by falling damage , but I didn't fall , I just walk
![wowscrnshot_021016_132724](https://cloud.githubusercontent.com/assets/17160036/12947227/331ffcd6-cffa-11e5-9366-83ffa1e7e088.jpg)

**Comment by unfairplayer** [comment]
Seems to happen in other places too, such as around Orgrimmar.

**Comment by Th3hydra** [comment]
I'm having this happen to me at Fort Livingston in Northern Stranglethorn. I can't even res as it insta kills me over and over again.

**Comment by Th3hydra** [comment]
Update: Luckily Warjakh was on and was able to TP me to Ogrimar so I'm not auto dying now. Thank you to him and the other devs for being able to help. This bug is a scary one.

**Comment by Valhalla-Gaming** [comment]
Fixed
