### ISSUE TITLE
Ressurecting in battleground

### ISSUE THREAD

**Issue by Tobaccoz** [Valhalla-Gaming/Tracker#4590]
When you die in battleground such as AB and gilneas, you can't revive normally, it doesn't teleport you to spirit healer, instead you are spawned where you died and you have to wait 2 minutes after each time you die. I believe this was reported already but I 'demand' urgent fix, it's really gamebreaking.

**Comment by Bombrick** [comment]
Fixed already close Please

**Comment by Bombrick** [comment]
.
