### ISSUE TITLE
[Priest] [100 Talent] Clarity of Will

### ISSUE THREAD

**Issue by Warjakh** [Valhalla-Gaming/Tracker#4594]
Clarity of Will Shields the target with a protective ward for only 1 . 

http://www.wowhead.com/spell=152118/clarity-of-will

**Comment by Aprophys** [comment]
I dont get any healf from this talend for me its broken

**Comment by Tobaccoz** [comment]
Its not supposed to heal, its just a shield which should stack up to 3 times.

**Comment by Aprophys** [comment]
y u cant get a shield so the spell/talent is bugged
