### ISSUE TITLE
Priest Healing crits.

### ISSUE THREAD

**Issue by Vynrae** [Valhalla-Gaming/Tracker#4596]
Devine Aegis which procs on crits shields for a bit more than the amount it should

**Comment by Collector-Valhalla** [comment]
#4410 [Divine Aegis](http://www.wowhead.com/spell=47515/divine-aegis)
Correct me if I'm wrong but as a Discipline priest all your critical heals should be converted into absorption shield.

**Comment by Tregeta** [comment]
As it is referenced already, closing
