### ISSUE TITLE
Quest: The Warp Rifts

### ISSUE THREAD

**Issue by ALuttmann** [Valhalla-Gaming/Tracker#4597]
Using the quest item in the appropriate area doesn't spawn the quest mobs.

**Comment by Cidragon** [comment]
Actually the quest is working but kind of buggy. if you stand on the warps you will spawn 50% of the time the right mob, if you're not on the warp you will never get an appropriate creature

**Comment by Cidragon** [comment]
Fixed in December 25th changelog.
