### ISSUE TITLE
Troll starting quest not working!

### ISSUE THREAD

**Issue by Taburasmano** [Valhalla-Gaming/Tracker#4598]
The quest "Proving Pit" doesnt work properly. If i speak to the Darkspear Jailor but I cant say him that he should let the naga out!

**Comment by Tregeta** [comment]
The troll area has not been scripted yet

**Comment by Taburasmano** [comment]
Ok. Do you know which areas are scripted?

**Comment by Tregeta** [comment]
Yes, Human, Orc, Tauren, Gnome, Dwarf, Bloof Elf (Mostly full all the way to 20), and Undead at the moment.

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/4263

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/981
