### ISSUE TITLE
Deep Wounds

### ISSUE THREAD

**Issue by miloskovac** [Valhalla-Gaming/Tracker#4604]
Hello ppl.
The ability Deep wounds is doing too much dmg. Should b 420% of ap in 15 sec, 84% per 3 sec, ad not 420% of ap per tic.

**Comment by miloskovac** [comment]
I ment 84% of ap per 3 sec

**Comment by Myrmidonx** [comment]
www.wowhead.com/spell=115768/deep-wounds#modified-by

dude, i checked all of your posts and they all are b..........nonsense

we are at WoD expansion, not in Pandaria/whatever xpac.

**Comment by miloskovac** [comment]
Hehe, learn to read plz. U posted what i stated, if u dont know math, thats u problem.
Thanks

**Comment by Moustachos** [comment]
AP coefficient is already 84% per tick, so there's no bug with this spell.

**Comment by Moustachos** [comment]
Ref #2266
