### ISSUE TITLE
Monk Xuen 4000 dmg / 0.2 sec INFINITE CRACKLING LIGHT

### ISSUE THREAD

**Issue by blablablablblabllabl** [Valhalla-Gaming/Tracker#4606]
So , i was in a bg and the monk guy's xuen hit me with his spell without cooldown and killed me when i was full hp , it seems like a serious bug 
![aaa](https://cloud.githubusercontent.com/assets/17201425/13012332/d64cdec8-d1e5-11e5-8c8d-e396a90fdb2d.png)

**Comment by Moustachos** [comment]
That's not a bug, Xuen is supposed to hit 3 enemies within 10 yards every second with Crackling Tiger Lightning.

See http://www.wowhead.com/spell=123904/invoke-xuen-the-white-tiger
