### ISSUE TITLE
Quest:  [Standards and Practices]

### ISSUE THREAD

**Issue by Strale2** [Valhalla-Gaming/Tracker#4614]
Link:    http://www.wowhead.com/quest=9910/standards-and-practices
Issue:  Using Mag'har Battle Standard while standing near / on top of  First Burning Blade Pyre, Second Burning Blade Pyre, and Third Burning Blade Pyre results in error text as if I was not near any of those pyres.

**Comment by Cidragon** [comment]
Fixed in December 5th changelog.
