### ISSUE TITLE
Paladin Seals Problem

### ISSUE THREAD

**Issue by Cristobal214** [Valhalla-Gaming/Tracker#4616]
I hope you guys can solve this problem faster. Paladins actually have a problem with the Seals, in specific with "Seal of Righteousness", we have two of this seals and is Bug, because it supposed to be only one and as I sayed before, we have two seals of "Seal of Righteousness" (We have the same seal, and should be only one seal). Can you fix it please.
[https://www.google.com.co/search?q=paladin+wod&biw=1366&bih=653&site=webhp&source=lnms&tbm=isch&sa=X&sqi=2&ved=0ahUKEwiTkpCJo_PKAhWIlR4KHbfhD24Q_AUIBygC#tbm=isch&q=paladin+wod+retribution+Seals&imgrc=peGao3gBDSRLZM%3A](url)

There it is how supposed the seals must be (Retribution).

Thank You.

**Comment by Tregeta** [comment]
Seals Ref #1619, #2592
