### ISSUE TITLE
[Quest] Whitebark's Memory

### ISSUE THREAD

**Issue by Pure-Valhalla** [Valhalla-Gaming/Tracker#4620]
Quest: http://www.wowhead.com/quest=10166/whitebarks-memory

Item: http://www.wowhead.com/item=28209/old-whitebarks-pendant

Doesn't recognize the runestone, when attempting to "bury" the pendant at it.

![whitebark](https://cloud.githubusercontent.com/assets/14964856/13025420/90fcfdb2-d1cc-11e5-85fe-bcb10d2d5756.jpg)

**Comment by Tregeta** [comment]
fixed next update
