### ISSUE TITLE
[Quests] Blood Elf starter area class specific training dummy quests

### ISSUE THREAD

**Issue by Pure-Valhalla** [Valhalla-Gaming/Tracker#4621]
The following quests are class specific and cannot be completed due to the training dummies in Sunstrider Isle not recognizing the spell being cast on them.

Charge! (Warrior) - http://www.wowhead.com/quest=27091/charge
Corruption (Warlock) - http://www.wowhead.com/quest=10073/corruption
Evisceration (Rogue) - http://www.wowhead.com/quest=10071/evisceration
Frost Nova (Mage) - http://www.wowhead.com/quest=10068/frost-nova
Learning the Word (Priest) - http://www.wowhead.com/quest=10072/learning-the-word
Steady Shot (Hunter) - http://www.wowhead.com/quest=10070/steady-shot
Tiger Palm (Monk) - http://www.wowhead.com/quest=31171/tiger-palm
Ways of the Light (Paladin) - http://www.wowhead.com/quest=10069/ways-of-the-light

**Comment by Tregeta** [comment]
fixed all next update.
