### ISSUE TITLE
Mage Talent: Ice Barrier

### ISSUE THREAD

**Issue by nuhrii** [Valhalla-Gaming/Tracker#4626]
Sometimes it would absorb more damage than what the tooltip says, not sure exactly why that is, my only guess is maybe multistrike.

**Comment by Tregeta** [comment]
Ice Barrier Scales with spell power, if you have spell power procs it increases it.

**Comment by nuhrii** [comment]
True, but i dont have a way to increase my spell power arbitrarily and it would sometimes increase to a 2 different set amounts, the first one being almost an increase of about 30% and the second one almost double the amount shield.

**Comment by Tregeta** [comment]
Trinkets, mage buffs, food, etc is possible, however with that much of an increase it seems off by a bit.

**Comment by Vynrae** [comment]
I can testify that lately it's been giving me random absorption amounts with a fixed amount of spell power = 5884 (after it got fixed from absorbing 0 dmg lately) http://postimg.org/gallery/e7dcsir8/

**Comment by GAMMARAYS** [comment]
Will be fixed next update.

**Comment by Tregeta** [comment]
#2266
