### ISSUE TITLE
Quest -  [A Necessary Distraction]

### ISSUE THREAD

**Issue by Strale2** [Valhalla-Gaming/Tracker#4634]
Quest: [[A Necessary Distraction]](http://www.wowhead.com/quest=10637/a-necessary-distraction)
+
Quest: [[A Necessary Distraction]](http://www.wowhead.com/quest=10688/a-necessary-distraction)
Zone: Shadowmoon Valley - Outland
Bug: Using scroll on [Azaloth ](http://www.wowhead.com/npc=21506/azaloth) does not free him and does not get quest completed.

**Comment by Pure-Valhalla** [comment]
#2927

Please do a search for existing issues and make a comment on them if you have other information to add. Thank you.
