### ISSUE TITLE
[Quest] [Hellfire Peninsula] Burn It Up... For the Horde!

### ISSUE THREAD

**Issue by Aevenger** [Valhalla-Gaming/Tracker#4639]
Even when very close to the cannon it tells you "Requires Alliance Cannon" and nothing happens.

http://www.wowhead.com/quest=10087/burn-it-up-for-the-horde

**Comment by Aevenger** [comment]
![Alt text](http://i68.tinypic.com/34q49i0.png "Cannon")

**Comment by Pure-Valhalla** [comment]
#4104
