### ISSUE TITLE
Tol barad no quest anymore

### ISSUE THREAD

**Issue by serenity-talador** [Valhalla-Gaming/Tracker#4641]
Since the last maj i was able to complete the quest only one time :'( it's been more than 24 h between the last time i complete and now

**Comment by Tregeta** [comment]
Sounds like a daily quest, it's possible something may have happened recently to bug this particular area out.

**Comment by serenity-talador** [comment]
Work now dont know why but work :)

**Comment by serenity-talador** [comment]
Work but the pnj offer you different quest when you just talk , quit and talk , you're able to redo the quest the same day

**Comment by serenity-talador** [comment]
solved
