### ISSUE TITLE
Spell Alerts And Hunter Ability:  [Thrill of the Hunt]

### ISSUE THREAD

**Issue by Strale2** [Valhalla-Gaming/Tracker#4642]
I have seen that this was reported earlier last year. [Here](https://github.com/Valhalla-Gaming/Tracker/issues/3270)
So apart that it works like there is 6% chance per focus spent (instead per 10 focus spent)  and it doesn't proc on [Black Arrow](http://www.wowhead.com/spell=3674/black-arrow) ability,
This ability is not triggering spell alert which I have enabled. Spell alerts are working properly for debuffs like stun, silence or disorientation but they never show up to let me know my ability is ready.

**Comment by Pure-Valhalla** [comment]
#3720

**Comment by Tregeta** [comment]
Moved comment to original post, closing duplicate.
