### ISSUE TITLE
Quest - [Unleashed Steel]

### ISSUE THREAD

**Issue by Strale2** [Valhalla-Gaming/Tracker#4649]
Quest: [Unleashed Steel](http://www.wowhead.com/quest=35102/unleashed-steel)
Zone: Talador
Bug:  [Morketh Bladehowl](http://www.wowhead.com/npc=79356/morketh-bladehowl) doesn't get freed, doesn't move to arsenal and quest is not completed.

**Comment by Pure-Valhalla** [comment]
#2780
