### ISSUE TITLE
[Monk][Talent] Chi explosion

### ISSUE THREAD

**Issue by Bombrick** [Valhalla-Gaming/Tracker#4657]
It works and does damage but doesn't have animation or sound

**Comment by Moustachos** [comment]
Works as intended.

**Comment by Moustachos** [comment]
Ref #2266

**Comment by Bombrick** [comment]
It doesn't work as intended in retail It does animation here it doesn't ...

**Comment by Moustachos** [comment]
Which talent specialization?

**Comment by Bombrick** [comment]
I tried with windwalker and mistweaver doesn't work
