### ISSUE TITLE
Spell: Spinning Crane Kick Monk

### ISSUE THREAD

**Issue by KeyBlack** [Valhalla-Gaming/Tracker#4658]
This ability doesn't do the real damage :(, the damage is very very low, Please fix it :(

**Comment by Tregeta** [comment]
What type of damage, please give us some numbers to work with as to what you are experiencing.

**Comment by KeyBlack** [comment]
For example, a mob lvl 85 i only do 2.000 aprox, of damage that is very strange, because i am lvl 100 and i have a very good equipment, this skill its impossible do that very low damage.
Before the ability do a very good damage but its nerf now :(, but 2.000 of damage? Its very low.

**Comment by Tregeta** [comment]
At level 85, is this mob in Pandaria?

**Comment by KeyBlack** [comment]
No, its in general, almost all mobs for example lvl 85, with the ability I only do 2k of damage, and this is very low :(

**Comment by Tregeta** [comment]
What spec are you? This will allow us to look into to make sure the damage is off.

**Comment by KeyBlack** [comment]
I am Brewmaster and WindWalker, but in the 2 specs, are the same damage

**Comment by Tregeta** [comment]
Thanks

**Comment by Tregeta** [comment]
Here is some exact damage from retail with BiS gear 


![spinning crane kick](https://cloud.githubusercontent.com/assets/12553233/13053607/fb183cde-d3ca-11e5-82b1-bebee8c880a9.png)

Would like to note that your damage is a bit more than this, unsure why this is the case, perhaps buffs, we'll look into it more thoroughly.

**Comment by KeyBlack** [comment]
Sorry but i can't upload a screenshot but in the chat says:

"1 hit 1017"
"2 hit 1050"
"3 hit 1300"
"4 hit 1097"

I hit the "Raider's Training Dummy" in ashran :)

**Comment by Moustachos** [comment]
Damage are fine, the "nerf" was just a balancing to match retail damage.

**Comment by Moustachos** [comment]
Ref #2266
