### ISSUE TITLE
Spell: Nimble Brew Monk

### ISSUE THREAD

**Issue by KeyBlack** [Valhalla-Gaming/Tracker#4659]
This ability, doesn't do what it says because, says : "Removes all root, stun, fear and horror effects and reduces the duration of future such effects by 60% for 6 sec."

But in the game you can only use this if you have been terrified or you have fear, but it says when you have been aturded or rooted.

Please fix it :(

**Comment by Femala** [comment]
This bug was reported 5 days ago. Please check tracker first. And do not make double topic.
