### ISSUE TITLE
Zone: Ghostlands Quest:Investigate An'daroth

### ISSUE THREAD

**Issue by Max-Valhalla** [Valhalla-Gaming/Tracker#466]
The quest involves killing 12 night elf spies and exploring the center of the zone, however when you approach the monument the quest resets and you have to start from scratch, at which point it resets again when you approach the monument.

**Comment by Malae1** [comment]
As above.

**Comment by Pure-Valhalla** [comment]
#1887
#2001

**Comment by Pure-Valhalla** [comment]
Quest now works
