### ISSUE TITLE
Glyph: Glyph of Trascendence Monk

### ISSUE THREAD

**Issue by KeyBlack** [Valhalla-Gaming/Tracker#4660]
This glyph doesn't do anything :( It says: "Reduces the cooldown of your Transcendence: Transfer spell by 5 sec."

But in the game this glyph doesn't do anything

Please fix it :(

**Comment by Moustachos** [comment]
Works as intended.

**Comment by Moustachos** [comment]
Ref #2266

**Comment by KeyBlack** [comment]
The glyph says something and don't do this :(
Pleade fix it

**Comment by Moustachos** [comment]
Check Transcendence: Transfer's tooltip before / after using Glyph of Transcendence, it is working.
