### ISSUE TITLE
Twist of Fate procs everytime a spell is used

### ISSUE THREAD

**Issue by Vynrae** [Valhalla-Gaming/Tracker#4665]
http://www.wowhead.com/spell=109142/twist-of-fate should proc only when you heal/dmg a target below 35% health, but it procs everytime no matter how much the health is http://postimg.org/gallery/2mzyyxcvo/

**Comment by Tregeta** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/3983
