### ISSUE TITLE
[General Spells] [Shield / Absorb spells] Block

### ISSUE THREAD

**Issue by Bombrick** [Valhalla-Gaming/Tracker#4668]
Any shield that absorbs blocks damage randomly and this is not supposed to happen for example BM Monk shield / Disc Priest shields / Mage Shield / Warrior shield and others... 

NOTE: It can block spells stuns saps and anything 
High Priority

**Comment by Myrmidonx** [comment]
i dont know if you re talking about the block skill or the absorb mitigation mechanic, but

wow.gamepedia.com/Absorb

absorb: can resist the Interrumpt/any pushback.

**Comment by Bombrick** [comment]
Myrmidonx not the block skill . Any shield blocks damage for no reason and this isn't happening in retail and it blocks anything normal dps spells any things

**Comment by Bombrick** [comment]
_It may be a visual bug._

**Comment by Bombrick** [comment]
Fixed
