### ISSUE TITLE
[Monk][Spell][Mistweaver] Life Cocoon

### ISSUE THREAD

**Issue by Bombrick** [Valhalla-Gaming/Tracker#4669]
It says in spell description absorbs 158k while it only absorbs 20-30k 
[<blockquote class="imgur-embed-pub" lang="en" data-id="pmcnIx4"><a href="//imgur.com/pmcnIx4">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>](url)

**Comment by Femala** [comment]
Did you check it in combat? I mean in duel? Cos i see cocoon is still active. In right corner of your screen. I play pure mist monk. And i didnt notice it. But mabye your right. I have to check it too. :)

**Comment by Bombrick** [comment]
Yes It works but gives low absorb instead of the normal

**Comment by Moustachos** [comment]
Ref #2266
