### ISSUE TITLE
[Monk][Talent][Mistweaver] Chi explosion 

### ISSUE THREAD

**Issue by Bombrick** [Valhalla-Gaming/Tracker#4670]
Chi explosion doesn't summon 8 healing spheres in an 8 yards radius ring around the target when you cast it in mistweaver monk with 4 chi in Stance of the wise Serpent
note: Healing spheres gets summoned in the stance of the Spirited crane and not in the wise serpent

**Comment by Bombrick** [comment]
It doesn't work sometimes but It works sorry

**Comment by Femala** [comment]
It works for me o . o

**Comment by Femala** [comment]
Ye you eddided it. Sorry :D
