### ISSUE TITLE
rip pepe

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#4680]
Idk how it is on horde side but on alliance there's Pepe on tree next to the tent with command table and he/she/it worked fine before one of the recent updates. He/she/it is still there, you can click it to get buff but **you can't see this gorgous little birdy on your head**.

Needs critical priority if you ask me.

**Comment by Aveta** [comment]
Same for Horde Pepe. And I just found him in Frostwall. : c
(he was hovering below the tree he's supposed to be on)

**Comment by Bombrick** [comment]
pepe is love pepe is life

**Comment by Collector-Valhalla** [comment]
PEPE WORKS NOW!
![wowscrnshot_030816_191106](https://cloud.githubusercontent.com/assets/14946340/13611205/940fc950-e561-11e5-94ea-7661ecd2f081.jpg)
