### ISSUE TITLE
[Monk][Spell][Mistweaver] Mana Tea

### ISSUE THREAD

**Issue by Bombrick** [Valhalla-Gaming/Tracker#4695]
Mana tea  gives 4 mana which means It's useless and It's needed when mana is low fix pls

**Comment by Moustachos** [comment]
Mana Tea is supposed to restore mana equal to 3 times your unbuffed Spirit.

Previously it was only restoring 1 time your unbuffed Spirit, will be fixed on next update.

**Comment by Moustachos** [comment]
Ref #2266
