### ISSUE TITLE
Warrior WoD PvP Fury 2P Bonus

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#4701]
http://www.wowhead.com/spell=165639/item-warrior-wod-pvp-fury-2p-bonus
http://www.wowhead.com/spell=165640/vicious-strike

Procs from every attack. [Bloodthirst](http://www.wowhead.com/spell=23881/bloodthirst) always have 50% more chance for critical hit. 

And I'll just add that [Bloodthirst](http://www.wowhead.com/spell=23881/bloodthirst) itself have critical strike increased by 40% so fury warriors always have enrage effect on.

**Comment by Moustachos** [comment]
Fixed in a previous update.
