### ISSUE TITLE
Tanks in pvp (and resolve)

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#4702]
http://us.battle.net/wow/en/forum/topic/18704977802
http://blues.wowraider.net/blue/us2/13271747932/Tank-Specs-in-PvP?1404947985

#4318 Resolve is still broken so I guess it's just for future - it shouldn't work in pvp combat.

And also tank specializations should take 25% additional damage in pvp combat.

**Comment by nmjayan** [comment]
I'm not sure if either of these is true, though, at first blush, resolve might not work in PvP, and the 25% is highly unlikely.

That said, I found many contradictory posts on this, and nothing substantiated by Blizzard. Needs an in-depth investigation.

**Comment by Collector-Valhalla** [comment]
http://us.battle.net/wow/en/blog/15682579/#gamesys_intro

I have found here line (**Tank Vengeance, Resolve, and PvP**) that says - "Tanks now take 25% additional damage while engaged in PvP combat."

**Comment by nmjayan** [comment]
Ohh, nice catch. Though I hate this idea, really. I mean, tanks just don't have the damage in PvP. This just makes things worse. Tanks can now be safely ignored. Bad move on Blizzard's part. But if that's the way it is, that's the way it is...

**Comment by Nienz** [comment]
prot warrs got a small dps boost on 6.2.3 but thats a later state, they are still viable

**Comment by GAMMARAYS** [comment]
Has been fixed feb 22
