### ISSUE TITLE
Old content not working

### ISSUE THREAD

**Issue by vasilaki** [Valhalla-Gaming/Tracker#4705]
I really wanted to try the old raids and dungeons and kill some of the popular bosses so i went to caverns of time and tryed every of the portals. Some didn't even let me in and in others there are bugs that make them impossible to play

**Comment by Collector-Valhalla** [comment]
I think you need to be more specific. Describe every single issue, add some links and stuff like that.

**Comment by serenity-talador** [comment]
and check #2468 in case it's already  reported
