### ISSUE TITLE
Daily Quests

### ISSUE THREAD

**Issue by lavalash551** [Valhalla-Gaming/Tracker#4712]
What is wrong: Daylie quests cant be done once every day anymore.
How should it work: Daylies should reset every day!

**Comment by serenity-talador** [comment]
where what quest ? give more info

**Comment by lavalash551** [comment]
All daylie quests can't be done anymore. Daylie cooking quests in main cities, dalaran, pandaria. dungeon daylies in shattrath, faction daylies for ebon knights in ice crown or wildhammer clan quests in twilight highlands.... or tol'barad... this affects ALL daylies.

**Comment by Tregeta** [comment]
Fixed
