### ISSUE TITLE
Tol'Barad dailies for horde

### ISSUE THREAD

**Issue by Pure-Valhalla** [Valhalla-Gaming/Tracker#4714]
Horde player is stating that the Tol'Barad dailies are not resetting and it has been two day since they last did them. 

Will test later tonight.

**Comment by nmjayan** [comment]
No dailies are resetting at the moment. Ref [#4712](https://github.com/Valhalla-Gaming/Tracker/issues/4712) and [#4678](https://github.com/Valhalla-Gaming/Tracker/issues/4678).

**Comment by serenity-talador** [comment]
They have reset at least one time

**Comment by serenity-talador** [comment]
But no more

**Comment by Tregeta** [comment]
@serenity-talador 
This issue is resolved now on Valhalla, your realm must wait for it's update.
