### ISSUE TITLE
DK Ghoul Problems

### ISSUE THREAD

**Issue by miloskovac** [Valhalla-Gaming/Tracker#4718]
Hello ppl.
Firstly i would like to thank you for trying to fix DK class.
There are some problems with Ghoul tho.
I noticed following:
1st HP of the ghould is very low (like 40k which means 1 hit dead). On Pet statistic he dosnt have stamina at all (so perhaps thats the reason for low HP, similar to hunters pets).
2nd Leap doesnt change to charge after Dark transformation.
3rd Pet disapears after using Summon Gargoyle spell (Gargoyle is still bugged, cosing 0 dmg on hit and have even less HP then Ghoul (20k ca).
Ill try to update this post if i notice more bugs.

**Comment by Bombrick** [comment]
Yes ghoul health is very low needs fix high priority

**Comment by Moustachos** [comment]
Ref #2266
