### ISSUE TITLE
DK Dark Simulacrum

### ISSUE THREAD

**Issue by miloskovac** [Valhalla-Gaming/Tracker#4720]
Hello ppl.
The spell got finaly fixed....but not as if should b. On healing spell it does replicate the same spell, but heal is 1Hp or sometimes 2Hp.
On Dmg spells, it hit aproximatly 15% of the original dmg spell did on dk. If hitted with 15k spell, u can cast the same spell with max dmg ca 2k.

**Comment by Moustachos** [comment]
Yes, we're aware of that issue. Currently copied spells damage / healing don't scale properly and we'll fix it asap.
