### ISSUE TITLE
DK Necrotic Plague

### ISSUE THREAD

**Issue by miloskovac** [Valhalla-Gaming/Tracker#4721]
Hello ppl.
There is a problem with Necrotic Plagues dmg on frost spec. It doesnt scale dmg properly with the mastery (like unholy do, doing 4 times more dmg as on frost spec).
It should do Shadowfrost dmg (shadow or frost depending on which would do more dmg).
Please review this talent.

**Comment by Moustachos** [comment]
Necrotic Plague is properly affected by both masteries, it's just that its base damage are higher in Unholy spec (check talent's tooltip) :)
