### ISSUE TITLE
Mage Spell: Deep Freeze

### ISSUE THREAD

**Issue by Vynrae** [Valhalla-Gaming/Tracker#4728]
Deep Freeze http://www.wowhead.com/spell=44572/deep-freeze is canceled when the target takes any damage from any source (mage, water pet, other players+pets), when only ice lance http://www.wowhead.com/spell=30455/ice-lance or ice nova http://www.wowhead.com/spell=157997/ice-nova should cancel it.

**Comment by mrcookieman** [comment]
This needs fix so bad, mage is so useless in 1v1 without it...
