### ISSUE TITLE
DK Chilblains Not Giving Chill Effect

### ISSUE THREAD

**Issue by miloskovac** [Valhalla-Gaming/Tracker#4731]
Hello ppl.
I have tested it, and Chilblain SHOULD apply with Necrotic Plague Talent.
Please fix this issue cose it pretty much essencial for dks to b able to get to the target.
Thank you.

**Comment by Moustachos** [comment]
Already reported (by you...) and it will be fixed on next update: #4719

**Comment by Moustachos** [comment]
Ref #2266
