### ISSUE TITLE
paladin talents lvl 90 bug

### ISSUE THREAD

**Issue by ReiiAndres** [Valhalla-Gaming/Tracker#4736]

**Comment by serenity-talador** [comment]
be more precise

**Comment by ReiiAndres** [comment]
ninguno de los 3 talentos cumple su funcion (no hacen nada como si no estubieran seleccionados)

**Comment by Tregeta** [comment]
Execution Sentence #1470, #1748
Holy Prism #1468, #1748
Light's Hammer #1469, #1748, #3754
