### ISSUE TITLE
Druid Spell: Moonfire

### ISSUE THREAD

**Issue by skorge1** [Valhalla-Gaming/Tracker#4753]
The issue with http://www.wowhead.com/spell=8921/moonfire and http://www.wowhead.com/spell=93402/sunfire is that the damage over time is not applied to the target for the same duration as it is on retail. On Valhalla the damage over time duration is 40 seconds (Moonfire)  when it is suppose to be 20 seconds. If you apply Moonfire again it can reach 50 seconds also When you apply Sunfire the first time it is at 24 seconds but when you apply it again it become 30 seconds.

**Comment by Moustachos** [comment]
This isn't a bug, the duration increase is the benefit of balance's passive http://www.wowhead.com/spell=33605/astral-showers :)

**Comment by Moustachos** [comment]
Ref #2266
