### ISSUE TITLE
[NPC] Ashran PvP vendors hp difference issue

### ISSUE THREAD

**Issue by carminejackal** [Valhalla-Gaming/Tracker#4757]
As can be seen below there is a rather large difference in the amount of health these npcs are supposed to normally have. The proper amount according to wowhead for both npcs is:

Amelia Clarke <Wild Conquest Quartermaster>  - Health: 97,854
http://www.wowhead.com/npc=93907/amelia-clarke

Cladd Dawnstrider <Wild Conquest Quartermaster> - Health: 733,905
http://www.wowhead.com/npc=93909/cladd-dawnstrider

![](http://i.imgur.com/YVUW4tS.jpg)
![](http://i.imgur.com/6bDjB7t.jpg)

**Comment by Tregeta** [comment]
fixed next update
