### ISSUE TITLE
passive buffs

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#4759]
Passive buffs (like [Unholy Aura](http://www.wowhead.com/spell=55610/unholy-aura)) disappear when someone else use some other buff with same effect - so that works as it should - but when you cancel someones buff your passive won't come back. Only way to "fix" it is relogging.

EDIT: And I don't know if this is same on retail but for example [Swiftblades Cunning](http://www.wowhead.com/spell=113742/swiftblades-cunning) removes versatility buff from unholy aura.

**Comment by miloskovac** [comment]
True. I already post this early on but my post was deleted/closed.
Passive bonuses dont 'stay' on chars even tho they r passive bonuses. Like Trueshot aura from huters is gone if a dk buffs it (but after the 1h duration of the horn, there is no more passive 10% bonus to the hunter, its gone).
Please do smth about it, cose reloging after every bg or arena is a bit pain in the ....

**Comment by Trekex** [comment]
I'll add that, for example, Lone Wolf buff disappears each time I enter an arena, so I have to call my pet and dismiss it to get buff back.

**Comment by Collector-Valhalla** [comment]
VERY annoying. Have to relog after every BG to get it back. Dying, changing zone, reloading, right clicking buff that removed my passive (for example druids buff - stats + versa) does not help.

And that additional haste is very important for killing machine mechanic.

**Comment by Traveler-Valhalla** [comment]
It's all changed in Legion so there's no issue.
