### ISSUE TITLE
Spell: Flying Serpent Kick Monk

### ISSUE THREAD

**Issue by KeyBlack** [Valhalla-Gaming/Tracker#4766]
In the description says: "Soar forward through the air at high speed for 2 sec.

If used again while active, you will land, dealing (53.658% of Attack power) damage to all enemies within 8 yards, and slowing them by 70% for 4 sec."

But you can't use again for land when you want, you only use 1 time and land when the spell end.

Please fix it :(

**Comment by Moustachos** [comment]
You can use it again, make sure you're not using a glyph altering the default behavior of this spell.

The only known bug of this spell is: #4696
