### ISSUE TITLE
Spell: Afterlife Monk WindWalker

### ISSUE THREAD

**Issue by KeyBlack** [Valhalla-Gaming/Tracker#4767]
In the description says: "When you kill an enemy while gaining experience or honor, you  summon a Healing Sphere, healing you for 0 when you walk through it.

Enemies who die from Blackout Kick have a 50% chance to summon a Chi Sphere, granting 1 Chi when you walk through it."

But it doesn't do anything.

**Comment by Aveta** [comment]
It does though? I get Healing Spheres on every enemy that grants experience (aka level not greyed out) and I get Chi Spheres from time to time when the target dies from Blackout Kick. Played my two monks enough to be sure.

**Comment by KeyBlack** [comment]
I get heal spheres but in Brewmaster, not in WindWalker, and this is other spell

**Comment by Aveta** [comment]
Brewmaster gets spheres from other passive, Gift of the Ox, which has a chance to spawn a sphere on autoattack multistrikes.
As for Afterlife:
![wowscrnshot_022416_183711](https://cloud.githubusercontent.com/assets/14302942/13294848/3b366220-db26-11e5-9c58-84253e7146d5.jpg)
It spawns only AFTER death of a mob.

**Comment by KeyBlack** [comment]
Ok thanks, but for example in pvp it doesn't spawn, that is the problem :(

**Comment by Aveta** [comment]
Ah. I don't PvP, so I couldn't notice.

**Comment by Moustachos** [comment]
Afterlife works as intended.

**Comment by KeyBlack** [comment]
Sorry, but in pvp doesn't function.

**Comment by Moustachos** [comment]
I tested it in PvP just yesterday, so it does work.

**Comment by Aveta** [comment]
I guess it's only on killing blows then.
