### ISSUE TITLE
Spell: Tigereye Brew  Monk WindWalker

### ISSUE THREAD

**Issue by KeyBlack** [Valhalla-Gaming/Tracker#4768]
In the description says: "For each 4 Chi you consume through use of abilities and attacks,"

But in the game for each 6 chi you generate 1 charge of this brew, and it says for each 4.

Please fix it :(

**Comment by Moustachos** [comment]
It is working as intended (1 charge per 4 chi consumed, with a potential additional charge with Bottled Fury mastery).

**Comment by KeyBlack** [comment]
Not working good, because i test it, for example with 3 chi =

**Comment by KeyBlack** [comment]
Sorry, for example 3 chi = Fist of fury, and 1 = Tiger palm in total do 4 chi and i haven't any charge of the brew, the brew only function with blackout kick, only acumulate charges if you use blackout kick 2 times but with other abilyties, doesn't function.

**Comment by Moustachos** [comment]
Turns out you were right about Fists of Fury: it wasn't accounted in Tigereye Brew stacks generation.

It will be fixed on next update :)
