### ISSUE TITLE
Feral druid savage roar

### ISSUE THREAD

**Issue by Leondezwart** [Valhalla-Gaming/Tracker#4769]
Ok so a few minutes ago there was  a small update for some fixes wich is great  but with savage roar its weird now.  when u use it it last 11 seconds while the  1 point energy is 18 seconds and even when u spend 5 points its still 11 seconds.

http://www.wowhead.com/spell=52610/savage-roar

**Comment by miloskovac** [comment]
True, Savage Roar spell (without the glyph) has bin buged, giving 11 sec duration on any amount of points,
Please make this top priority.

**Comment by EPS1L0N** [comment]
#2266
