### ISSUE TITLE
DK Frost Strike

### ISSUE THREAD

**Issue by miloskovac** [Valhalla-Gaming/Tracker#4771]
Hello ppl. 
Frost Strike Spell seems bugged. It coses was less dmg then it should for the gear im in.
Fully buffed with all my cds (I am DW DK), (and razorice 10% more frost dmg from DKs abilities, and 10% more frost dmg from a DKs 4th set bonus) does only 40k to a dummy, and even less vs players.
Never played on retail, but on youtube ppl r doing from 70-110k with Frost Strike.
That is way below the normal dmg DK (725 ilvl) should do.
Please review the spell formula cose that doesnt seems right, or the bonuses doesnt stack as they should b.

**Comment by Aveta** [comment]
What's your mastery %? It also influences the damage of Frost strike and by quite a huge margin (it's the most important stat for DW frost DK). Tho I'm not 100% positive if it works. Same for otherbonuses.

**Comment by Moustachos** [comment]
Have you checked your Frost Strike's tooltip? Because my Frost Strike's damage matches the tooltip on training dummies.

Another thing: I don't know if you're dual wielding or using a 2H weapon, but if you're dual wielding, there's 2 numbers you need to account for when you hit: main weapon damage and off hand damage (with Might of the Frozen Wastes passive).

**Comment by Tregeta** [comment]
> Fully buffed with all my cds (I am DW DK)

DW = Dual Wield

**Comment by Moustachos** [comment]
My bad, missed that part. So yeah please compare your damage on L85 training dummies (the other ones aren't reliable, due to armor or legacy buff) with the tooltip (accounting for off-hand damage).

For me there's no miscalculation.

Also be careful, checking damage from retail video where the DK probably has a completely different stuff and such isn't a reliable comparison source for us.

**Comment by miloskovac** [comment]
Ok, ill check it out on the L85 dummies and let u know.
I know its not reliable, thats why im not saying its a bug, just asking for a review.
Anyhow thx for the quick respond. Ill report asap.
Cheers

**Comment by miloskovac** [comment]
Ok, i tested it on L85 dummies in Orgrimmar.
Results were disapointing. I can sed u the Screen Shots if u want.

**Comment by miloskovac** [comment]
My mastery is 34% pve (outside the bg/arena).

**Comment by Aveta** [comment]
I guess it would be nice to post them or just the numbers for comparison. Did testing on my own DK on a lvl 85 training dummy in Org.
She's ilvl 622, has mastery of 25.95%, versa of 6,29%. Her trinkets are Greka's Dentures and Novice Rylak Hunter's Horn and she's an orc which gives her Blood Fury buff. Her strength without any procs etc is 3247.
My maximum crit with all procs and buffs, Razorice fully stacked was 31810. Average crit was 22524.

**Comment by miloskovac** [comment]
Yeah, smth is wrong with the Frost strike dmg...it should b 20-30% more.
Btw i have 14% versa in pve also so together with razorice (10% more frost dmg) and Biting frost (10% more dmg from frost dmg) and 33% mastery still getting 45k (30k main and 15k offhand) with full proc looks low to me and compared to the retail Frost DKs its around 20-30% lower.
Anyhow i can send u the SS on a mail, or i can send the SS to Puure's mail and u can get it hrom him/her.
Cheers

**Comment by Collector-Valhalla** [comment]
You guys want Frost Strike to crit like hunter's Chimaera Shot? :P 
There's a difference between ability that can be "spammed" and the one that can be used every 6 seconds.
Retail is on season 3. We are on season 2.

**Comment by miloskovac** [comment]
Well, ur crits make more then any other class (exept for the fury warrs now) so ur pretty cool with the thins as they r. Thats true on the season tho. But, review of the spell formula and making it fixed spell with fixed dmg doesnt hurt any1.... Anyhow u want pvp and all classes to b fixed dont u?

**Comment by Collector-Valhalla** [comment]
I play as frost dk now and everything seems ok to me. I really enjoy it :P

**Comment by miloskovac** [comment]
Not everything is as it looks....jk...review of the spell formula...is that a bad thing?

**Comment by EPS1L0N** [comment]
I spent a few hours gathering data on frost strike, my findings don't indicate anything wrong with the spell.

I did however notice that min/max weapon damage wasn't quite matching blizz (it was close though), so I fixed that before i began testing values.

Here are my findings:
```
Tested with ilvl 740 full Wild Glad s2 excluding strength equip bonus trinket, on Raider's Training dummy. Characters are identical.
Frost Strike ignores armor so the possibility of damage being different because of our armor values for creatures being slightly off isn't possible.

100x Frost Strike's on Blizz:
- Frost Strike (Critical Hits) Max - 25,065, Min - 20,780
- Frost Strike (Normal Hits) Max 12,632, Min - 10,950

100x Frost Strike's on Valhalla:
- Frost Strike (Crititical Hits) Max - 24,154, Min - 20,722
- Frost Strike (Normal Hits) Max - 12,085, Min - 10,381

Modifiers:
  Mastery: Frozen Heart - 37%
  Threat of Thassarian - 100%
```
