### ISSUE TITLE
Arena Passive Buffs

### ISSUE THREAD

**Issue by Bombrick** [Valhalla-Gaming/Tracker#4774]
Passive buffs doesn't work in arena It doesn't appear in buffs list and doesn't give  bonus

**Comment by miloskovac** [comment]
Its not about arena mate, its about that, that some1 buffed u before with a buff that has a time duration...after the time expires (or u enter arena) those buffs disapear but u lose ur passive abilitis as well. This was posted already (by me 1 month ago) and collector yesturday.
To 'get' ur passive abilities back, u need to relog.
Cheers

**Comment by Bombrick** [comment]
Dude I don't have time to relog in arena I wabt to have the passive buffs which has no limit duration in arena

**Comment by Bombrick** [comment]
Want'

**Comment by Bombrick** [comment]
Want'

**Comment by miloskovac** [comment]
I know what u meen, and i feel ya.
But its not up to me to fix it :*

**Comment by Tregeta** [comment]
Please provide us a list of the passive buffs you're speaking about.

**Comment by Bombrick** [comment]
I tried 2 only for now and both not working in arena  : Windflurry (WW Monk), Grace of Air (Shaman)

**Comment by Bombrick** [comment]
Windflurry works as intended now
