### ISSUE TITLE
Fishing Toubles

### ISSUE THREAD

**Issue by MagraHell1989** [Valhalla-Gaming/Tracker#4775]
Hellow. I wanted to notice that fishing doesn´t work. The bauble splashes and makes noise, but when i click on it to get the fish, an "interrupt" word appears instead and i can´t get the fish.

**Comment by GamerCrazy2** [comment]
This is Still an issue 5 months later :T

**Comment by Hemoglobine-Valhalla** [comment]
Fishing still doesnt work in the Legion server, same bug appeared when you're about catch the fix "Interrupt" appears and you dont get skill point or node loot.

**Comment by Frosting0** [comment]
I guess that puts this at 9 months now. Fishing doesn't work, I want dem dailies.
