### ISSUE TITLE
[Death Knight] Black door re-use don't work

### ISSUE THREAD

**Issue by Volodslav** [Valhalla-Gaming/Tracker#4776]
Hello developers,
I noticed that the back-porting with the black door from the dk don't work.
Porting from any place to Acherus works fine, but when I use black door again standing in Acherus, it don't ports me back to where I set the black door the first time.
Would be outragerous if you could fix it :)

Thanks a lot,
Vladdi

**Comment by Tregeta** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/947
