### ISSUE TITLE
Shaman Spell bug: Ancestral Swiftness

### ISSUE THREAD

**Issue by niveks1** [Valhalla-Gaming/Tracker#4780]
http://www.wowhead.com/spell=16188/ancestral-swiftness
this spell worked well, but now this spell is consumed with any other spell, even shocks and ticks of  spells, when it should be consumed only with Nature spells

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #2266
