### ISSUE TITLE
parry

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#4781]
Plate clasess like death knights or paladins have way to much parry chance in DPS spec. My death knight 714 pvp ilvl have 33% parry chance and lots of my attacks get parried by retribution paladins. 

I don't know how it is on retail so I'm just guessing. Please don't hit me if I'm wrong.

http://wow.gamepedia.com/Parry

**Comment by Tobaccoz** [comment]
I went to retail armory, a full S3 DK has 22,71%
Source: http://us.battle.net/wow/en/character/korgath/Mes/advanced

**Comment by Chimba** [comment]
I have 17% parry chance with my frost DK

**Comment by Collector-Valhalla** [comment]
I don't know why but it changes randomly. Sometimes I have 16%+ parry too and sometimes I have this...

![wowscrnshot_022616_013430](https://cloud.githubusercontent.com/assets/14946340/13343138/c5fae204-dc49-11e5-97f4-a3f4a98af056.jpg)

... I have no clue why.

**Comment by miloskovac** [comment]
Well, gear value goes up in bgs/arenas and parry will scale with strenght....but 45% is way too much...also warriors parry is way too high (parry chanse of 15% will proc if 7/10 times, tested it several times).
Also, BLOCK should reduce dmg for 30% on hit dmg, not ignore all dmg afflicted (100k dmg spell, should do 70k if blocked, not 0 dmg if blocked).

**Comment by Bombrick** [comment]
Thanks miolskovac for the Information I made another issue about your report for blocks

**Comment by miloskovac** [comment]
Anytime :D

**Comment by miloskovac** [comment]
Btw, DKs get a 25% parry rating of their Strenght, so when a dk activate Pillar of Frost spell, and gets a trinket strenght proc, and gets proc on fallen crusader weapon rune, the parry ratig will go significatly up whit it.

**Comment by Traveler-Valhalla** [comment]
is this still a thing in Legion? idk
