### ISSUE TITLE
[Death Knight] Army of the Dead

### ISSUE THREAD

**Issue by Tregeta** [Valhalla-Gaming/Tracker#4782]
Upon using the spell it begins to show ghouls being summoned, however after it is cast, all but one vanish.

http://www.wowhead.com/spell=42650/army-of-the-dead

**Comment by Bombrick** [comment]
Also ghouls deal very low dps (100-200) at end game pvp I don't know if this is normal or not

**Comment by Moustachos** [comment]
Ref #2266
