### ISSUE TITLE
Engineering

### ISSUE THREAD

**Issue by stefo555** [Valhalla-Gaming/Tracker#4783]
You see i am at level 60 with engineering, but np matter how many rough pwders or dunamites i create i wont advance past sixty so im stuck plz help i want that glider.

**Comment by Tregeta** [comment]
http://www.wowhead.com/skill=202/engineering 

Please have a look at this list: rough powder becomes gray at 40, which if you are at 60 already with this trade skill it will not level with that ability any further. Same with dynamites, it turns gray at 60, you will no longer get levels from this.
