### ISSUE TITLE
Fire Mage Proc and Effect Bug!!

### ISSUE THREAD

**Issue by MagraHell1989** [Valhalla-Gaming/Tracker#4800]
When a critical damage is landed with a fire spell, the proc that allows to cast pyroblast instant, no mana and with 25% more spellpower doesn´t appear, and thus, the effect of pyroblast can´t happen.

**Comment by Tregeta** [comment]
Link from WoWhead please.

**Comment by Collector-Valhalla** [comment]
[Heating Up](http://www.wowhead.com/spell=48107/heating-up)

**Comment by Tregeta** [comment]
Ref #4640
