### ISSUE TITLE
[Monk][Spell][Windwalker] Touch of Karma 

### ISSUE THREAD

**Issue by Bombrick** [Valhalla-Gaming/Tracker#4801]
Touch of Karma got broken after last update Now you take damage and your enemy take very low damage too now Need re write High Priority

**Comment by Moustachos** [comment]
Nothing changed on this spell in last update, and I just tested it without any problem.

So unless you can provide more information and a way to reproduce the bug your experienced, I'm afraid we can't help you and I'll close the issue.

**Comment by Bombrick** [comment]
I tried it in a duel and It didn't work . but now it works I think the issue was temporarily 
(note I relogged)

**Comment by Bombrick** [comment]
Tried last time sometimes it doesn't work and sometimes it does

**Comment by Bombrick** [comment]
Will make another issue with more details
