### ISSUE TITLE
[QUEST] 4 important quest on Draenor what need to work

### ISSUE THREAD

**Issue by sevike777** [Valhalla-Gaming/Tracker#4802]
Darkness Falls

The Battle of Thunder Pass

The Battle for Shattrath

And Justice for Thrall

Darkness Falls - http://www.wowhead.com/quest=33837/darkness-falls

The Battle of Thunder Pass - http://www.wowhead.com/quest=34124/the-battle-of-thunder-pass

The Battle for Shattrath - http://www.wowhead.com/quest=34099/the-battle-for-shattrath  AND  http://www.wowhead.com/quest=33731/the-battle-for-shattrath  (alli&horde)

And Justice for Thrall - http://www.wowhead.com/quest=35171/and-justice-for-thrall  AND  http://www.wowhead.com/quest=35169/and-justice-for-thrall  (alli&horde)

**Comment by Tregeta** [comment]
Ref #2608
