### ISSUE TITLE
Warrior Block

### ISSUE THREAD

**Issue by Bombrick** [Valhalla-Gaming/Tracker#4810]
Block is bugged when a warrior blocks spell or something they are supposed to take 30% less damage not take no damage at all.
For example If I cast a 30k damage spell they should block around 8-10k damage not block 30k.

**Comment by Bombrick** [comment]
EDIT : Block value seems to be very high on this server also

**Comment by Myrmidonx** [comment]
do you have any proof/pic to show this? Im seeing the block working as intended (tank class) like

A player did 1400  dmg (600 blocked)

*by the way, yes, dps class got parry and other defensive stats WAY too wrong.

**Comment by Bombrick** [comment]
#4781
