### ISSUE TITLE
[Monk][Spell][Windwalker] Touch of Karma

### ISSUE THREAD

**Issue by Bombrick** [Valhalla-Gaming/Tracker#4811]
It's broken in pvp ( battle ground and arenas) and in duels Was working well before last update now it got broken

**Comment by Bombrick** [comment]
Needs Urgent fix Necessary for WW Monk Survivability

**Comment by Moustachos** [comment]
Fixed on next update.

Ref #2266

**Comment by Bombrick** [comment]
@Moustachos thanks man I really need that spell
