### ISSUE TITLE
Shaman: Lava Burst (damage)

### ISSUE THREAD

**Issue by Djurdjevdan** [Valhalla-Gaming/Tracker#4813]
Lava Burst deals more damage when you are restoration then when you are elemental. in fact it deals double the amount.
I am level 51 when I am writting this.
As restoration, my Lava Burst deals 1044 damage
As elemental, my Lava Burst deals 522 damage

I would love someone on higher levels to comfirm this is happening just in case.

**Comment by Tregeta** [comment]
Ref #2958
