### ISSUE TITLE
Druid: Bear form (Health)

### ISSUE THREAD

**Issue by Djurdjevdan** [Valhalla-Gaming/Tracker#4815]
You have higher HP when you are in battleground then in world.
In world I have 398k when I am in bear form.
In battleground I have 498k when I am in bear form.

**Comment by Tregeta** [comment]
PVP gear?

**Comment by Djurdjevdan** [comment]
Well I am in full PvP gear.

**Comment by miloskovac** [comment]
Well, ur gear scales in the arena/BGs, cose it is a pvp gear.
Everything is all right
