### ISSUE TITLE
Glyph of Regenerative Magic

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#4817]
http://www.wowhead.com/spell=146648/glyph-of-regenerative-magic

Cooldown of anti magic shield with this glyph always go down to ~20 seconds after effect ends no matter if you absorbed any magic at all.

**Comment by Moustachos** [comment]
This glyph works as intended, the closer you are to initial absorb amount the more CD reduction you get (up to 50% of base cooldown).

I just tested it and with no damage absorbed cd dropped to 19 sec, with many damage taken it was around 30 sec.
