### ISSUE TITLE
Heirloom Hoarder "Achievement"

### ISSUE THREAD

**Issue by KeyBlack** [Valhalla-Gaming/Tracker#4822]
When i have 35 heirloom, the achievement send you a Mount called "Chauffeured Chopper", but when i tried to learn it, the key dissapeared and i didn't learn, and in my collection didn't appear.

**Comment by Trekex** [comment]
That's why you are Horde. They have started to fix only Alliance one so far.

**Comment by Tregeta** [comment]
Ref to #4709
