### ISSUE TITLE
When is envenom going to get fixed ?

### ISSUE THREAD

**Issue by sebway2k3** [Valhalla-Gaming/Tracker#4827]
I just started to play on this private server and i really think this is the best i have ever seen, i started a rogue since my main character on retail is a rogue and i noticed that my melee auto attack are dealing more damage than envenom, even with 5 combo points, i'm level 31 and my auto attacks does around 65 - 75 damage but envenom only deal 50 at best which is kinda sad since that's assassination's only combo finisher, are you guys aware of that and plan to fix it ?

**Comment by Tregeta** [comment]
Yes we are aware of it, it's already on our tracker, you won't need to open another issue on the spell.

Ref #4178, #4547
