### ISSUE TITLE
CP cap have being reseted to 1500

### ISSUE THREAD

**Issue by miloskovac** [Valhalla-Gaming/Tracker#4833]
Hello ppl.
After the update (and late cp reset) the cp cap (based on arena rating) has been reseted to 1500.
Please fix this cose ppl were working hard to get to certain rating and now the reward has been taken from us.
This is High Priority

**Comment by Collector-Valhalla** [comment]
#4770
Yes it is ;oooo

**Comment by Tregeta** [comment]
updated from high to critical on #4770

**Comment by EPS1L0N** [comment]
We had to do a manual reset today due to an issue that came up with the timers, everything should be back to normal after the next reset, also:

> Your cap is calculated based on your best rating from the previous week, so if you don't do arenas for a week it will reset to 1500- this is blizzlike
