### ISSUE TITLE
Raid loot

### ISSUE THREAD

**Issue by Khainite** [Valhalla-Gaming/Tracker#4834]
I'm not sure what happened in last update but now no raids are seem to be dropping loot in Karazhan, Naxx and OS that I tested tonight and all 3 were doing so before. Furthermore MC is not spawning either. Just a heads up there.

**Comment by Valhalla-Gaming** [comment]
What loot settings do you have, also did you set a loot specialization?

**Comment by Khainite** [comment]
I just had it on normal 10man raid hopped in killed the first 2 bosses in
the construct quarter. No loot dropped on trash or bosses. Then spoke to
Petulah who was in Karazhan whom was experiencing a similar issue. So, then
i went to os to kill the boss there and no loot appeared there either.

**Comment by Valhalla-Gaming** [comment]
Thank you for reporting this. We will look into it ASAP. Please continue to update this post with additional dungeon and raid looting issues as you find them.

**Comment by Valhalla-Gaming** [comment]
A last minute addition caused the issues above. Molten Core will require more research to solve, so we have removed it from the change log for now. The loot issue has been fix.
