### ISSUE TITLE
Priest: Saving grace

### ISSUE THREAD

**Issue by Vynrae** [Valhalla-Gaming/Tracker#4835]
The spell healing is still not reduced in pvp combat.

**Comment by Aprophys** [comment]
ofc it is in pvp i heal with Saving grace only 50k in a duell.

**Comment by EPS1L0N** [comment]
http://puu.sh/nqPtG/488d8f54be.jpg

SP                                  = 7003    (spell power)
Vers                               = 1.0376 (3.76% versatility)
PvPHealingMod             = 0.85     (All healing and absorbs reduced by 15% in pvp combat)
PvPSavingGraceMod     = 0.75     (Saving Grace healing reduced by 25% in pvp combat)
GracePassive                 = 1.3
MasteryMod                   = 1.15     (Mastery: Shield Discipline, 30% mastery = 15% to heals)
SavingGraceDebuff        = 0.85

SP * 9.45 = 66178.35 (rounded to 66179 in tooltip)
(66179+1) * 1.0376 * 0.85 * 0.75 * 1.3 * 1.15 * 0.85 = 55628.46

account for some rounding, we get 55630.

only issue i see here is that I don't think the debuff should be applied before it calculates the heal, so the first Saving Grace gets reduced by the debuff

**Comment by EPS1L0N** [comment]
Fixed the issue with the debuff
