### ISSUE TITLE
Conquest points cap.

### ISSUE THREAD

**Issue by Vynrae** [Valhalla-Gaming/Tracker#4836]
CP cap is now fixed at 1500 again, while i have 1800+ rating.

**Comment by Aprophys** [comment]
Same here.

**Comment by miloskovac** [comment]
They made this issue critical priority.
Apperently we have 1500 rating this week :s
Is it posible to do the reset now and fix the player ratings?

**Comment by Tregeta** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/4833#issuecomment-190564570
