### ISSUE TITLE
Quests

### ISSUE THREAD

**Issue by Lonlyy** [Valhalla-Gaming/Tracker#4838]
Hello, since im new to this server (Valhalla-Gaming), and i really hate bugged quests, i'll start doing every quest that i came to find and if it's bugged i'll post here, so, please start fixing them. :)

First quests that i came to find  bugged are from Eversong Woods:
1. [Tiger Palm] - http://www.wowhead.com/quest=31171/tiger-palm - It do not count as completed when i use my Tiger Palm on Training Dummy, and i've tried few of them, just to be sure.
2. [Thirst Unending] - http://www.wowhead.com/quest=37439/thirst-unending - Same as above, it do not count as completed when used near Mana Wyrm (http://www.wowhead.com/npc=15274/mana-wyrm) or Feral Tender (http://www.wowhead.com/npc=15294/feral-tender) since u can complete it with both of this mobs. And i've tried with more than one mob of each groupe.
3. [Whitebark's Memory] - http://www.wowhead.com/quest=10166/whitebarks-memory - unable to summon Old Whitebark (http://www.wowhead.com/npc=15409/old-whitebark) at Scorched Grove Runestone, i've tried to use it around runestone by moving step by step and still nothing.

That's all for now, ill keep looking for buggs and i'll let ya know about them, and i'll be waiting for fixes :)

-Lonlyy

**Comment by Tregeta** [comment]
Ref for 1. #4621
2. Possibly related to being a monk
3. #4620

**Comment by Pure-Valhalla** [comment]
Please note to make a separate post for each issue, Thanks!
