### ISSUE TITLE
Power Word: Shield adjusting

### ISSUE THREAD

**Issue by Tobaccoz** [Valhalla-Gaming/Tracker#4840]
Patch 6.1.0 (24-Feb-2015): Power Word: Shield now absorbs 10% less damage.
Source: wowhead
Is this already implended? Wondering because I see you are adjusting spell formulas according to hotfixes.

**Comment by Aprophys** [comment]
Powerword shield absorbs on a full cp disc only 65k dmg

**Comment by EPS1L0N** [comment]
only changes that say "in pvp combat" need to be manually set

**Comment by Tobaccoz** [comment]
I see, my bad then, thank you for explanation.
