### ISSUE TITLE
Monk| Guard bug.

### ISSUE THREAD

**Issue by neano300** [Valhalla-Gaming/Tracker#4849]
Hello, I found a bug of monk in the spec of Brewmaster  is the guard.

When you use Purifying Brew you give to your friend or any from 15yards a shield (Guard)

I make a video to report this bug.
https://www.youtube.com/watch?v=7mP3JJuO_3E&feature=youtu.be

**Comment by Collector-Valhalla** [comment]
Maybe it's because of [Monk WoD PvP Brewmaster 4P Bonus](http://www.wowhead.com/spell=171445/item-monk-wod-pvp-brewmaster-4p-bonus).

**Comment by neano300** [comment]
Maybe, but if u look fine its a bug. 1 Chi = 1 shield and no consume the real Guard

**Comment by Moustachos** [comment]
Will be fixed on next update, thanks for reporting.
