### ISSUE TITLE
Meilosh of Timbermaw Hold

### ISSUE THREAD

**Issue by Max-Valhalla** [Valhalla-Gaming/Tracker#485]
"http://www.wowhead.com/npc=11557/meilosh#sells

This NPC does not sell or teach (even at revered) anything."

**Comment by Trekex** [comment]
[Stave of Fur and Claw](http://www.wowhead.com/item=66888/stave-of-fur-and-claw) is still missing.

**Comment by TheRealHoboo** [comment]
[Stave of Fur and Claw](http://www.wowhead.com/item=66888/stave-of-fur-and-claw) still missing :(

**Comment by Tregeta** [comment]
fixed next update
