### ISSUE TITLE
Icebound Fortitude

### ISSUE THREAD

**Issue by DKwhitenoise** [Valhalla-Gaming/Tracker#4855]
This spell is function, but when is DK already stunned. DK can use icebound fortitude like insignia.
Im in stunt and i can use icebound fortitude for escape from stunt = bugged.
http://www.wowhead.com/spell=58130/icebound-fortitude

**Comment by Moustachos** [comment]
This is not a bug, see http://wow.gamepedia.com/Icebound_Fortitude

> Patch 4.0.6 (2011-02-08): Now breaks stuns when used, in addition to providing immunity to them.

**Comment by Moustachos** [comment]
Ref #2266
