### ISSUE TITLE
Maelstrom weapon

### ISSUE THREAD

**Issue by DKwhitenoise** [Valhalla-Gaming/Tracker#4856]
Maelstrom weapon problem with stacking.
http://www.wowhead.com/spell=51530/maelstrom-weapon

**Comment by EPS1L0N** [comment]
need more info

**Comment by DKwhitenoise** [comment]
stacking maelstrom weapon is too slowly = never use instant heal...

**Comment by Tregeta** [comment]
Ref Maelstrom Weapon 	#2802, #3596
