### ISSUE TITLE
Druid's Wild Mushroom spell bug

### ISSUE THREAD

**Issue by tribaljet** [Valhalla-Gaming/Tracker#4861]
http://www.wowhead.com/spell=88747/wild-mushroom

When a Balance Druid casts this spell, multiple Wild Mushrooms can be spawned and a player for the opposing faction that isn't flagged for PvP can get flagged when getting in (aggro) range. This flagging issue seems to happen in the event the opposing faction player reflects damage.

**Comment by Tregeta** [comment]
Ref #2161
