### ISSUE TITLE
Soul Link / Grimoire of Sacrifice

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#4877]
http://www.wowhead.com/spell=108415/soul-link
http://www.wowhead.com/spell=108503/grimoire-of-sacrifice

Grimoire of Sacrifice should give 20% more health points with Soul Link talent. Currently it gives 20% more HP by default even without Soul Link.

**Comment by Tregeta** [comment]
#2266
