### ISSUE TITLE
Monk skills bugged.

### ISSUE THREAD

**Issue by neano300** [Valhalla-Gaming/Tracker#4880]
Hello, today i test  3 skills bugged to report here, well my english is not profesional but i make videos about this to show.

1) Surging Mist. This skill generate Chi when can not do it, its only a heal not a chi generator. (Only generate chi in Mistweaver)
Video: https://www.youtube.com/watch?v=ZWvWSWCGwZE&feature=youtu.be
WoWHead Link: http://www.wowhead.com/spell=116694/surging-mist

2) Breath of Fire. This skill is a fire dot for 8 seconds but only do the first damage and have a really low chance to give the dot.
Video: https://www.youtube.com/watch?v=dlUx8wfe93Q&feature=youtu.be
WoWHead Link: http://www.wowhead.com/spell=123394/glyph-of-breath-of-fire

3) Charging Ox Wave: This is a range stun but dont work in anything, No stun and no visual just dont work.
Video: https://www.youtube.com/watch?v=8HF-Rex2WaM&feature=youtu.be
WoWHead Link: http://www.wowhead.com/spell=119392/charging-ox-wave

And here a Video showing all the videos
Video: https://www.youtube.com/watch?v=_xd02PviVtY&feature=youtu.be

**Comment by Moustachos** [comment]
1) will be fixed on next update
