### ISSUE TITLE
Psychic Scream

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#4882]
http://www.wowhead.com/spell=8122/psychic-scream

Fears two times in a row. First time for about 1 second with half second gab to other X amount of seconds fear.

But I think that might affect other abilities aswell. For example DKs [Remorseless Winter](http://www.wowhead.com/spell=108200/remorseless-winter).

**Comment by GAMMARAYS** [comment]
Fixed.
