### ISSUE TITLE
Some raids won't reset

### ISSUE THREAD

**Issue by PrizmPotter** [Valhalla-Gaming/Tracker#4886]
The Black Temple and Serpentshrine Caverns both won't reset. There may be more but right now the bosses won't respawn when I do 'reset instances' It only shows that dungeons are reset and not these raids.

**Comment by Collector-Valhalla** [comment]
You can't reset raids. Open your calendar to see when they reset. You can do em once per week.

**Comment by PrizmPotter** [comment]
I know I just figured this out -.- the GM I asked before DID NOT tell me that and told me to post it here

**Comment by Tregeta** [comment]
Have you found where?
