### ISSUE TITLE
The obsidian Sanctum angry eggs

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#4895]
[The Obsidian Sanctum](www.wowhead.com/zone=4493/the-obsidian-sanctum)

There is this thing attacking you. Not targetable or killable.

![wowscrnshot_030616_012240](https://cloud.githubusercontent.com/assets/14946340/13551458/e5f5b762-e33a-11e5-902d-cd12a4213bde.jpg)

**Comment by Tregeta** [comment]
fixed next update
