### ISSUE TITLE
Emblem of...

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#4896]
[Emblem of Triumph](http://www.wowhead.com/item=47241/emblem-of-triumph) and [Emblem of Frost](http://www.wowhead.com/item=49426/emblem-of-frost) are dropped by bosses in Ulduar, Ruby and Obsidian Sanctum and Vault of Archavon. 

Those items should not exist in current version of the game.

**Comment by Collector-Valhalla** [comment]
Also four horseman chest in Naxxramas have that emblem inside.

**Comment by Tregeta** [comment]
Fixed in next update
