### ISSUE TITLE
Death Grip DC?

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#4897]
I'm not sure but... I think [Death Grip](http://www.wowhead.com/spell=49576/death-grip) sometimes causes disconnects to pulled players.

**Comment by Tregeta** [comment]
How often has this occurred?

**Comment by Collector-Valhalla** [comment]
It's "rare". Maybe once per 100 bgs? I don't know. 

And I think it happens to players that have some lag/high latency. Last person that disconnected from my Death Grip (2-3 days ago) was "teleporting" around and still moving after dead.

**Comment by Moustachos** [comment]
Doesn't seem related to Death Grip, since it's totally random and apparently only occurs on players with a high latency.

So it's likely a network issue.
