### ISSUE TITLE
Silk Bandage

### ISSUE THREAD

**Issue by Max-Valhalla** [Valhalla-Gaming/Tracker#492]
Silk bandages are healing 1250 each sec when it was supposed to heal 720 over 8 secs.

**Comment by Guybrush-Hellscream** [comment]
Same trouble with Linen Bandage (https://github.com/HellscreamWoW/Tracker/issues/2137) and Heavy Silk Bandage (https://github.com/HellscreamWoW/Tracker/issues/2138).

**Comment by Tregeta** [comment]
fixed next update
