### ISSUE TITLE
Protection Paladin Armor Specialization bug

### ISSUE THREAD

**Issue by tribaljet** [Valhalla-Gaming/Tracker#4936]
http://www.wowhead.com/spell=86525/plate-specialization

The Paladin's Protection spec isn't benefiting from armor specialization, whereas the Retribution spec is. Holy spec wasn't tested.

**Comment by Moustachos** [comment]
Works as intended, just tested it.

It can be easily verified by equipying some common plates items (sold by http://www.wowhead.com/npc=1349/agustus-moulaine for example), check your stamina then try to equip an item of an invalid type (ie: mail), you'll see your stamina drop / increase by 5%.

Also, make sure you have an armor piece of the right time equipped in each required slot (head, shoulders, chest, wrist, waist, legs, feet).

**Comment by Moustachos** [comment]
Ref #2266

**Comment by tribaljet** [comment]
The plate specialization is working indeed, but instead of increasing the previous stamina by 5% with a given player having a full plate armor set, it's decreasing it by 5% when placing mail armor or lower. This can be observed through how I have had the exact same gear for over a week prior to the last update as well as after the last update and stamina didn't change at all, it can only go down by replacing a plate armor piece with a mail (or lower) armor piece with the same stamina value.

Please look into this as armor specialization for Protection Paladins is not working as intended.

**Comment by EPS1L0N** [comment]
> they can get 5% less if they swap one plate armor piece for another armor type

Plate Armor Specialization is only applied when you are wearing only plate, so if you have a piece that isn't plate, the extra 5% won't be applied, therefor giving you a decrease of 5% if you go from full plate to all but one piece being plate. Prior to the update the 5% was applied regardless

**Comment by tribaljet** [comment]
So what you're saying is that it was already being applied before, hence me not seeing any stamina increase? I naturally don't intend on wearing anything other than plate but that does put my mind at ease.
