### ISSUE TITLE
hunter misc

### ISSUE THREAD

**Issue by sausagepl** [Valhalla-Gaming/Tracker#4939]
so here is a list of not working hunter talents.
◾ Mastery: Sniper Training is not working the buff is not show up when you stand still 
 Glaive Toss - does no damage
◾ A Murder of Crows - does nothing 
◾ Stampede - does nothing 
◾ Narrow Escape is not working 
◾ Glyph of Chimaera Shot - dont heal for 2 percent as it should
 Glyph of Aspect of the Cheetah  very usefull but its probaly not scripted
Explosive it does nothing after launching 
Glyph of Snake Trap not scripted

so its just a mm hunter report so survival is almost unplayable.i am a bit bored to se so much improvment on almost every class but not a single update was made for hunters.i now its important to fix the most bugged classes first but i think its time to start also whit this class because for example in pvp is hunter lost against almost every class and thats sad so please be so kind and start working a little bit on hunter fixes thanks and sorry fofr bad english

**Comment by Tregeta** [comment]
Sniper Training (Marksmanship) #4193
A Murder of Crows 	#2797
Narrow Escape #461, #2789
Explosive Trap #2357

Others will be logged.

**Comment by sausagepl** [comment]
I reported it all again because some reports are months old and nothing
happend :D
Dňa 9.3.2016 21:25 používateľ "Tregeta" <notifications@github.com> napísal:

**Comment by Tregeta** [comment]
Rest assured, you only need to report it once, our issues are flagged on the 2266 and on the milestones. When the developers reach hunters he will see these issues in their entirety.

**Comment by sausagepl** [comment]
Ok but is there any chance to se an update soon? Or are there still more
broken classes?
Dňa 10.3.2016 0:09 používateľ "Tregeta" <notifications@github.com> napísal:

**Comment by Tregeta** [comment]
It's possible that some may fit in each update, but it is entirely up to the spell developers on which area/class they are focusing on at the time. Rest assure it shouldn't be too much longer until all classes are in extremely good shape at the rate they are going.

**Comment by sausagepl** [comment]
Thanks a lot and have a nice day
Dňa 10.3.2016 6:01 používateľ "Tregeta" <notifications@github.com> napísal:

**Comment by Moustachos** [comment]
Narrow Escape was fixed in a previous update.

Mastery: Sniper Training and A Murder of Crows will be fixed on next update.

**Comment by Moustachos** [comment]
- Glaive Toss will be fixed on next update
- Glyph of Chimaera Shot will be fixed on next update
- Glyph of Aspect of the Cheetah will be fixed on next update
- Explosive Trap will be fixed on next update
- Glyph of Snake Trap will be fixed on next update

The only remaining bug of this issue is on Stampede.

**Comment by Moustachos** [comment]
Ref #2266
