### ISSUE TITLE
Necrotic Plague spell 

### ISSUE THREAD

**Issue by miloskovac** [Valhalla-Gaming/Tracker#4940]
Hello ppl. 
Necrotic plague spell had being refreshing with Holowing blast (basicly it should give 1 more stack, but now it refreshes the NP on the targets.

**Comment by miloskovac** [comment]
Update: Icy touch spell also refresh the necrotic plague on the target.

**Comment by miloskovac** [comment]
Also, Frost strike should 'give' 1 more stack of NP on the target (with Plaguebearer talent) and it doesnt

**Comment by Moustachos** [comment]
Ref #2266

**Comment by Bombrick** [comment]
Plaguestrike also resets NP
