### ISSUE TITLE
[npc] Sindragosa unattackable

### ISSUE THREAD

**Issue by lavalash551** [Valhalla-Gaming/Tracker#4945]
http://www.wowhead.com/npc=36853/sindragosa
I did the raid on 10 men difficulty and after killing the trash in front of her and her 2 minion dragons she started to attack me, landed and somehow the event stopped, i were out of combat and coulnt attack her.
On my screen shot you can see mee me mounted up (to prove i am out of combat).
![wowscrnshot_030916_145308](https://cloud.githubusercontent.com/assets/16776049/13661026/8bd93ecc-e68f-11e5-81d3-95ac861f971e.jpg)

**Comment by Tregeta** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/3276
