### ISSUE TITLE
Saving Grace

### ISSUE THREAD

**Issue by Maldazar** [Valhalla-Gaming/Tracker#4946]
Saving Grace debuff doesn't decrease shielding amount.
Video proof: https://www.youtube.com/watch?v=j-r3HkheV1A

**Comment by Nienz** [comment]
i might add something about saving grace it also triggers http://www.wowhead.com/spell=45243/focused-will effect with the dmg reduction, healed myself twice with saving grace and got 30% dmg reduction, that needs a bit way to overpowered meaning basically immortal status

**Comment by Moustachos** [comment]
Ref #2266
