### ISSUE TITLE
DK On a pale horse passive ability

### ISSUE THREAD

**Issue by miloskovac** [Valhalla-Gaming/Tracker#4947]
Hello ppl. 
This DK ability seems not to b wokring properly. 
http://www.wowhead.com/spell=51986/on-a-pale-horse
It should reduce moment slowing effects by 30% and increase mount speed by 20%

**Comment by Moustachos** [comment]
This passive works as intended (both effects).

Please test more carefully before reporting issues.

**Comment by Moustachos** [comment]
Ref #226
