### ISSUE TITLE
Warrior execute

### ISSUE THREAD

**Issue by Egnivia** [Valhalla-Gaming/Tracker#4949]
[http://www.wowhead.com/spell=5308/execute](url) should hit with main hand and off hand. It's dealing dmg only with off hand after last patch.
[http://imgur.com/PA2RAmW](url)
[http://imgur.com/psgXnZR](url)
[http://imgur.com/XSjZS8a](url)

**Comment by Moustachos** [comment]
That's just a combat log visual bug, both weapons are hitting.
