### ISSUE TITLE
[Item]  Burden of Eternity (Timeless Isle Chest Loot)

### ISSUE THREAD

**Issue by Luminescent-Valhalla** [Valhalla-Gaming/Tracker#4950]
After looting [Burden of Eternity](http://www.wowhead.com/item=103982/burden-of-eternity) from a chest on Timeless Isle you are unable to use the item to create and set piece of gear for your spec.

**Comment by Trekex** [comment]
#3492 :)

**Comment by Hacksandlies** [comment]
I guess its same thing that prevents you to create those green items from garrison missions.

**Comment by Tregeta** [comment]
Referenced already
