### ISSUE TITLE
Calling Pet Hunter Ability corrupt

### ISSUE THREAD

**Issue by Vofuse** [Valhalla-Gaming/Tracker#4957]
I made a blood elf hunter and when i entered again the the realm my pet dissapeared. When i press the call button in the hotbar seems stuck and the one from spell book doesn't make anything after the calling animation is made.

**Comment by Moustachos** [comment]
Can't reproduce this bug, looks like a character-specific issue.

Closing it, please contact a GM.

**Comment by Moustachos** [comment]
Ref #2266
