### ISSUE TITLE
Graham McTroller <Hippogryph Master>

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#4967]
I'm here at Surwich in Blasted Lands...
![wowscrnshot_031316_072503](https://cloud.githubusercontent.com/assets/14946340/13727279/d757cc9c-e8ec-11e5-94c9-1c12b6ba8cd1.jpg)

... but flight master thinks I'm in that troll jungle...
![wowscrnshot_031316_072514](https://cloud.githubusercontent.com/assets/14946340/13727285/f094ddb2-e8ec-11e5-9b28-6f55a5e83d65.jpg)

...HE TROLLED ME!

**Comment by carminejackal** [comment]
ref# https://github.com/Valhalla-Gaming/Tracker/issues/4404
