### ISSUE TITLE
Wow crash in talador

### ISSUE THREAD

**Issue by serenity-talador** [Valhalla-Gaming/Tracker#4969]
Hi , 

A friend have a curious problem , his character get disconnected when he is near the ptero nest in talador , but when i use his account (different computer) i'm able to move as there is no problem.

we really dont know why :/ just that it happen near the ptero nest

**Comment by Tregeta** [comment]
Have him clear his cache folder and log in to the game.

**Comment by serenity-talador** [comment]
Already done , sorry i didnt write it ^^
