### ISSUE TITLE
Unholy dk ghoul problems

### ISSUE THREAD

**Issue by Bombrick** [Valhalla-Gaming/Tracker#4971]
Some spells are missing like leap in normal ghoul and Stambling charge inDark Transformation

**Comment by Bombrick** [comment]
I also think it deals low dps not sure about this

**Comment by Moustachos** [comment]
Check your ghoul's spellbook, they aren't missing :)

**Comment by Bombrick** [comment]
And Dark Transformation doesn't increase ghoul dps by100% didn't find any diffrence at dps
