### ISSUE TITLE
Fists of Fury

### ISSUE THREAD

**Issue by Chimba** [Valhalla-Gaming/Tracker#4974]
Enemies parry a monk skill called Fists of Fury. It's channeling skill that applies stun and damage, not an apply-damage-on-hit skill. I don't think that it is supposed to have a chance of parrying this skill. (Prove me if I'm wrong :P )

**Comment by Tregeta** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/907#issuecomment-109758919
