### ISSUE TITLE
Glyph of Savagery

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#4983]
http://www.wowhead.com/item=110816/glyph-of-savagery

Doesn't work.

**Comment by Tregeta** [comment]
@Raizo575

> You learn it, you use it, Savage Roar shows on your spellbook as a passive 30% damage buff, but that's in your spellbook only, it doesn't give you an increase to damage whatosever nor make the Savage Roar animation when you shift into Cat Form
