### ISSUE TITLE
Glyph of Ninth Life

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#4984]
http://www.wowhead.com/spell=159444/glyph-of-the-ninth-life

I'm bad at math but I think it reduces more than 10% of damage taken.

EDIT: At least frostbolt during duel dealt to me 15k damage without glyph and 8k with it. In BGs there's too many numbers and my brain can't take it.

**Comment by Moustachos** [comment]
Reduction's amount is 10%, not much.

**Comment by Moustachos** [comment]
Ref #2266
