### ISSUE TITLE
Mark of the Shattered Hand

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#4986]
http://www.wowhead.com/spell=159236/mark-of-the-shattered-hand

You can kill yourself with that thing. Procs on you from doing damage or healing.

So I guess you could heal low level players to kill them. thihi

**Comment by Aveta** [comment]
Sounds like issue that happens with Elemental Force enchantment I once reported.
Damaging self in case of that one happened on dots, leech, heals from strikes like Blackout Kick and Bloodthirst etc.
Also, this thing procs on every single bit of dmg which makes it obscenely overpowered. I heard it's already being abused in pvp.

**Comment by Bombrick** [comment]
Some rouge abuse it also Its effect stays forever  till you die even after leaving combat and stop being  ttacked

**Comment by Aveta** [comment]
It seems to proc off itself.

**Comment by Tregeta** [comment]
Fixed next update
