### ISSUE TITLE
Eversong woods Quests

### ISSUE THREAD

**Issue by Max-Valhalla** [Valhalla-Gaming/Tracker#500]
"http://www.wowhead.com/npc=16144/lord-saltheril Is not there so you can't complete or do any subsequent quests.

http://www.wowhead.com/quest=9395/saltherils-haven

http://www.wowhead.com/quest=8885/the-ring-of-mmmrrrggglll I killed Mmmrrrggglll three times and the ring did not drop.

http://www.wowhead.com/quest=8490/powering-our-defenses does not work
http://www.wowhead.com/item=22693/infused-crystal <--you can use this item, but you don't get credit.

http://www.wowhead.com/quest=9258/the-scorched-grove You can not complete or do Subsequent quests because the NPC 
http://www.wowhead.com/npc=16397/ardeyn-riverwind

all other seem to be in working order."

**Comment by Pure-Valhalla** [comment]
All quests have been fixed except Powering Our Defenses
