### ISSUE TITLE
Inscription: Scribe's Research Notes

### ISSUE THREAD

**Issue by llamalama** [Valhalla-Gaming/Tracker#5000]
http://www.wowhead.com/item=113992/scribes-research-notes

It works fine for teaching all the warbinder's ink glyphs but after it tries to teach you lower ink level ones it sometimes doesn't teach you a glyph at all.

**Comment by miloskovac** [comment]
I cant learn anymore glyphs. 
I learned all 'low lvl' herb glyphs got Dreanors Scribe's Notes, got few glyphs and now it doesnt give any glyphs at all. I tried over 40 of them on max inscript lvl (700).

**Comment by Tregeta** [comment]
Which ones are you missing? Are they from the old ones or the Draenor one?

**Comment by Tregeta** [comment]
Should be fixed in the next update
