### ISSUE TITLE
Monks are  too OP

### ISSUE THREAD

**Issue by Leondezwart** [Valhalla-Gaming/Tracker#5002]
So in bg a few minutes ago we came across a monk with 700k health and shields from 100k and to me it looked like that that shield didnt go away nor he did get hurt so u cant 1v1 nor 2v1 nor 3v1 so u must get the whole team to kill one guy and that reallly ruins the BG

**Comment by miloskovac** [comment]
True....also please fix the damn guard ability already (its too much absorb for a player to have fix 130k and (with full hp) it should b 30k) and plz fix the but that if in guard ppl can cap bases in bgs cose they ignore dmg taken (and for example if base is cleared and no enemy is around, ppl cant cap base cose of debuff and dot on ppl).

**Comment by miloskovac** [comment]
...and plz fix the ''bug''...

**Comment by Tregeta** [comment]
@miloskovac Where do you get the 30k value from?

**Comment by miloskovac** [comment]
Well, simple calculate says so (low geared monks also freshly made 100 with basic (620ilvl gear) with 2k ap and 1-2% versa, can make cca 30-35k guard abrosb, which can b improved (significatly) by resolve with dmg taken...and not fix guard on max stats which ppl (whose classes r pretty messed up) cant even pass.
Furthermore direct attack on ppl should interrupt caping flags and dots not.

**Comment by Bombrick** [comment]
You can kill fresh BM monk 1x1 but not the pvp geared

**Comment by Moustachos** [comment]
> Well, simple calculate says so (low geared monks also freshly made 100 with basic (620ilvl gear) with 2k ap and 1-2% versa, can make cca 30-35k guard abrosb, which can b improved (significatly) by resolve with dmg taken

Guard's absorb amount = _(Attack power * 18) * Versatility_, Resolve can only increase this amount, not reduce it, so even if Resolve mechanic isn't working at the moment, it's not related to this "bug".

For the "bug" itself, so far I haven't found the case, but I'm still investigating.

**Comment by miloskovac** [comment]
Well i dont think Ap*18*versa is a real formula for guard (regardless whats on wowhead) cose a simple math of good geared monk with his all cds poped up will have around 4.5k-5k ap and versa of 10-15%.
would make 750.000-1.400.000 absorb amount. and that aint the case.

**Comment by Moustachos** [comment]
> Well i dont think Ap18versa is a real formula for guard (regardless whats on wowhead) cose a simple math of good geared monk with his all cds poped up will have around 4.5k-5k ap and versa of 10-15%.
would make 750.000-1.400.000 absorb amount. and that aint the case.

Wowhead's formula is taken from client files, so it is the real formula, and your calculation is wrong, taking your example of 5.000 AP and 15% Versatility, Guard amount is:
(18 * 5000) * 1.15 = 103500

**Comment by miloskovac** [comment]
Oh my bad.... its 1+%versa not 1+versa.

**Comment by Moustachos** [comment]
To give you some news, this fix (already applied on previous Valhalla update):
> Generated charges of Elusive Brew are now based on weapon speed, not just weapon type

Should help for this issue, and another one will be deployed on next update:
> healing spheres provided by Gift of the Ox will now only heal on expire, not when you pass through them

Once this latest fix is live, I'd need your feedbacks (after a few days of course) to see if things are better / fine.

**Comment by Analog-Valhalla** [comment]
Old post. Does not represent 7.1.5
