### ISSUE TITLE
NPC: Bloodmaul Warder

### ISSUE THREAD

**Issue by skorge1** [Valhalla-Gaming/Tracker#5004]
The issue with http://www.wowhead.com/npc=75210/bloodmaul-warder#abilities is that his ability http://www.wowhead.com/spell=151545/frightening-roar isn't on a 3 second cast. It is instant cast which isn't right.

**Comment by Valhalla-Gaming** [comment]
Will be fixed in the next update. Also, this mob should have the "Hardened" buff in Mythic mode. This will also be fixed in the next update.
