### ISSUE TITLE
Pit of Saron

### ISSUE THREAD

**Issue by restlessspirit4** [Valhalla-Gaming/Tracker#5005]
Last boss Lord Tyrannus is untouchable,and for that matter unkillable.*you cant aim at him at all,but he can hit you and kill you)
By not be able to kill him,the players are unable to progress to halls of reflection dungeon.
I hope I explained this properly.

**Comment by Collector-Valhalla** [comment]
#4891

**Comment by Tregeta** [comment]
Since already referenced, now closing.
