### ISSUE TITLE
Fury Warrior damage

### ISSUE THREAD

**Issue by Bombrick** [Valhalla-Gaming/Tracker#5011]
Wild strike damage seems to be high a warrior 68k me outside pvp (wasn't fully geared cp) while on a retail video max wild strike with  itemlevel 740 was 54k  also seigebreaker damage seems to be higher than retail alot

**Comment by Leondezwart** [comment]
yeah seems to be im a warrior also and it does alot of dmg

**Comment by Egnivia** [comment]
If it was me i will say it again.. enrage, avatar, strength pot, battle shout, draenic strength potion.. I have 20k-22k dmg in WSG without potion and enrage.

**Comment by Bombrick** [comment]
Nah it was someone who spams wild strike and abuse potions to heal him

**Comment by Leondezwart** [comment]
i dont use potions cant be me ^^ too poor,... :(

**Comment by EPS1L0N** [comment]
#4570

**Comment by EPS1L0N** [comment]
#2266

**Comment by EPS1L0N** [comment]
reopening, wild strike is still either proccing too much or is doing too much damage

**Comment by Egnivia** [comment]
Where did u get wild strike is proccing too much? or doing high dmg?

**Comment by Leondezwart** [comment]
the proccing is normal but the dmg maybe not idk for sure though im a warrior fury (bigfighter)

**Comment by Bombrick** [comment]
Fixed and  closing issue
