### ISSUE TITLE
Inscription: List of all unlearnable glyphs

### ISSUE THREAD

**Issue by llamalama** [Valhalla-Gaming/Tracker#5019]
These glyphs are still not learned after getting the error "You have learned all recipes from this research." The only exception is Ink of Dreams because it just stops teaching glyphs without an error. The Scribe's Research Notes do not teach these glyphs either. #5000 

http://www.wowhead.com/guides/professions/wod/inscription-overview#learning-glyphs

Midnight ink: http://www.wowhead.com/spell=165304/research-midnight-ink
http://www.wowhead.com/spell=57250/glyph-of-chaining
http://www.wowhead.com/spell=57258/glyph-of-conflagrate
http://www.wowhead.com/spell=64296/glyph-of-death-from-above
http://www.wowhead.com/spell=64317/glyph-of-demonic-circle
http://www.wowhead.com/spell=64309/glyph-of-focused-mending
http://www.wowhead.com/spell=57202/glyph-of-prayer-of-mending
http://www.wowhead.com/spell=56958/glyph-of-skull-bash
http://www.wowhead.com/spell=57014/glyph-of-solace
http://www.wowhead.com/spell=64268/glyph-of-survival-instincts
http://www.wowhead.com/spell=64284/glyph-of-vendetta

Lion's Ink: http://www.wowhead.com/spell=165456/research-lions-ink
http://www.wowhead.com/spell=56975/glyph-of-combustion
http://www.wowhead.com/spell=57247/glyph-of-grounding-totem
http://www.wowhead.com/spell=95825/glyph-of-protector-of-the-innocent
http://www.wowhead.com/spell=57191/glyph-of-psychic-horror
http://www.wowhead.com/spell=64289/glyph-of-riptide
http://www.wowhead.com/spell=64311/glyph-of-unending-resolve
http://www.wowhead.com/spell=64295/glyph-of-wind-and-thunder

Jadefire Ink: http://www.wowhead.com/spell=165460/research-jadefire-ink
http://www.wowhead.com/spell=57223/glyph-of-army-of-the-dead
http://www.wowhead.com/spell=57181/glyph-of-circle-of-healing
http://www.wowhead.com/spell=64250/glyph-of-crimson-banish
http://www.wowhead.com/spell=64297/glyph-of-dancing-rune-weapon
http://www.wowhead.com/spell=56999/glyph-of-endless-wrath
http://www.wowhead.com/spell=64288/glyph-of-feral-spirit
http://www.wowhead.com/spell=57237/glyph-of-fire-elemental-totem
http://www.wowhead.com/spell=59561/glyph-of-immediate-truth
http://www.wowhead.com/spell=182157/glyph-of-purify-spirit
http://www.wowhead.com/spell=56954/glyph-of-regrowth
http://www.wowhead.com/spell=57127/glyph-of-smoke-bomb
http://www.wowhead.com/spell=64247/glyph-of-totemic-vigor

Shimmering Ink: http://www.wowhead.com/spell=165463/research-shimmering-ink
http://www.wowhead.com/item=90715/glyph-of-blackout-kick
http://www.wowhead.com/spell=57211/glyph-of-chains-of-ice
http://www.wowhead.com/spell=57124/glyph-of-detection
http://www.wowhead.com/spell=56946/glyph-of-hurricane
http://www.wowhead.com/spell=64281/glyph-of-leap-of-faith
http://www.wowhead.com/spell=57267/glyph-of-subtlety
http://www.wowhead.com/spell=64300/glyph-of-tranquil-grip
http://www.wowhead.com/spell=57232/glyph-of-unstable-earth

Ethereal Ink: http://www.wowhead.com/spell=165464/research-ethereal-ink
http://www.wowhead.com/spell=57207/glyph-of-anti-magic-shell
http://www.wowhead.com/spell=57115/glyph-of-blade-flurry
http://www.wowhead.com/spell=182154/glyph-of-cleanse
http://www.wowhead.com/spell=57263/glyph-of-felguard
http://www.wowhead.com/spell=57164/glyph-of-resonating-power
http://www.wowhead.com/spell=57234/glyph-of-spirit-walk
http://www.wowhead.com/spell=57195/glyph-of-spirit-of-redemption

Ink of the Sea: http://www.wowhead.com/spell=165465/research-ink-of-the-sea
http://www.wowhead.com/spell=57159/glyph-of-blitz
http://www.wowhead.com/spell=57233/glyph-of-chain-lightning
http://www.wowhead.com/spell=57019/glyph-of-focused-shield
http://www.wowhead.com/spell=56988/glyph-of-icy-veins
http://www.wowhead.com/spell=57130/glyph-of-kick
http://www.wowhead.com/spell=64248/glyph-of-life-tap
http://www.wowhead.com/spell=182156/glyph-of-purification
http://www.wowhead.com/spell=57260/glyph-of-verdant-spheres
http://www.wowhead.com/spell=57193/glyph-of-weakened-soul

Blackfallow Ink: http://www.wowhead.com/spell=165466/research-blackfallow-ink
http://www.wowhead.com/spell=64304/glyph-of-aspect-of-the-cheetah
http://www.wowhead.com/spell=64256/glyph-of-barkskin
http://www.wowhead.com/spell=56986/glyph-of-crittermorph
http://www.wowhead.com/spell=64257/glyph-of-deep-freeze
http://www.wowhead.com/spell=57190/glyph-of-mass-dispel
http://www.wowhead.com/spell=64246/glyph-of-mirrored-blades
http://www.wowhead.com/spell=94711/glyph-of-vanish

Ink of Dreams: http://www.wowhead.com/spell=165467/research-ink-of-dreams
http://www.wowhead.com/spell=64303/glyph-of-cloak-of-shadows
http://www.wowhead.com/spell=57189/glyph-of-deep-wells
http://www.wowhead.com/spell=56998/glyph-of-distracting-shot
http://www.wowhead.com/spell=57160/glyph-of-mortal-strike
http://www.wowhead.com/spell=57152/glyph-of-shield-slam

**Comment by Tregeta** [comment]
Should be fixed in the next update.
