### ISSUE TITLE
[Priest] [Talent] Power Infusion

### ISSUE THREAD

**Issue by Aprophys** [Valhalla-Gaming/Tracker#5020]
http://www.wowhead.com/spell=10060/power-infusion

This spell/talent dont reduce the mana cost correctly.
After multiple tests (same spells same ammount of spells)
this talent reduces only 7-10% and its might should be 20%

**Comment by Moustachos** [comment]
The reduction amount is just fine.

**Comment by Moustachos** [comment]
Ref #2266
