### ISSUE TITLE
[priest] [spell] - mind blast 

### ISSUE THREAD

**Issue by forstix** [Valhalla-Gaming/Tracker#5025]
when you hit a target for the first time with <a href="http://www.wowhead.com/spell=8092/mind-blast">Mind Blast</a>
 you get 3 orbs and not 1 as it should (start happening after the last update).

ty.

**Comment by Leondezwart** [comment]
i dont know alot about priests but it should give u 3 when the mob is under ur lvl and 1 just normal im not sure

**Comment by Collector-Valhalla** [comment]
With some glyph you get 3 orbs. Without it mind blast should generate 1 orb.

**Comment by forstix** [comment]
i'm talking about bg and without the glyph

**Comment by Moustachos** [comment]
Will be fixed on next update.

**Comment by Moustachos** [comment]
Ref #2266
