### ISSUE TITLE
Netherwing Egg

### ISSUE THREAD

**Issue by Aveta** [Valhalla-Gaming/Tracker#5028]
http://www.wowhead.com/item=32506/netherwing-egg
http://www.wowhead.com/object=185915/netherwing-egg
While the egg items are possible to obtain through drops, mining and herbalism the container objects with those don't spawn at all. This slows down the rep gain.

**Comment by Tregeta** [comment]
Should be fixed next update.

**Comment by Braemen** [comment]
I found 10 spawned object so yes, they spawn.
