### ISSUE TITLE
[NPC] Rivern Frostwind

### ISSUE THREAD

**Issue by lavalash551** [Valhalla-Gaming/Tracker#5034]
http://www.wowhead.com/npc=10618/rivern-frostwind
NPC should be fixed since a couple of days but still doesnt work as vendor when you are exhalted.
I'll add a screen shot as proof ("ehrfürchtig" is german for exhalted ;) )
![wowscrnshot_032416_082410](https://cloud.githubusercontent.com/assets/16776049/14010968/8ea52682-f19a-11e5-8dd7-05b84481db34.jpg)

**Comment by lavalash551** [comment]
![wowscrnshot_032416_083053](https://cloud.githubusercontent.com/assets/16776049/14010984/bc212f5c-f19a-11e5-929c-e683401ccb4f.jpg)

**Comment by Tregeta** [comment]
wrong npc flags, will be fixed in next update.
