### ISSUE TITLE
Potions, Elixirs, Flask and Food.

### ISSUE THREAD

**Issue by neano300** [Valhalla-Gaming/Tracker#5048]
Hello everyone I come here to report a bug really High.
The potions, elixirs flask and food give High stats when that is not true.

Flask of the Earth : http://www.wowhead.com/item=76087
This flask give you 171p stamina. but in the server increase with the level and that is not normal. 
Pic: [img]http://i.imgur.com/OpxGcmU.jpg[/img]

This happends with others buffs.

Food: Well Fed this http://www.wowhead.com/item=113143
This food give you 187p stamina but in the server give you 730.
Pic: [img]http://i.imgur.com/pmf2Ukz.jpg[/img]

Same with Elixirs:

Giant Growth:  http://www.wowhead.com/item=6662
A low potion level gives 8 strength but in the server give 417p 
Pic: [img]http://i.imgur.com/XVIBhMn.png[/img]
This is a problem in the PvP or Pve because make the server totally unbalanced. If you want know more elixirs, potions. flask and food just test alchemy and cooking.
Every food low level give you High stats.

Thanks for reading.

**Comment by Bombrick** [comment]
Same with health potions I think they scale with level in this server

**Comment by neano300** [comment]
Yeah, its a big bug.

**Comment by Egnivia** [comment]
Draenor potions are giving less stats then it should..

**Comment by GAMMARAYS** [comment]
Fixed
