### ISSUE TITLE
More abusing weapons molten-punch

### ISSUE THREAD

**Issue by Aprophys** [Valhalla-Gaming/Tracker#5055]
This have a procc chance of 15% not 100%
The damage is to high 
tahts the same issue like this other earlier bugged weapon " blazegrease" or what is called
http://www.wowhead.com/spell=163762/molten-punch
http://imgur.com/BAIvw9n this was a realy short fight like 20 sec after beated another alliance then the shaman and he onehit everything with this bug wep
thanks

**Comment by miloskovac** [comment]
Omg, plz make this high prio or warn that ...... shaman not to abuse this anymore cose he is making retarded amount of dmg with this buged weapons.

**Comment by Leondezwart** [comment]
so it is bugged i was curious abit it

**Comment by Tregeta** [comment]
Should be fixed next update
