### ISSUE TITLE
Take Four Bases/Control Four Bases

### ISSUE THREAD

**Issue by Trekex** [Valhalla-Gaming/Tracker#5056]
[Take Four Bases](http://www.wowhead.com/quest=8121/take-four-bases)  should be for Horde side only, but I keep getting it (I'm Alli).
Maybe there is the same issue with [Control Four Bases](http://www.wowhead.com/quest=8114/control-four-bases) that is Alli only, but I have no idea.

**Comment by Tregeta** [comment]
Deprecated quests.
