### ISSUE TITLE
[Warrior] Crazed Berserker

### ISSUE THREAD

**Issue by Tregeta** [Valhalla-Gaming/Tracker#5058]
http://www.wowhead.com/spell=23588/crazed-berserker

Spinx

> I was busy farming firelands straight away and first i tested out the damage between 2  2 handers (normal honor points) and the 2  1 handers (conquest points),anyway I was testing on a magma lord first with the 2 1 handers  I tested it out with only 1 bladestorm and did 30% health damage to him and then I tested with my 2  2 handers and it did 70-90% health damage.

**Comment by Moustachos** [comment]
This passive works just fine.

**Comment by Moustachos** [comment]
Ref #2266
