### ISSUE TITLE
INITIAL DRAENOR QUESTS CRASHED

### ISSUE THREAD

**Issue by checharor** [Valhalla-Gaming/Tracker#5059]
I've started the Draenor quest, i did the first three quests without problem, but i'm here in the part where are the Alliance and horde portals and when i talk to Archimage Kahadgar it tells me that take me to Draenor, it has a ! like i can take a quest, but it doesn't give me any quest.

If i click in take me to draenor it tells me that draenor is not abelivle to play until i finish... :/ WTF?

My character is Sarango Darnei priest lvl 90.
![wowscrnshot_033116_220618](https://cloud.githubusercontent.com/assets/13007618/14196778/317e783e-f78d-11e5-8ba4-02ee1a4b728c.jpg)

![wowscrnshot_033116_220718](https://cloud.githubusercontent.com/assets/13007618/14196782/3ebf21ce-f78d-11e5-95e6-22bfc8782082.jpg)

![wowscrnshot_033116_220737](https://cloud.githubusercontent.com/assets/13007618/14196792/4a2214a4-f78d-11e5-98e1-658e9fd89617.jpg)

**Comment by serenity-talador** [comment]
Did you try to accept ? it's been a while since i made this so i dont remember correctly whats to do but it surely work , ask players online

**Comment by Aveta** [comment]
Click Accept. Draenor isn't fully scripted but you can access it and get your garrison.
