### ISSUE TITLE
[Quest] The Woodland Protector

### ISSUE THREAD

**Issue by A-Vladimir** [Valhalla-Gaming/Tracker#5060]
When i go into the cave Tarindrella doesn't show up behind me. So i'm stuck with this quest. Even if a gm finishes the quest for me i would be still stuck because i need to get more quests from Tarindrella.
ps: I know there are other posts about this quest but it's still an issue and as a night elf i'm stuck so pls fix it.

**Comment by Valhalla-Gaming** [comment]
Fixed
