### ISSUE TITLE
[Druid] Eclipse

### ISSUE THREAD

**Issue by Aveta** [Valhalla-Gaming/Tracker#5063]
This time I'm providing a video. Eclipse mechanic is pretty much broken at this point, Peaks don't get consumed and the eclipses don't switch properly if they do at all (happens once every like 5 lunar eclipses). From what I learned it's not an isolated issue. It's not awesomesauce quality gameplay, but I guess it should show properly that sth isn't right. I sped up some of the cycles with Astral Communion.
https://www.youtube.com/watch?v=3XEZdLJ-eLM
I hope the vid can be viewed properly, I never did this stuff before x)

**Comment by unfairplayer** [comment]
![wowscrnshot_040116_200820](https://cloud.githubusercontent.com/assets/15180333/14217724/7601aa64-f858-11e5-828a-286f895ccafb.jpg)

From test on another druid (different PC and account). Seems it has the same problems.

**Comment by Moustachos** [comment]
I couldn't reproduce the issue you're experiencing in the video you provided (eclipses not switching properly), event after copying your character to my account to test it with the very same talents and such.

However, I did some small changes to Eclipse mechanics and fixed the issue with peaks.

Tell me if this bug still occurs after next update.

**Comment by Aveta** [comment]
I guess it was something borked in the live server code that wasn't present on test because this update fixed it.

**Comment by Moustachos** [comment]
Good then :)
