### ISSUE TITLE
Bladestorm classification

### ISSUE THREAD

**Issue by Vargrift** [Valhalla-Gaming/Tracker#5064]
Hello.

Bladestorm should be classified as an aura (possible to cancel) not as debuff (can't cancel). It's really annoying when you use bladestorm and they just fly/jump away and you can't do anything... It has major influence on warrior PvP.

Here Bajheera uses Bladestorm in first 30 sec of the video. See it on your own eyes ;) https://www.youtube.com/watch?v=FM2_Zg1Psrs

Also as a buff mage shouldn't steal it or priest dispell it. Only warrior himself can /cancelaura Bladestorm ;)

**Comment by Vargrift** [comment]
Here is my screenshot of bugged type of Bladestorm aura.

http://s30.postimg.org/o7hmyov6p/Wo_WScrn_Shot_040216_154542.jpg

**Comment by Moustachos** [comment]
Ref #2266

**Comment by Vargrift** [comment]
Why this thread was closed? Bladestorm is bugged and should be fixed one
day. It's a buff not debuff and warrior should /cancelaura it just like any
other spell.

2016-04-05 0:27 GMT+08:00 Moustachos <notifications@github.com>:

> Ref #2266 <https://github.com/Valhalla-Gaming/Tracker/issues/2266>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Valhalla-Gaming/Tracker/issues/5064#issuecomment-205377364>
>



-- 

Pozdrawiam,

Maksymilian Szafrański

**Comment by Tregeta** [comment]
When the issue is closed this means there is likely an update coming for it.
