### ISSUE TITLE
Glyph of Rallying Cry

### ISSUE THREAD

**Issue by Vargrift** [Valhalla-Gaming/Tracker#5065]
Hello.

http://www.wowhead.com/spell=159754/glyph-of-rallying-cry

Completely not working. Big loss of survivability for warriors. 20% leeching is like almost new skill.

**Comment by Vargrift** [comment]
Proof --> http://s16.postimg.org/9v3pzkypx/Wo_WScrn_Shot_040216_154253.jpg

Rallying Cry is on, I used offensive skills but still there's no healing.

**Comment by Moustachos** [comment]
Ref #2266

**Comment by Vargrift** [comment]
Why is this thread closed? Glyph is bugged and is not giving 20% leech, not
even at all.

2016-04-05 0:27 GMT+08:00 Moustachos <notifications@github.com>:

> Ref #2266 <https://github.com/Valhalla-Gaming/Tracker/issues/2266>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Valhalla-Gaming/Tracker/issues/5065#issuecomment-205377204>
>



-- 

Pozdrawiam,

Maksymilian Szafrański

**Comment by Tregeta** [comment]
When the issue is closed this means there is likely an update coming for it. If there is not it will be noted that it is working as intended.
