### ISSUE TITLE
Whirlwind rage cost

### ISSUE THREAD

**Issue by Vargrift** [Valhalla-Gaming/Tracker#5066]
Hello.

it's rage cost is 30 for all specs, while on Arms Warrior it should be 20 rage instead of 30 if not for all specs in WoD. About Arms I'm 100% sure.

http://www.wowhead.com/spell=1680/whirlwind#comments

**Comment by Vargrift** [comment]
Ok since server is back online I can say that arms warriors have 20 rage, but fury has 30. wowhead shows just 20, so propably other specs should have it.

Thing to check. If not just delete this.

**Comment by Moustachos** [comment]
This isn't a bug, see http://wow.gamepedia.com/Whirlwind

> Patch 5.2.0 (2013-03-05): Now costs 20 rage (was 30) for Arms Warriors. The cost is unchanged for Fury Warriors.

**Comment by Moustachos** [comment]
Ref #2266
