### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by checharor** [Valhalla-Gaming/Tracker#5067]
i download the new launcher but can't connect

![wowscrnshot_040116_210420](https://cloud.githubusercontent.com/assets/13007618/14223842/aaf1f982-f84d-11e5-8672-d711f724bc2e.jpg)
![wowscrnshot_040116_210454](https://cloud.githubusercontent.com/assets/13007618/14223845/b6c718b4-f84d-11e5-8837-bea0c9aff7a1.jpg)

**Comment by Vargrift** [comment]
everyone have it
be patient
