### ISSUE TITLE
Arms offhand trigger

### ISSUE THREAD

**Issue by Vargrift** [Valhalla-Gaming/Tracker#5071]
Hello,

Some skills on arms warrior are triggering offhand damage, which they shouldn't.
These are for example Bladestorm and Siegebraker. It's not a big amount of dmg (1-4k per hit) but still shouldn't happen.

Here are my screenshots of what recount recorded:

http://s16.postimg.org/u27z0ehfp/Wo_WScrn_Shot_040216_154618.jpg
http://s28.postimg.org/a4zxuxz7x/Wo_WScrn_Shot_040216_154615.jpg

Also don't watch my dmg because I was killing nearby critters with Bladestorm...

**Comment by Tregeta** [comment]
Dev note: Arms uses http://www.wowhead.com/spell=176289/siegebreaker for mainhand only.
Fury swings with both.

**Comment by Vargrift** [comment]
There is Storm Bolt too. Nothing should have offhand dmg on arms. I didn't find more skills bugged this way.

**Comment by Vargrift** [comment]
Hello,

please add Storm Bolt. It has offhand dmg on arms too.



2016-04-03 0:29 GMT+01:00 Tregeta <notifications@github.com>:

> Dev note: Arms uses http://www.wowhead.com/spell=176289/siegebreaker for
> mainhand only.
> Fury swings with both.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Valhalla-Gaming/Tracker/issues/5071#issuecomment-204826461>
>



-- 

Pozdrawiam,

Maksymilian Szafrański

**Comment by Moustachos** [comment]
Ref #2266
