### ISSUE TITLE
inscription wod

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#5073]
[Draenor Inscription scroll](http://www.wowhead.com/item=111923/draenor-inscription) is not giving you any WoD recipes.

![wowscrnshot_040416_074550](https://cloud.githubusercontent.com/assets/14946340/14239182/591575b0-fa39-11e5-891b-c021461e5706.jpg)

**Comment by Tregeta** [comment]
should be fixed in next update.

**Comment by Collector-Valhalla** [comment]
Still not fixed after recent update.

**Comment by Tregeta** [comment]
Found the issue, will be fixed next update

**Comment by Collector-Valhalla** [comment]
thank you :>
