### ISSUE TITLE
hunter important glyph

### ISSUE THREAD

**Issue by sausagepl** [Valhalla-Gaming/Tracker#5075]
Glyph of Aspect of the Cheetah
Requires Hunter 

Your Aspect of the Cheetah no longer causes you to be dazed when struck.  Instead, the effect is cancelled. 

its not working because you still get dazed!

**Comment by Tregeta** [comment]
Ref #4939

**Comment by sausagepl** [comment]
hi can i ask why you close a issue when its still not done?

2016-04-05 17:44 GMT+02:00 Tregeta <notifications@github.com>:

**Comment by Tregeta** [comment]
It is already reported.

**Comment by sausagepl** [comment]
Oh ok
Dňa 5.4.2016 19:15 používateľ "Tregeta" <notifications@github.com> napísal:
