### ISSUE TITLE
Paladin's Execution Sentence bug

### ISSUE THREAD

**Issue by tribaljet** [Valhalla-Gaming/Tracker#5078]
http://www.wowhead.com/spell=114157/execution-sentence

This skill causes an unending combat bug that requires players to either go through a loading screen or relog entirely.

Currently, all tier 6 talents are affected by this issue.

Additionally, the skill causes the player to constantly go in and out of combat while the skill's duration is ongoing.

**Comment by Moustachos** [comment]
This bug isn't related to any of these spells, we'll investigate though.
