### ISSUE TITLE
Glyph of Power Word: Shield

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#5082]
I'm here in shadow specialization just standing doing nothing and I've noticed that my [Power Word: Shield](http://www.wowhead.com/spell=17/power-word-shield) gives me some random absorb amounts. Only last ~19k is correct or at least tooltip has same number. Dunno if this happens in other 2 specializations. And I guess the only two things that could interfere with that spell are [Glyph of Reflective Shield](http://www.wowhead.com/spell=33202/glyph-of-reflective-shield) and maybe [Priest WoD PvP Shadow 2P Bonus](http://www.wowhead.com/spell=171146/item-priest-wod-pvp-shadow-2p-bonus).

![wowscrnshot_040716_002404](https://cloud.githubusercontent.com/assets/14946340/14334824/4e6e6cd2-fc57-11e5-9571-f6cbd77b2cf4.jpg)
![wowscrnshot_040716_002332](https://cloud.githubusercontent.com/assets/14946340/14334837/5b4ac928-fc57-11e5-9690-481884bbfe7a.jpg)
![wowscrnshot_040716_002316](https://cloud.githubusercontent.com/assets/14946340/14334846/66a4ec22-fc57-11e5-835b-097a58901577.jpg)

**Comment by Collector-Valhalla** [comment]
Same thing happens to discipline specialization. My tooltip says ~39k but sometimes I get 40k-50k shields without anything procing like intellect trinkets and stuff.

**Comment by GAMMARAYS** [comment]
It's called multistrike.

The only bug here is that the glyph should reduce the amount absorbed by the shield by the amount ot heals by.

**Comment by Tregeta** [comment]
As it appears that this is now unrelated to power word shield and more related to the glyph, changing title to fit.

**Comment by Collector-Valhalla** [comment]
Then it happens with [Glyph of Weakened Soul](http://www.wowhead.com/item=42407/glyph-of-weakened-soul) aswell.

**Comment by Collector-Valhalla** [comment]
I've checked that spell without any "shield glyphs" in shadow specialization and here are my results:

My tooltip says 23k+...
![wowscrnshot_041116_201503](https://cloud.githubusercontent.com/assets/14946340/14437613/5dcba072-0022-11e6-9ce4-6a26ea1863c8.jpg)

...and indeed I sometimes get that amount but...
![wowscrnshot_041116_201430](https://cloud.githubusercontent.com/assets/14946340/14437604/53aa4f26-0022-11e6-9939-21841cf79b2a.jpg)

...there's also this 47k+...
![wowscrnshot_041116_201359](https://cloud.githubusercontent.com/assets/14946340/14437672/acaf68c2-0022-11e6-8bcb-1e97b079f886.jpg)

...and this 61k+...
![wowscrnshot_041116_201456](https://cloud.githubusercontent.com/assets/14946340/14437667/9b7e342a-0022-11e6-80f0-8c5a5f59912b.jpg)

...here are my talents and glyphs.
![wowscrnshot_041116_201503](https://cloud.githubusercontent.com/assets/14946340/14437691/c395a7a4-0022-11e6-9696-c118e13407b8.jpg)
![wowscrnshot_041116_201507](https://cloud.githubusercontent.com/assets/14946340/14437697/cbbd452c-0022-11e6-8490-8e7775703a86.jpg)

Same thing happens in discipline specialization. With those glyph and talents...
![wowscrnshot_041116_202227](https://cloud.githubusercontent.com/assets/14946340/14437907/d4a724cc-0023-11e6-831e-f1cdb15dd4c8.jpg)
![wowscrnshot_041116_202231](https://cloud.githubusercontent.com/assets/14946340/14437909/db02b642-0023-11e6-8c18-d30082020841.jpg)

...I got most of the time correct amount of absorb...
![wowscrnshot_041116_202242](https://cloud.githubusercontent.com/assets/14946340/14437930/f2a2c1ca-0023-11e6-90b5-cc320df941a2.jpg)

...but sometimes also this without anything like trinket proccing...
![wowscrnshot_041116_202524](https://cloud.githubusercontent.com/assets/14946340/14437961/0f20f574-0024-11e6-9caf-a4ba9d98ea93.jpg)

...and I'm just in shrine in pandalandia but it happens everywhere.

**Comment by GAMMARAYS** [comment]
Jesus.

Multistrike boosts the shielding up to 60%.

The +/-1 is called a dice roll.
47k is a crit, no multistrike proc.
61k is a crit + 1 multistrike proc.

53k is a multistrike.
66k is a double multistrike proc.

As I said, the only issue is NOT with that shield. It's about the 20% of the damage absorbed that gets converted into heals. In short: overall efficiency of Power Word: Shield is reduced by 20% with the glyph active.

Reflective Shield etc, are out of the question.

**Comment by Collector-Valhalla** [comment]
Too much math for me...

Then there's an issue with multistrike not showing in combat log and stuff? It's so confusing. I reported Siegebreaker too that aparrently have similar issue. Should I make another report for multistrike or is it something known?

**Comment by GAMMARAYS** [comment]
Yes, the issue here is multistrike hits not showing up as multistrike in combat-log for non-melee damage spells.

**Comment by GAMMARAYS** [comment]
Glyph fixed next update.
