### ISSUE TITLE
Shadowy Insight

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#5084]
http://www.wowhead.com/spell=162452/shadowy-insight

Procs from [Devouring Plague](http://www.wowhead.com/spell=2944/devouring-plague) aswell. It shouldn't.

Also cooldown of [Mind Blast](http://www.wowhead.com/spell=8092/mind-blast) does not reset.

**Comment by Tregeta** [comment]
Merging from the other report of this spell #3496
