### ISSUE TITLE
Careful Aim

### ISSUE THREAD

**Issue by Trekex** [Valhalla-Gaming/Tracker#5092]
This passive does not seem to work. I'm not completely sure because I can reach 92% crit if it works and not 100% since my base % is 42%.
Anyway I tried it on Dummies with [Rapid Fire](http://www.wowhead.com/spell=3045/rapid-fire) and [Aimed Shot](http://www.wowhead.com/spell=19434/aimed-shot) didn't crit many times.
http://www.wowhead.com/spell=34483/careful-aim

**Comment by sausagepl** [comment]
Megawatt Filament
Item Level 100 

Use: Permanently attaches an electrified device to a ranged weapon, sometimes increasing critical strike by 750 for 12 sec when dealing damage with ranged attacks.

Attaching this device to a ranged weapon causes it to become soulbound.
Requires Level 91
"Everything is better when it's electrified." 

its not doing enything

**Comment by Tregeta** [comment]
@sausagepl  You need to create a separate report for this particular item.

**Comment by Trekex** [comment]
@sausagepl It's the same issue as #5016. I've added it there :)

**Comment by Moustachos** [comment]
Ref #2266

**Comment by sausagepl** [comment]
Explosive shoot stil have cd after lock and load trigers so its stil broken
and unusual
Dňa 27.4.2016 17:52 používateľ "Moustachos" <notifications@github.com>
napísal:

**Comment by Tregeta** [comment]
@sausagepl we have not updated the realm for it yet.
