### ISSUE TITLE
Laying Waste to the Unwanted

### ISSUE THREAD

**Issue by neano300** [Valhalla-Gaming/Tracker#5093]
Hello, I come to report this quest, the problem is the zone.
Video:https://www.youtube.com/watch?v=RPtWxhwbAjs&feature=youtu.be
WoWHead Link: http://www.wowhead.com/quest=10078/laying-waste-to-the-unwanted

**Comment by nuhrii** [comment]
dupl #694

**Comment by Cidragon** [comment]
Fixed in December 5th changelog
