### ISSUE TITLE
In-game shop

### ISSUE THREAD

**Issue by SloppyPuppy** [Valhalla-Gaming/Tracker#5094]
I brought an item from the shop.. and I have made the character but never loged into it before buying... so after a long time thinking I speculate thats why I haven't recived my item... As I have noticed on the shop page it says that you don't send the items to the mail anymore... but I belive thats a better option.. So please retrive my item and respond swiftly.
Thank you in Advance
-SloppyPuppy

**Comment by SloppyPuppy** [comment]
I'm sorry if I won't respond quickly as of this time I have to go to bed.
So good night and see you In the morning!

**Comment by Tregeta** [comment]
Please send myself or Warjakh a PM on the forum regarding your item that is missing.

**Comment by SloppyPuppy** [comment]
Oh Im sorry.. I have found out what was the problem and thank you for support!
I didn't know how hairlooms worked before... as last time i played was during the Catalysm.
So Thank you!

**Comment by Tregeta** [comment]
No problem ( ͡° ͜ʖ ͡°)

**Comment by SloppyPuppy** [comment]
lol that face doh x3,btw sorry for wasting your time...

**Comment by Tregeta** [comment]
No time wasted, this is what we're here for :+1:
