### ISSUE TITLE
[Spell][Paladin] Sacred Shield

### ISSUE THREAD

**Issue by lavalash551** [Valhalla-Gaming/Tracker#5101]
http://www.wowhead.com/spell=20925/sacred-shield
It shields the paladin every 6 secounds, but there are 2 things that dont work correctly. The first shield should appear after the spell is casted. Now you cast it and after 6 sec the first shield appears-thats totally wrong!
And the 2nd mistake is haste. It should decrease the time between the shields appear. At the moment the spell works as if i had no haste (0%)...means 4x a shield in 30 sec duration. With 10% haste and if point 1 would be working i should have 6 absorbing shiels in that 30 sec.

**Comment by Moustachos** [comment]
About the two "bugs" you reported:
- the fact that the shield doesn't appear instantly is intended and is the same on retail
- haste properly decreases the time between two ticks, just like on any other periodic effect

However, there was a bug with Sacred Shield: it couldn't stack with existing absorb effect (if any), it will be fixed on next update.

**Comment by Moustachos** [comment]
Ref #2266
