### ISSUE TITLE
Glyphe for feral that i cant use as feral

### ISSUE THREAD

**Issue by serenity-talador** [Valhalla-Gaming/Tracker#5103]
http://www.wowhead.com/spell=67598/glyph-of-ferocious-bite
and
http://www.wowhead.com/spell=47180/glyph-of-cat-form

I cant use them because "it's not for your specialisation" , while i'm feral, somes others player encounter the same problem.

#4175 
Not working or there is a bug on somes players

**Comment by GAMMARAYS** [comment]
This will be fixed in the next update.
