### ISSUE TITLE
Item abuse.

### ISSUE THREAD

**Issue by neano300** [Valhalla-Gaming/Tracker#5104]
Hello, I come to report this item bug, this item is only for a quest not for players on players reduce lots of damage
WoWHead Links: http://www.wowhead.com/quest=28324/studies-in-lethality

Pics:
 [img]http://i.imgur.com/E6p1aMj.jpg[/img]
 [img]http://i.imgur.com/IFYI36o.jpg[/img]

**Comment by Luminescent-Valhalla** [comment]
this would explain why some players take way less damage than others

**Comment by Tregeta** [comment]
fixed next update
