### ISSUE TITLE
[Monk] [Spell] [Windwalker] Touch of Karma

### ISSUE THREAD

**Issue by Bombrick** [Valhalla-Gaming/Tracker#5107]
Sometimes fails to reflect damage taken. (Happened after the last update)
It's acting weird at the first 3 secs or so It doesn't reflect damage and after it does or something like that please rewrite Script.

**Comment by Bombrick** [comment]
and sometimes it does 1 damage

**Comment by Luminescent-Valhalla** [comment]
Confirmed had hits over over 105K in ilvl 719 pvp gear

**Comment by Bombrick** [comment]
Why close this without answer?
