### ISSUE TITLE
Holy shield retarded dmg 

### ISSUE THREAD

**Issue by miloskovac** [Valhalla-Gaming/Tracker#5108]
Hello ppl.
Plz modify the retarded dmg and dmg proc on Holy shield. It does way too much dmg and procs on dots also (and it should only proc on blocked dmg (PHYSICAL)).
Thank you!

**Comment by lavalash551** [comment]
http://www.wowhead.com/spell=152261/holy-shield   works as it should! It increases block chance and  makes spells blockable too... so what is the problem with it?

**Comment by Collector-Valhalla** [comment]
> so what is the problem with it?

It's retarded...

Sorry, I had to hahahaha... sorry.

**Comment by Tregeta** [comment]
If you have numbers that would be immensely helpful. (Combat Log entries with time stamps)

**Comment by Luminescent-Valhalla** [comment]
i dont see a issue with it (tested using both my accounts)

`20:33:04> Your Holy Shield hit Dionysus 3778 Holy. (Critical) 
20:33:06> Your Holy Shield hit Dionysus 2519 Holy. 
20:33:08> Your Holy Shield hit Dionysus 2519 Holy. 
20:33:09> Your Holy Shield hit Dionysus 2519 Holy. 
20:33:11> Your Holy Shield hit Dionysus 2519 Holy. 
20:33:15> Your Holy Shield hit Dionysus 2519 Holy. 
20:33:17> Your Holy Shield hit Dionysus 2519 Holy. 
20:33:41> Your Holy Shield hit Dionysus 2519 Holy. 
20:33:49> Your Holy Shield hit Dionysus 2519 Holy. 
20:33:58> Your Holy Shield hit Dionysus 2519 Holy. 
20:34:10> Your Avenger's Shield hit Dionysus 7335 Holy. 
20:34:18> Your Holy Shield hit Dionysus 2519 Holy. 
20:34:24> Your Holy Shield hit Dionysus 2519 Holy. 
20:34:25> Your Holy Shield hit Dionysus 2519 Holy. 
20:34:27> Your Holy Shield hit Dionysus 2519 Holy. 
20:34:33> Your Holy Shield hit Dionysus 3778 Holy. (Critical) 
20:34:37> Your Holy Shield hit Dionysus 2519 Holy. 
20:34:37> Your Holy Shield hit Dionysus 1132 Holy. (Critical) 
20:34:40> Your Holy Shield hit Dionysus 2519 Holy. 
20:34:44> Your Holy Shield hit Dionysus 2519 Holy. 
20:34:46> Your Holy Shield hit Dionysus 3778 Holy. (Critical) 
20:34:48> Your Holy Shield hit Dionysus 2519 Holy. 
20:34:50> Your Holy Shield hit Dionysus 2519 Holy. 
20:34:55> Your Holy Shield hit Dionysus 2519 Holy. 
20:34:57> Your Holy Shield hit Dionysus 2519 Holy. 
20:34:59> Your Holy Shield hit Dionysus 3778 Holy. (Critical) 
20:34:59> Your Holy Shield hit Dionysus 2519 Holy. 
20:35:01> Your Holy Shield hit Dionysus 2519 Holy. 
20:35:05> Your Holy Shield hit Dionysus 2519 Holy. 
20:35:14> Your Holy Shield hit Dionysus 2519 Holy. 
20:35:20> Your Holy Shield hit Dionysus 2519 Holy. 
20:35:24> Your Holy Shield hit Dionysus 2519 Holy. 
20:35:25> Your Holy Shield hit Dionysus 2519 Holy. `

![wowscrnshot_041316_203546](https://cloud.githubusercontent.com/assets/13806368/14506779/68f3a012-01b7-11e6-9d3b-d21c8268bccf.jpg)

**Comment by miloskovac** [comment]
Ok, so it increases chanse of block and makes posible to block spells....
That meens a chanse to block mele and spells, not 100% block spell and dots (damage over time that paly is already have) cose it makes my affly lock practicly kill him self when fully dot a paly.
That being said, there is a dmg that i (fortunatly) have screen shot.
I will send it directly to Tregeta on forum (idk how to upload the image here).
Also that dmg can b a critical hit.....which i dont think its normal.

**Comment by Luminescent-Valhalla** [comment]
uploading images is easy on git hub open your screenshot folder and just drag and drop and it auto uploads it to github.

only issue i could find with it is the proc might be set a bit too high max damage i got it to do by having my druid dot my paladin with moonfire was 3.5k max and that was a crit.

**Comment by miloskovac** [comment]
Well i got 13.9k crit and all other 7.8k dmg on every tic on every dot i placed on him and lituraly almost killed my self with it. I sent SS to Tregeta already.

**Comment by tribaljet** [comment]
No numbers out of the ordinary happen on my characters either and as others have said earlier, magic damage can be blocked as well, this was actually extensively talked over on past issues.

**Comment by Luminescent-Valhalla** [comment]
I will confirm the part about it reflecting dots tonight reactivated retail sub so just got finish leveling paladin .
