### ISSUE TITLE
[Balance Druid] Sunfire

### ISSUE THREAD

**Issue by Doctahdre** [Valhalla-Gaming/Tracker#5113]
Moonfire doesn't turn into Sunfire when it is supposed to.

Actually Sunfire is nowhere to be found. It's not even on the Spellbook.

http://www.wowhead.com/spell=93402/sunfire#see-also-other

**Comment by Aveta** [comment]
For me it swaps properly. Make sure to relog when you change spec to Balance.
Also Sunfire doesn't appear in the spellbook until Moonfire swaps with it.

**Comment by Doctahdre** [comment]
I've tried that and it doesn't work. I even tried resetting my spec then relogged but nothing happened.

**Comment by Aveta** [comment]
Hmm, no idea. Did you clear your cache? I've had this issue for some time but one of the recent updates fixed it and clearing cache might do the trick.
After the update I've had an issue where it didn't swap until the second full cycle started but now it works fully for me, without hiccups.

**Comment by Doctahdre** [comment]
Nothing works. Sigh. I've tried everything. I even put this up on the forums and Warjakh gave me some instructions on what to do but nothing worked. Moonfire is still Moonfire no matter how many spec resets, relogs, cache deletions I do. It's sad that I can't play my favorite class and favorite spec and it seems like it's only not working for me.

**Comment by Doctahdre** [comment]
I tried using Celestial Alignment and it turns to Sunfire but when I don't use Celestial Alignment it doesn't. So weeeeiiiird.

**Comment by Doctahdre** [comment]
Okay it switches to Sunfire ONLY when I use Astral Communion to move to Solar side. Otherwise, it doesn't.

**Comment by Aveta** [comment]
Now when I'm checking it it stopped switching for me too. Bah, I don't even get peak buffs after the first one.

**Comment by Tregeta** [comment]
We have not yet managed to reproduce this. If there is any extra information you can provide such as what you were doing during the time of having it, that would be extremely helpful.

**Comment by Aveta** [comment]
I'm gonna try and record a vid, tbh it can be something present on our live server that won't trigger on test.

**Comment by Aveta** [comment]
I kinda lacked time and also changed computers, but I managed to record a vid thanks to the software already installed on my new laptop. Some time ago I made a Worgen Druid on my second account, so I figured out I could bring him to lvl 10 and record the vid on him to avoid any possible gear, glyph and talent interference.
https://www.youtube.com/watch?v=5Up0crOtWos
