### ISSUE TITLE
Portal to isle of thunder is not working. 

### ISSUE THREAD

**Issue by DXSTAR007** [Valhalla-Gaming/Tracker#5116]
A portal (Alliance) from the faction camps outside the Shado-Pan Garrison in west-central Townlong Steppes to Isle of thunder is not working. Please help fix this problem. I really want to join Raid on that island so bad.

**Comment by Tregeta** [comment]
Ref: https://github.com/Valhalla-Gaming/Tracker/issues/1815

**Comment by Collector-Valhalla** [comment]
;O

my body is ready
