### ISSUE TITLE
Mark of the Shattered Hand

### ISSUE THREAD

**Issue by Garendorf** [Valhalla-Gaming/Tracker#5118]
It still procs when you receive damage, even from creatures and not from the players.

![wowscrnshot_041716_035503](https://cloud.githubusercontent.com/assets/16792371/14584647/aced847c-0450-11e6-8741-2b69eb2e16b3.jpg)

**Comment by Tregeta** [comment]
How often? Looks like you're a monk from the stagger debuff, this could be triggering it easily as you're doing damage to yourself by not clearing your stagger.

**Comment by Aveta** [comment]
Yes, I think the reason for it is the Stagger, as it's damage done to you and the source of this damage is also coded as you.

**Comment by Garendorf** [comment]
No, it happens aswell on my warrior, is about the damage taken, like when healing were making it proc on yourself

**Comment by serenity-talador** [comment]
It proc on heals /hot , i got it with isera gift in the middle of nowhere

**Comment by Luminescent-Valhalla** [comment]
Confirmed ysera's gift (druid talent) can proc the debuff this should not
happen.

**Comment by Tregeta** [comment]
Should be fixed in next update (hopefully).
