### ISSUE TITLE
Pve gear (mythic) scaling in pvp

### ISSUE THREAD

**Issue by miloskovac** [Valhalla-Gaming/Tracker#5119]
Hello.
The pve gear is scaling in pvp (arena/bg). It doesnt show it like in pvp gear (where u can c the difference), but stats go 'up' in pvp on those pve gear.
I tested on varius items (on my lock) and all of them scale in pvp (giving more int and stamina (or other stats) then in pve.

**Comment by Tregeta** [comment]
Non-PvP gear between item levels 560 and 690 will now scale up to 690 in PvP combat.
Non-PvP gear above item level 715 will now scale down to 715 in PvP combat.
PvP gear remains unaffected and will not be capped in PvP combat.
