### ISSUE TITLE
Bandages

### ISSUE THREAD

**Issue by rawhunger** [Valhalla-Gaming/Tracker#5121]
I have noticed that bandages above Linen Bandages are not showing the amount that they are healing for.

**Comment by Tregeta** [comment]
Try disabling your damage text and re-enabling them.

**Comment by rawhunger** [comment]
I tried what you suggested, but I still don't see any text.  Nor do I see any significant healing difference between types of bandages.  Linen bandages heals for about the same as wool bandages.

**Comment by Tregeta** [comment]
Thanks for the information.

Linen bandages should heal for about 120~ over 6 seconds
Wool bandages should heal for about 287~ over 7 seconds.

More information base on these healing number can be found in a comment with the direct item links here: http://www.wowhead.com/skill=129/first-aid#comments:id=1386990

Please try checking your combat log to see if the healing is indeed correct on any of these and if possible post a screenshot for us.

**Comment by rawhunger** [comment]
My combat log is up all the time, and I only see Linen Bandages healing for anything... +20HP per tick.  None of the other bandages I have show any healing at all (I'm just up to wool ATM).

**Comment by Tregeta** [comment]
Thanks

**Comment by ATalisan** [comment]
Wool and Heavy Wool bandages are not healing at all.
Alliance Night Elf, lvl 22, Darkshore and attempted both in and out of combat.

**Comment by GAMMARAYS** [comment]
Will be fixed next update.

Some real weird code uncovers....
