### ISSUE TITLE
Grimoire of Supremancy Demons

### ISSUE THREAD

**Issue by nuhrii** [Valhalla-Gaming/Tracker#5126]
The [Fel Imp](http://www.wowhead.com/spell=112866), [Shivarra](http://www.wowhead.com/spell=112868), [Observer](http://www.wowhead.com/spell=112869), assuming [Voidlord](http://www.wowhead.com/spell=112867), [Wraithguard](http://www.wowhead.com/spell=112870), and [Abyssal](http://www.wowhead.com/spell=112921) and [Terrorguard](http://www.wowhead.com/spell=112927) under the effects of Demonic Servitude, do not use Energy as they're supposed to, but Mana instead, which doesn't allow them to use their abilities.

**Comment by Tregeta** [comment]
http://www.wowhead.com/spell=108499/grimoire-of-supremacy
