### ISSUE TITLE
Pet bug

### ISSUE THREAD

**Issue by nuhrii** [Valhalla-Gaming/Tracker#5127]
Normally you can only have one combat pet(a pet you can control) active at a time and as many guardian pets(a pet that just does its thing) you are able to summon. However as it currently stands you can only have one pet active at a time. If you summon a guardian pet it will desummoned your combat pet or your previous guardian, best example right now is [Wild Imps](http://www.wowhead.com/spell=159607), if you summon one it desummons your current combat pet demon and if you summon another Wild Imp it will desummon the first one.

**Comment by Tregeta** [comment]
Ref #2312
