### ISSUE TITLE
Grimoire of Service spell: Grimoire: Felguard

### ISSUE THREAD

**Issue by nuhrii** [Valhalla-Gaming/Tracker#5128]
The summoned [Felguard](http://www.wowhead.com/spell=111898) does cast [Axe Toss](http://www.wowhead.com/spell=89766) on summon or cast [Legion Strike](http://www.wowhead.com/spell=30213) whenever

**Comment by Tregeta** [comment]
Please make sure you have these spells active on your spell casting for your pet.

**Comment by nuhrii** [comment]
They're supposed to automatically cast these spells because of their guardian pet status, if thats what you're saying. Also they replace you're active combat pet demon too

**Comment by nuhrii** [comment]
As of Legion, Non Demonology Warlocks can learn this spell when taking Grimoire of Service, they are not supposed to
