### ISSUE TITLE
Grimoire of Service spell: Grimoire: Imp

### ISSUE THREAD

**Issue by nuhrii** [Valhalla-Gaming/Tracker#5129]
[Imp](http://www.wowhead.com/spell=111859) doesn't cast [Firebolt](http://www.wowhead.com/spell=3110) whenever, unsure if it will cast [Singe Magic](http://www.wowhead.com/spell=89808) on the caster when summoned

**Comment by Tregeta** [comment]
Please make sure you have these spells active on your spell casting for your pet.

**Comment by nuhrii** [comment]
They're supposed to automatically cast these spells because of their guardian pet status, if thats what you're saying. Also they replace your active combat pet demon too
