### ISSUE TITLE
Grimoire of Service spell: Grimoire: Voidwalker

### ISSUE THREAD

**Issue by nuhrii** [Valhalla-Gaming/Tracker#5130]
[Voidwalker](http://www.wowhead.com/spell=111895) does not cast [Suffering](http://www.wowhead.com/spell=17735) on the target when summoned, doesn't cast [Torment](http://www.wowhead.com/spell=3716) at all

**Comment by Tregeta** [comment]
Please make sure you have these spells active on your spell casting for your pet.

**Comment by nuhrii** [comment]
They're supposed to automatically cast these spells because of their guardian pet status, if thats what you're saying. Also they replace your active combat pet demon too
