### ISSUE TITLE
Grimoire of Service spell: Grimoire: Succubus

### ISSUE THREAD

**Issue by nuhrii** [Valhalla-Gaming/Tracker#5131]
[Succubus](http://www.wowhead.com/spell=111896) does not cast [Lash of Pain](http://www.wowhead.com/spell=7814) at all. Unknown if it will cast [Seduction](http://www.wowhead.com/spell=6358) on a Humanoid target on summon, but probably not.

**Comment by Tregeta** [comment]
Please make sure you have these spells active on your spell casting for your pet.

**Comment by nuhrii** [comment]
They're supposed to automatically cast these spells because of their guardian pet status, if thats what you're saying. Also they replace your active combat pet demon too
