### ISSUE TITLE
Grimoire of Service spell: Grimoire: Felhunter

### ISSUE THREAD

**Issue by nuhrii** [Valhalla-Gaming/Tracker#5132]
[Felhunter](http://www.wowhead.com/spell=111897) doesn't cast [Shadow Bite](http://www.wowhead.com/spell=54049). Probably does not cast [Spell Lock](http://www.wowhead.com/spell=19647) on summon.

**Comment by Tregeta** [comment]
http://www.wowhead.com/spell=108501/grimoire-of-service

Please make sure you have these spells active on your spell casting for your pet.

**Comment by nuhrii** [comment]
They're supposed to automatically cast these spells because of their guardian pet status, if thats what you're saying. Also they replace your active combat pet demon too
