### ISSUE TITLE
Glyph of Detox

### ISSUE THREAD

**Issue by Garendorf** [Valhalla-Gaming/Tracker#5135]
Hello, recently i've tested the glyph of detox and it doesn't clean all the poison/diseases, for example while you are against 2 dks, instead it clean only 1 and i think it doesn't heal the 4% sometimes it does heal 2% or 3%

http://www.wowhead.com/item=87899/glyph-of-detox

**Comment by Tregeta** [comment]
Detox heals your target for 4% of their maximum health when it successfully removes **a** harmful effect.

**Comment by Moustachos** [comment]
There is no bug with this glyph, it's cleaning one harmful effect and healing for 4% of max health anytime.

However, this amount can be reduced if (for example) you got a debuff reducing the healing you receive, and that's intended.

**Comment by Moustachos** [comment]
Ref #2266
