### ISSUE TITLE
Shields/Bubles

### ISSUE THREAD

**Issue by Garendorf** [Valhalla-Gaming/Tracker#5136]
While you use Guard, Sacro shield or any other kind of shield you still can take flags in bg, doesn't matter if people hits you

**Comment by forstix** [comment]
as long you can absorb all that dmg i dont see a problem and u can stun/fear him

**Comment by Garendorf** [comment]
You shouldn't be able to take the flag if someone hits you, doesn't matter if you absorb or not the damage.

**Comment by forstix** [comment]
and - https://github.com/Valhalla-Gaming/Tracker/issues/4716

**Comment by Tregeta** [comment]
should be fixed in latest update.
