### ISSUE TITLE
Druid Glyph: Glyph of Regrowth

### ISSUE THREAD

**Issue by skorge1** [Valhalla-Gaming/Tracker#5139]
The issue with http://www.wowhead.com/item=40912/glyph-of-regrowth is that it still applies heal over time effect and isn't added to the 60% crit to make 100% chance so it doesn't always crit.

**Comment by GAMMARAYS** [comment]
Will be fixed next update.

**Comment by Tregeta** [comment]
#2266

**Comment by skorge1** [comment]
When you use regrowth with the glyph it doesn't crit everytime and it is still doing heal over time.
