### ISSUE TITLE
glyph error

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#5140]
I get this error message when I try to apply glyph. I think it's a new problem after recent update.

![wowscrnshot_041916_034120](https://cloud.githubusercontent.com/assets/14946340/14625129/a6e8837e-05e0-11e6-9747-79aa30fa7a71.jpg)

**Comment by Tregeta** [comment]
Which glyph are you trying to apply?

**Comment by Collector-Valhalla** [comment]
Unlearned glyph of sha and tried to learn glyph of heavens.

**Comment by forstix** [comment]
same here

**Comment by SL-Starcaller** [comment]
Same problem here, I have only 1 glyph learned for my current spec Resto, though I am unable to fill up the other two slots.
"You may only have one glyph of the %s type"

**Comment by Garendorf** [comment]
Same goes for me, can't put minor glyphs with my warrior.

**Comment by GAMMARAYS** [comment]
Will be fixed next update - we overlooked glyphs that have no conditions.
