### ISSUE TITLE
Mythic Gear

### ISSUE THREAD

**Issue by Trekex** [Valhalla-Gaming/Tracker#5144]
Seems that Mythic gear (From BSM) is scaling to 750 in PvP and I'm not sure it should happen.
Anyway some people (I won't say from which faction most of them are from :P) are already abusing it.
Here you see Mythic equipped and PvP ilvl: http://imgur.com/a/Ifl64

In our changelog (2016.18.02.033000) I read:
"Gear below ilvl 700 & above ilvl 560 will now be scaled up to 700 in pvp combat. This scaling occurs on retail as well"

Thanks to Hnata for the collaboration :D

**Comment by miloskovac** [comment]
I noticed that also...and i reported it already..but it was dismissed. Prolly i didnt explain well...Nvm.
Gj on explaining Trekex

**Comment by Tregeta** [comment]
Ref Link: http://us.battle.net/wow/en/blog/19806402/fury-of-hellfire-62-patch-notes-6-22-2015#pvp

Level 100 Gear Scaling in PvP Combat

    Level 100 characters engaging in PvP combat now have the following gear changes.
        All gear between item levels 560 and 690 will now scale up to 690 in PvP combat.
        Non-PvP gear above item level 715 will scale down to 715 in PvP combat.
        PvP gear above item level 715 will not be capped in PvP combat.

**Comment by Tregeta** [comment]
Should be fixed now
