### ISSUE TITLE
hunter

### ISSUE THREAD

**Issue by sausagepl** [Valhalla-Gaming/Tracker#5145]
Megawatt Filament
Item Level 100 

Use: Permanently attaches an electrified device to a ranged weapon, sometimes increasing critical strike by 750 for 12 sec when dealing damage with ranged attacks.

Attaching this device to a ranged weapon causes it to become soulbound.
Requires Level 91 

so the buff is not showing up

**Comment by Trekex** [comment]
I've reported it already on #5016 yesterday :)

**Comment by sausagepl** [comment]
cool bro atleast one person who cares about hunter skills :D

slapcity in da house :D

2016-04-19 22:12 GMT+02:00 Tregeta <notifications@github.com>:
