### ISSUE TITLE
Nisha

### ISSUE THREAD

**Issue by Trekex** [Valhalla-Gaming/Tracker#5147]
This NPC flight master is double spawned at Iron Docks flight point. And Wowhead signs it at Breaker's Crown fligh point (where there is no flight master).
http://www.wowhead.com/npc=81674/nisha

![wowscrnshot_041916_182115](https://cloud.githubusercontent.com/assets/14263412/14648371/3575d43a-0662-11e6-8a58-a06bd6c1f091.jpg)

**Comment by Tregeta** [comment]
Wowhead is wrong in this case, however Nisha spawn double spawn addressed.
