### ISSUE TITLE
Heirlooms Trinkets 715

### ISSUE THREAD

**Issue by Garendorf** [Valhalla-Gaming/Tracker#5149]
Hello recently i saw that most of those 715 trinkets heirlooms from the shop procs so much, and i wonder if it is like retail or they are bugged and might get fixed, also whould like to make a question:

Why don't you remove them from the shop? they aren't supposed to by earned like that way and they are kind of op...

![wowscrnshot_041916_210825](https://cloud.githubusercontent.com/assets/16792371/14652374/4daecbee-0674-11e6-9ce7-d119563d40b5.jpg)

**Comment by Luminescent-Valhalla** [comment]
They are currently bugged they proc way too much .

**Comment by Tregeta** [comment]
All heirlooms are in the shop, procs will be adjusted however.

**Comment by Collector-Valhalla** [comment]
#4541 It basically gives it's user constant 1k+ strenght as it procs from everything.

**Comment by Tregeta** [comment]
Should be fixed next update.
