### ISSUE TITLE
Ultimatum - prot warrior passive

### ISSUE THREAD

**Issue by forstix** [Valhalla-Gaming/Tracker#5150]
<a href="http://www.wowhead.com/spell=122509/ultimatum">ultimatum</a> stay up even after one <a href="http://www.wowhead.com/spell=59035/heroic-strike">heroic-strike</a> so we can spam 100% crit heroic strike while this buff up 
ty.

**Comment by Orunla** [comment]
I have the same issue here. I can spam critical Heroic Strikes after I get one Shield Slam crit for the whole duration of Ultimatum.
