### ISSUE TITLE
Gorgrond Flytrap and Blackrock Ore

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#5151]
http://www.wowhead.com/item=109126/gorgrond-flytrap

After recent update all nodes of that herb are empty for me. Others work fine.

**Comment by Collector-Valhalla** [comment]
And it's same with blackrock ore.

**Comment by Tregeta** [comment]
Let me know if it's fixed in the next update please.

**Comment by Collector-Valhalla** [comment]
Still not fixed.

**Comment by Tregeta** [comment]
Took a while to find the error, but have located it...will need to know the exact location of the blackrock ore/true iron ore to get the correct entries.
