### ISSUE TITLE
Gronntooth war horn and similar trinkets

### ISSUE THREAD

**Issue by Bombrick** [Valhalla-Gaming/Tracker#5153]
http://www.wowhead.com/item=133595/gronntooth-war-horn
If u read the comments you will see that the 5 trinkets might drop in mythic dungeons for a low chance and for the looter's spec but didn't see it drop to anyone for now chance is around 5%-10%.

**Comment by Leondezwart** [comment]
yeah should be nice if we could get it without buying it :P but u might as well look at the procs i think its broken

**Comment by Tregeta** [comment]
Proc is already fixed in next update. Loot for these trinkets will need to be set.

**Comment by Tregeta** [comment]
Fixed next update.
