### ISSUE TITLE
Glyph of the Treant / Glyph of Stars

### ISSUE THREAD

**Issue by SL-Starcaller** [Valhalla-Gaming/Tracker#5155]
Glyph of the Treant http://www.wowhead.com/item=68039 should only give an additional shape shift form, and should be canceled once swapping to another shape shift form.

Currently one can activate this form, and shape shift into any form whilst keeping the looks of Glyph of the Treant.

This is more then "just" a visual error, since it really makes it harder to keep track of your shapeshift form whilst PVP-ing.

This also counts for glyph of stars, http://www.wowhead.com/item=44922/glyph-of-stars#comments which only should apply on your humanoid form, whilst beeing in moonkin form.

**Comment by GAMMARAYS** [comment]
Will be fixed next update (for glyph of the treant. Glyph of Stars is a totally different problem)
