### ISSUE TITLE
shadowy-insight does not procs CD of Mind Blast

### ISSUE THREAD

**Issue by SL-Starcaller** [Valhalla-Gaming/Tracker#5156]
http://www.wowhead.com/spell=162452 does not resets the CD on Mindblast on proc.

**Comment by forstix** [comment]
mind blast aren't instant by default but u got tallent call <a href="http://www.wowhead.com/spell=155246/clarity-of-power">clarity of power</a> to make it instant

**Comment by SL-Starcaller** [comment]
I know, I had a different talent (void entropy) but still gained the Mind Blast with no cd.
After changing to this talent and back to void entropy, I indeed had the 1.38 sec cast time.
I will edit the title referring to shadowy insight only, thanks.
