### ISSUE TITLE
dots while capping a base

### ISSUE THREAD

**Issue by SL-Starcaller** [Valhalla-Gaming/Tracker#5157]
Dots should not interrupt the flag capping proces especially if the applier of those is dead.

**Comment by neano300** [comment]
its funny and ugly see 5 guys try taking a  base but can't only for a dk dot :c

**Comment by Tregeta** [comment]
Tested on retail - was capping flag with Power Word: Shield up and with Shadow Word: Pain on me, with caster dead and was still getting interrupted.

**Comment by Luminescent-Valhalla** [comment]
I can confirm tregeta's report just tested in wsg on retail realm. Dots
interrupt picking up flags.
