### ISSUE TITLE
Mark of Bleeding Hollow procs

### ISSUE THREAD

**Issue by forstix** [Valhalla-Gaming/Tracker#5164]
<a href="http://www.wowhead.com/spell=173323/mark-of-bleeding-hollow">mark of bleeding hollow</a> doesn't procs from spell cast. i'm never played on retail so i'm not 100% sure it should,
ty.

**Comment by Aprophys** [comment]
Its bugged atm abd its allready reported
https://github.com/Valhalla-Gaming/Tracker/issues/5015
