### ISSUE TITLE
Glyphs problem

### ISSUE THREAD

**Issue by neano300** [Valhalla-Gaming/Tracker#5165]
Hello i found this bug about glyphs.
When you try put a glyph jump " You may only have one glpyh of the %s type.
Pic: [img]http://i.imgur.com/bBVqfim.jpg[/img]

**Comment by forstix** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/5140

**Comment by GAMMARAYS** [comment]
Will be fixed next update.
