### ISSUE TITLE
Blackout Kick -> Shuffle

### ISSUE THREAD

**Issue by Garendorf** [Valhalla-Gaming/Tracker#5167]
When you does Blackout Kick as Brew Master, you should get the Shuffle which should increase the parry 10%, actually you get the shuffle but it doesn't increase your parry.

http://www.wowhead.com/spell=100784/blackout-kick
http://www.wowhead.com/spell=115307/shuffle

![wowscrnshot_042216_043131](https://cloud.githubusercontent.com/assets/16792371/14730199/acb7d4a6-0844-11e6-9fbc-96ab5dfab530.jpg)

**Comment by GAMMARAYS** [comment]
Will be fixed next update.

**Comment by Tregeta** [comment]
#2266
