### ISSUE TITLE
[npc] Master Smith Burninate <The Thorium Brotherhood>

### ISSUE THREAD

**Issue by lavalash551** [Valhalla-Gaming/Tracker#5174]
http://www.wowhead.com/npc=14624/master-smith-burninate#starts
NPC should be not only a vendor, he should also start 2 repeatable quests for reputation farming:
http://www.wowhead.com/quest=13662/gaining-acceptance
http://www.wowhead.com/quest=7737/gaining-even-more-acceptance
Those 2 quests are missing at the moment.

**Comment by Tregeta** [comment]
Fixed next update. 

Reputation is required to be @ friendly to see these quests.
Further Gaining even more acceptance will no longer be accessible once you reach honored.
