### ISSUE TITLE
[npc] Lokhtos Darkbargainer <The Thorium Brotherhood>

### ISSUE THREAD

**Issue by lavalash551** [Valhalla-Gaming/Tracker#5175]
http://www.wowhead.com/npc=12944/lokhtos-darkbargainer
NPC is only a vendor at the moment, but should be also a quest giver for 5 repeatable quests.

**Comment by Tregeta** [comment]
Fixed next update.

Reputation is required to be @ Honored with Thorium Brotherhood to see these quests.
