### ISSUE TITLE
Vir'aani double spawns

### ISSUE THREAD

**Issue by GeneralCaveman** [Valhalla-Gaming/Tracker#5176]
![wowscrnshot_042316_194558](https://cloud.githubusercontent.com/assets/12555606/14764613/1ab32616-098c-11e6-922e-484d7dc264f6.jpg)

http://www.wowhead.com/npc=17149/viraani-raider
http://www.wowhead.com/npc=17150/viraani-arcanist

**Comment by Tregeta** [comment]
fixed
