### ISSUE TITLE
Hunter talent: Intimidate

### ISSUE THREAD

**Issue by nuhrii** [Valhalla-Gaming/Tracker#5177]
Having an Issue with learn the [Intimidate](http://www.wowhead.com/spell=19577) talent. It would reset upon logging out and logging in, to whatever talent you had before, whether it be another talent on that tier or none at all.

**Comment by Trekex** [comment]
Do you have a secondary spec with a different talent on that tier? It may cause the issue I think
If not, dunno :D

**Comment by nuhrii** [comment]
No i dont have second spec with a different talent on that tier. When i had just hit level 30 on my hunter learned, relogged, i could use that spell anymore and it would be the default to the "?" icon and if i switched it around it would go back to other other option that was last picked

**Comment by Moustachos** [comment]
Can't reproduce this bug, looks like a character-specific issue.

Closing it, please contact a GM.

**Comment by Moustachos** [comment]
Ref #2266
