### ISSUE TITLE
Herb Spawns, Item: Fel Creep

### ISSUE THREAD

**Issue by ATalisan** [Valhalla-Gaming/Tracker#5180]
Since the NPC to turn the Fel Creep into (Quest: Salve Via Herbalism) no longer exists since Cataclysm, this item needs to stop dropping from the herbs worldwide. Herb spawns known to be affected are Golden Sansam, Dreamfoil, Gromsblood, Sorrowmoss, but there may be others.

**Comment by Tregeta** [comment]
fixed next update.
