### ISSUE TITLE
Glyph of Flame Shock bug / Lightning shield bug

### ISSUE THREAD

**Issue by miloskovac** [Valhalla-Gaming/Tracker#5186]
Hello ppl.
The problem with this glyph is that it heals elemental shaman (and prolly every other spec) with all dmg done 45% of it. http://www.wowhead.com/spell=55447/glyph-of-flame-shock should heal 45% of dmg delt with flame shock dmg only and not on lava burst, lightning bolt, earth shock...and even dmg dont on lighning shield.
Also there is a problem with the Glyph of Lightning Shield (it cant b putted on any spec), not allowed even if u dont have any glyph in.
Also another bug a shaman can have only 1 major glyph at the time, every time u want to put 2nd its not allowed no matter of the glyph u want to put.

**Comment by Tregeta** [comment]
Verified the glyph of flame shock
