### ISSUE TITLE
Archaeology: Trainer Belloc  {No Interaction}

### ISSUE THREAD

**Issue by KraitX** [Valhalla-Gaming/Tracker#5200]
NPC http://www.wowhead.com/npc=47571/belloc-brightblade

Has no interaction

**Comment by nuhrii** [comment]
Close this, he's not broken, he's just finicky when trying to interact with. Unless you're refering to a different version of this NPC for the one refered here is the Archeology Trainer in Orgrimmar

**Comment by KraitX** [comment]
No problem
