### ISSUE TITLE
frostwolf orcs rep

### ISSUE THREAD

**Issue by forstix** [Valhalla-Gaming/Tracker#5203]
hello,
<a href="http://www.wowhead.com/npc=78896/maggle#drops">maggle</a> and <a href="http://www.wowhead.com/npc=78758/shiverblood-slasher#drops">shiverblood slasher</a> should give 500 rep with frostwolf orcs faction which allow us to get extra follower and right now all we can do is farm mobs that give 5-50(lvl 101 rares) which take forever...
ty.

**Comment by Tregeta** [comment]
should be fixed next update.
