### ISSUE TITLE
pet buffs

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#5207]
All hunter pet buffs should have **auto cast** option but currently only stamina one (for example bears) have it.

For sure pet buffs for crit (wolfs) and crit/mastery (spirit beasts) are without **auto cast** option.

**Comment by Bombrick** [comment]
Also boar vers buff

**Comment by Moustachos** [comment]
This is not a bug, these spells can be autocast, they work the same way on retail.

**Comment by Moustachos** [comment]
Ref #2266

**Comment by Collector-Valhalla** [comment]
They can? When I right click on them they don't have that glowing thing around that indicates auto cast. Also when I enter combat the buff isn't casted. I need to do it manually every time I summon my pet.

For me. Only bear pets with stamina buff have auto cast option.

**Comment by Bombrick** [comment]
same for my boar pet his vers buff needs to be applied manually I don't see auto cast borders around it and when I right click nothing happens also

**Comment by Moustachos** [comment]
They can't *, mistyped, sorry.

**Comment by Collector-Valhalla** [comment]
:<

**Comment by Collector-Valhalla** [comment]
I'm sorry if this is a big problem but on forum posts for current expansion (for example [skill-capped site](http://www.skill-capped.com/forums/showthread.php?28028-pet-abilities-autocast-on-off)) I can see people talking about pet buffs having auto cast option. 

Also if I remember correctly of course pet buffs were with auto cast option in Cataclysm and Mists of Pandaria expansions.

And here on Valhalla only bears stamina buff have this option. I'm very confused.

**Comment by Bombrick** [comment]
Ikr d:
