### ISSUE TITLE
Charge (Pet)

### ISSUE THREAD

**Issue by Trekex** [Valhalla-Gaming/Tracker#5218]
[Charge](http://www.wowhead.com/spell=61685/charge) is not immobilizing anyone. For the 25% damage increase I'm not sure, but I guess it's not working too

**Comment by nuhrii** [comment]
The damage increase is working, but it lasts for more than one attack?

**Comment by Moustachos** [comment]
Ref #2266

**Comment by Trekex** [comment]
It is still not immobilizing. I tested it with a running guy and he kept running

**Comment by Moustachos** [comment]
Just tested it on a running unit, it's properly immobilizing.

Maybe your target was immuned to root effects or the charge didn't fully work on this specific target but under normal circumstances it's working just fine.
