### ISSUE TITLE
Frenzy

### ISSUE THREAD

**Issue by Trekex** [Valhalla-Gaming/Tracker#5220]
[Frenzy](http://www.wowhead.com/spell=19623/frenzy) is now stacking. But it reduces attack speed of pet instead of increasing :P

**Comment by nuhrii** [comment]
If you're refering to the attack speed thats listed in the Character Screen its amount of seconds it takes to make an attack not the number of attacks in a second. Close this if thats the case.

**Comment by Trekex** [comment]
Ooooops :D 
Sorry
