### ISSUE TITLE
Hunter: Aspect of the Cheetah/Pack

### ISSUE THREAD

**Issue by nuhrii** [Valhalla-Gaming/Tracker#5237]
http://www.wowhead.com/spell=5118
http://www.wowhead.com/spell=13159
The daze applied when hit while these abilities are active are multiplicative rather than additive, so your speed goes down to 39% rather than 60%.

**Comment by Moustachos** [comment]
It's not a bug, that's the same on retail.

**Comment by Moustachos** [comment]
Ref #2266
