### ISSUE TITLE
Rogue / Deathnote

### ISSUE THREAD

**Issue by roguetwinky** [Valhalla-Gaming/Tracker#5242]
1st of all i found vanish is not working correctly...u can vanish but it does not let u stealth for 2 seconds as it says actually if you use vanish  you may get out of stealth after using it... second is smoke bomb and it is not working at all ... and evasion it gives  99.8 % not 100% ... and i feel rogue damge is  low

**Comment by Trekex** [comment]
Smoke Bomb is already reported here #2684

**Comment by Tregeta** [comment]
Vanish Ref #2841, #3136

**Comment by Moustachos** [comment]
Ref #2266
