### ISSUE TITLE
Hunter: Focus Fire

### ISSUE THREAD

**Issue by nuhrii** [Valhalla-Gaming/Tracker#5245]
http://www.wowhead.com/spell=82692
Restoring an inconsistance amount focus not equal to the amount is listed.

**Comment by Moustachos** [comment]
The amount is just fine, 6 Focus per Frenzy stack consumed for the pet.

**Comment by Moustachos** [comment]
Ref #2266

**Comment by nuhrii** [comment]
Reopen this i was wasn't clear about it, would sometimes restore an inconsistent amount of focus. Sometimes i'll get all the focus, sometimes i'll get some focus, and sometimes ill get no focus. Once i used up 5 stacks of frenzy and got 7 focus.
