### ISSUE TITLE
Rogue / Deathnote

### ISSUE THREAD

**Issue by roguetwinky** [Valhalla-Gaming/Tracker#5256]
hello again.. i found new bugs latley... 1st is  my Rupture ability ... it says it does 21k damge  over 24 secs... if we calucalte this it means 900 dmage per 1 sec... but it does only bleed 300 per sec which = in 24 ....12k damge.... second is my Evenom it should does 18k damge as it says but it does only 1 damge + there are 2 talents for lvl 100 (shodow Rflection .. .it does not work at all ... and Venom rush it gives extra energy but it does not increase any energy generation rate) and please look up for assassination spec damge :) ... thx

**Comment by Tregeta** [comment]
Can you provide links from wowhead for logging purposes please?

**Comment by roguetwinky** [comment]
http://www.wowhead.com/spell=1943/rupture
http://www.wowhead.com/spell=32645/envenom
http://www.wowhead.com/spell=152151/shadow-reflection
http://www.wowhead.com/spell=156719/venom-rush

**Comment by Tregeta** [comment]
Thanks

**Comment by Tregeta** [comment]
Closing since there are duplicates, References
Rupture - #3397
Envenom - #4178, #4547
Shadow Reflection - #3168
Venom Rush - #1333
