### ISSUE TITLE
[brewmaster] keg smash

### ISSUE THREAD

**Issue by Max-Valhalla** [Valhalla-Gaming/Tracker#526]
"http://www.wowhead.com/spell=121253/keg-smash
how it should work: dealing [14.5 * ((1.0 * (1 + $versadmg)) * (0.857143 * (Mainhand Min DPS + 1 * (Offhand Min DPS /2)) + Attack power / 3.5 - 1))] to [14.5 * ((1.0 * (1 + $versadmg)) * (0.857143 * (Mainhand Max DPS + 1 * (Offhand Max DPS /2)) + Attack power / 3.5 + 1))] damage to all enemies within 8 yards and reducing their movement speed by 50% for 15 sec. Generates 2 Chi.

what happens: It slows all enemies within 8 yards. Does 1 dmg (2 crit) and doesnt generate any chi!"

**Comment by HSklaWe** [comment]
The Problem still exists...fighting "without" this skill is very bad :(
