### ISSUE TITLE
kill command

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#5264]
I have no idea why (yet) but "sometimes" (it's fairly rare) Kill Command do nothing. Pet goes and attacks with all his abilities but _"I can't see that spell animation, hear sound"_ (**EDIT**: that part is wrong I actually see spell animation but still... ability does nothing), see enemy's HP bar going down or anything in combat log even tho Kill Command goes on cooldown. 

I think it happens a little more often when you engadge/aggro enemy with Kill Command. 

www.wowhead.com/spell=34026/kill-command

**Comment by Collector-Valhalla** [comment]
Actually it's not that rare. More or less 50% of Kill Commands do nothing.

Anyone have same issue? Cause I have no clue why it happens.

**Comment by Collector-Valhalla** [comment]
It also often happens when you are in line of sight (to your target) but your pet isn't.

**Comment by nuhrii** [comment]
This problem seems to have fixed itself in Legion but the damage it deals is much lower
