### ISSUE TITLE
[Hunter]Exotic Munitions - Poisoned Ammo damage stacking

### ISSUE THREAD

**Issue by Aveta** [Valhalla-Gaming/Tracker#5266]
![wowscrnshot_050316_134330](https://cloud.githubusercontent.com/assets/14302942/14982908/337192f4-113a-11e6-9bf3-560b216706ac.jpg)
![wowscrnshot_050316_141410](https://cloud.githubusercontent.com/assets/14302942/14982907/336ac1fe-113a-11e6-9a5a-8a0e1b52c11a.jpg)
http://www.wowhead.com/spell=170661/poisoned-ammo
I'm fairly sure it's not supposed to stack up THIS high. It's possible to get more than 1mil dmg rolling with enough autoattacks.
Edit: It happens on all specs, but for Survival Poisoned Ammo dot and Serpent Sting are replacing each other, which I'll report in another issue.  At first I thought it happens only for Marksman.

**Comment by Trekex** [comment]
Well I reached 1 billion :)
What I noticed is that it does not stack linearly, but kinda multiplicatively/exponentially
Funny indeed :P
