### ISSUE TITLE
[Hunter]Glaive Toss range

### ISSUE THREAD

**Issue by Aveta** [Valhalla-Gaming/Tracker#5267]
http://www.wowhead.com/spell=117050/glaive-toss
Tooltip says nothing about minimal range of this spell, but when I'm at less than 10 yards range then it says "Target too close" on the screen.
![wowscrnshot_050316_142455](https://cloud.githubusercontent.com/assets/14302942/14983070/1c1ad2ea-113b-11e6-8c2c-fcf9c0c1e90c.jpg)

**Comment by Moustachos** [comment]
That's not meant to happen on retail but due to the way we scripted that spell, allowing to use it within a smaller range could have caused undefined behavior or even crashes.

So it will stay as it is.

**Comment by Aveta** [comment]
I see, thanks for explanation x)
