### ISSUE TITLE
pet panel

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#5270]
Sometimes it shows correct amounts and sometimes it doesn't. No idea why.

![wowscrnshot_050316_200024](https://cloud.githubusercontent.com/assets/14946340/14993144/c78baf4a-1169-11e6-8fbc-7898f6e0ee96.jpg)

**Comment by Luminescent-Valhalla** [comment]
i did a bit of testing this morning comparing lvl 1 human females on retail to Valhalla i can confirm pets are not working as intended i will upload a video with a side by side of retail and Valhalla later this evening to show my findings.
