### ISSUE TITLE
[Quest] Altar-Altercation 

### ISSUE THREAD

**Issue by Garendorf** [Valhalla-Gaming/Tracker#5273]
Hello, aparently with the last update this quest became bugged, and all the chars below 90 that must do it now, wont be able to complete it, you escolt ariok to the altar, you destroy the orbs the cinematic with kilrogg appears ariok jump in the blood thingy and then he fight agains the orcs of kilrogg, but the quest doest get completed.
http://www.wowhead.com/quest=34423/altar-altercation

**Comment by Efereon** [comment]
i have the same problem. The issue is that when you go with ariok to the altar, the game does not recognize the action

**Comment by Aveta** [comment]
Can something be done about it? It's impossible to go to Draenor because of this bug.

**Comment by Valhalla-Gaming** [comment]
Fixed
