### ISSUE TITLE
honor hold debuff

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#5283]
I get this guard's mark in honor hold. Also sometimes all those flying guards are "trying" to kill meh. :<

![wowscrnshot_050416_181429](https://cloud.githubusercontent.com/assets/14946340/15020898/5d7269e4-1224-11e6-804d-363c2ab50ad5.jpg)

**Comment by Aveta** [comment]
Same thingy happens in Thrallmar. It's puzzling xd

**Comment by Collector-Valhalla** [comment]
Actually it happens in all quest hubs with guards in outlands.

**Comment by Collector-Valhalla** [comment]
Sometimes those guards follow you. Don't attack because are friendly but it makes you stuck in combat.

![wowscrnshot_050516_003025](https://cloud.githubusercontent.com/assets/14946340/15054566/6b049eda-1308-11e6-8d60-fb82808a7cfe.jpg)

**Comment by Braemen** [comment]
Same happens to me... Really frustrating having to re-log because of combat

**Comment by Traveler-Valhalla** [comment]
It's not happening to me anymore so I GUESS it is fixed now.

???

**Comment by Traveler-Valhalla** [comment]
no longer an issue
