### ISSUE TITLE
pet underground

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#5284]
When you mount and dismount near a mountain or some hill your pet will be spawned somewhere deep under textures.

![wowscrnshot_050416_162406](https://cloud.githubusercontent.com/assets/14946340/15021000/c5343f76-1224-11e6-8e21-919e1519ec26.jpg)

**Comment by Trekex** [comment]
And pet can still pass walls and similar as reported in #3099
I think it's related?
