### ISSUE TITLE
steady focus

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#5285]
www.wowhead.com/spell=177667/steady-focus

Doesn't work for beast mastery hunters with their cobra shot (so i guess for survival aswell).

**Comment by Trekex** [comment]
I get the buff when using them twice (In BM). Not checked if the buff applies anything tho

**Comment by Collector-Valhalla** [comment]
Works indeed. I'm sorry for false report.
