### ISSUE TITLE
felwood quests 

### ISSUE THREAD

**Issue by sandi7** [Valhalla-Gaming/Tracker#5288]
navarx's gambit is bugged you were supposed to kill Navarx when you accept this quest but he is still a friendly target so i can't kill him. Please fix this

**Comment by Luminescent-Valhalla** [comment]
[http://www.wowhead.com/quest=28264/navaraxs-gambit](url)

Please add links to the quests to make it easier for the devs.

**Comment by Trekex** [comment]
Already in #1550
