### ISSUE TITLE
Quête altercation à l'autel

### ISSUE THREAD

**Issue by kogatana** [Valhalla-Gaming/Tracker#5295]
Bonjour,
La quetê "Altercation à l'autel" bug ce qui me bloque et m’empêche d'obtenir d'autre quête pour sortir de la zone de l'assaut sur la porte des ténèbres.

**Comment by Luminescent-Valhalla** [comment]
[www.wowhead.com/quest=34423/altar-altercation](url)

Please add links from wowhead to make it easier for the devs

**Comment by Trekex** [comment]
Lumi your link seems not to work.

**Comment by kogatana** [comment]
http://fr.wowhead.com/quest=34817/altercation-a-l-autel

**Comment by Luminescent-Valhalla** [comment]
thanks for the update Trek either way  This quest was marked obsolete by Blizzard and cannot be obtained or completed. (meaning quest should not be able to be picked up.)

Translation for original poster : 


merci pour la mise à jour Trek de toute façon Cette quête est marquée comme obsolète par Blizzard et ne peut être obtenue ou accomplie . ( Quête signifiant ne devrait pas être en mesure d' être ramassé. )

( Traduit en utilisant Google Translate )

**Comment by Aveta** [comment]
The French version seems to be old. http://www.wowhead.com/quest=34423/altar-altercation is still a valid and non-obsolete quest as it belongs to Draenor introductory questline before you land in Shadowmoon Valley or Frostfire Ridge depending on your side.

**Comment by Luminescent-Valhalla** [comment]
@Aveta  Well spotted there, I can confirm this quest still exists on retail as you can see below the character shown below on kel'thuzad is 20 days old.
![2016-05-05_13-15-52](https://cloud.githubusercontent.com/assets/13806368/15043302/af622556-12c3-11e6-8d1f-75af0eb4edeb.jpg)

used  /script print(IsQuestFlaggedCompleted(34423)) to check completion of the quest on retail servers please ignor my last comment as i was using information obtained from the french link provided.

**Comment by Luminescent-Valhalla** [comment]
#5273

**Comment by kogatana** [comment]
petite vidéo d'explication du bug

https://youtu.be/MzpgvDLWKGg

**Comment by Luminescent-Valhalla** [comment]
@kogatana  the video is private so can not be viewed.

**Comment by kogatana** [comment]
Video Corriger

**Comment by Valhalla-Gaming** [comment]
Fixed
