### ISSUE TITLE
[npc] Ragnaros

### ISSUE THREAD

**Issue by lavalash551** [Valhalla-Gaming/Tracker#5303]
http://de.wowhead.com/npc=11502/ragnaros
The script of his summon works perfect. You talk to Executus and he summons Ragnaros BUT after Ragnaros has killed Executus he is targetable, but not attackable.He has got the wrong flag after the script.
![wowscrnshot_050516_160753](https://cloud.githubusercontent.com/assets/16776049/15045713/61f187da-12dc-11e6-9a60-9e0cf7851359.jpg)

**Comment by SloppyPuppy** [comment]
Wait,you closed my issue request,does that mean you just aint gonna care to fix it? lele
