### ISSUE TITLE
Horn of Winter Death Knight Spell

### ISSUE THREAD

**Issue by KraitX** [Valhalla-Gaming/Tracker#5308]
I just used this spell and it seems not be working, I checked my stats and also the buff icon is not present in the upper right corner.

**Comment by Aprophys** [comment]
Ur buffed by a druid? the buffs dont stack

**Comment by KraitX** [comment]
Thank You Aprophys, I was in a party with friend offline, Left party and it is working now

**Comment by KraitX** [comment]
AS soon as you join a party this buff vaishes, when you leave party it comes back, and this is with online people in party
