### ISSUE TITLE
Not fair

### ISSUE THREAD

**Issue by LeMiNaTiK** [Valhalla-Gaming/Tracker#5314]
Character named Fdisti is level 10, he somehow did a quest, and instantly got to level 100, it's not really fair to the community so do something about it

**Comment by serenity-talador** [comment]
Are you sure He doesnt pay his lvls ? because you can by purchasing levels in the store..

**Comment by 90isti90** [comment]
i was troling hi a litel  i was lvl 99  and lvld to 100 he askd  how i did it ,teld him its a secret and he reported ,he just dos not understand jokes ,and cuz of this report he got kickd from the guild

**Comment by LeMiNaTiK** [comment]
I can take a joke, dark humor is my sh*t, but telling its a secret and for 200k gold you would tell me is not a joke, I don't see humor there, and I told you I was gonna report you, you told me to do it, I did, and you told me it was a 'prank' after I did it, and you got surprised that I reported you

**Comment by Tregeta** [comment]
So is this an issue or not?

**Comment by Collector-Valhalla** [comment]
just a prank

:'D
