### ISSUE TITLE
Deadly Poison

### ISSUE THREAD

**Issue by ATalisan** [Valhalla-Gaming/Tracker#5316]
Orc rogue at level 14 - Deadly Poison doesn't appear to apply when I have either one of my one handed weapons equipped to the main hand
Copper Dagger
Harpy Wing Clipper
I have a well-fed buff up, but the poison is not showing with it. Getting into some test combats and the poison never applies.

**Comment by ATalisan** [comment]
Logging and coming back hours later seemed to fix it.

**Comment by Aveta** [comment]
I heard about a bug that also applies on retail that poisons can randomly drop off. Best case to do is to always check the buff bar. x)
