### ISSUE TITLE
mana regen

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#5317]
I think there's something wrong.

![wowscrnshot_050716_182106](https://cloud.githubusercontent.com/assets/14946340/15093211/9dcd552c-1480-11e6-9b7e-bb1b879bf1e8.jpg)

**Comment by Trekex** [comment]
Is it visual or it restores a huge amount of mana for real?

**Comment by Collector-Valhalla** [comment]
for real

**Comment by forstix** [comment]
all good with shadow look like disc problem

**Comment by Collector-Valhalla** [comment]
https://valhalla-realms.com/forum/viewtopic.php?f=28&t=4842

It's same for resto druids.

**Comment by Bombrick** [comment]
Same for mistweaver monk

**Comment by Bombrick** [comment]
Alright from what I've seen in pvp this issue is for all Healer specs.

**Comment by Braemen** [comment]
It's funny that "shhhhh" in chat :smile:

**Comment by GAMMARAYS** [comment]
Going to close this as this was an issue on the WoD realm; Legion has removed spirit, likely eliminating this bug.
