### ISSUE TITLE
priest critical heals

### ISSUE THREAD

**Issue by forstix** [Valhalla-Gaming/Tracker#5323]
<a href="http://www.wowhead.com/spell=2061/flash-heal#changelog">flash heal</a> always heal the same no matter criti or not, i think it always heal as crit, same with heal and holy nova 
ty.
pic:
![wowscrnshot_050916_103855](https://cloud.githubusercontent.com/assets/17231331/15106548/dabc7c12-15d2-11e6-94a5-3369638ff333.jpg)

edit: all good with shadow spec healing.

**Comment by Collector-Valhalla** [comment]
that is normal for discipline priest?

http://www.wowhead.com/spell=47515/divine-aegis

"Critical heals and their multistrikes **create a protective shield** on the target, absorbing 100% of the amount healed, **instead of healing for twice as much**."

**Comment by forstix** [comment]
as u can see tooltip say 23k heal and it does 42k
