### ISSUE TITLE
Devilosaur

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#5330]
have both bite and claw. should have only bite.

![wowscrnshot_050916_201748](https://cloud.githubusercontent.com/assets/14946340/15123266/5bacf43c-1623-11e6-830c-78504e6afd03.jpg)

**Comment by Moustachos** [comment]
Mine only has Bite, which pet specialization? Do you have Adaptation talent?

**Comment by Collector-Valhalla** [comment]
I'm at level 92. Pet was in tenacity because of some bug and now is in ferocity spec. Checked him right now still have both abilities.

http://www.wowhead.com/npc=70005/young-primal-devilsaur is the one I tamed.

**Comment by Moustachos** [comment]
Just tried to tame the same one as you, it also only has Bite, not Claw.

As it seems to be a character-specific bug, I'm closing the issue and I suggest you to PM someone with a DB access (ie: Max), so that he can remove this spell from DB for your pet.

**Comment by Moustachos** [comment]
Ref #2266
