### ISSUE TITLE
mounted speed

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#5347]
sorry in advance if this is false report

http://www.wowhead.com/spell=32223/heart-of-the-crusader
http://www.wowhead.com/spell=51986/on-a-pale-horse

Should increase mounted speed by 20% but it currently increases it by 40%. From basic 200% speed as retri paladin I went to 240%. Flight speed is at 496% if I remember correctly.

**Comment by nuhrii** [comment]
It should be noted that all movement speed modifiers are additive with the advent of Patch 6.0.2
http://us.battle.net/wow/en/blog/15682579/#movement_speed
