### ISSUE TITLE
hammer of wrath

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#5348]
sorry in advance if this is false report

http://www.wowhead.com/spell=24275/hammer-of-wrath

Does not grant you holy power if you kill your target with it. It should (???).

**Comment by Collector-Valhalla** [comment]
it's not generating holy power at all :<

**Comment by Laevoth** [comment]
I believe in Legion, Hammer of Wrath was removed. This issue now may be a non-issue.
