### ISSUE TITLE
Quest: Hidden Treasures

### ISSUE THREAD

**Issue by ATalisan** [Valhalla-Gaming/Tracker#5353]
Quest is marked as obsolete by blizzard

**Comment by Trekex** [comment]
This quest does not seem to be marked as obsolete
http://www.wowhead.com/quest=27391/hidden-treasures
Where did you find it's obsolete?

**Comment by ATalisan** [comment]
Wowhead
http://www.wowhead.com/quest=5942/hidden-treasures
Though to be honest, I'm not sure what of the old wow reference sites are up to date

**Comment by Trekex** [comment]
The one you linked has been removed with Cataclysm. Anyway we have the right one in game :)
Closing
