### ISSUE TITLE
glyph spec

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#5355]
You can't apply glyphs (only minor I think) that require certain specialization. For example as retribution paladin I can't learn/use those in pic below.
![wowscrnshot_051316_181915](https://cloud.githubusercontent.com/assets/14946340/15254736/977522a6-1938-11e6-80a4-ebff178d36ad.jpg)

EDIT: It applies to major aswell altho I have 2 other spec glyphs learned so dunno what happened there.
![wowscrnshot_051316_184103](https://cloud.githubusercontent.com/assets/14946340/15255120/6259dc40-193a-11e6-85d1-b297aa974a2a.jpg)

**Comment by Collector-Valhalla** [comment]
www.wowhead.com/spell=54927/glyph-of-avenging-wrath
http://www.wowhead.com/spell=57979/glyph-of-winged-vengeance
www.wowhead.com/item=80584/glyph-of-the-falling-avenger

these are the glyphs i can not learn/use for sure

**Comment by Aveta** [comment]
It's an issue with all glyphs useable by two specs. Universal and single-spec glyphs are fine.

**Comment by Traveler-Valhalla** [comment]
Glyphs are different (only visual/cosmetic) in Legion so there's no issue.
