### ISSUE TITLE
Divine Purpose

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#5357]
http://www.wowhead.com/spell=86172/divine-purpose

I asked in world chat and according to players it is working but I've killed hundreds mobs and it didn't proc at all from templar's verdict, word of glory or divine storm.

EDIT: Attacked training dummy for 15 minutes with not a single proc of divine purpose. Clearing cache and such didn't help.

**Comment by Tregeta** [comment]
Try resetting your talents and re-selecting it.

**Comment by Collector-Valhalla** [comment]
Did that too still nothing. I'll will try that talent again when I get to lvl 100.

**Comment by Collector-Valhalla** [comment]
Doesn't work at level 100. Resetting talents, glyphs, clearing cache doesn't help.

And shouldn't Divine Purpose tooltip change with Final Verdict talent? Currently with that talent tooltip still says that procs from Templar's Verdict.

Anyway, I have no idea why it doesn't work for me.
