### ISSUE TITLE
tooltip from chat

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#5360]
Tooltip for spells etc. linked in chat have wrong numbers. Example here is http://www.wowhead.com/spell=76672/mastery-hand-of-light . Chat tooltip shows 0.0% while tooltip from character screen shows 17.0%.

![wowscrnshot_051316_211728](https://cloud.githubusercontent.com/assets/14946340/15259242/57d81a96-1950-11e6-9962-ed3648ce0d1e.jpg)

**Comment by GAMMARAYS** [comment]
Not a bug.

**Comment by Trekex** [comment]
![wowscrnshot_051416_144507](https://cloud.githubusercontent.com/assets/14263412/15268527/9573d1b4-19e2-11e6-82a9-1af520e42e3a.jpg)
My passive is useless if it increases stats by 0%
