### ISSUE TITLE
druids ferals , dps amount

### ISSUE THREAD

**Issue by serenity-talador** [Valhalla-Gaming/Tracker#5375]
First sorry if it's not the place to ask that :/

But since the druid is likely all debug it's seems my druid is weak on dps amounts

With 691ilvl mostly pve i struggle to kept a correct dps amount face to other classes even with less ilvl and on single target , i'm able to dps at like 20K /s i was wondering if it's normal 

i followed guide and i do correctly my cycle. 
i can provide screenshot if needed 

Thanks for your work :)

**Comment by Aveta** [comment]
Feral is more of a burst spec, unleashing big amounts in short amount of time. It's weaker when it comes to sustained, long-term dps. It's also a single-target spec mostly. So yes, your dps will be weaker on packs/trash and it will be better on shorter single target fights.
After all there's a reason on retail Feral is both one of the best pvp specs and not-so-great in pve.

**Comment by serenity-talador** [comment]
okay thx , so i close the issue then
