### ISSUE TITLE
Inscription Research: Shimmering Ink

### ISSUE THREAD

**Issue by ATalisan** [Valhalla-Gaming/Tracker#5377]
While using Research: Shimmering Ink
I reached skill level 375
And the research yielded:
You have learned how to create a new item: Research: Ink of the Sea.
instead of a a Glyph

**Comment by Aveta** [comment]
When you reach skill level 375 you automatically get Ink of the Sea research, so I'm not sure if it's a bug.

**Comment by Tregeta** [comment]
DB shows this spell is not learnable through the research
