### ISSUE TITLE
Stealth not working?

### ISSUE THREAD

**Issue by Ichaflash** [Valhalla-Gaming/Tracker#5378]
Activating stealth gives me the "stealth" buff but doesn't change my animations, make me invisible, slow me down, or change my action bar to the stealth skills bar, mobs aggro as if I wasn't in stealth, I know it's a bug because the stealth icon changes, I can click the icon and stealth will enter cooldown as normal.

**Comment by Aveta** [comment]
Do you have Subtrefuge as your level 15 talent or Glyph of Stealth as one of your glyphs?

**Comment by Aveta** [comment]
Just checked to be sure, Stealth works properly, so it must be one of those things.
