### ISSUE TITLE
divine storm

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#5387]
www.wowhead.com/spell=53385/divine-storm

Description says that it deals damage to **ALL** targets but currently there is a limit of 5.

**Comment by Luminescent-Valhalla** [comment]
Confirmed test on Kel'Thuzad US one cast of divine storm hit 16 targets total.

![2016-05-16_21-06-16](https://cloud.githubusercontent.com/assets/13806368/15302301/3449bcb8-1baa-11e6-8ad9-b01f4fff0421.png)
