### ISSUE TITLE
[priest] [spell] - Divine Aegis

### ISSUE THREAD

**Issue by forstix** [Valhalla-Gaming/Tracker#5390]
<a href="http://www.wowhead.com/spell=47515/divine-aegis#comments">Divine-Aegis</a> absorb way too much.
 i heal 42k flash with normal heal ( non crit) and then when i crit i healed for 42k and get shield of 80k i'm not 100% sure how it spell should works but this sound way too much 
pic:
![wowscrnshot_051816_004427](https://cloud.githubusercontent.com/assets/17231331/15340491/75717206-1c92-11e6-8a9b-05cf30b7b65d.jpg)

and one more thing as i saw in this spell comments this should stack untill 40% of the priest max health and as u can see in the combat log after very lucky crits i got 182k shield while i got only 303k health
ty.

**Comment by Tregeta** [comment]
The data from that comment is very old, back from MoP time.

**Comment by forstix** [comment]
couldn't find anything updated if someone can help that whould be great, i'll keep looking anyway...

**Comment by forstix** [comment]
no longer ingame
