### ISSUE TITLE
Monk Spell: Gift of the Ox

### ISSUE THREAD

**Issue by llamalama** [Valhalla-Gaming/Tracker#5394]
http://www.wowhead.com/spell=124502/gift-of-the-ox

The spheres it summons auto heal you after a little bit if you are standing close enough instead of when you walk through them.

**Comment by Moustachos** [comment]
This isn't a bug, you can't either "trigger" the orb by walking through it on retail.

But I agree that the spell's description is misleading.

**Comment by Moustachos** [comment]
Ref #2266

**Comment by llamalama** [comment]
http://www.icy-veins.com/wow/brewmaster-monk-pve-tank-rotation-cooldowns-abilities

"Thanks to Gift of the Ox, a passive ability, you have a chance to summon a healing sphere each time you deal damage with an autoattack multistrike. These healing spheres persist on the ground around you, and moving over them causes them to be consumed, healing you.
You should make it a habit to pick up these spheres whenever you need extra healing. If the spheres expire without being consumed, they will do their healing to you automatically, provided that you are in range of them."
