### ISSUE TITLE
[FDruid][Skill] Cyclone

### ISSUE THREAD

**Issue by CageValhalla** [Valhalla-Gaming/Tracker#5398]
After using finishing move one would get 20% chance for each combo point to get next NAture spell instant cast. It doesnt work for Cyclone.

**Comment by Collector-Valhalla** [comment]
It's not for all nature spells. Description of [Predatory Swiftness](http://www.wowhead.com/spell=69369/predatory-swiftness) says: 
_"Your finishing moves have a 20% chance per combo point to make your next **Healing Touch**, **Entangling Roots**, or **Rebirth** instant, free, and castable in all forms."_

This ability worked for nature spells before patch 5.0.1.
