### ISSUE TITLE
[FDruid][Talent] Faerie Swarm

### ISSUE THREAD

**Issue by CageValhalla** [Valhalla-Gaming/Tracker#5399]
Doesnt work at all.

**Comment by Tregeta** [comment]
More information please.

**Comment by Collector-Valhalla** [comment]
Slow effect works. I don't know about invisibility part. But if I remember correctly priests could still use spectral guise (invisibility) with this debuff on 'em. So maybe that doesn't work.

**Comment by forstix** [comment]
it works on priest too, just checked it.

**Comment by CageValhalla** [comment]
I tried it many times, it wont cast at all.
