### ISSUE TITLE
[Searing Gorge][Horde/Alliance] Quest: Lunk's Task 

### ISSUE THREAD

**Issue by JaakkoSoini** [Valhalla-Gaming/Tracker#5408]
http://www.wowhead.com/quest=27956/lunks-task

This quest can be completed, but it cannot be turned in for the reward. 

The NPC who should accept the quest turn-in after collecting the required items, is not in the camp (where the quest completion marker points to). I cannot find the NPC anywhere in Searing Gorge.

**Comment by Trekex** [comment]
Already in #3970 and #2542
