### ISSUE TITLE
Rogue Mutilate

### ISSUE THREAD

**Issue by Bombrick** [Valhalla-Gaming/Tracker#5417]
Doesn't give two combo points after being used.

**Comment by Aveta** [comment]
It gives two properly though? The only two possible cases when it wouldn't is one strike missing/being parried or being at four combo points.

**Comment by Moustachos** [comment]
Works fine as of current version, could you provide your talents / glyphs / stuff or anything that would have an effect on Mutilate?

**Comment by Bombrick** [comment]
I have just created a blood elf and leveled it to 10  that time multilate wasn't giving cps.

**Comment by Moustachos** [comment]
Just tested it on level 10 blood elf like you and Mutilate properly generates 2 CP, so it's likely an isolated character issue.

**Comment by Moustachos** [comment]
Ref #2266

**Comment by Bombrick** [comment]
@Moustachos  It isn't working! I tried it on  another charcter it didn't work! also I asked a level 100 if It's working he told me It's bugged and rarely gives cp points Please look into this

**Comment by Aveta** [comment]
I main a rogue on this server from pretty much the time I started (10 months ago) and Mutilate ALWAYS gave me proper cp. When I get home tomorrow I'll check it, but for me it was never an issue

**Comment by Bombrick** [comment]
@Aveta  I asked another rouge it didn't give him two cps at all any time.

**Comment by Aveta** [comment]
Returned home and checked. Mutilate gave me 2 CP all the time. Can give a record if needed.

**Comment by Tregeta** [comment]
Reset your talents and clear your cache @Bombrick

**Comment by Bombrick** [comment]
@Tregeta I know the issue now If you oneshot an mob with mutilate it won't give you combo points but if you hit it without oneshoting it with mutilate it will give you 2 cp the issue isn't big but It's bad for low levels.
