### ISSUE TITLE
Shattrath Quest: City of Light

### ISSUE THREAD

**Issue by ATalisan** [Valhalla-Gaming/Tracker#5418]
This quest does not appear to be available from Archmage Khadgar
to a level 66 Night Elf Druid or a level 66 Blood Elf Mage
Which appears to mean that Allegiance to the Scryer or Aldor quests are not available either.

**Comment by Aveta** [comment]
You need to talk to a Haggard War Weteran first who will send you to A'Dal. After this quest is completed, City of Light quest is available.
http://www.wowhead.com/npc=19684/haggard-war-veteran

**Comment by Tregeta** [comment]
As Aveta has explained.
