### ISSUE TITLE
[Rogue]Anticipation related bugs

### ISSUE THREAD

**Issue by Aveta** [Valhalla-Gaming/Tracker#5424]
1)Mutilate doesn't give any stacks of Anticipation. Only Dispatch does so.
2)Anticipation stacks are supposed to be turned into combo points on every CP consuming offensive move. Currently it doesn't happen on Rupture and Kidney Shot.
3)Ambush grants only one stack of Anticipation when it's a power that grants two combo points. Idk, maybe it's working as intended but better safe than sorry.
With Subtlety, aside from possibly Ambush it works all fine.

**Comment by Moustachos** [comment]
1) and 2) will be fixed on next update

I must check for 3) on retail but PTR is down at the moment, so I'll check (and fix if necessary) in the upcoming days.

**Comment by Moustachos** [comment]
Ref #2266
