### ISSUE TITLE
Warlock Pet Bar is missing

### ISSUE THREAD

**Issue by Drakonys** [Valhalla-Gaming/Tracker#5429]
I've just started a Warlock i can't see Pet action bar.. i reached even lvl 10 but nothing, script this.
Thank You

**Comment by Tregeta** [comment]
Please relog, and clear your cache folder located in your WoW Directory.

**Comment by Drakonys** [comment]
Thank You, resolved :DDDD

2016-05-23 18:25 GMT+02:00 Tregeta <notifications@github.com>:
