### ISSUE TITLE
Warlock Passive Ability: Backdraft

### ISSUE THREAD

**Issue by ATalisan** [Valhalla-Gaming/Tracker#5431]
The tooltip says when you cast Conflagrate the cast time and mana cost of your next Chaos Bolt or next three Incinerates is reduced by 30%.

Problem 1: The mana cost is not being reduced to 70% of normal. Instead it's being reduced by 7.5%. The casting time is being applied correctly.
Problem 2: The Backdraft effect is applied when you cast Conflagrate, Immolate, Incinerate, Chaos Bolt and Shadowburn - it should only be applied when you cast Conflagrate.
Problem 3: Casting any of the above spells (in Problem 2) increments the number of charges up rather than down and resets the duration to full.

**Comment by Nienz** [comment]
New thing with Backdraft is it procs on every spell you do

**Comment by nuhrii** [comment]
Backdraft has become a talent in Legion, that only reduces the cast time of Incinerate and Chaosbolt, however it is not doing that when Conflagrate is cast
http://www.wowhead.com/spell=196406
