### ISSUE TITLE
Chimera

### ISSUE THREAD

**Issue by Hemoglobine-Valhalla** [Valhalla-Gaming/Tracker#5432]
Well, i dont know if this is the right amount of damage it should deal, but since i am a tank it must be way higher to a dps class, so yea i feel it might be corrected somehow... 

![wowscrnshot_052316_17230122](https://cloud.githubusercontent.com/assets/16792371/15475702/a793f9a2-210b-11e6-87bf-654b0d627eb4.jpg)

**Comment by Aveta** [comment]
Chimarea Shot is magic damage so armor doesn't affect its damage (and resistances aren't a thing anymore), still if that particular hunter you targeted was the source of the chim shot then the dmg looks way too high for me.

**Comment by Garendorf** [comment]
i've an answer for that.

http://www.wowhead.com/spell=157533/soul-dance = You are now able to shrug off even spells, such that 30% of your normal stagger amount works against magic damage.

http://www.wowhead.com/spell=115069/stance-of-the-sturdy-ox = reduces magic damage taken by 15%

**Comment by Aveta** [comment]
Forgot about those two x)
Either way the damage seems way too high. Especially in case the hunter wasn't fully decked in conquest gear.

**Comment by Garendorf** [comment]
Well, the hunter of this case wear 8 mythic items, which are bugged and scales to 750 ilvl in pvp.

**Comment by Nienz** [comment]
if its a mythic geard fella i can understand that kinda dmg but a "normal" high crit chim should be around 140k-170k so ye mythic is le bad guy again
