### ISSUE TITLE
Missing Battlegrounds

### ISSUE THREAD

**Issue by skorge1** [Valhalla-Gaming/Tracker#5435]
I've been pvping on this server for a while now and i've noticed that a couple of battlegrounds are missing such as http://www.wowhead.com/zone=2597/alterac-valley , http://www.wowhead.com/zone=4710/isle-of-conquest http://www.wowhead.com/zone=4384/strand-of-the-ancients . I'm aware that Alterac Valley was disabled due to some npcs hitting way too high. The reason I bring this up is that on the web info it states - 'End Game PvP. Player vs. Player combat is fully scripted for maximum enjoyment. This includes all battlegrounds, arenas and rated PvP.' I just want to make sure that people that join are getting what they have read. Thanks for taking the time to read this and hope to see it resolved.

**Comment by Garendorf** [comment]
Alterac valley was working, i think people just removed it from the random bg pop and that's why it doesn't call to such bg anymore, no clue about SotA or IoC

**Comment by Luminescent-Valhalla** [comment]
@Garendorf plays can select to remove bg's but currently that feature is not working since i first ran AV when it was enabled i had selected for no AV's due to how bugged the bosses are in that bg and it still popped up.
