### ISSUE TITLE
Primordial Direhorn Mounts

### ISSUE THREAD

**Issue by nuhrii** [Valhalla-Gaming/Tracker#5439]
I'm going to go on a limb here and report that the Primordial Direhorn Mounts do not drop from the Zandalari Warbringers, unless anyone else was able to obtain them
http://www.wowhead.com/item=94230
http://www.wowhead.com/item=94231
http://www.wowhead.com/item=94229

**Comment by Trekex** [comment]
I got all them 3 :P Keep trying
