### ISSUE TITLE
[Felwood] Quest: The Chieftain's Key

### ISSUE THREAD

**Issue by ATalisan** [Valhalla-Gaming/Tracker#5440]
1) The quest giver should be up north in Felwood, instead of fleeing from the totem in Southern Felwood.
2) Upon getting the key, the turn-in NPC is absent in Felpaw Village.

**Comment by Trekex** [comment]
Atm he escapes before you free him and runs through the textures (couldn't follow him so I have no idea if he stops somewhere).
Also, this is double spawned

**Comment by Cidragon** [comment]
Fix quest was fixed on November 25 changelog.
