### ISSUE TITLE
sap animation

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#5452]
Should it be like that? When you sap someone his animations/movement/whatever stop.

EDIT: Well nvm. It's not for all creatures. For sure http://www.wowhead.com/npc=3825/ghostpaw-alpha animations stop when you sap em.

**Comment by Collector-Valhalla** [comment]
Same thing for:

http://www.wowhead.com/npc=8959/felpaw-wolf
http://www.wowhead.com/npc=18077/umbrafen-oracle (or another one of those broken in that area im not sure 100%)
