### ISSUE TITLE
Ruthlessness

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#5455]
www.wowhead.com/spell=14161/ruthlessness

_"For each combo point spent, your damaging finishing moves reduce the cooldown on your Adrenaline Rush, Killing Spree, and Sprint by 2 sec, and all your finishing moves have a **20% chance to grant a combo point** and restore 25 Energy."_

Currently it has 100% chance to generate combo points... and it generates 2 combo points instead of 1.

EDIT: It's for Eviscerate in Combat spec. Slice and Dice and Recuperate finishing moves correctly generate 1 combo point (about chance I'm not sure).

EDIT2: Slice and Dice "sometimes" generates 2 combo points aswell.

:P

**Comment by Moustachos** [comment]
This isn't a bug, tooltip doesn't properly state it but it's 20% chance per combo point spent on finishing moves, so it's 100% with 5 CP.

**Comment by Moustachos** [comment]
Ref #2266
