### ISSUE TITLE
Revealing Strike

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#5456]
www.wowhead.com/spell=84617/revealing-strike

_Deals 120% Physical damage, increasing the effect of your offensive finishing moves on that target by 35%, **and giving your Sinister Strike a 25% chance to generate an extra combo point.**  Lasts 24 sec. Awards 1 combo point._

Sinister Strike with this debuff on target always generates 1 combo point. Should have a chance to generate 2.

**Comment by Moustachos** [comment]
Will be fixed on next update, as stated here #2385

**Comment by Moustachos** [comment]
Ref #2266
