### ISSUE TITLE
sap

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#5459]
When you sap one target and attack and kill another one ""sometimes"" sap on that first target breaks.

_Really wish to give more details but I have no idea why it breaks so I've wrote "sometimes"._

:<

**Comment by Collector-Valhalla** [comment]
So sap randomly breaks when you:

sap one target and attack another one
sap target, go out of steath and enter stealth again
sap one target and attack and kill another one

sometimes it works sometimes it doesn't ;p
