### ISSUE TITLE
[Dungeon] Halls of Reflection 

### ISSUE THREAD

**Issue by oGoody** [Valhalla-Gaming/Tracker#5460]
[Remorseless Winter] - _Slows movement speed by 75%. Also deals 7069 to 7931 Frost damage per second to players within 10 yards of him Debuff on the Lich King for the duration of the encounter._

I interrupted this non-interruptable ability and which made The Lich King move quicker hence killing Jaina, making the dungeon incompletable.

**Comment by Tregeta** [comment]
fixed next update
