### ISSUE TITLE
Bandit's Guile

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#5464]
http://www.wowhead.com/spell=84654/bandits-guile

_"Take advantage of the natural ebb and flow of combat, **causing your Sinister Strike to gradually increase your damage dealt by up to 30%**. This maximum effect will last for 15 sec before fading and beginning the cycle anew."_

Currently that effect:

1) procs from any ability not only sinister strike
2) I guess proc chance for shallow > moderate > deep insight's works ok but any action refreshes that effect. Well that shallow (green one) for sure is refreshed by any attack.

**Comment by Aveta** [comment]
From what I've read it's supposed to go 4 sinister strikes>first buff>4 ss>second buff and same thing for third then it falls off and starts all over again. Before deep insight ss is supposed to refresh the duration.

**Comment by Moustachos** [comment]
Both issues will be fixed on next update, and yes Aveta you're right about the way this talent works, you need 4 SS to move to the next Insight level.

Once Deep Insight is reached it can't be refreshed anymore and you need to wait for the buff to end to start a new cycle.

Ref #2266
