### ISSUE TITLE
Quest The Wolves and Warriors Draenor

### ISSUE THREAD

**Issue by LordLupusDei** [Valhalla-Gaming/Tracker#5465]
When I doen quests in first location after Dark Portal . I ,Khadgar and Thrall met Durotan he offers us to ride with him . After Riding to selected Location the Characters  disappear what is Normally but in Video from Official Server after disappear of Characters the Thrall have to spawn so I coud complete Quest but on our we can't complete becouse Thrall is not spawn and I can't go more quest line .
Please Repair this bug so we can complete more in Quests . I woud check next quests after this but I can't can you check please ? 

Quest ID : World of Warcraft Quest : Of Wolves and Warriors ID: 34402
and here is Youtube  : https://www.youtube.com/watch?v=g0bFMdTSmhE
Thanks for Checking this report.

**Comment by Tregeta** [comment]
The quest chain up to the garrisons work, speak with a GM to have your quests reset if you are somehow bugged.

**Comment by nuhrii** [comment]
Reopen this, I got this problem too which didn't happen before the update.

**Comment by Collector-Valhalla** [comment]
Same for me. I did this quest without problem on other character few days ago. Now this quest does not work.
