### ISSUE TITLE
Horde garrison

### ISSUE THREAD

**Issue by Nienz** [Valhalla-Gaming/Tracker#5470]
So i did the tanaan pre quest incl the newly added one, went to frostfire ridge, did first quest and when im trying to do http://www.wowhead.com/quest=34402/of-wolves-and-warriors the npc just phase out when reaching the destination in frostwolf, i tried abandon it and running over there instead of mount but nothing, even deleted cache folder but nothing helps so asked in world and few said it was a phase bug, so since i didnt find any here on tracker which was odd but guess someone gotta do it after few days

**Comment by Tregeta** [comment]
This quest currently works, please speak with a GM to have your quests reset.
