### ISSUE TITLE
internal bleeding

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#5472]
http://www.wowhead.com/spell=154904/internal-bleeding

Deals same amount of damage no matter how many combos used. With 5 and with 2 used it dealt 140 damage.

Also tooltip in talent window and actual damage have different amounts.
![wowscrnshot_052916_205657](https://cloud.githubusercontent.com/assets/14946340/15635500/f14f86a0-25df-11e6-81e8-bf9e9897c164.jpg)

**Comment by Bombrick** [comment]
shaman spells milestone? tregeta are you ok m8?

**Comment by Collector-Valhalla** [comment]
ayy

**Comment by Tregeta** [comment]
Apologies, it's right under rogue :laughing:

**Comment by Moustachos** [comment]
Ref #2266
