### ISSUE TITLE
Error messages on Troll Characters

### ISSUE THREAD

**Issue by nuhrii** [Valhalla-Gaming/Tracker#5503]
Getting errors messages on troll characters saying "You are in the wrong zone, "You are mounted", and "You are in flight". Im going to chalk this up the the recent scripting of The Rise of the Darkspear quest. Even on a new character just completes the quest then leaves the Echo Islands then relogs it comes back.

**Comment by Tregeta** [comment]
Is this upon just logging in to a fresh new character? Are there any other details that you have left out?

**Comment by nuhrii** [comment]
Well it only started recently on troll characters that had lying around and it never happened before. I don't think its occuring on other races. I rerolled a troll and it doesn't seem to happen on the Echo Isles, and it started up again when i left into Durotar and relogged. Look back at it i think its forcibly making the character sit, kinda hard to tell though on a male troll.

**Comment by nuhrii** [comment]
Okay its happening whenever you enter a new zone or subzone

**Comment by Trekex** [comment]
Should be fixed next update :)
