### ISSUE TITLE
shuriken toss

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#5507]
www.wowhead.com/spell=114014/shuriken-toss

Should have chance to apply lethal but it applies right now non-lethal.

**Comment by Moustachos** [comment]
Ref #2266

**Comment by Collector-Valhalla** [comment]
www.wowhead.com/spell=3408/crippling-poison

That non lethal poison is still applied by shuriken toss.
![wowscrnshot_061416_075614](https://cloud.githubusercontent.com/assets/14946340/16032413/d903e4ec-3205-11e6-9383-1c898f6407de.jpg)

**Comment by Traveler-Valhalla** [comment]
It's changed now in Legion so there's no issue.
