### ISSUE TITLE
venom rush

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#5508]
http://www.wowhead.com/spell=152152/venom-rush

_"Increases your maximum energy by 15. **Increases your energy regeneration rate by 5% for every enemy you have poisoned, up to 3.**"_

Doesn't increase energy regen (should apply buff). 
Should increase it from non-lethal, instant poison...
_...and things like internal bleeding is that correct?_

**Comment by Aveta** [comment]
I'm fairly certain not from Internal Bleeding talent as it's a bleed, not a poison. Venomous Wounds would be more likely, but then if you have Venomous Wounds procing then it means you have the target poisoned already.
