### ISSUE TITLE
[Quest] Corrupting Influence? + [Quest Item] Troll Charm

### ISSUE THREAD

**Issue by carminejackal** [Valhalla-Gaming/Tracker#5514]
Cleared the area and the item giving the quest never dropped, even when on the Culling quest to kill the mobs. Also there's a lot of mobs missing from the Thistlefur Village area I noticed. 
http://www.wowhead.com/quest=13868/corrupting-influence
http://us.battle.net/wow/en/item/46128
http://www.wowhead.com/item=46128/troll-charm

Checked on retail and got it 4 kills in on my lvl 21 there, without having done any quests in the area.
![](http://image.prntscr.com/image/9ccee7c481694539aed1eebf0195d430.png)

**Comment by Tregeta** [comment]
Fixed next update.
