### ISSUE TITLE
Shadow Reflection

### ISSUE THREAD

**Issue by Bombrick** [Valhalla-Gaming/Tracker#5515]
The first Buff that is summoning your shadow is ok but the second buff that your shadow should attack and do all what you have done in the duration of the first buff doesn't work which makes this spell useless.
[Shadow Reflection](http://www.wowhead.com/spell=152151/shadow-reflection)

**Comment by Moustachos** [comment]
I don't get your first and second buff thing, the reflection properly memorizes the offensive abilities you use within the first 8 secs then use them with the same timing during the next 8 secs.

**Comment by Moustachos** [comment]
Ref #2266

**Comment by Bombrick** [comment]
seriously It doesn't work I tried it even my friend tried it it doesn't work the reflection memeorizes the offensive abilities within the first 8 sec but he doesn't use them

**Comment by Tregeta** [comment]
Confirmed, the shadow reflection actions are extremely delayed, so much so that he barely only copies one or two spells at maximum.
