### ISSUE TITLE
Powering our defenses quest bugged

### ISSUE THREAD

**Issue by Parthrax** [Valhalla-Gaming/Tracker#5516]
when you click the crystal to release its energy nothing happens,

**Comment by forstix** [comment]
http://www.wowhead.com/quest=8490/powering-our-defenses

**Comment by forstix** [comment]
http://www.wowhead.com/quest=8490/powering-our-defenses

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/500
