### ISSUE TITLE
Thistlefur Village missing mobs

### ISSUE THREAD

**Issue by carminejackal** [Valhalla-Gaming/Tracker#5519]
http://www.wowhead.com/npc=3924/thistlefur-shaman
http://www.wowhead.com/npc=3925/thistlefur-avenger
http://www.wowhead.com/npc=3926/thistlefur-pathfinder

The above mobs are largely missing from Thistlefur Village forcing you to head up closer to the Hold and Cave area to get the needed 15 kills for http://www.wowhead.com/quest=13867/culling-the-furbolg-threat

**Comment by Tregeta** [comment]
There are exactly 56 of these npcs spawned currently and their counts are as follows:
7 - Pathfinders
28 - Avengers
21 - Shaman

Further I believe the quest you are seeking is unrelated to this area completely as it is meant to be done down at this region of the map:

![thinning the herd](https://cloud.githubusercontent.com/assets/12553233/15801356/c02fc180-2a57-11e6-9245-98c122c3be07.png)


The ear's drop rate is around 80-87% for these creatures:
http://www.wowhead.com/npc=3743/foulweald-warrior
http://www.wowhead.com/npc=3745/foulweald-pathfinder
http://www.wowhead.com/npc=3750/foulweald-totemic

**Comment by carminejackal** [comment]
The quest I linked is an alliance quest, and happens up around Thistlefur Village. It's a simple kill quest and has nothing do to with ears.

**Comment by Tregeta** [comment]
30 spawns are actually outside the cave area, though the quest only calls for 15. Can you go more into detail the exact area where you feel these spawns are too low? Will confirm on retail afterward.

**Comment by carminejackal** [comment]
Edited the my comment above with findings

**Comment by Tregeta** [comment]
Thanks, I've located the exact area.

**Comment by Tregeta** [comment]
Fixed next update

**Comment by Ardente47** [comment]
I know It's a old issue and I know It has been fixed.
Yes, the quest is working fine - we're able to complete it.

However, there are just some minor things that bother me.
First of, none of the NPCs around the area are moving. They're just standing still, doing nothing. Placed, without a waypoint or anything.

And at the beginning of the area is just 1 of the Quest NPCs, doing nothing.
Then theres a huge part of nothingness.. until you reach the area with the not moving NPCs.
![wowscrnshot_031417_140815](https://cloud.githubusercontent.com/assets/26364152/23902454/764f7b84-08c1-11e7-8f6b-d93c00cb141d.jpg)
![wowscrnshot_031417_140827](https://cloud.githubusercontent.com/assets/26364152/23902455/79f6240e-08c1-11e7-9ef1-b9c28b582543.jpg)
![wowscrnshot_031417_140842](https://cloud.githubusercontent.com/assets/26364152/23902471/7ed40ad6-08c1-11e7-8dab-109babae17f0.jpg)



PS: Yes, they run towards or away from you, when you attack them.
And yes, you can aggro them.
