### ISSUE TITLE
Swiftgear Station should have prerequisite quests

### ISSUE THREAD

**Issue by Reloque** [Valhalla-Gaming/Tracker#552]
I can't tell you which quests with certainty, but the Wetlands quest [Swiftgear Station](http://www.wowhead.com/quest=26980)(26980) definitely should have prerequisites. [The Eye of Paleth](http://www.wowhead.com/quest=25819)(25819) seems like a suitable prerequisite quest. See the [comments on wowhead](http://www.wowhead.com/quest=26980#comments) for more information.

**Comment by Tregeta** [comment]
fixed next update
