### ISSUE TITLE
Valley of Trials glitch

### ISSUE THREAD

**Issue by carminejackal** [Valhalla-Gaming/Tracker#5520]
I noticed upon entering Valley of Trials it told my troll druid that she was 'in the wrong zone' , but decided to ignore it to continue on. I then began to notice it keeps randomly forcing her into a sitting position, in addition to telling her she's in the wrong zone. In the below screenshot it just forced her to sit after she accepted the quest given by the npc she has targeted, and you can see the error message telling her she's in the wrong zone. I can get her up out of the sitting position by making her jump, but sometimes it forces her repeatedly to sit and she's even attacked things from a seated position. I first noticed it happening upon accepting the quest http://www.wowhead.com/quest=25152/your-place-in-the-world (It might be just a troll thing as I have no issues with the orc I just rolled)

![](http://i.imgur.com/UVIyL9Z.jpg)

**Comment by Tregeta** [comment]
This should be fixed next update as reported here https://github.com/Valhalla-Gaming/Tracker/issues/5503
