### ISSUE TITLE
subterfuge

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#5521]
http://www.wowhead.com/spell=108208/subterfuge

Currently works only with ambush. Should work with garrote, cheap shot, sap and - according to comments on wowhead - summoning mount, using hearthstone, surveying (archaelogy) and using certain consumables,

**Comment by Moustachos** [comment]
Works just fine for the spells you quoted, as of summoning mount etc., these spells aren't supposed to be used while stealthed.

So this isn't a

**Comment by Moustachos** [comment]
Works just fine for the spells you quoted, as of summoning mount etc., these spells aren't supposed to be used while stealthed.

So this isn't a bug.

**Comment by Moustachos** [comment]
Ref #2266

**Comment by Collector-Valhalla** [comment]
GUYS, my stealth for 100% real breaks after using garrote and cheap shot. Subterfuge FOR ME works only with ambush. After using ambush I'm correctly in stealth for few seconds.

Please I can upload a video if it is hard to believe altho I'm not a big fan of downloading video programs just to remove them in next 5 minutes.

**Comment by Tregeta** [comment]
I have just confirmed that both of these are as Collector says. The issue is likely due to subterfuge not being applied to garrote / cheapshot.

**Comment by Moustachos** [comment]
My bad, found the issue with Garrote / Cheap Shot.

Will be fixed on next update.
