### ISSUE TITLE
Kezzik the Striker <Gladiator, Merciless, & Vengeful Gear>

### ISSUE THREAD

**Issue by oGoody** [Valhalla-Gaming/Tracker#5524]
This NPC only sells season 1, 2 & 3 weapons but no PVP armor.

[Page 1](https://gyazo.com/73ee985373acfa230c50767072b35ae6)

[Page 2](https://gyazo.com/7988692af61c8acab233a387b5adf454)

**Comment by Tregeta** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/4952
