### ISSUE TITLE
Mage Fire Spec

### ISSUE THREAD

**Issue by Nienz** [Valhalla-Gaming/Tracker#5525]
http://www.wowhead.com/spell=11129/combustion works on resetting Inferno Blast but the additional damage isnt applied

http://www.wowhead.com/spell=44457/living-bomb works but doesnt spread when using Inferno Blast

http://www.wowhead.com/spell=157976/unstable-magic dont work on what i can see will test it more properly in Firelands

http://www.wowhead.com/spell=157642/enhanced-pyrotechnics dont reset the stacking but just increases it after each hit even if it does a critical strike

http://www.wowhead.com/spell=11366/pyroblast dont get the procs from non critical hits

http://www.wowhead.com/spell=12846/mastery-ignite dont work

**Comment by Tregeta** [comment]
Combustion #4560 
Living bomb  #4550
Pyroblast #1405 
Mastery(Fire) #4559

**Comment by LordYawgmoth** [comment]
unstable magic works for me lvl 94 human fire mage
