### ISSUE TITLE
Small Pouch of Coins

### ISSUE THREAD

**Issue by TheRealHoboo** [Valhalla-Gaming/Tracker#5535]
http://www.wowhead.com/item=114028/small-pouch-of-coins

When you open this item there is nothing inside of it but there should be several coins.

**Comment by nuhrii** [comment]
You forgot to add all of these ones too
http://www.wowhead.com/item=114028
http://www.wowhead.com/item=114970
http://www.wowhead.com/item=116111
http://www.wowhead.com/item=116376
http://www.wowhead.com/item=116764
http://www.wowhead.com/item=128327
Money for all your different secrets

**Comment by Tregeta** [comment]
Thank you, as only one was linked that was the only one fixed.

**Comment by Tregeta** [comment]
Fixed next update
