### ISSUE TITLE
[Quest] Lost in the Floods

### ISSUE THREAD

**Issue by GamerCrazy2** [Valhalla-Gaming/Tracker#5536]
[Lost In The Floods](http://www.wowhead.com/quest=25187/lost-in-the-floods)
This quest is unable to be completed as you must use the "[Thonk's SpyGlass](http://www.wowhead.com/item=52514)" but it only gives the error "Requires top of Razor Hill Watchtower" regardless of where the character is located even if standing beside Thonk.

**Comment by GamerCrazy2** [comment]
Close this issue, found another open from over a YEAR ago that still open

**Comment by Tregeta** [comment]
Ref #589
