### ISSUE TITLE
Netherwing questline

### ISSUE THREAD

**Issue by TheRealHoboo** [Valhalla-Gaming/Tracker#5547]
Finished the quest [Karynaku](http://www.wowhead.com/quest=10858/karynaku) but he didn't give me the next quest [Zuluhed the Whacked](http://www.wowhead.com/quest=10866/zuluhed-the-whacked#comments) so im unable to finish the questline.

So im gonna say [THIS](http://www.wowhead.com/quest=10872/zuluhed-the-whacked) quest is missing.

**Comment by Trekex** [comment]
Sometimes it works, some other not. For me it worked for example (some time ago)

**Comment by oGoody** [comment]
So i'm guessing for me it didn't work, how do i fix it?

**Comment by Tregeta** [comment]
What is your faction?

**Comment by TheRealHoboo** [comment]
I am an alliance, human hunter

**Comment by Tregeta** [comment]
fixed in next update.

**Comment by TheRealHoboo** [comment]
Still not working for me

**Comment by Tregeta** [comment]
You will likely need a quest reset from a GM.

**Comment by TheRealHoboo** [comment]
okay thank you :+1:
