### ISSUE TITLE
abedneum

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#5557]
http://www.wowhead.com/npc=30899/abedneum
http://www.wowhead.com/zone=4264/halls-of-stone

Abedneum should talk only but currently he's attacking you.

![wowscrnshot_060616_100234](https://cloud.githubusercontent.com/assets/14946340/15950258/70039f56-2ead-11e6-8cc4-d672b154d3c2.jpg)

**Comment by Tregeta** [comment]
fixed next update
