### ISSUE TITLE
stealth

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#5558]
"Sometimes" you can't use your stealth. I'm very not sure but I think it happens when you get stunned or whatever during Killing Spree, die and come back to life. 

Below proof. Trying to use stealth but "ability is not ready yet".
![wowscrnshot_060216_203906](https://cloud.githubusercontent.com/assets/14946340/15950290/c0334cec-2ead-11e6-8631-db998bf33d5d.jpg)
![wowscrnshot_060516_182424](https://cloud.githubusercontent.com/assets/14946340/15950294/c5844cdc-2ead-11e6-8b9e-b3e719516153.jpg)

**Comment by CageValhalla** [comment]
It happens to me on dudu also, it doesnt show up cd sometimes, but after time im able to prowl. Dunno if that the deal with rogue too.

**Comment by Tregeta** [comment]
Will be placed in rogue for the time being, hopefully with the fix of rogue will also fix the issue with druid.
