### ISSUE TITLE
emblem of triumph

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#5559]
http://www.wowhead.com/zone=4493/the-obsidian-sanctum
http://www.wowhead.com/item=43347/satchel-of-spoils
http://www.wowhead.com/item=47241/emblem-of-triumph

There's still Emblem of Triumph dropping from Sachel of Spoils in Obsidian Sanctum from Sartharion.

![wowscrnshot_060816_025725](https://cloud.githubusercontent.com/assets/14946340/15950349/3cecfbe8-2eae-11e6-9aa0-dc2e19e947f8.jpg)

**Comment by Tregeta** [comment]
fixed in next update
