### ISSUE TITLE
[Druid][Balance]Eclipse: fix the passive then the spells affected by it

### ISSUE THREAD

**Issue by alexrrtm** [Valhalla-Gaming/Tracker#5560]
- Moonfire doesn't change into Sunfire( http://www.wowhead.com/spell=164815/sunfire) when the balance bar reach the "solar" area.

- Neither it procs Solar Peak (http://www.wowhead.com/spell=171744/solar-peak) when reaching the required 100 solar energy, instead it procs Lunar Peak on both sides.

- Both peaks "procs" at 90 lunar/solar energy respectively instead of only proccing only when the bar reaches 100 on each side.

- The movement in the bar is erratic, it goes faster at some moments for no apparent reason or without being under the effect of Astral Communion (http://www.wowhead.com/spell=127663/astral-communion).

I have to admit that i know too little about scripts, but it seems that the whole Eclipse script is messed up, i'll suggest doing something like "re-scripting" Eclipse or checking if some other data could be messing up the passive script and the spells related to it.

Didn't wanted to believe that such core mechanic on a class spec has been buggy for so long seeing how good your work has been with the development.
Something like that shouldn't remain broken for so long, is a core mechanic and damage source of the balance spec.

**Comment by Tregeta** [comment]
Eclipse Ref: http://www.wowhead.com/spell=79577/eclipse

**Comment by Tregeta** [comment]
@alexrrtm merging your new topic into this
>hi there.
after borrowing my friend's retail account and playing a balance druid over there, then comparing the functionallity of the eclipse mechanic with the one here, the only problem here is moonfire not changing into sunfire and solar peak not proccing.
besides that, everything else works retail-like (damage increase, the transition speed) for that i have to say excellent work.
Also, casually, was looking at the Balance talent calculator and found this http://www.wowhead.com/spell=137013 now given that eclipse is actually bugged i wanted to ask if you guys have that implemented.
hope this can make finding the problem a little easier.
