### ISSUE TITLE
[Quests][Teldrassil] Refusal of the Aspects

### ISSUE THREAD

**Issue by alexrrtm** [Valhalla-Gaming/Tracker#5562]
the quest (http://www.wowhead.com/quest=929/teldrassil-the-refusal-of-the-aspects) is nowhere to be found cause the NPC (http://www.wowhead.com/npc=3515/corithras-moonrage) doesn't give it

Side note: the quest is obtainable only to Night Elfs

**Comment by Cidragon** [comment]
the NPC is there now.
