### ISSUE TITLE
[Spawn] Sirana Iceshriek

### ISSUE THREAD

**Issue by Braemen** [Valhalla-Gaming/Tracker#5565]
[Sirana Iceshriek](http://www.wowhead.com/npc=29794/sirana-iceshriek)
Never saw this mob spawned, checked with multiple alts.

This mob is required for the quest [Sirana Iceshriek](http://www.wowhead.com/quest=12868/sirana-iceshriek)

**Comment by Tregeta** [comment]
This creature is currently spawned, you may have missed it on each alt.

**Comment by Braemen** [comment]
In this case I apologize :-)
