### ISSUE TITLE
[Quest][Durotar]Lost in the Floods

### ISSUE THREAD

**Issue by justSelim** [Valhalla-Gaming/Tracker#5566]
- Quest: [Lost in the Floods](http://www.wowhead.com/quest=25187/lost-in-the-floods)
- NPC: [Thonk](http://www.wowhead.com/npc=39323)
- Item: [Thonk's Spyglass](http://www.wowhead.com/item=52514)

- The Bug: Thonk's Spyglass isn't able to use. It means you must be at the guard tower. I am on the top of the guard tower but I still cant use the item.
 

I hope it gets fixed soon :).

With greetings,
Selim

**Comment by Tregeta** [comment]
Ref #589
