### ISSUE TITLE
[Quest][Durotar]The Burning Blade

### ISSUE THREAD

**Issue by justSelim** [Valhalla-Gaming/Tracker#5568]
Quest: [The Burning Blade](http://www.wowhead.com/quest=25232/the-burning-blade)
Bug: The NPC's are doing a lot of damage so it is impossible to get these Burning Blade Spellscrolls. I am LvL 8 RIGHT NOW so if i lock at the stats. They do like 80 Damage every hit and they get some buffs that they make 120% more Damage. They kill me with 288HP in 2 Second.

I hope it gets fixed soon.

With greetings,
Selim

**Comment by Tregeta** [comment]
Do you have a screenshot of your combat log?

**Comment by justSelim** [comment]
![wowscrnshot_061216_114833](https://cloud.githubusercontent.com/assets/19872202/15990499/285de696-3094-11e6-9c73-94f2758b27ca.jpg)
![wowscrnshot_061216_114827](https://cloud.githubusercontent.com/assets/19872202/15990501/2dbb8a94-3094-11e6-8de9-0d54c2e9ffb1.jpg)

**Comment by Tregeta** [comment]
Thanks, will check this and see what I find
