### ISSUE TITLE
Rogue Ap value

### ISSUE THREAD

**Issue by miloskovac** [Valhalla-Gaming/Tracker#5572]
Hello ppl.
There seems to b a problem with ap value with rogues. Same gear same talents and yet different specs have different ap. 
Even on sub spec (15% increase on agy) it still has less ap then my combat spec.
Sub: 4008 agility/4008 ap
Combat: 3485 agility/5228 ap, same gear was on both specs.

**Comment by Collector-Valhalla** [comment]
http://www.wowhead.com/spell=61329/vitality
