### ISSUE TITLE
GARRISON

### ISSUE THREAD

**Issue by Kuneman** [Valhalla-Gaming/Tracker#5573]
Please, i am a hord player and i did quest for GARRISON, but i didnt get it !

Thanks for solving this fast ! :)

**Comment by Tregeta** [comment]
Were you mounted?

**Comment by Kuneman** [comment]
Yes i didtn know that needed to be unmounted
13.06.2016. 02.12, "Tregeta" <notifications@github.com> је написао/ла:

**Comment by Kuneman** [comment]
can you resolve this?

**Comment by Tregeta** [comment]
Yes, But you need to message me on the forum with your player name.

**Comment by Kuneman** [comment]
Name: Soslas

**Comment by Tregeta** [comment]
You actually need to be in game too.
