### ISSUE TITLE
Claws from the Deep and Reclaiming Goods should have a prerequisite

### ISSUE THREAD

**Issue by Reloque** [Valhalla-Gaming/Tracker#558]
Both [Claws from the Deep](http://www.wowhead.com/quest=25801)(25801) and [Reclaiming Goods](http://www.wowhead.com/quest=25802)(25802) should have [When Life Gives You Crabs](http://www.wowhead.com/quest=25800)(25800) as a prerequisite. All three quests are given by [Karl Boran](http://www.wowhead.com/npc=41297)(41297) in Menethil Harbor, Wetlands.

**Comment by Tregeta** [comment]
Fixed next update
