### ISSUE TITLE
[Druid] update on the Eclipse problem

### ISSUE THREAD

**Issue by alexrrtm** [Valhalla-Gaming/Tracker#5583]
hi there.
after borrowing my friend's retail account and playing a balance druid over there, then comparing the functionallity of the eclipse mechanic with the one here, the only problem here is moonfire not changing into sunfire and solar peak not proccing.

besides that, everything else works retail-like (damage increase, the transition speed) for that i have to say excellent work.
Also, casually, was looking at the Balance talent calculator and found this http://www.wowhead.com/spell=137013 now given that eclipse is actually bugged i wanted to ask if you guys have that implemented.

hope this can make finding the problem a little easier.

**Comment by Tregeta** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/5560#issuecomment-225756644
