### ISSUE TITLE
[Quest][Stormshield]Ashran Appearance

### ISSUE THREAD

**Issue by justSelim** [Valhalla-Gaming/Tracker#5588]
**Quest:** [Ashran Appearance](http://www.wowhead.com/quest=36624/ashran-appearance)
**NPC's:** **START:** [Lieutenant Thorn](http://www.wowhead.com/npc=79953) & [Dungar Longdrink](http://www.wowhead.com/npc=81103/dungar-longdrink)    **END:** [Private Tristan](http://www.wowhead.com/npc=86065/private-tristan)

**Bug:** The NPC [Dungar Longdrink](http://www.wowhead.com/npc=81103/dungar-longdrink) is bugged. I should ask him for a fly to Ashran but I am not available to ask him... 

Pls fix this bug. It is really important to do the quests in the Garrision.
This should be High Priority!!!!

With greetings,
Selim

**Comment by Tregeta** [comment]
Ref #3875
