### ISSUE TITLE
[Quest][Shadowmoon Valley]Lost Lumberjacks

### ISSUE THREAD

**Issue by justSelim** [Valhalla-Gaming/Tracker#5590]
**Quest:** [Lost Lumberjacks](http://www.wowhead.com/quest=34820/lost-lumberjacks)
**NPC:**  **START:** [Ken Loggin](http://www.wowhead.com/npc=80163/ken-loggin) **END:** [Lost Packmule](http://www.wowhead.com/npc=79966/lost-packmule)

**Bug:** Everything works fine but when your on the position where you should be on the map. There is no [Lost Packmule](http://www.wowhead.com/npc=79966/lost-packmule)

**Comment by Tregeta** [comment]
Ref #3874
