### ISSUE TITLE
[Quest][Shadowmoon Valley]The Young Alchemist

### ISSUE THREAD

**Issue by justSelim** [Valhalla-Gaming/Tracker#5593]
**Quest:** [The Young Alchemist](http://www.wowhead.com/quest=35343/the-young-alchemist)
**NPC's:** **START:** [Aenir](http://www.wowhead.com/npc=82466/aenir) **END:** [Abatha](http://www.wowhead.com/npc=82497)

**Bug:** The bug is that Abatha is not on her position like in wowhead. Maybe the Quest or NPC is bugged

**Comment by Tregeta** [comment]
Ref #3876
