### ISSUE TITLE
[Warlock] Guardians and pets despawn each other

### ISSUE THREAD

**Issue by Usernameisntalreadytaken** [Valhalla-Gaming/Tracker#5595]
When you cast "summon Infernal", it makes your current pet (a voidwalker for example) despawn.
When you try to summon a pet (a voidwalker for example) while an infernal is already summoned, the infernal despawns.

Infernals (and doomguards, and abysals, and maybe a couple other lock summons) are meant to be GUARDIANS and not PETS and therefore should not be mutually exclusive with pets.

**Comment by Usernameisntalreadytaken** [comment]
Well, it's a duplicate:
https://github.com/Valhalla-Gaming/Tracker/issues/4607

ofc this would've been reported before, it's quite the issue for a lock.

**Comment by Tregeta** [comment]
As referenced already, will copy your text to the current referenced related in a quote.
