### ISSUE TITLE
Hunter Pet

### ISSUE THREAD

**Issue by TheRealHoboo** [Valhalla-Gaming/Tracker#5600]
My hunter pet always disappears every night when i log in. Which means i have to go and tame another pet, then dismiss it for the [Lone Wolf](http://www.wowhead.com/spell=155228/lone-wolf) buff. Otherwise i have no 30% dmg increase buff, which means the [talent](http://www.wowhead.com/spell=155228/lone-wolf#comments) becomes completely useless.

**Comment by Redrian-Hellscream** [comment]
Negative, I own 5 pets and none of them disappear at any time.

**Comment by Tregeta** [comment]
This but could somehow be character specific.

**Comment by TheRealHoboo** [comment]
how do i find out if it's character specific:?

**Comment by Tregeta** [comment]
A Spell developer that has worked on this system will need to confirm it.

**Comment by TheRealHoboo** [comment]
How long will this take to confirm?

**Comment by TheRealHoboo** [comment]
It just happened to me.
