### ISSUE TITLE
[Paladin][Talent]Long Arm of the Law

### ISSUE THREAD

**Issue by MrVojtik** [Valhalla-Gaming/Tracker#5604]
It's just not working.
I would really appreciate if you fix this talent.

+I think that Pursuit of Justice may be broken, but it's hard to notice 5% movement speed, so not sure.

**Comment by Luminescent-Valhalla** [comment]
Confirmed Long arm of the law is not working on Valhalla 

![wowscrnshot_061916_141304](https://cloud.githubusercontent.com/assets/13806368/16177529/552b1394-3628-11e6-8d81-e363a04af74c.jpg)
![wowscrnshot_061916_141313](https://cloud.githubusercontent.com/assets/13806368/16177531/58328bf8-3628-11e6-8bae-7c9aa6325da0.jpg)
