### ISSUE TITLE
kromgar boi

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#5606]
http://www.wowhead.com/npc=42028/kromgar-quartermaster

That dude should sell shoulders, head and wrist items. I mostly care about those sweet shoulders (http://www.wowhead.com/item=57502/kromgar-champions-hide-shoulderguard) cuz it would fit my mog very mucho grande oi oi.

![wowscrnshot_061816_150946](https://cloud.githubusercontent.com/assets/14946340/16171112/b165c436-3567-11e6-8768-cb17928b3b8e.jpg)

**Comment by Tregeta** [comment]
Fixed next update, please refer to 
http://www.wowhead.com/npc=42028/kromgar-quartermaster#comments:id=1459762

Each rank rewarded will issue the new purchases.
