### ISSUE TITLE
[Quest] [Borean Tundra] The Tides Turn

### ISSUE THREAD

**Issue by dejmbastos** [Valhalla-Gaming/Tracker#5614]
Quest Link: http://www.wowhead.com/quest=11968/the-tides-turn#screenshots

In this quest you are supposed to kill a mini boss with the help of some npc's that are fighting the Kvaldir's around. On the place where the boss is spawned, you have an NPC defender staked on top of another one, and both of them make too much damage to the quest target, which makes it very difficult for you to make enough damage to complete the quest.

**Comment by ATalisan** [comment]
Heigarr the Horrible does not seem to spawn.

**Comment by Tregeta** [comment]
fixed next update
