### ISSUE TITLE
[Quest] [Borean Tundra] Plan B

### ISSUE THREAD

**Issue by dejmbastos** [Valhalla-Gaming/Tracker#5618]
Quest Link: http://www.wowhead.com/quest=11658/plan-b#screenshots

The dead orc corpsed from which your supposed to pick up the quest items are bunny models on this server.

![image](https://cloud.githubusercontent.com/assets/19983710/16179489/519ae6d2-365f-11e6-8ecf-f07a9dd47fdf.png)

**Comment by Tregeta** [comment]
fixed
