### ISSUE TITLE
Dewin Shimmerdawn sells unlimited Healing Potions

### ISSUE THREAD

**Issue by Reloque** [Valhalla-Gaming/Tracker#562]
Alchemy Supplies vendor [Dewin Shimmerdawn](http://www.wowhead.com/npc=1453)(1453) in Menethil Harbor, Wetlands sells an unlimited amount of [Healing Potion](http://www.wowhead.com/item=929)s(929). He should have a stock of 3 potions which replenish very slowly over time.

**Comment by Tregeta** [comment]
fixed
