### ISSUE TITLE
[Warlock][Talent] Grimoire of Sacrifice (2 bugs)

### ISSUE THREAD

**Issue by Usernameisntalreadytaken** [Valhalla-Gaming/Tracker#5621]
How it works:
you summon a pet, cast "grimoire of sacrifice", and get a buff + one of its abilities. The pet dies.
In the description it says the buff  "Lasts 1 hour or until you summon a pet." 
http://www.wowhead.com/spell=108503/grimoire-of-sacrifice

**BUG 1** (positive bug):
I can summon a pet after I recieved the buff from casting "grimoire of sacrifice" and then enjoy both the pet and the buff (it doesnt go away).

**BUG 2** (negative bug):
I don't get the sacrificed pet's ability.

**Comment by nuhrii** [comment]
As of Legion, the buffed gained from this ability remains when switching talents
