### ISSUE TITLE
Quest: Can't Get Ear-nough... (Borean Tundra)

### ISSUE THREAD

**Issue by ATalisan** [Valhalla-Gaming/Tracker#5622]
Arch Druid Lathorius has a blue question mark above his head
He should allow you to turn in Nesingwary Lackey Ears x15 for 150 Cenarion Expedition Rep
However, he is not offering that dialogue option
(Note, I have completed all the rest of the DEHTA quest at this encampment)
Wowhead: http://www.wowhead.com/quest=11867/cant-get-ear-nough

**Comment by Tregeta** [comment]
Fixed next update
