### ISSUE TITLE
[Warlock][Talent]"Cataclysm" does not apply DoT's

### ISSUE THREAD

**Issue by Andreder** [Valhalla-Gaming/Tracker#5625]
[http://www.wowhead.com/spell=152108/cataclysm](Catalysm)
Tooltip: "Conjures a cataclysm at the target location, dealing (750% of Spell power) Shadowflame damage to all enemies within 0 yards, and **applying Agony and Unstable Affliction/Corruption/Immolate**."

Not tested on either Destruction(Immolate) or Demonology(Corruption), but on Affliction it doesn't apply neither Agony or Unstable Affliction, only dealing the initial damage.

**Comment by nuhrii** [comment]
This talent has changed in Legion being only avalible to Destruction Warlock. However it is only suppose to apply the damage over time effect of Immolate and not its initial damage and generate Soul Shards.
