### ISSUE TITLE
Brak Durnad sells unlimited Blessed Claymores and doesn't sell Executioner's Sword

### ISSUE THREAD

**Issue by Reloque** [Valhalla-Gaming/Tracker#564]
Weaponsmith [Brak Durnad](http://www.wowhead.com/npc=1441)(1441) in Menethil Harbor, Wetlands sells an unlimited quantity of [Blessed Claymore](http://www.wowhead.com/item=4817)s(4817), when he should have a stock of 2 which replenishes slowly over time.

He should also sell [Executioner's Sword](http://www.wowhead.com/item=4818)s(4818), with a stock of 2. Seeing as he sells unlimited Blessed Claymores, it would appear that on our server he does not sell Executioner's Sword at all.

**Comment by Tregeta** [comment]
fixed
