### ISSUE TITLE
paladin ...

### ISSUE THREAD

**Issue by roguetwinky** [Valhalla-Gaming/Tracker#5647]
i feel Paladin Mastrey (Hand of Light) not totally fixed  + lvl 15 talent (Long Arms of Law) not working .. so please fix it we need that speed :)

**Comment by neano300** [comment]
They work fine

**Comment by Luminescent-Valhalla** [comment]
please use the search when reporting things as duplicate reports do not help the developers 

@neano300 Long arm of the law is actually not working asi confirmed in this report #5604

**Comment by Tregeta** [comment]
Duplicate
