### ISSUE TITLE
s.e.l.f.i.e camera

### ISSUE THREAD

**Issue by LordLupusDei** [Valhalla-Gaming/Tracker#5663]
from my Garrison I recieved s.e.l.f.i.e. camera it work nice 
Yesterday i recieved quest in my garrison to get upgrade to my Camera but when I get that upgrade and used it my camera disappear and I can't get it back. I tried reconnect but no camera.

Please fix this I really like that Camera 
![wowscrnshot_062316_222213](https://cloud.githubusercontent.com/assets/19625389/16345798/1c253e24-3a44-11e6-85bc-7417ce5fbad1.jpg)

**Comment by Redrian-Hellscream** [comment]
PM a GM to get a new camera.

**Comment by Braemen** [comment]
#3931

**Comment by Tregeta** [comment]
Duplicate, thanks for pointing it out @Braemen
