### ISSUE TITLE
Shadowfang Keep dungeon not working.

### ISSUE THREAD

**Issue by real900** [Valhalla-Gaming/Tracker#5671]
You can enter and kill the initial mobs but a lot of them are still untargetable and after killing the first boss in front of one of the cells, the guy who is supposed to open the door for the rest of the dungeon simply stays there, doesnt leave the cell and you cant talk to him.

 #465 
#4933

**Comment by Tregeta** [comment]
Thank you, we are still aware of the issue. Please add the untargetable mobs names to the #4933 post. Closing as is duplicate.
