### ISSUE TITLE
[Warlock][Talent] Soul Link - should heal player and demon 3% of dmg dealt, but no healing done

### ISSUE THREAD

**Issue by Usernameisntalreadytaken** [Valhalla-Gaming/Tracker#5672]
Seeing as there's no mention of Soul Link on the spell tracker:
"20% of all damage taken is split with your demon pet, and 3% of damage you deal heals you and your demon."

EDIT:
There's no healing at all being done, wether to me or the demon.

**Comment by Tregeta** [comment]
http://www.wowhead.com/spell=108415/soul-link

**Comment by Braemen** [comment]
[#797](https://github.com/Valhalla-Gaming/Tracker/issues/797)

**Comment by Tregeta** [comment]
Thanks Braemen, I was wondering why I wasn't able to find it on our spell tracker.
