### ISSUE TITLE
[Warlock][Glyph] Can't learn Glyph of Drain life

### ISSUE THREAD

**Issue by Usernameisntalreadytaken** [Valhalla-Gaming/Tracker#5674]
http://www.wowhead.com/spell=63302/glyph-of-drain-life

My specialization is Affliction.
I tried learning Glyph of Drain life (to combine it with the talent Harvest Life) 
http://www.wowhead.com/spell=108371/harvest-life

turns out I can't learn it wether I have the talent Harvest Life or not and wether I relog or not

the error given is "That glyph is invalid for your Affliction specialization" when I try to learn it

the tooltip (and wowhead) show that I should be able to learn it

**Comment by Aveta** [comment]
It's an issue with all glyphs useable by two specs.
