### ISSUE TITLE
The Far Watch Offensive 

### ISSUE THREAD

**Issue by LordLupusDei** [Valhalla-Gaming/Tracker#5677]
In this Quest I have to kill 5 Razormane defenders 5 Razormane ThornWeavers  and 1 Kreening Snarlsnout but when i came to Quest location there is no mob  and I cant do that quest .

**Comment by Tregeta** [comment]
They are spawned, check in the cave. Once you're inside the cave you'll see they are in their correct spot.
![Img1](http://i.imgur.com/el00G6C.jpg)
