### ISSUE TITLE
Into the Raptor's net 

### ISSUE THREAD

**Issue by LordLupusDei** [Valhalla-Gaming/Tracker#5678]
I have to kill Sunscale Raptors and reciever the Sunscale Feather but when I try to place it on nest  it will start loading of placing the feather to nest but I didnt reciver in my quest line that I done it 

please fix it

**Comment by Braemen** [comment]
[#662](https://github.com/Valhalla-Gaming/Tracker/issues/662)

**Comment by Tregeta** [comment]
Duplicate
