### ISSUE TITLE
I shoot magic into the Darkness

### ISSUE THREAD

**Issue by Kelpo122** [Valhalla-Gaming/Tracker#568]
Quest: http://www.wowhead.com/quest=9700/i-shoot-magic-into-the-darkness
Start/End: http://www.wowhead.com/npc=17684/vindicator-boros

You can't verify the location of the portal, explored all around the structure and nothing happened

**Comment by Lazyg33k** [comment]
ya i try to get the quest donne but nothing work but the mob you have to kill

**Comment by zwei7** [comment]
Can't verify location of sun portal.

**Comment by tribaljet** [comment]
Confirmed, the Sun Portal Site Confirmed objective cannot be completed at the time of writing.

**Comment by Pure-Valhalla** [comment]
Quest now works. 

(Watch for the notification about confirming the location of the Sun Portal. It'll appear on your screen but the quest tracker won't show it.)

**Comment by Tregeta** [comment]
working as of current version
