### ISSUE TITLE
Glyph of Lightning Shield

### ISSUE THREAD

**Issue by Orunla** [Valhalla-Gaming/Tracker#5683]
The Glyph of Lightning Shield cannot be equipped. I get an error saying "The glyph is invalid for your Enhancement Specialization" 
I find this pretty crucial since the glyph would provide flat 10% dmg reduction.

Happens both on elemental and enhancement shaman (..."for your elmental specialization" on elemental...)

**Comment by TheRealHoboo** [comment]
happens to me too

**Comment by Aveta** [comment]
It's an issue with all glyphs for two specs.

**Comment by Tregeta** [comment]
Ref also #5186, will be closing since duplicate.
