### ISSUE TITLE
[Glyphs] Glyphs useable by two specs

### ISSUE THREAD

**Issue by Aveta** [Valhalla-Gaming/Tracker#5684]
All glyphs useable by two specs are impossible to equip with an error message "This glyph is invalid for your x specialization"
Some of those are pretty important to the class. Also I want to avoid having more varieties of pretty much the same issue (ppl reporting single glyphs) cluttering the tracker.
Glyphs affected:
Death Knight:
http://www.wowhead.com/spell=63333/glyph-of-death-coil
http://www.wowhead.com/spell=159421/glyph-of-empowerment
Druid:
http://www.wowhead.com/spell=116216/glyph-of-skull-bash
http://www.wowhead.com/spell=159453/glyph-of-the-shapemender
http://www.wowhead.com/spell=63057/glyph-of-barkskin (this one is three-spec, but then Druids have four specs)
http://www.wowhead.com/spell=94386/glyph-of-faerie-fire
http://www.wowhead.com/spell=114223/glyph-of-survival-instincts
Mage:
http://www.wowhead.com/spell=115705/glyph-of-cone-of-cold
Monk:
http://www.wowhead.com/spell=125151/glyph-of-rising-tiger-kick
http://www.wowhead.com/spell=120477/glyph-of-zen-meditation
Paladin:
http://www.wowhead.com/spell=54927/glyph-of-avenging-wrath
http://www.wowhead.com/spell=63219/glyph-of-hammer-of-the-righteous
http://www.wowhead.com/spell=56416/glyph-of-immediate-truth
http://www.wowhead.com/spell=57947/glyph-of-seal-of-blood
http://www.wowhead.com/spell=115931/glyph-of-the-falling-avenger
http://www.wowhead.com/spell=57979/glyph-of-winged-vengeance (obviously the most important one : P )
Priest:
http://www.wowhead.com/spell=119853/glyph-of-holy-fire
http://www.wowhead.com/spell=171921/glyph-of-purification
http://www.wowhead.com/spell=55677/glyph-of-purify
http://www.wowhead.com/spell=159628/glyph-of-shadow-magic
http://www.wowhead.com/spell=55692/glyph-of-smite
http://www.wowhead.com/spell=159624/glyph-of-the-inquisitor
Rogue:
http://www.wowhead.com/spell=159638/glyph-of-disappearance
Shaman:
http://www.wowhead.com/spell=159647/glyph-of-reactive-shielding
http://www.wowhead.com/spell=159648/glyph-of-shamanistic-resolve
http://www.wowhead.com/spell=101052/glyph-of-lightning-shield
http://www.wowhead.com/spell=63280/glyph-of-shamanistic-rage
http://www.wowhead.com/spell=159651/glyph-of-spiritwalkers-aegis
http://www.wowhead.com/spell=55446/glyph-of-spiritwalkers-grace
Warlock:
http://www.wowhead.com/spell=63302/glyph-of-drain-life
http://www.wowhead.com/spell=56238/glyph-of-health-funnel
http://www.wowhead.com/spell=159669/glyph-of-life-pact
http://www.wowhead.com/spell=63320/glyph-of-life-tap
http://www.wowhead.com/spell=56241/glyph-of-verdant-spheres
Warrior:
http://www.wowhead.com/spell=115946/glyph-of-burning-anger
http://www.wowhead.com/spell=58386/glyph-of-die-by-the-sword
http://www.wowhead.com/spell=159761/glyph-of-flawless-defense
http://www.wowhead.com/spell=159754/glyph-of-rallying-cry
http://www.wowhead.com/spell=94374/glyph-of-recklessness
http://www.wowhead.com/spell=58356/glyph-of-resonating-power
http://www.wowhead.com/spell=159759/glyph-of-shattering-throw
http://www.wowhead.com/spell=159703/glyph-of-the-drawn-sword
http://www.wowhead.com/spell=68164/glyph-of-thunder-strike

**Comment by Aveta** [comment]
Issues reporting some of the glyphs:
https://github.com/Valhalla-Gaming/Tracker/issues/5683
https://github.com/Valhalla-Gaming/Tracker/issues/5674
https://github.com/Valhalla-Gaming/Tracker/issues/5355

**Comment by ATalisan** [comment]
Good on you Aveta, I was working on compiling a list too, but didn't have a tenth of these.

**Comment by CageValhalla** [comment]
I can confirm this

**Comment by Aveta** [comment]
Since most glyphs aren't a thing anymore (and those that are are applied per spec) I'll close this.
