### ISSUE TITLE
Shaman: Lava Lash

### ISSUE THREAD

**Issue by nuhrii** [Valhalla-Gaming/Tracker#5694]
Tested the damage are target dummy and i am doing about 20%-30% less damage than is listed on the tooltip

**Comment by TheRealHoboo** [comment]
What dummy is it?

**Comment by nuhrii** [comment]
The standard level 85 dummy, not the raiders, but it shouldn't matter it does fire damage so it shouldn't be affected by armor. And this is fairly recent and i can't figure out what would causing this.
