### ISSUE TITLE
Charge on Warrior

### ISSUE THREAD

**Issue by zeefire05** [Valhalla-Gaming/Tracker#5699]
When I use Charge in BG, I immediately got DC after jumped from god knows where.

**Comment by Leondezwart** [comment]
u have the minor glyph of blazing trail?

**Comment by zeefire05** [comment]
In fact I am, is that the cause of it? Because I do not get the DC anymore now

**Comment by Luminescent-Valhalla** [comment]
Best way to check this would be charge with the glyph see if you DC and then remove and charge again this will give a indication if the glyph is causing the issue or not.
