### ISSUE TITLE
Common bug npcs

### ISSUE THREAD

**Issue by FlameChampion34** [Valhalla-Gaming/Tracker#57]
There's a common bug I found with few dead npcs, their names are "Laird, Decomposing Thistle Bear, Maranding poacher and Teronis corpse", the issue is that when you point to any of them, in the floating window where it shows what's his level or health, it also shows thing like 0 damage, 0 armor and "cannot be tamed", this info shouldn't really show up, it's supposed to be hidden, the only thing it should show is his level and health, also the dead npcs are with health, while they should be without health. 

Here are few screenshots to give you better example: 

http://store.picbg.net/pubpic/70/C7/7a03ae26bb6c70c7.jpg 

http://store.picbg.net/pubpic/02/83/e91ef0d8bfa70283.jpg

http://store.picbg.net/pubpic/2C/E4/61dc6f57d9832ce4.jpg

http://store.picbg.net/pubpic/1B/0E/4c1a15c87b241b0e.jpg

**Comment by Tregeta** [comment]
fixed next update
