### ISSUE TITLE
[Archaology][Alchemie][Recipe]

### ISSUE THREAD

**Issue by Aprophys** [Valhalla-Gaming/Tracker#5722]
Hello dear Devleopers

My issue is tha u cant get the recipe 
http://www.wowhead.com/item=67538/recipe-vial-of-the-sands
from 
http://www.wowhead.com/item=64657/canopic-jar
The dropchance is by 2-5% 
But after i asked an GM if this recipe is collecable, he tollds me its not scripted yet.
I hope u guys look for it.
Thank you

**Comment by Tregeta** [comment]
Drop rate does match, it will be very rare to obtain.
