### ISSUE TITLE
(blood elf) (quest) bugged?

### ISSUE THREAD

**Issue by foxman142** [Valhalla-Gaming/Tracker#5727]
the quest "powering our defenses" in Eversong wood does not work. i bring the infused crystal to the designated area and the item does not activate like it should.

**Comment by Braemen** [comment]
[#5516](https://github.com/Valhalla-Gaming/Tracker/issues/5516) and [#2803](https://github.com/Valhalla-Gaming/Tracker/issues/2803) :-)

**Comment by foxman142** [comment]
thanks much appreciated!

**Comment by Tregeta** [comment]
Duplicate
