### ISSUE TITLE
Vizzklick sells unlimited Pattern: Crimson Silk Robe

### ISSUE THREAD

**Issue by Reloque** [Valhalla-Gaming/Tracker#573]
Tailoring Supplies vendor [Vizzklick](http://www.wowhead.com/npc=6568)(6568) in Gadgetzan, Tanaris offers unlimited amounts of [Pattern: Crimson Silk Robe](http://www.wowhead.com/item=7088)(7088). This item should have a stock amount of one, which apparently replenishes after about three hours.

**Comment by Tregeta** [comment]
fixed
