### ISSUE TITLE
Paladin talent / enchanting

### ISSUE THREAD

**Issue by roguetwinky** [Valhalla-Gaming/Tracker#5730]
1st of wall there is paladin talent called (amrs of law ) which gives 45% movment speed for succefull judgment.... it was working like 5 months ago ... and now it is not working anymore .... 
2nd weapon enchants in enchanting profession  ... only 1 weapon encahnt work ... other weapon encahnts never proc

**Comment by Luminescent-Valhalla** [comment]
Please make separate reports for issues that way the developers can close a report when that issue has been fixed. Also Long Arm of the Law has already been reported as you can see here #5604

**Comment by Tregeta** [comment]
Please check first before reporting, duplicate otherwise, closing.
