### ISSUE TITLE
[Rogue ability] Shadow reflection

### ISSUE THREAD

**Issue by Bugdetective** [Valhalla-Gaming/Tracker#5731]
Whenever I use shadow reflection the shadow does appear, but at the end of it's "Copying time" it will just dissapear, without casting any ability.
Also, the trinkets/gear that summons companions, makes the shadow dissapear instantly when a companion is summoned.

**Comment by Tregeta** [comment]
http://www.wowhead.com/spell=152151/shadow-reflection

**Comment by Bombrick** [comment]
I reported this already and I was given a answer that the spells works correctly when it doesn't I hope you look into this.
