### ISSUE TITLE
Plz fix fishing!

### ISSUE THREAD

**Issue by miloskovac** [Valhalla-Gaming/Tracker#5736]
Hello ppl.
Plz fix fishing! Its already a long time it had been reported and it didnt get any progress...
The bobber dont react as intended and insteat says (after fish bites) 'Interrupt' so it sees fishing as a channeling spell and it interrupts on any action including clicking on bobber.

Funny thing is that fishing was ok before and it got screwed in process and since then it was not fixed.
Thank u

**Comment by Tregeta** [comment]
Duplicate
