### ISSUE TITLE
Shaman: Unleash Elements

### ISSUE THREAD

**Issue by nuhrii** [Valhalla-Gaming/Tracker#5737]
Don't know if its working as intended but Unleash Wind effect stacks are being consumed by Stormstrike and probably Lava Lash too, instead of basic auto attacks.

The Unleash Flame effect is not increasing the damage of Fire spells

http://www.wowhead.com/spell=73680
http://www.wowhead.com/spell=73681
http://www.wowhead.com/spell=73683

**Comment by Orunla** [comment]
yeah, while the attack speed should only be increased for the next 3 **swings**, our "Windfury" passive (the 3 extra **attacks** of main hand) consumes charges of unleash wind too, which is kinda bad since we have basically no charges after that procs...

**Comment by nuhrii** [comment]
Removed in Legion
