### ISSUE TITLE
Bloodied Arcanite Reaper Heirloom Not Working

### ISSUE THREAD

**Issue by Calibrunz** [Valhalla-Gaming/Tracker#5739]
I purchased the Arcanite Reaper from the store a while ago, and it was working fine until I made a new blood elf Paladin. The Heirloom doesn't show up for any of my characters anymore. Please help!

**Comment by Tregeta** [comment]
Change it to all classes in your menu, a short guide can be found here: https://valhalla-realms.com/forum/viewtopic.php?f=35&t=3962
