### ISSUE TITLE
Haughty Modiste sells unlimited Pattern: Dress Shoes

### ISSUE THREAD

**Issue by Reloque** [Valhalla-Gaming/Tracker#574]
Fashion Designer [Haughty Modiste](http://www.wowhead.com/npc=40572)(40572) in Gadgetzan, Tanaris sells an unlimited amount of [Pattern: Dress Shoes](http://www.wowhead.com/item=37915)(37915). This item should have a stock of one, which apparently replenishes after about twenty minutes.

**Comment by Tregeta** [comment]
fixed
