### ISSUE TITLE
Blizrik Buckshot sells unlimited Schematic: EZ-Thro Dynamite II

### ISSUE THREAD

**Issue by Reloque** [Valhalla-Gaming/Tracker#575]
Gunsmith [Blizrik Buckshot](http://www.wowhead.com/npc=8131)(8131) in Gadgetzan, Tanaris sells an unlimited amount of [Schematic: EZ-Thro Dynamite II](http://www.wowhead.com/item=18650)(18650). This item should have a stock amount of one, and apparently replenishes in under ten minutes.

**Comment by Tregeta** [comment]
fixed
