### ISSUE TITLE
Riding Skills

### ISSUE THREAD

**Issue by S1xEyes** [Valhalla-Gaming/Tracker#5754]
Logged in today and randomly lost all of my basic Riding skills. Lost [Apprentice Riding], [Journeyman Riding] and [Expert Riding]. But I kept [Flight Master's License] for some reason... I can still ride my mounts but can only travel at 100% ground speed and cannot fly.

**Comment by nuhrii** [comment]
Same thing happened to me but i went through a portal

**Comment by Tregeta** [comment]
This issue can be resolved by a high ranking GM and should no longer occur. Please post the required information at the link below so it can be resolved.
https://valhalla-realms.com/forum/viewtopic.php?f=26&t=5316
