### ISSUE TITLE
Warlock [pet bar]

### ISSUE THREAD

**Issue by W0lf91** [Valhalla-Gaming/Tracker#5759]
Hi,
when i summon the pet the "Pet Bar" is invisible. I tried deleting the folder cache and reload, but nothing happened.
Thanks :)

**Comment by Tregeta** [comment]
If you are below 10 your pet bar will not be visible.

**Comment by W0lf91** [comment]
ok perfect!
Thanks for the answer ^^

**Comment by Tregeta** [comment]
Not a problem, as this looks like it resolved your issue will be closing now.
