### ISSUE TITLE
Alchemist Pestlezugg sells unlimited Alchemy recipes

### ISSUE THREAD

**Issue by Reloque** [Valhalla-Gaming/Tracker#576]
Two of the recipes sold by [Alchemist Pestlezugg](http://www.wowhead.com/npc=5594)(5594) in Gadgetzan, Tanaris should be limited to a stock of 1: [Recipe: Transmutate Mithril to Truesilver](http://www.wowhead.com/item=9305)(9305) and [Recipe: Nature Protection Potion](http://www.wowhead.com/item=6057)(6057). Apparently both recipes take about twenty minutes to restock.

**Comment by Tregeta** [comment]
fixed
