### ISSUE TITLE
Netherwing Questline

### ISSUE THREAD

**Issue by TheGallahad** [Valhalla-Gaming/Tracker#5762]
It seems the Questline stops after [The Force of Neltharaku](http://www.wowhead.com/quest=10854/the-force-of-neltharaku) and cannot continue [Karynaku](http://www.wowhead.com/quest=10858/karynaku)

 Also [Zuluhed the Whacked](http://www.wowhead.com/npc=11980/zuluhed-the-whacked) is missing.
http://i.imgur.com/KY2Rl5i.jpg

**Comment by Tregeta** [comment]
Unable to replicate, please seek a GM in possibly removing/resetting/acquiring the quest.
