### ISSUE TITLE
[Vashjr] Fatigue

### ISSUE THREAD

**Issue by CageValhalla** [Valhalla-Gaming/Tracker#5768]
Fatigue losing all over Vashjr, and even while dead. Then player gets bugged out and constantly ported to graveyard

**Comment by Braemen** [comment]
[#4422](https://github.com/Valhalla-Gaming/Tracker/issues/4422) and [#3535](https://github.com/Valhalla-Gaming/Tracker/issues/3535)

**Comment by Tregeta** [comment]
duplicate
