### ISSUE TITLE
Cleansing Witch Hill

### ISSUE THREAD

**Issue by Goodless** [Valhalla-Gaming/Tracker#5780]
[http://www.wowhead.com/quest=27190/cleansing-witch-hill](url)

Witchbane Torch not works

**Comment by Braemen** [comment]
[#1793](https://github.com/Valhalla-Gaming/Tracker/issues/1793) and [#1260](https://github.com/Valhalla-Gaming/Tracker/issues/1260)

**Comment by Tregeta** [comment]
duplicate
