### ISSUE TITLE
[Druid] [Talent] Dead (ghost) healing try

### ISSUE THREAD

**Issue by Andret1** [Valhalla-Gaming/Tracker#5783]
After getting level 30 as druid I can chose the Talent from second row. The first one infinitely heals me 4%. It is trying to heal me also, when I'm dead, and I still get messages "You are dead" at the top.

**Comment by Andreder** [comment]
The talent in question is [Ysera's Gift](http://www.wowhead.com/spell=145108/yseras-gift)
