### ISSUE TITLE
Insight is broken

### ISSUE THREAD

**Issue by SanDrilLa187** [Valhalla-Gaming/Tracker#5785]
At the Moment i only get the shallow Insight, you can hit and hit and hit, but don´t become moderate or deep Insight. A few weeks ago, it was all normal, i get all Insights.
Thanks and good day...........

**Comment by Braemen** [comment]
[#5464](https://github.com/Valhalla-Gaming/Tracker/issues/5464)

**Comment by Tregeta** [comment]
duplicate
