### ISSUE TITLE
Tormmok

### ISSUE THREAD

**Issue by LordLupusDei** [Valhalla-Gaming/Tracker#5834]
In Draenor is npc found in Gorgrond called Tormmok Ogre Centurion . Grou that he leads was ambushed by that Flower guys and only he remains . When we come there shoud be interaction with him > Starts the quest > survive 3 waves > got Follower > yeeeey 

but now we cant start Quest so its unvaiable.

**Comment by Braemen** [comment]
#3927 and #4312

**Comment by Tregeta** [comment]
Duplicate
