### ISSUE TITLE
[Worgen][Druid] Movement stacking

### ISSUE THREAD

**Issue by CageValhalla** [Valhalla-Gaming/Tracker#5841]
Darkflight doesn't stack up on Dash.

[http://www.wowhead.com/spell=68992/darkflight](url)
[http://www.wowhead.com/spell=1850/dash](url)

**Comment by nuhrii** [comment]
Close this, i believe this is working as intended. In patch 6.0.2 movement bonuses that are temporary do not stack and only the one with the highest bonus will be applied
http://us.battle.net/wow/en/blog/15682579/the-iron-tide-602-patch-notes-10-13-2014#movement_speed

**Comment by Tregeta** [comment]
After testing, these spells do not stack.
