### ISSUE TITLE
Quest: Putting Olakin Back Together Again

### ISSUE THREAD

**Issue by ATalisan** [Valhalla-Gaming/Tracker#5843]
The Spool of Thread and Cleaver do not spawn
So the quest cannot be completed

**Comment by Braemen** [comment]
[Spool of Thread](http://www.wowhead.com/object=193091/spool-of-thread)
[The Doctor's Cleaver](http://www.wowhead.com/object=193092/the-doctors-cleaver)

**Comment by Tregeta** [comment]
should be spawned now
