### ISSUE TITLE
Quest: Honor is for the Weak

### ISSUE THREAD

**Issue by ATalisan** [Valhalla-Gaming/Tracker#5848]
Interacting with the Eye of Domination in the Ebon camp successfully turns you into a Eidolon Watcher
However, you hike your ass down the road towards the Weeping Quarry and you immediately lose the form
Therefore you cannot use the Watcher's ability to assassinate the Restless Lookouts

Also note it bugs your primary weapon

**Comment by Tregeta** [comment]
Ref #5685
