### ISSUE TITLE
[Item] Precious Bloodthorn Loop

### ISSUE THREAD

**Issue by nuhrii** [Valhalla-Gaming/Tracker#5854]
Provides the wrong stats, is giving 37 Spirit rather than Versatility

http://www.wowhead.com/item=113082&bonus=0

**Comment by Aveta** [comment]
Spirit was removed with Legion pre-patch and was replaced with Versatility on gear. We don't have Legion pre-patch changes introduced yet thus Spirit being there is still correct for now.

**Comment by Tregeta** [comment]
Issue is now resolved.
