### ISSUE TITLE
[Northern Barrens] Kor'kron MOBs

### ISSUE THREAD

**Issue by menelkir** [Valhalla-Gaming/Tracker#5868]
In official servers, those orcs (level 90 if I remember) are yellow and they're red here. 
Isn't really a bug, but will make the life of low level players a bit hard, since they'll aggro from a long distance.

Some of them are near spirit healers, for example.

**Comment by Tregeta** [comment]
Ref - https://github.com/Valhalla-Gaming/Tracker/issues/3840
