### ISSUE TITLE
[Quest] [Dwarf] Follow that Gyro-Copter | No NPC + Copter after a re-log

### ISSUE THREAD

**Issue by damiongans** [Valhalla-Gaming/Tracker#5869]
Questgiver ID: 6782
Quest ID: 24491
NPC ID: 37113

When accepting this quest the questgiver does the right animation (shooting stuff in the air), and the NPC + copter do appear. But, after a re-log they disappear, while the quest is still in the quest log. Abandoning and retaking the quest does work.

[After accepting]
![wowscrnshot_080516_101248](https://cloud.githubusercontent.com/assets/20154922/17430586/460561f2-5af5-11e6-8847-51d633fa22ea.jpg)

[After re-log]
![wowscrnshot_080516_100359](https://cloud.githubusercontent.com/assets/20154922/17430543/13733c32-5af5-11e6-841c-54c249057fb4.jpg)

**Comment by Guybrush-VR** [comment]
It should be fixed next update! If it's not the case, comment here again? :)
