### ISSUE TITLE
[Flight] [Dwarf] Helicopter flight after the quest: Pack your bags is way too slow

### ISSUE THREAD

**Issue by damiongans** [Valhalla-Gaming/Tracker#5870]
The fight starts after completion of quest ID: 24492

The flight does work, but is way too slow. I forget to record the slow flight, but here's a video how it is on retail: https://www.youtube.com/watch?v=WU10NZj2gSQ.

Also, the announcements made by Mylo's Gyro (ID: 37169) while the flight is going are showing up in chat, but not as balloons above the copter.

Those announcements are fast enough, but does not represent what they tell, like the fact that Gnomeregan is to the left, because the flight is too slow.

**Comment by Guybrush-VR** [comment]
Not slow anymore, It'll fly like a butterfly! Fixed in next update.
