### ISSUE TITLE
Giant Purse of Timeless Coins

### ISSUE THREAD

**Issue by Braemen** [Valhalla-Gaming/Tracker#5874]
This item ([Giant Purse of Timeless Coins](http://www.wowhead.com/item=104035/giant-purse-of-timeless-coins)) can't be opened (with given error "You can't loot that item now").
As of wowhead comments, it should contain from 500 to 1500 [Timeless Coins](http://www.wowhead.com/currency=777/timeless-coin).

**Comment by Tregeta** [comment]
Fixed Next Update
