### ISSUE TITLE
[Fishing] Journeyman Fishing doesn't unlock 150 skill

### ISSUE THREAD

**Issue by Braemen** [Valhalla-Gaming/Tracker#5875]
Premise: I learned [Apprentice Fishing](http://www.wowhead.com/spell=7620/fishing) (spell id: 7620) and [Journeyman Fishing](http://www.wowhead.com/spell=7731/fishing) (spell id: 7731) from fishing trainer.
As of title, any trainer shows up the option to learn the next step: [Expert Fishing](http://www.wowhead.com/spell=7732/fishing) (required: Fishing 125), but I can't learn it because I don't have the right spell ([Journeyman Fishing](http://www.wowhead.com/spell=64485/journeyman-fishing), spell id: 64485), that can bring me up to 150 fishing skill.

P.S. I know fishing is bugged, but you can still gain skills with dailies.

**Comment by Tregeta** [comment]
You wll need to speak with Warjakh to have it reset. For a bit more information, what trainer did you learn the journeyman fishing from?

**Comment by Braemen** [comment]
Can't remember the exact trainer (it happened some time ago), but I tried several.

**Comment by Braemen** [comment]
I can close it... Tregeta fixed for me :smile:
