### ISSUE TITLE
[Event] Darkmoon Faire Quest Items

### ISSUE THREAD

**Issue by Braemen** [Valhalla-Gaming/Tracker#5877]
Quest items like [Monstrous Egg](http://www.wowhead.com/item=71636/monstrous-egg) begins repeatable quests (you can repeat quests once every Darkmoon Faire event, so once per month).
First time the quest works, but next time (with another identical item, even after 2 months) you can't still repeat the quest (quest item gives the error "You are already on that quest" when you click on it).

Here a complete list of Darkmoon Faire quest items (with quests):
-  [Monstrous Egg](http://www.wowhead.com/item=71636/monstrous-egg) ->  [An Exotic Egg](http://www.wowhead.com/quest=29444/an-exotic-egg)
-  [Fallen Adventurer's Journal](http://www.wowhead.com/item=71953/fallen-adventurers-journal) ->  [The Captured Journal](http://www.wowhead.com/quest=29458/the-captured-journal)
- [Banner of the Fallen](http://www.wowhead.com/item=71951/banner-of-the-fallen) ->  [A Captured Banner](http://www.wowhead.com/quest=29456/a-captured-banner)
- [Captured Insignia](http://www.wowhead.com/item=71952/captured-insignia) ->  [The Enemy's Insignia](http://www.wowhead.com/quest=29457/the-enemys-insignia)
- [Imbued Crystal](http://www.wowhead.com/item=71635/imbued-crystal) ->  [A Curious Crystal](http://www.wowhead.com/quest=29443/a-curious-crystal)
- [Mysterious Grimoire](http://www.wowhead.com/item=71637/mysterious-grimoire) ->  [An Intriguing Grimoire](http://www.wowhead.com/quest=29445/an-intriguing-grimoire)
- [Ornate Weapon](http://www.wowhead.com/item=71638/ornate-weapon) ->  [A Wondrous Weapon](http://www.wowhead.com/quest=29446/a-wondrous-weapon)
- [Soothsayer's Runes](http://www.wowhead.com/item=71716/soothsayers-runes) ->  [Tools of Divination](http://www.wowhead.com/quest=29464/tools-of-divination)
- [A Treatise on Strategy](http://www.wowhead.com/item=71715/a-treatise-on-strategy) ->  [The Master Strategist](http://www.wowhead.com/quest=29451/the-master-strategist)

**Comment by Tregeta** [comment]
Should be fixed next update
