### ISSUE TITLE
[Quest] Zuluhed the Whacked

### ISSUE THREAD

**Issue by Braemen** [Valhalla-Gaming/Tracker#5878]
On horde side there's no problem with this quest.
On ally side, NPC [Karynaku](http://www.wowhead.com/npc=22112/karynaku) doesn't give the quest ([Zuluhed the Whacked](http://www.wowhead.com/quest=10866/zuluhed-the-whacked), id: 10866).

I asked a GM so he resetted and gives the quest to me, but NPC that I need to kill ([Zuluhed the Whacked](http://www.wowhead.com/npc=11980/zuluhed-the-whacked)) still doesn't spawn (and GMs can't spawn NPCs for players, I know :smile:).

I also noticed that there's a deprecated version of this quest (only for ally, while the right one is for both factions): [Zuluhed the Whacked](http://www.wowhead.com/quest=10872/zuluhed-the-whacked), id: 10872. Maybe this can be a problem?

P.S. I posted this issue because of [this](https://github.com/Valhalla-Gaming/Tracker/issues/5762) and [this](https://github.com/Valhalla-Gaming/Tracker/issues/5547), and because I'm sure this quest is bugged.

P.P.S. Maybe this is not related to the issue, but I also noticed that near the quest giver there's an NPC that spams an harmful spell against player and nearby mobs, killing them. [This](http://www.wowhead.com/npc=22332/brood-of-neltharaku) is the NPC and [this](http://www.wowhead.com/spell=38906/arcane-breath-chain) is the spell.

Here there's a video example:
[![[Valhalla Realm] Arcane Breath Chain spell spam](https://img.youtube.com/vi/TmTpY7pM4fc/0.jpg)](https://www.youtube.com/watch?v=TmTpY7pM4fc)

**Comment by Tregeta** [comment]
Still unable to reproduce, perhaps you would be able to film the entire questline for us. As after running it on our own plays out fine with no error of retrieving the quest.

**Comment by Braemen** [comment]
Ok, I will try to film the entire questline. Stay tuned :smile:

**Comment by Braemen** [comment]
Update: I tried the entire questline with an alt and... was unable to reproduce the problem :smile:
By the way I solved that problem: with that alt I took the quest (mob spawned normally) and then I was able to finish it with my main.

Now there's another problem: NPC still doesn't give me the next quest (), the final one. I think I'm totally bugged :smile:

Here the entire questline videos, for completeness:

[Kindness](http://www.wowhead.com/quest=10804/kindness)
[![[Valhalla Realm][Quest] Kindness](https://img.youtube.com/vi/608uCaN__Yo/0.jpg)](https://www.youtube.com/watch?v=608uCaN__Yo)

[Seek Out Neltharaku](http://www.wowhead.com/quest=10811/seek-out-neltharaku) + [Neltharaku's Tale](http://www.wowhead.com/quest=10814/neltharakus-tale) + [Infiltrating Dragonmaw Fortress](http://www.wowhead.com/quest=10836/infiltrating-dragonmaw-fortress) + [To Netherwing Ledge!](http://www.wowhead.com/quest=10837/to-netherwing-ledge)
[![[Valhalla Realm][Quest] Seek Out Neltharaku → To Netherwing Ledge!](https://img.youtube.com/vi/H1ltlkwcaZM/0.jpg)](https://www.youtube.com/watch?v=H1ltlkwcaZM)

[The Force of Neltharaku](http://www.wowhead.com/quest=10854/the-force-of-neltharaku) + [Karynaku](http://www.wowhead.com/quest=10858/karynaku)
[![[Valhalla Realm][Quest] The Force of Neltharaku + Karynaku](https://img.youtube.com/vi/XwAt9pA_ZeI/0.jpg)](https://www.youtube.com/watch?v=XwAt9pA_ZeI)

[Zuluhed the Whacked](http://www.wowhead.com/quest=10866/zuluhed-the-whacked) + [Ally of the Netherwing](http://www.wowhead.com/quest=10870/ally-of-the-netherwing)
[![[Valhalla Realm][Quest] Zuluhed the Whacked + Ally of the Netherwing](https://img.youtube.com/vi/u8E0y3O4Ak0/0.jpg)](https://www.youtube.com/watch?v=u8E0y3O4Ak0)

I will try to contact Warjakh when online, for adding me the last one.

**Comment by chamakmak** [comment]
Hi,

For new player and new alt the questline work without any problem, we have a problem with our main wish we did the questline before last fix for this reputation.

And i m available in game if any GM can reset quest, to know wish quest fix questline for old player.

**Comment by Tregeta** [comment]
To get the Ally of the Netherwing you must first have Master Riding if not mistaken.

**Comment by Braemen** [comment]
Artisan, but I have Master
