### ISSUE TITLE
[Class][Warlock]Warlock Metamorphosis

### ISSUE THREAD

**Issue by EldritchIHC** [Valhalla-Gaming/Tracker#5881]
If I use The demon form of ShadowBolt(after using Metamorphosis) my chracter gets out of demon form.This issue makes the demon form a bit unusable.

**Comment by EldritchIHC** [comment]
While in demon form ,If i use shadow bolt or soul fire I imediately get out of the demon form and i still have enough demonic fury.The same happens when killing an enemy with other spells.I dont see the point in fixing this problem since Legion will change the Warlock class anyways.

**Comment by nuhrii** [comment]
I just remembered Shadow Bolt changes into a Touch of Chaos while in metamorphosis, so casting shadow bolt will take you out of metamorphosis. So this is not an issue and close this.
