### ISSUE TITLE
[Draenor Treasure] Webbed Sac

### ISSUE THREAD

**Issue by Braemen** [Valhalla-Gaming/Tracker#5883]
[Webbed Sac](http://www.wowhead.com/object=228019/webbed-sac) contains [Dessicated Orc's Coin Pouch](http://www.wowhead.com/item=116129/dessicated-orcs-coin-pouch) correctly but, when you try to open the pouch, nothing happens.
Item turns grey and then (after reopening the bag) vanished.

**Comment by Tregeta** [comment]
fixed next update
