### ISSUE TITLE
[NPC] Engorged Mushroom

### ISSUE THREAD

**Issue by Braemen** [Valhalla-Gaming/Tracker#5892]
[Engorged Mushroom](http://www.wowhead.com/npc=80716/engorged-mushroom): these mobs should not move, but could only attack nearby enemies with [this ability](http://www.wowhead.com/spell=163083/spore-explosion) (as you can see [here](https://www.youtube.com/watch?v=ddsApd63fIU)). They are present in [Crimson Fen](http://wowwiki.wikia.com/wiki/Crimson_Fen) area.

Two screenshots of the possible variants:

![Engorged Mushroom](http://i.imgur.com/fh10Bop.jpg)
![Engorged Mushroom](http://i.imgur.com/fiRchG0.jpg)

**Comment by Tregeta** [comment]
Fixed next update.
