### ISSUE TITLE
Quest: Test Your Strength (Darkmoon Faire)

### ISSUE THREAD

**Issue by VictorTyne** [Valhalla-Gaming/Tracker#5893]
http://www.wowhead.com/quest=29433/test-your-strength

This quest is not currently repeatable, although you can continue to accumulate [Grisly Trophy] as long as you are holding [Darkmoon Adventurer's Guide].

You should be able to turn in this quest again each time the Darkmoon Faire opens.

**Comment by Tregeta** [comment]
fixed next update, for reference this is a monthly quest.
