### ISSUE TITLE
[Object] Pippers' Buried Supplies

### ISSUE THREAD

**Issue by Braemen** [Valhalla-Gaming/Tracker#5897]
Pippers' Buried Supplies contains nothing when looted.
It should contain [Garrison Resources](http://www.wowhead.com/currency=824/garrison-resources).

There are 4 versions of this object:
[Pippers' Buried Supplies 1](http://www.wowhead.com/object=232248/pippers-buried-supplies): [video](https://www.youtube.com/watch?v=xbBEGtc3Kx4)
[Pippers' Buried Supplies 2](http://www.wowhead.com/object=232250/pippers-buried-supplies): [video](https://www.youtube.com/watch?v=9kw7cNyADB4)
[Pippers' Buried Supplies 3](http://www.wowhead.com/object=232251/pippers-buried-supplies): [video](https://www.youtube.com/watch?v=SyWlwEdg6EY)
[Pippers' Buried Supplies 4](http://www.wowhead.com/object=232252/pippers-buried-supplies): [video](https://www.youtube.com/watch?v=_FKH5_OzgfM)

**Comment by Tregeta** [comment]
Fixed next update
