### ISSUE TITLE
[Spell][Paladin] Word of Glory

### ISSUE THREAD

**Issue by Lebiedz** [Valhalla-Gaming/Tracker#5898]
**What is bugged**:
This spell is partially sharing global cooldowns with other spells. What I mean by partial sharing is that if I want to use it after (for example) Crusader Strike, I have to wait 1,5 sec for the GCD to pass. The following use of Word of Glory, however, doesn't induce global cooldown on damaging abilities (such as Crusader Strike).

**How it should work:**
It should be possible to use Word of Glory (or Eternal Flame, if talented) regardless of the GCD.

**Link:**
Due to recent changes in wowhead's database connected with upcoming Legion's release, I can't provide wowhead's link to this spell. So I'll just hope that link will be enough: [Word of Glory](http://www.wowdb.com/spells/85673-word-of-glory)

**Comment by GM-Pyromanic** [comment]
Word of glory does have a GCD as can be seen in the following screen shot taken from a internet archive dated 21st April 2016.
![firefox_2016-08-14_22-08-38](https://cloud.githubusercontent.com/assets/20587569/17652087/d39b0a94-626b-11e6-903a-6659ea7acc02.png)

**Comment by Lebiedz** [comment]
Ok, then there is a bug with that the GCD isn't being shown on the spell icon. It's seen as if it wasn't affected by the GCD.

**Comment by GM-Pyromanic** [comment]
GCD is showing on Word of Glory for me on one of my play characters (Blured pixels added to hide my transmog and guild message of the day)
![firefox_2016-08-15_00-12-27](https://cloud.githubusercontent.com/assets/20587569/17652743/f4867868-627c-11e6-8d08-1c122e20cf83.png)

**Comment by Lebiedz** [comment]
I've done more research now. And from what I've found, the GCD for WoG is removed for protection specialization (which is my paladin's) due to Guarded by the Light passive effect (applied when choosing protection specialization).

Proof (version updated in 6.0.2 while, as you can see, next change was made in Legion):
![screenshot_27](https://cloud.githubusercontent.com/assets/13126019/17652868/c3483ce4-6288-11e6-9713-cba7d9147a15.png)

I don't know why my mouse cursor haven't been captured, but at the time of making the screenshot I was mousing over the highlighted row.

We are both right. In general, for retribution and holy specializations (as your proof shows) WoG is affected by the GCD. It is not on GCD only for protection paladins.
