### ISSUE TITLE
Hunter

### ISSUE THREAD

**Issue by Goodless** [Valhalla-Gaming/Tracker#5915]
When i attack a Mob the Pet will lost and i become a Nagrad Wolf buff.about this buff my Pet is not in Stable.I take the second Pet and it is the same

**Comment by Tregeta** [comment]
Please make sure you don't have a trinket that summons anything and then try.

**Comment by Goodless** [comment]
[http://www.wowhead.com/item=118246/call-of-the-wolfmother&bonus=0](url)

Thats delete the pets =(

**Comment by Tregeta** [comment]
Yes, the items that currently summon a pet as a guardian are actually overwriting your current pet and removing it basically, we're working on it.

**Comment by Goodless** [comment]
Nice thx =)
