### ISSUE TITLE
[Quest] Gorat's Vengeance

### ISSUE THREAD

**Issue by LamByh** [Valhalla-Gaming/Tracker#5932]
Cant use the quest item on Gorat . So i cant kill the quest mob. 

Link : http://www.wowhead.com/quest=13621/gorats-vengeance

**Comment by Seregruth** [comment]
That quest has already been reported. #1744
In the future please check if the quest has already been reported :)

**Comment by Braemen** [comment]
even #4268, to be precise :smile:

**Comment by Seregruth** [comment]
Already Reported #1744
