### ISSUE TITLE
Issue to connect 

### ISSUE THREAD

**Issue by LordLupusDei** [Valhalla-Gaming/Tracker#5934]
Please someone help 
![desktop capture-08-30-2016 17-18-31-974](https://cloud.githubusercontent.com/assets/19625389/18095137/45a03094-6ed6-11e6-8280-f6726687742d.jpg)

**Comment by Goodless** [comment]
Read the info.about the 31 is release.after 31 is log in =)

**Comment by Tregeta** [comment]
Please post connection issues on our forums so that our GM team can help you resolve them.
