### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by krasimir32** [Valhalla-Gaming/Tracker#5936]
I am again and again getting an error ,( unable to connect with (blz51901002) after all the text.

**Comment by bureklover** [comment]
i have the same problem.. :O  did u fix it ? and if u did then how ?

**Comment by krasimir32** [comment]
nope didnt fix but ...they said they are doing Preparations for the Legion realm so just wait

**Comment by GM-Pyromanic** [comment]
We are aware of the issue please refer to https://valhalla-realms.com/forum/viewtopic.php?f=2&t=5613

**Comment by Tregeta** [comment]
Please post connection issues on our forums so that our GM team can help you resolve them.
