### ISSUE TITLE
unable to connect with (blz51901002)

### ISSUE THREAD

**Issue by bureklover** [Valhalla-Gaming/Tracker#5938]
Can someon help me,i cant connect on wow it say Unable to connect please try again later unable to connect with (blz51901002) ???

**Comment by Joker13783** [comment]
same Problems here, anyone can help?

**Comment by ILKES** [comment]
same Problems here, anyone can help?

**Comment by bludgos23** [comment]
yes bro bad problam i can't connect server unable to connect blz51901002 error pls helpppp

**Comment by GM-Pyromanic** [comment]
We are aware od the issue please refer to this topic https://valhalla-realms.com/forum/viewtopic.php?f=2&t=5613&start=130

**Comment by Tregeta** [comment]
Please post connection issues on our forums so that our GM team can help you resolve them.
