### ISSUE TITLE
A problem.

### ISSUE THREAD

**Issue by krasimir32** [Valhalla-Gaming/Tracker#5939]
it is not a probem just asking ....are you gonna tell us on the web site if the server is up and running ?

**Comment by bureklover** [comment]
I think server is online but they cant fix our problem..... (blz51901002)

**Comment by Collector-Valhalla** [comment]
Join Discord for any news or just stay at forum. GitHub is for bug reports.

**Comment by Tregeta** [comment]
Please post connection issues on our forums so that our GM team can help you resolve them.
