### ISSUE TITLE
Artefact weapon

### ISSUE THREAD

**Issue by shadowshinobi11** [Valhalla-Gaming/Tracker#5944]
Warrior fury artefact weapon spawns only one sword

**Comment by Tregeta** [comment]
Please try equipping the weapon first. It should place a second one in your offhand slot automatically.

**Comment by h0bb1tz** [comment]
Tregeta is right. I did report this bug, but then it didnt work, i dont know if u made it work or we just did it wrong.When i had empty hands, i just right clicked weapon and got both of them.
