### ISSUE TITLE
Just started a hunter and i cant call my pet?

### ISSUE THREAD

**Issue by Elmertusk** [Valhalla-Gaming/Tracker#5945]

**Comment by Tregeta** [comment]
Need more information, do you currently have a pet out already? What race, faction?

**Comment by Elmertusk** [comment]
I was playing a troll hunter and I start the game without a pet so I assumed if I called it then it would spawn but it didn't so I tried to revive which did the cast but nothing happened.
Hope that helps at all

**Comment by Tregeta** [comment]
Did you try to create another one just to be safe?

**Comment by Elmertusk** [comment]
Couldn't the server went offline :/

**Comment by Tregeta** [comment]
Alrighty, please let me know on a follow up when we're online again if possible.

**Comment by Moustachos** [comment]
Ref #5979
