### ISSUE TITLE
Clean Up Bag

### ISSUE THREAD

**Issue by Jefferythegod** [Valhalla-Gaming/Tracker#5947]
the issue is when i move my hearthstone in another place in the bag, after i press Clean Up Bag It doesn't move and it goes from normal to grey and its unclickable.
![image](https://cloud.githubusercontent.com/assets/21697206/18188878/fc226798-70b5-11e6-8a41-0ab21e398fb9.png)

**Comment by Tregeta** [comment]
Ref #2529
