### ISSUE TITLE
Can not Create Gnome hunters.

### ISSUE THREAD

**Issue by GM-Pyromanic** [Valhalla-Gaming/Tracker#5948]
After creating a Gnome hunter you get the following error.  "Error Creating Character" 

![2016-09-02_01-34-48](https://cloud.githubusercontent.com/assets/20587569/18188898/c68076aa-70ad-11e6-9740-edf2c8561210.jpg)

**Comment by Traveler-Valhalla** [comment]
Seriously I want to play gnome hunter really bad.

**Comment by g0908** [comment]
I second that! Gnome hunter :D.

**Comment by Traveler-Valhalla** [comment]
you can create gnome hunters now
