### ISSUE TITLE
Warlock spell - drain life

### ISSUE THREAD

**Issue by Pravlad** [Valhalla-Gaming/Tracker#5953]
I just started new warlock and there is problem with starting abbility- drain life it deals just 1Dmg...
You can see it in combat log
![wowscrnshot_090216_023540](https://cloud.githubusercontent.com/assets/18075013/18188986/f2331e02-70b6-11e6-953a-8f6208217d14.jpg)

**Comment by poxol25** [comment]
i have the same error and the imp dont attack.

**Comment by Pravlad** [comment]
strange, imp worked fine for me, I didn't have pet action bar but I think this becomes available on level 10.

**Comment by Pravlad** [comment]
Another problem- destro/demon warlock can use drain life too, should be affi only

**Comment by nuhrii** [comment]
According to wowhead all warlocks have access to drain life, just that its affliction warlock's filler spell
http://www.wowhead.com/spell=689

**Comment by Reaper996** [comment]
Wowhead is wrong about this one.

Life drain should deal 40% of spell power (intellect) per tic and heal 600%

**Comment by Lorelai-Hellscream** [comment]
This is also affected by the fact that "Secrets of the Neophyte", a passive effect in the Affliction specialization is broken.  It is supposed to boost the damage of Drain Life.

**Comment by Reaper996** [comment]
That passive actually works, it just increases damage for 100% instead of 200% and you cannot notice it working because the damage of drain life is extremely low..

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #5979
