### ISSUE TITLE
Rogue Spell: Multilate

### ISSUE THREAD

**Issue by Jefferythegod** [Valhalla-Gaming/Tracker#5957]
![image](https://cloud.githubusercontent.com/assets/21697206/18189082/bcd0ab84-70b7-11e6-9f08-370da39ae0fd.png)
Problem: I don't get 2 Combo Points as it says in the Spell Describtion.
How it should work: Attack with both weapons, dealing a total % Physical damage. Awards 2 Combo Points

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #5979
