### ISSUE TITLE
Undead Starting Zone

### ISSUE THREAD

**Issue by Emberflame** [Valhalla-Gaming/Tracker#5960]
hello to you all,
It seems that there is no quest whatsoever in the undead Starting zones,and we don't get our basic spell as well.

**Comment by Tregeta** [comment]
Need more information. What class are you playing?

**Comment by Emberflame** [comment]
I'm playing a mage

**Comment by Tregeta** [comment]
Ref to mage spells #5937

**Comment by Seregruth** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Dh1t3jGb&#x2F;13-horde-forsaken-1-5"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> HORDE • Forsaken (1-5)</a>

**Comment by Seregruth** [comment]
Fixed in next update.
