### ISSUE TITLE
[Paladin][Spell] Consecration

### ISSUE THREAD

**Issue by keyna** [Valhalla-Gaming/Tracker#5968]
http://www.wowhead.com/spell=26573/consecration
Deals very low damage.

**Comment by Tregeta** [comment]
Ref #5944

**Comment by MichRattay** [comment]
update :D doesn't deal dmg, has no visual effect

**Comment by Laevoth** [comment]
Consecration works when specialized in protection, but does not work when selecting the talent when Retribution specialization is selected. It generates an invisible placeholder that mobs can freely attack, while the spell itself does absolutely nothing. An NPC/Ally appears on minimap where consecration was placed.

**Comment by Moustachos** [comment]
Ref #5979
