### ISSUE TITLE
Warrior Heroic Leap

### ISSUE THREAD

**Issue by h0bb1tz** [Valhalla-Gaming/Tracker#5970]
Heroic Leap doesn't work.

**Comment by Matija5** [comment]
Can confirm, heroic leap doesn't work

**Comment by Nienz** [comment]
i will add few things here then, arms warr heroic leap has 45 second cooldown, but its actually 1.5min long and yes heroic leap works somehow after rogue updates, awesome!

**Comment by Moustachos** [comment]
Ref #5979
