### ISSUE TITLE
Mailbox Crash

### ISSUE THREAD

**Issue by TheGallahad** [Valhalla-Gaming/Tracker#5976]
Opening mailboxes crashes the game giving a #132 error.

**Comment by Valhalla-Gaming** [comment]
Can you please provide some additional information? For example, what kind of items do you expect to have in your mailbox (if any). We are not able to reproduce this issue.

**Comment by TheGallahad** [comment]
I do have the [Mountain-o-Mounts](http://www.wowhead.com/achievement=2536/mountain-o-mounts) Achievement Bug. The problem is i cannot check what items are in my mailbox because the moment i click on it the game immediately crashes

**Comment by Valhalla-Gaming** [comment]
Thank you, we'll look into that.

**Comment by TheGallahad** [comment]
A little more testing and i have mails from Customer Support and from Mei Francis. 
I now got a "not enough memory error". Going to try different mailboxes.

**Comment by llamalama** [comment]
I can confirm I have the Mountain o Mounts Achievement and my game crashed when I used my mail box also with the memory error. I had mail from Mei Francis and Customer Support as well.  I have no idea what was in the customer support mail, but I assumed it was my off-hand weapon because it completely vanished from my character.

**Comment by Trekex** [comment]
Mine is not crashing. I have only the mount mail

**Comment by TheGallahad** [comment]
I think the problem is with chars with dual wielded weapons equipped before the upgrade to legion. My Frost DK spawned with only one of his swords and the other one is missing which i assume is in the customer support mail. More testing is still advised. will try on a different class next time.

**Comment by llamalama** [comment]
I checked on my rogue and her offhand weapon was not missing and was able to use her mail just fine. My enhancement shaman's offhand weapon was gone and her weapon arrived in Customer Support, but she was able to use the mail with no problem. It seems like it might be a Frost DK problem?

**Comment by Bombrick** [comment]
Once I open the mailbox I crash with the message "Not enough memory"

**Comment by forstix** [comment]
i got "not enough memory" error when i press H for bg/arena tab

**Comment by GAMMARAYS** [comment]
Is this still happening?
