### ISSUE TITLE
Unable to Connect.

### ISSUE THREAD

**Issue by Hemowow** [Valhalla-Gaming/Tracker#5980]
Hello,I live in SE (Southeast Europe)(Croatia)and i've seen that the realms are online.but i can't enter the realm.It says:-
Unable to connect. please try again later. (BLZ51901001).

I tried everything to fix it i was looking at the forums and the fixes weren't working for me.Help would be appreciated.

Hemowow-lvl 11 started year ago but quit and im back for legion.

**Comment by Cud0ri** [comment]
BLZ51901001 code means Server is offline.

**Comment by Hemowow** [comment]
Okay Thank you ! :)
