### ISSUE TITLE
[Monk][Spell] Tiger Palm + [Monk][Spell] Blackout Strike

### ISSUE THREAD

**Issue by SasoriDanna** [Valhalla-Gaming/Tracker#5987]
http://www.wowhead.com/spell=100780/tiger-palm
The spell doesn't cast.

+
http://www.wowhead.com/spell=205523/blackout-strike
Spell also doesn't cast.

**Comment by Moustachos** [comment]
Both spells work fine as of current version.

**Comment by Moustachos** [comment]
Ref #5979
