### ISSUE TITLE
Healers's Mana pool

### ISSUE THREAD

**Issue by keyna** [Valhalla-Gaming/Tracker#5988]
At level 100, Holy paladin only has 32k mana. I don't know if this happens with other classes as well.
**Update:** This also happens with other healing specs.

**Comment by skorge1** [comment]
same for resto druid probably the same for healing specs

**Comment by shineyerlight** [comment]
Issue's name and desctiption updated.

**Comment by llamalama** [comment]
This is also a problem for Resto Shamans.
Holy and Disc priests are both fine.

**Comment by Moustachos** [comment]
Ref #5979
