### ISSUE TITLE
[Rogue][Ability] Stealth

### ISSUE THREAD

**Issue by Twiggstar** [Valhalla-Gaming/Tracker#5992]
[Stealth](http://www.wowhead.com/spell=1784/stealth)

You can see aura active when used under buffs tab but bars don't change, you can't use abilities that require stealth and you are seen by npcs/players.

**Comment by Twiggstar** [comment]
When you guys fix Stealth i'll be reporting anything else that doesn't work :P

**Comment by Tregeta** [comment]
Ref #5966
