### ISSUE TITLE
[Rogue][Ability] Backstab

### ISSUE THREAD

**Issue by Twiggstar** [Valhalla-Gaming/Tracker#5995]
[Backstab](http://www.wowhead.com/spell=53/backstab)

Ability requires you to be behind your target but in fact you shouldn't wich was changed in Legion but instead if you are behind the target you get 30% damage increase on [Backstab](http://www.wowhead.com/spell=53/backstab)

**Comment by Jefferythegod** [comment]
You don't have to be behind your target to use Backstab

**Comment by Moustachos** [comment]
Ref #5979
