### ISSUE TITLE
[Demon Hunter][Talent]Demon blades

### ISSUE THREAD

**Issue by SirTwenty** [Valhalla-Gaming/Tracker#5998]
[Demon blades](http://www.wowhead.com/spell=203555/demon-blades) talent replaces [Demon's bite] spell giving us [Your auto attacks have a 75% chance to deal additional Shadow damage and generate Fury] but it's bugged and demon hunters cant generate fury which renders demon hunters unplayable.The only way is to change the talent either by being in a rested area or through the tome of clear mind but i cant find those in demon hunter starting zone.

**Comment by Moustachos** [comment]
Will be fixed on next update.

**Comment by Moustachos** [comment]
Ref #5979 
Ref #6200 
Ref #6378 
Ref #6380
