### ISSUE TITLE
NPC: Argos Nightwhisper

### ISSUE THREAD

**Issue by FlameChampion34** [Valhalla-Gaming/Tracker#60]
I can't tak to this npc, he is supposed to have dialogue window, and when talking to him, this is what he's saying: "With Stormwind's park district destroyed by Deathwing's pass over the city, we're returning to Darnassus for a time". 

http://www.wowhead.com/npc=4984/argos-nightwhisper

**Comment by Trekex** [comment]
This is working atm :)
