### ISSUE TITLE
Log in.

### ISSUE THREAD

**Issue by krasimir32** [Valhalla-Gaming/Tracker#6005]
**Describe the issue you're having**:
When i try to log in it just says "We couldn't log you in with what you just entered. please try again.(blz51900003)
**Explain how you expect it work**:
to let me play.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Zeyox** [comment]
Server is offline, please dear god wait for the announcement.

**Comment by krasimir32** [comment]
:D dont get mad tho xd

**Comment by Zeyox** [comment]
Then read the forums..

**Comment by Seregruth** [comment]
Please keep the issue tracker for in-game bugs.
