### ISSUE TITLE
[Paladin][Spell] Templar's Verdict

### ISSUE THREAD

**Issue by keyna** [Valhalla-Gaming/Tracker#6007]
**Describe the issue you're having**:
It consumes holy power but doesn't deal damage

**Explain how you expect it work**:
It should consume 3 holy power and deal 400% holy damage

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**: 
http://www.wowhead.com/spell=85256/templars-verdict

**Comment by midodragon** [comment]
doesn't do damage

**Comment by Moustachos** [comment]
Ref #5979
