### ISSUE TITLE
Ice Lance

### ISSUE THREAD

**Issue by nicktothenock** [Valhalla-Gaming/Tracker#6014]
**Describe the issue you're having**:
ice lance isnt doing any damage, its just taunting the target when it hits
**Explain how you expect it work**:
should do damage 
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Trekex** [comment]
http://www.wowhead.com/spell=30455/ice-lance

**Comment by nuhrii** [comment]
#4625

**Comment by Moustachos** [comment]
Ref #5979
