### ISSUE TITLE
Questing

### ISSUE THREAD

**Issue by nicktothenock** [Valhalla-Gaming/Tracker#6016]
**Describe the issue you're having**:
in blood elf starting area, when i accept a quest, some of them dont show on the map to where to turn it in.
**Explain how you expect it work**:
should show question marks on the map where to turn the quest in
**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Cidragon** [comment]
Hi Nicktothenock, sadly without say to us the exactly quests with problems we can't fix it.
