### ISSUE TITLE
Blood elf quest

### ISSUE THREAD

**Issue by nicktothenock** [Valhalla-Gaming/Tracker#6017]
**Describe the issue you're having**:
the quest [Completing the Delivery] doesnt turn in when i choose a reward
**Explain how you expect it work**:
should be able to choose a reward then click complete quest and its turned in
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Trekex** [comment]
http://www.wowhead.com/quest=8350/completing-the-delivery

**Comment by Seregruth** [comment]
The quest is working, I just tested it.
