### ISSUE TITLE
Cobra Shot Focus

### ISSUE THREAD

**Issue by benedickt** [Valhalla-Gaming/Tracker#6024]
**Describe the issue you're having**:
Cobra Shot consumes 80 focus.
**Explain how you expect it work**:
Tooltip describes Cobra Shot to only use 40 Focus.
**Steps to reproduce the problem**:

1. Make a Hunter.
2. Find a mob.
3. Try to use Cobra Shot at 40 focus as described.

**Links to Wowhead, YouTube, etc**:

**Comment by Trekex** [comment]
http://www.wowhead.com/spell=193455/cobra-shot

**Comment by GeneralCaveman** [comment]
This spell currently uses 40 focus on my character.

**Comment by Moustachos** [comment]
Ref #5979
