### ISSUE TITLE
Paladin Spell TV

### ISSUE THREAD

**Issue by krasimir32** [Valhalla-Gaming/Tracker#6025]
**Describe the issue you're having**:
Paladin spell "templar's verdict" consumes holy power does not do dmg.
**Explain how you expect it work**:
To do dmg.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Trekex** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6007
