### ISSUE TITLE
Shaman's maelstrom.

### ISSUE THREAD

**Issue by AngryWolf123** [Valhalla-Gaming/Tracker#6026]
**Describe the issue you're having**:
Shaman's maelstrom bar is not working.
**Explain how you expect it work**:
Spells should regenerate maelstrom (Which is the main resource for almost every spell for shamans)
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/5981
