### ISSUE TITLE
dk runes and runic power

### ISSUE THREAD

**Issue by tigerct** [Valhalla-Gaming/Tracker#6027]
**Describe the issue you're having**:
My runes won't disappear and I don't gain runic power but at the same time my runes won't work
**Explain how you expect it work**:
The runes disappear and create runic power for me to use on my other abilities.
**Steps to reproduce the problem**:

1. make a dk
2. try to use abilities that take runes repeatedly

**Links to Wowhead, YouTube, etc**:

**Comment by Trekex** [comment]
Ref #5949
