### ISSUE TITLE
DK Runes Not Recharging + No Runic Power Regen

### ISSUE THREAD

**Issue by benedickt** [Valhalla-Gaming/Tracker#6028]
**Describe the issue you're having**:
When a spell that costs runes is used, it uses a rune, but only 6 runes can be used, then no spells can be cast until a relog. Runic power is also not generated upon Rune Usage.

**Explain how you expect it work**:
Runes should recharge, runes used should create runic power.

**Steps to reproduce the problem**:

1. Make a dk
2. Cast spells until you can't cast any more

**Links to Wowhead, YouTube, etc**:

**Comment by Trekex** [comment]
Ref #5949
