### ISSUE TITLE
Paladin Spell execution sentence

### ISSUE THREAD

**Issue by krasimir32** [Valhalla-Gaming/Tracker#6029]
**Describe the issue you're having**:
IT consumes holy power it does not do dmg execution sentesnce
**Explain how you expect it work**:
to do dmg
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Trekex** [comment]
http://www.wowhead.com/spell=213757/execution-sentence

**Comment by MichRattay** [comment]
spell works

**Comment by keyna** [comment]
it does work

**Comment by midodragon** [comment]
the spell works fine now
