### ISSUE TITLE
Weapon Rack no loot for Pandaren Monk 

### ISSUE THREAD

**Issue by Brodywood900** [Valhalla-Gaming/Tracker#6032]
**Describe the issue you're having**:
I cannot loot the weapon rack to complete the quest The Lesson of the Iron Bough (this is monk specific) 

**Explain how you expect it work**:
I expect there to be loot from the weapon rack for monks 
**Steps to reproduce the problem**:
1. Create a Pandaren monk 
2. Get the quest 
3. Try to loot the weapon rack 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=30027/the-lesson-of-the-iron-bough
http://www.wowhead.com/object=210005/weapon-rack

**Comment by Chayni** [comment]
Any update on a fix?
