### ISSUE TITLE
Human beginning quest not completable

### ISSUE THREAD

**Issue by Jerpent** [Valhalla-Gaming/Tracker#6033]
Could not turn in first quest in human starting zone

I clicked on the turn in button, but there was no effect. The button became indented as I clicked on it which means it knew it was being clicked, but no other effect happened.

1. Start new human  
2. Get quest to kill 6 wargs and kill them
3. return to quest giver

**Comment by TheGodyr** [comment]
yeah just skip it go do other quest ^^

**Comment by Sargares** [comment]
i am now lvl 14 without give the quest in
