### ISSUE TITLE
Falara Nightsong

### ISSUE THREAD

**Issue by jpazminos** [Valhalla-Gaming/Tracker#6034]
So this NPC on Mardum, Falara Nightsong, located on the Illidari Foothold is the only NPC ive seen that could repair but you cant even talk to it. It would be nice if they fixed it since there are some DH that have red armor beside me.
![wowscrnshot_090416_001936](https://cloud.githubusercontent.com/assets/16790785/18229210/8077328c-7235-11e6-9e7b-3496fbb87d95.jpg)

**Comment by Trekex** [comment]
She should also sell DH gear in the Order Hall

**Comment by EldritchIHC** [comment]
Is there any way to repair my items without the npc?this problem is annoying already.  ;_;

**Comment by Guybrush-VR** [comment]
Fixed in next update gentlemen. :palm_tree:
