### ISSUE TITLE
Combo Points

### ISSUE THREAD

**Issue by blablablablblabllabl** [Valhalla-Gaming/Tracker#6036]
**Describe the issue you're having**: Cant gain combo points 

**Explain how you expect it work**: obviously use a combo gaining ability ( shadowstrike etc) and gain combo point
**Links to Wowhead, YouTube, etc**:http://wowwiki.wikia.com/wiki/Combo_point
My thoughts : Combo point is a really essential system in monks , rogues (especially) , and druids
without combo points rogues cant use about 10-12 spells in 3 specs combined

**Comment by Trekex** [comment]
Fixed last update
