### ISSUE TITLE
[Paladin][Spell] Divine Steed

### ISSUE THREAD

**Issue by hiepsivn03** [Valhalla-Gaming/Tracker#6040]
Divine Steed does nothing.

The spell should summon a horse and boost your movement speed for 3 sec.
 Wowhead: http://www.wowhead.com/spell=190784/divine-steed

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/5985

**Comment by midodragon** [comment]
doesn't work at all

**Comment by Moustachos** [comment]
Ref #5979
