### ISSUE TITLE
Shadow Priests don't have an insanity bar.

### ISSUE THREAD

**Issue by earlsweatshirt** [Valhalla-Gaming/Tracker#6052]
**Describe the issue you're having**:
Shadow priests don't have an insanity bar
**Explain how you expect it work**:
You generate insanity by casting damaging spells and when you reach 100 insanity you cast void eruption to enter void form which gives you a new spell and a very big damage/haste buff.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/resource=13/insanity
http://www.wowhead.com/spell=228266/void-bolt
http://www.wowhead.com/spell=194249/voidform

**Comment by earlsweatshirt** [comment]
Please...

**Comment by Moustachos** [comment]
Will be fixed on next update.

Ref #5979
