### ISSUE TITLE
[Warlock][Spell]Hand of Gul'Dan and Call Dreadstalkers not working

### ISSUE THREAD

**Issue by EldritchIHC** [Valhalla-Gaming/Tracker#6053]
Hand of Gul'Dan does no damage and Call Dreadstalkers doesn't cast.

http://www.wowhead.com/spell=1000128/call-dreadstalkers
http://www.wowhead.com/spell=105174/hand-of-guldan

**Comment by nuhrii** [comment]
For future reference keep issues to a single thing not two different things so its easier to keep track of what has been fixed or not.
Hand of Gul'dan is also not consuming up to 4 Soul Shards if available nor is it summoning Wild Imps depending on the number of Soul Shards consumed. Also it's not "not doing damage", it doesn't register hitting the target

**Comment by EldritchIHC** [comment]
kk

**Comment by Moustachos** [comment]
Ref #5979
