### ISSUE TITLE
Warrior: Order Hall

### ISSUE THREAD

**Issue by shadowshinobi11** [Valhalla-Gaming/Tracker#6055]
**Describe the issue you're having**:

**Explain how you expect it work**:

**Steps to reproduce the problem**:
1. There is a Val'kyr, but no **golden light** in front of her and no extra button to jump
2. Warrior: Head to Krasus' Landing and look for the Val'kyr. Step into the
   **golden light** in front of her and you will be given an extra button to press. Press it and you will jump to the order hall.
3. Can you place the **golden light** or something i dont really know
   ![untitled](https://cloud.githubusercontent.com/assets/20188151/18229648/f3be1db0-7289-11e6-955d-faee9e65e66f.jpg)
   **Links to Wowhead, YouTube, etc**:

**Comment by Moustachos** [comment]
Fixed in a previous update.
