### ISSUE TITLE
Death knights

### ISSUE THREAD

**Issue by judicator1** [Valhalla-Gaming/Tracker#6057]
**Describe the issue you're having**:can't use any of my abilitys

**Explain how you expect it work**:i think DK runes don't regen

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by judicator1** [comment]
fix ass oon as possible please i can't play

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/5949
