### ISSUE TITLE
(Quest) Catch and Release

### ISSUE THREAD

**Issue by Aedomus** [Valhalla-Gaming/Tracker#606]
Objective; Morae at Blood Watch wants you to 'mark' 6 Blacksilt Scouts using the Murloc Tagger. 

Issue; Not getting credit for "marking" Blacksilt Scouts

http://www.wowhead.com/quest=9629/catch-and-release

**Comment by Malae1** [comment]
Nothing happens when using the item, as above.

**Comment by Pure-Valhalla** [comment]
Quest now works
