### ISSUE TITLE
Shaman ((  [Ascendance] )) Not Work 

### ISSUE THREAD

**Issue by EvanovicH** [Valhalla-Gaming/Tracker#6060]
*_Shaman ((  [Ascendance] )) Not Work *_:

*_Just Make IT Work Like It Was In WOD :) *_:

**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Trekex** [comment]
http://www.wowhead.com/spell=114049/ascendance

**Comment by Moustachos** [comment]
This spell works just fine.

**Comment by Moustachos** [comment]
Ref #5979
