### ISSUE TITLE
Get "kick" out of the server 

### ISSUE THREAD

**Issue by lillandril** [Valhalla-Gaming/Tracker#6061]
**Describe the issue you're having**:
I'm log in play about 10 min on my characters , then i get disconnected ( I don't know if you consider this issue as a connection problem so I put it here ^^') I put the error code with the post.

![p_20160904_100321](https://cloud.githubusercontent.com/assets/17160036/18229868/1f54a2f6-7289-11e6-91cc-30646fe3a933.jpg)

good luck to all the staff ^^
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by damiongans** [comment]
The server crashes often right now. It's not your account or client.

**Comment by lillandril** [comment]
Okay thank you ^^

2016-09-04 10:39 GMT+02:00 Damion Gans <notifications@github.com>:
