### ISSUE TITLE
[Warrior-Protection] instant death when blocking an attack

### ISSUE THREAD

**Issue by newman091** [Valhalla-Gaming/Tracker#6064]
Whenever i tried to fight in nagrand i just died mid fight to a unreal amount of damage ( 7 million or something) so i looked for a reason why, and i have found the reason why i die to so much dmg.
In the Character tab when i cursor over the "block" stat it says "blocks 1084634634% amount of dmg" and i was like this isnt right. As a matter of fact i dont die at the beginning of the fight but randomly while i fight so i assume i just die whenever the "block" happens.

i hope this description is enough to solve the block-stat bug other than that most spells for warriors work.

interception, heroric leap and ignore pain do not work.

**Comment by Trekex** [comment]
[Intercept](http://www.wowhead.com/spell=198304/intercept)
Heroic Leap Ref https://github.com/Valhalla-Gaming/Tracker/issues/5970
[Ignore Pain](http://www.wowhead.com/spell=190456/ignore-pain)

**Comment by keyna** [comment]
same for protection paladins.

**Comment by Moustachos** [comment]
Can't reproduce.
