### ISSUE TITLE
Crash Lighting

### ISSUE THREAD

**Issue by AngryWolf123** [Valhalla-Gaming/Tracker#6068]
**Describe the issue you're having**:
somehow even tho maelstrom is not working i can still cast maelstrom spells, "Crash Lighting" is not working it keeps saying i need melee weapon even tho i have a melee weapon.
**Explain how you expect it work**:

**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Trekex** [comment]
http://www.wowhead.com/spell=187874/crash-lightning

**Comment by Moustachos** [comment]
Ref #5979

**Comment by Moustachos** [comment]
Ref #5979
