### ISSUE TITLE
Warrior Spell: Charge

### ISSUE THREAD

**Issue by DeathByDuke** [Valhalla-Gaming/Tracker#6071]
**Describe the issue you're having**:
Charge activates, but character doesn't move to attack NPC
**Explain how you expect it work**:
Char should "charge" at enemy, giving damage
**Steps to reproduce the problem**:

1. Human Warrior
2. Northshire Abbey
3. Charge

**Links to Wowhead, YouTube, etc**:

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/5961
