### ISSUE TITLE
Monk Spell: Tiger Palm

### ISSUE THREAD

**Issue by DeathByDuke** [Valhalla-Gaming/Tracker#6072]
**Describe the issue you're having**:
Unable to use Tiger Palm, is blued out constantly. Cannot activate spell or complete first trainer quest
**Explain how you expect it work**:
Usable spell, to complete trainer quest
**Steps to reproduce the problem**:

1. Human Monk
2. Northshire Abbey
3. Attempt Tiger Palm

**Links to Wowhead, YouTube, etc**:

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/5987
