### ISSUE TITLE
Flightmaster issue after a crash

### ISSUE THREAD

**Issue by Archerofdawn** [Valhalla-Gaming/Tracker#6073]
I flew from Forest Song to Astranaar with the flightmasters' service. It worked fine, proper path, no glitching, no issues. I landed shortly before the most recent crash as of posting this. When I logged back in, my character was back on the automated mount, flew back to Forest Song in a straight line, going through terrain and bumping into objects, grinding against them then continuing on. After getting there, the hyppogriph took a 180 degree turn and was back on the normal flight path from Forest Song to Astranaar where it arrived once again properly.

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/4354
