### ISSUE TITLE
Warrior Training Quest: Beating Them Back!

### ISSUE THREAD

**Issue by DeathByDuke** [Valhalla-Gaming/Tracker#6074]
**Describe the issue you're having**:
Completed quest as Human Warrior in Northshire Abbey, unable to complete or hand in quest.
**Explain how you expect it work**:
Quest hands in, get rewards.
**Steps to reproduce the problem**:
1. Human Warrior
2. Northshire Abbey
3. "Beating Them Back!" Questline

**Links to Wowhead, YouTube, etc**:

**Comment by Cidragon** [comment]
It's working now.
