### ISSUE TITLE
Quest: A Rogue's Advantage / Night Elf Rogue

### ISSUE THREAD

**Issue by Sonofsven** [Valhalla-Gaming/Tracker#6082]
**Describe the issue you're having**:
No Combo Points available and no  Eviscerate skill (Req, Lv 10 in Skill Book) this quest is for Lv 3
**Explain how you expect it work**:
Gain Combopoints and use  Eviscerate Skill

**Links to Wowhead, YouTube, etc**:

http://www.wowhead.com/quest=26946/a-rogues-advantage

Thx, Keep Up the Good Work

**Comment by Trekex** [comment]
Eviscerate Ref https://github.com/Valhalla-Gaming/Tracker/issues/5954
Combo Points Ref https://github.com/Valhalla-Gaming/Tracker/issues/6036
