### ISSUE TITLE
[Hunter]Marked Shot

### ISSUE THREAD

**Issue by jarqo91** [Valhalla-Gaming/Tracker#6085]
**Describe the issue you're having**:

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. Spell market Shot does not work. It appears as grey spell(not usable).
2. You should be able use this spell, but atm you can't somehow.
3. Log hunter,train MMspec and get level 18 atleast, then try use that spell.

**Links to Wowhead, YouTube, etc**:
Source: http://www.wowhead.com/spell=212621/marked-shot

**Comment by Trekex** [comment]
Targets need Hunter's mark to let you cast Marked Shot

**Comment by jarqo91** [comment]
Thats why it's bugged, see here: https://github.com/Valhalla-Gaming/Tracker/issues/6087

**Comment by Trekex** [comment]
How can you say Marked Shot is not working, if Hunter Mark is never applied? #6087 is enough atm
