### ISSUE TITLE
donate point for heirlooms shop not work

### ISSUE THREAD

**Issue by Myhtos** [Valhalla-Gaming/Tracker#6086]
**Describe the issue you're having**:
i buy 3 items shoulder, head, and back for hunter from heirlooms shop using free donate point but i cannot get it
**Explain how you expect it work**:
as u say "Note: Collections (Heirlooms, Mounts, Battle Pets, Toys) no longer get sent to your mail box. Instead, they will be instantly added to your collections tab. Further, transmog, shirts and tabards are custom cosmetic items with no stat bonuses applied. All transmog items will carry the normal - and not the mythic - display. "
**Steps to reproduce the problem**:
please fix it My IGN : " Mythoz"  ... thx

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/item=122356&bonus=583
http://www.wowhead.com/item=122261&bonus=583
http://www.wowhead.com/item=122246&bonus=583

**Comment by Tregeta** [comment]
Ref to #6114 
As side note, have you marked down.
