### ISSUE TITLE
[Death Knight] Can't use any Spells

### ISSUE THREAD

**Issue by iblast** [Valhalla-Gaming/Tracker#6090]
**Describe the issue you're having**:
I can't use any spells
**Explain how you expect it work**:
We'll i should be able to use Howling Blast Or Obliate but nothing works.
**Steps to reproduce the problem**:

1.  Fix the Skills
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Guybrush-VR** [comment]
You mean Batman can't use his spells? We're doomed!

**Comment by Trekex** [comment]
Edited. lol

**Comment by Trekex** [comment]
Fixed already
