### ISSUE TITLE
Combo points for rogues

### ISSUE THREAD

**Issue by Potatoe123** [Valhalla-Gaming/Tracker#6094]
**Describe the issue you're having**:
Combo points for rogues do not work at all and any abilities that are supposed to generate combo points simply dont generate them (for example mutilate)
**Explain how you expect it work**:
I expect CP generating abilities to generate combo points
**Steps to reproduce the problem**:

1. cast mutilate
2. No CP gain
3. cant use finishers

**Links to Wowhead, YouTube, etc**:

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/6036
