### ISSUE TITLE
[Paladin][Talent] Sanctificed Wrath

### ISSUE THREAD

**Issue by keyna** [Valhalla-Gaming/Tracker#6095]
http://www.wowhead.com/spell=53376/sanctified-wrath
It makes Holy Shock have no cooldown. It should only reduce Holy Shock's cooldown by 50%.

**Comment by boxty123** [comment]
holy shock is instant cast?

**Comment by keyna** [comment]
my bad :D description updated

**Comment by boxty123** [comment]
dont complain about that xD no cd means u'll be op lol

**Comment by keyna** [comment]
haha :D, not so op with the mana issue :D

**Comment by Moustachos** [comment]
Ref #5979
