### ISSUE TITLE
Purchase from shop

### ISSUE THREAD

**Issue by boxty123** [Valhalla-Gaming/Tracker#6096]
I just purchased 2 heirloom items from the shop(2 rings) but i never got them i relogged and restarted the game still dont have them but my valhalla points are gone

**Comment by keyna** [comment]
have you checked the heirloom tab?

**Comment by boxty123** [comment]
yes it sais i have no heirloom items they are all grayed out

**Comment by Aveh** [comment]
got the same issue

**Comment by keyna** [comment]
probably a new bug, i just purchased mine few hours ago and it was normal

**Comment by boxty123** [comment]
i just unlucky i guess

**Comment by hillelm6** [comment]
im unluky 2 i guess not get my heirlooms and  mount i buy :(

**Comment by Tregeta** [comment]
Closing Issue, have a newer one open already
