### ISSUE TITLE
[Death Knight] Horn of Winter

### ISSUE THREAD

**Issue by Ulvos** [Valhalla-Gaming/Tracker#6097]
**Describe the issue you're having**:
1. Runes does not go on cooldown and does not show on cool down
2. Using runes do not generate runic power 
3. Horn of Winter does not work
**Explain how you expect it work**:
1. Using runes make it goes in cool down
2. Using rune should generate runic power
3. Horn of Winter should give 2 rune and generating 10 Runic Power.
**Steps to reproduce the problem**:

1. Using skill that requires runes does not show runes on cooldown, After using it six times, you won't be able to use any skill until you relog
2. No runic power after using skill that cinsumes rune
3. Nothing happens

**Links to Wowhead, YouTube, etc**:
1 and 2. https://www.youtube.com/watch?v=f7Zn0vjaPZk
3. http://www.wowhead.com/spell=57330/horn-of-winter

**Comment by Trekex** [comment]
Runic Power Ref https://github.com/Valhalla-Gaming/Tracker/issues/5949

**Comment by Trekex** [comment]
Fixed last update
