### ISSUE TITLE
Arcane mage-Arcane charges

### ISSUE THREAD

**Issue by boxty123** [Valhalla-Gaming/Tracker#6099]
Im leveling an arcane mage right now and the arcane charges never go away after i use arcane barrage or after not attacking for a while they are all still there but when i do dmg the dmg is random sometimes arcane blast does more dmg sometimes a lot less even tho i still have all arcane charges, also arcane barrage doesnt hit additional enemies as its supposed to when u use it with more charges. fix please cuz i rly like mages. im sure u already know about frostbolt not slowing and ice lance not doing dmg

**Comment by Trekex** [comment]
http://www.wowhead.com/spell=36032/arcane-charge

**Comment by nuhrii** [comment]
Arcanes charges are stacking correctly, but when they are expended they do not stack again, but it says you still have x charges. Relogging will allow them to expire normally

**Comment by Trekex** [comment]
Arcane Charge fixed last update

@nuhrii please open a new issue for Arcane Missiles if not already reported
