### ISSUE TITLE
[Quest] Beating them Back!

### ISSUE THREAD

**Issue by Tevon2** [Valhalla-Gaming/Tracker#6101]
I can't get past this quest. Clicking "Complete" quest does nothing.

I don't really know how else to explain it except that it just doesn't work.

Abandoning quest and doing it again didn't work.

Logging out and logging in again didn't work either

I'm a human warrior

**Comment by DeathByDuke** [comment]
Not alone, having same issues with a Human Warrior. Cannot progress as a result.

**Comment by boxty123** [comment]
i dont rememer the quest name but i had the same issue with a quest in the blood elf area i couldnt turn the quest in i was clicking complete it didnt work so i just abandoned it

**Comment by GM-Pyromanic** [comment]
Duplicate report
#6074
