### ISSUE TITLE
demon hunter class hall inaccessible

### ISSUE THREAD

**Issue by supermaxu** [Valhalla-Gaming/Tracker#6102]
the way you have to get to demon hunter class hall is impossible to do due to glide not working properly as well as when using it to attempt the game crashes

when you just from the platform near the flight person off to glide to the portal you come up very short

**Steps to reproduce the problem**:
1. go to new daloran near the broken edge of the wall
2. jump then double jump and glide
3. 

https://youtu.be/5w3SWYdlwYc

**Comment by MalkiOrki** [comment]
It does work. I've been in the class hall few times already.

**Comment by supermaxu** [comment]
then you glitched it doing it is impossible do to glide being messed up

**Comment by Alkiraz** [comment]
Go in vengance
Jump
Glide
then leap to the border when you are close (Infernal strike)

**Comment by Analog-Valhalla** [comment]
As stated by @MalkiOrki getting to the Class hall works properly. I suggest trying the method @Alkiraz provided above. :D
