### ISSUE TITLE
Earth Shock

### ISSUE THREAD

**Issue by NaughtyDecent** [Valhalla-Gaming/Tracker#6106]
**Describe the issue you're having**:
Earth SHock SPell of Shaman class isn't working... It remain un use able no matter i'm in fight or rsting.
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Trekex** [comment]
http://www.wowhead.com/spell=8042/earth-shock

**Comment by Trekex** [comment]
Fixed already
