### ISSUE TITLE
Sara Timberlain wont reward players 

### ISSUE THREAD

**Issue by Brodywood900** [Valhalla-Gaming/Tracker#6108]
**Describe the issue you're having**:
I cannot complete the quest 
**Explain how you expect it work**:
The quest would complete and I would be rewarded 
**Steps to reproduce the problem**:
1. Accept the quest  
2. Complete The quest 
3. Try to hand in the quest 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=83/fine-linen-goods
http://www.wowhead.com/quest=59/cloth-and-leather-armor

**Comment by Cidragon** [comment]
they are working now.
