### ISSUE TITLE
Druid Starting Spell "Shred" is Mising

### ISSUE THREAD

**Issue by AbhiSheikh** [Valhalla-Gaming/Tracker#6109]
**Describe the issue you're having**:
hi guys, i made a druid and its starting spells are missing and it sucks without them...

**Explain how you expect it work**:
Please fix it so we can have fun

**Comment by Delahunts** [comment]
You can not find them on P too?!

**Comment by AbhiSheikh** [comment]
i can see it on "Spell Book" but it show's in grey color like its high lvl or cant use it yet...
try making a druid its a starting spell u will understand :)

**Comment by Trekex** [comment]
@AbhiSheikh 
*Hello Guys, it says on site that u guys fixed druid starting spells..but i dont see it in the game..is it my char bug? but i tried making a new druid and i still miss "Shred" and i dont even see it in the Spell Book now..did they remove it in Legion or is it still bug? please help me out..

**Comment by GM-Pyromanic** [comment]
Strange I tested the spell shred on the live realm the other day it was there and working. I still have that character on the account so when I log on will check if the spell is still there.

**Comment by GM-Pyromanic** [comment]
Issue has been fixed in a previous update - http://i.imgur.com/LBDQdNq.jpg (Screen taken on Valhalla)
