### ISSUE TITLE
[Warrior] Spell:Charge Is not working

### ISSUE THREAD

**Issue by GorVeK244** [Valhalla-Gaming/Tracker#6115]
**Describe the issue you're having**:
The spell charge doesn't do anything aside from giving me rage..
**Explain how you expect it work**:
The spell should practicly rush me at the enemy and get me closer to it.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/5961
