### ISSUE TITLE
"Hunter Spell Steady Shot is Missing"

### ISSUE THREAD

**Issue by AbhiSheikh** [Valhalla-Gaming/Tracker#6116]
**Describe the issue you're having**:
There is no Steady Shot on Hunter....
**Explain how you expect it work**:
Please Fix this

**Comment by boxty123** [comment]
this is legion its not supposed to be there its removed

**Comment by GorVeK244** [comment]
lol so tru ur just stupid

**Comment by Redrian-Hellscream** [comment]
Please close this.
