### ISSUE TITLE
[Mage][Fire][Spell Fire Blast]

### ISSUE THREAD

**Issue by boxty123** [Valhalla-Gaming/Tracker#6119]
**Describe the issue you're having**:
Fire Blast is supposed to be a critical strike but it doesnt crit. that is the main rotation of fire mage 
**Explain how you expect it work**:
the spell is supposed to have a 100% crit chance
**Steps to reproduce the problem**:

1. Use Fire blast
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Trekex** [comment]
http://www.wowhead.com/spell=108853/fire-blast

**Comment by Moustachos** [comment]
Ref #5979
