### ISSUE TITLE
[Paladin] Greater Blessings

### ISSUE THREAD

**Issue by skarodwex** [Valhalla-Gaming/Tracker#6121]
Blessings don't work

**Comment by Trekex** [comment]
http://www.wowhead.com/spell=203528/greater-blessing-of-might
http://www.wowhead.com/spell=203539/greater-blessing-of-wisdom
http://www.wowhead.com/spell=203538/greater-blessing-of-kings

**Comment by Moustachos** [comment]
Greater Blessing of Wisdom works fine on current version.

**Comment by Moustachos** [comment]
Ref #5979
