### ISSUE TITLE
[Quest] Lou's Parting Thoughts

### ISSUE THREAD

**Issue by Delahunts** [Valhalla-Gaming/Tracker#6124]
**Describe the issue you're having**:
Quest known as "Lou's Parting Thought", taken in Westfall, does not work.

**Explain how you expect it work**:
To work. The thug i need to kill is not there.

**Steps to reproduce the problem**:

1. Quest fixing.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=26232/lous-parting-thoughts

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/2941
