### ISSUE TITLE
Healing Surge

### ISSUE THREAD

**Issue by AngryWolf123** [Valhalla-Gaming/Tracker#6125]
**Describe the issue you're having**:
Healing surge can be cast while moving .
**Explain how you expect it work**:
casts while standing only.
**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Trekex** [comment]
http://www.wowhead.com/spell=8004/healing-surge
http://www.wowhead.com/spell=188070/healing-surge

**Comment by gaven90** [comment]
For enhanc spec there is also a bug. Healing surge doesn't become instant with maelstorm http://www.wowhead.com/spell=188070/healing-surge

**Comment by Nikos92** [comment]
Should someone create a new issue for Healing Surge in enchancement spec not using 20 maelstorm to become instant or they use the comment by gaven 90?

**Comment by Moustachos** [comment]
Ref #5979
