### ISSUE TITLE
Death Knight Skills Broken on all 3 specilizations

### ISSUE THREAD

**Issue by fudgey24** [Valhalla-Gaming/Tracker#6127]
**Describe the issue you're having**:
Death Knight Skills do not work, they just do animations if that much.
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/6090
