### ISSUE TITLE
Ice lance Bug

### ISSUE THREAD

**Issue by Emberflame** [Valhalla-Gaming/Tracker#6129]
**The mage spell Ice Lance does Zero Damage**:

**it should do the damage its supposed to do**:

**Steps to reproduce the problem**:

1. Create a mage
2. Hit level 5
3. try the spell at a dummy or any trash

**http://www.wowhead.com/spell=30455/ice-lance**:

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/6014

**Comment by Moustachos** [comment]
Ref #5979
