### ISSUE TITLE
Warrior charge

### ISSUE THREAD

**Issue by HunterZolomoon** [Valhalla-Gaming/Tracker#6130]
**Describe the issue you're having**:
Warrior's charge not working, the character doesn't move and neither the spell takes effect.
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by forstix** [comment]
guys plz check it this spell reported already i saw like 3 reports about charge

**Comment by forstix** [comment]
guys plz check it this spell reported already i saw like 3 reports about charge

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/5961
I've seen many more :P
