### ISSUE TITLE
Fix most of the dk spells

### ISSUE THREAD

**Issue by tuan206** [Valhalla-Gaming/Tracker#6135]
**Describe the issue you're having**:
Deathknights are only able to use spells that frost rune or no rune. Spells like blood boil will work, but death strike does not work.
**Explain how you expect it work**:
There should be 2 runes for each spec if I remember correctly.
**Steps to reproduce the problem**:

1.  Create a DK
2.  Choose unholy/death spec
3.  Find a mob and try to use the ability on it.

**Links to Wowhead, YouTube, etc**:

**Comment by GM-Pyromanic** [comment]
Patch 7.0.3 (19-Jul-2016): Runes are more straightforward by removing their division into separate Blood, Frost, and Unholy types. Death Knights now have six unified Runes to spend, with a maximum of three recharging at any one time.
