### ISSUE TITLE
Whisp

### ISSUE THREAD

**Issue by aminbogy** [Valhalla-Gaming/Tracker#6136]
Hi
whisp is bug , when im whisp to my friends , they didn't recevie it. please fix it,
Thanks

**Comment by GM-Pyromanic** [comment]
Greetings aminbogy,

I have not been having any issues while whispering players, If you could provide us with more information on this issue so we can look into it more in-depth. Thank you.

**Comment by aminbogy** [comment]
today i try to whisp my friends , but they didn't answer me , then i call them and after speak i whisp them again but they didn't recieve my chat's , idk why , my class is demon hunter , and my friend too

**Comment by Trekex** [comment]
Are you two from the same faction?

**Comment by aminbogy** [comment]
yes , i try too much , but my friend didn't recevie my whispers
