### ISSUE TITLE
Dk Spells

### ISSUE THREAD

**Issue by Willentor** [Valhalla-Gaming/Tracker#6137]
**Describe the issue you're having**:
My spells do not work when i use them and dont seem to be using any runes 
**Explain how you expect it work**:
My abilities should work and and use runes 
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/6090
