### ISSUE TITLE
[Quest] [Northern Stranglethorn] Spared from Madness

### ISSUE THREAD

**Issue by rawhunger** [Valhalla-Gaming/Tracker#6138]
**Describe the issue you're having**:
The NPCs Berrin Burnquill, Emerine Junis and Osborn Obnoticus are missing.
**Explain how you expect it work**:
They should be somewhere in or around Kurzen's Compound in Northern Stranglethorn.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
Wowhead quest link: [Spared from Madness](http://www.wowhead.com/quest=26736/spared-from-madness)

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/860
