### ISSUE TITLE
[Quest] [Northern Stranglethorn] I Think She's Hungry

### ISSUE THREAD

**Issue by rawhunger** [Valhalla-Gaming/Tracker#6139]
**Describe the issue you're having**:
Killing Crystal Spine Basilisks records no bites for the quest.
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
Wowhead quest link: [I Think She's Hungry](http://www.wowhead.com/quest=26739/i-think-shes-hungry)

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/4977
