### ISSUE TITLE
Run Through - Spell - Rogue

### ISSUE THREAD

**Issue by Jefferythegod** [Valhalla-Gaming/Tracker#6143]
**Describe the issue you're having**:
 Run Through reques only 1 combo points when you have 5 Combo Points.
**Explain how you expect it work**:
If you have 5 Combo Points and u press Run Through you should deal more damage, but it only uses 1 Combo Point, instead of 5 Combo Point's when you have them.
**Steps to reproduce the problem**:

1. If you have 5 Combo Points, Run Through should waste them all
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=2098/run-through

**Comment by Grummar** [comment]
All rogue abilities like for example Eviscerate, Envenom, Kidney shot, Between the eyes etc. should work like he described

**Comment by Jefferythegod** [comment]
@Grummar Correct.

**Comment by Moustachos** [comment]
Ref #5979
