### ISSUE TITLE
[Demon Hunter][Vengeance Spec][Spell] Metamorphosis

### ISSUE THREAD

**Issue by hiepsivn03** [Valhalla-Gaming/Tracker#6146]
The spell transforms the caster into a sheep instead of a demon.
Picture: http://imgur.com/a/AZYPh

The spell should transforms the caster into a demon.
Wowhead: http://www.wowhead.com/spell=187827/metamorphosis

**Comment by Antinaka** [comment]
That's a pretty funny bug! Lmao

**Comment by Neredun** [comment]
Probably the bug is because the npc who use the spell doesn't have his correct model (68671), or maybe the npc isn't added to the Database (or it can be the model who isn't added in the creature_model_info table)
it seems Tank Meta uses This npc model: http://www.wowhead.com/npc=104712

**Comment by Moustachos** [comment]
Ref #5979
