### ISSUE TITLE
Frostbolt

### ISSUE THREAD

**Issue by kombustion** [Valhalla-Gaming/Tracker#6147]
**Describe the issue you're having**:
Hi Team,

I am playing as a Frost Mage and there few issues I've noticed as of Level 5 now. Frostbolt snare effect isn't working, as it is supposed to slow down the enemies but that ain't the case here. Also there is no damage happening to enemies when using Ice Lance, none at all. Also, undead zone quests aren't available. Please fix these accordingly. 

Thanks
Shubhojit
**Explain how you expect it work**:
Provide Fix
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Trekex** [comment]
Ice Lance Ref https://github.com/Valhalla-Gaming/Tracker/issues/6014
[Frostbolt](http://www.wowhead.com/spell=116/frostbolt)
Undead quests Ref https://github.com/Valhalla-Gaming/Tracker/issues/5960

**Comment by Moustachos** [comment]
Ref #5979
