### ISSUE TITLE
"Rouge Stealth is Bug"

### ISSUE THREAD

**Issue by AbhiSheikh** [Valhalla-Gaming/Tracker#6155]
**Describe the issue you're having**:
Hello Guys, i m playing Rouge and ty for fixing combo points but Rouge Stealth is Also Bug.. & Rouge Poison shows 60min time limit to expire but somtimes it expires in 2 mins..please also check on that
1.Rouge Stealth 
2. Rouge Poison

**Comment by Mhroczny** [comment]
Thats true I experience the same issue on my rogue. Pls fix this as soon as possible, stealth is the most important skill for rogues.

**Comment by AbhiSheikh** [comment]
Guys Poison is Fix but Stealth is still buggy please fix this asap bcz its really important to us rouges...Ty!

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/5966

**Comment by Xerqe** [comment]
https://github.com/TrinityCore/TrinityCore/pull/15779/commits/1c73a381d7c3a61a18c3b9179f19608c2f8e2c8f What about this ? In my opinion this should help.
P.S it's not my work

**Comment by Trekex** [comment]
Please comment under the open issue, not the closed one
