### ISSUE TITLE
Warlock: Hand of Gul'dan

### ISSUE THREAD

**Issue by nuhrii** [Valhalla-Gaming/Tracker#6156]
**Describe the issue you're having**:
Not consuming, more than 1, up to 4 Soul Shards and not Summoning Wild Imps
and the other one #6053 
**Explain how you expect it work**:
Is supposed to consume 1 to 4 Soul Shards, and summon Wild Imps
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=105174

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/6053

**Comment by nuhrii** [comment]
Why was this one closed, it refers to a different problem than the one that was referenced

**Comment by Trekex** [comment]
If the spell is the same, please add details in that issue instead of creating new ones

**Comment by Moustachos** [comment]
Ref #5979
