### ISSUE TITLE
"Warlock Pet"

### ISSUE THREAD

**Issue by AbhiSheikh** [Valhalla-Gaming/Tracker#6157]
Hello Guys, i played warlock and his pet is also bug + starting spells are missing it takes 5mins to kill a mob..please fix this

**Comment by nuhrii** [comment]
The issue with demons is that they are normally set to passive until level 10 where they will learn Control Demon which gives the warlock a Pet Action Bar
http://www.wowhead.com/spell=93375

**Comment by Moustachos** [comment]
Ref #5979
