### ISSUE TITLE
"Druid Starting Spells Again"

### ISSUE THREAD

**Issue by AbhiSheikh** [Valhalla-Gaming/Tracker#6159]
*Hello Guys, it says on site that u guys fixed druid starting spells..but i dont see it in the game..is it my char bug? but i tried making a new druid and i still miss "Shred" and i dont even see it in the Spell Book now..did they remove it in Legion or is it still bug? please help me out..

**Comment by Trekex** [comment]
I'm closing this and copying your message to https://github.com/Valhalla-Gaming/Tracker/issues/6109
