### ISSUE TITLE
Ghostlands Quests

### ISSUE THREAD

**Issue by mdowns331** [Valhalla-Gaming/Tracker#616]
http://www.wowhead.com/quest=9193/investigate-the-amani-catacombs -- You can bury the mummies, but when you move to the investigate part of the quest, you do not get credit for investigating and any mummies you burned gets reset to 0/10.

http://www.wowhead.com/quest=9164/captives-at-deatholme --
 http://www.wowhead.com/npc=16208 Apothecary Enith -- you can click on the option to give him the Draught, but when you tell him he can go the way is clear it does not respond and you don't get credit.

http://www.wowhead.com/npc=16206 -- This NPC is not there

http://www.wowhead.com/npc=16209 -- Same as Apothecary Enith, you can give him the draught, but you can't click on the option for them to leave.

**Comment by Max-Hellscream** [comment]
http://www.wowhead.com/npc=16206 will be spawned with the next update.

**Comment by Pure-Valhalla** [comment]
#1766

**Comment by Pure-Valhalla** [comment]
quest has been fixed
