### ISSUE TITLE
Warlock: Demonwrath

### ISSUE THREAD

**Issue by nuhrii** [Valhalla-Gaming/Tracker#6160]
**Describe the issue you're having**:
Causes the Target to deal damage in an area, the area of effect damage is way larger than 10 yards about 40, and its costs one more tick of mana than it should
**Explain how you expect it work**:
Its supposed to affect my demons and apply an effect to do damage within 10 yards of them and is costing one more mana-per-second than it should.
**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=193440

**Comment by Fumbles123** [comment]
A note: Demonwrath's total range is much larger than 40 yards. With experimentation I've narrowed it down to a number between 150 yards and 200 yards.

**Comment by Moustachos** [comment]
Ref #5979
