### ISSUE TITLE
Warlock: Soul Leech

### ISSUE THREAD

**Issue by nuhrii** [Valhalla-Gaming/Tracker#6162]
**Describe the issue you're having**:
Not doing anything
**Explain how you expect it work**:
Suppose to grant shields based on single target damage
**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=108370

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #5979
