### ISSUE TITLE
[Monk] Stagger

### ISSUE THREAD

**Issue by Gonmo** [Valhalla-Gaming/Tracker#6167]
**Describe the issue you're having**: From time to time Stagger kills you instantly

**Explain how you expect it work**: It works fine most of the time, dividing the damage received and applying it to you as a debuff

**Steps to reproduce the problem**:

1. Level 10 monk character (brewmaster)
2. Go kill mobs
3. While in combat, sometimes you insta-die. At combat log it says "Stagger damaged you (plenty of damage)"

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=124255/stagger

**Comment by Hemoglobine-Valhalla** [comment]
same happen when you're high level, sometimes damage does more than your life, 

![wowscrnshot_090816_025335](https://cloud.githubusercontent.com/assets/16792371/18334478/065b8296-7578-11e6-9e4f-82e0e2202429.jpg)

**Comment by Moustachos** [comment]
Ref #5979
