### ISSUE TITLE
I used to have mounts

### ISSUE THREAD

**Issue by Toruq** [Valhalla-Gaming/Tracker#6169]
**Describe the issue you're having**:
Hi all,

first of all, it's my first bug report. So, sorry if I do it in a wrong way :).
Before all the legion/DDoS situation, I used to have two mounts. I am in the levelling part and don't want to waste some money rebuying them. Could you look into the problem and give them back to me? Thanks! I do appreciate the work you are all doing in this great server :)

**Comment by Braemen** [comment]
#5959

**Comment by Tregeta** [comment]
Ref to #5959
