### ISSUE TITLE
Pandaren: - first quest  ,,The Lesson of the iron Bourh´´

### ISSUE THREAD

**Issue by gaudium1** [Valhalla-Gaming/Tracker#6170]
Hi, first quest in starting pandaren zone ,,The Lesson of the iron Bourh´´ does not work. Player should take weapon from rack but loot window is Empty, so player can not continue.

Thank you for help

Gaudium

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/6032

**Comment by Iaxpo** [comment]
quote!
