### ISSUE TITLE
Demon Hunter: Glide is uncontrollable 

### ISSUE THREAD

**Issue by kalata98123123123** [Valhalla-Gaming/Tracker#6171]
**Describe the issue you're having**: The demon hunter glide acts like a slow fall ability ( same thing with goblin air glider )

**Explain how you expect it work**: You should be able to control the glide and move in all sorts of directions i also believe that the speed is not correct, not sure on that tho.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/5940
