### ISSUE TITLE
[Monk] Chi Wave

### ISSUE THREAD

**Issue by Gonmo** [Valhalla-Gaming/Tracker#6173]
**Describe the issue you're having**: Chi wave animations does bounce the times descripted but only heals you once (even if it bounces twice on you). 

**Explain how you expect it work**: It should heal time it bounces, even if the targed is repeated

**Steps to reproduce the problem**:

1. Use Chi wave on a target ( an ally nearby )
2. See the bouncing animation but no 2nd heal

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=115098/chi-wave

**Comment by Moustachos** [comment]
Unless it changed with Legion, Chi Wave isn't supposed to bounce from an ally to another ally, it's meant to bounce from an ally to an enemy and so on.

Do you have a source for this change? (if there's effectively one)

**Comment by Gonmo** [comment]
No I dont. Even though, if im alone with a mob and I cast Chi Wave, it doesnt heal me more than once (although the animation does rebounce on me)

**Comment by Moustachos** [comment]
I'll check this out, anyway many spells will need some rework with Legion.

**Comment by Moustachos** [comment]
I just checked this spell on current version and it bounces just fine, healing me everytime it bounces back to my character.

That being said, healing & damage values weren't up-to-date for Legion and it will be fixed soon.

**Comment by Moustachos** [comment]
Ref #5979
