### ISSUE TITLE
Shield of Vengeance(Retribution paladin spell)

### ISSUE THREAD

**Issue by Zeyox** [Valhalla-Gaming/Tracker#6174]
**Describe the issue you're having**:
SoV should absord the dmg according to formula attack power*10 and then after duration unleash absorbed damage as  holy damage to all nearby enemies.
**Explain how you expect it work**:
Absorbs the set value, deals dmg equal to amount absorbed
**Steps to reproduce the problem**:

1. Cast Shield of Vengeance
2. /
3. Observe the result

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=184662/shield-of-vengeance

**Comment by midodragon** [comment]
the spell doesn't work, only the animation works

**Comment by Moustachos** [comment]
Ref #5979
