### ISSUE TITLE
Retribution Paladin Judgement

### ISSUE THREAD

**Issue by Zeyox** [Valhalla-Gaming/Tracker#6176]
**Describe the issue you're having**:
It damages only your  target.

**Explain how you expect it work**:
It's supposed to damage your target plus additional two targets.

**Steps to reproduce the problem**:

1. Cast Judgement(Retribution)
2. Observe the results
3. / 

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=20271/judgment

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/5963

**Comment by midodragon** [comment]
it also gives holy power, but in legion it should not give u anymore
