### ISSUE TITLE
Shaman Maelstorm Generation

### ISSUE THREAD

**Issue by energy733** [Valhalla-Gaming/Tracker#6177]
**Describe the issue you're having**:
as a shaman i can't generate maelstorm which i use in most spells

**Explain how you expect it work**:
Dunno, Haven't played on the official server since this got introduced
**Steps to reproduce the problem**:

1. Fix maelstorm
2. Fix maelstorm
3. Fix maelstorm?

**Links to Wowhead, YouTube, etc**:
Sorry i can't give you that much info XD

**Comment by GM-Pyromanic** [comment]
Issue should be fixed with the latest change log
