### ISSUE TITLE
[Priest] Major Bug

### ISSUE THREAD

**Issue by Aprophys** [Valhalla-Gaming/Tracker#6178]
**Describe the issue you're having**:
Well it doesnt matter what i wonna try to hit i cant even hit 1 single mob or player in a duel with ur spells. Everytime Miss Miss Miss Miss. So its a major problem
**Explain how you expect it work**:
how it should work hmm... maybe your spells should hit enemies?
**Steps to reproduce the problem**:
1. Changed Specc
2. Changed Talents
3. Reloged/reloaded
   well i talked with oher players and they said the same. U cant hit at the moment npcs with spells, its a priest bug.

**Links to Wowhead, YouTube, etc**:

**Comment by Analog-Valhalla** [comment]
Result of level scaling. Fixed many updates ago.
