### ISSUE TITLE
Hunter Pet stats display

### ISSUE THREAD

**Issue by Redrian-Hellscream** [Valhalla-Gaming/Tracker#618]
Hunter's pet stats windows displays 1-1 as damage value, while the real damage is calculated correctly.

**Comment by zwei7** [comment]
Like this
![wowscrnshot_111415_235753](https://cloud.githubusercontent.com/assets/15259298/11167334/8e4eaaf8-8b2b-11e5-9781-4d6e102b7d1e.jpg)

**Comment by Tregeta** [comment]
#2266
