### ISSUE TITLE
[SHAMAN] Spell " Ghost Wolf " bug

### ISSUE THREAD

**Issue by Aristeas** [Valhalla-Gaming/Tracker#6181]
Hi
When, I cast a Ghost Wolf spell the maelstrom bar disappear and  he come back after i change specialization or reconnect 
Before cast spell : [http://imgur.com/BkMUEZm](url)
After : [http://imgur.com/j6lcyAS](url)  and [http://imgur.com/wty88W1](url)

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/6140
