### ISSUE TITLE
[DH][Skill} Fel Rush

### ISSUE THREAD

**Issue by CageValhalla** [Valhalla-Gaming/Tracker#6182]
It always does the damage if positioned correctly but wont always do animation and move the player.

**Comment by Collector-Valhalla** [comment]
"sometimes" is does move i have no idea why :<

**Comment by Hemoglobine-Valhalla** [comment]
Yep, sometimes it does move, others it doesnt, it should move to the direction facing and deal damage, same goes when you're in the air and you use it, it also should move to the direction facing

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/5964
Add details there if needed

**Comment by Moustachos** [comment]
Ref #5979
