### ISSUE TITLE
[DH][Skill] Glide

### ISSUE THREAD

**Issue by CageValhalla** [Valhalla-Gaming/Tracker#6183]
I think it should be controlable mid air (direction wise), fall speed should be slower, and also Fel Rush should been able to use midair.

**Comment by Hemoglobine-Valhalla** [comment]
yeah a dude made the report already, is like it does move to the direction facing and in valhalla that doesnt happen, wing open and u fall with them.

**Comment by Trekex** [comment]
Fel Rush Ref https://github.com/Valhalla-Gaming/Tracker/issues/5964
Glide Ref https://github.com/Valhalla-Gaming/Tracker/issues/5940
