### ISSUE TITLE
[Group] Party Loot options broken

### ISSUE THREAD

**Issue by DeathByDuke** [Valhalla-Gaming/Tracker#6185]
**Describe the issue you're having**:
Loot rolls don't happen in groups, loot options are all talent tree options - there is no way to enable or change loot options from say Group Loot to Free for All
**Explain how you expect it work**:
Loot options should be available for change, and not be talent tree specializations
**Steps to reproduce the problem**:
1. Join a party as leader
2. Try to change loot options
3. ????

**Links to Wowhead, YouTube, etc**:

**Comment by Jefferythegod** [comment]
![lootframe](https://cloud.githubusercontent.com/assets/21697206/18249062/53f37372-737c-11e6-9db2-4483332c9c21.JPG)
It should be like that but it doesn't exist

**Comment by DeathByDuke** [comment]
Agreed, the loot roll options don't appear and loot options are broken
