### ISSUE TITLE
[Mage][Spell] Ice Lance

### ISSUE THREAD

**Issue by darkus25** [Valhalla-Gaming/Tracker#6187]
**Describe the issue you're having**:
Ice Lance doesn't do any DMG. Not even against frozen targets.
**Explain how you expect it work**:
The damage against frozen targets should be tripled and against non-frozen targets it should deal (76% of Spell power) Frost damage
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=30455/ice-lance

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/6129
