### ISSUE TITLE
(Quest/Class/Spell) The Art of the Monk

### ISSUE THREAD

**Issue by Aedomus** [Valhalla-Gaming/Tracker#619]
Objective; Reach level 3 to learn Tiger's Palm. Look for a Training Dummy and practice using Tiger's Palm.

Issue; I was asked to complete "The Art of the Monk" quest...when I completed the quest, I went back Laoxi to turn in the quest...once done I looked around for another quest giver and none were available...meaning none had "!" over their heads. I rolled two different Monks in Shadowglen and had the same issue.

http://www.wowhead.com/quest=31169/the-art-of-the-monk

**Comment by phikaro** [comment]
Same here.

**Comment by Articuno** [comment]
Confirmed. Dinged lvl 3, turned in The Art of the Monk and there are no further quests.

**Comment by Luminescent-Hellscream** [comment]
This is a known issue for panda and worgens use the portals at the start of the zones to skip there leveling areas and level somewhere else.

**Comment by Articuno** [comment]
But It's in the Night Elf starting area...

**Comment by Tregeta** [comment]
We are aware of this issue in the Night Elf area.
