### ISSUE TITLE
Fel Rush jump

### ISSUE THREAD

**Issue by CuteRam** [Valhalla-Gaming/Tracker#6191]
**Describe the issue you're having**:
Fel Rush dont work in air. Or when used character gets down
**Explain how you expect it work**:
 Can be usable on air.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
https://www.youtube.com/watch?v=qdhl_K_jJ3M Like 5:40 on this video.

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/5964
