### ISSUE TITLE
Mardum, the Shattered Abyss Change abilities place

### ISSUE THREAD

**Issue by CuteRam** [Valhalla-Gaming/Tracker#6192]
**Describe the issue you're having**:
Can't find any one place for change abilities.
**Explain how you expect it work**:
I think we need any free place for it, because if got wrong spells cant change it.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by nuhrii** [comment]
You can change your spec at anytime, however if you want to change your talents you need to be in a rested EXP area

**Comment by CuteRam** [comment]
Yeah, because no rested area on this map :)

**Comment by Valhalla-Gaming** [comment]
This behavior is blizz-like. On retail there is no rest area in the DH start zone, and consequently talents can't be changed here.
