### ISSUE TITLE
can someone tell me why i cant log in 

### ISSUE THREAD

**Issue by boxty123** [Valhalla-Gaming/Tracker#6193]
**Describe the issue you're having**:
the server is offline acording to the site but i still see issue reports, but i cant play it dc's me 
**Explain how you expect it work**:
if everyone else is playing then i should be able 2 , sry if u already said why i havent seen that yet
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Gonmo** [comment]
These problems shouldnt be posted here. Try : https://valhalla-realms.com/forum/viewforum.php?f=26

**Comment by boxty123** [comment]
yes ik sry but everyone seems to respond here

**Comment by Gonmo** [comment]
Even though its not the proper way to do it. If you want to know: I am not able to connect to server yet

**Comment by boxty123** [comment]
but people are still posting issues doesnt that mean they are playing? xD

**Comment by Gonmo** [comment]
As I said before, they could write down the bugs and then (when the server is down), post them here

**Comment by nuhrii** [comment]
Close this, this is a non ingame issue
