### ISSUE TITLE
Monk: CHI

### ISSUE THREAD

**Issue by gaudium1** [Valhalla-Gaming/Tracker#6194]
**Describe the issue you're having**:
In Monk class does not works Chi.
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by boxty123** [comment]
are you a windwalker? mistweaver doesnt have chi , im not sure about brewmaster i think that has chi too

**Comment by Aveta** [comment]
Only Windwalker has Chi now.

**Comment by Moustachos** [comment]
Will be fixed on next update.

**Comment by Moustachos** [comment]
Ref #5979
