### ISSUE TITLE
Artifact traits + artifact power

### ISSUE THREAD

**Issue by Hemoglobine-Valhalla** [Valhalla-Gaming/Tracker#6196]
**Describe the issue you're having**:
1. When you gain artifact power if you relog you lose it
2. If you learned an artifact trait and you did relog such bonus is lost, in the artifact it appears that it is learned, but bonus is gone.
**Explain how you expect it work**:
Both should keep if you relog or not
**Steps to reproduce the problem**:

1.  Gain artifact power from a scroll droped by random mobs in the broken island
2.  Learn an artifact trait 
3.  relog

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/guides/acquiring-and-spending-artifact-power-and-knowledge

**Comment by neano300** [comment]
I lose 4k poitns :c *cry*

**Comment by Moustachos** [comment]
> in the artifact it appears that it is learned, but bonus is gone.

What do you mean?

If the trait appears as learned, you should still have the bonus :o

Which Artifact weapon & which trait is it?

**Comment by Hemoglobine-Valhalla** [comment]
Note: trait last after relog what is gone is the artifact level bonus which gives stam and damage

Sorry for the wrong info, i thought it was gone but it isn't, tested right now.

**Comment by Moustachos** [comment]
Okay I'll check this out.

**Comment by Moustachos** [comment]
Will be fixed on next update.
