### ISSUE TITLE
Fel Rush sometimes doesn't work, I mean it doesn't rush foward.

### ISSUE THREAD

**Issue by Matija5** [Valhalla-Gaming/Tracker#6198]
**Describe the issue you're having**:

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/5964

**Comment by Matija5** [comment]
No when u jump, sometimes while u are running your fel rush doesn't rush foward, but is still goes on CD

**Comment by Tregeta** [comment]
@matija5 please use the referenced comment to add to it, having multiple tickets opened on the same issue is very cluttered.
