### ISSUE TITLE
Demon Hunter: Fel Rush

### ISSUE THREAD

**Issue by Raizo575** [Valhalla-Gaming/Tracker#6199]
**Describe the issue you're having**:
Fel Rush doesn't propel me forward while on ground most of the time, and it never propels me forward while in mid air.
**Explain how you expect it work**:
I expect it to propel me forwards no matter where I use it, ground or air.
**Steps to reproduce the problem**:

1. Start a Demon Hunter
2. Start running or jumping.
3. Use Fel Rush.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=195072/fel-rush

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/5964

**Comment by Moustachos** [comment]
Ref #5979
