### ISSUE TITLE
Untargetable infernal in Dun Algaz

### ISSUE THREAD

**Issue by GeneralCaveman** [Valhalla-Gaming/Tracker#620]
There seems to be a small untargetable infernal (I am pretty sure they are used as place holders) in the Wetlands. The little guy two shot me at level 20 so it isn't just window dressing.

![wowscrnshot_052615_014529](https://cloud.githubusercontent.com/assets/12555606/7806010/a680df5c-0349-11e5-9000-ca3892a21a8c.jpg)

Wetlands, Dun Algaz: (48.1, 75.9)

**Comment by Kelpo122** [comment]
I also got killed there but couldn't find the source of the damage to report. Thanks!

**Comment by GeneralCaveman** [comment]
There are 2 more of these guys at (Wetlands, : 59.3, 44.9).

**Comment by Tregeta** [comment]
fixed as of may 31st 2016 build
