### ISSUE TITLE
Demon Hunter: Demon Blades

### ISSUE THREAD

**Issue by Raizo575** [Valhalla-Gaming/Tracker#6200]
**Describe the issue you're having**:
Takes away my Demon's Bite skill but in return my auto attacks don't deal additional Shadow Damage on a 75% chance and neither do they generate any Fury.
**Explain how you expect it work**:
I expect it to make my auto attacks deal Shadow Damage on a 75% chance and generate Fury.
**Steps to reproduce the problem**:

1. Play Demon Hunter
2. Pick the Talent Demon Blades
3. Start attacking anything.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=203555/demon-blades

**Comment by GM-Pyromanic** [comment]
#5998
