### ISSUE TITLE
[spell][racial][Running wild]

### ISSUE THREAD

**Issue by Diuesh** [Valhalla-Gaming/Tracker#6201]
Whenever I use Running wild this happens:

![14215605_511524895721868_1415648851_o](https://cloud.githubusercontent.com/assets/21990652/18270942/49c44216-7438-11e6-9688-af9a98772295.png)

**Comment by EldritchIHC** [comment]
Like

**Comment by EldritchIHC** [comment]
A better explanation would be:"running wild racial spell has the animation/model broken".Next time explain it better N00b.

**Comment by forstix** [comment]
already reorted: https://github.com/Valhalla-Gaming/Tracker/issues/6186
And EldritchIHC u can be nice sometimes

**Comment by Tregeta** [comment]
Ref to #6186
