### ISSUE TITLE
Fel Rush

### ISSUE THREAD

**Issue by drethz** [Valhalla-Gaming/Tracker#6204]
**Describe the issue you're having**:
When using Fel Rush while mid-air and while have the Glide on, Fel Rush brings you on the ground.

**Explain how you expect it work**:
It should work so that Fel Rush boosts you forward.

**Steps to reproduce the problem**:

1. Have a Demon Hunter
2. Double jump and activate Glide
3. Use Fel Rush

**Links to Wowhead, YouTube, etc**:
Sorry, i couldn't find any videos about this. But I HAVE seen it working on Retail!

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/5964
