### ISSUE TITLE
Sub Rogue

### ISSUE THREAD

**Issue by ElrondMcBong1337** [Valhalla-Gaming/Tracker#6205]
**Describe the issue you're having**:

1.Shadowstrike does not teleport you to the target location, it seems to have a increased range...
2.Shadowdance does not always enable to use stealth abilities 
3.Symbols of Death seem not to make Shadowstrike crit
4.Backstab does not work if you are in front of the enemy
5.may be mentioned before but stealth doesn't do anything

**Explain how you expect it work**:

1.Teleport to target within 25yd range
2.You can use stealth abilities and activate the "actionbar" like you were in stealth
3.Make shadowstrike crit and increase all damage done by 20%
4.Deal damage in front, deal more behind target
5.Make invisible/stealthy and activate the other "actionbar" (sry don't know the English term)

**Steps to reproduce the problem**:

Just use the abilities

**Links to Wowhead, YouTube, etc**:

http://www.wowhead.com/guides/classes/rogue/subtlety/overview

**Comment by ElrondMcBong1337** [comment]
Shadowdance works mostly but does not show buff and not highlight skills sometimes(so you can not use them)

**Comment by Moustachos** [comment]
Symbols of Death's effect on Shadowstrike works just fine.

**Comment by Moustachos** [comment]
Ref #5979
