### ISSUE TITLE
Death Grip

### ISSUE THREAD

**Issue by Neredun** [Valhalla-Gaming/Tracker#6207]
**Describe the issue you're having**:
Death Grip send you to the Enemy location instead of drawing the target toward you
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. Use Death Grip on a Enemy
2. See how the bug happen
3. 

**Links to Wowhead, YouTube, etc**:
Death Grip: http://www.wowhead.com/spell=49576

**Comment by Trekex** [comment]
Fixed last update
