### ISSUE TITLE
Horn of Winter

### ISSUE THREAD

**Issue by Neredun** [Valhalla-Gaming/Tracker#6208]
**Describe the issue you're having**:
Horn of Winter only gives you 10 p. of Runic Power, but the spell doesn't restore you the 2 runes 
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. Use Runes
2. Use Horn of Winter
3. 

**Links to Wowhead, YouTube, etc**:
Horn of Winter: http://www.wowhead.com/spell=57330

**Comment by Trekex** [comment]
Fixed last update
