### ISSUE TITLE
[Legion] Dalaran portals are missing

### ISSUE THREAD

**Issue by GM-Pyromanic** [Valhalla-Gaming/Tracker#6209]
**Describe the issue you're having**:
The portals from the legion version of dalaran are currently missing for both Horde and Alliance
**Explain how you expect it work**:
Portals should always be spawned in a area of Dalaran for alliance and Horde to major capitals of each faction.
**Steps to reproduce the problem**:

1. Head to Grayfang Enclave for alliance portals.
2. Head to Windrunners Sanctuary for Horde portals.
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/6126
