### ISSUE TITLE
Removed WoD Talents Still on Characters

### ISSUE THREAD

**Issue by llamalama** [Valhalla-Gaming/Tracker#6210]
Looking in the general tab of the spell book, I noticed some abilities that I chose as a talent in WoD are still there and useable. This may be applying to passive talents but I cannot tell as they do not show up in the spellbook.

These are all the spells I have confirmed to be on my pre-legion created characters:

Death Knight:
http://www.wowhead.com/spell=48743/death-pact
http://www.wowhead.com/spell=49039/lichborne
http://www.wowhead.com/spell=123693/plague-leech

Hunter:
http://www.wowhead.com/spell=162534/exotic-munitions

Paladin:
http://www.wowhead.com/spell=157048/final-verdict (note that this is not the same as the level 15 ret paladin talent with the same name)

Rogue:
http://www.wowhead.com/spell=108212/burst-of-speed
http://www.wowhead.com/spell=74001/combat-readiness

Druid:
http://www.wowhead.com/spell=171745/claws-of-shirvallah (This one does not show up in the general tab, it is on your normal animal forms bar in the cat form space)

I do not know if the spells kept for characters are random or if everyone who picked these talents also has them. There are possibly other talents that I didn't pick that other characters have.

**Comment by LordYawgmoth** [comment]
plz remove burst of speed form old chars, it is already getting abused in bg on the first day

**Comment by LordYawgmoth** [comment]
suggestion if removing it from every player is too bothersome just make the skill not having an effect for using it

**Comment by Moustachos** [comment]
Ref #5979
