### ISSUE TITLE
[Clean Up the Bag]

### ISSUE THREAD

**Issue by NaughtyDecent** [Valhalla-Gaming/Tracker#6212]
**Describe the issue you're having**:
Clean up the bag button turns all items to grey and they are bugged. you can't do anything to those untill you relog.
**Explain how you expect it work**:
It should auto rearrange the items in bags.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/2529
