### ISSUE TITLE
[Quest] [The Far watch Offensive]

### ISSUE THREAD

**Issue by NaughtyDecent** [Valhalla-Gaming/Tracker#6214]
**Describe the issue you're having**:
Unable to turn in the quest after completion. It is located in Northern Barens
**Explain how you expect it work**:
it should let me turn in so that i can get xp and gold.
**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Cidragon** [comment]
This is working now.
