### ISSUE TITLE
Earth Shock Broken

### ISSUE THREAD

**Issue by AIAS2** [Valhalla-Gaming/Tracker#6217]
**Describe the issue you're having**:
Earth Shock is not working properly, it consumes 10 maelstorm every use and hits as if 100 were consumed making it overpowered
**Explain how you expect it work**:
Damage should vary depending on maelstorm spent
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Trekex** [comment]
Fixed already
