### ISSUE TITLE
Lava Burst

### ISSUE THREAD

**Issue by AIAS2** [Valhalla-Gaming/Tracker#6219]
**Describe the issue you're having**:
Lava Burst works fine when it comes to damage, visual is out of date however
**Explain how you expect it work**:
Visual should be updated
**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by llamalama** [comment]
This spell is critting 100% of the time even when your target does not have Flame Shock on it when it should not.

**Comment by Moustachos** [comment]
Ref #5979
