### ISSUE TITLE
[Legion] [Warlock] [Affliction] [Talent] Siphon Life has no effect

### ISSUE THREAD

**Issue by Usernameisntalreadytaken** [Valhalla-Gaming/Tracker#6230]
http://www.wowhead.com/spell=35195/siphon-life

The debuff shows up when cast on an enemy, with a seemingly correct tooltip, (just like any other afflock DoT) but it never procs/deals any damage as it should.

Tested while full hp on grey full hp lv1 mobs

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #5979
