### ISSUE TITLE
[Legion] [Warlock] [Mounts] [Collection] Felsteed

### ISSUE THREAD

**Issue by Usernameisntalreadytaken** [Valhalla-Gaming/Tracker#6231]
Warlocks get 2 class mounts: the felsteed, then the dreadsteed.
(well, all of my other mounts, including the flying ones, disappeared...)

Everytime I log in, and I think upon map/instance change too, it tells me I've got new items in my collection (small popup at the bottom) and tells me to unwrap them.

And every single time, it's just the felsteed counting as a newly acquired mount.

That's it, it just gets annoying tho.

Thanks.

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #5979
