### ISSUE TITLE
DK Change Spec No Runes Bug

### ISSUE THREAD

**Issue by benedickt** [Valhalla-Gaming/Tracker#6236]
**Describe the issue you're having**:
if you try to change spec, you **can't use spells that cost runes.**
**Explain how you expect it work**:
you should be able to switch spec and have **spells that require runes** work right away
**Steps to reproduce the problem**:
1. make a dk
2. switch to any other spec
3. attempt to use **spell that costs runes** on mob

**Links to Wowhead, YouTube, etc**:

**Comment by benedickt** [comment]
Updated, found what was really happening, regarding runes.

**Comment by theprototyze** [comment]
This issue doesn't exist anymore in 7.1.5
