### ISSUE TITLE
Blood DK Blooddrinker Talent

### ISSUE THREAD

**Issue by benedickt** [Valhalla-Gaming/Tracker#6243]
**Describe the issue you're having**:
when blooddrinker is used, you're not healed.
**Explain how you expect it work**:
blooddrinker should drain health from the target, healing the user.
**Steps to reproduce the problem**:

1. make a blood dk and select talent blooddrinker
2. find mob
3. use blooddrinker

**Links to Wowhead, YouTube, etc**:

**Comment by ElrondMcBong1337** [comment]
It also does not deal damage ^^

**Comment by Moustachos** [comment]
Ref #5979
