### ISSUE TITLE
[Quest] Their numbers are legion

### ISSUE THREAD

**Issue by Nicoray360** [Valhalla-Gaming/Tracker#6244]
**Describe the issue you're having**:
Upon completing this quest, the player does not get the item reward. It onl grants experience and gold as rewards

**Explain how you expect it work**:
Should also reward this item for Night Elf: http://www.wowhead.com/item=128950/demon-rend-shoulderblades
and this one for Blood Elf: http://www.wowhead.com/item=133311/demon-rend-shoulderblades

**Steps to reproduce the problem**:
1. Get the quest
2. Complete it
3. 

**Links to Wowhead, YouTube, etc**:
Quest link: http://www.wowhead.com/quest=38819/their-numbers-are-legion

**Comment by Analog-Valhalla** [comment]
Duplicate #9237
