### ISSUE TITLE
Demon Hunter Level 100 Spells

### ISSUE THREAD

**Issue by Neredun** [Valhalla-Gaming/Tracker#6253]
**Describe the issue you're having**:
When a Demon Hunter reach level 100 they should obtain the following spells:
-Blade Dance
-Imprison
-Darkness
**Explain how you expect it work**:
seting that abilities to learn at level 100
**Steps to reproduce the problem**:

1. Create a Demon Hunter
2. Reach level 100
3. 

**Links to Wowhead, YouTube, etc**:
Blade Dance: http://www.wowhead.com/spell=188499
Imprison: http://www.wowhead.com/spell=217832
Darkness: http://www.wowhead.com/spell=196718

**Comment by Redrian-Hellscream** [comment]
Indeed, I tested demon hunters and they don't obtain those abilities even when hitting level 110.

**Comment by nuhrii** [comment]
Should be noted that Blade Dance and Darkness are Havoc only

**Comment by KaelM** [comment]
I choosed Havoc and don't recieved these spells too.

**Comment by Moustachos** [comment]
Ref #5979
