### ISSUE TITLE
Falara Nightsong Reapirer

### ISSUE THREAD

**Issue by Neredun** [Valhalla-Gaming/Tracker#6255]
**Describe the issue you're having**:
The npc Falara Nightsong in Mardum, the shattered abyss, doesn't show his items to buy and doesn't repair yours
**Explain how you expect it work**:
Adding items to the npc_vendor table
**Steps to reproduce the problem**:

1. Use Demon Hunter
2. Go to Illidari Camp
3. Look for Falara

**Links to Wowhead, YouTube, etc**:
Falara Nightsong: http://www.wowhead.com/npc=96650/

**Comment by Braemen** [comment]
#6034

**Comment by Trekex** [comment]
As commented by Braemen, this issue is already opened.
