### ISSUE TITLE
[Legion] [Warlock] [Affliction] [Talent] Writhe in Agony has no effect

### ISSUE THREAD

**Issue by Usernameisntalreadytaken** [Valhalla-Gaming/Tracker#6258]
I'm starting to think I shouldnt bother reporting broken talents since none are scripted.

http://www.wowhead.com/spell=196102/writhe-in-agony
"Agony's damage may now ramp up twice as high."
aka Agony should get up to 20 stacks as opposed to 10 max if you spec in that talent

well, when i cast agony on someone, it doesn't ever get above 10 stacks despite me having the talent
that's all.

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #5979
