### ISSUE TITLE
[Legion] [Warlock] CRITICAL: soul shards

### ISSUE THREAD

**Issue by Usernameisntalreadytaken** [Valhalla-Gaming/Tracker#6260]
Currently specced in affliction
I only ever have 1 soul shard MAX at any given time, out of 5 maximum

and that's bad

When resting, it only regens up to 1.
During fights, I should be able to get soul shards back from AGONY and maybe some other spells, but that just never happens.

So basically as an afflock I'm limited to 1 soul shard per fight and then cant do crap, I have to get back out of combat for a while to cast anything worthwhile.

tl,dr game-breaking bug regarding soul shard regen (just like in WOD) which just doesnt happen

**Comment by nuhrii** [comment]
This is not a bug warlock will always have 1 Soul Shard out of combat and will degen a Soul Shard every 30 seconds out of combat, you are supposed to generate Soul Shards out of spells and nothing else

**Comment by Collector-Valhalla** [comment]
https://worldofwarcraft.com/en-us/news/20252902#1

hotfixed recently to:
"Soul Shards now regenerate to 3, while out of combat (up from 1)."

**Comment by nuhrii** [comment]
That still wouldn't make it a bug since we are not on that build, we are using a live build, if its not like that when we do reach that build then yes it is a bug

**Comment by Usernameisntalreadytaken** [comment]
It's not just agony, it's a combination of agony not giving soul shards, soul conduit never refunding any, and every single other spell/ability/talent which should generate soul shards doesn't either

**Comment by Moustachos** [comment]
Ref #5979
