### ISSUE TITLE
spriest spell - Vampiric Touch

### ISSUE THREAD

**Issue by forstix** [Valhalla-Gaming/Tracker#6275]
**Describe the issue you're having**:
Vampiric Touch does only 2 shadow dmg per 2.6 sec at lvl 110

**Explain how you expect it work**:
Vampiric Touch tooltip say it should dmg the taget for 142620 shadow dmg over 18 sec
which mean alot more then 2 per 2.6 sec
**Steps to reproduce the problem**:

1. roll shadow priest 
2. use vt on target 
3. check this dmg

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=34914/vampiric-touch#changelog

**Comment by forstix** [comment]
seen to works atm for some reason

**Comment by Moustachos** [comment]
Ref #5979
