### ISSUE TITLE
90 BOOST LEVEL PASSENGER was DISPATCH

### ISSUE THREAD

**Issue by Furyr** [Valhalla-Gaming/Tracker#6283]
#? .**Describe the issue you're having**:
I BUY 90 LVL BOOST BUT DONT SEND ME MOUNT PLS I DONT HAVE MOUNT
![das](https://cloud.githubusercontent.com/assets/22060103/18397489/2b1734ae-76d1-11e6-8a4e-12958996a118.png)

**Explain how you expect it work**:

**Steps to reproduce the problem**:
1
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Braemen** [comment]
You opened 3 identical issues in less than 24 hours... #6283, #6363, #6371. C'mon man...
Issue is already reported, just use search function.
#6114 #5959

**Comment by GM-Pyromanic** [comment]
Please send me a screenshot on the forums of your purchase history along with the mount you picked to Pyromanic.

**Comment by Furyr** [comment]
![image](https://cloud.githubusercontent.com/assets/22060103/18397510/3f63bfb8-76d1-11e6-8461-a7089df19ea2.png)
