### ISSUE TITLE
Warlock: Pet: Grimoire of Supremacy Doomguard

### ISSUE THREAD

**Issue by nuhrii** [Valhalla-Gaming/Tracker#6300]
**Describe the issue you're having**:
This Doomguard has mana still instead of energy so he can't cast anything since those cost energy
**Explain how you expect it work**:
Doomguard has energy
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/npc=78158

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/6298
