### ISSUE TITLE
Portals!

### ISSUE THREAD

**Issue by Ac3ofShadows** [Valhalla-Gaming/Tracker#6304]
**Describe the issue you're having**:
I'm seeing alot of important portals missing. This should be a quick fix.
Note: Dalaran portals for orgrimmar, vale of eternal blossoms, etc.
Same for the alliance side.
**Explain how you expect it work**:
There should be a bunch of portals in Windrunners Sanctuary, Dalaran.
As it currently is there is no way to get to ORG/SW without using HS thats set in capitals.
**Steps to reproduce the problem**:

1. Go to new Dalaran.
2. Try to get back to the capitals without having a HS set in capitals.
3. $$$

**Links to Wowhead, YouTube, etc**:

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/6126
