### ISSUE TITLE
All Reputation Gains Broken with Legion Release

### ISSUE THREAD

**Issue by ATalisan** [Valhalla-Gaming/Tracker#6313]
Varedis Must Be Stopped - with the aldor grants no reputation change
Netherwing Daily Quests - no reputation change

**Comment by nuhrii** [comment]
You should change this to just reputation gain, because i went around and test a few quests that i knew that were going to give me reputation they didn't give me any at all

**Comment by Collector-Valhalla** [comment]
You don't get reputation from ALL quests ingame. Legion release broke it.
:<

**Comment by Collector-Valhalla** [comment]
Is it any high at priority list? We are losing lots of reputation while leveling without it.

**Comment by Bugtracker3000** [comment]
yes we are losing a lots of time with this bug, please , rep is 1 of most important thing in wow,lets change to high proprity

**Comment by Bugtracker3000** [comment]
ps: if u kill mob in firelands, u gain xp. Some mobs give u xp aroun all wow (about 2-4 factions)

**Comment by ATalisan** [comment]
No updates on this? I was hoping to start playing again, but it's kinda pointless until reputation works.

**Comment by Traveler-Valhalla** [comment]
Play like me. My 72 level paladin has 0 quests done. All by grinding at x5 rates lol.

**Comment by ATalisan** [comment]
Doesn't really help while doing Netherwing quests to get a drake. ^_^

**Comment by Traveler-Valhalla** [comment]
is this fixed now? i received reputation from a quest in elwynn..
