### ISSUE TITLE
DK Dark Succor

### ISSUE THREAD

**Issue by benedickt** [Valhalla-Gaming/Tracker#6318]
**Issue**:
Dark Succor does **not** proc for **Frost spec**, while it does proc for Unholy.

**How it should work**:
Dark succor should proc when the player kills an enemy or player, granting a free death strike with 100% added healing effects.
**Steps to reproduce the problem**:
1. make frost dk
2. hit level 60
3. kill a mob that grants exp or player

**Comment by benedickt** [comment]
I thought I made a mistake so I closed issue, but re-opened after realizing I was right afterall.

**Comment by Moustachos** [comment]
Ref #5979
