### ISSUE TITLE
Mining

### ISSUE THREAD

**Issue by Trekex** [Valhalla-Gaming/Tracker#6326]
**Describe the issue you're having**:
When I try to mine in Broken Island, it says "Invalid target"
**Explain how you expect it work**:
It should mine the deposit, I guess
**Steps to reproduce the problem**:
1. Find a mining place
2. Click on it
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Falango** [comment]
This started happening to me in Darkshore today too
