### ISSUE TITLE
Hunter: Scalehides, probably Oxen and Mechanicals

### ISSUE THREAD

**Issue by nuhrii** [Valhalla-Gaming/Tracker#6330]
Can't Tame any memebers of the new Scalehide family and probably Oxen and Mechanical familes

**Comment by Moustachos** [comment]
Can't reproduce this issue, I've been able to tame the following Scalehide pets:
- http://www.wowhead.com/npc=56239/adolescent-mushan
- http://www.wowhead.com/npc=4700/aged-kodo

If you're unable to tame a specific creature, please provide a wowhead link, closing the issue.

**Comment by Moustachos** [comment]
Ref #5979
