### ISSUE TITLE
(Class) A Mage's Bugged Spell

### ISSUE THREAD

**Issue by Delahunts** [Valhalla-Gaming/Tracker#6332]
**Describe the issue you're having**: Mage's spell "Flurry" does not work. I can cast it, but it doesn't deal any damage to the enemy.

**Explain how you expect it work**: To deal damage and work.

**Steps to reproduce the problem**: Fixing. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=44614/flurry
https://www.youtube.com/watch?v=DovIt9qcEx4

**Comment by nuhrii** [comment]
dupl #6272

**Comment by Moustachos** [comment]
Ref #5979
