### ISSUE TITLE
Demon Hunter Annihilation

### ISSUE THREAD

**Issue by Neredun** [Valhalla-Gaming/Tracker#6335]
**Describe the issue you're having**:
The Skill Annihilation hits both the target and the demon hunter self, that shouldn't happen
**Explain how you expect it work**:
fixing the spell to only hit the enemy
**Steps to reproduce the problem**:

1. Use Demon Hunter Dps
2. Use Metamorphosis
3. Use Annihilation

**Links to Wowhead, YouTube, etc**:
Annihilation: http://www.wowhead.com/spell=201427

**Comment by Moustachos** [comment]
This spell only hits the target as of current version, closing the issue.

**Comment by Moustachos** [comment]
Ref #5979
