### ISSUE TITLE
spriest spell - Dispersion

### ISSUE THREAD

**Issue by forstix** [Valhalla-Gaming/Tracker#6352]
**Describe the issue you're having**:
when Dispersion active your insnity keep draining 
**Explain how you expect it work**:
Dispersion should make the insnity bar freze until Dispersion end
**Steps to reproduce the problem**:

1. roll shadow priest
2. enter voidform
3. use Dispersion and see what happend
**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=47585/dispersion

**Comment by Trekex** [comment]
Fixed last update
