### ISSUE TITLE
Monk: Wind Walker artifact ability unusable after leveling up once

### ISSUE THREAD

**Issue by kpurc** [Valhalla-Gaming/Tracker#6353]
**Describe the issue you're having**:
When leveling from 100-110 I notice that every single time I leveled up, my artifact ability would be unuseable until I relogged 
**Explain how you expect it work**:
Spell works great as a whole, but after I level once it requires a relog to reuse.
**Steps to reproduce the problem**:

1. Use WW artifact ability
2. Level Once
3. ***Realize spell is unuseable till relogged***

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=205320/strike-of-the-windlord

**Comment by Moustachos** [comment]
Can't reproduce on current version, seems to work just fine.

**Comment by Moustachos** [comment]
Ref #5979
