### ISSUE TITLE
Artifact Power.

### ISSUE THREAD

**Issue by neano300** [Valhalla-Gaming/Tracker#6354]
**Describe the issue you're having**:
The artifact power it reboots when you relog
**Explain how you expect it work**:
The artifact power can't rebots when you relog
**Steps to reproduce the problem**:

1. Learn the Artifact power watch your points
2. Reload
3. And watch again

**Links to Wowhead, YouTube, etc**:
https://www.youtube.com/watch?v=an_ZsIiW6q8&feature=youtu.be

I lose 10k Artifact points with this... is frustrating..

**Comment by boxty123** [comment]
amm where do you get artifact power? the quests in the legion zones dont work do they?

**Comment by Hemoglobine-Valhalla** [comment]
This isn't the place to make such answer, this is the bug tracker not the forum.

**Comment by CageValhalla** [comment]
Confirming this bug, happened to me, after 2 hours of grinding got random dc, when I logged back everything all AP I had was gone.

**Comment by Redrian-Hellscream** [comment]
Why is this not pinned to the ultimate tracker? it's the most annoying bug at the moment.

**Comment by Guybrush-VR** [comment]
I missed it, good catch!

**Comment by Moustachos** [comment]
Will be fixed on next update.

Ref #5979
