### ISSUE TITLE
too much fury

### ISSUE THREAD

**Issue by Collector-Valhalla** [Valhalla-Gaming/Tracker#6356]
After recent update demon hunters have thousands of fury (and pain in tank spec) points. Max should be 100.

![wowscrnshot_090816_070207](https://cloud.githubusercontent.com/assets/14946340/18337671/e14167c6-7592-11e6-8b01-16ddb0a4a3a0.jpg)

**Comment by boxty123** [comment]
tank dh doesnt have pain bar it has the same fury bar as havoc

**Comment by Neredun** [comment]
confirmed, and we can use all that fury, so is not only visual 
Images: http://imgur.com/a/OhtBG

**Comment by Redrian-Hellscream** [comment]
It's fixed now, should be closed.
