### ISSUE TITLE
Sigil of Chains Demon Hunter Tank

### ISSUE THREAD

**Issue by neano300** [Valhalla-Gaming/Tracker#6360]
**Describe the issue you're having**:
The demon hunters tank have the spell  Sigil of Chains in spellbook
**Explain how you expect it work**:
This skill is from talent so we can't have it in the spellbook without learn
**Steps to reproduce the problem**:

1. Level up in the Dh start zone to level 105-106 and automatically this spell will learn alone
2. -
3. -

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=202138/sigil-of-chains

[img]http://i.imgur.com/HleIVTO.jpg[/img]

**Comment by Moustachos** [comment]
Can't reproduce this issue, I only learn Sigil of Chains through talent tree.

**Comment by Moustachos** [comment]
Ref #5979
