### ISSUE TITLE
Druid Spell: Stag Form 

### ISSUE THREAD

**Issue by skorge1** [Valhalla-Gaming/Tracker#6362]
**Describe the issue you're having**:
When i use Stag form i cannot be mounted by any of the members in my party or raid.
**Explain how you expect it work**:
I expect for me to be mount while in the stag form.
**Steps to reproduce the problem**:

1. Acquire Tome of the wilds: Stag Form and learn it.
2. Join a group 
3. Turn into Stag form

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=210053/stag-form

**Comment by Moustachos** [comment]
Will be fixed on next update.

**Comment by Moustachos** [comment]
Ref #5979
