### ISSUE TITLE
90 LVL BOOST İS BUG

### ISSUE THREAD

**Issue by Furyr** [Valhalla-Gaming/Tracker#6363]
**Describe the issue you're having**:
NOT ARMOR NOT MOUNT NOT WEAPON
**Explain how you expect it work**:
SEND ME 
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Braemen** [comment]
You opened 3 identical issues in less than 24 hours... #6283, #6363, #6371. C'mon man...
Issue is already reported, just use search function.
#6114 #5959

**Comment by GM-Pyromanic** [comment]
Duplicate report #6283
