### ISSUE TITLE
Demon Hunter Class Order Hall

### ISSUE THREAD

**Issue by boxty123** [Valhalla-Gaming/Tracker#6365]
Demon hunters dont have a class order hall? We cant buy the gear from our order hall? Or pick artifact traits. Fix please

**Comment by Trekex** [comment]
Demon Hunters have an Order Hall and you can pick your artifact traits in the forge in there.

**Comment by boxty123** [comment]
can u tell me how to get there

**Comment by Trekex** [comment]
It's the small floating island you see from Krasus Landing in Dalaran. You have to get there with double jump and glide
