### ISSUE TITLE
Some Windwalker Monk bugs

### ISSUE THREAD

**Issue by fake911** [Valhalla-Gaming/Tracker#6367]
**Describe the issue you're having**:
Hello. I've just started playing in this server and I noticed few bugs on my main class - WW Monk. First one is Fists of Fury damage - the ability deals damage only once (after casting it) and then does no damage at all. Another crucial bug is Touch of Death damage - after 8 seconds the damage done is 1 when it should be equal to your maximum health. I noticed lvl 100 talent Whirling Dragon Punch is bugged as well (deals no damage at all), but I see it as a secondary bug since Serenity is usable. Absolutely the same thing I spotted in the 15 lvl talents, where Eye of the Tiger works fine, but Chi Burst doesn't work (no damage, no healing). I'll put wowhead links for all 4 spells, however, my main point in this report is on FoF and ToD.
**Explain how you expect it work**:
Fists of Fury deals damage over time whilst the player channels it. Touch of Death deals big damage after 8 seconds.
**Steps to reproduce the problem**:

1. Acquire 3 chi, cast Fists of Fury and see the health of the enemy - it stays as it is, as FoF hits only once.
2. Use Touch of Death and wait till it expires - the damage done equals 1.

I usually don't report bugs etc., I am patient and I know they will eventually be fixed. But, as a WW Monk to miss 2 of your main abilities is a pain. The damage from FoF is a huge part of the Windwalker gameplay, same as ToD. I hope you guys find time to fix at least one from these abilities in the coming weeks. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=113656/fists-of-fury
http://www.wowhead.com/spell=115080/touch-of-death
http://www.wowhead.com/spell=123986/chi-burst
http://www.wowhead.com/spell=152175/whirling-dragon-punch

**Comment by boxty123** [comment]
u just joined the server and ur past lvl 100?

**Comment by fake911** [comment]
No, I saw a lvl 100 Monk testing spells out in Orgrimmar. So I saw that WDP isn't working, and the other spells I reported as well. I am currently lvl 62.

**Comment by Moustachos** [comment]
Ref #5979
