### ISSUE TITLE
90 level boost servise bug

### ISSUE THREAD

**Issue by Furyr** [Valhalla-Gaming/Tracker#6371]
**Describe the issue you're having**:
buy boost service but dont send me mount , armor , weapon
**Explain how you expect it work**:
SEND ME MOUNT , WEAPON , ARMOR 
                                                      PLS READ

**Comment by Braemen** [comment]
You opened 3 identical issues in less than 24 hours... #6283, #6363, #6371. C'mon man...
Issue is already reported, just use search function.
#6114 #5959

**Comment by GM-Pyromanic** [comment]
Duplicate report #6283
