### ISSUE TITLE
Undead unplayable

### ISSUE THREAD

**Issue by Hatevein** [Valhalla-Gaming/Tracker#6372]
Hey guys (: 

Upon creating a new  Undead character (Does not matter which class) you enter the game lying down. You cannot stand up in any way, I've tried everything but to no avail. 

Upon creating an Undead character there should be a Valkyrie waiting in front of you with a quest. This quest should trigger your character to stand up. No quest of any sort is available to do so.

Simply create an Undead to recreate

**Comment by Emberflame** [comment]
There is a buff you need to take it off,it is on the top right of the screen.

**Comment by Seregruth** [comment]
#5960
