### ISSUE TITLE
[Death Knight] (Blood) - Bonestorm

### ISSUE THREAD

**Issue by Ulvos** [Valhalla-Gaming/Tracker#6374]
**Describe the issue you're having**:
not working properly:
Death and Decay - DoT AoE on the ground
Blood Boil - does not apply Blood Plague
Bonestorm - only use 10 runic power so it only last for 1 sec

**Explain how you expect it work**:
Death and Decay - there should be a circle that does AoE
Blood Boil - All Enemies hit by Blood Boil should have Blood Plague
Bonestorm - similar to Breath of Sindragosa? not sure

**Steps to reproduce the problem**:

**Links to Wowhead, YouTube, etc**:
Death and Decay - http://www.wowhead.com/spell=43265/death-and-decay
Blood Boil - http://www.wowhead.com/spell=50842/blood-boil
Bonestorm - http://www.wowhead.com/spell=194844/bonestorm

**Comment by Trekex** [comment]
Death and Decay & Blood Boil fixed last update

**Comment by Moustachos** [comment]
Ref #5979
