### ISSUE TITLE
[Quest] Rescue the Fallen

### ISSUE THREAD

**Issue by Rhicas** [Valhalla-Gaming/Tracker#6376]
Describe the issue you're having:
did the quest tried to turn it in but when i click the complete button nothing happens (tried reloggin and restarting)
Explain how you expect it work:
i expect it to finish the quest
Steps to reproduce the problem:
1. Do quest
2. Try to turn it in
   Links to Wowhead, YouTube, etc:
   http://www.wowhead.com/quest=13613/rescue-the-fallen

(On a side note i ran into this issue before on a other quest and i noticed that both quest where added/changed with the  Cataclysm expansion maybe it has something to do with that??)

**Comment by Cidragon** [comment]
It's working now.
