### ISSUE TITLE
Conjure Refreshment

### ISSUE THREAD

**Issue by Emberflame** [Valhalla-Gaming/Tracker#6377]
**Describe the issue you're having**:The following Spell that not work,when executed nothing happens it does not create food

**Explain how you expect it work**:It should create food

**Steps to reproduce the problem**:

1. Create a mage
2. Hit level 22
3. Test the spell

**Links to Wowhead, YouTube, etc**:http://www.wowhead.com/spell=42955/conjure-refreshment

**Comment by GM-Pyromanic** [comment]
Duplicate report #6189
