### ISSUE TITLE
Demon blade Talent

### ISSUE THREAD

**Issue by Emberflame** [Valhalla-Gaming/Tracker#6378]
**Describe the issue you're having**:The following Talent does not work, no fury generated or shadow damage added.

**Explain how you expect it work**:The  auto attack should have 75% chance to have addtional shadow damage and generate fury.

**Steps to reproduce the problem**:

1. Create a demon Hunter
2. Hit level 100 and choose the following talent Demon blades
3. Attack any mob,you won't be generating any fury

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=203555/demon-blades

**Comment by GM-Pyromanic** [comment]
Duplicate report #5998
