### ISSUE TITLE
Divine Storm Does NOT Work

### ISSUE THREAD

**Issue by AIAS2** [Valhalla-Gaming/Tracker#6379]
**Describe the issue you're having**:
There is no animation, nor damage dealt, however it consumes holy power
**Explain how you expect it work**:
An animation should appear and damage should be inflicted to all targets nearby as specified by spell
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by GM-Pyromanic** [comment]
#5979

**Comment by Laevoth** [comment]
Just for verification, this still is not working. Using the spells grants no damage or animation, but still uses holy power.

**Comment by AIAS2** [comment]
Not working, neither is templars verdict

**Comment by Moustachos** [comment]
Ref #5979
