### ISSUE TITLE
[DH] Demon Blade talent

### ISSUE THREAD

**Issue by iblast** [Valhalla-Gaming/Tracker#6380]
**Describe the issue you're having**:
Demon Blade not working
**Explain how you expect it work**:
We'll i'd shouldve generate fury with auto attacks but it doenst
**Steps to reproduce the problem**:

1.  Fix the Talent
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=203555/demon-blades

**Comment by GM-Pyromanic** [comment]
Duplicate report #5998
