### ISSUE TITLE
[Havoc] Demon Hunter Metamorphosis

### ISSUE THREAD

**Issue by Neredun** [Valhalla-Gaming/Tracker#6387]
**Describe the issue you're having**:
The Metamorphosis spell of Havoc (dps) Demon Hunter do a lot of damage when you do the first part (leap and stun)
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. Use Demon Hunter (Havoc)
2. Use Metamorphosis spell and jump in a enemy location (Tested in Arena)
3. see the Combatlog

**Links to Wowhead, YouTube, etc**:
Combatlog: http://imgur.com/a/dGqG7
Metamorphosis Spell: http://www.wowhead.com/spell=191427
Metamorphosis Spell (Probably this link is for the Leap and Stun part): http://www.wowhead.com/spell=200166

**Comment by Redrian-Hellscream** [comment]
Metamorphosis deals very high damage only on players, many other class abilities do the same and it may be a bug in pvp's scaling system, not in the ability itself but I can't be sure.

**Comment by Moustachos** [comment]
Will be fixed on next update.

**Comment by Moustachos** [comment]
Ref #5979
