### ISSUE TITLE
[Mage] Hot Streak and Heating Up

### ISSUE THREAD

**Issue by Emberflame** [Valhalla-Gaming/Tracker#6389]
**Describe the issue you're having**:Hot Streak and Heating Up don't work

**Explain how you expect it work**:After dealing a critical strike with a direct damage fire ability ( Fireball, Scorch, Inferno Blast, Pyroblast ) mage should get Heating Up buff. While having Heating Up next critical strike will replace that buff with Pyroblast! buff, increasing damage - reducing mana cost and making pyroblast instant cast.

**Steps to reproduce the problem**:

1. Create a mage choose fire as a spec
2. hit level 12
3. cast any spell as critical strike,you should have the heating up proc.

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=195283/hot-streak

**Comment by Braemen** [comment]
#1878

**Comment by Moustachos** [comment]
Ref #5979
