### ISSUE TITLE
[Warlock] [Spell] Life Drain

### ISSUE THREAD

**Issue by W0lf91** [Valhalla-Gaming/Tracker#6390]
**Describe the issue you're having**:
When i use "Life Drain" it's supposed to damage enemy and cure me for 600% of damage done.
the cure effect work as intended, but not the damage. I'm level 5 and it should inflict 9 damage every second for 6 second, but instead it deal 1 damage every second! Without the "imp" it's impossible kill the enemies.

**Steps to reproduce the problem**:
1.  Create a Warlock.
2.  use Life Drain.

![wowscrnshot_090816_204201](https://cloud.githubusercontent.com/assets/19821394/18362830/a658abe0-7607-11e6-90bb-cbfce97741b7.jpg)

**Comment by nuhrii** [comment]
dupl #5953

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #5979
