### ISSUE TITLE
[Warrior] Charge not work

### ISSUE THREAD

**Issue by tomas80208** [Valhalla-Gaming/Tracker#6393]
***Charge spell spell does not work *:

**When press the charge to jump on the enemy but only generates rage**:

**Steps to reproduce the problem**:

**Thanks for reactions**:

 I am writing this in case they should forget it because all the class already had at least 2 updates a warrior or 1

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/5961
