### ISSUE TITLE
Blood DK Death and Decay

### ISSUE THREAD

**Issue by benedickt** [Valhalla-Gaming/Tracker#6397]
**Describe the issue you're having**:
Death and Decay does near 0 dmg per tick
**Explain how you expect it work**:
it should be doing dmg over time
**Steps to reproduce the problem**:

1. make a dk
2. find mob
3. use death and decay

**Links to Wowhead, YouTube, etc**:

**Comment by Guybrush-VR** [comment]
It was fixed in a previous update.
