### ISSUE TITLE
Blood DK Blood Boil

### ISSUE THREAD

**Issue by benedickt** [Valhalla-Gaming/Tracker#6399]
**Describe the issue you're having**:
Blood Boil doesn't infect targets hit with Blood Plague (**NOTE** I was not using the Soulgorge talent, which would normally cause this.)
**Explain how you expect it work**:
targets hit by blood boil should be infected with blood plague
**Steps to reproduce the problem**:

1. make blood dk
2. find mob
3. use blood boil on them

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=50842/blood-boil

**Comment by Trekex** [comment]
Fixed last update
