### ISSUE TITLE
Cannot create gnome hunters

### ISSUE THREAD

**Issue by Riskweaver** [Valhalla-Gaming/Tracker#6401]
**Describe the issue you're having**:
Receive an error message when attempting to create a gnome hunter
**Explain how you expect it work**:
Gnomes can be hunters in legion
**Steps to reproduce the problem**:

1. Choose gnome race, then hunter class.
2. Input name then click "finish"
3. 
![wowscrnshot_090816_160938](https://cloud.githubusercontent.com/assets/22084797/18365065/17f87b14-75df-11e6-90fd-a8030733c633.jpg)

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/class=3/hunter#races

**Comment by Traveler-Valhalla** [comment]
#5948
