### ISSUE TITLE
Blood DK Blood Tap

### ISSUE THREAD

**Issue by benedickt** [Valhalla-Gaming/Tracker#6403]
**Describe the issue you're having**:
talent does not work
**Explain how you expect it work**:
Blood Tap should restore 1 rune with each charge.
**Steps to reproduce the problem**:

1. make blood dk
2. hit 58 & select blood tap talent
3. use some runes then cast blood tap

**Links to Wowhead, YouTube, etc**:

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #5979
