### ISSUE TITLE
Falara Nightsong bugged

### ISSUE THREAD

**Issue by Anomander-Irake** [Valhalla-Gaming/Tracker#6410]
**Describe the issue you're having**:
Cannot interact with the NPC to repair my gear
**Explain how you expect it work**:
Be able to interact with NPC
**Steps to reproduce the problem**:

1. Make a Demon Hunter
2.  Go talk to Falara Nightsong

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/npc=97618/falara-nightsong

**Comment by Braemen** [comment]
#6034

**Comment by Trekex** [comment]
As commented by Braemen, this issue is already opened.
