### ISSUE TITLE
[Quest] - Spirits of Stonemaul Hold - Dustwallow Marsh 

### ISSUE THREAD

**Issue by Kaludarr** [Valhalla-Gaming/Tracker#6414]
**Describe the issue you're having**:
Interacting with 'Ogre Remains' doesnt count towards quest completition.
**Explain how you expect it work**:
Each 'Ogre Remains' interacted with adds 1/10 spirits laid to rest to quest counter.
**Steps to reproduce the problem**:
1. Complete quests 'The Essence of Enmity' and 'Banner of the Stonemaul';
2. Take the quest 'Spirits of Stonemaul Hold' from 'Brogg';
3. Interact with 'Ogre Remains'.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=27410/spirits-of-stonemaul-hold

**Comment by nuhrii** [comment]
ref #1223 and #356

**Comment by Moustachos** [comment]
Ref #5979
