### ISSUE TITLE
SERVİCE BUGS

### ISSUE THREAD

**Issue by Furyr** [Valhalla-Gaming/Tracker#6416]
**Describe the issue you're having**:
I BUY 90 LEVEL BOOST BUT DONT SEND ME MOUNT 
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. SEND ME MOUNT AND ARMOR AND WEAPON
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by GM-Pyromanic** [comment]
Duplicate report #6283
