### ISSUE TITLE
(PALADIN) Veredict's Templar Issue

### ISSUE THREAD

**Issue by hayberx** [Valhalla-Gaming/Tracker#6419]
**Describe the issue you're having**:
The ability does no damage
**Explain how you expect it work**:
Templar's Verdict is one of the most important skills of the rotation in the early levels of the paladin and does not work , so it is a serious problem
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
duplicate https://github.com/Valhalla-Gaming/Tracker/issues/6007
