### ISSUE TITLE
Fire mage Hot streak/ heating up

### ISSUE THREAD

**Issue by nicktothenock** [Valhalla-Gaming/Tracker#6420]
**Describe the issue you're having**:
every crit i get, i dont get heating up for fire mage, also hot streak never activates, and also flame on doesnt work nor does pyromaniac on the talent tree.
**Explain how you expect it work**:
doing what the ability says
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by nuhrii** [comment]
#1878

**Comment by Moustachos** [comment]
Ref #5979
