### ISSUE TITLE
Frostbolt. 

### ISSUE THREAD

**Issue by Zaid1972x** [Valhalla-Gaming/Tracker#6423]
**Describe the issue you're having**:
Frostbolt doesn't give slow de buff
**Explain how you expect it work**:
The frostbolt must give de buff to slow the target but it doesn't work.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Braemen** [comment]
#6147

**Comment by Moustachos** [comment]
Ref #5979
