### ISSUE TITLE
Hunter: Call Pet and Stables

### ISSUE THREAD

**Issue by llamalama** [Valhalla-Gaming/Tracker#6424]
If you have less than the max amount of pets in your Call Pet roster, the pet in the first slot will take up 2 slots. Trying to summon the one in the 2nd slot will still only summon the one in the first slot.

Going to a stable master will immediately take any pet you have in your stable and add it to your pets you carry around with you. Trying to rearrange the pets in the order you want does not work correctly and it will not let you leave a slot open in your carry around group.

Having 5 pets with you, the 1st pet will work fine, but the 2nd - 4th will be over one slot, so the 2nd one will be summoned by using Call Pet 3, etc. This is making the pet in slot 5 not able to be summoned at all.

Going to a stable master while having 5 pets will cause the first one to take up 2 slots and the pet that was in 5th place will be auto placed into the stable, fixing the "one over call pet" bug but still having the multi-slot bug.

The "one over call pet" bug still seems to appear sometimes when you only have 4 pets and the first pet is taking up 2 slots, though it is a bit different. All pets except the pet in slot one are summoned  by the slot ahead of them, so the pet in slot 3 would be summed by using Call Pet 2.

These bugs are making it impossible to tame new pets without abandoning old ones, making it so you can only use 4 pets instead of 5, and making summoning pets confusing.

http://www.wowhead.com/spell=883/call-pet-1
http://www.wowhead.com/spell=83242/call-pet-2
http://www.wowhead.com/spell=83243/call-pet-3
http://www.wowhead.com/spell=83244/call-pet-4
http://www.wowhead.com/spell=83245/call-pet-5

**Comment by Moustachos** [comment]
Ref #5979

**Comment by nuhrii** [comment]
This is still occuring

**Comment by nuhrii** [comment]
You can close this now its working
