### ISSUE TITLE
Aimed shot 

### ISSUE THREAD

**Issue by Redrian-Valhalla** [Valhalla-Gaming/Tracker#6425]
**Describe the issue you're having**:
Aimed shot does very low damage since it doesn't scale properly
**Explain how you expect it work**:
Aimed shot should deal consistent damage, not less than Arcane Shot as it does now.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Moustachos** [comment]
Arcane Shot deals arcane damage while Aimed Shot deals physical damage. That's why Aimed Shot has lower damage on targets, because of armor reduction.

Maybe armor reduction formula needs to be updated for Legion, but Aimed Shot damage are fine.

**Comment by Moustachos** [comment]
Ref #5979
