### ISSUE TITLE
Rouge Stealth and Dungeon Not Working

### ISSUE THREAD

**Issue by Lovor1** [Valhalla-Gaming/Tracker#6432]
I'm blood elf rouge and I can't go in stealth,when i use power it just stays same. Second problem is dungeons,when i click on the logo of dungeons it says it's loading but it isn't and i can't play dungeons. 

Please repair it.

![screenshot_9](https://cloud.githubusercontent.com/assets/22095527/18381925/ee76d8c6-767e-11e6-9b5b-d0771d274518.jpg)
![screenshot_10](https://cloud.githubusercontent.com/assets/22095527/18381926/ee815f9e-767e-11e6-88fc-f7e79b317d20.jpg)

**Comment by Trekex** [comment]
Stealth https://github.com/Valhalla-Gaming/Tracker/issues/5966
Dungeon https://github.com/Valhalla-Gaming/Tracker/issues/6012

**Comment by Moustachos** [comment]
Dungeon Finder will be fixed on next update.
