### ISSUE TITLE
hot streak

### ISSUE THREAD

**Issue by avaksx** [Valhalla-Gaming/Tracker#6436]
**Describe the issue you're having**:hot streak doesnt work

**Explain how you expect it work**:after two criticals needs to be instant pyroblast

**Steps to reproduce the problem**: 
1.  Create a mage
2.  Go fire spec
3. See whats the problem and fix it

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=195283/hot-streak

**Comment by nuhrii** [comment]
ref #1878

**Comment by Moustachos** [comment]
Ref #5979

**Comment by LordYawgmoth** [comment]
still broken
