### ISSUE TITLE
Ashes to Ashes

### ISSUE THREAD

**Issue by ismar1994** [Valhalla-Gaming/Tracker#6443]
**Describe the issue you're having**:
Ashes to Ashes quest in Western Plaguelands does not work, the Deathguard War-Captain 0/3 do not exist on the map.
**Explain how you expect it work**:
The Deathguard War-Captains should exist on the map.
**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by nuhrii** [comment]
#4294
