### ISSUE TITLE
Death Knight "Death Strike" not healing as intended 

### ISSUE THREAD

**Issue by real900** [Valhalla-Gaming/Tracker#6445]
When using "Death Strike" from the Death Knight class it doesn't heal as intended.

When you use "Death Strike" it should heal you for 20% of all the damage taken in the last 5 seconds.

All you need to reproduce the problem is to get a Death Knight and use your "Death Strike"and see it doesnt heal you.

#2266

**Comment by nuhrii** [comment]
dupl #6242
