### ISSUE TITLE
Repair NPC doesn't work in Mardum

### ISSUE THREAD

**Issue by rho1986** [Valhalla-Gaming/Tracker#6447]
**Describe the issue you're having**:
We normally can talk to the NPC named Falara Nightsong to buy/sell some reagents and to repair gear. She doesn't work. That make repairing and continuing quests in Mardum impossible.

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. No interaction between player and the NPC. So no repair.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/npc=97618/falara-nightsong

**Comment by rho1986** [comment]
There will be no need to bother anyone even GM to repair.

**Comment by Braemen** [comment]
#6034

**Comment by Trekex** [comment]
As commented by Braemen, this issue is already opened.
