### ISSUE TITLE
Blade dance missing (demon hunter)

### ISSUE THREAD

**Issue by gaven90** [Valhalla-Gaming/Tracker#6450]
**Describe the issue you're having**:
the spell is missing
**Explain how you expect it work**:
should strike multiple enemies
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=188499/blade-dance

**Comment by nuhrii** [comment]
ref #6253

**Comment by Moustachos** [comment]
Ref #5979
