### ISSUE TITLE
Legion/Archaeology: cannot create artifacts

### ISSUE THREAD

**Issue by Nethralen** [Valhalla-Gaming/Tracker#6455]
I cannot create artifact, despite having enough fragments. The error message says :"You have not provided enough items to cast this spell"

![wowscrnshot_090816_224824](https://cloud.githubusercontent.com/assets/22058183/18394935/9937443e-76bc-11e6-955f-a75653ee4732.jpg)

**Comment by Rigloss** [comment]
If you can fix this thing it would be awesome as it would give us something to do while waiting for other updates. Thanks.
