### ISSUE TITLE
Demon Hunter-Glide is not working properly

### ISSUE THREAD

**Issue by WINICK** [Valhalla-Gaming/Tracker#6457]
When i use glide i dont get speed boost and i cant control it.

**Explain how you expect it work**:
Whenever you use Glide you will get small speed bsmalland you should be able to control wherebto go like abflying mount.
**Steps to reproduce the problem**:

1. Try to copy the files for Glide from retail version.

http://www.wowhead.com/spell=131347/glide ;

**Comment by Aveta** [comment]
Copying won't do anything because scripts have to be done on server. Otherwise all servers would work just like retail : P

**Comment by Seregruth** [comment]
Already reported.
#5940
