### ISSUE TITLE
Zen Pilgrimage

### ISSUE THREAD

**Issue by Nightcap** [Valhalla-Gaming/Tracker#6458]
**Describe the issue you're having**: Zen Pilgrimage doesn't return you to where you came from after use.

**Explain how you expect it work**:It should return you

**Steps to reproduce the problem**: Use it and try using it to return

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Moustachos** [comment]
It works properly, but you mustn't logout while you're in Temple of Five Dawns (or Peak or Serenity), otherwise it won't return you to your departure point.

**Comment by Moustachos** [comment]
Ref #5979
