### ISSUE TITLE
First worgen quest bug

### ISSUE THREAD

**Issue by Sebastianus06** [Valhalla-Gaming/Tracker#6461]
**Describe the issue you're having**:
I have just made a worgen and me, and several others can not finish the second quest. The npc (Prince Liam Greymane) only shows the "goodbye" option, and does not see the quest as completed.
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. take the quest
2. Try to finish it
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Seregruth** [comment]
#21 #3632 #4568
