### ISSUE TITLE
Death strike

### ISSUE THREAD

**Issue by Kreten7** [Valhalla-Gaming/Tracker#6465]
**Describe the issue you're having**:When i use spell it does dmg,but there is no heal part of spell.
Also passive in frost and unholy spec named Daark Succor no work,killing enemy wiith exp or honor,give free Death Strike with 100% bonus heal.

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. Cast spell Death Strike and you will see there is no heal part od spell.
2. Kill enemy with exp or honor give no free Death strike
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by nuhrii** [comment]
dupl #6242

**Comment by Moustachos** [comment]
Ref #5979
