### ISSUE TITLE
Not Just Any Body

### ISSUE THREAD

**Issue by GeneralCaveman** [Valhalla-Gaming/Tracker#647]
http://www.wowhead.com/quest=26161/not-just-any-body

When opening the chest that is supposed to contain 'Loramus' Head', the first time I opened the chest I received nothing. The second time I opened it, I received both the head and the legs.  The third time I just received the head.

Edit: it seems that the chest that is supposed to contain the Torso is unable to be interacted with.

**Comment by Tregeta** [comment]
currently working
