### ISSUE TITLE
Death Knight Spell: Wraith Walk

### ISSUE THREAD

**Issue by llamalama** [Valhalla-Gaming/Tracker#6480]
http://www.wowhead.com/spell=212552/wraith-walk

This spell has 45 second cooldown, but even though it shows it being useable, it still isn't useable until 60 seconds has gone by.

**Comment by Moustachos** [comment]
Can't confirm this issue, can you tell me which specialization / talents you're using?

**Comment by llamalama** [comment]
Frost spec:
http://www.wowhead.com/spell=194878/icy-talons
http://www.wowhead.com/spell=207060/freezing-fog
http://www.wowhead.com/spell=207126/icecap
http://www.wowhead.com/spell=207167/blinding-sleet
http://www.wowhead.com/spell=207188/volatile-shielding
http://www.wowhead.com/spell=207230/frostscythe
http://www.wowhead.com/spell=152279/breath-of-sindragosa

**Comment by Nienz** [comment]
im unholy spec and can confirm the cd is longer then it should, 15 seconds longer cooldown

**Comment by theprototyze** [comment]
This is not an issue in 7.1.5 anymore

**Comment by llamalama** [comment]
Can confirm it is no longer a problem.

**Comment by Moustachos** [comment]
Ref #5979
