### ISSUE TITLE
[Mage] Mastery: Savant (Arcane)

### ISSUE THREAD

**Issue by Aveta** [Valhalla-Gaming/Tracker#6482]
**Describe the issue you're having**: Currently Arcane Mage Mastery shows a 0% bonus to both maximum mana/mana regen increase and Arcane Charge damage increase.
**Explain how you expect it work**: Arcane Mastery should increase your mana regeneration, maximum mana and Arcane Charge damage bonus

**Steps to reproduce the problem**:

1. Make a mage
2. Get it to lvl 78 to unlock mastery
3. Check the character sheet, specifically mastery percentages.

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=190740/mastery-savant

**Comment by Moustachos** [comment]
Note: Arcane Charge damage bonus part works, mana regeneration rate & maximum mana don't work.

**Comment by Moustachos** [comment]
Ref #5979
