### ISSUE TITLE
[Priest][Spell] Power Word: Shield

### ISSUE THREAD

**Issue by Baitmaster** [Valhalla-Gaming/Tracker#6487]
**Describe the issue you're having**:
Power Word: Shield doesn't absorb damage, instead it blocks damage.
EDIT: Apparently it only "blocks" for ranged damages and spells, enemies melees are **absorbed** correctly.
**Explain how you expect it work**:
PW:S Should Absorb damage instead of blocking it, it's explicit on tooltip.
**Steps to reproduce the problem**:
1. Cast Power Word: Shield
2. Get hit by a ranged spell
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=17/power-word-shield

**Comment by Moustachos** [comment]
This is just a visual bug, absorbed damage are displayed as blocked, but this isn't specific to PW: S.

**Comment by Moustachos** [comment]
Ref #5979
