### ISSUE TITLE
Warlock talent: Roaring blaze

### ISSUE THREAD

**Issue by cesium136** [Valhalla-Gaming/Tracker#6488]
**Describe the issue you're having**: roaring blaze is not working period

**Explain how you expect it work**: what is it suppose to do is increase the reaming immolate damage on the target when cast conflagrate.

**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:http://www.wowhead.com/spell=205184/roaring-blaze

**Comment by nuhrii** [comment]
duplitcate of #6306

**Comment by Moustachos** [comment]
Ref #5979
