### ISSUE TITLE
Warlock: cataclysm

### ISSUE THREAD

**Issue by cesium136** [Valhalla-Gaming/Tracker#6489]
**Describe the issue you're having**: the talented spell cataclysm is not applying immolate to targets it hits
**Explain how you expect it work**:
catatclysm is suppose to apply immolate to all targets hit
**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=152108/cataclysm

**Comment by nuhrii** [comment]
close this, duplicate of  #5625

**Comment by Moustachos** [comment]
Ref #5979
