### ISSUE TITLE
Warlock talent: mana tap

### ISSUE THREAD

**Issue by cesium136** [Valhalla-Gaming/Tracker#6490]
**Describe the issue you're having**:
mana tap is not consuming any mana
**Explain how you expect it work**:
mana tap is suppose to comsume 25% of your current mana to give you a buff for 20s that increases damage by 10%
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=196104/mana-tap

**Comment by nuhrii** [comment]
close this its a duplicate of #6302

**Comment by Moustachos** [comment]
Ref #5979
