### ISSUE TITLE
Warlock talent: burning rush

### ISSUE THREAD

**Issue by cesium136** [Valhalla-Gaming/Tracker#6492]
**Describe the issue you're having**: after activating burning rush the spell can not be canceled unleash you mount up or change instances.

**Explain how you expect it work**:after activating burning rush the skill should change to a cancel button to turn off burning rush.

**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=111400/burning-rush

**Comment by nuhrii** [comment]
duplicate of #1060

**Comment by llamalama** [comment]
This spell should also auto cancel if you don't have enough hp but it is instead killing you.

**Comment by Moustachos** [comment]
Ref #5979
