### ISSUE TITLE
Warlock infernal pet

### ISSUE THREAD

**Issue by cesium136** [Valhalla-Gaming/Tracker#6495]
**Describe the issue you're having**:the health of the infernal is not scaled correctly. the model has not been update to the new legion model. when the infernal is summoned it replaces the current pet

**Explain how you expect it work**:
the model needs updating the health needs to be fixed and when summoned it is not suppose to replace the current pet
**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=1122/summon-infernal

**Comment by nuhrii** [comment]
This one is a secondary effect of some other bugs so it will go away when the fix pets for warlocks

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #5979
