### ISSUE TITLE
warlock summon doomgurad

### ISSUE THREAD

**Issue by cesium136** [Valhalla-Gaming/Tracker#6497]
**Describe the issue you're having**:
the doomguard is not casting shadow bolt
**Explain how you expect it work**:
when summoned the doomguard is to attack your target with shadowbotls
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=18540/summon-doomguard

**Comment by EldritchIHC** [comment]
Shouldn't the doomgurd be a lot bigger than it is now?

**Comment by nuhrii** [comment]
dupl #6300 or #6298
