### ISSUE TITLE
Warlock: havoc

### ISSUE THREAD

**Issue by cesium136** [Valhalla-Gaming/Tracker#6498]
**Describe the issue you're having**:
havoc is not causing all single target spells to also hit the target marked with havoc
**Explain how you expect it work**:
suppose to apply a debuff to target  that causes all single target spells, regardless of who the new target is, to also hit the targets with havoc on them 
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=80240/havoc

**Comment by nuhrii** [comment]
duplitcate of  #4109

**Comment by Moustachos** [comment]
Ref #5979
