### ISSUE TITLE
warlock: rain of fire

### ISSUE THREAD

**Issue by cesium136** [Valhalla-Gaming/Tracker#6499]
**Describe the issue you're having**: rain of fire is not doing any damage

**Explain how you expect it work**:rain of fire is suppose to to an amount of damage to each target in the targeted area over a period of time

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=5740/rain-of-fire

**Comment by nuhrii** [comment]
duplicate of #2573

**Comment by Moustachos** [comment]
Ref #5979
