### ISSUE TITLE
warlock: soulwell

### ISSUE THREAD

**Issue by cesium136** [Valhalla-Gaming/Tracker#6500]
**Describe the issue you're having**:the soulwell does not give healthstone

**Explain how you expect it work**:party and raid members should be able to click the soulwell and be given a healthstone

**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=29893/create-soulwell

**Comment by nuhrii** [comment]
duplicate of #4872

**Comment by llamalama** [comment]
Still not fixed, please reopen issue.

**Comment by Moustachos** [comment]
Ref #5979
