### ISSUE TITLE
Wake of Ashes, Paladin

### ISSUE THREAD

**Issue by Redrian-Hellscream** [Valhalla-Gaming/Tracker#6502]
**Describe the issue you're having**:
Wake of Ashes deals exaggerate damage against players and is totally gamebreaking.
**Explain how you expect it work**:
It should deal 650% of Attack power, not 800k per hit.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Moustachos** [comment]
Will be fixed on next update.

**Comment by Moustachos** [comment]
Ref #5979
