### ISSUE TITLE
RESET TALENTS PLS

### ISSUE THREAD

**Issue by Furyr** [Valhalla-Gaming/Tracker#6509]
**Describe the issue you're having**:
![wowscrnshot_091116_002054](https://cloud.githubusercontent.com/assets/22060103/18413627/bbe6f11a-77b5-11e6-8e03-ac9d2057b1ae.jpg)

**Explain how you expect it work**:
MY DEMON BİTE İS PASİFE 
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by nuhrii** [comment]
You can only change talents in a rested area this isn't a bug and there are no rested areas on mardum
