### ISSUE TITLE
DH class hall vendor

### ISSUE THREAD

**Issue by Stonfa** [Valhalla-Gaming/Tracker#6517]
**Describe the issue you're having**:
Erm DH class vendor is bugged and its kinda anoying 
**Explain how you expect it work**:
Well to work actually
**Steps to reproduce the problem**:

1. Speak with Falara nightsong
2. Does nothing.
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/npc=97618/falara-nightsong#objective-of

**Comment by Redrian-Hellscream** [comment]
Anything?

We can't even buy gear because of that.
