### ISSUE TITLE
Rogues Not working Stealth

### ISSUE THREAD

**Issue by Eusoj0** [Valhalla-Gaming/Tracker#6523]
At level 5 you get stealth one of the most importants abilities of the rogue and its not working

**I press the abilitie and nothing happens it says im stealthed but is not true**:

**Steps to reproduce the problem**:

1. Go to rogue class
2. Level up to 5
3. Press stealth

**Links to Wowhead, YouTube, etc**:

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/5966
