### ISSUE TITLE
[SPELL] [STEADY SHOT] [HUNTER]

### ISSUE THREAD

**Issue by NaughtyDecent** [Valhalla-Gaming/Tracker#6526]
**Describe the issue you're having**:
Steady shot Spell of hunter isn't there in spell book.
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Nicoray360** [comment]
Hunters no longer have steady shot in legion: read class changes before posting here

**Comment by Redrian-Hellscream** [comment]
Seriously, this is not wod, stop making invalid reports.

**Comment by burtle123** [comment]
well the quest to practice steady shot is still around and uncompleteable

**Comment by Redrian-Hellscream** [comment]
The quest has to be removed.

**Comment by burtle123** [comment]
yeah just meant that that would be the issue rather then the skill

**Comment by GM-Pyromanic** [comment]
Invalid report 
![firefox_2016-09-13_02-46-01](https://cloud.githubusercontent.com/assets/20587569/18458813/5ec65fcc-795c-11e6-9f44-1ff3d5852be0.png)
