### ISSUE TITLE
[SPELL][AIMED SHOT] [HUNTER]

### ISSUE THREAD

**Issue by NaughtyDecent** [Valhalla-Gaming/Tracker#6528]
**Describe the issue you're having**:
Aimed shot spell of hunter do not work while moving. 
**Explain how you expect it work**:
Aimed shot works while moving thats what was in draenor.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Eusoj0** [comment]
Maybe in legion they dissabled it

**Comment by Nicoray360** [comment]
Aimed shot in legion does no longer work while moving and that's not an issue, it's supposed to be like this

**Comment by Redrian-Hellscream** [comment]
The spell works correctly regarding that, please close.
