### ISSUE TITLE
QUEST: Burn It Up... For The Horde

### ISSUE THREAD

**Issue by arhcangeljovan** [Valhalla-Gaming/Tracker#6536]
**Describe the issue you're having**: You can burn out the cannon's at all. 

**Explain how you expect it work**: When you get closer to the cannon you should be able to cast the flaming torch and burn them. 

**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Cidragon** [comment]
It's working now.
