### ISSUE TITLE
Demon Hunter: Glide

### ISSUE THREAD

**Issue by Raizo575** [Valhalla-Gaming/Tracker#6539]
**Describe the issue you're having**:
When I use Glide during a fall, it does not let me change the direction of my character mid-air, the character will just keep gliding in the initial direction Glide was used on.
**Explain how you expect it work**:
I expect to steer left and right when I glide through the air, choosing where to land just like it works in retail.
**Steps to reproduce the problem**:

1. Play Demon Hunter
2. Jump from any height.
3. Use Glide.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=131347/glide   /    https://youtu.be/45z5QnWB5ik

**Comment by Raizo575** [comment]
Additionally, activating glide in retail seems to give a slight boost to speed whereas it does not in valhalla currently. Here's the video that proves it:
https://youtu.be/Tlg9SLMM5aI

**Comment by Seregruth** [comment]
Already reported.
#5940
