### ISSUE TITLE
Shield of The Righteous - Paladin Protection Spell

### ISSUE THREAD

**Issue by MichRattay** [Valhalla-Gaming/Tracker#6544]
**Got to level 24 and didn't learn the spell**:

**On reaching level 24 player should learn spell Shield of the Righteous (deals 400% of wep dmg as holy dmg and reduces dmg taken by player by 25% for 4 sec) along with appearing on action bar**:

**Steps to reproduce the problem**:

1. Level up a paladin to lvl 10
2. Change spec to protection
3.  level up to 24

**Links to Wowhead, YouTube, etc**: 
http://www.wowhead.com/spell=53600/shield-of-the-righteous

**Comment by Moustachos** [comment]
Works just fine on current version.

**Comment by Moustachos** [comment]
Ref #5979
