### ISSUE TITLE
(Brewmaster) Stagger

### ISSUE THREAD

**Issue by Nightcap** [Valhalla-Gaming/Tracker#6547]
**Describe the issue you're having**: Stagger gets you one shotted by anything, can't tank as monk because of this.

**Explain how you expect it work**: Stagger the amount of damage takin over time

**Steps to reproduce the problem**: play a brewmaster and get hit

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Hemoglobine-Valhalla** [comment]
http://www.wowhead.com/spell=124255/stagger#changelog

**Comment by Traveler-Valhalla** [comment]
#6167

**Comment by Moustachos** [comment]
Ref #5979
