### ISSUE TITLE
(Monk) Spell

### ISSUE THREAD

**Issue by Nightcap** [Valhalla-Gaming/Tracker#6548]
**Describe the issue you're having**: Spell : Earth,Wind and Fire Does nothing when used

**Explain how you expect it work**: It should summon copies of yourself that fight at your side.

**Steps to reproduce the problem**: Use it

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Guybrush-VR** [comment]
Do you mean this one : http://www.wowhead.com/spell=137639/storm-earth-and-fire ?

**Comment by Nightcap** [comment]
Thats the one

**Comment by Moustachos** [comment]
Ref #5979
