### ISSUE TITLE
DK [Artisan Riding] skill bug - Stop work after reconnect

### ISSUE THREAD

**Issue by KaelM** [Valhalla-Gaming/Tracker#6551]
**Describe the issue you're having**:
I've bought "Perito em Montaria"(Astisan Riding) to flight in outlands, after one serverdown my skill still in "Perito"(Astisan) but i can't flight in outlands anymore and the trainer still trying to sell me the same skill i already have... I've spent 200 gold and can't spent this again or i will never be able to learn how to fly in northrend.
**Explain how you expect it work**:
I expect to train once one time...

*Image attached.
![artisanerror](https://cloud.githubusercontent.com/assets/22139641/18423853/53f33a9e-787f-11e6-84f9-e86d27bf643d.png)

**Sorry for my bad english, i'm Brazillian.

**Comment by Kreten7** [comment]
I can confirm that bugg too.This ID fly license bugg is only on DK class.On all other class it work fine.

**Comment by KaelM** [comment]
My brother have the same problem with his DK...

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6830
