### ISSUE TITLE
mage spell

### ISSUE THREAD

**Issue by poxol25** [Valhalla-Gaming/Tracker#6553]
**Describe the issue you're having**:
the spell dont do damage
**Explain how you expect it work**:
Ice Lance
40 yd  range
1.0% of base mana
Instant cast
Deals x Frost damage to an enemy target.

Ice Lance damage is doubled against frozen targets.

**Steps to reproduce the problem**:

1. i lucnh the spell
2. the spell donts do damage
3. 

**Links to Wowhead, YouTube, etc**:
http://wowwiki.wikia.com/wiki/Ice_Lance

**Comment by nuhrii** [comment]
duplicate #6014

**Comment by GM-Pyromanic** [comment]
Duplicate report.

**Comment by Moustachos** [comment]
Ref #5979
