### ISSUE TITLE
DH Starting area item repair.

### ISSUE THREAD

**Issue by sevike777** [Valhalla-Gaming/Tracker#6556]
**Describe the issue you're having**:
I cant repair my items on the DH starting area(Vault of the Wardens & Marduum). If I cant repair my weapons I cant kill the mobs so Im stuck in the starting area. I begging to the GM two days ago to fix this bug but all GMs are ignoring me. They said they have bigger problems.
**Explain how you expect it work**:
http://www.wowhead.com/search?q=falara+nightsong     These npcs have to repair the items.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by nuhrii** [comment]
ref #6034

**Comment by Guybrush-VR** [comment]
Fixed in next update! :palm_tree:
