### ISSUE TITLE
Problem with "The Imp Mother's Tome" DH quest (stuck in this)

### ISSUE THREAD

**Issue by KaelM** [Valhalla-Gaming/Tracker#6561]
**Describe the issue you're having**:
I'm in "The Imp Mother's Tome" and there no Demon Hunter NPCs to help me to kill her, she's damage is too high for me to fight alone and i die every time i try to kill her.

**Explain how you expect it work**:
I seen a video that some demon hunters are fighting with her and i only need to join them, i don't know if its the right way but fight with her alone seems to be impossible.

**Steps to reproduce the problem**:
1. Just accept the quest in 102lv demon hunter.

**Links to Wowhead, YouTube, etc**:
http://wowwiki.wikia.com/wiki/Quest:The_Imp_Mother%27s_Tome

**Comment by GM-Pyromanic** [comment]
This is how the fight is on retail.

"This fight can be tough, as it is movement-oriented. Prolifica will summon
forth not only imps for players to deal with, but also area of effect
damage over time pools. Keep moving and killing the imps, using their souls
to heal. Between summons, keep hitting her."

**Comment by nuhrii** [comment]
you can also interrupt her spell casts too you know

**Comment by KaelM** [comment]
Thanks, i've started another DM with my brother to play together, i remember that imps can't be targeted, but i will tri again.
