### ISSUE TITLE
Paladin - Talent - Greater Justice

### ISSUE THREAD

**Issue by MichRattay** [Valhalla-Gaming/Tracker#6562]
**Describe the issue you're having**: Talent doesn't influence the skill "Judgment'

**Explain how you expect it work**: Greater Justice should make Judgment always crit when enemy has more than 50% health. Also base number of targets hit should increase from base 2 targets to 3 targets

**Steps to reproduce the problem**:

1.  Take Greater Justice talent
2.  use judgment on a target surrounded by two other enemies 
3.  observe results

**Links to Wowhead, YouTube, etc**:http://www.wowhead.com/spell=20271/judgment

**Comment by midodragon** [comment]
this talent doesn't work at all

**Comment by Moustachos** [comment]
Ref #5979
