### ISSUE TITLE
Unholy DK not working

### ISSUE THREAD

**Issue by mateokun123** [Valhalla-Gaming/Tracker#6565]
**Describe the issue you're having**:
The whole Unholy DK spec is bugged, my character just swirls around when performing festering strike dealing no damage and the aoe basic curse (cant recall the name as im a wotlk player) when performed says :you're facing the wrong way: which is completely incorrect as im standing in front of the monster
**Explain how you expect it work**:
I expect it to deal damage!
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Trekex** [comment]
Festering Strike fixed last update
