### ISSUE TITLE
Dungeons and Rouge's Stealth

### ISSUE THREAD

**Issue by Lovor1** [Valhalla-Gaming/Tracker#6566]
Please fix Dungeons ASAP, and rouge stealth needs to be fixed cuz rouge without stealth isn't rouge :)

**Comment by Redrian-Hellscream** [comment]
You can't pretend them to fix dungeons like that, and rogue's stealth has been reported numerous times already, please close.

**Comment by GM-Pyromanic** [comment]
Duplicate reports.
