### ISSUE TITLE
Ferocious Bite Combo Points

### ISSUE THREAD

**Issue by HDkiller45** [Valhalla-Gaming/Tracker#6570]
**Describe the issue you're having**:
Ferocious Bite loses 1 combo points everytime you use it, even tho you have a full combo points, it will keep loosing 1 combo points if you use it
**Explain how you expect it work**:
When you have 1 or more combo points, you will lose all that combo points depending how much you have.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=22568/ferocious-bite

**Comment by CageValhalla** [comment]
It has been reported. Use search option before posting multiple reports
[https://github.com/Valhalla-Gaming/Tracker/issues/6010](url)

**Comment by Moustachos** [comment]
Fixed in a previous update.
