### ISSUE TITLE
Word of Glory, Paladin

### ISSUE THREAD

**Issue by Redrian-Valhalla** [Valhalla-Gaming/Tracker#6573]
**Describe the issue you're having**:
World of Glory makes the player immune to any damage.
**Explain how you expect it work**:
World of Glory should simply heal the player up to 5 nearby friendly targets.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Moustachos** [comment]
There are few issues with Word of Glory that will be fixed soon, but it doesn't make player immune to any damage on current version.

**Comment by Moustachos** [comment]
Ref #5979
