### ISSUE TITLE
Hot Streak !!!

### ISSUE THREAD

**Issue by Mordreed** [Valhalla-Gaming/Tracker#6579]
**When the spell crit u didn`t have the passiv "Hot Streal" **:

**When 1 fire spell crit u should get that proc**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**http://www.wowhead.com/spell=195283/hot-streak**:

**Comment by nuhrii** [comment]
ref #1878
check the issue tracker before posting this is the 5th time its been reported
