### ISSUE TITLE
Warlock Talent: Fire and Brimstone

### ISSUE THREAD

**Issue by llamalama** [Valhalla-Gaming/Tracker#6581]
Fire and Brimstone always is active even if you picked one of the other 2 talents in the level 60 row.

http://www.wowhead.com/spell=196408/fire-and-brimstone
http://www.wowhead.com/spell=196412/eradication
http://www.wowhead.com/spell=196098/soul-harvest

**Comment by nuhrii** [comment]
ref #4549

**Comment by Moustachos** [comment]
Ref #5979
