### ISSUE TITLE
Death knight spells not working after talent spec change

### ISSUE THREAD

**Issue by Mejtrix** [Valhalla-Gaming/Tracker#6590]
**Describe the issue you're having**:
It seems like after changing talent spec, the spells are not working at all. You can only autoattack. Tried it on more DKs, the spells normally worked until I changed the talent spec to different one (e.g. frost to unholy).
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. try using spells on a mob/dummy
2. change talent specialization
3. try using spells on a mob/dummy

**Links to Wowhead, YouTube, etc**:

**Comment by Mejtrix** [comment]
Edit: sometimes few seconds works normally, then doesn't do anything again. Also on DK with no talent spec changed ever sometimes happens to ignore using spells, just autoattacking for few seconds.

**Comment by Guybrush-VR** [comment]
Does it work after relogging?

**Comment by Mejtrix** [comment]
After some more testing - relog seems to help blood and frost specs being usable, only unholy talent spec when activated it screws up all the other talent specs.

**Comment by Moustachos** [comment]
Ref #5979
