### ISSUE TITLE
Undead warrior charge not working

### ISSUE THREAD

**Issue by bogdan97** [Valhalla-Gaming/Tracker#6591]
**Describe the issue you're having**: Charge isn't working, when I activate the spell the character does nothing. I am an undead warrior

**Explain how you expect it work**: When I select the target and I am in the proper range, the warrior should run at it and then stun the target.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Mejtrix** [comment]
Charge not working for all warrior races, not only undead. Gives cooldown but doesn't react.

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/5961
