### ISSUE TITLE
Druid-Spell-Predatory Swiftness

### ISSUE THREAD

**Issue by Valkrin** [Valhalla-Gaming/Tracker#6593]
**Describe the issue you're having**:
Predatory Swiftness passive does not trigger after using combo points.
**Explain how you expect it work**:
Predatory Swiftness should give a free healing touch, Entangling Roots or a rebirth.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=16974/predatory-swiftness

**Comment by Traveler-Valhalla** [comment]
#6268

**Comment by Moustachos** [comment]
Ref #5979
