### ISSUE TITLE
Rogue Stealth

### ISSUE THREAD

**Issue by Sebastianus06** [Valhalla-Gaming/Tracker#6595]
**Describe the issue you're having**:
Well, simply, rogue's stealth is not working.
I've just made a dwarf rogue and it doesn't make me "invisible", monsters aggro me just like i dont have it, and even more, i can't use spells like "sap" which require stealth.
**Explain how you expect it work**:
like stealth works.
**Steps to reproduce the problem**:

1. make a rogue
2. use stealth
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Jefferythegod** [comment]
already reported
pls dont report something that is already reported

**Comment by Sebastianus06** [comment]
And is it going to ever be fixed? Rogues are unplayable without stealth.

**Comment by Jefferythegod** [comment]
be patient

**Comment by Jefferythegod** [comment]
they got a LOOOOOOOOOOOOOOOOOOT of stuff to fix

**Comment by Redrian-Hellscream** [comment]
When will people learn to search before posting? close please.

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/5966
