### ISSUE TITLE
Stuck in demon hunter starter zone

### ISSUE THREAD

**Issue by Cefalosporin** [Valhalla-Gaming/Tracker#6596]
Hello, I've used the hearthstone in order to find a npc to fix my weapons since i had to kill Bastillax from the beginner's chain quests, but unfortunatly, since I didn't knew, I'm now stuck in the beginners area (Mardum) without being able to find a way out. Character name is Cefalosporin

**Comment by Redrian-Hellscream** [comment]
This place is for bug reports, contact a GM for problems like this.
