### ISSUE TITLE
MY CHARACTER İS BUG

### ISSUE THREAD

**Issue by Furyr** [Valhalla-Gaming/Tracker#6599]
**Describe the issue you're having**:
![wowscrnshot_091316_224738](https://cloud.githubusercontent.com/assets/22060103/18489007/6ebaa232-7a04-11e6-9327-5c6e6a04ae37.jpg)

**Explain how you expect it work**:
HEY ANYBODY HELP ME PLSSS
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/search?q=THE+LESSON+OF+THE+İRON+BOUGH

**Comment by Jefferythegod** [comment]
problem fixed: 
dont play that stupid race

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/6032
