### ISSUE TITLE
Death Strike

### ISSUE THREAD

**Issue by Skyfallen156** [Valhalla-Gaming/Tracker#6605]
**Describe the issue you're having**:
Death Strike (http://www.wowhead.com/spell=49998/death-strike) not healing as intended.
**Explain how you expect it work**:
"heals you for 20% of all damage taken in the last 5 sec, minimum 10% of maximum health."

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/6242

**Comment by Moustachos** [comment]
Ref #5979
