### ISSUE TITLE
LAUNCHER CAPTCHA ERROR PLEASE

### ISSUE THREAD

**Issue by mndy125** [Valhalla-Gaming/Tracker#6607]
im having a problem with the launcher security captcha- i cant see it so i cant get in the game and i get a cac system error so please help 

**Explain how you expect it work**: to show the captcha on the screen so i could type it and enter the game

**Comment by GM-Pyromanic** [comment]
We do not have a Captcha system on our launcher as you can see from this image taken from my own valhalla launcher.
![valhalla launcher_2016-09-14_12-37-01](https://cloud.githubusercontent.com/assets/20587569/18510816/0ed687e0-7a78-11e6-9ac8-9a71d2126c86.png)
