### ISSUE TITLE
[Demon Hunter] Metamorphosis spell

### ISSUE THREAD

**Issue by riskcapcap** [Valhalla-Gaming/Tracker#6612]
**Describe the issue you're having**:
When I cast Metamorphosis somewhere not in my line of sight I don't get the cooldown, but the leap happens without transforming me into a demon.
**Explain how you expect it work**:
When you cast Metamorphosis somewhere not in line of sight, nothing should happen
**Steps to reproduce the problem**:
Use Metamorphosis somewhere you don't have line of sight of.
**Links to Wowhead, YouTube, etc**:
https://www.youtube.com/watch?v=0w1ukF3eWJM&feature=youtu.be

**Comment by Redrian-Hellscream** [comment]
The same happens if you use meta pointing it in the air(to force the range limit) and then cast it while running.

**Comment by Moustachos** [comment]
Ref #5979
