### ISSUE TITLE
Heirloom vendors: no buying possible

### ISSUE THREAD

**Issue by kjelt** [Valhalla-Gaming/Tracker#6613]
**Describe the issue you're having**:
Both heirloom vendors (Alliance/Horde) do have heirlooms but do not show any sell prices.

**Explain how you expect it work**:
With showing sell prices you are able to buy displayed items. (Without not)

**Steps to reproduce the problem**:
1. Got to the vendor in IF or UC
2. Open vendor interface

**Links to Wowhead, YouTube, etc**:
![screenshot_4](https://cloud.githubusercontent.com/assets/905480/18516011/b5889cd0-7a97-11e6-8be5-df1d44328d56.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/905480/18516014/bab0172e-7a97-11e6-9486-059812afffcd.png)

http://www.wowhead.com/npc=6294/krom-stoutarm
http://www.wowhead.com/npc=6566/estelle-gendry

**Comment by Redrian-Hellscream** [comment]
That's because they're supposed to cost marks of honor, which aren't implemented yet.

**Comment by kjelt** [comment]
ähm as i read it mark of honor items are item that you had bought with honor or other pvp currencies.
But that Heirlooms are buyable with normal gold described by wowhead.com 

Where do you take your information from? 
Marks of Honor are pvp related but above heirlooms are pve related things. Please add your information source.

**Comment by Redrian-Hellscream** [comment]
You obtain these Marks through loot boxes from both rated and unrated PvP.
You don't buy them.
The same bug affecting heirlooms(both pve and pvp ones) are also affecting old pvp tems.

I don't know what the devs did when upgrading the db to legion but I just gave a suggestion to what could have been the reason of their currency being broken.

My information source is me going around Azeroth and carefully checking wowhead's db, you could do that too.

**Comment by kjelt** [comment]
what do you say to both wowhead links - is that information wrong or right?

**Comment by kjelt** [comment]
what do you say to both wowhead links provided in first part - is that information wrong or right?

i think you thought of
http://www.wowhead.com/npc=52036/galra in OG
http://www.wowhead.com/npc=52030/liliana-emberfrost in SW

That are different vendors!

**Comment by Redrian-Hellscream** [comment]
I know they are, but the bug could be the same, anyway just wait for them to fix it since it's nothing complex.
