### ISSUE TITLE
Mardun(DH starting zone) Loot chests are borken

### ISSUE THREAD

**Issue by EldritchIHC** [Valhalla-Gaming/Tracker#6618]
I have found a lot of small grey chests in the Dh starting zone but when I open them they are empty.

I see a chest,I click it it gives me loot,simple.

**Steps to reproduce the problem**:
1. Find a grey small chest in the DH starting zone
2. Mouse over it and you will see a purple outline
3. Click on it
4. Wait for it to open
5. Observe that it is empty
6. Bang your keyboard with your head because it is the 10th time it happens
   7.shfgyegufgyenj
   ![image](https://cloud.githubusercontent.com/assets/20945698/18548236/6b090bfe-7b50-11e6-9bed-cf7c82bf2e3b.png)

**Comment by Diuesh** [comment]
I like the last step

**Comment by EldritchIHC** [comment]
My keyboard dosen't like it

**Comment by Diuesh** [comment]
Neither do mine

**Comment by Aival94** [comment]
Bump.

Please implemente loot. Some of the chests in DH have unique items while rest have max 2 kind of items.

**Comment by Guybrush-VR** [comment]
We have 22/25 chests spawned, I'll take care of it!

**Comment by Aival94** [comment]
Ty. Here have some of the chests with the Unique gear as well in the category Rares and Treasures: http://www.wowhead.com/guides/classes/demon-hunter/starting-quests

**Comment by Guybrush-VR** [comment]
Okay, I scripted them on local. The three chests you're looking for are spawned (the ones that contain [Mardum Lord Signet](http://www.wowhead.com/item=128946/mardum-lord-signet), [Inquisitor's Menacing Eye](http://www.wowhead.com/item=129192/inquisitors-menacing-eye) & [Vile Stalkerskin Pouch](http://www.wowhead.com/item=129195/vile-stalkerskin-pouch)). This fix should reach Midgard soon, depending on when we'll update!
