### ISSUE TITLE
Shadow priest Vampiric touch

### ISSUE THREAD

**Issue by Ghifrix** [Valhalla-Gaming/Tracker#6620]
**Describe the issue you're having**: it's not dealing any damage nor healing 

**Explain how you expect it work**: it should deal damage and heal 

**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by forstix** [comment]
reported https://github.com/Valhalla-Gaming/Tracker/issues/6275

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #5979
