### ISSUE TITLE
demon hunters wtf

### ISSUE THREAD

**Issue by nnjck** [Valhalla-Gaming/Tracker#6628]
The demon hunter starting zone needs some vendors to repair your armor.
When i started my demon hunter my armor and weapons broke at some point and i needed to create new demon hunter and so long.You can ad portals to stormwind and orgrimar or just some vendors.
At this point the demon hunters are almost unplayble and how other players make the quest line without 
their armor being broken.I lost 5 to 10 hours just making new demon hunters and trying to do the questline without breaking my armor. pls if your reading this tell me how to make it.

**Comment by Collector-Valhalla** [comment]
> pls if your reading this tell me how to make it.

get gut
