### ISSUE TITLE
[Balance Druid] - Fury of Elune

### ISSUE THREAD

**Issue by Maldazar** [Valhalla-Gaming/Tracker#6633]
**Describe the issue you're having**: Talent 'Fury of Elune' doesn't work at all.

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=202770/fury-of-elune

**Comment by Moustachos** [comment]
Ref #5979

**Comment by Moustachos** [comment]
Will be fixed on next update.

**Comment by Moustachos** [comment]
Ref #5979
