### ISSUE TITLE
[Balance Druid] - New/Half/Full Moon

### ISSUE THREAD

**Issue by Maldazar** [Valhalla-Gaming/Tracker#6635]
**Describe the issue you're having**: Artifact spell 'New Moon' is broken.

**Explain how you expect it work**: It should evolve from New to Half and from Half to Full moon but it is Half Moon all the time.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=202767/new-moon#comments

**Comment by Moustachos** [comment]
Will be fixed on next update.

**Comment by Moustachos** [comment]
Ref #5979
