### ISSUE TITLE
wod ability

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#6644]
I had a rogue in WoD with burst of speed talent. Now it is gone (at least for Outlaw) but I still have it in general abilities tab... and it works.

![wowscrnshot_091516_005546](https://cloud.githubusercontent.com/assets/14946340/18553471/d156e916-7b60-11e6-887c-3895c3b5ac3e.jpg)

**Comment by Traveler-Valhalla** [comment]
similar thing with feral druid
if you had claws of shrivallah talent in wod, your basic cat form in legion will have that appearance

**Comment by Traveler-Valhalla** [comment]
And for paladins 
final verdict talent is in general tab
![wowscrnshot_100616_213240](https://cloud.githubusercontent.com/assets/14946340/19532210/0eaae2c8-963b-11e6-9f8f-1a4b1bd1bd81.jpg)
selfless healer talent is proccing
![wowscrnshot_100616_213507](https://cloud.githubusercontent.com/assets/14946340/19532211/0ead7aec-963b-11e6-8d26-cd93a81361d1.jpg)

those talents/abilities were removed with legion i guess

**Comment by Traveler-Valhalla** [comment]
and dks from wod times have death pact ability
![wowscrnshot_100616_171116](https://cloud.githubusercontent.com/assets/14946340/19570336/cb136f0c-96f9-11e6-863d-19772dcbd7e5.jpg)

**Comment by Traveler-Valhalla** [comment]
#6210

**Comment by Moustachos** [comment]
Ref #5979
