### ISSUE TITLE
Demon hunter losing spells

### ISSUE THREAD

**Issue by gmk01** [Valhalla-Gaming/Tracker#6700]
-as a demon hunter losing all portal/teleport spells after logging out or getting disconnected (vale of eternal blossoms/warspear bought from a portal trainer) as well as any newly bound macros 

-expect the learnt/bound abilities to stay after logging out/experiencing disconnects

-reproduce by buying the aforementioned spells and logging out/getting disconnected (as a lvl 102 demon hunter specifically)

**Comment by Aveta** [comment]
Eh, a Demon Hunter is not supposed to learn Teleport/Portal spells. It's mage stuff.
