### ISSUE TITLE
Blackwing Descent Instance Issue

### ISSUE THREAD

**Issue by kombustion** [Valhalla-Gaming/Tracker#6702]
Hi Team,

The Game crashes as soon as I enter the Blackwing Descent Instance. I tried to go inside the instance with my DH and everytime the game crashed. Please check the screenshot below for reference.
![blackwing descent crash](https://cloud.githubusercontent.com/assets/21998215/18580198/b532b6ae-7c17-11e6-98ef-3ab295bac516.jpg)

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by GM-Pyromanic** [comment]
Duplicate Report #6047
