### ISSUE TITLE
BUG collection！

### ISSUE THREAD

**Issue by Clerics** [Valhalla-Gaming/Tracker#6707]
**Describe the issue you're having**:Professional hall can't received the task!   DK skills will not work!   The monk can't dual wield one-handed weapon!  Warrior heroic leap doesn't work!  A copy of the part cannot enter!

**Explain how you expect it work**:I hope they can work normally!

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Aveta** [comment]
Regarding monks: which spec are you in? Currently only Windwalkers can dual wield. Also, I noticed on retail that you need to manually drag your second weapon onto the offhand slot.

**Comment by Nightcap** [comment]
WW monk dual wield works fine.

**Comment by Clerics** [comment]
Sorry！I didn't notice, because is my trade union staff tell me ~ ~
