### ISSUE TITLE
Switching Specialization should also give access to artifact weapon for that specialization!

### ISSUE THREAD

**Issue by kombustion** [Valhalla-Gaming/Tracker#6710]
As in the game itself, we have artifact weapons for each specializations, now imagine if I need to switch to another specialization, which does works but gives no options to have the Artifact corresponding to that specialization then switching talents and specialization is a waste.

For example, if I am level 110 Marksman Hunter with my artifact weapon Thas'dorah Legacy of the Windrunner and wish to switch to Survival, I should also have access to the weapon for that specialization i.e. Talonclaw.

If switching specialization doesn't grants access to their respective Artifacts then it defeats the purpose.

So. either you should have ways to have access to them otherwise people will end up making 3 or atleast 2 characters each for each specialization (if they want to play all 3 or atleast 2)

http://us.battle.net/forums/en/wow/topic/20749005551
http://www.wowhead.com/guides/legion/artifact-weapons

**Comment by Moustachos** [comment]
On retail at first you're only able to choose an artifact for one specialization, so you have to choose wisely (hence the confirmation box when you're about to select the artifact).

Once you completed some quests (related to your Class Hall campaign), you can acquire the other ones. But switching to another specialization isn't supposed to automatically grant you the related artifact.

For now on Valhalla the questlines allowing you to get these artifacts aren't scripted and we decided to restrict the NPC allowing you to get them to one artifact per character.

It might change in the future, but for now we'll keep it that way.
