### ISSUE TITLE
warrior bug heroic leap

### ISSUE THREAD

**Issue by zintox** [Valhalla-Gaming/Tracker#6715]
**Describe the issue you're having**:
i cant use heroic leap
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. the spell does not work only show cd 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/5970

**Comment by Moustachos** [comment]
Ref #5979
