### ISSUE TITLE
paladin bug templar's verdict

### ISSUE THREAD

**Issue by zintox** [Valhalla-Gaming/Tracker#6716]
**Describe the issue you're having**:
templar's verdict 0 dmg
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. take the cost of 3 holy power but dont do dmg
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
duplicate https://github.com/Valhalla-Gaming/Tracker/issues/6007
