### ISSUE TITLE
Mage issues

### ISSUE THREAD

**Issue by nicktothenock** [Valhalla-Gaming/Tracker#6720]
**Describe the issue you're having**:
1. Frost mages Ice Lance still doesnt deal damage, 
2. Fire doesnt produce hot streak or gain the chance to get heating up when casting spells. Thus making Pyromanic in the talent tree for fire doesnt work.
3. Conjure Refreshment doesnt work.
4. Also cant get to mage class hall at level required.
5. Procs on most specs for mages really dont work, mostly fire.
6. Conflagration for fire mage doesnt work properly.
7. Cinderstorm doesnt do anything.
8. Displacement for arcane doesnt allow you to use it after you blink.
9. Crit strikes from spells on fire mage doesnt lower the cooldown of combustion when having the talent kindling.
10. Flame patch doesnt leave a damage area.
11. Flame on doesnt work properly.
12. Frostbolt doesnt apply the slow movement it should.
13. Frost spec pet is an earth elemental and should be a water.
 I may have not gotten all the issues that mages are having but these are the ones ive noticed.
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Braemen** [comment]
Every spell bug you've written is reported on the [Ultimate Legion Spell Tracker](https://github.com/Valhalla-Gaming/Tracker/issues/5979#Mage).

**Comment by GM-Pyromanic** [comment]
All spells listed have already been reported, Also please create separate reports for each one so that when a dev fixes a certain spell it can be closed.

**Comment by Moustachos** [comment]
Ref #5979
