### ISSUE TITLE
the art of a rogue

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#6722]
http://www.wowhead.com/quest=26207/the-arts-of-a-rogue
Doesn't work. 

![wowscrnshot_091716_001744](https://cloud.githubusercontent.com/assets/14946340/18604841/0510aab2-7c83-11e6-98ba-8f2bb82f725d.jpg)

**Comment by Aveta** [comment]
Those quests were removed with patch 7.0.3 so they shouldn't appear at all.

**Comment by Traveler-Valhalla** [comment]
same situation with http://www.wowhead.com/quest=26915/the-deepest-cut
