### ISSUE TITLE
[Legion] [Warlock] [Affliction] DRAIN SOUL: same problem as DRAIN LIFE

### ISSUE THREAD

**Issue by Usernameisntalreadytaken** [Valhalla-Gaming/Tracker#6739]
Drain soul deals abnormally low damage, just like drain life does.

How to reproduce it:
-get an afflock
-take the "drain soul talent"
-use it and look at how much damage you'll deal (usually less than 10 per tick)

Wowhead:
http://www.wowhead.com/spell=198590/drain-soul#changelog
might wanna take a closer look at that changelog to see actual values that were used for the spell.
I'm pretty sure the 6 damage that's listed is scaled for naked lv1 characters.

That's all.

**Comment by ATalisan** [comment]
Drain Soul does not work to grant a Soul Shard when the target dies while you are draining it.
Tested with an Affliction Warlock at level 33.

**Comment by Moustachos** [comment]
Ref #5979
