### ISSUE TITLE
Feral Druid: Combo Point Finishers

### ISSUE THREAD

**Issue by Raizo575** [Valhalla-Gaming/Tracker#6742]
**Describe the issue you're having**:
Finishers consume only 1 combo point at a time regardless of the current number of combo points you've accumulated.
**Explain how you expect it work**:
I expect my finishers to consume all combo points.
**Steps to reproduce the problem**:

1. Play Feral Druid.
2. Build up combo points.
3. Use any of your finishers that consume combo points.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/resource=4/combo-points

**Comment by Wilfredfizzlebang** [comment]
Rip sometimes uses 2 combo points but works as it was using only 1 ^^

**Comment by magicjoe92** [comment]
The rouges having problem with that too.!

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #5979
