### ISSUE TITLE
Feral Druid: Predatory Swiftness

### ISSUE THREAD

**Issue by Raizo575** [Valhalla-Gaming/Tracker#6743]
**Describe the issue you're having**:
Predatory Swiftness is not giving me the instant cast heal,root or rebirth as it should. Not even at 5 CP.
**Explain how you expect it work**:
I expect it to simply work as it should, it's not working at all right now.
**Steps to reproduce the problem**:

1. Play Feral Druid.
2. Use finishing moves at maximum combo points while being level 28 or above.
3. Watch your Predatory Swiftness passive taking up useless space in your spell book.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=16974

**Comment by Traveler-Valhalla** [comment]
#6268

**Comment by Moustachos** [comment]
Ref #5979
