### ISSUE TITLE
Druid spell: Predatory Swiftness

### ISSUE THREAD

**Issue by Djurdjevdan** [Valhalla-Gaming/Tracker#6752]
**Describe the issue you're having**:
Predatory Swiftness never procs. It should proc 20% per combo when you use finisher meaning at 5 combos it should always be active when you cast finisher.
**Explain how you expect it work**:
Predartory Swiftness should proc 20% per combo while using finishers making rebirth, healing touch and entegraling root insta cast in all forms.
**Steps to reproduce the problem**:
I'm sure this is linked to feral cimbo points as finishers consumes only one point instead of all of them.
**Links to Wowhead, YouTube, etc**:
http://wow.gamepedia.com/Predatory_Swiftness

**Comment by Traveler-Valhalla** [comment]
#6268

**Comment by Moustachos** [comment]
Ref #5979
