### ISSUE TITLE
İTEM SHOP

### ISSUE THREAD

**Issue by Furyr** [Valhalla-Gaming/Tracker#6753]
HELLO I NEED YOUR HELP I BUY İTEM (HORDE) BUT IAM ALİANCE PLS CHANGE İTEM OR GIVE MY MONEY BACK
![wowscrnshot_091816_175954](https://cloud.githubusercontent.com/assets/22060103/18616764/5c80f1fa-7dc1-11e6-9c22-135038f0a1f9.jpg) 
![image](https://cloud.githubusercontent.com/assets/22060103/18616893/adccbe88-7dc4-11e6-895c-8165e268223d.png)

**Comment by Redrian-Hellscream** [comment]
Again, learn to contact some GM privately, this is not the place for that.

**Comment by Furyr** [comment]
Hey How do I tell GM

**Comment by Seregruth** [comment]
Furyr, again. PLEASE send one of us GMs a PM on the forums so we can help you out.
The issue tracker is not a place for this kind of issue.
