### ISSUE TITLE
[Paladin][Talent][Protection]Cavalier

### ISSUE THREAD

**Issue by MichRattay** [Valhalla-Gaming/Tracker#6764]
**Describe the issue you're having**: Doesn't apply 

**Explain how you expect it work**: Should add a charge to Divine Steed spell

**Steps to reproduce the problem**:

1.  Choose the talent
2.  
3. 

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=230332/cavalier, http://www.wowhead.com/spell=190784/divine-steed

**Comment by Moustachos** [comment]
Works just fine on current version (Cavalier talent).

**Comment by Moustachos** [comment]
Ref #5979
