### ISSUE TITLE
[Paladin][Talent][Protection]Seraphim

### ISSUE THREAD

**Issue by MichRattay** [Valhalla-Gaming/Tracker#6766]
**Describe the issue you're having**: Doesn't increase said statistics and doesn't consume charges of Shield of the Righteous

**Explain how you expect it work**: should increase Critical Strike, Mastery, Haste, Versatillity

**Steps to reproduce the problem**:

1.  Use Seraphim
2.  observe characters statistics
3. 

**Links to Wowhead, YouTube, etc**:http://www.wowhead.com/spell=152262/seraphim

**Comment by Moustachos** [comment]
It properly increases the stats as of current version, but it still doesn't consume Shield of the Righteous' charges (will be fixed soon).

**Comment by Moustachos** [comment]
Ref #5979
