### ISSUE TITLE
Warrior - Heroic Leap - [spell=6544]

### ISSUE THREAD

**Issue by magicjoe92** [Valhalla-Gaming/Tracker#6772]
** Heroic Leap [spell=6544]
 - Do not  leaping**:

**Leap through the air toward a target location, slamming down with destructive force to deal (62.4% of Attack power) Physical damage to all enemies within 8 yards**:

**-http://www.wowhead.com/spell=6544/heroic-leap
   -https://www.youtube.com/watch?v=ZwJYqaA8nKM**:

**Comment by Trekex** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/5970
