### ISSUE TITLE
[Paladin][Retribution] Holy power

### ISSUE THREAD

**Issue by Aveh** [Valhalla-Gaming/Tracker#6774]
**Describe the issue you're having**:
Nothing  what use Holy power works even talent skill
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Moustachos** [comment]
Works fine on current version.

**Comment by Moustachos** [comment]
Ref #5979
