### ISSUE TITLE
Demon Hunter stuck at starting zone after finishing the quest chain 

### ISSUE THREAD

**Issue by Siifon** [Valhalla-Gaming/Tracker#6775]
After finishing the Demon Hunter Quest chain and getting out From vault of wardens , I talked to Khadgar and got ported to Orgrimmar and there i accidentally clicked on the Depholm Portal while searching for the dalaran's one , So i unstcuked my caracter and found myself in Mardum stuck there can't go anywhere. Please HELP ASAP 

after finishing the Quest , Khadgar port the Demon hunter to dalaran not Orgrimmar.

**Comment by Redrian-Hellscream** [comment]
If Khadgar ported you you, you would be stuck there with no inn and no artifact weapon, ask a GM for help.
