### ISSUE TITLE
Miss chance of mobs at the same level

### ISSUE THREAD

**Issue by TheGallahad** [Valhalla-Gaming/Tracker#6781]
With the level scaling implemented there still lies the issue of casters still having their spells miss frequently on mobs at the same level.

**Comment by Zulbox** [comment]
Not only casters, but melees aswell :) Not to mention their HP isn't scaled right, you deal way more than damage than their HP is, but it doesn't die :)

**Comment by Traveler-Valhalla** [comment]
Guys it's really heavy. As affliction warlock it's very hard to level up past 100. I can cast some dot spell 10+ times and it's all miss miss miss...
