### ISSUE TITLE
Heroic Leap

### ISSUE THREAD

**Issue by mameya007** [Valhalla-Gaming/Tracker#6783]
Bugged , the warrior can't jump fix it plz :'(

**Comment by kjelt** [comment]
use the template for reporting

I play warrior too and can confirm that heroic leap is not working. Sound works. But no effect to mop and no character movement.

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6864

**Comment by Moustachos** [comment]
Ref #5979
