### ISSUE TITLE
Cant Log in

### ISSUE THREAD

**Issue by 7DT** [Valhalla-Gaming/Tracker#6787]
Cant log in, i get disconnected every time

**Comment by kakaman123** [comment]
There is already a post about it in the server's forum. The GM said the server is supposed to be working soon.

**Comment by martovip** [comment]
When they will start the server does anyone knows?

**Comment by naftata** [comment]
Why not conect in server ? Server is offline or ???

**Comment by kakaman123** [comment]
I don't know if the server is online or not, but it will take some time until it gets able to log in because it has suffred a Ddos attack.

**Comment by Seregruth** [comment]
Please keep the issue tracker for Bugs please, not this kind of issue.
