### ISSUE TITLE
[Frost Mage] Flurry

### ISSUE THREAD

**Issue by shadowhunte182** [Valhalla-Gaming/Tracker#6788]
**Describe the issue you're having**: The spell doesn't have the animation of skill, i doesn't deal damage and it doesn't slow the target

**Explain how you expect it work**:
Have the animation, deal damage and slow the target
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
The animation, effect and damage are showed from 1:20 to 1:45: 
https://www.youtube.com/watch?v=DovIt9qcEx4
Sources: Channel Hogmanlolz on Youtube

**Comment by forstix** [comment]
reported https://github.com/Valhalla-Gaming/Tracker/issues/6272

**Comment by Moustachos** [comment]
Ref #5979
