### ISSUE TITLE
Rogue [Outlaw] Roll the bones and Grappling hook

### ISSUE THREAD

**Issue by Jehudiel** [Valhalla-Gaming/Tracker#6789]
**Describe the issue you're having**:
Roll the bones isn't work and grappling hook too
**Explain how you expect it work**:
Don't give a buff at least (role the bones). Grappling hook don't tae you where you want.
**Steps to reproduce the problem**:

1. You activate roll the bones / Grappling hook
2. Don't give any buff / don't take you wherever you want.
3. 

**Links to Wowhead, YouTube, etc**:

https://www.youtube.com/watch?v=ledN9bz8iBA

**Comment by Aveta** [comment]
In case you're level 100, the talent Slice and Dice which replaces RTB seems to work. Of course it's worse than RTB and isn't the best talent at lvl 100, but for now it should do the job as Outlaw quite needs the buff provided from RTB/SND.

**Comment by Moustachos** [comment]
Ref #5979
