### ISSUE TITLE
Fel rush and gliding

### ISSUE THREAD

**Issue by Zaid1972x** [Valhalla-Gaming/Tracker#6790]
**Describe the issue you're having**:
When you glide and use fel rush, you fall down to the ground rather than pushing you to the way you are gliding too
**Explain how you expect it work**:
When you double jump glide then fel rush it must push you to the way you are gliding too not to the ground.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
Watch any demon hunter gameplay.

**Comment by Redrian-Hellscream** [comment]
Already referenced in https://github.com/Valhalla-Gaming/Tracker/issues/5964, please close.
