### ISSUE TITLE
Gliding,

### ISSUE THREAD

**Issue by Zaid1972x** [Valhalla-Gaming/Tracker#6791]
**Describe the issue you're having**:
When you double jump and glide, its not working as it should
**Explain how you expect it work**:
When you double jump then 3rd space to glide, you get little jump boost to gliding more.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
Any demon hunter gameplay.

**Comment by Redrian-Hellscream** [comment]
Already referenced in https://github.com/Valhalla-Gaming/Tracker/issues/5940, please close.
