### ISSUE TITLE
Rogue Spell : Between the eyes

### ISSUE THREAD

**Issue by Bugtracker3000** [Valhalla-Gaming/Tracker#6814]
spell 90% times don't stun mobs, critical don't do 4x dmg

1 combo= 1 sec stun ...5 combo points 5 sec stun

spell must trigger stun effect and 4xtimes dmg on critical

http://www.wowhead.com/spell=199804/between-the-eyes

**Comment by Moustachos** [comment]
Can't confirm any of these issues, critical strikes properly deal four times normal damage and stun effect always applied when I tested it.

**Comment by Moustachos** [comment]
Ref #5979
