### ISSUE TITLE
[Warrior]Intercept

### ISSUE THREAD

**Issue by jarqo91** [Valhalla-Gaming/Tracker#6815]
**Describe the issue you're having**:

**Explain how you expect it work**:

**Steps to reproduce the problem**:
1. Spell does not work, only generate 20 rage when used. Before when it was charge everything was working fine. After when i reached next lvl it(charge) got morphed into intercept.
2. Run at high speed toward an ally or enemy. When targeting an enemy, Intercept will root for 1.5 sec, but has a minimum range of 8 yds. When targeting an ally, Intercept will intercept the next melee or ranged attack against the ally within 10 sec while the target remains within 10 yards. Generates 20 Rage.
3. Log warrior,get prot spec, earn 28lvl, try use intercept vs mob

**Links to Wowhead, YouTube, etc**:
Source: http://www.wowhead.com/spell=198304/intercept

**Comment by Moustachos** [comment]
Will be fixed on next update.

**Comment by Moustachos** [comment]
Ref #5979
