### ISSUE TITLE
[Rogue] Combo points don't increase Rupture's duration

### ISSUE THREAD

**Issue by Bugtracker3000** [Valhalla-Gaming/Tracker#6817]
when u use 5 combo points, the final spell spend all points but the effect is like you use only 1 combo point. 

es: i use rapture with 5 combo points....rapture is 8 sec and not at full 24sec

**Comment by Aveta** [comment]
Same thing happens to Nightblade, the Sub DoT.

**Comment by KimKatya** [comment]
And not just 8 seconds, but around 5-6.

**Comment by Bugtracker3000** [comment]
it happen to all spell that require combo points not only rapture!!

**Comment by Moustachos** [comment]
Ref #5979
