### ISSUE TITLE
Havoc Demon Hunter Demon's bite damage

### ISSUE THREAD

**Issue by GhettoStarGG** [Valhalla-Gaming/Tracker#6818]
**Describe the issue you're having**:
Havoc Demon Hunter Demon's bite damage is not correct.I've tested on mobs in legion areas, i am level 110 and vs a lvl 110 mob spell icon indicates that the spell damage is 31k  ,actually it hits the mobs for like 17-18k which is a huge pain. 

Needs correction of the damage of Demon's bite.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Moustachos** [comment]
Demon's Bite damage are just fine, if you see a lower amount that's because of your target's armor.

**Comment by Moustachos** [comment]
Ref #5979
