### ISSUE TITLE
Havoc Demon Hunter Chaos Strike damage

### ISSUE THREAD

**Issue by GhettoStarGG** [Valhalla-Gaming/Tracker#6819]
**Describe the issue you're having**:
Havoc Demon Hunter Chaos Strike damage is not correct.Icon of the spell indicates that it deal 68k dmg, actually it hits for much lower amount(35-45k).Tested with my havoc dh lvl 110 vs any legion lvl 110 mobs.
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Moustachos** [comment]
Chaos Strike damage are just fine, if you see a lower amount that's because of your target's armor.

**Comment by Moustachos** [comment]
Ref #5979

**Comment by Redrian-Valhalla** [comment]
Chaos Strike deals chaos damage, not physical, so there shouldn't be any reduction.
https://github.com/Valhalla-Gaming/Tracker/issues/7082
