### ISSUE TITLE
[Monk] [Spell] Windwalker: Fists of Fury

### ISSUE THREAD

**Issue by Blobble** [Valhalla-Gaming/Tracker#6829]
**Describe the issue you're having**: I use the spell on an enemy and all it does is deal some damage to the enemy I'm focusing. It's suppose to be an aoe spell.

**Explain how you expect it work**: You pummel all the targets in front of you dealing X damage over 4 seconds.

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=113656/fists-of-fury

**Comment by Bombrick** [comment]
it hits once only and doesn't continue hitting while the spell is channeling

**Comment by Blobble** [comment]
But that's the points of the spell. It should because it's a channeling
spell not instant.

Den 22 sep 2016 22:35 skrev "Bombrick" <notifications@github.com>:

**Comment by Blobble** [comment]
Channeling. Not instant.

**Comment by Moustachos** [comment]
Ref #5979
