### ISSUE TITLE
Arcane Blast

### ISSUE THREAD

**Issue by Oculeth** [Valhalla-Gaming/Tracker#6840]
**Describe the issue you're having**: Arcane blast of arcane mage spec doesnt generate an arcane charge

**Explain how you expect it work**: When i cast arcane blast, an arcane charge should be created below my character portrait

**Steps to reproduce the problem**: 

1. Cast Arcane Blast
2.  The Arcane Charges remain empty
3.  

**Links to Wowhead, YouTube, etc**:

**Comment by llamalama** [comment]
This does work correctly, you just have to relog after switching to arcane spec if it wasn't your active spec when you logged in last time.

**Comment by Moustachos** [comment]
Ref #5979
