### ISSUE TITLE
dot critical in general

### ISSUE THREAD

**Issue by forstix** [Valhalla-Gaming/Tracker#6846]
**Describe the issue you're having**:
dot ( damage over time ) is unable to crit
**Explain how you expect it work**:
dot should be able to crit 
**Links to Wowhead, YouTube, etc**:
tested on affi warlock and spriest so here some spell links:
sw: pain - http://www.wowhead.com/spell=589/shadow-word-pain
vt - http://www.wowhead.com/spell=34914/vampiric-touch
corruption - http://www.wowhead.com/spell=172/corruption
agony - http://www.wowhead.com/spell=980/agony
unstable affliction - http://www.wowhead.com/spell=30108/unstable-affliction

**Comment by forstix** [comment]
same with healing over time ^

**Comment by Moustachos** [comment]
Ref #5979
