### ISSUE TITLE
Dearest Natalia

### ISSUE THREAD

**Issue by GeneralCaveman** [Valhalla-Gaming/Tracker#685]
http://www.wowhead.com/quest=8304/dearest-natalia

You are able to talk with Rutgar and Frankal but there are only two dialogue screens with Rutgar and no dialogue options with Frankal.

**Comment by MeleeMaster** [comment]
I just wanted to say that I did this quest recently and it was possible to complete it. Looks like it was fixed.

**Comment by Cidragon** [comment]
You're right. This quest was fixed.
