### ISSUE TITLE
 [Inspiring Presence]

### ISSUE THREAD

**Issue by neano300** [Valhalla-Gaming/Tracker#6851]
**Describe the issue you're having**:
This spell work  bad. the spell give the buff but his don't heal when your allies attack.
**Explain how you expect it work**:
you inspire your allies within 60 yards, causing them to be healed for 3% of all damage they deal.
**Steps to reproduce the problem**:

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=205484/inspiring-presence

**Comment by llamalama** [comment]
This also pvp flags you automatically as it goes onto guards and such when it should not.

**Comment by Moustachos** [comment]
Ref #5979
