### ISSUE TITLE
 [Impending Victory]

### ISSUE THREAD

**Issue by neano300** [Valhalla-Gaming/Tracker#6852]
**Describe the issue you're having**:
This spell don't heal you when use it.
**Explain how you expect it work**:
Instantly attack the target, causing (240% of Attack power) damage and healing you for 15% of your maximum health.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=202168/impending-victory

**Comment by llamalama** [comment]
Adding in that the cooldown doesn't reset when you kill an enemy that rewards exp or honor.

**Comment by Moustachos** [comment]
Ref #5979
