### ISSUE TITLE
 [Shield Block]

### ISSUE THREAD

**Issue by neano300** [Valhalla-Gaming/Tracker#6863]
**Describe the issue you're having**:
When you use it "increase" your block  but everyone can hits you in all  moment 
**Explain how you expect it work**:
Raise your shield, blocking every melee attack against you for 6 sec. These blocks can be critical blocks. Increases Shield Slam damage by 30% while active.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=2565/shield-block

**Comment by Moustachos** [comment]
Block isn't supposed to fully absorb damage, it's only blocking 30% of incoming damage.

Shield Block is supposed to increase the chance to block these 30% and that's just what it already does, no bug.

**Comment by Moustachos** [comment]
Ref #5979
