### ISSUE TITLE
[Monk][Talent] Eye of the Tiger

### ISSUE THREAD

**Issue by Hemoglobine-Valhalla** [Valhalla-Gaming/Tracker#6865]
**Describe the issue you're having**:
Once you does palm of the tiger it should pop and heal you and damage your target acts like a bleed.
**Explain how you expect it work**:
Tiger Palm also applies Eye of the Tiger, dealing (172% of Attack power) Nature damage to the enemy and (172% of Attack power) healing to the Monk over 8 sec.
**Steps to reproduce the problem**:

1.  Hit an enemy with th talent choosed
2.  Watch how it works

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=196607/eye-of-the-tiger#changelog

**Comment by Bombrick** [comment]
info: damage works but healing doesn't.

**Comment by Hemoglobine-Valhalla** [comment]
Bombrick it doesnt deal damage, dot appears but doesnt deal damage.

**Comment by Moustachos** [comment]
Ref #5979
