### ISSUE TITLE
food dont work

### ISSUE THREAD

**Issue by nocturne1500** [Valhalla-Gaming/Tracker#6866]
**Describe the issue you're having**:

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by forstix** [comment]
reported https://github.com/Valhalla-Gaming/Tracker/issues/6375

**Comment by Seregruth** [comment]
Issue already reported,
Also please follow the template when reporting an issue.
