### ISSUE TITLE
transmog restiction

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#6870]
You should be able to transmog one-handed axe to one-handed sword but currently you can't. 

Seems like current restrictions are based on Cata patch but in MoP patch 5.2 restrictions were changed.

http://www.wowhead.com/guides/how-to-transmogrify-and-what-you-can-and-cannot-do

"Restriction: Weapons may be mogged with similar weapons. The compatible types are: (1h sword, axe, mace), (2h sword, axe, mace), (polearm, staff), and (bow, gun, crossbow). Daggers, fists, wands, shields, and off-hands can only be mogged with items of the same type, and you still must be able to equip both weapons normally."

**Comment by llamalama** [comment]
I was able to mog my 1h axe into a sword fine. You're either a shaman and can't use 1h swords, thus being unable to mog into them, or didn't use the drop down menu on the right side of the transmog window to switch the view from axes to swords.
