### ISSUE TITLE
Vampiric Touch

### ISSUE THREAD

**Issue by odelun** [Valhalla-Gaming/Tracker#6886]
Vampiric Touch is bugged, im almost level 110 and its  still dealing only 2 damage and 2 healing each tick, which makes shadow priest unplayable.

http://www.wowhead.com/spell=34914

[spell=34914]

**Comment by forstix** [comment]
reported https://github.com/Valhalla-Gaming/Tracker/issues/6275

**Comment by forstix** [comment]
Fixed

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #5979
