### ISSUE TITLE
[Demon Hunter][Veangeance][Metamophosis]

### ISSUE THREAD

**Issue by Diuesh** [Valhalla-Gaming/Tracker#6892]
**Describe the issue you're having**:
The Metamorphosis ability on vengeance demon hunter transforms me into a pig instead of a demon
**Explain how you expect it work**:
It should tranform me into a demon
**Steps to reproduce the problem**:

1. Create a demon hunter
2. Chose the Vengeance specialization
3. use Metamofphosis

**Links to Wowhead, YouTube, etc**:

**Comment by EldritchIHC** [comment]
Metamorphosis*

**Comment by Traveler-Valhalla** [comment]
Metapig*

**Comment by EldritchIHC** [comment]
xD

**Comment by Moustachos** [comment]
Ref #5979
