### ISSUE TITLE
Vial of Sands/Sanstone Drake

### ISSUE THREAD

**Issue by PapaToast** [Valhalla-Gaming/Tracker#6900]
I bought the mount Vial of Sands/Sandstone Drake from the shop because my friend plans of joining the server so i bought it so i can fly him around.a visual glitch where it shows another drake on top where the other player is supposed to be.

 You can reproduce this bug by mounting. 
![drake](https://cloud.githubusercontent.com/assets/21697440/18816189/4d9566b6-8312-11e6-9eb8-e1017652f540.JPG)

**Comment by GAMMARAYS** [comment]
Will be fixed next update.

**Comment by BeyondSteaLikez** [comment]
still not fixed. FeelsBadMan
