### ISSUE TITLE
[Warrior] [Arms] [Second Wind]

### ISSUE THREAD

**Issue by JozV** [Valhalla-Gaming/Tracker#6908]
**Describe the issue you're having**:
Second Wind is healing me non-stop, making me very hard to kill.

**Explain how you expect it work**:
Restores 6% health every 1 sec **when you have not taken damage for 5 sec.**

**Steps to reproduce the problem**:
1. Choose the talent Second Wind
2. Receive damage

**Links to Wowhead, YouTube, etc**:
https://www.youtube.com/watch?v=3fxqrxabpxM&feature=youtu.be

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #5979
