### ISSUE TITLE
[spriest][vampiric touch][shadow word:death]

### ISSUE THREAD

**Issue by magnaaa** [Valhalla-Gaming/Tracker#6911]
**Describe the issue you're having**:
the spell vampiric touch deals 2 unit of damage and after each tick from the moment i unlocked the spell until right now that my sprist is 100lvl
the spell shadow word death doesn't generate any insanity in and out of voidform.

**Explain how you expect it work**:
vampiric touch should deal a fixed amount of damage and heal me half the damage it deals.
shadow word:death is supposed to generate 10 units of insanity and 30 units of insanity if the target dies.
**Steps to reproduce the problem**:
1. cast vampiric touch
2. check your combat log

1.cast shadow word:death.
2.check your insanity amount.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=34914/vampiric-touch#changelog
http://www.wowhead.com/spell=32379/shadow-word-death

**Comment by forstix** [comment]
Vt fixed

**Comment by Moustachos** [comment]
Ref #5979
