### ISSUE TITLE
(shaman) earthgrab totem

### ISSUE THREAD

**Issue by camadonna** [Valhalla-Gaming/Tracker#6916]
**Describe the issue you're having**:
it roots for a second instead of 5 and then slowes 
**Explain how you expect it work**:
it should root for 5 seconds and then slow
**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=51485/earthgrab-totem

**Comment by retardnation** [comment]
works fine for me

**Comment by Nikos92** [comment]
also it should root the moment you put it on the ground. not after 2 sec. (the first pulse is instant)

**Comment by Nikos92** [comment]
but yeah the root duration is fine

**Comment by Moustachos** [comment]
Ref #5979
