### ISSUE TITLE
(shaman) vodoo totem

### ISSUE THREAD

**Issue by camadonna** [Valhalla-Gaming/Tracker#6917]
**Describe the issue you're having**:
does nothing
**Explain how you expect it work**:
should hex in 8 yards around totem
**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=196932/voodoo-totem

**Comment by Moustachos** [comment]
Will be fixed on next update.

**Comment by Moustachos** [comment]
Ref #5979
