### ISSUE TITLE
(shaman) earth shock

### ISSUE THREAD

**Issue by camadonna** [Valhalla-Gaming/Tracker#6919]
**Describe the issue you're having**:
it doesnt scale correctly with the amount of maelstrom
**Explain how you expect it work**:
it should deal more dmg for more maelstrom spent. Damage dealt  with 10 and 100 maelstrom is too close there should be a lot more difference
**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=8042/earth-shock

**Comment by Moustachos** [comment]
Works just fine.

**Comment by Moustachos** [comment]
Ref #5979
