### ISSUE TITLE
(shaman) overall dmg

### ISSUE THREAD

**Issue by camadonna** [Valhalla-Gaming/Tracker#6923]
**Describe the issue you're having**:
i leveled my ele shaman in retail for around 40 levels i m quite sure the dmg dealt in general (lava, lightning bolt, earth shock, frost shock, chain lightining isn' t correct. i had a lot less problems with mobs.
Surely it depends on gear weared but like here i didnt do any dungeon and had no heirlooms so more or less the gears are the same. i think that the dmg of the whole ele shaman has to be checked and corrected
**Explain how you expect it work**:
every spell should deal more dmg
**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by VictorTyne** [comment]
I think the more appropriate explanation here is Elemental Shaman spells are not currently receiving any bonuses from stats (namely Intellect). The tooltip states that Intellect should increase the magnitude of your spells. However when I cast a spell, say Lightning Bolt, the mob takes the exact damage reflected in the tooltip popup for Lightning Bolt.

So my Lightning Bolt tooltip currently says "Hurls a bolt of lightning at the target, dealing 885 nature Damage." Each time I cast it, the target will take exactly 885 damage no matter what gear I'm currently wearing.

**Comment by Moustachos** [comment]
Many Elemental shaman spells aren't working at the moment, but for the working ones damage are just fine.

**Comment by Moustachos** [comment]
Ref #5979
