### ISSUE TITLE
Arms warrior talents bugs 

### ISSUE THREAD

**Issue by zintox** [Valhalla-Gaming/Tracker#6926]
**Describe the issue you're having**:Fervor of Battle bug

**Explain how you expect it work**:

**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=202316/fervor-of-battle

**Comment by Tolno** [comment]
To add further details, the talent just doesn't work at all, it does not provide 30% increased damage on primary target, if you use it you can see easily that the damge is the same on every targets.

**Comment by Moustachos** [comment]
Ref #5979
