### ISSUE TITLE
Mage Spell: Arcane Missiles

### ISSUE THREAD

**Issue by llamalama** [Valhalla-Gaming/Tracker#6935]
http://www.wowhead.com/spell=5143/arcane-missiles

This spell is not generating arcane charges.

This spell is only getting a damage increase from arcane charges the first time you cast it after increasing your arcane charges. The second cast and onward it will act as if you have no arcane charges until you gain another charge (or reset charges and then add one if you're already at 4 charges.)

After casting this spell, any other spell that uses Arcane Charges will do damage as if you had no charges even when you do. This will happen until you reset your charges to 0.

**Comment by nuhrii** [comment]
Been reported

**Comment by Moustachos** [comment]
Ref #5979
