### ISSUE TITLE
[Demon Hunter] [Havoc] [Momentum] [Prepared]

### ISSUE THREAD

**Issue by JozV** [Valhalla-Gaming/Tracker#6936]
**Describe the issue you're having**:
Momentum and Prepared are being procced by Demon's bite and Throw Glaive. Momentum is being triggered by Vengeful Retreat and Prepared is being triggered by Fel Rush.

**Explain how you expect it work**:
Momentum should only be triggered by Fel Rush and Vengeful Retreat; and Prepared should only be triggered by Vengeful Retreat.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=206476/momentum
http://www.wowhead.com/spell=203551/prepared
https://www.youtube.com/watch?v=7mTap8du_Yo&feature=youtu.be

**Comment by Aveta** [comment]
Momentum IS supposed to be triggered by Vengeful Retreat.

**Comment by JozV** [comment]
I am so sorry for this mistake. I apologize for my ignorance

**Comment by Moustachos** [comment]
Ref #5979
