### ISSUE TITLE
[Rogue] [Kidney Shot] [bugged]

### ISSUE THREAD

**Issue by Bugtracker3000** [Valhalla-Gaming/Tracker#6942]
**Describe the issue you're having**:

kidney shot stun by 1 sec stead of 2/3/4/5/6 sec (requires combo points)

**Explain how you expect it work**:

1 combo=2 sec stun 2 combo=3sec stun....... 5 combo=6sec stun

**Comment by Aveta** [comment]
Envenom buff has the same issue currently.

**Comment by Moustachos** [comment]
Ref #5979
