### ISSUE TITLE
Demon Hunter: Blade Dance

### ISSUE THREAD

**Issue by Nienz** [Valhalla-Gaming/Tracker#6943]
**Describe the issue you're having**:
Spell isnt in spellbook, have to drag from spec tab but the spell doesnt work

**Explain how you expect it work**:
Instant cast

**Steps to reproduce the problem**:

1. Look on spellbook
2. Drag skill from Specialization tab to actionbar
3. Check skill on dummie

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=188499/blade-dance#modified-by

**Comment by Redrian-Hellscream** [comment]
Already reported.

**Comment by Moustachos** [comment]
Ref #5979
