### ISSUE TITLE
Warrior: Second wind (Legion)

### ISSUE THREAD

**Issue by Nienz** [Valhalla-Gaming/Tracker#6945]
**Describe the issue you're having**:
it heals massively even if im in combat

**Explain how you expect it work**:
start heal when being out of combat for 5 seconds

**Steps to reproduce the problem**:
1. Get to Level 60 pick Second WInd talent
2. Stand infront a mob and let it attack you
3. Watch the healing from Second Wind

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=29838/second-wind

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6908
