### ISSUE TITLE
Web Store: Purchased item not delivered

### ISSUE THREAD

**Issue by legendr820** [Valhalla-Gaming/Tracker#6952]
**Describe the issue you're having**: Item purchased from Web Store not delivered, 
item purchased: Date / Name / Currency
Sep, 25 2016 | 05:13 am
Upgraded Dwarven Hand Cannon
45 XTS

Please assist, thanks.

**Explain how you expect it work**: Deliver item

**Steps to reproduce the problem**: n/a

**Links to Wowhead, YouTube, etc**:

**Comment by GM-Pyromanic** [comment]
Heirlooms are placed in your collections tab shift + P (If you are logged in at time of purchase you will need to logout for them to show.)

Also the issue tracker is not for store related things please use the forums for Store issues.

**Comment by legendr820** [comment]
Thank you. I appreciate the response. BTW, I did use the forum, but no one
answered me.

Thank you.
