### ISSUE TITLE
Death Knight [Blood Talents] 

### ISSUE THREAD

**Issue by MissDK** [Valhalla-Gaming/Tracker#6955]
**Describe the issue you're having**:
Blooddrinker doesnt heal me at all.

**Explain how you expect it work**:
Blooddrinker should heal me.

**Steps to reproduce the problem**:

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=206931/blooddrinker

**Comment by Moustachos** [comment]
Will be fixed on next update.

**Comment by Moustachos** [comment]
Ref #5979
