### ISSUE TITLE
Death Knight [Blood Spells]

### ISSUE THREAD

**Issue by MissDK** [Valhalla-Gaming/Tracker#6959]
**Describe the issue you're having**:
1.Marrowrend deals too low damage.
2.It doesnt generate any charges of Bone Shield.
3.Bone Shield doesnt work at all.

**Explain how you expect it work**:
1.Marrowrend should deal correct damage.
2.The spell should generate 3 charges of Bone Shield.
3.When i have charges of bone shield each damaging attack should consume a charge and i have to take 16% reduced damage.
4.When i have at least one charge of Bone Shield my haste has to be increased by 10%.

**Steps to reproduce the problem**:
1. Now the spell only deals damage 
2. The damage it deals is too low.
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=195182/marrowrend
http://www.wowhead.com/spell=195181/bone-shield

**Comment by Moustachos** [comment]
Will be fixed on next update.

**Comment by Moustachos** [comment]
Ref #5979
