### ISSUE TITLE
Death Knight Rune Regen

### ISSUE THREAD

**Issue by llamalama** [Valhalla-Gaming/Tracker#6963]
The cooldown on runes occasionally bugs out and cuts the cooldown on a rune still regenerating, making it say the rune is fully replenished, but being unuseable until its normal cooldown would have passed.

When this happens, spells say they are castable, but trying to cast them will only make their casting animation occur with no damage and no cooldown.

**Comment by ElrondMcBong1337** [comment]
I also have the problem sometimes that for example two of your runes are visually regenerated, but you can only use spells again when ALL runes have regenerated.

**Comment by Moustachos** [comment]
Ref #5979
