### ISSUE TITLE
apexis vendors

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#6964]
**Describe the issue you're having**:
Arrakoa vendors sell their gear for free.
**Explain how you expect it work**:
I expect that gear to cost some goldz.
**Steps to reproduce the problem**:
1. fly to ashran island in draenor
2. walk or run whatever u want to those vendors
3. use mouse and right click to open their window

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/npc=86389/dawn-seeker-verroak

**Comment by kjelt** [comment]
And not all apexis vendors are available in ashran
