### ISSUE TITLE
udk bugs

### ISSUE THREAD

**Issue by nocturne1500** [Valhalla-Gaming/Tracker#6965]
**[Raise Dead][Death and Decay][Death Strike]
[Boost fever] [Unholy Frenzy] [Thrust fever][Contamination debilitating]**:

**it all bug  **:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
Try to add more details when reporting issues and post one problem at a time.
Most of those bugs have been reported, they're fixed and you should wait for the next update to see if changes took effect correctly.
