### ISSUE TITLE
Druid balance spell starsurge does not work

### ISSUE THREAD

**Issue by borisivaylov** [Valhalla-Gaming/Tracker#6966]
**Describe the issue you're having**:
It can't be casted.
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Aveta** [comment]
It works tho. Clear your cache and make sure you got the Astral Power for it.

**Comment by borisivaylov** [comment]
I did it but still I have that problem. I have the balance energy but it just can't be casted.

**Comment by Aveta** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6639 might be relevant? 
I have the talent Stellar Flare which shows same problems, so it's overall with AP spenders.

**Comment by Moustachos** [comment]
Ref #5979
