### ISSUE TITLE
Undead Warlock stuned with rigor mortis

### ISSUE THREAD

**Issue by priestgodgift** [Valhalla-Gaming/Tracker#6969]
**Describe the issue you're having**:
My character is never resurected so practicaly nothing works.
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 
![wowscrnshot_092916_025246](https://cloud.githubusercontent.com/assets/22509664/18936427/e910c3e4-85ef-11e6-8dcf-85d49466c9fb.jpg)

**Links to Wowhead, YouTube, etc**:

**Comment by iv4o939** [comment]
there is a buff you need to cancel it

**Comment by Seregruth** [comment]
Fixed next update.
