### ISSUE TITLE
Demon Hunter Dc from server issue

### ISSUE THREAD

**Issue by Hydriel** [Valhalla-Gaming/Tracker#6972]
**Describe the issue you're having**:
I am getting disconnected from the server almost every time i use my wing glide skill with my Demon Hunter Raith.
**Explain how you expect it work**:
It should not be disconnecting me from the server using skills 
**Steps to reproduce the problem**:
1. Use double jump, then glide, land on ground and get disconnected almost every time.
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
Did you try to repair your WoW client?

**Comment by Hydriel** [comment]
How do i do that, there is no repair option

**Comment by Moustachos** [comment]
Ref #5979
