### ISSUE TITLE
dont got items

### ISSUE THREAD

**Issue by tomee996** [Valhalla-Gaming/Tracker#6978]
**Describe the issue you're having**:
i bought these items yesterday and i wont got them yet.
**Explain how you expect it work**:
 i think its a problem because my level boost and gold arrived in time (5mins)
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
![elozmeny](https://cloud.githubusercontent.com/assets/22527123/18963479/7262c07c-8675-11e6-811e-999b7e081480.jpg)
![wowscrnshot_092916_184644](https://cloud.githubusercontent.com/assets/22527123/18963484/76ca66f6-8675-11e6-9745-b0b5aecd10c1.jpg)

**Comment by GM-Pyromanic** [comment]
Please post issues like this on the forum and not the issue tracker. Also I have replied to the topic you made on the forums. Issue tracker is for bugged spells talents mobs ect not store related issuses.
