### ISSUE TITLE
Druid Talent: Balance Affinity (Restoration Spec)

### ISSUE THREAD

**Issue by skorge1** [Valhalla-Gaming/Tracker#6982]
**Describe the issue you're having**:
When I enter moonkin form I still look like my normal form
**Explain how you expect it work**:
I expect to look like a moonkin
**Steps to reproduce the problem**:

1. Pick restoration spec
2. Pick Balance Affinity talent
3. Use moonkin form

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=197632/balance-affinity

**Comment by GM-Pyromanic** [comment]
Duplicate report #6251
