### ISSUE TITLE
Healing Surge not using maelstorm in enchancement shaman spec

### ISSUE THREAD

**Issue by Nikos92** [Valhalla-Gaming/Tracker#6984]
**Describe the issue you're having**: 
As enchancement shaman if you gather more than 20 maelstorm and use healing surge, it isn't being casted as an instant spell. It is casted over 2seconds instead

**Explain how you expect it work**:
After gathering 20 maelstorm, if you cast healing surge (as enchancement shaman), then it should consume 20 maelstorm and become instant cast

**Steps to reproduce the problem**:
1. Use skills that generate Maelstorm like Rockbiter and gather more than 20 Maelstorm
2. Cast Healing Wave. If it wasn't bugged it should consume 20 maelstorm and become an instant cast
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=188070/healing-surge

**Comment by GM-Pyromanic** [comment]
Duplicate report #6125

**Comment by Redrian-Valhalla** [comment]
Sorry Pyro but it's not a duplicate, that was not the same issue.

**Comment by Moustachos** [comment]
Ref #5979
