### ISSUE TITLE
Demon hunter missing abilities

### ISSUE THREAD

**Issue by wikktor1225** [Valhalla-Gaming/Tracker#6988]
**Describe the issue you're having**: I noticed that Havoc Demon Hunter have some missing abilities The links are below.

**Explain how you expect it work**: It should work as the wowhead link will show it. 

**Steps to reproduce the problem**:

1.  The best option would be that these missing abilities would come automatically with the level or just add it in from the beginning of a Demon Hunter. Because these spell would come by level or by quests officially and as many DH are already on level 110 they still would not have these abilities, so the best option is just to add it in for all the level Demon Hunters.
2. 
3. 

**Links to Wowhead, YouTube, etc**:
1. http://www.wowhead.com/spell=188499/blade-dance
2. http://www.wowhead.com/spell=217832/imprison
3. http://www.wowhead.com/spell=196718/darkness
4. http://www.wowhead.com/item=127829/twinblades-of-the-deceiver&bonus=0 this item should give this: http://www.wowhead.com/spell=201628/fury-of-the-illidari ability

**Comment by Redrian-Valhalla** [comment]
Fury of the Illidari is already present when you obtain your artifact, the other abilities have already been reported, you can find them here: https://github.com/Valhalla-Gaming/Tracker/issues/5979

**Comment by wikktor1225** [comment]
Hi Fury of the Illidari is in present, but does not working! so it is there
but sometimes if you click on the spell happens nothing, or it apperas but
does no damage so thats why I reported as missing ability

2016-09-29 23:44 GMT+02:00 Redrian-Valhalla <notifications@github.com>:

**Comment by Redrian-Valhalla** [comment]
That's reported too.

**Comment by Moustachos** [comment]
Ref #5979
