### ISSUE TITLE
Rogue Soothing Darkness/Deepening Shadows

### ISSUE THREAD

**Issue by ElrondMcBong1337** [Valhalla-Gaming/Tracker#6989]
**Describe the issue you're having**:

Both passive abilities/skills do not work

**Explain how you expect it work**:

Deepening Shadows should reduce cooldown of Shadowdance with finishing moves (important for sub-build)
Soothing Darkness does not heal in stealth

**Steps to reproduce the problem**:
use finishing moves 
set talent to Soothing Darkness

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/guides/classes/rogue/subtlety/talents
http://www.wowhead.com/spell=185314/deepening-shadows

**Comment by Redrian-Valhalla** [comment]
Deepening Shadows was already reported https://github.com/Valhalla-Gaming/Tracker/issues/6417
Soothing Darkness seems to be new.

**Comment by Moustachos** [comment]
Soothing Darkness works just fine (healing will appear as "Stealth" in combat log).

**Comment by Moustachos** [comment]
Ref #5979
