### ISSUE TITLE
Death Knight: Bursting Sores, Epidemic, Icecap

### ISSUE THREAD

**Issue by ElrondMcBong1337** [Valhalla-Gaming/Tracker#6993]
**Describe the issue you're having**:

Bursting Sores: Talent does not do aoe damage to nearby enemys
Epidemic: deals no damage and pulls enemys even without virulent plagues
Icecap: does not reduce cooldown of Pillar of Frost

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=207264/bursting-sores
http://www.wowhead.com/spell=207317/epidemic

http://www.wowhead.com/guides/classes/death-knight/frost/talents

**Comment by Redrian-Valhalla** [comment]
Please make a report for each spell, it will be easier to get them fixed like that.
