### ISSUE TITLE
Expert riding dissapears

### ISSUE THREAD

**Issue by priestgodgift** [Valhalla-Gaming/Tracker#6995]
**Describe the issue you're having**:
I taught my dk expert riding 2 times and every time i log out i lose the ability to fly
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
Duplicate of https://github.com/Valhalla-Gaming/Tracker/issues/6830
