### ISSUE TITLE
Bugs of Shaman

### ISSUE THREAD

**Issue by sierra95** [Valhalla-Gaming/Tracker#7002]
Hi, i noticed bug on spells of shaman...
1. Fire Elemental, it does not evoke the fire elemental;
2. Lightning Surge Totem, does nothing;
3. Echo of the Elements, if you choose the talent when it works but if you restart the game, or even a simple logout talent remains but the spell no longer doubled;
4. Earthen Rage, i do not even function because I do not see anything happen to what he says;

Pleads I only discovered these bugs, if I find more I will point them at the earliest. Thanks and sorry for the trouble.

**Comment by sierra95** [comment]
There here also Tidal Waves, don't proc when i cast Riptide and the talet Crashing Waves don't make other stack of Riptide. When i'm in elemental spec and cast Wolf form and then return in normal form the bar of Maelstorm faded.

**Comment by Redrian-Valhalla** [comment]
Your first 2 spells are already reported, please don't make duplicates, try to search before posting something new.
Echo of the elements, Earthen rage and Tidal waves seem to be new bugs, but please report them at once, don't put more spells in the same post, thank you.

**Comment by Traveler-Valhalla** [comment]
#6351 earthen rage reported too

**Comment by sierra95** [comment]
Sorry next time i ceck first and then post.
