### ISSUE TITLE
shadow mend [disc priest]

### ISSUE THREAD

**Issue by aetoni** [Valhalla-Gaming/Tracker#7009]
**Describe the issue you're having**: shadow mend is supposed to deal damage when you heal but it doesnt

**Explain how you expect it work**: heal the target then deal damage unless the target is out of combat
![screenshot_2](https://cloud.githubusercontent.com/assets/22433174/19019764/33393952-8847-11e6-82e2-b6cc547e2a45.png)

**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by forstix** [comment]
reported https://github.com/Valhalla-Gaming/Tracker/issues/6712

**Comment by Moustachos** [comment]
Ref #5979
