### ISSUE TITLE
First Level's Training

### ISSUE THREAD

**Issue by Chayni** [Valhalla-Gaming/Tracker#7010]
**Describe the issue you're having**:

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. Paladin's and Rouge's Trainings are bugged (Human Race, may be in another classes.)
2. Spells dosent exist and you need to get to lvl 10 or giher to choose the 2nd skill. (On the class training mission)
3. 

**Links to Wowhead, YouTube, etc**: None.

**Comment by GM-Pyromanic** [comment]
The quests can be skipped they were removed from retail and will be removed from Valhalla in a future update as we go back and check over the starting zones.
