### ISSUE TITLE
[Balance-Druid] Eclipse bar disappears.

### ISSUE THREAD

**Issue by impressmelv** [Valhalla-Gaming/Tracker#7013]
**When loging as a druid balance, as a normal form i see the whole bar - HP, Solar/Lunar(eclipse) bar, MP. After switching to any other form - for example, the same balance form Moonkin, the Solar/Lunar bar disappears permanently, and there are just HP and MP, no matter what i do, and it reappears only when relogged, but as you see, changing forms after relog - again it disappears. **:

**Explain how you expect it work**:
Using normal form and switching to moonkin form and back to normal form the Solar/Lunar power bar stays all the time, and working properly.

**Steps to reproduce the problem**:

1. Probably re-scripting the bar status/situation. 

**Links to Wowhead, YouTube, etc**:
http://wow.gamepedia.com/Eclipse
https://www.youtube.com/watch?v=QGDwwft5tJ0 (how it should be in legion(from retail)).

**Comment by GM-Pyromanic** [comment]
Issue should not be fixed with latest changelog https://valhalla-realms.com/log#2016.6.10.071500
