### ISSUE TITLE
enhacement shaman hailstorm talent bug

### ISSUE THREAD

**Issue by retardnation** [Valhalla-Gaming/Tracker#7014]
**Describe the issue you're having**:
when frostbrand is active the buff is showed as a debuff and frostbrand attacks only slow the target and dont do extra damage while having the Hailstorm talent as a new passive
**Explain how you expect it work**:
with getting hailstorm as a talent it passively adds damage to forstbrand attacks 
**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Nikos92** [comment]
Adding a wowhead link:
http://www.wowhead.com/spell=196834/frostbrand

**Comment by Nikos92** [comment]
And also don't forget that it should also proc on all weapon attacks like stormstrike and lava lash not only on melee hits. Just like flametongue as i show in my bug report for it. https://github.com/Valhalla-Gaming/Tracker/issues/7084

**Comment by Nikos92** [comment]
Also frostband appear on debuffs. Ofc this is something minor but it's annoying because when if it appears on debuffs it doesn't appear on the health/mana bar with buffs on the middle of the screen like flametongue does

**Comment by Moustachos** [comment]
Ref #5979
