### ISSUE TITLE
Demon hunter ''Glide''

### ISSUE THREAD

**Issue by Kato134** [Valhalla-Gaming/Tracker#7017]
The spell ''Glide'' of the demon hunter does not work correctly

When you use it after use the double jump or when you are falling, you can control the falling direction

http://www.wowhead.com/spell=131347/glide#changelog
https://www.youtube.com/watch?v=33JTf26Kkkg

**Comment by Redrian-Valhalla** [comment]
Already reported https://github.com/Valhalla-Gaming/Tracker/issues/5940
