### ISSUE TITLE
Pandaren

### ISSUE THREAD

**Issue by Chayni** [Valhalla-Gaming/Tracker#7018]
**Describe the issue you're having**: Pandaren fist mission, you cant complete it.

**Explain how you expect it work**: 

**Steps to reproduce the problem**:

1.  Creating a Pandaren character
2.  At the first mission, you cant pick up the weapon you need to complete the mission.
3. 

**Links to Wowhead, YouTube, etc**: None.

**Comment by Redrian-Valhalla** [comment]
Could you provide more information please? what's the name of the quest?

**Comment by Traveler-Valhalla** [comment]
http://www.wowhead.com/quest=30027/the-lesson-of-the-iron-bough
#6032

**Comment by Seregruth** [comment]
Already reported #6032
