### ISSUE TITLE
Trinket: Touch Of The Void 

### ISSUE THREAD

**Issue by callumjames12** [Valhalla-Gaming/Tracker#7019]
**Describe the issue you're having**:
The Trinket skill does 12 damage at level 12, which doesnt seem right
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
This item doesn't deal damage, are you talking about the NPC summoned by it?

**Comment by callumjames12** [comment]
Trinket: Touch of Void, Summons forth void Tendrils to Aid you in combat for 20 secs, so i presume they do damage rather than so little damage i wonder why i donated for them. and sorry my level was 26,

**Comment by Seregruth** [comment]
Already been reported.
#2358
