### ISSUE TITLE
questing in draenor

### ISSUE THREAD

**Issue by aetoni** [Valhalla-Gaming/Tracker#7023]
**Describe the issue you're having**: so i went to draenor and i cant find any quest after garrison

**Explain how you expect it work**: well i expect to find at least some quests working cuse ims tuck at lvl 93, i went through all gorgrond and shadowmoon  valley even the frostfire ridge

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
A big part of Draenor's quests are not scripted, some are but the fastest way to level to 100 is by killing NPCs.
