### ISSUE TITLE
Demon hunter Soul Fragments

### ISSUE THREAD

**Issue by Nienz** [Valhalla-Gaming/Tracker#7027]
So i tested few stuff on my DH in Vengeance spec, cant really pinpoint what is causing it but came up with two things but first let me talk about:

 http://www.wowhead.com/spell=209795/fracture, it suppose to spawn lesser fragments which it doesnt it actually spawns a Soul Fragment that heals for 300k/ Fragment at a high rate, with few hits theres 10 Soul Fragments each healing for same amount

And we have http://www.wowhead.com/spell=203782/shear that should spawn lesser soul fragments, but it spawns Soul Fragments as well as the above healing for 300k / fragment

So i have never seen a lesser fragment spawn once, only the ones from http://www.wowhead.com/spell=204254/shattered-souls. so either one of the above is making the big fragments spawn or the mastery is buggy

**Comment by Redrian-Valhalla** [comment]
already reported few minutes ago https://github.com/Valhalla-Gaming/Tracker/issues/7026
if you have something new to add, please do it there.
