### ISSUE TITLE
Paladin Consecration - Templar&Final Verdict - Dvinestorm - Greater Judgment not working

### ISSUE THREAD

**Issue by Deazz** [Valhalla-Gaming/Tracker#7028]
Paladin Consecration - Templar&Final Verdict - Dvinestorm - Greater Judgment 0 dmg also not working

**Comment by Redrian-Valhalla** [comment]
Duplicates:
https://github.com/Valhalla-Gaming/Tracker/issues/5968
https://github.com/Valhalla-Gaming/Tracker/issues/6379
https://github.com/Valhalla-Gaming/Tracker/issues/6210
https://github.com/Valhalla-Gaming/Tracker/issues/6007

Once again, please search before making reports and never post more than a spell unless it is somehow related to another issue.
