### ISSUE TITLE
champion's treadblade

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#7030]
**Describe the issue you're having**:
Champion's Treadblade costs nothing.
**Explain how you expect it work**:
Should cost 100k gold.
**Steps to reproduce the problem**:

1. go to stormwind
2. find that dude selling bike
3. right click thet bike to "buy" it

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/item=116789/champions-treadblade

**Comment by Redrian-Valhalla** [comment]
These things are to be reported privately to a member of the staff.
