### ISSUE TITLE
heirloom upgrade tokens

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#7031]
**Describe the issue you're having**:
Upgrade tokens can be "bought" for free.
**Explain how you expect it work**:
Should cost goldzzz.
**Steps to reproduce the problem**:

1. go to ironforge or undercity
2. find that dude selling heirlooms
3. "buy" em

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/item=122339/ancient-heirloom-scabbard
http://www.wowhead.com/item=122340/timeworn-heirloom-armor-casing
http://www.wowhead.com/item=122341/timeworn-heirloom-scabbard
http://www.wowhead.com/item=122338/ancient-heirloom-armor-casing

**Comment by Redrian-Valhalla** [comment]
These things are to be reported privately to a member of the staff.
