### ISSUE TITLE
Everything wrong with Frost DK atm

### ISSUE THREAD

**Issue by miloskovac** [Valhalla-Gaming/Tracker#7034]
**Describe the issue you're having**:

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. Here we go:
http://www.wowhead.com/spell=189186/crystalline-swords dont work as main dk artifact passive ability.
http://www.wowhead.com/spell=190778/sindragosas-fury dont work as a main dk artifact cd
http://www.wowhead.com/spell=189185/hypothermia artifact passive trait also dont work.
http://www.wowhead.com/spell=194913/glacial-advance talent also not working
http://www.wowhead.com/spell=123693/plague-leech also not working
2. as it say in wow links: actualy work and do dmg and other side effects (slow, make deasease ect).
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by miloskovac** [comment]
Ofc there r more talents/spells bugged atm, but i think these r the top priority ones

**Comment by Redrian-Valhalla** [comment]
Hello, reporting multiple spells at the same time will end up with them being ignored by devs or not categorized, please report each one of them on their own post.
