### ISSUE TITLE
warrior "shockwave is bug and other issues"

### ISSUE THREAD

**Issue by esteban1890** [Valhalla-Gaming/Tracker#7036]
hi! the server is ver so good, yeah! , howeber the warrior talent shockwave is bug, and others protection talents,

thanks , and thanks for this server , :)

**Comment by Redrian-Valhalla** [comment]
I'm glad you like Valhalla, but the talent Shockwave is already reported https://github.com/Valhalla-Gaming/Tracker/issues/6850
Let us know if you found any new bugs if they haven't been reported before.
