### ISSUE TITLE
[Arms - Warrior] Overpower

### ISSUE THREAD

**Issue by assassin14** [Valhalla-Gaming/Tracker#7039]
**Describe the issue you're having**:
The skill goes away when you use another skill that isn't overpower
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. wait until its up
2. when its up use a skill that's not overpower
3. 

**Links to Wowhead, YouTube, etc**:
www.wowhead.com/spell=7384/overpower

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6925
already reported.
