### ISSUE TITLE
[Arms - Warrior] Fervor of battle

### ISSUE THREAD

**Issue by assassin14** [Valhalla-Gaming/Tracker#7040]
**Describe the issue you're having**:
does not add the 30% increased damage to primary target
**Explain how you expect it work**:
Should add more damage to primary target
**Steps to reproduce the problem**:

1. use whirlwind while attacking 4 or more without the talent on main target
2. using Fevor of Battle in the same group the damage is the same on main target
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=202316/fervor-of-battle

**Comment by Redrian-Valhalla** [comment]
Fervor of battle
