### ISSUE TITLE
[Arms - Artifact] many will fall

### ISSUE THREAD

**Issue by assassin14** [Valhalla-Gaming/Tracker#7045]
**Describe the issue you're having**:
Does not add Increases damage dealt by Whirlwind by 5%.  for each upgrade

**Steps to reproduce the problem**:
1. put 3 into the trait 
2. Damage does not increase Whirlwind damage
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=216274/many-will-fall

**Comment by Moustachos** [comment]
Works just fine.
