### ISSUE TITLE
stormstrike damage ; enhancement shaman

### ISSUE THREAD

**Issue by retardnation** [Valhalla-Gaming/Tracker#7046]
**Describe the issue you're having**:
stormstrike deals like 60% of normal damage 
**Explain how you expect it work**:
![wowscrnshot_100516_153726](https://cloud.githubusercontent.com/assets/22277085/19115685/301485d2-8b13-11e6-8f19-9f0adda31fdb.jpg)

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
You didn't count NPCs' armor rating, to test damage properly you should get a friend, ask him to duel without any armor and the damage should be closer to the one suggested in the tooltip.
