### ISSUE TITLE
windfury passive/doom winds artifact weapon spell ;enhancement shaman

### ISSUE THREAD

**Issue by retardnation** [Valhalla-Gaming/Tracker#7047]
**Describe the issue you're having**:
windfury passive on triggers when doom winds is active ,and when doom winds is active damage dealt by windfury attacks deal normal damage instead of dealing 200% bonus damage
**Explain how you expect it work**:
when u cast doom winds all attacks trigger windfury, which works correctly , and windfury attacks have 200% increased damage ,which is bugged, and windfury should have passively a 6% chance to trigger with auto attacks ,which is bugged.
![wowscrnshot_100516_154129](https://cloud.githubusercontent.com/assets/22277085/19116057/78a35eee-8b14-11e6-86bb-0b2fe3732f34.jpg)

**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Moustachos** [comment]
Both Windfury and Doom Winds work just fine.

**Comment by Moustachos** [comment]
Ref #5979

**Comment by Moustachos** [comment]
Ref #5979
