### ISSUE TITLE
Warrior Talent Impeding Victory (Critical talent for Warrior Survival)

### ISSUE THREAD

**Issue by cypherous12** [Valhalla-Gaming/Tracker#7048]
**Describe the issue you're having**:Impeding victory (Critical Talent for warriors survival)

**Explain how you expect it work**:It does not heal you for 30% when you hit a mob/target

**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by cypherous12** [comment]
please please please fix soon I main a warrior prot and I need it to heal in combat!

**Comment by Moustachos** [comment]
Ref #5979
