### ISSUE TITLE
Fel Rush disconnecting the player

### ISSUE THREAD

**Issue by Redrian-Valhalla** [Valhalla-Gaming/Tracker#7050]
**Describe the issue you're having**:
Fel Rush disconnects the player when used in air.
**Explain how you expect it work**:
It shouldn't disconnect the player.
**Steps to reproduce the problem**:

1. Jump
2. Use Fel Rush in air
3. Rage.

**Links to Wowhead, YouTube, etc**:

**Comment by hellraiserz** [comment]
pls fix ASAP ty :)

**Comment by Moustachos** [comment]
Ref #5979
