### ISSUE TITLE
Character textures missing?

### ISSUE THREAD

**Issue by Falango** [Valhalla-Gaming/Tracker#7051]
**Describe the issue you're having**:
Male NE character displays as bright blue on screen, in health bar avatar, and small action bar avatar.  Shapeshifts seem ok.  This only happens after shapeshifting.  It shows properly after relogging.
**Explain how you expect it work**:

**Steps to reproduce the problem**:
1. Shapeshift into an animal form
2. Shift back to caster form
3. See bright blue radioactive skin
   ![blueeeeee](https://cloud.githubusercontent.com/assets/22652137/19140580/46e0ffd6-8b43-11e6-9bce-5ed4ba8fd6c4.jpg)

**Links to Wowhead, YouTube, etc**:

**Comment by get50** [comment]
it problem with nightelf my demon hunter got like this after relog its fixed

**Comment by masterbater089** [comment]
Maybe because it tries to show an old model after you switch out of a form..??? No idea why

**Comment by Redrian-Valhalla** [comment]
The problem is server-side, please wait for the next update.

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7091
