### ISSUE TITLE
Can not learn the (Apprentice) Mining profession.

### ISSUE THREAD

**Issue by Leonflowen** [Valhalla-Gaming/Tracker#7052]
**Describe the issue you're having**: Can not learn the (Apprentice) Mining profession.

**Explain how you expect it work**: For 8 copper, I should be able to learn Apprentice Mining.

**Steps to reproduce the problem**: 

1. Have Skinning as a primary (first) profession.
2. Attempt learning Apprentice Mining for 8 copper.
3. Hitting "Accept" does nothing, and Apprentice Mining remains in the NPC's menu.

**Links to Wowhead, YouTube, etc**: 

For the record, I am a level 7 Blood Elf Priest, attempting to learn from Belil in Farstriders' Square, Silvermoon City. 

I've tried using /reload, logging out and back in, and even closing and restarting the game. The installation is fresh, and I made sure to give the menu time to fully load.

**Comment by Redrian-Valhalla** [comment]
Please try to learn Mining from another NPC, if the problem persists contact a GM.
