### ISSUE TITLE
[Quest]  [Rise of the Illidari]

### ISSUE THREAD

**Issue by get50** [Valhalla-Gaming/Tracker#7053]
**Describe the issue you're having**:
quest  [Rise of the Illidari] click on the cell do nothing 
**Explain how you expect it work**:
it should complete the quest and spawn freed illidari
**Steps to reproduce the problem**:

1. click
2. cell broken
3. invalid target

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=38690/rise-of-the-illidari

**Comment by Redrian-Valhalla** [comment]
The quest is confirmed as working.

**Comment by get50** [comment]
for me it didnt work and i inv another demon hunter to do this quest for me and worked for him

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7065

**Comment by GM-Pyromanic** [comment]
Just tested this quest in game and am able to gain credit for the quest.
![valhalla-64_2016-10-06_23-53-17](https://cloud.githubusercontent.com/assets/20587569/19173602/4b023bb0-8c20-11e6-9a18-8df8892988ef.jpg)

**Comment by rover4fun** [comment]
This quest did not work for me (invalid target). I closed the game and cleared Cache folder - that worked! :)
