### ISSUE TITLE
All thing paladin

### ISSUE THREAD

**Issue by restlessspirit4** [Valhalla-Gaming/Tracker#7057]
**Describe the issue you're having**:
Retribution talents in row 15 and 75 are not working properly.Also there is a problem with holy wrath talent.Templar verdict and divine storm are also broken.

**Explain how you expect it work**:
We expect for them deal damage obviously.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
lvl 15 talents
http://www.wowhead.com/spell=157048/final-verdict
http://www.wowhead.com/spell=213757/execution-sentence
http://www.wowhead.com/spell=26573/consecration
lvl 75 talents
http://www.wowhead.com/spell=215661/justicars-vengeance
http://www.wowhead.com/spell=205191/eye-for-an-eye
http://www.wowhead.com/spell=210191/word-of-glory
lvl 100
http://www.wowhead.com/spell=210220/holy-wrath

As for the initial skills themselves
http://www.wowhead.com/spell=85256/templars-verdict
http://www.wowhead.com/spell=53385/divine-storm

Hoping this gets fixed soon.Palas arent unplayable but we are kinda impaired wouldnt you say.

With regards

Kandros

ps-Keep up the good work guys. 8)
pps-Blessings that dont work properly.
http://www.wowhead.com/spell=203528/greater-blessing-of-might
http://www.wowhead.com/spell=203538/greater-blessing-of-kings

Wisdom works by what i can gather

**Comment by Redrian-Valhalla** [comment]
Many of these issues are already reported, don't post more than one issue in the same post.
