### ISSUE TITLE
barber crash shop

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#7061]
**Describe the issue you're having**:
When I try to change appearance of my beautiful female undead character at barber shop I get an error 132.
**Explain how you expect it work**:
I should be able to change my character's face, hair, whatever without any crash.
**Steps to reproduce the problem**:
1. make female undead
2. go to barber
3. try to change something

**Links to Wowhead, YouTube, etc**:

**Comment by rover4fun** [comment]
Also this druid looks like abomination, or she have serious genetic disease ;P
[![WoWScrnShot_100716_165421.jpg](https://s10.postimg.org/pguf3b2m1/Wo_WScrn_Shot_100716_165421.jpg)](https://postimg.org/image/719y5wohh/)
https://postimg.org/image/719y5wohh/
This occurs after shapeshifting.
I believe both issues are related.

**Comment by Traveler-Valhalla** [comment]
also i got that crash when i tried to change something on female gnome
