### ISSUE TITLE
Death Knight Apocalypse

### ISSUE THREAD

**Issue by ElrondMcBong1337** [Valhalla-Gaming/Tracker#7062]
**Describe the issue you're having**:

The spell Apocalypse deals damage but does not summon the Army of Dead Ghouls... 
The Spell Army of  Dead itself works

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=220143/apocalypse
http://www.wowhead.com/spell=42650/army-of-the-dead

**Comment by theprototyze** [comment]
The issue is that Apocalypse doesn't burst any Festering Wounds (should burst up to 6) and spawns ny Ghouls

**Comment by theprototyze** [comment]
It also deals only about 50% of the damage that it says it does.

**Comment by Moustachos** [comment]
Ref #5979
