### ISSUE TITLE
Demon Hunter Blade Dance

### ISSUE THREAD

**Issue by lamasaregods** [Valhalla-Gaming/Tracker#7064]
**Describe the issue you're having**: After casting Blade Dance, Master of the Glaive applies to the caster of Blade Dance and slows him by 50%

**Explain how you expect it work**: Not applying Master of the Glaive on myself after casting Blade Dance

**Steps to reproduce the problem**: 

1. play Demon Hunter
2. get into battle
3. cast Blade Dance

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
I can't replicate the issue with the info you've given, Blade Dance seems to work fine.
