### ISSUE TITLE
[Profession] [Mining] [Human Monk]

### ISSUE THREAD

**Issue by DeathByDuke** [Valhalla-Gaming/Tracker#7066]
**Describe the issue you're having**:
Unable to mine any veins in Burning Steppes, Elwynn Forest, Copper, Mithril etc. Have disabled addons, logged out and even bought a new mining pick. Each veins comes with the message "invalid target"
**Explain how you expect it work**:
Mine to my merry hearts content! I want dem gold in thar hills!
**Steps to reproduce the problem**:

1. Learn mining
2. Try mining
3. no Profit? :/

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7073
