### ISSUE TITLE
Fel Rush bug

### ISSUE THREAD

**Issue by wikktor1225** [Valhalla-Gaming/Tracker#7068]
**Describe the issue you're having**: I noticed that with the new update on 10.05.2016 when they fixed the mid air travelling with Felrush, that okay now it travels me forwards, but always causes a game crash which is pretty nasty.

**Explain how you expect it work**:
Should work without any gamcrashes
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7050
