### ISSUE TITLE
Demon Hunter transmog bug + simple transmog bug

### ISSUE THREAD

**Issue by wikktor1225** [Valhalla-Gaming/Tracker#7069]
**Describe the issue you're having**: Not all the achievable items are added into the wardrobe, some items what have been earned doesnt appears in the wardrobe however the game noticed us in the chat bubble that the item has been added, or just even doesnt adds it to our wardrobe. Demon Hunter weapon transmog bug for demon hunters there is only 3 options to transmog weapon: one-handed weapons, one-handed axes, and warglaives, the missing weapon types are daggers and fist weapons. There is no such a choosable tab to transmog fistweapons or daggers only the 3 above listed ones. Demon Hunters should be allowed to transmog their weapons to any type what they can wear, just like on retail.

**Explain how you expect it work**:
Any collectable Item should be added correctly to the wardrobe, and update the wardrobe feature with all the missing items. Fix the items what even appears in the wardrobe as achievable items but when you achieve it it is not added to your wardrobe. Demon Hunters should be able to transmog their weapons on any type of weapon what they are able to wear (fixing the transmog system for them make available the other 2 weapon type).

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
Demon Hunters can equip Warglaives, daggers, swords, axes, and fist weapons. Warglaives, swords, and axes can be transmogged onto each other.
You should try equipping the item to add it in the wardrobe.
