### ISSUE TITLE
Hunter - Marked Shot

### ISSUE THREAD

**Issue by Redrian-Valhalla** [Valhalla-Gaming/Tracker#7070]
**Describe the issue you're having**:
Marked Shot can be spammed and its damage grows exponentially because of Vulnerable.
**Explain how you expect it work**:
Marked Shot should consume Hunter's Mark on each use.
**Steps to reproduce the problem**:

1. Wait for Hunter's Mark to be applied on the target
2. Once HM is on, spam Marked Shot repeatedly. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by forstix** [comment]
i got hit by that spell for 1m health... kinda sad

**Comment by Moustachos** [comment]
Ref #5979
