### ISSUE TITLE
Demon Hunter - Blade Dance

### ISSUE THREAD

**Issue by Redrian-Valhalla** [Valhalla-Gaming/Tracker#7071]
**Describe the issue you're having**:
Using Blade Dance right after using Fel Rush, causes the player to get a Master of The Glaive debuff, slowing down the caster.
**Explain how you expect it work**:
Blade Dance shouldn't apply that debuff.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
Using a mount before casting fel rush may also trigger the same debuff after using Blade Dance.

**Comment by Moustachos** [comment]
Ref #5979
