### ISSUE TITLE
Herbalism 75-150 Broken

### ISSUE THREAD

**Issue by Korserva** [Valhalla-Gaming/Tracker#7073]
**Describe the issue you're having**:
Herbalism worked during 1-75, but at 75-150 all herbs are now coming up as "invalid target".
**Explain how you expect it work**:
I should be able to harvest herbs and gain skill points when appropriate.
**Steps to reproduce the problem**:

1. Get herb 1-75 from stormwind trainer as a human
2. advance it to 75-150
(I have tried clearing cache, relogging, and restarting)

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7054

**Comment by Korserva** [comment]
I dropped Journeyman, relearned Apprentice, and now it too is not working.

**Comment by Redrian-Valhalla** [comment]
Our developers are aware of the issue and they're working right now to solve it as soon as possible.

**Comment by Korserva** [comment]
Thank you for the info Redrian.  I was trying to repair, repatch, etc.  Guess it just means more leveling focus time.  :)

**Comment by EldritchIHC** [comment]
Fix warlock plz xD
