### ISSUE TITLE
Chaos Damage from Fel Rush and Chaos Strike

### ISSUE THREAD

**Issue by Redrian-Valhalla** [Valhalla-Gaming/Tracker#7082]
**Describe the issue you're having**:
Fel Rush and Chaos Strike's damage gets reduced by armor rating.
**Explain how you expect it work**:
They both deal chaos damage, chaos damage is not affected by armor rating in any way unless the target has 100% resistance to every magic school.
**Steps to reproduce the problem**:

1. Cast fel rush on a 110 dummy
2. notice the damage being almost half as it should.
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by mikonameton** [comment]
no this is not true

**Comment by mikonameton** [comment]
link give me a link from wow head

**Comment by Moustachos** [comment]
This is true and I incorrectly closed the previous issue.

Chaos damage shouldn't be affected by armor or any single resistance, see:
> http://wow.gamepedia.com/Chaos_(spell_school)

**Comment by Moustachos** [comment]
Ref #5979
