### ISSUE TITLE
Demon hunter - Soul Fragments

### ISSUE THREAD

**Issue by mikonameton** [Valhalla-Gaming/Tracker#7085]
**Describe the issue you're having**:

**Explain how you expect it work**:

**Steps to reproduce the problem**:
1. soul Fragments will disappear in combat on ground in 3sec  before u consume them whit spell soul cleave. after 3 sec or 4 sec u cant see any Fragments  around u in combat with pvp (if u have 2 or 3 or more soul Fragments  when you use one of them whitout use the soul cleave to healling . another soul Fragments  will be disappear in combat sometimes ) this is a huge problem for veng
2. that Fragments must be  around u until u consume them coz in this case u will be lost of them by moving on of them 
3. soul Fragments must be around you (when u move on one of them ) the others must be untill u use them or move on them  (every soul Fragments  for himself )

**Links to Wowhead, YouTube, etc**:

**Comment by Nienz** [comment]
i can add that the talent: Fracture dont proc 2x lesser fragments but instead 2x Soul fragments that heals for 300k+ each

**Comment by Moustachos** [comment]
Ref #5979
