### ISSUE TITLE
buuged demon hunter in hunter zone 

### ISSUE THREAD

**Issue by monsterblood** [Valhalla-Gaming/Tracker#7086]
**Describe the issue you're having**:
im blocked in hunter zone
**Explain how you expect it work**:
i use herathtone unstuck and unstuck site and dont working
**Steps to reproduce the problem**:
i finish all quest in hunter zone but i cant 
1. pls 1 gm teleport me in ogrimmar 
2. im bugged 3 day ago
3.

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
You had to set your hearthstone out of Dalaran once you finished the DH quest chain, contact a GM and ask explain him your issue.

**Comment by monsterblood** [comment]
1 name a gm plss

**Comment by Redrian-Valhalla** [comment]
Pyromanic, Seregruth or Warjakh.

**Comment by monsterblood** [comment]
isn-t online :(( ahhh

**Comment by monsterblood** [comment]
man you know other gm pls?

**Comment by Redrian-Valhalla** [comment]
You can contact the ones I mentioned by forum PM.

**Comment by monsterblood** [comment]
aaaa im new in this game 
you can say a name one gm in game pls?
