### ISSUE TITLE
Gnome Hunter error

### ISSUE THREAD

**Issue by sgtlex** [Valhalla-Gaming/Tracker#7088]
**Describe the issue you're having**:Trying to create a gnome hunter gives an error

**Explain how you expect it work**:Try creating a gnome hunter then it gives Error Creating Character. Tried with male and female, always the same out come.

**Steps to reproduce the problem**:

1. Just try creating a gnome hunter
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/5948
