### ISSUE TITLE
Fel Rush fails

### ISSUE THREAD

**Issue by Redrian-Valhalla** [Valhalla-Gaming/Tracker#7089]
**Describe the issue you're having**:
Using Fel Rush in air teleports the player to the original position.
**Explain how you expect it work**:
I expect to land where Fel Rush's momentum ends.

**Comment by hellraiserz** [comment]
using felrush still DC's patch fail

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7090

**Comment by Moustachos** [comment]
Should be fixed on next update.
