### ISSUE TITLE
Disturbance at Umbrafen Lake

### ISSUE THREAD

**Issue by GeneralCaveman** [Valhalla-Gaming/Tracker#709]
http://www.wowhead.com/quest=9716/disturbance-at-umbrafen-lake

Arriving at the marked location does not complete the objective.

**Comment by Guybrush-Hellscream** [comment]
Here's what happened for me : 
1 - I arrive at the location and i see a yellow sentence that tells me that i complete the objective
2 - But when i look at my quest log, nothing is completed
3 - I was about to abandon it but when i spoke to Ysiel Windsinger, the NPC that gives you that quest, i could return it to here and finish it.

So in other words, it doesn't appear finished but it is in reality.

**Comment by Cidragon** [comment]
This is working now :)
