### ISSUE TITLE
[Spell][Legion][Warlock][Destruction] Shadowburn

### ISSUE THREAD

**Issue by Tromend** [Valhalla-Gaming/Tracker#7092]
**Describe the issue you're having**:

Shadowburn applies Debuff correctly, but does not return 2 Soul Shards when target dies with said Debuff still on.

**Explain how you expect it work**:

Shadowburn is supposed to return 2 Soul Shards whenever a target that has the "Shadowburn" Debuff dies.

**Steps to reproduce the problem**:
1. Apply Shadowburn to an enemy.
2. Kill it with the Debuff still on.

**Links to Wowhead, YouTube, etc**:

http://www.wowhead.com/spell=17877/shadowburn

**Comment by Tromend** [comment]
Also Shadowburn is applying [Eradication](http://www.wowhead.com/spell=196412/eradication) from time to time, and it shouldn't do that.

**Comment by Moustachos** [comment]
Ref #5979
