### ISSUE TITLE
Pandaren monk first quest doesnt work

### ISSUE THREAD

**Issue by priestgodgift** [Valhalla-Gaming/Tracker#7094]
**Describe the issue you're having**:
Need to loot trainees handwraps to proceed and weapon stand doesnt provide them
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6032
