### ISSUE TITLE
eye of acheron (ebon hold) movement problem

### ISSUE THREAD

**Issue by arkrazzha** [Valhalla-Gaming/Tracker#7096]
eye of acheron in ebon hold movement problem

need accept the quest for dks
(dead come from on high)

right click on eye of acheron and try to move down to complete the quest

**Comment by kjelt** [comment]
any wowhead links?

use of issue template makes it a lot of easier to read.

**Comment by DeathByDuke** [comment]
Death Knight starting zone is heavily bugged, I have already reported it previously, as had others. Currently you cannot complete the full questline, and get the mount nor use a gryphon to get down to Death's Beach #6515 #7000

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6515
