### ISSUE TITLE
Observing the Sporelings

### ISSUE THREAD

**Issue by GeneralCaveman** [Valhalla-Gaming/Tracker#711]
http://www.wowhead.com/quest=9701/observing-the-sporelings

Going to the place marked on the map does not trigger the objective for this quest.

**Comment by Guybrush-Hellscream** [comment]
Same problem as #709 and #710, look at my anwsers.
![wowscrnshot_090215_164450](https://cloud.githubusercontent.com/assets/13908354/9634459/1e4d5600-5192-11e5-80ae-017d837fa46e.jpg)

**Comment by Cidragon** [comment]
This is working now :)
