### ISSUE TITLE
Prot paladin Avenger Shield

### ISSUE THREAD

**Issue by Nightcap** [Valhalla-Gaming/Tracker#7115]
**Describe the issue you're having**:When using Avenger Shield on large packs of enemies, the game freezes for 5-10 seconds

**Explain how you expect it work**: Game shouldnt freeze

**Steps to reproduce the problem**: Pull large groups of monsters and hit them with avenger shield

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
That's a performance issue and it depends entirely on your own machine.

**Comment by Nightcap** [comment]
Incorrect, My machine is way over the top. After more testing is seems to only happen in Shadowmoon Valley

**Comment by Redrian-Valhalla** [comment]
I need more people to report the same.
