### ISSUE TITLE
Vengeance DH Parry

### ISSUE THREAD

**Issue by zsolti16** [Valhalla-Gaming/Tracker#7116]
**Describe the issue you're having**:
My VDH does not have parry, never parrys an attack, not even with demon spikes on!
**Explain how you expect it work**:
Should parry incoming attacks sometimes
**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by mikonameton** [comment]
yea

**Comment by zsolti16** [comment]
This needs to be fixed, its important

**Comment by zsolti16** [comment]
Still waiting for it

**Comment by Moustachos** [comment]
Ref #5979
