### ISSUE TITLE
Paladin Avenger shield

### ISSUE THREAD

**Issue by Nightcap** [Valhalla-Gaming/Tracker#7117]
**Describe the issue you're having**: Avenger shield temporarily freezes the game when pulling lots of mobs with is in Shadowmoon Valley (WoD) -With a Top end gaming machine-

**Explain how you expect it work**: No freezing

**Steps to reproduce the problem**: Pull many mobs in SMV (WoD) hitting them with Avenger shield.

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
I made someone else test it on packs of mobs in SV, there was no freeze.
