### ISSUE TITLE
Metamorphosis VDH

### ISSUE THREAD

**Issue by zsolti16** [Valhalla-Gaming/Tracker#7119]
**Describe the issue you're having**:
It does not increase the current health of the player only the max health
**Explain how you expect it work**:
It should heal u for 30% of max hp
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=187827/metamorphosis

**Comment by Moustachos** [comment]
It's not supposed to actually heal you for 30% of max health.

What it's supposed to do it to maintain the health percentage you add before casting Metamorphosis, for example if you were at 70% HP before using it, you'll still be at 70% with Metamorphosis.

And that part works just fine.

**Comment by Moustachos** [comment]
Ref #5979
