### ISSUE TITLE
Ice lance bug

### ISSUE THREAD

**Issue by alixandero** [Valhalla-Gaming/Tracker#7127]
**Describe the issue you're having**:

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. Ice lance does no damage but the animation is working
2. Ice lance must do damage
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6014

**Comment by Moustachos** [comment]
Ref #5979
