### ISSUE TITLE
Frost Mage Frozen Orb

### ISSUE THREAD

**Issue by Taurial** [Valhalla-Gaming/Tracker#7129]
**Describe the issue you're having**:
No Animation
No Damage

**Links to Wowhead, YouTube, etc**:
[http://www.wowhead.com/spell=84714/frozen-orb](url)

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6875

**Comment by Moustachos** [comment]
Ref #5979
