### ISSUE TITLE
Stuck ingame

### ISSUE THREAD

**Issue by kjelt** [Valhalla-Gaming/Tracker#7131]
**Describe the issue you're having**:
My character Beldeh, demon hunter is a ghost. I can not find a graveyard with a working ghosthealer. Unstuck feature of website has not worked and is now stucked itself. No GM available

**Explain how you expect it work**:
Unstuck should unstuck and revive me or any graveyard should have a working ghosthealer.
Maybe more online time of game masters overall and not only a few hours a day only one.

**Comment by Redrian-Valhalla** [comment]
Please contact a GM on Discord or on the forum.
