### ISSUE TITLE
Food and potions

### ISSUE THREAD

**Issue by Danielo96** [Valhalla-Gaming/Tracker#7135]
**Describe the issue you're having**: Food and potions have no effect

**Explain how you expect it work**: food should restore health and potions health/mana or other miscellanneous effects

**Steps to reproduce the problem**:

1. Eat at low health
2. drink potions
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6375
