### ISSUE TITLE
warrior bugs

### ISSUE THREAD

**Issue by Adnan994** [Valhalla-Gaming/Tracker#7136]
Intercept doesn't work.
Heroic Leap doesn't reset Taunt cooldown.
No deffensive cooldown usable while Neltharion's Fury is up.
Heavy Repercussions doesn't have effect.
Vengance haves no effect.
Bounding strikes do reduce cooldown of Heroic Leap howerver it doesn't provide movement speed after using Heroic Leap.
Ultimatum haves no effect.
Devastate never resets cooldown of Shield Slam.
Parries and dodges do not reset Revenge.
Shield Block does not increase damage of Shield Slam.
Focused Rage goes of with every spell used.
Ravager does not work.
Ignore Pain absorbs 700 damage (max)
Demoralizing Shout does not reduce the damage u recive.

**Comment by Redrian-Valhalla** [comment]
Please make individual reports for each issue.
