### ISSUE TITLE
felrush still not fixed

### ISSUE THREAD

**Issue by hellraiserz** [Valhalla-Gaming/Tracker#7138]
**Describe the issue you're having**:
after 3 patches felrush is still not fixed still not moving forward and DC's in air
**Explain how you expect it work**:
moves forward and and wont DC you in air
**Steps to reproduce the problem**:

1. using felrush on air
2. 
3. 

**Links to Wowhead, YouTube, **etc**:**

**Comment by Redrian-Valhalla** [comment]
Just tested it, fel rush works on both ground and air.
