### ISSUE TITLE
Warlock : Immolation Aura

### ISSUE THREAD

**Issue by eugenajazaj** [Valhalla-Gaming/Tracker#714]
When Warlock goes Metamorphosis (Demon Mode) Hellfire turns to Immolation Aura spell.
It should do damage but it doesn't .http://www.wowhead.com/spell=140720/immolation-aura

**Comment by Traveler-Valhalla** [comment]
obsolete issue

**Comment by Traveler-Valhalla** [comment]
i think its no longer an issue
