### ISSUE TITLE
VDH Artifact trait

### ISSUE THREAD

**Issue by zsolti16** [Valhalla-Gaming/Tracker#7142]
**Describe the issue you're having**:
The most recent fix to the artifact trait "fueled by pain" have a bug, every time it procs it triggers cooldown on metamorphosis, and it should not do that!
**Explain how you expect it work**:
This trait should not make metamorphosis go on cooldown
**Steps to reproduce the problem**:
No idea why, somebody closed the same issue i was describing.
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=213017/fueled-by-pain   http://www.wowhead.com/spell=187827/metamorphosis

**Comment by Moustachos** [comment]
Will be fixed on next update, that's why I closed the other issue.

**Comment by Moustachos** [comment]
Ref #5979
