### ISSUE TITLE
reached 100k AP still cant buy the belt

### ISSUE THREAD

**Issue by hellraiserz** [Valhalla-Gaming/Tracker#7145]
**Describe the issue you're having**:
I've reached 100k AP i still can't buy the belt item that requires 100k AP at class hall vendor
**Explain how you expect it work**:
If you reach 100k AP you can buy the item

**Steps to reproduce the problem**:

1. reached 100k AP still can't buy it
2. after i click buy its says "item is locked"
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
Already reported: https://github.com/Valhalla-Gaming/Tracker/issues/6737
