### ISSUE TITLE
Shattered Souls Bug

### ISSUE THREAD

**Issue by Ihugyou** [Valhalla-Gaming/Tracker#7152]
**Describe the issue you're having**: The passive spell Shattered Souls got bugged doesn't work for both spec vengeance and havoc.

Explain how you expect it work: Vengeance Shattered Souls
 says : Killing a target will sometimes shatter their soul, leaving a Soul Fragment behind for 20 sec.

The Soul Fragment will be consumed when you approach it, healing you for (2125% of Attack power) health.

Consuming a Demon's soul will grant you 20% increased damage for 15 sec.

Havoc :Killing an enemy sometimes creates a Soul Fragment that is consumed when you approach it, healing you for 25% of maximum health.

If the Soul Fragment came from a Demon, you will deal 20% increased damage for 15 sec.

The problem is we don't get any soul fragments at all i was online today for 4 H killing,farming,etc not even one single mob drop the soul fragment. I think it got bugged from the last update i hope u check it out and fix it.

Wowhead: http://www.wowhead.com/spell=204254/shattered-souls Vengeance
                  http://www.wowhead.com/spell=178940/shattered-souls Havoc

**Comment by Redrian-Valhalla** [comment]
Just tested it on both spects, works as intended.

**Comment by Ihugyou** [comment]
It doesn t work on low lvl mop and it should work go try a lower lvl zone
