### ISSUE TITLE
Shattered Souls does not work on low lvls

### ISSUE THREAD

**Issue by Ihugyou** [Valhalla-Gaming/Tracker#7153]
The first post i made was kinda wrong the Shattered Souls work on the broken island
but go to a lower lvl zone like Pandaria or draenor i am atm in firelands raid not even one mob drop the souls and when i farm yesterday like 90 % of the mobs drop soul fragments go test it in a lower lvl zone not on the broken island and don t close my post if you didn t research the spells like u should do !!

P.S i play here over 2 weeks so i am 100000000000 % sure that Shattered Souls-Soul Fragments droped from lower lvl mobs ....

**Comment by Redrian-Valhalla** [comment]
Again, it works as intended(otherwise it would be OP and nonsense), also I really doubt killing low level npcs spawned them, I play DH and killing lower level npcs never spawned a single soul.

**Comment by Moustachos** [comment]
Shattered Souls (and similar talents) only triggers its effect upon killing a target that yields xp or honor.

So killing too low level targets (or targets not supposed to grant any xp) won't trigger it.
