### ISSUE TITLE
Soul Cleave visual bug-buff bug

### ISSUE THREAD

**Issue by ghost** [Valhalla-Gaming/Tracker#7154]
Ok i was wrong with the shatter soul i saw the changelog and found Shear will now spawn Lesser Soul Fragments (instead of Soul Fragments) and provide less healing when i kill low lvl mobs i got soul fragments and that why i was thiking that low lvl should drop them that was my bad and sry about the posts. 

What about this Soul Cleave doesn t show the number of near souls and i don t see the buff in the top of the corner the purple ball with numbers. Soul Cleave should show the number of soul fragments and lesser soul fragments when they are near you and u should get a buff in the top of the corner.

Here vidieo https://www.youtube.com/watch?v=rRY-iGecIlg (4:20 min) look at spell bar look at Soul Cleave it shows the numbers of the souls and the buff u can see purple ball with numbers.

**Comment by mikonameton** [comment]
mo its fixed and show to me even the first day i play with dh

**Comment by Ihugyou** [comment]
@mikonameton  you still a idiot its not fix here is screen shot from today http://imgur.com/a/Wchvn

**Comment by Ihugyou** [comment]
I am not the only one with the visual bug  http://imgur.com/a/CbWCD

**Comment by Ihugyou** [comment]
Update it seems that the buff sometimes work and sometimes not here are SS http://imgur.com/a/zfbYq
On the frist two you can see i don t have the buff but on the last one i got them

**Comment by Moustachos** [comment]
Ref #5979
