### ISSUE TITLE
Demon Hunter Fel Rush

### ISSUE THREAD

**Issue by PortRoyale153** [Valhalla-Gaming/Tracker#7155]
**Describe the issue you're having**:

as a demon hunter i have a speel "Fel Rush" but sometimes when i use it i get stuck in air and then it kick me of the server i dont know if its just me having this problem maybe other people have this problem too

**Explain how you expect it work**:

me and other users should be happy when it will be working (sorry for bad english)

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
I'm currently investigating the issue to create an accurate report once I have all the information to make that happen, for now please avoid using Fel Rush twice in a row while in air.
