### ISSUE TITLE
Shattered Souls DMG buff in Vengeance spec bug added screen shots

### ISSUE THREAD

**Issue by Ihugyou** [Valhalla-Gaming/Tracker#7160]
Shattered Souls should give you Consuming a Demon's soul will grant you 20% increased damage for 15 sec. i am killing atm 110 lvl demons on the broken island in azsuna (Faronaar) and i don t get the 20 % dmg buff from the soul fragments its only bugged for the Vengeance spec  pls go test it . I try it in Havoc and i get the buff so it works for Havoc but not for Vengeance spec.

http://www.wowhead.com/spell=204254/shattered-souls

**Comment by Redrian-Valhalla** [comment]
I'll check it later.

**Comment by Ihugyou** [comment]
I found out that for Havoc Shattered Souls procs on humans,beast dragons ... so u get dmg buff for killing non demons you can test it to just kill a random non demon npc on the broken island that need to be fix to the buff should only be from demons

**Comment by Ihugyou** [comment]
Screen shot on havoc i killed a beast and got dmg buff http://imgur.com/a/dHL0Y it only should give dmg buff on demons.

Screen shot Vengeance  i killed a demon and i didn t got the dmg buff Vengeance

**Comment by Nienz** [comment]
well im Vengeance on mine and i do get the dmg buff but on the heal part its different i cant tell if its a bug or not heres how it looks like [img]http://i.imgur.com/RaQcDue.jpg[/img]

**Comment by Ihugyou** [comment]
I killed demons and i don t get the buff http://imgur.com/a/84G5p here you can see that i consume soul from a demon on the Broken Isles

**Comment by Ihugyou** [comment]
Update still no dmg buff
