### ISSUE TITLE
Feel Rush Distance travel bug

### ISSUE THREAD

**Issue by Ihugyou** [Valhalla-Gaming/Tracker#7161]
While  holding W or moving forward and using fusing feel rush in the air u travel a long distance its too long you can easy test it find a flat place then use Double Jump then press feel rush you will see that u will fly short/move short distance forward, then try it again use Double Jump while in air pres W or what bind u use to move forwards and use feel rush (while  holding your W bind) you will see that u travel/fly a very very long distance.
I think its bugged cuz if this is how it should be Dh will cap flags in bgs in a very fast time.

Retail vidoe https://www.youtube.com/watch?v=NdOgc9hAAzU  3:00 min and https://www.youtube.com/watch?v=Q9qUkaAhxGc 4:15 min you can see how much they travel.

**Comment by Ihugyou** [comment]
This got fix last update close this topic or mark it fixed.

**Comment by Moustachos** [comment]
Ref #5979
