### ISSUE TITLE
First quest and breathe in Vashjir

### ISSUE THREAD

**Issue by acermat** [Valhalla-Gaming/Tracker#7166]
**Describe the issue you're having**:
I can't do the first quest in Vashjir, the kraken doesn't attack the boat. And after, I made the quest for unlimited breathe but it doesn't work.

**Explain how you expect it work**:

**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Cidragon** [comment]
which quest?
