### ISSUE TITLE
Death Knight Quest

### ISSUE THREAD

**Issue by PortRoyale153** [Valhalla-Gaming/Tracker#7169]
**Describe the issue you're having**:

im currently having issue with DK quest "Death Comes From On High" 
when i travel to new avalon forge etc. it dont counts as analyzed 

**Explain how you expect it work**:

Add something like analyzer spell to Eye Of Acherus

**Links to Wowhead, YouTube, etc**:

WoW Head : 
http://www.wowhead.com/quest=12641/death-comes-from-on-high
Youtube : 
https://www.youtube.com/watch?v=9V8KWMMa0aU

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6501
