### ISSUE TITLE
Paladin

### ISSUE THREAD

**Issue by Paloading** [Valhalla-Gaming/Tracker#7171]
Hi my name is Paloading and i´m here to report Ret paladins bugged spells
Divine Steed, That should summons a paladin mount during combat increasing movement  speed.http://www.wowhead.com/spell=190784/divine-steed

Divine Storm http://www.wowhead.com/spell=53385/divine-storm

All Greater Blessing

Final verdict http://www.wowhead.com/spell=157048/final-verdict

Templar´s verdict http://www.wowhead.com/spell=85256/templars-verdict

Judgement Just hit 1 target http://www.wowhead.com/spell=20271/judgment

Consecration http://www.wowhead.com/spell=26573/consecration

blinding light http://www.wowhead.com/spell=115750/blinding-light

**Comment by Redrian-Valhalla** [comment]
Hello, most of those spells are already reported, please avoid posting more than one issue in the same report, thanks.
