### ISSUE TITLE
Stonebark(Restoration)

### ISSUE THREAD

**Issue by Milofajjour** [Valhalla-Gaming/Tracker#7172]
**Describe the issue you're having**:
Stonebark talent for resto druid is only reducing the cooldown of ironbark and not increasing the hots by 20% actually its not even increasing it by 1%.
**Explain how you expect it work**:
My healing over time effects should increase by 20%

**Comment by Moustachos** [comment]
Both effects work just fine.

**Comment by Moustachos** [comment]
Ref #5979
