### ISSUE TITLE
Blur dodge and Demon Spikes parry added screen shots

### ISSUE THREAD

**Issue by ghost** [Valhalla-Gaming/Tracker#7181]
When i use Blur and look at my character stats it doesn't show me 50% dodge in the stats
http://www.wowhead.com/spell=198589/blur#reward-from-q
When i use Demon Spikes and look at my character stats  it doesn't show me that my parry is 20 % or increased my parry stay the same 
http://www.wowhead.com/spell=203720/demon-spikes

So i think that blur and demon spikes are bugged and don t give dodge or parry.

Why do i think its bugged cuz when i am in Metamorphosis with the talent Soul Rending picked it shows on my character stats 100% Leech in dps spec and 50% Leech in tank spec while i am in Metamorphosis.
So it should show me 50 % dodge and 20 % more parry when i use blur or demon spikes.

 You should check it cuz if the spells don t work Dh los big def cds.

**Comment by Ihugyou** [comment]
Blur Screen shot http://imgur.com/a/e0CVb

With out demon spikes my stats http://imgur.com/a/fB3yq

Wtih demon spikes http://imgur.com/a/wpW8f 

 Same stas i don t get parry

**Comment by LordYawgmoth** [comment]
u dont get parry cause u dont even have a parry stat in ur window

**Comment by Ihugyou** [comment]
@LordYawgmoth  You don t have Leech in your stats to but when i use Metamorphosis and look at my character i see this http://imgur.com/a/DbIVL you can see i get 50 % leech as stats so i think it should be the same for Blur and Demon spikes when i use them and open my character screen i should see 50 % dodge or 20 % parry.

**Comment by Moustachos** [comment]
No bug with these spells (as of current version).

Dodge percent provided by Blur doen't show up in character stats but that's intended (same on retail).

Parry percent provided by Demon Spikes properly shows up in character stats.

**Comment by Moustachos** [comment]
Ref #5979
