### ISSUE TITLE
Chaos Strike crit refund bug Added screen shot to prove the bug

### ISSUE THREAD

**Issue by ghost** [Valhalla-Gaming/Tracker#7183]
The fury refund only works when the main hand crits and never off hand for explain 

Chaos Strike hits for x (critical)
Chaos Strike hits for x 
gives fury but 

Chaos Strike hits for x
Chaos Strike hits for x (critical)
doesn t give fury 

so it gives fury on main hand crits but not on off hands crits.

You can test it easy just go hit a dummy and watch your combat log and fury bar.

Link http://www.wowhead.com/spell=162794/chaos-strike

**Comment by Ihugyou** [comment]
Here is a screen shot of the bug http://imgur.com/dMHXEuK this SS shows main hand crit and it gives back 20 fury.
This shows off hand crit and it doesn t give back 20 fury http://imgur.com/a/Wchvn

chaos strike cost 40 fury i use it on 100 fury so main hand gives back 20 fury that u see on the first SS i have 80 fury but on the off hand it doesn t give fury that s why u see i have 60 fury

**Comment by Moustachos** [comment]
Ref #5979
