### ISSUE TITLE
Crafted Profession Mounts.

### ISSUE THREAD

**Issue by LordLupusDei** [Valhalla-Gaming/Tracker#7186]
On my main Character (orc Warrior Fury) got engeneering on lvl 405 
I created  Fly machine (Mount) but I cant use it like I never got Engeneering or got some low lvl on engeneering but I got 405 please do  something about it.

**Comment by Redrian-Valhalla** [comment]
What's the mount?

**Comment by GM-Pyromanic** [comment]
#6741
