### ISSUE TITLE
DH Vengeance talents bug

### ISSUE THREAD

**Issue by ghost** [Valhalla-Gaming/Tracker#7187]
So vengeance spec works great too but i found some bugs.

--

- [ ] lvl 99 Razor Spikes http://www.wowhead.com/spell=209400/razor-spikes

While Demon Spikes is active, you deal 20% increased Physical damage and your melee attacks snare targets by 50% for 6 sec. the talent works great the bug is when you use demon spikes you slow your target but even when demon spikes fade away and you keep hitting the target with out demon spikes you will refresh the slow so you can keep the target forever in a slow if you keep hitting it. test it for yourself.

- [ ] lvl 104 Feed the demon http://www.wowhead.com/spell=218612/feed-the-demon

Consuming a Soul Fragment reduces the remaining cooldown of Demon Spikes by 1 sec.
the bug is it seems it works with Lesser Soul Fragments.

- [x] lvl 104 Fracture http://www.wowhead.com/spell=209795/fracture

Brutally slam your target for (378% + 756%) Physical damage, and shatter two Lesser Soul Fragments from them. 

The bug is it shatter two Soul fragments not lesser soul fragments.

--

Two talents that i could not test are Blade turning cuz from what i saw in the report parry doesn t work on DH and Nether Bond bcuz i don t have any friends (q.q)

The rest of the talents work fine and very good.

**Comment by Redrian-Valhalla** [comment]
Please try to make a single report for each issue.

**Comment by Ihugyou** [comment]
You mean that i should report 1 by 1 of the talents like make 1 post for feed the demon then make new topic about  etc i was thinking it would be this way easyer for you sorry :(

**Comment by Redrian-Valhalla** [comment]
I'm sorry but it would be easier for us to have one post for each.

**Comment by Ihugyou** [comment]
Should i report it again 1 by 1 ? or i can do its not a big problem

**Comment by Redrian-Valhalla** [comment]
It's okay this time.

**Comment by Guybrush-VR** [comment]
Updated your comment so that we can check what has been fixed.

**Comment by Moustachos** [comment]
For Feed the Demon: not a bug, Lesser Soul Fragments can trigger it.

**Comment by Moustachos** [comment]
Ref #5979
