### ISSUE TITLE
[Priest][Disc] Divine Star

### ISSUE THREAD

**Issue by Aprophys** [Valhalla-Gaming/Tracker#7190]
**Describe the issue you're having**:
If u activate / use the talent Divine star nothing happends only the character move animation.

**Explain how you expect it work**:

Fires a Divine Star forward 24 yds, healing allies in its path for (90% of Spell power) and dealing (145% of Spell power) Holy damage to enemies. After reaching its destination, the Divine Star returns to you, healing allies and damaging enemies in its path again.

**Steps to reproduce the problem**:

1. Learned it un learned and relearned it
2. Relogged
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=110744/divine-star

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7105
