### ISSUE TITLE
Demon hunter vengeance

### ISSUE THREAD

**Issue by gondin** [Valhalla-Gaming/Tracker#7191]
**Describe the issue you're having**:

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. Soul Fragments must be invisible for allies and enemys 
2. only dh  must can see that on ground not another players even demon hunters (hord or alliance )
only the original caster must see the soul fragments  (every souls on ground for their own )
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
Please stop describing the problem in the "Steps to reproduce the problem:", use the template correctly.

**Comment by LordYawgmoth** [comment]
what does this have to do with vengeance? it s obivously a problem of the passive ability: shattered souls and others creating soul shards
