### ISSUE TITLE
[Monk][Windwalker][Trait] Healing Winds

### ISSUE THREAD

**Issue by Bombrick** [Valhalla-Gaming/Tracker#7192]
**Describe the issue you're having**:
Healing winds does NOT heal you for (10/15/20)% Of your max health over time when you use Transcedence : Transfer
**Explain how you expect it work**:
Healing winds SHOULD heal you for (10/15/20)% Of your max health over time if used Transcedence : Transfer
**Steps to reproduce the problem**:

1. Learn Healing winds Trait
2. Cast Transcedence somewhere
3. Cast Transcedence : Transfer

**Comment by forstix** [comment]
http://www.wowhead.com/spell=195380/healing-winds

**Comment by Moustachos** [comment]
Ref #5979
