### ISSUE TITLE
[Monk] Transcedence

### ISSUE THREAD

**Issue by Bombrick** [Valhalla-Gaming/Tracker#7193]
**Describe the issue you're having**:
You can spam Transcedence and have unlimited spirits each of them last 15 min
**Explain how you expect it work**:
When you have a spirit active by Transcedence , and you use Transcedence a new spirit will appear replacing the previous one.
**Steps to reproduce the problem**:

1. Go somewhere
2. Cast Transcedence Multiple times
3. See the results

**Comment by forstix** [comment]
http://www.wowhead.com/spell=101643/transcendence#changelog

**Comment by Moustachos** [comment]
Ref #5979
