### ISSUE TITLE
Bloodlet hotfix

### ISSUE THREAD

**Issue by Ihugyou** [Valhalla-Gaming/Tracker#7195]
Bloodlet (Talent) now deals 150% of initial Throw Glaive damage.

the talents atm on the server say 200 % it should be 150 %
WoWhead http://www.wowhead.com/spell=206473/bloodlet
retail https://worldofwarcraft.com/en-us/news/20252902/hotfixes-october-3 scroll down to september 26

P.S there hotfix to other classes to you should read and fix them too

**Comment by Redrian-Valhalla** [comment]
We're not on the 7.1

**Comment by Ihugyou** [comment]
dude this is not 7.1 its 7.0.3 retail is on 7.0.3 dude the hotfix are on 7.0.3 patch ..... read link .................
