### ISSUE TITLE
Fel Mastery hotfix

### ISSUE THREAD

**Issue by Ihugyou** [Valhalla-Gaming/Tracker#7196]
Fel Mastery (Talent) damage bonus to Fel Rush reduced to 30%.

atm on the server its 50 % should be 30 % 

wowhead http://www.wowhead.com/spell=192939/fel-mastery

Increases Fel Rush damage by 30%

retail https://worldofwarcraft.com/en-us/news/20252902/hotfixes-october-3 scroll down to september 23

**Comment by Redrian-Valhalla** [comment]
The server is not running 7.1 yet.

**Comment by Ihugyou** [comment]
dude this is not 7.1 its 7.0.3 retail is on 7.0.3 dude the hotfix are on 7.0.3 patch ..... read link .................
