### ISSUE TITLE
Vengeance mastery hotfix

### ISSUE THREAD

**Issue by Ihugyou** [Valhalla-Gaming/Tracker#7197]
Mastery now provides 50% less damage reduction per point. 

this effects only the dmg reduc from mastery not the att power so don t bug it .....

retail https://worldofwarcraft.com/en-us/news/20252902/hotfixes-october-3 september 23

**Comment by Redrian-Valhalla** [comment]
We're not on the 7.1

**Comment by Ihugyou** [comment]
dude this is not 7.1 its 7.0.3 retail is on 7.0.3 dude the hotfix are on 7.0.3 patch ..... read link .................
