### ISSUE TITLE
DH havoc fellrush still broken

### ISSUE THREAD

**Issue by hellraiserz** [Valhalla-Gaming/Tracker#7203]
**Describe the issue you're having**:
when i use fel rush in air still DC after the 2 patches
**Explain how you expect it work**:
when using felrush on air you dont DC
**Steps to reproduce the problem**:
1. use felrush on air
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
Try to relog, use fel rush on the ground and tell me if it disconnects you again by using it in air.

**Comment by Ihugyou** [comment]
It stills some times DC you and if you use it on the ground it doesn t even more you farwar is just stucks you in the place ..... check it

**Comment by hellraiserz** [comment]
yep still DC's always when use in air if not you are stuck in that area unable to move forward

**Comment by SweexMeex** [comment]
When will this be fixed?

**Comment by hellraiserz** [comment]
FYI felrush on air still broken especially on double jumps

**Comment by Redrian-Valhalla** [comment]
We know, but at least the chance of getting disconnected is lower now.

**Comment by hellraiserz** [comment]
i hope this will be fix

**Comment by Moustachos** [comment]
Ref #5979
