### ISSUE TITLE
Class-Hunter Bugs and Race-Draenei [Gift of Naaru] Bug

### ISSUE THREAD

**Issue by ProTaMaka** [Valhalla-Gaming/Tracker#7205]
Race-Draenei bug

Tested on my hunter with 976k HP! 20% form that is 194k HP! Using [Gift of Naaru] on my self Should heal me that much in 5 seconds! Instead it healed me only 3426 five times and last time 969 hp resulting in max heal being only 18099 HP! Healing from [Gift of Naaru] Should heal by little more then times 10 current healing!

Class-Hunter
Marksmanship specialization!

[Hunter's Mark] stays on target even after you use [Marked Shot] on them, it should be removed after [Marked Shot] is fired, fixing visual bug of not being able to use [Marked Shot] on target even when they have [Hunter's Mark] on them!

[Marked Shot] is supposed to give [Vulnerable] AFTER it does damage! It is not supposed to Buff damage from FIRST fired [Marked Shot], resulting in [Marked shot] getting increased damage by 150% at start if you are using [Patient Sniper] talent.

[Patient Sniper] Is stacking it self if you fire more then 1 [Marked Shot] on target going up to 3. Problem here is if You are NOT using [Patient Sniper], [Vulnerable] should stack 3 times each time giving 25% increased damage! After you take [Patient Sniper] talent you can stack it 3 time resulting in giving increased damage to [Marked Shot] and [Aimed shot] up to 450% damage! It should not happen! [Patient Sniper] talent says that it can't stack anymore!

If you are casting [Aimed Shot] and [Lock and Load] is activated, you lose one instant [Aimed Shot] because you were already casting it when [Lock and Load] activated!

Damage from [Aimed Shot] without [Vulnerable] is 50% reduced!

[True Shot] when activated is supposed to give every [Arcane Shot] and [Multi-Shot] ability to Apply [Hunter's Mark]! It doesn't! Abilities are only Shining! Using [Arcane Shot] or [Multi-Shot] will only result in doing damage, not applying [Hunter's Mark]!

[Aspect of the Turtle] is not working at all! Damage is not reduced, you can attack while it is activated, attacks are not deflected and [Healing Shell] is not activated if you are having that Artifact trait!

[Exhilaration] With normal 50% Heal, also activates [Healing Shell] Artifact trait! It should not happen!

If you have [Mark of the Windrunner] artifact trait, [Windburst] is not applying [Vulnerable] on target after shot!

Artifact train [Legacy of the Windrunners] is not working! No animation of wind arrows nor bonus damage ever happened on [Aimed Shot]!

 [Sentinel] talent doesn't apply [Hunter's Mark] nor to your target nor to other enemies around!

 [True Aim] doesn't apply de-buff on target from first shot!

 [Volley] does 50% less damage and every auto attack doesn't spend 3 focus as it is supposed to do!

 [A Murder of Crows] does 50% less damage!

 [Trick Shot] not working, doesn't give 15% bonus damage to next [Aimed shot] if there are not [Vulnerable] targets! Also doesn't ricochet to other targets!

[Bursting Shot] Doesn't disorient targets hit! Also some mobs can instanly return to their previous position even after being knocked back by [Bursting Shot]

Sorry for a lot of text! 
I hope this helps! With my 15 artifact trait levels this is as far as I can go with testing! Will do testing of other specializations next time!! <3

**Comment by gondin** [comment]
yea hunter damage is bug and this is a bad thing 
no one can kill hunter mark

**Comment by Redrian-Valhalla** [comment]
Multiple issues on the same report are not accepted since they make it harder for our devs to work on what has to be fixed.

**Comment by ProTaMaka** [comment]
I reported every bug for MM hunter that exists, if you cant handle it on same place make more posts for every ability

**Comment by ProTaMaka** [comment]
I'm sorry for a lot of things in one place I will make seperate posts!
