### ISSUE TITLE
Race-Draenei bug [Gift of Naaru]

### ISSUE THREAD

**Issue by ProTaMaka** [Valhalla-Gaming/Tracker#7215]
Tested on my hunter with 976k HP! 20% form that is 194k HP! Using [Gift of Naaru] on my self Should heal me that much in 5 seconds! Instead it healed me only 18099 HP! Healing from [Gift of Naaru] Should heal by little more then times 10 current healing!
I also tested to see if it healed only by normal stamina that hunter has without items, It still didn't heal 20% of HP!

**Comment by Traveler-Valhalla** [comment]
#4153

**Comment by GM-Pyromanic** [comment]
Duplicate report original issue has already be referenced.
