### ISSUE TITLE
Class-Hunter [Aimed Shot] damage

### ISSUE THREAD

**Issue by ProTaMaka** [Valhalla-Gaming/Tracker#7220]
Damage from [Aimed Shot] without [Vulnerable] is 50% reduced!

**Comment by Redrian-Valhalla** [comment]
Actually I believe that aimed shot's damage is still ridiculously reduced, nothing close to the damage it would deal on retail.

**Comment by Moustachos** [comment]
Aimed Shot's damage are a perfect match of tooltip on a target with no armor.

**Comment by Moustachos** [comment]
Ref #5979
