### ISSUE TITLE
Class-Hunter [Volley] bug

### ISSUE THREAD

**Issue by ProTaMaka** [Valhalla-Gaming/Tracker#7228]
[Volley] does 50% less damage and every auto attack doesn't spend 3 focus as it is supposed to do!

**Comment by Moustachos** [comment]
Damage are just fine on a target with no armor (reflecting the tooltip and even more).

The focus cost is indeed bugged though, it will be fixed soon.

**Comment by Moustachos** [comment]
Ref #5979
