### ISSUE TITLE
Draenor profession scroll 

### ISSUE THREAD

**Issue by forstix** [Valhalla-Gaming/Tracker#7237]
**Describe the issue you're having**:
all the dranor profession scroll only give u skill cap to 700

**Explain how you expect it work**:
those scroll should also teach u some recipe depend on the profession 

**Links to Wowhead, YouTube, etc**:
didn't test all of them but i guess it's a problem in all of them (didnt test tailor/enchant)
Draenor Inscription - http://www.wowhead.com/item=111923/draenor-inscription#comments
Draenor Blacksmithing - http://www.wowhead.com/item=115356/draenor-blacksmithing
do i really need to put all of them here...? let me know if i do

**Comment by forstix** [comment]
ty for the high priority redrian :)

**Comment by ProTaMaka** [comment]
I tested tailoring it is same for it too

**Comment by Yeastus** [comment]
The leatherworking scroll has this issue also.

**Comment by Luthienne88** [comment]
Jewelcrafting too.

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/8203
