### ISSUE TITLE
Death Knight Talent: March of the Damned

### ISSUE THREAD

**Issue by llamalama** [Valhalla-Gaming/Tracker#7243]
http://www.wowhead.com/spell=219779/march-of-the-damned

This isn't letting you use Wrath Walk while stunned.

**Comment by Moustachos** [comment]
According to this comment http://www.wowhead.com/spell=219779/march-of-the-damned#comments:id=2469762 this bug also occurs on retail as of 7.1.5.

However, currently Wraith Walk doesn't remove snares either with March of the Damned, I'll fix that part.

**Comment by Moustachos** [comment]
Ref #5979
