### ISSUE TITLE
Bugs regaring Potions & Food/ Roll on Items in Grups

### ISSUE THREAD

**Issue by Drathgar** [Valhalla-Gaming/Tracker#7263]
Hey Guys at Valhalla,
In Addition on how Valhalla runs/works, my friends decided to join your server.
But sadly as we played, we experienced some issues, like that when we take potions etc. we simply don't get healed. The Items were used and we sit down when we ate the items, but with no result.

Another thing that we had to face was the incapability to roll for better items when we were in a group togehter. We have lost some decent Loot because of that. Especially the whole reason why we wanted to start WoW was to play the newest Expansion and to do Raids together.

If you were so kind to fix these above mentioned Issues we would be really happy and enjoy a great time.

Faithfully
Micheal, Ian, Phillip, Pascal, Timo, Laurenz

**Comment by Redrian-Valhalla** [comment]
Hello, these issues have already been reported.
