### ISSUE TITLE
(Warlock Affliction) Agony Spell

### ISSUE THREAD

**Issue by Mooshii** [Valhalla-Gaming/Tracker#7272]
**Describe the issue you're having**:
Agony damage is not scaling right, does not generate soul shards.

**Steps to reproduce the problem**:
1. Use Agony
2. See the total damage after the duration
3. Not giving any soul shards

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=980/agony

**Comment by Moustachos** [comment]
Damage are just fine.

Soul Shards generation is indeed broken though.

**Comment by Moustachos** [comment]
Ref #5979
