### ISSUE TITLE
(Warlock Affliction) Corruption Spell

### ISSUE THREAD

**Issue by Mooshii** [Valhalla-Gaming/Tracker#7273]
**Describe the issue you're having**:
Damage is not scaling right.

**Steps to reproduce the problem**:
1. Use Corruption
2. See the total damage after the full duration

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=172/corruption

**Comment by Moustachos** [comment]
Damage are just fine.

**Comment by Moustachos** [comment]
Ref #5979
