### ISSUE TITLE
(Warlock Affliction) Siphon Life Spell/Talent

### ISSUE THREAD

**Issue by Mooshii** [Valhalla-Gaming/Tracker#7274]
**Describe the issue you're having**:
Siphon life damage is not scaling right

**Steps to reproduce the problem**:

1. Use Siphon Life
2. See the damage after the full duration

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=63106/siphon-life

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6230
