### ISSUE TITLE
(Warlock Affliction) Drain Life Spell

### ISSUE THREAD

**Issue by Mooshii** [Valhalla-Gaming/Tracker#7276]
**Describe the issue you're having**:
Damage is not scaling right.

**Steps to reproduce the problem**:

1. Use drain life
2. See the damage after full duration

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=689/drain-life

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6390
