### ISSUE TITLE
(Warlock Affliction) Seed of Corruption Spell

### ISSUE THREAD

**Issue by Mooshii** [Valhalla-Gaming/Tracker#7277]
**Describe the issue you're having**:
Hits all targets infront of you, while it should only hit 1 enemy. (unless you take Sow the Seeds talent)

**Steps to reproduce the problem**:

1. Use Seed of Corruption spell on an enemy

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=27243/seed-of-corruption

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6284
