### ISSUE TITLE
(Warlock Affliction) Haunt Spell/Talent

### ISSUE THREAD

**Issue by Mooshii** [Valhalla-Gaming/Tracker#7278]
**Describe the issue you're having**:
Damage not scaling right. Haunt does the damage in 1 tick, not over 16,8 seconds. Does not reset cooldown if target dies within 15 seconds.

**Steps to reproduce the problem**:

1. Use Haunt on an enemy

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=48181/haunt

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6421
