### ISSUE TITLE
(Warlock Affliction) Soul Effigy Spell/Talent

### ISSUE THREAD

**Issue by Mooshii** [Valhalla-Gaming/Tracker#7279]
**Describe the issue you're having**:
Summons an invisible memic that cannot be targeted at all.

**Explain how you expect it work**:
Should summon a Soul Effigy with targets HP where you can use your spells on. 35% of the damage you deal with the spell will also be taken by the enemy.

**Steps to reproduce the problem**:

1. Use Soul Effigy on a target enemy

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=205178/soul-effigy

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6290
