### ISSUE TITLE
(Warlock Affliction) Reap Soul Artifact Spell

### ISSUE THREAD

**Issue by Mooshii** [Valhalla-Gaming/Tracker#7280]
**Describe the issue you're having**:
Does not give any damage boost.

**Explain how you expect it work**:
Should give a damage boost of 10% when used. Duration increased per soul consumed.

**Steps to reproduce the problem**:

1. Kill enemy's to get souls
2. Use Reap Soul Spell

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=216698/reap-souls

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6740
