### ISSUE TITLE
(Warlock Affliction) Summon Doomguard Spell

### ISSUE THREAD

**Issue by Mooshii** [Valhalla-Gaming/Tracker#7281]
**Describe the issue you're having**:
The summoned demon only uses his auto-attacks

**Explain how you expect it work**:
He should also use his ability

**Steps to reproduce the problem**:
1. Use Summon Doomguard
2. Let it attack an enemy

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=18540/summon-doomguard

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #5979
