### ISSUE TITLE
(Warlock Affliction) Create Healthstone

### ISSUE THREAD

**Issue by Mooshii** [Valhalla-Gaming/Tracker#7282]
**Describe the issue you're having**:
Healthstones does not heal.

**Steps to reproduce the problem**:

1. Create a Healthstone
2. Use it

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=6201/create-healthstone

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6175
