### ISSUE TITLE
(Warlock Affliction) Create Soulwell Spell

### ISSUE THREAD

**Issue by Mooshii** [Valhalla-Gaming/Tracker#7283]
**Describe the issue you're having**:
It does create a soulwell but you cannot take any healthstones from it.

**Explain how you expect it work**:
Should give a healthstone to everyone that uses it.

**Steps to reproduce the problem**:

1. Cast summon soulwell
2. Click the soulwell

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=29893/create-soulwell

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6500
