### ISSUE TITLE
(Warlock Affliction) Demonic Circle

### ISSUE THREAD

**Issue by Mooshii** [Valhalla-Gaming/Tracker#7284]
**Describe the issue you're having**:
After using it you cannot teleport back to it.

**Explain how you expect it work**:
Should create a portal for 6min where you can teleport back to.

**Steps to reproduce the problem**:

1. Use demonic circle
2. Spell cannot be cast again

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=48020/demonic-circle

**Comment by Redrian-Valhalla** [comment]
Please check your reports before posting, most of them are duplicates and I have to close them. 
https://github.com/Valhalla-Gaming/Tracker/issues/6493
