### ISSUE TITLE
(Warlock Affliction) Demonic Gateway Spell

### ISSUE THREAD

**Issue by Mooshii** [Valhalla-Gaming/Tracker#7285]
**Describe the issue you're having**:
Cannot use the portal.

**Explain how you expect it work**:
Should summon 2 portal which can be used to teleport from one location to another.

**Steps to reproduce the problem**:

1. Use demonic gateway
2. Click the portal

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=111771/demonic-gateway

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6261 please stop posting duplicates.

**Comment by Mooshii** [comment]
Sorry for duplicates, I only searched on spells that were labaled as Warlock. First time posting here. My bad.
