### ISSUE TITLE
Hand of Guldan / Call Dreadstalkers Demonology warlock bug 

### ISSUE THREAD

**Issue by ActivEa111** [Valhalla-Gaming/Tracker#7288]
Hand of Guldan - dont spawn imps 
Call Dreadstalkers - cant cast 
https://github.com/Valhalla-Gaming/Tracker/issues/6156 in this one i have only info about how this spell works. I need to know how to fix this. Like 1... 2... 3...
Help, i want to main Demonology warlock.

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6053

**Comment by ActivEa111** [comment]
How to fix that? My Hand of Guldan does dmg but dont spawn imps.

**Comment by Redrian-Valhalla** [comment]
You need to wait for the spell dev to get to it.

**Comment by ActivEa111** [comment]
I dont understand (bad English). I need to wait for spell "DEV"?

**Comment by ActivEa111** [comment]
Hand of Guldan 0 dmg + dont spawn imps :/

**Comment by Redrian-Valhalla** [comment]
You can't fix the issue by yourself, all you can do is to wait for a developer.

**Comment by ActivEa111** [comment]
Oh, ty. For all :)
