### ISSUE TITLE
filtering (search) of Browse Auctions is disabled

### ISSUE THREAD

**Issue by lightsword67** [Valhalla-Gaming/Tracker#7290]
**Describe the issue you're having**:
filtering (search) of Browse Auctions is disabled, we can't search items in weapons,armor,gems,glyphs and all Game Accessories.
**Explain how you expect it work**:
it must have easy filtering in search.
**Steps to reproduce the problem**:

1. do fix filtering of Browse Auctions
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6572
