### ISSUE TITLE
shadow priest talent bug  [Mind Bomb]

### ISSUE THREAD

**Issue by voodoomaster** [Valhalla-Gaming/Tracker#7292]
**Describe the issue you're having**: [Mind Bomb]

**Explain how you expect it work**:its should stun people but do nothing 

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:http://www.wowhead.com/spell=205369/mind-bomb

**Comment by Redrian-Valhalla** [comment]
Duplicate of https://github.com/Valhalla-Gaming/Tracker/issues/7022
