### ISSUE TITLE
bug quest HORD  [Burn It Up... For the Horde!] 

### ISSUE THREAD

**Issue by voodoomaster** [Valhalla-Gaming/Tracker#7293]
the issue you're having**:quest  [Burn It Up... For the Horde!]

**Explain how you expect it work**cant burn the tanks 

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:http://www.wowhead.com/quest=10087/burn-it-up-for-the-horde

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6536
