### ISSUE TITLE
Pandaren appearance cant be changed in barbershop

### ISSUE THREAD

**Issue by hellraiserz** [Valhalla-Gaming/Tracker#7294]
**Describe the issue you're having**:
i cant change my pandaren appearance in barbershop while i click "okey" nothing happens
**Explain how you expect it work**:
when pressing "okey" change happens
**Steps to reproduce the problem**:
1. cycle through the apperance then i press "okey" nothing happens
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7061
