### ISSUE TITLE
 [Shadow Word: Death] shadow priest bug

### ISSUE THREAD

**Issue by voodoomaster** [Valhalla-Gaming/Tracker#7295]
**Describe the issue you're having**: [Shadow Word: Death]

**Explain how you expect it work**:its don't generate  insanity for priest 

**Steps to reproduce the problem**:
1. it should generate insanity about 10-30 
2. 
3. 

**Links to Wowhead, YouTube, etc**:http://www.wowhead.com/spell=32379/shadow-word-death

**Comment by forstix** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6911

**Comment by Moustachos** [comment]
Ref #5979
