### ISSUE TITLE
quest bug  [Zeth'Gor Must Burn!]

### ISSUE THREAD

**Issue by voodoomaster** [Valhalla-Gaming/Tracker#7296]
**Describe the issue you're having**: [Zeth'Gor Must Burn!]

**Explain how you expect it work**:
when go ext to the fore could turn on  [Bleeding Hollow Torch] for burning the buildings 
but its dont turn on 
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=10792/zethgor-must-burn

**Comment by Redrian-Valhalla** [comment]
Please try to not post duplicates, research before making a new issue.https://github.com/Valhalla-Gaming/Tracker/issues/2770
