### ISSUE TITLE
infight not fading

### ISSUE THREAD

**Issue by LordYawgmoth** [Valhalla-Gaming/Tracker#7297]
**Describe the issue you're having**:
wanted to test some abilities and talents with my mage (lvl 28, human, fire) and went to the puppets in sw
after attacking the puppets i didnt get out of fight and couldnt thus couldnt change talents

**Explain how you expect it work**:
after 5s or so of no action  the infight should fade away

**Steps to reproduce the problem**:

1. hit a test puppet
2. see that u wont get out of combat
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
You have to take them out of your target and get some distance.
