### ISSUE TITLE
quest  [From the Abyss]

### ISSUE THREAD

**Issue by voodoomaster** [Valhalla-Gaming/Tracker#7298]
**Describe the issue you're having**:its say need void stone

**Explain how you expect it work**:
equip a void stone there untill quest item work 
**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:http://www.wowhead.com/quest=10295/from-the-abyss
http://www.wowhead.com/quest=10295/from-the-abyss

**Comment by Cidragon** [comment]
working in next update.
