### ISSUE TITLE
shadow priest  [Shadowy Apparitions]

### ISSUE THREAD

**Issue by voodoomaster** [Valhalla-Gaming/Tracker#7299]
**Describe the issue you're having**:
dont work
**Explain how you expect it work**:
its dont work need to fix
**Steps to reproduce the problem**:

1. do a work its start working
2. :)
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=78203/shadowy-apparitions

**Comment by forstix** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7032

**Comment by Redrian-Valhalla** [comment]
Indeed, thanks Fostix.
