### ISSUE TITLE
quest  [Doorway to the Abyss]

### ISSUE THREAD

**Issue by voodoomaster** [Valhalla-Gaming/Tracker#7300]
**Describe the issue you're having**:
there is nothing to click on that and close burning legion gate .
**Explain how you expect it work**:
it could be any thing for click on that and close burning legion gate 
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=10392/doorway-to-the-abyss#screenshots

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/4004
