### ISSUE TITLE
legion: scaling npcs

### ISSUE THREAD

**Issue by LordYawgmoth** [Valhalla-Gaming/Tracker#7302]
**Describe the issue you're having**:
farming ap in the spidernest near illidari perch is a pain in the ass, why?
first the npcs scale with ur own lvl, this shouldnt happen 
second the scaling is overboard a lvl 110 spider (small) deals 60k autohit dmg (dh veangance! that s god damn tank built!) and it s hard to aggro only one

**Explain how you expect it work**:
npc lvl should stay according to the zone 100-103 i think?

**Steps to reproduce the problem**:
go with lvl 110 into low lvl legion zones
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by kjelt** [comment]
Scaling is introduced with Legion: 
http://www.polygon.com/2015/11/6/9684580/world-of-warcraft-legion-zones-level-scaling

Only problem i see is you got lvl 110 but your gear is not that appropriate as on retail. There are too many bugs related to get better gear. No quests, no instances and no item drops lead to that issue.
