### ISSUE TITLE
quest  [Blessing of Incineratus] 

### ISSUE THREAD

**Issue by voodoomaster** [Valhalla-Gaming/Tracker#7303]
**Describe the issue you're having**:
its dont work and say requires  windyreed hunt 
**Explain how you expect it work**:

**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=9805/blessing-of-incineratus#comments

**Comment by Cidragon** [comment]
Fixed in December 5th changelog.
