### ISSUE TITLE
Monks spells

### ISSUE THREAD

**Issue by Exkan** [Valhalla-Gaming/Tracker#7310]
this spells don't work:

1. http://es.wowhead.com/spell=115080/toque-de-la-muerte - it doesn't hurt
2. http://es.wowhead.com/spell=117952/relampago-crepitante-de-jade - it doesn't hurt and doesn`t psuh
3. http://es.wowhead.com/spell=115288/elixir-tonificante -don't work, no active

**Comment by Redrian-Valhalla** [comment]
Please don't report multiple smells in the same issue.

**Comment by Exkan** [comment]
ok :( i will try again
thanks

**Comment by Redrian-Valhalla** [comment]
Make sure to check for duplicates too.

**Comment by Exkan** [comment]
ok thanks for the inf
