### ISSUE TITLE
(Brewmaster) Stagger

### ISSUE THREAD

**Issue by Nightcap** [Valhalla-Gaming/Tracker#7325]
**Describe the issue you're having**: This is the one shot stagger bug that's been around awhile but I don't see it listed here anymore. Below is a image showing the bug

**Explain how you expect it work**:Stagger spreads out damage over time 

**Steps to reproduce the problem**:

1. Make a BM monk
2. Fight mobs
3. Die instantly from stagger amplifying damage incorrectly

**Links to Wowhead, YouTube, etc**: http://imgur.com/a/jX1mY
http://www.wowhead.com/spell=124255/stagger#changelog

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6167 
It will be fixed in the next update, that's why the issue was closed.
