### ISSUE TITLE
Who Are They?

### ISSUE THREAD

**Issue by GeneralCaveman** [Valhalla-Gaming/Tracker#733]
http://www.wowhead.com/quest=10041/who-are-they

After talking with the required people, their objectives do not complete.

**Comment by manic17** [comment]
objectives seem to be completing for me just that the shadowy laborer seems to be missing 

http://i.imgur.com/i2zolwG.jpg

**Comment by Malae1** [comment]
After searching through there does seem to be a limited amount of laborers located at the area, though the quest is complete-able by talking to the few that are available.

**Comment by jfdaigle** [comment]
Works fine.  Only thing is that you must take quest unmounted, and not use your mount to go to the area as you will loose the disguise.

**Comment by Cidragon** [comment]
This quest is working fine :)
