### ISSUE TITLE
Fiery Demise VDH artifact trait

### ISSUE THREAD

**Issue by zsolti16** [Valhalla-Gaming/Tracker#7330]
**Describe the issue you're having**:
This artifact trait does not increase the fire damage taken by the target
**Explain how you expect it work**:
It should increase the fire damage done to the target by 30% at 3 trait points
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=212817/fiery-demise

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7099
