### ISSUE TITLE
Vengeance demon hunter parry and crit

### ISSUE THREAD

**Issue by zsolti16** [Valhalla-Gaming/Tracker#7331]
**Describe the issue you're having**:
Crit does not increase the parry rating, it just sits at a base of 6%, but my crit says that it should increase it by 6.63% so it should be 12.63% total.
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7170

**Comment by zsolti16** [comment]
Redrian that is not the same issue!!!

**Comment by Redrian-Valhalla** [comment]
My bad, I thought it was included in the comments, I'll label your new issue.
