### ISSUE TITLE
[Monk][Brewmaster][Passive] Gift of the Ox

### ISSUE THREAD

**Issue by Hemoglobine-Valhalla** [Valhalla-Gaming/Tracker#7339]
**Describe the issue you're having**:
It doesnt summon spheres
**Explain how you expect it work**:
It should generate spheres, making the monk heal for 750% attack power
**Steps to reproduce the problem**:
1.  Since it doesnt work you can't reproduce the problem.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=124502/gift-of-the-ox

**Comment by Nightcap** [comment]
Tested and comfirmed

**Comment by Moustachos** [comment]
Ref #5979
