### ISSUE TITLE
[Hunter][Skill] Market Shot

### ISSUE THREAD

**Issue by Aprophys** [Valhalla-Gaming/Tracker#7340]
**Describe the issue you're having**:
Market shot atm dieals alot of dmg in pvp
blob:http://imgur.com/09fa2554-2e18-47d5-8856-700ccd588f90
http://imgur.com/a/hg7S7
**Explain how you expect it work**:
Marked Shot
30 Focus	40 yd range
Instant
Requires Hunter (Marksmanship)
Requires level 18
Requires Ranged Weapon
Rapidly fires shots at all targets with your Hunter's Mark, dealing 250% Physical damage and making them Vulnerable for 30 sec.

Vulnerable
Damage taken from Marked Shot and Aimed Shot increased by 25%. Lasts 30 sec. Stacks up to 3 times.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=185901/marked-shot

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7217
