### ISSUE TITLE
Quest Credits - Core

### ISSUE THREAD

**Issue by Kumanix** [Valhalla-Gaming/Tracker#7341]
**Describe the issue you're having:**
Items or npcs that are needed for certain quests can be right-click spammed granting all credits at once instead of just one per item/npc.

**Explain how you expect it work**:
You can't get more than 1 credit per item/npc.

**Steps to reproduce the problem**:
1. Get a quest that asks you to pick something up (that has no channeling) or that asks you to interact with an npc such as [Fear No Evil](http://www.wowhead.com/quest=28813/fear-no-evil)
2. Right click spam on the item/npc
3. Get the quest completed with just one item/npc

**Links to Wowhead, YouTube, etc**:

**Comment by GAMMARAYS** [comment]
This kind of issue is sadly quest-specific, as there really is no way that anyone knows about to tell if an NPC should despawn after it has granted its quest credit
