### ISSUE TITLE
[Monk][Brewmaster][Mastery] 

### ISSUE THREAD

**Issue by Hemoglobine-Valhalla** [Valhalla-Gaming/Tracker#7342]
**Describe the issue you're having**:
It doesn't give Attack power as it should (it doesnt give attack power at all only dodge part works)
**Explain how you expect it work**:
Each time you are hit by a melee attack, you gain stacking 8% increased Dodge chance until your next successful Dodge.

Also increases your attack power by 8%.
**Steps to reproduce the problem**:

1.  Make a bm monk let a mob hit you and check the buff about the mastery and you will notice that the attack power doesnt get increased.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=117906/mastery-elusive-brawler

**Comment by Moustachos** [comment]
Attacker power part is working too, but not upon dodging. It's a passive buff.

**Comment by Moustachos** [comment]
Ref #5979
