### ISSUE TITLE
Mage fire artifact trait : Blast furnace

### ISSUE THREAD

**Issue by Nienz** [Valhalla-Gaming/Tracker#7344]
**Describe the issue you're having**:
The dot dmg from Blast Furnace never goes away, one fireball on a dummie as an ex it wont get off

**Explain how you expect it work**:
fire blast does an additional 12.159  fire dmg over 9 seconds

**Steps to reproduce the problem**:
1. get the trait Blasting Furnace
2. use any spell on a dummie
3. watch the dot damage go on endlessly

**Links to Wowhead, YouTube, etc**:

**Comment by Nienz** [comment]
i will update this prior to 7.1 patch it when casting meteor near guards they are hit by it and burn forever until i alt f4 out

**Comment by Moustachos** [comment]
Ref #5979
