### ISSUE TITLE
[Holy Paladin][Trait] Deliver the Light

### ISSUE THREAD

**Issue by keyna** [Valhalla-Gaming/Tracker#7345]
**Describe the issue you're having**:

This trait doesn't increase healings done by Holy Light and Flash of Light. 

**Explain how you expect it work**:

It should increase the healings of Holy Light and Flash of Light by 3% for each points spent. 

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=200294/deliver-the-light

**Comment by Moustachos** [comment]
It works.

**Comment by Moustachos** [comment]
Ref #5979
