### ISSUE TITLE
Rogue: Outlaw/Subtlety

### ISSUE THREAD

**Issue by ElrondMcBong1337** [Valhalla-Gaming/Tracker#7363]
**Describe the issue you're having**:
Outlaw:
-Ruthlessness: does not generate the combo point even at 5 cp
-Roll the Bones: Jolly Roger and Buried Treasure seem not to give the Bonus (you can see still the same percentage chance of pistol shot at the text of Saber Slash/ Energy regen visually the same)

Subtlety:
-Nightblade: Does not slow the target, it slows yourself when attacking !! :D
-Subterfuge: Mobs often "resist" your Cheap Shot while the duration of Subterfuge, they kind of reset combat ... when simultaneously activating auto attack, it works better (same for this talent in Assassination). 
-Shuriken Storm:  Stealth does not increase damage, Shadow Dance works
-Shadow Techniques: Never got one combo point while only auto attacking
-Relentness Strikes: Does not give 25 energy back even at 5 combo points

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=14161/ruthlessness
http://www.wowhead.com/spell=199600/buried-treasure
http://www.wowhead.com/spell=199603/jolly-roger
http://www.wowhead.com/spell=196912/shadow-techniques
http://www.wowhead.com/spell=195452/nightblade
http://www.wowhead.com/spell=58423/relentless-strikes

**Comment by Redrian-Valhalla** [comment]
I'm sorry but you have to report each issue separately.
