### ISSUE TITLE
Rogue: Roll the Bones

### ISSUE THREAD

**Issue by ElrondMcBong1337** [Valhalla-Gaming/Tracker#7367]
**Describe the issue you're having**:

Roll the Bones: Jolly Roger and Buried Treasure seem not to give the Bonus (you can see still the same percentage chance of pistol shot at the text of Saber Slash/ Energy regen visually the same)

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=199600/buried-treasure
http://www.wowhead.com/spell=199603/jolly-roger

**Comment by Moustachos** [comment]
Both buffs work just fine.

**Comment by Moustachos** [comment]
Ref #5979
