### ISSUE TITLE
[Battleground][Reward] Battleground Victory Award

### ISSUE THREAD

**Issue by Hemoglobine-Valhalla** [Valhalla-Gaming/Tracker#7372]
**Describe the issue you're having**:
Once you win a bg you don't get the box
**Explain how you expect it work**:
It should provide a box with stuff as reward from winning a bg
**Steps to reproduce the problem**:
1.  Join in a bg
2.  Win the bg

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/item=141901/battleground-victory-award

**Comment by Moustachos** [comment]
Fixed in a previous update.
