### ISSUE TITLE
Purified Shard of the Third Moon

### ISSUE THREAD

**Issue by Mocniyogurt** [Valhalla-Gaming/Tracker#7379]
**Describe the issue you're having**: This trinket absorbs any kind of damage instead of damage only made by demons.

**Explain how you expect it work**: It should absorb damage made only by demons.

**Steps to reproduce the problem**: ?

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/item=133598/purified-shard-of-the-third-moon

**Comment by Redrian-Valhalla** [comment]
The trinket normally absorbs any kind of damage, but it's twice as effective against demons.
