### ISSUE TITLE
Major Demon Hunter Quest not available/starting

### ISSUE THREAD

**Issue by timepass12345** [Valhalla-Gaming/Tracker#7381]
**Describe the issue you're having**:
QUest "Cry Havoc and Let Slip the Illidari!" is not starting , no NPC is giving that quest, subsequently no other quest are also present through which progress can be made. 
Kayn Sunfury is supposed to give quest.
**Explain how you expect it work**:
Cry Havoc and Let Slip the Illidari! should start 
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=39516/cry-havoc-and-let-slip-the-illidari

**Comment by Redrian-Valhalla** [comment]
The quest is working, you need the help of a GM in case you did something wrong with the quest chain.
