### ISSUE TITLE
DH Double Jump DC Glitch

### ISSUE THREAD

**Issue by tuan206** [Valhalla-Gaming/Tracker#7393]
**Describe the issue you're having**:
When double jumping on Demon Hunter, it dc's me.
**Explain how you expect it work**:
When you double jump, you shouldn't get disconnected.
**Steps to reproduce the problem**:
1. Make a DH
2. Double Jump a couple times
3.  Boom, dc'ed

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=196055/double-jump

**Comment by Redrian-Valhalla** [comment]
Related to https://github.com/Valhalla-Gaming/Tracker/issues/7203

**Comment by gondin** [comment]
for someone this is happen

**Comment by gondin** [comment]
not for all but yea bugged

**Comment by Moustachos** [comment]
Ref #5979
