### ISSUE TITLE
Battleground: Friendly enemy

### ISSUE THREAD

**Issue by Djurdjevdan** [Valhalla-Gaming/Tracker#7394]
**Describe the issue you're having**:
In Battleground, something can cause that you can't attack enemy meaning they are friendly to you. Akwardly you take damage from their attacks.
**Explain how you expect it work**:
You should be able to attack opposing faction.
**Steps to reproduce the problem**:
1. I got that bug when I lost connection so I think it is probably linked to that (someone needs to confirm that)
2. After exiting Battleground and entering (after deserter debuff) bug is gone and everything is back to normal.

**Comment by Bombrick** [comment]
I have got this bug when my game crashed then i relogged

**Comment by Bombrick** [comment]
Fixed as the last changelog says.
