### ISSUE TITLE
Paladin spells

### ISSUE THREAD

**Issue by patroneq** [Valhalla-Gaming/Tracker#7395]
**Describe the issue you're having**:
1. Judgment only hits 1 enemy
2. Templar's Verdict deals no damage
**Explain how you expect it work**:
1. Judgment should hit your target and one the nearest enemy
2. Templar's Verdict should deal damage

**Links to Wowhead, YouTube, etc**:
1. http://www.wowhead.com/spell=20271/judgment
2. http://www.wowhead.com/spell=85256/templars-verdict

**Comment by forstix** [comment]
both reported already https://github.com/Valhalla-Gaming/Tracker/issues/6903
https://github.com/Valhalla-Gaming/Tracker/issues/6007
