### ISSUE TITLE
Dynamic NPC Scaling (legion)

### ISSUE THREAD

**Issue by lavalampe77** [Valhalla-Gaming/Tracker#7396]
**Describe the issue you're having**:
Mobs in broken isles are shown correctly with health pool and level, BUT all scaled mobs act like level 110 what means i had to do about 300k damage on a 80k health mob before he died. Damage currently done is shown correctly but my damage done to a scaled mob is not correctly removed from mob's health (seems to be only a % amount of it).
Also, mobs are doing to much damage and parry/dodge/resist spells too often. AND, their aggro range is way too high.
**Explain how you expect it work**:
If i fight a 120k health mob he should die after i have done 120k damage.
**Steps to reproduce the problem**:

1.Fight any scale mob below level 110 (have tested it with a lvl100 pally,druid,rogue and priest)
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Hemoglobine-Valhalla** [comment]
Confirmed, happen with my dk.

**Comment by Vikvaryas** [comment]
Hope this gets fixed fast, its very hard for me to level :(

**Comment by Aveta** [comment]
Aggro radius applies to literally all mobs in the game.
