### ISSUE TITLE
Item level of draenor mythic items

### ISSUE THREAD

**Issue by lavalampe77** [Valhalla-Gaming/Tracker#7397]
**Describe the issue you're having**:
Somehow mythic items from draenor (ilvl685) dont count as ilvl685-they seem to be ilvl 0. After i had changed these items with draenor pvp items (ilvl670), that are supposed to be badder, all my stats increased.
**Explain how you expect it work**:
Draenor mythics should increase player's ilvl correctly.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6779
