### ISSUE TITLE
PVP Tab Crash

### ISSUE THREAD

**Issue by Bombrick** [Valhalla-Gaming/Tracker#7399]
Some players can't open PVP tab because when they open it by clicking on the icon or pressing H on the keyboard They crash with:
"Not enough memory"

Deleting Cache won't help.

**Comment by forstix** [comment]
Same here but got realy old computer so new one on the way maybe it'll be fixed then

**Comment by Bombrick** [comment]
Fixed by making WoW folder not read only ( by properties)
