### ISSUE TITLE
[Quest] The Fight Continues

### ISSUE THREAD

**Issue by Kumanix** [Valhalla-Gaming/Tracker#7405]
**Describe the issue you're having**:
Quest is getting completed before the roleplay is done.

**Explain how you expect it work**:
You get the quest from High Tinker Mekkatorque, starts a roleplay event where he explains you about the Operation: Gnomeregan and once he is done, you get the quest done.

**Steps to reproduce the problem**:

1. Complete the quest up to The Fight Continues
2. Get the quest from High Tinker Mekkatorque
3. See it get auto-completed.

**Links to Wowhead, YouTube, etc**:
https://www.youtube.com/watch?v=Bp5PFxTxubc

[3227](https://github.com/Valhalla-Gaming/Tracker/issues/3227) / [2338](https://github.com/Valhalla-Gaming/Tracker/issues/2338) - Unlike these previous reports, the quest is "working", the roleplay does happen, but as I said, the credit is given as soon as you get the quest instead of being credited after the roleplay is done.

**Comment by Guybrush-VR** [comment]
This is how the quest behave on retail! I believe they change it after Cataclysm on player request. The video you linked is from early Cataclysm so it's not up to date!
Here you can find a 6.1.2 video of this quest: https://www.youtube.com/watch?v=xJUNRZYml1o
Thank you for linking the two other report though, forgot to close them. :penguin:
