### ISSUE TITLE
Quest:"Zeth'Gor Must Burn!" Quest=10792

### ISSUE THREAD

**Issue by alucula** [Valhalla-Gaming/Tracker#7406]
**Describe the issue you're having**:
unable to complete the quest due to missing forge
**Explain how you expect it work**:
i gathered the torch, i went to the forge and the game sad that i missed the forge
**Steps to reproduce the problem**:

1. take the quest
2. gather torch 
3.go to the forge

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=10792/zethgor-must-burn

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/2770
