### ISSUE TITLE
Powering our Defenses

### ISSUE THREAD

**Issue by Interpo** [Valhalla-Gaming/Tracker#7407]
**Describe the issue you're having**:
Cant use quest item even if i'm in correct place... Mobs are around this place but they should be there... they should respawn after i use my item... its look like quest is "stuck" on stage after this

**Explain how you expect it work**:
I should be able to use it and then mobs should spawn and attack me... 

**Links to Wowhead, YouTube, etc**:
https://www.youtube.com/watch?v=Dctry8qOkIc

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/500
