### ISSUE TITLE
quest:"Doorway to the Abyss"

### ISSUE THREAD

**Issue by alucula** [Valhalla-Gaming/Tracker#7408]
**Describe the issue you're having**:
Unable to complete the quest
**Explain how you expect it work**:
i should be able to click the gate( a little green sphere)
**Steps to reproduce the problem**:

1. take the quest
2. kill the mobs
3. gather what to gather

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=10392/doorway-to-the-abyss      https://www.youtube.com/watch?v=e02fyeH16jc

**Comment by Redrian-Valhalla** [comment]
Please search for duplicates before posting https://github.com/Valhalla-Gaming/Tracker/issues/4004
