### ISSUE TITLE
Mob HP dont decrease by the amount I hit for

### ISSUE THREAD

**Issue by Vikvaryas** [Valhalla-Gaming/Tracker#7409]
**Describe the issue you're having**:
I hit mobs for 10k or 20k and its health only reduce by 1k or 2k
**Explain how you expect it work**:
Mobs should die by the amount of HP i hit them for
**Steps to reproduce the problem**:

1. Use lvl 100-105 character (Higher level characters seem to hit properly)
2.  Attack any mob in Broken isles
3.  Observe above bug

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7396
