### ISSUE TITLE
Enhancement Shaman Healing Surge

### ISSUE THREAD

**Issue by TheGarga** [Valhalla-Gaming/Tracker#7411]
**Describe the issue you're having**:
Healing surge should become instant if you have 20 maelstorm 
**Explain how you expect it work**:
It should consume 20 maelstorm and become instant cast.
**Steps to reproduce the problem**:

1. Get 20 Maelstorm
2. Use healing surge 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=188070/healing-surge

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6984
