### ISSUE TITLE
No leather from looting skinned beasts.

### ISSUE THREAD

**Issue by Yeastus** [Valhalla-Gaming/Tracker#7412]
**Describe the issue you're having**:
Skinning doesn't give me any leather. When i skin the beast it has loot, but when i click on it it disappears. The chat says i looted an x amount of leather though it is not in my bags. This happens in Outland, Northrend, Pandaria and Draenor. 

**Explain how you expect it work**:
I expected to see the leather in my inventory

**Steps to reproduce the problem**:

1. Kill a beast in on of the area's named above
2. Skin and loot the beast
3. No leather/scraps/hides in inventory

**Comment by forstix** [comment]
Check ur bank\regant bank

**Comment by Yeastus** [comment]
Forstix thanks for the tip. I didn't know it was send to the reagent bank automatically. Issue solved.

**Comment by forstix** [comment]
I'm not sure if that should happend tbh :)
