### ISSUE TITLE
Heirlooms Achievement

### ISSUE THREAD

**Issue by rgk0777** [Valhalla-Gaming/Tracker#7414]
**Describe the issue you're having**:
so, i just bought about 36-37 heirlooms but i didn't get any achievement and heirloom hoarder

**Explain how you expect it work**:
it should give me an heirloom achievement and heirloom hoarder
**Steps to reproduce the problem**:

1. buy 35 heirlooms
2. get heirloom hoarder achievement
3. get heirloom hoarder mount

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/achievement=9909/heirloom-hoarder
https://www.youtube.com/watch?v=IQRmfjlVZ9Y

**Comment by Moustachos** [comment]
Already reported and closed because it will be fixed on next update.
