### ISSUE TITLE
Reputation Rewards ALL Quests

### ISSUE THREAD

**Issue by Samorias** [Valhalla-Gaming/Tracker#7417]
**Describe the issue you're having**:
the reputation rewards that all quests (and with all i mean ALL) should give, be it for ogrimmar, Thrallmar, Cenerian Circle etc. is not awarded

**Explain how you expect it work**:
it should be giving x reputation with *faction*
**Steps to reproduce the problem**:
do any quest for any faction

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6313
