### ISSUE TITLE
All remaining rogue bugs.

### ISSUE THREAD

**Issue by blablablablblabllabl** [Valhalla-Gaming/Tracker#7418]
All the remaining rogue bugs. By importance level. *Artifact talents and honor talents are not listed*

# Importance : High
Shadow Dance - doesn't work 
                            www.wowhead.com/spell=185313

Cannonball Barrage(Talent) - doesn't work (no damage, no slow, no animation)
                                  www.wowhead.com/spell=185767

Venomous wound - deals damage
  How it should work : It deals damage in WoD, but in legion it only regenerates energy.
                                www.wowhead.com/spell=79134

Anticipation(Talent) - doesn't work
                                www.wowhead.com/spell=193539

Deeper Stratagem - doesnt work 
                               www.wowhead.com/spell=193531

Backstab - cannot cast from front
   How it should work : In wod this ability couln't be cast from front, but as in legion update this can be 
                                   cast from front.
                                   www.wowhead.com/spell=53

Death from Above - doesn't work
                                 www.wowhead.com/spell=152150

# Importance : Medium
Agonizing Poison (Talent) - stacks with other lethal poisons,
   How it should work :  As a lethal poison, it cannot be used at the same time with other lethal poisons.
                                    For example you cant have Deadly Poison and Agonizing Poison at the same 
                                    time.
                                     http://www.wowhead.com/spell=200802
Alacrity (Talent) - doesn't proc properly 
  How it should work : Finishing moves- which require combo points to activate - should proc alacrity 
                                  and give haste but, SOME combo generating abilities, and Mastery: Main Gauche 
                                  (outlaw) procs alacrity and gives haste stack when it shouldnt. 
                                  http://www.wowhead.com/spell=193539
Deepening Shadows - doesn't work 
                                  www.wowhead.com/spell=185314

Elaborate Planning(Talent) - ONLY abilities that deal direct damage AT CAST procs it 
    How it should work : Only finishing moves - which require combo points to activate - should proc it
                                    , but Mutilate, Fan of Knives procs it ( which shouldn't), and Rupture , Kidney
                                    shot doesnt proc it ( which should).
                                  www.wowhead.com/spell=193640
Enveloping Shadow(Talent) - doesn't work 
                                 www.wowhead.com/spell=206237
Master of Shadows(Talent) - doesn't work 
                         http://www.wowhead.com/spell=196976

Strike from the Shadows(Talent) - doesn't work 
                              www.wowhead.com/spell=196951
# Importance : Low
Thuggee(Talent) - doesn't work 
              http://www.wowhead.com/spell=196861

Internal Bleeding(Talent) - doesn't deal damage
                            www.wowhead.com/spell=154904

Exsanguinate (Talent)- doesn't work 
                                 www.wowhead.com/spell=200806

**Comment by Redrian-Valhalla** [comment]
Please report each issue separately, also check for duplicates.
