### ISSUE TITLE
Monk(Talent) Blackout Combo

### ISSUE THREAD

**Issue by Nightcap** [Valhalla-Gaming/Tracker#7422]
**Describe the issue you're having**:This talents passive effects do not work.

**Explain how you expect it work**: There are several passive effects, see wowhead link below.

**Steps to reproduce the problem** Select this talent and use the mentioned abilities, notice how the passives from it do not work
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=196736/blackout-combo

**Comment by theprototyze** [comment]
Some passives work, but wrongly (Breath of Fire shows cooldown as being 15 but whenever it's used, it's just 8)

**Comment by Moustachos** [comment]
Ref #5979
