### ISSUE TITLE
Monk (Talent) Elusive Dance

### ISSUE THREAD

**Issue by Nightcap** [Valhalla-Gaming/Tracker#7423]
**Describe the issue you're having**: The Elusive Dance passive talent does not grant it's effects - 15% Dodge AND Damage done.  And does not clear a additional 15% Stagger when purifing brew is used.

**Explain how you expect it work**: This passive should work as mentioned, see wowhead link

**Steps to reproduce the problem**: Select the talent, get some stagger built and notice the  passive effects aren't working with Purifying Brew
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=196738/elusive-dance

**Comment by Moustachos** [comment]
The 15% additional purified Stagger part works.

The other one will be fixed on next update.

**Comment by Moustachos** [comment]
Ref #5979
