### ISSUE TITLE
Monk (Talent) High Tolerance

### ISSUE THREAD

**Issue by Nightcap** [Valhalla-Gaming/Tracker#7424]
**Describe the issue you're having**: The High Tolerance talent does not grant it's passive effects - 10% additional Stagger Delay and 15% Haste based on Stagger.

**Explain how you expect it work**: It should work as mentioned, see Wowhead link below

**Steps to reproduce the problem**: Select a appropriate level enemy without the talent first,and take note of it's stagger damage, Then select the talent and see that the additional 10% stagger has not been accounted for. And also that it does not increase Haste by 15% based on stagger - (Character stats page)

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=196737/high-tolerance

**Comment by Moustachos** [comment]
This spell works just fine.

**Comment by Moustachos** [comment]
Ref #5979

**Comment by Moustachos** [comment]
Ref #5979
