### ISSUE TITLE
ilvl810 (Trinket) Six-Feather Fan

### ISSUE THREAD

**Issue by Nightcap** [Valhalla-Gaming/Tracker#7427]
**Describe the issue you're having**: This item has a chance to launch a 6 shot volley at attackers, But usually it attacks the player using it, Sometimes killing the player.

**Explain how you expect it work**: It should not attack the player

**Steps to reproduce the problem**: Equip and go into battle with it, I should take long to attack you, it seems to be around a 50% chance to attack the player.

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/item=141585/six-feather-fan

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7353
