### ISSUE TITLE
Mythic dungeons not resettinf properly

### ISSUE THREAD

**Issue by tylegg** [Valhalla-Gaming/Tracker#7428]
**Describe the issue you're having**:I run a Draenor mythic dungeon for the first time with no problem but when I exit and reset all instances. the dungeon bosses wont drop any loot any more. Ive gone in 10+ times but nothing will drop. Ive reset instances and logged fully out of the game and the bosses will drop loot again but the loot is the same as the last loot I recieved

**Explain how you expect it work**: I should be able to reset a Mythic dungeon and reenter without logging out. the loot should change with each new instance

**Steps to reproduce the problem**:

1. Finish a mythic dungeon
2. reset all instances
3. reenter mythic dungeon

**Links to Wowhead, YouTube, etc**:

**Comment by Aveta** [comment]
You can loot a mythic boss only once per week.
