### ISSUE TITLE
Arms Warrior Overpower

### ISSUE THREAD

**Issue by Bluedoc** [Valhalla-Gaming/Tracker#7429]
**Describe the issue you're having**:
Overpower talent says that your melee attacks and abilities have a chance to activate overpower, it does that just fine, but whenever you use an other ability that isn't overpower, it makes it so you can't use it anymore, and have to wait on another proc.

**Explain how you expect it work**:
The overpower buff should stay on you for 12 seconds until you use it, then it should remove itself.

**Steps to reproduce the problem**:

1. Take over power talent in arms warrior.
2. Attack something until you get overpower proc.
3. Use another ability that isn't overpower.

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6925 please check for duplicates before posting.
