### ISSUE TITLE
Arms warrior Colossus Smash

### ISSUE THREAD

**Issue by Bluedoc** [Valhalla-Gaming/Tracker#7430]
**Describe the issue you're having**:
Arms warriors have a passive talent called Tactician that makes it so that you have 0.65% change per rage spent to reset the cooldown on Colossus smash and mortal strike, it doesn't.

**Explain how you expect it work**:
Whenever this passive procs, Colossus Smash should become available.

**Steps to reproduce the problem**:

1. Take arms warrior.
2. Use colossus smash.
3. Spend some rage, and wait for a proc, you'll see Colossus Smash highlight, but still on cooldown.

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6930
