### ISSUE TITLE
Warriors Heroic Leap

### ISSUE THREAD

**Issue by Bluedoc** [Valhalla-Gaming/Tracker#7431]
**Describe the issue you're having**:
Somehow the heroic leap cooldown is longer than what is showed on the icon/tooltip.

**Explain how you expect it work**:
The ability should be available to use whenever it comes off cooldown.
**Steps to reproduce the problem**:
1. Create warrior
2. Use Heroic Leap
3. wait for cooldown to count down, try to use ability, there's a delay of around 30 sec

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/8147

**Comment by Moustachos** [comment]
Ref #5979
