### ISSUE TITLE
Prot warrior str/crit and parry

### ISSUE THREAD

**Issue by zsolti16** [Valhalla-Gaming/Tracker#7432]
**Describe the issue you're having**:
At the moment strength contributes to parry chance, and crit ratings does not.
**Explain how you expect it work**:
Critical rating should contribute to parry ratings and not strength, this is major becouse i get insane amounts of parry chance, sitting at 40% at the moment.
**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Moustachos** [comment]
Critical Chance contribution to Parry has been fixed in a previous update.

Strength must increase Parry, but the Strength to Parry ratio has to be updated to Legion, hence the high values you see right now.

**Comment by Moustachos** [comment]
Ref #5979
