### ISSUE TITLE
Warlock Mana Generating

### ISSUE THREAD

**Issue by Bryan2001** [Valhalla-Gaming/Tracker#7434]
The Mana for warlocks don't regenerate at low level.

I expect to fix the mana issue and make potions etc work.

Steps
1. Either make Life Tap work on lower  level or fix the mana regenerating

**Links to Wowhead, YouTube, etc**:

**Comment by Moustachos** [comment]
Can't reproduce this bug on current version.

**Comment by Moustachos** [comment]
Ref #5979
