### ISSUE TITLE
Holy priest mastery issue.

### ISSUE THREAD

**Issue by n0b0di** [Valhalla-Gaming/Tracker#7435]
Holy priest passive skill named: Mastery: Echo of Light is not procing it's heal over time after casting a heal (in this case, it does not work with any heal in the priest's arsenal of spells)

"Your direct healing spells heal for an additional XY% over 6 sec" The XY scales of the mastery and I don't know the precise "math" for this.

http://www.wowhead.com/spell=77485/mastery-echo-of-light

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7101
