### ISSUE TITLE
[Quest] [Cry Havoc and let slip the illidari] Demon Hunters

### ISSUE THREAD

**Issue by Spectrali** [Valhalla-Gaming/Tracker#7438]
**Describe the issue you're having**: The quest worked fine, however when i went to train the other npc demon hunter into the specialization , right after they dissapeared and did not reappear. So i can't turn in the quest and progress further.

**Explain how you expect it work**: The Npc dont dissapear and allows to validate the quest.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=39516/cry-havoc-and-let-slip-the-illidari

**Comment by Redrian-Valhalla** [comment]
The quest for itself works works well, but seems you ended up in some phasing error, I suggest you contact a GM to help you out.
