### ISSUE TITLE
Phoenix's Flames[fire mage artifact trait]

### ISSUE THREAD

**Issue by Milofajjour** [Valhalla-Gaming/Tracker#7440]
**Describe the issue you're having**:
Phoenix's flame is not always criting as it should be and its not doing splash dmg to nearby enemies 
**Explain how you expect it work**:
Phoenix's Flames has 3 charges wich do good amount of dmg but always crit like fire blast and it should do splash dmg to enemies nearby the orgininal target.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=194466/phoenixs-flames

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7346
