### ISSUE TITLE
Possibly Server-Breaking not working quest

### ISSUE THREAD

**Issue by Cubewest95** [Valhalla-Gaming/Tracker#7441]
-snip-

**Comment by Redrian-Valhalla** [comment]
Thank you for your report, but please try to let us know about issues like this privately, you can do that by sending me a PM and I'll handle the rest.

**Comment by Cubewest95** [comment]
I told a GM but he told me to come here. Apologies

**Comment by Redrian-Valhalla** [comment]
The issue has been solved and a fix will be applied with the next update.

**Comment by Cubewest95** [comment]
I am glad to hear that, next time I'll contact you first if I find something that game-breaking. Have a good day
