### ISSUE TITLE
[Paladin][Protection] Consecration 

### ISSUE THREAD

**Issue by lavalampe77** [Valhalla-Gaming/Tracker#7442]
**Describe the issue you're having**:
Consecration deals extremly low damage at level 110 and makes it rather useless.
**Explain how you expect it work**:
Consecrates the land beneath you, causing [(30% of Attack power) * 9] Holy damage over 9 sec to enemies who enter the area.
**Steps to reproduce the problem**:

1. Use the spell.
2. Watch the damge.
3. 

**Links to Wowhead, YouTube, etc**:
[IMG]http://i65.tinypic.com/2a7fk40.jpg[/IMG]

**Comment by Moustachos** [comment]
Will be fixed on next update.

**Comment by Moustachos** [comment]
Ref #5979
