### ISSUE TITLE
emerald portals

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#7446]
**Describe the issue you're having**:
portal in mount hyjal to emerald dreamsomethingsomething can be used by any class at any level
**Explain how you expect it work**:
should be usable only for druids
**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
![wowscrnshot_102816_194234](https://cloud.githubusercontent.com/assets/14946340/19816260/e23c8be8-9d46-11e6-83e1-fb8b9bf51800.jpg)
![wowscrnshot_102816_194207](https://cloud.githubusercontent.com/assets/14946340/19816266/e7c8fc0e-9d46-11e6-82c3-fed0f983d719.jpg)

**Comment by Redrian-Valhalla** [comment]
Cool bug :P

**Comment by Guybrush-VR** [comment]
Inception :sleeping:

**Comment by GM-Pyromanic** [comment]
Issue was fixed a few updates ago.
