### ISSUE TITLE
[Paladin][Protection] Shield of the Righteous

### ISSUE THREAD

**Issue by lavalampe77** [Valhalla-Gaming/Tracker#7452]
**Describe the issue you're having**:
The spell has got 2 tasks: 1.It does damage 2.It reduces damage taken. The secound part doesnt seem to work. I cant see any damage taken reduction in my combat log (my tooltip shows it should be 37%)and the Buff when damage reduction is active is missing.
**Explain how you expect it work**:
Slams the target with your shield, causing (360% of Attack power) Holy damage, and reducing damage you take by (- 1 \* 25 ; Min - 80, Max - 25)% for 4.5 sec. 20% increased effect when standing in consecration.
**Steps to reproduce the problem**:
1. Fight a mob and watch the combat log damage taken.
2. Use Shield of the Righteous and compare damage taken now (for the next 4,5 secounds)
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=53600/shield-of-the-righteous
damage reduction buff: http://www.wowhead.com/spell=132403/shield-of-the-righteous#buff

**Comment by Femala** [comment]
URGENT Pls .... 175K ....  cant play 2v2 with paladins noobs where they IK us

**Comment by Moustachos** [comment]
Ref #5979
