### ISSUE TITLE
[PVP][Battlegound] Item level scalling

### ISSUE THREAD

**Issue by Hemoglobine-Valhalla** [Valhalla-Gaming/Tracker#7461]
**Describe the issue you're having**:
When you join into a bg a buff should be there explaining that your stats out of bg were changed in bg scalling with your item level such buff isn't there.
**Explain how you expect it work**:
When you join into a bg a buff should be there explaining that your stats out of bg were changed in bg scalling with your item level
**Steps to reproduce the problem**:
1.  Join a bg
2.  Check your buffs
3.  notice it isn't there.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=197912/principles-of-war

**Comment by Hemoglobine-Valhalla** [comment]
Adding a note about this, item level scalling system doesn't work aswell, stats doesnt change either if you get a higher ilvl or not, with stats i mean critic, haste and such. seems like it is a 60% or so of the amount you get out of bg.

**Comment by forstix** [comment]
i found the formula for that gear scaling check this link http://pwncastdailyquest.com/legion-pvp-system-breakdown-everything-you-need-to-know/

**Comment by Moustachos** [comment]
Will be fixed on next update.
