### ISSUE TITLE
[Trinket ]Six-Feather Fan

### ISSUE THREAD

**Issue by Gonosz** [Valhalla-Gaming/Tracker#7463]
**Describe the issue you're having**:

When the trinket proc, it also makes the player who uses it move slower, and also damage itself.

**Explain how you expect it work**:

It should only slow and damage the player's target, not the player too.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/item=141585/six-feather-fan

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7353 Will be fixed with the next update.
