### ISSUE TITLE
Guardian Druid bugged passives

### ISSUE THREAD

**Issue by Kamisama143** [Valhalla-Gaming/Tracker#7471]
**Describe the issue you're having**:
Guardian Druid passive : 
Gore - It doesn't reset the cooldown of Mangle
Galactic Guardian - Doesn't Trigger a free Moonfire
**Explain how you expect it work**:
Gore - Should reset the cooldown of Mangle
Galactic Guardian - Should trigger a free Moonfire

Links to both skills : 

http://www.wowhead.com/spell=210706/gore
http://www.wowhead.com/spell=203964/galactic-guardian

**Comment by Analog-Valhalla** [comment]
Closing to remake post to better suit 7.1.5 changes. Thank you :D
