### ISSUE TITLE
Warrior Rage

### ISSUE THREAD

**Issue by TheGarga** [Valhalla-Gaming/Tracker#7472]
**Describe the issue you're having**:
One melee hit fills your rage bar to full
**Explain how you expect it work**:
It should only give you 20-30 rage don't know the exact number
**Steps to reproduce the problem**:

1. Hit mob with melee hit
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by VictorTyne** [comment]
What sort of warrior are you playing to have this problem?
Playing a Fury Warrior has the opposite problem: auto-attacks generate no rage whatsoever.
https://github.com/Valhalla-Gaming/Tracker/issues/7815

**Comment by Moustachos** [comment]
Ref #5979
