### ISSUE TITLE
[Demon Hunter][Talent] Fel Barrage - No effect

### ISSUE THREAD

**Issue by tideful** [Valhalla-Gaming/Tracker#7474]
**Describe the issue you're having**:

Havoc Demon Hunter Tier 7 talent, Fel Barrage does nothing, regardless of the number of charges.

**Explain how you expect it work**:

"inflicting [(250% of Attack power)] Chaos damage to your target and nearby enemies for each charge" (Wowhead quotation)

**Steps to reproduce the problem**:

1.  Roll a Demon Hunter, get level 110
2.  Pick "Fel Barrage" as a talent
3.  Go to a nearby enemy, use it, see no damage on the screen, no damage on Recount.

**Links to Wowhead, YouTube, etc**:

http://www.wowhead.com/spell=211053/fel-barrage
https://www.youtube.com/watch?v=X1ZLUXFoyYU

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7185
