### ISSUE TITLE
Berserker Rage bug

### ISSUE THREAD

**Issue by bewilder1** [Valhalla-Gaming/Tracker#7478]
**Describe the issue you're having**:
Berserker Rage does not work. It does not remove nor grant immunity to sap, fear, and incapacitated
**Explain how you expect it work**:
It should grant immunity or / and remove those debuffs
**Steps to reproduce the problem**:

1. Get sapped, feared, incapacitated
2. Use berserker rage
3. Nothing

http://www.wowhead.com/spell=18499/berserker-rage

**Comment by bewilder1** [comment]
Tested again. It works for vengeance demon hunter's fear. Not worked for demon hunter's demon imprison with PvP talent taken, fire mage's dragon breath, priest's fear.

**Comment by Moustachos** [comment]
Berserker Rage isn't meant to grant immunity to Dragon's Breath or Imprison.

Works fine on priest's fear, unless you're referring to another spell than Psychic Scream?

**Comment by Moustachos** [comment]
Ref #5979
