### ISSUE TITLE
Heroic Leap and Charge makes you DC

### ISSUE THREAD

**Issue by bewilder1** [Valhalla-Gaming/Tracker#7480]
**Describe the issue you're having**:
I often DCed whenever I use charge or heroic leap (warrior skills)
**Explain how you expect it work**:
I should be not DCed
**Steps to reproduce the problem**:

1. Cast Charge / Heroic leap
2. In mid animation, press movement keys .
3. Sometimes I don't DCed, mostly I do.

**Links to Wowhead, YouTube, etc**:

**Comment by Hellfurian** [comment]
I personally haven't received that problem.. Try clearing cache or checking game files.

**Comment by Moustachos** [comment]
Ref #5979
