### ISSUE TITLE
DH-PVP Imprison

### ISSUE THREAD

**Issue by Redrian-Valhalla** [Valhalla-Gaming/Tracker#7481]
**Describe the issue you're having**:
Imprison applies its PvE duration on Players targets.
**Explain how you expect it work**:
It should apply its shorter duration on Players.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=217832/imprison

**Comment by Hemoglobine-Valhalla** [comment]
happen the same with 

http://www.wowhead.com/spell=207684/sigil-of-misery

**Comment by Ihugyou** [comment]
Not only that Surv hunter roots for 30 SEC in pvp that is a bug should be shoter

**Comment by Redrian-Valhalla** [comment]
Already reported and we're aware about it.
