### ISSUE TITLE
male night elf demon huntard

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#7484]
**Describe the issue you're having**:
cant make it
**Explain how you expect it work**:
i should be able to make it
**Steps to reproduce the problem**:

1. try to make it
2. 
3. 

**Links to Wowhead, YouTube, etc**:
![wowscrnshot_110116_193203](https://cloud.githubusercontent.com/assets/14946340/19902150/f96b864a-a069-11e6-80f0-0b657d4f7f47.jpg)

**Comment by Redrian-Valhalla** [comment]
Did this start to happen after the latest update?

**Comment by Traveler-Valhalla** [comment]
i dont know sry. male belf and females work ok.

**Comment by Traveler-Valhalla** [comment]
today for some reason i am able to make male night elf demon hunter
