### ISSUE TITLE
DH pvp talent Rushing Vault bug

### ISSUE THREAD

**Issue by ghost** [Valhalla-Gaming/Tracker#7490]
Describe the issue you're having : It doesn t work totally bugged.

Explain how you expect it work : 
Using Vengeful Retreat grants a charge of Fel Rush.

http://www.wowhead.com/spell=205601/rushing-vault

**Comment by Moustachos** [comment]
Rushing Vault has been removed in 7.1.5

**Comment by Moustachos** [comment]
Ref #5979
