### ISSUE TITLE
Fists of Fury not working as intended

### ISSUE THREAD

**Issue by Furyan9x** [Valhalla-Gaming/Tracker#7495]
**Describe the issue you're having**: As a Gnome Monk(Not sure if all races or just this one) when Fist of Fury is used regardless of if the channel finishes or not the skill goes through its entire duration. It has allowed me to kill groups of mobs quicker by starting it, canceling it and using other skills while it channels. Also, it doesn't stun as intended. At least not in PvE. 

**Explain how you expect it work**: 

Should lock player for the duration of the channel, and cease to continue if channel is interrupted or canceled. Should also stun for the duration unless cc-broken. 

**Steps to reproduce the problem**:

1.  Play Monk
2.  Use Fists of Fury
3.  Cancel channel; profit. 

**Links to Wowhead, YouTube, etc**:

**Comment by Bombrick** [comment]
Stun is removed in legion expect if you have the honor talent

**Comment by Furyan9x** [comment]
Oh, I did not know that. Valhalla is my first time in the Legion xpac, my apologies.

**Comment by Moustachos** [comment]
Can't reproduce this issue, if I cast anything else during FoF's channeling, it breaks.

How exactly do you "cancel" it?

**Comment by Bombrick** [comment]
When you get stunned or incapiated or lose control of your char and you are casting FoF the channeling breaks but the damage and stun(if have honor talent) still continues.

**Comment by Moustachos** [comment]
Tried both (stunned and cast a spell) and FoF properly interrupts in both cases. There must be an additional condition to meet to reproduce this issue :/

**Comment by Ihugyou** [comment]
Btw do u guys have the bug with the visual/animation of fist of fury when i use it and move or my target dies my char stops the visual but still keeps doing the channel and dmg i just don t see the animation and yes i download full wow ....

**Comment by Bombrick** [comment]
yes ^ is an example of what i mean

**Comment by Furyan9x** [comment]
You cancel the channel with movement, sorry I forgot to put that in there.. I start FoF then move in any direction then I can freely cast other spells while it finishes, the only time I've noticed it being canceled is when I get stunned or knocked down before I can cancel it with movement. Regardless, you shouldn't be able to move while it's channeling. Sorry for being vague.
