### ISSUE TITLE
rogue honor talent bugs

### ISSUE THREAD

**Issue by Milofajjour** [Valhalla-Gaming/Tracker#7497]
**Describe the issue you're having**:
 [Maneuverability] [Intent to Kill] [Turn the Tables] [Honor Among Thieves] [Deadly Brew]   [Mind-numbing Poison] [Creeping Venom]
**Explain how you expect it work**: nothing happens all bugged

**Steps to reproduce the problem**: fix it pls 

1. thank you 
2. thank you
3. thank you sir

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
Please report each one of them separately.
