### ISSUE TITLE
Proving Pit quest bug (Troll starting area)

### ISSUE THREAD

**Issue by Gathe3** [Valhalla-Gaming/Tracker#7503]
**Describe the issue you're having**:
The quest asks me to talk to a Darkspear Jailor, but when I talk to him there's no option to click (there should be something saying "I'm ready to face my challenge", but there isn't). Without this, I can't go on with the quest and consequently I am stuck.
**Explain how you expect it work**:
When we talk to the Darkspear Jailor, there should be a text saying "I'm ready to face my challenge" so that we can click it and continue the quest.
How it should work: https://www.youtube.com/watch?v=xsc8UuquNgI
**Steps to reproduce the problem**:
I have no idea since I'm not a coder...

Hoping for this to get fixed so that I can be a troll in this server...

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/1203 you can still be a troll in this server, just skip the quest.

**Comment by Gathe3** [comment]
How do I skip it?

**Comment by Redrian-Valhalla** [comment]
Just cancel the quest and move on in the world, find another place to level, at low levels skipping quests won't make you lose anything.

**Comment by Gathe3** [comment]
Ok, thanks!
