### ISSUE TITLE
Aerylia <Stormflight Master>

### ISSUE THREAD

**Issue by Zalazar69** [Valhalla-Gaming/Tracker#7504]
**Describe the issue you're having**: Does not throw me back down to dalaran anymore

**Explain how you expect it work**: She should be able to talk and have an option where you can port back to dalaran

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Guybrush-VR** [comment]
It'll be repaired in next update! :penguin:
