### ISSUE TITLE
Broken PvP

### ISSUE THREAD

**Issue by revan1986** [Valhalla-Gaming/Tracker#7506]
**Describe the issue you're having**:
1) DK can fly in some battlegrounds.
2) In PvP instances, you use a stat template for your class and spec, all of your gear is nullified other than 3) the Artifact. - doesn't work
4) The strongbox system  - doesn't work
5) In some battlegrounds aliance players are friedly to horde.
6) Mark of Honor currency is missing as reward for BG and as price for old PvP gear

**Explain how you expect it work**:
1) no more flying for DK in BGs
2) - 6) as intended. I think no more description needed because it was described upper.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/item=137642/mark-of-honor
http://www.wowhead.com/item=126914/gold-strongbox

**Comment by Redrian-Valhalla** [comment]
All of these issues are already reported and the developers are aware of them.
