### ISSUE TITLE
immortal Illidan Stormrage in BT

### ISSUE THREAD

**Issue by revan1986** [Valhalla-Gaming/Tracker#7508]
**Describe the issue you're having**:
In last phase of fighting with Illidan when you are freed from Maie stun Illidan should be slained but his hp stops at 1% and he becomes immortal. 

**Explain how you expect it work**:
Illidan should be normally slained.

**Links to Wowhead, YouTube, etc**:
https://www.youtube.com/watch?v=289f4PnhA6E

**Comment by Holylaw** [comment]
Illidan is doable. Try to hit him with AOE on 1%. He will stand down, wait for replies and then he dies and voila :p
