### ISSUE TITLE
immortal Lady Vashj

### ISSUE THREAD

**Issue by revan1986** [Valhalla-Gaming/Tracker#7509]
**Describe the issue you're having**:
When Lady Vashj get in 2nd phase  she will continue to attack you but she will be unattackable. In order to make her attackable, you will need to collect  Tainted Core from Tainted Elemental. But problem is that you cannot use Tainted Core to diable her shield which makes her immortal.

**Explain how you expect it work**:
Her shield should be destroyed by 4 Tainted Cores use to each stream of power from 4 obejects around.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/npc=21212/lady-vashj

**Comment by Holylaw** [comment]
Lady Vashj is doable. You must 1 hit her

**Comment by revan1986** [comment]
How one hit her? She always went to 2nd phase automatically even when I did ebough dmg to ik her. Even if it will be possible there is still no reason why to leave it bugged.

**Comment by Traveler-Valhalla** [comment]
#3012
:P
