### ISSUE TITLE
Shaman "Healing Surge"

### ISSUE THREAD

**Issue by fadida14** [Valhalla-Gaming/Tracker#7513]
**Describe the issue you're having**:
Healing Surge will not use mealstorm to be cast instantly

**Explain how you expect it work**:
I would expect it to work as the tooltip says

**Steps to reproduce the problem**:

1. Create a shaman
2. Unlock Healing Surge
3. Get 20 mealstorm and try to use the ability

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6125 please look for duplicates before posting.
