### ISSUE TITLE
DH : Stuck in storyline. Flight master for quest "On Felbat wings"

### ISSUE THREAD

**Issue by Araldwenn** [Valhalla-Gaming/Tracker#7516]
**Describe the issue you're having:**
When i pick the quest "On felbat wings", talking to the flightmaster Izal Whitemoon validate the quest, but doesn't give me the flight. And if I try to pick a flight, it says "You are too far away from the taxi stand!". Tried reloading, log out, clearing cache, abandon quest and take it again, nothing works. I can't go furter in DH quests.

**Explain how you expect it work:**
Flight master should take me to the Fel Hammer

**Steps to reproduce the problem :**
1. Accept the quest, On Felbat Wings, from Kayn Sunfury at coords 60.5, 44.8 (Illidari Foothold).
2. Travel east to coords 62.5, 44.9, and speak with Izal Whitemoon to take a Fel Bat to The Fel Hammer.
3. Get message "You're too far away"
4. Cry cause you can't go further in DH storyline

**Links to Wowhead, YouTube, etc:**
http://www.wowhead.com/quest=39663/on-felbat-wings

**Comment by Redrian-Valhalla** [comment]
Did you try talking to a GM?

**Comment by Araldwenn** [comment]
In fact, i'm actually on Talador realm (french server), which is supposed to be using the same server and merging servers soon, and i'm waiting for migration.

**Comment by Redrian-Valhalla** [comment]
There's high chance that the migration will not happen due to Talador's low population and the complex operations behind it, I suggest you to start playing directly on Valhalla, the quest you reported is working as intended.
