### ISSUE TITLE
OUT OF RANGE BUG  !!!!!

### ISSUE THREAD

**Issue by Ihugyou** [Valhalla-Gaming/Tracker#7518]
I report this bug again cuz it seems nobody cares its close to imposs to play pvp as mele with this bug 
Fix this ffs its a big problem half of the time i can t hit the target not only me all mele have the problem.
I test on my war,monk,rog,dh,dk same happens.
Read my first report and tag this its need to be fix asap.
https://github.com/Valhalla-Gaming/Tracker/issues/7467

**Comment by Redrian-Valhalla** [comment]
I'll make sure that this gets between our top priorities right now, thank you.
