### ISSUE TITLE
Paladin Blinding Light talent bug

### ISSUE THREAD

**Issue by tribaljet** [Valhalla-Gaming/Tracker#7522]
http://www.wowhead.com/spell=115750/blinding-light

The spell was intended to do a specific percentage of damage to all enemies surrounding the paladin but is currently doing no damage whatsoever to either single or multiple targets while within spell range.

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/5580
