### ISSUE TITLE
Demon hunter disconnect 

### ISSUE THREAD

**Issue by Guggayt** [Valhalla-Gaming/Tracker#7523]
**Describe the issue you're having**: Basicly . sometimes when demon hunters use fel rush in air we get diconnected for server protection against flying hack I believe...

**Explain how you expect it work**: We should not get disconnected from the server for using a freakin ability

**Steps to reproduce the problem**: 

1. Double Jump
2. Fel rush while in the air
3. Do that a couple times.....

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7203
