### ISSUE TITLE
keep getting logged out

### ISSUE THREAD

**Issue by davidehni21** [Valhalla-Gaming/Tracker#7550]
**Describe the issue you're having**: hi i keep getting logged out after the restart

**Explain how you expect it work**:shouldnt get logged out

**Steps to reproduce the problem**:

1. try to stop it
2. do another restart
3. do maintance

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
Your report doesn't contain any useful information, please contact a GM if you have problems connecting.
