### ISSUE TITLE
[Priest][Disc] Mindbender

### ISSUE THREAD

**Issue by Aprophys** [Valhalla-Gaming/Tracker#7559]
**Describe the issue you're having**:
Mindbender still dont regenerate mana.
**Explain how you expect it work**:
Summons a Mindbender to attack the target for 12 sec. You regenerate 0.75% of maximum mana each time the Mindbender attacks.
**Steps to reproduce the problem**:

1. Learned and relearned mindbender
2. still no reg
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=123040/mindbender

**Comment by Moustachos** [comment]
Works just fine.

**Comment by Moustachos** [comment]
Ref #5979
