### ISSUE TITLE
[Priest][Disc] Massdispell

### ISSUE THREAD

**Issue by Aprophys** [Valhalla-Gaming/Tracker#7561]
**Describe the issue you're having**:
Massdispell dont dispell iceblock or divine shield.

**Explain how you expect it work**:
Dispels magic in a 15 yard radius, removing all harmful Magic from 5 friendly targets and 1 beneficial Magic effects from 5 enemy targets. Potent enough to remove Magic that is normally undispellable.

Mass dispel prioritises buffs/debuffs that can only be dispelled using mass dispel before others. So iceblock and divine shield will get priorities over arcane intellect or blessing of might, for example.

**Steps to reproduce the problem**:
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=32375/mass-dispel
https://www.youtube.com/watch?v=K67LS0hQzlc roundabout 5 min u see mage iceblock and priest MD

**Comment by forstix** [comment]
Just disc can dispel them or every priest spec?

**Comment by Aprophys** [comment]
I think every specc can yeah

**Comment by Moustachos** [comment]
Ref #5979
