### ISSUE TITLE
[Monk][Mistweaver] Renewing Mist

### ISSUE THREAD

**Issue by Ncektot** [Valhalla-Gaming/Tracker#7566]
**Describe the issue you're having**:
Renewing Mist buff to increase Vivify healing Spell not proc at all
**Explain how you expect it work**:
Renewing mist has a 4% chance to increase the healing of your next Vivify by 40% called Uplifting Trance.
**Steps to reproduce the problem**:

1. Tried spreading renewing mist in battle ground to all player, but still no buff up. 

**Links to Wowhead, YouTube, etc**:
1. http://www.wowhead.com/spell=115151/renewing-mist (Renewing Mist)
2. http://www.wowhead.com/spell=197206/uplifting-trance (Buff from Renewing Mist)

**Comment by MrNonameNo3** [comment]
The Hot is also not jumping to the next injured ally when healing a target with full health

**Comment by Moustachos** [comment]
Ref #5979
