### ISSUE TITLE
[Quest] Pandaren Monk Starting Zone

### ISSUE THREAD

**Issue by Ncektot** [Valhalla-Gaming/Tracker#7568]
**Describe the issue you're having**:
Pandaren Monk first quest _**The Lesson of the Iron Bough**_ ask to take quest item in the Weapon Rack, but theres no quest item in it, so Pandaren Monk cant complete that quest, preventing to continue the quest chain.

This only happen to Pandaren Monk. Other Pandaren class working just fine.
And somehow player cant change into pandaren monk later using vote point.

**Explain how you expect it work**:
After taking The Lesson of the Iron Bough quest, we go to weapon rack and take the item quest, so the quest can be finished.

**Steps to reproduce the problem**:
1. Take The Lesson of the Iron Bough quest
2. Go to weapon rack and loot it
3. No quest Item in it.

**Links to Wowhead, YouTube, etc**:
1. http://www.wowhead.com/quest=30027/the-lesson-of-the-iron-bough
2. https://www.youtube.com/watch?v=pxcPCYNeHBs

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6032
