### ISSUE TITLE
Rouge Parley in pvp

### ISSUE THREAD

**Issue by Bombrick** [Valhalla-Gaming/Tracker#7569]
Parley is usable on players for the full duration it can be abused in  bg.
[Picture here](http://imgur.com/a/7AZUb)

Link:
[http://www.wowhead.com/spell=199743/parley](http://www.wowhead.com/spell=199743/parley)

**Comment by Moustachos** [comment]
Then it's not Bribe, what's the name of the debuff with that human face icon?

**Comment by Traveler-Valhalla** [comment]
looks like parley :P 
http://www.wowhead.com/spell=199743/parley

**Comment by Bombrick** [comment]
I haven't noticed but looks like traveler got it

**Comment by Bombrick** [comment]
I have changed the title to make it more accurate

**Comment by Moustachos** [comment]
Ref #5979

**Comment by Bombrick** [comment]
Note : fixed
