### ISSUE TITLE
Crash Lightning [Shaman Enhancement] (Spell)

### ISSUE THREAD

**Issue by Rattlehead19** [Valhalla-Gaming/Tracker#7579]
#**Describe the issue you're having**:
The skill Crash Lightning does not work, when used it appears a message that says "You need two melee weapons"

**Explain how you expect it work**:
The skill should be used when you have the 20 points of Maelstorm

**Steps to reproduce the problem**:

1. When generating the 20 points o Maelstorm use Crash Lightning
2. Do not see the message "You need two melee weapons"
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=187874/crash-lightning

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6068
