### ISSUE TITLE
Stormbringer [Shaman Enhancement] (Passive Spell)

### ISSUE THREAD

**Issue by Rattlehead19** [Valhalla-Gaming/Tracker#7580]
**Describe the issue you're having**:
The attacks do not activate at any time Stormbringer
**Explain how you expect it work**:
Each attack with the right hand has the chance to activate Stormbringer 
**Steps to reproduce the problem**:

1. Use basic attacks
2. Each attack with the right hand has the chance to activate Stormbringer
3. Activate Stormbringer and reset the cooldown of Stormstrike

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=201845/stormbringer

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6448
