### ISSUE TITLE
Feral Spirit [Shaman Enhancement] (Spell) 

### ISSUE THREAD

**Issue by Rattlehead19** [Valhalla-Gaming/Tracker#7581]
**Describe the issue you're having**:
When is it used Feral Spirit no invokes the spirits of wolf
**Explain how you expect it work**:
Use the ability and invoke the wolf spirits and generate Maelstorm and do damage
**Steps to reproduce the problem**:

1. Use the ability Feral Spirit 
2. Ivoke the wolf spirits 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=51533/feral-spirit

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6366
