### ISSUE TITLE
Holy Paladin Bugs

### ISSUE THREAD

**Issue by Haeratus** [Valhalla-Gaming/Tracker#7582]
Beacon of the Lightbringer Talent is only giving the Ligh of Dawn +30% healing but not doing the main feature.

Blessing of Freedom spell does not work against all stuns, I casted  it and still got stuned in less than 8 seconds.

Holy Ritual, Ultimate Sacrifice and Spreading the Word Honor Talents are not working at all.

I expect these skills to work like they are written in game (I don`t know if this was necessary).

**Comment by Redrian-Valhalla** [comment]
Please check issues for duplicates, also don't report more issues at the same time unless they're related to each other.
