### ISSUE TITLE
[Arms Warrior] - Focused Rage

### ISSUE THREAD

**Issue by Zulbox** [Valhalla-Gaming/Tracker#7586]
**Describe the issue you're having**: Focused Rage is affecting global cooldown.

**Explain how you expect it work**: You should be able to cast it off GCD.

**Steps to reproduce the problem**:

1. Cast Focused Rage
2. profit
3. ??

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=207982/focused-rage

**Comment by Moustachos** [comment]
Focused Rage isn't affected by GCD as of current version.

**Comment by Moustachos** [comment]
Ref #5979

**Comment by Moustachos** [comment]
Ref #5979
