### ISSUE TITLE
DH Bloodlet bug on shields

### ISSUE THREAD

**Issue by ghost** [Valhalla-Gaming/Tracker#7590]
The talent Bloodlet doesn t get apply on shields for explain i did today bgs and vs priest i use my Throw Glaive on the priest he shield him self and didn t got the bleed effect. not sure if its only priest absorb maybe someother too hope you will check it

Throw Glaive causes targets to bleed for 150% of the damage inflicted over 10 sec. If this effect is reapplied, any remaining damage will be added to the new Bloodlet.

http://www.wowhead.com/spell=206473/bloodlet

**Comment by Ihugyou** [comment]
Eh dude this talent bug is for demon hunters not DK .....

**Comment by Milofajjour** [comment]
Lol 😂 he hasn't said DK its written DH very clearly

**Comment by Moustachos** [comment]
Ref #5979
