### ISSUE TITLE
I´m stuck and a can get to my corpse.

### ISSUE THREAD

**Issue by MichlonS** [Valhalla-Gaming/Tracker#7604]
I cant get to my corpse i bugged through some cover and fell in to void.
cuz of glide bug whet i try to glide and sometimes when i land with glide it disconnect me and this happened when i went in to some stone and i disconnected me and when i logged in i was falling in to the void. Please help me. BTW help>character stuck>teleport to graveyard don´t work for me. 
Character name is Muflon
Please help me.
im level 100.

**Comment by Redrian-Valhalla** [comment]
Please contact a GM for help, or try the unstuck from the website.

**Comment by MichlonS** [comment]
thank ya bruh
