### ISSUE TITLE
Afflock honor talent MIND QUICKNESS not working

### ISSUE THREAD

**Issue by Usernameisntalreadytaken** [Valhalla-Gaming/Tracker#7607]
http://www.wowhead.com/spell=213546/mind-quickness

It should increase my haste by 6%
I kept track of my haste stat (the % and the actual value) while learning and/or unlearning the talent, 0 effect
=> yet another not-working talent
should I really bother reporting every single one of the afflock honor talents?
their status in the tracker shows as "unknown", but you guys do know you didn't script any of them, right? kek

**Comment by Moustachos** [comment]
Works just fine, keep in mind that honor talents are only active in duels / BG or arenas.

**Comment by Moustachos** [comment]
Ref #5979
