### ISSUE TITLE
Afflock honor talent ENDLESS AFFLICTION not working

### ISSUE THREAD

**Issue by Usernameisntalreadytaken** [Valhalla-Gaming/Tracker#7608]
http://www.wowhead.com/spell=213400/endless-affliction

"Increases the duration of Unstable Affliction by 4 sec."

well no it doesn't, it has 0 effect.

**Comment by Moustachos** [comment]
Works just fine, keep in mind that honor talents are only active in duels / BG or arenas.

**Comment by Moustachos** [comment]
Ref #5979
