### ISSUE TITLE
(QUEST) all that Skitters - The Hinterlands

### ISSUE THREAD

**Issue by Kelpo122** [Valhalla-Gaming/Tracker#761]
http://www.wowhead.com/quest=26523/all-that-skitters

You cannot collect the spiders when left clicking on them,

**Comment by Pure-Valhalla** [comment]
Quest now works

**Comment by ATalisan** [comment]
When I click on the spiders, I kill them.

**Comment by VictorTyne** [comment]
The workaround that I found for this quest was to kill the spiders, then kill and loot a nearby troll. The [Skittering Spiderling] will show up in the area loot window.

**Comment by Tregeta** [comment]
Dev note: spellclick

**Comment by Tregeta** [comment]
Quest is fixed on both factions now.
