### ISSUE TITLE
Rogue / Subtlety/ Finishers

### ISSUE THREAD

**Issue by ElrondMcBong1337** [Valhalla-Gaming/Tracker#7611]
At first thank you for all the effort put into making the classes work !
After recent fixes:  

**Describe the issue you're having**:
Deepening Shadows and Relentless Strikes work on Eviscerate but not when using other finishers like Kidney Shot or Nightblade  
**Explain how you expect it work**:
should work with other finishing moves

**Comment by Moustachos** [comment]
Will be fixed on next update.

**Comment by Moustachos** [comment]
Ref #5979
