### ISSUE TITLE
(QUEST) Summit of Fate - The Hinterlands

### ISSUE THREAD

**Issue by Kelpo122** [Valhalla-Gaming/Tracker#762]
http://www.wowhead.com/quest=26517/summit-of-fate

The Sacrificed Vilebranch should give as loot a Spider Idol upon clicking

http://www.wowhead.com/npc=42857/sacrificed-vilebranch#comments
http://www.wowhead.com/item=58228/spider-idol

**Comment by coba999** [comment]
Still didn.t working.

**Comment by GMTyrial** [comment]
The corpses are not lootable

**Comment by Tregeta** [comment]
Quest is fixed on both factions now.
