### ISSUE TITLE
Afflock honor talent AMPLIFY AFFLICTIONS not working

### ISSUE THREAD

**Issue by Usernameisntalreadytaken** [Valhalla-Gaming/Tracker#7629]
http://www.wowhead.com/spell=200290/amplify-afflictions

"Reduces the global cooldown of your Curses, Agony, Corruption, and Unstable Affliction by 0.5 sec."
the GCD for my DoTs & other spells is ALWAYS the same no matter what I cast for every single spell, there's no GCD reduction at all

=> the talent has no effect

**Comment by Moustachos** [comment]
Works just fine, keep in mind that honor talents are only active in duels / BG or arenas.

**Comment by Moustachos** [comment]
Ref #5979
