### ISSUE TITLE
(QUEST) Hunt the Keeper - The Hinterlands

### ISSUE THREAD

**Issue by Kelpo122** [Valhalla-Gaming/Tracker#763]
http://www.wowhead.com/quest=26526/hunt-the-keeper

The mob doesn't spawn
http://www.wowhead.com/npc=42877/mortagya-the-keeper

**Comment by coba999** [comment]
Still did not working. The mob doesn't spawn.

**Comment by Pure-Valhalla** [comment]
Note: Quest is auto-coplete

**Comment by TheRealHoboo** [comment]
Quest is no longer auto-completable.

**Comment by Tregeta** [comment]
creature should spawn next update.
