### ISSUE TITLE
Afflock honor talent CASTING CIRCLE

### ISSUE THREAD

**Issue by Usernameisntalreadytaken** [Valhalla-Gaming/Tracker#7630]
"Summons a Casting Circle for 10 sec. While within the casting circle, the duration of silence and interrupt effects are reduced by 70%. Limit 1."

http://www.wowhead.com/spell=221703/casting-circle

It says I need to be flagged for PVP whenever I try casting it. Not sure it's intended. I'mma try it in BG soon

**Comment by forstix** [comment]
Every honor talent is active in bg\arena or duels outside of those it doesn't work

**Comment by forstix** [comment]
If all those honor talent u reported already tested out of pvp battle plz test them again in duels or some pvp

**Comment by Usernameisntalreadytaken** [comment]
None of them are scripted for locks bro, I'm just doing it as a formality since nobody else reported them not working ("unknown" status in the tracker), and yeah none of those I've been testing worked in BGs either.

**Comment by Moustachos** [comment]
Ref #5979
