### ISSUE TITLE
Rogue / Outlaw / Alacrity (lvl 60 Talent)

### ISSUE THREAD

**Issue by MrNonameNo3** [Valhalla-Gaming/Tracker#7634]
http://www.wowhead.com/spell=193539/alacrity

Gets not only triggered by Finisher moves but als by
http://www.wowhead.com/spell=76806/mastery-main-gauche
and abilities which grand combo points.

**Comment by Moustachos** [comment]
Will be fixed on next update.

**Comment by Moustachos** [comment]
Ref #5979
