### ISSUE TITLE
DH Havoc spec Throw Glaive haste cd bug

### ISSUE THREAD

**Issue by ghost** [Valhalla-Gaming/Tracker#7636]
Describe the issue you're having: The bug is that Throw Glaive doesn t get affected by haste in havoc spec its allways on 10 sec no matter how much haste i have.
Prove http://imgur.com/a/c9HC6

Explain how you expect it work: It should get affected by haste and have a lower CD based on how much haste you have here is a youtube retail vidoe  https://www.youtube.com/watch?v=F41F383pQLE  on 16:35 he shows Throw Glaive spell and u see that the CD is green that means it get affected by haste.

http://www.wowhead.com/spell=185123/throw-glaive

**Comment by Moustachos** [comment]
Works just fine on current version.

**Comment by Moustachos** [comment]
Ref #5979
