### ISSUE TITLE
Shaman spells bug

### ISSUE THREAD

**Issue by stepitz** [Valhalla-Gaming/Tracker#764]
Spells:
Healing stream totem doesn't heal. http://www.wowhead.com/spell=5394/healing-stream-totem

Stormstrike sometimes main hand weapon doesn't hit. http://www.wowhead.com/spell=17364/stormstrike

Enhanced weapons doesn't work: never trigger 3 hits of main weapon and never trigger fire damages of off hand weapon http://www.wowhead.com/spell=166221/enhanced-weapons

Talents:
Frozen power doesn't work: frost shock never root the target. http://www.wowhead.com/spell=63374/frozen-power

Nature's guardian doesn't work: it doesn't increase maximum hp by 25% when hp drop below 30%. http://www.wowhead.com/spell=30884/natures-guardian

**Comment by Kilrathe** [comment]
I am also having problems with my healing stream totem not healing anyone including my shaman. Can you look into this please?
