### ISSUE TITLE
Illidan StormRage Bug

### ISSUE THREAD

**Issue by Haeratus** [Valhalla-Gaming/Tracker#7643]
I know you have to kill him slowly or else you bug him, the thing is, I killed him the first time I did Black Temple, but the second time I messed up and bursted him, then he because immortal and we know this problem very well, BUT, the third and fourth time I did Black Temple, no matter how ULTRA SLOW I would damage him, he would enter a state where he cannot have less than 1 health. This is so frustating, I have been fighting Illidan for weeks, I just want a Chestguard of the Forgotten Conqueror (Paladin version) for a simple Transmog that will not even make me strongher, it has a drop chance of 70% please help me, my character name is Haeratus thank you for your time.

**Comment by Redrian-Valhalla** [comment]
Hello, it's very unlikely for our development team to focus on old and unconfirmed issues like this, I can only suggest you to try killing him again, otherwise you can just get your transmog piece from the shop, that's the easiest way.

**Comment by Haeratus** [comment]
okay =(
