### ISSUE TITLE
assassination rogue prey on the weak talent

### ISSUE THREAD

**Issue by Milofajjour** [Valhalla-Gaming/Tracker#7648]
**Describe the issue you're having**:
prey on the weak is not working.
**Explain how you expect it work**:
all kinds of damage should increase on a sapped or stunned target by 10%
**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=131511/prey-on-the-weak

**Comment by Moustachos** [comment]
It works.

**Comment by Moustachos** [comment]
Ref #5979
