### ISSUE TITLE
assassination rogue Shiv honor talent

### ISSUE THREAD

**Issue by Milofajjour** [Valhalla-Gaming/Tracker#7657]
**Describe the issue you're having**:
 Shiv applying to the target but no damage is done from it.
**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=206328/shiv

**Comment by Moustachos** [comment]
Shiv's direct damage work just fine and the Neurotoxin isn't meant to deal any damage, only increase the cooldown of abilities and that part works too.

**Comment by Moustachos** [comment]
Ref #5979
