### ISSUE TITLE
Demon Hunter: Havoc: Metamorphosis Bug

### ISSUE THREAD

**Issue by Heartglen** [Valhalla-Gaming/Tracker#7662]
**Describe the issue you're having**:
Casting **_Metamorphosis_** at max range **_sometimes_** just leaps you there, cause the AOE damage, but not use the cooldown or transform you.
**Explain how you expect it work**:
Suppose to leap, transform, then goes on cooldown
**Steps to reproduce the problem**:

1. Click on **_Metamorphosis_**, go to max range.
2. Use spell, it will **_sometimes_** leap you and not go on cooldown or transform you.

Really abuseable in PVP

**Links to Wowhead, YouTube, etc**:

**Comment by Ihugyou** [comment]
True sometimes it bugs out ....

**Comment by Bloodshade** [comment]
Please fix this in next patch, so many players are abusing this and ruining all Battlegrounds.

**Comment by Moustachos** [comment]
Ref #5979
