### ISSUE TITLE
[Priest][Discipline/Holy][Talent]Divine Star

### ISSUE THREAD

**Issue by Rhyrem** [Valhalla-Gaming/Tracker#7684]
**Describe the issue you're having**: When you use Divine star and there is some kind of obstacle in it's path, usually it gets stuck in the place until the cooldown of the skill ends, and sometimes it reaches the maximum distance and doesn't return but you can't see it either (it's like the star disappeared).

**Explain how you expect it work**: The star should travel all the distance and then come back to the priest, without getting stuck in place until it finishes the cooldown.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
WowHead: http://www.wowhead.com/spell=110744/divine-star
YouTube: https://www.youtube.com/watch?v=wzh8jPHmxgc
At 0:33 the priest uses Divine Star and then it comes back even if he's not completely upstairs.

**Comment by Warjakh** [comment]
You are posting several issues that are already posted on our Issue Tracker. Please search for issues before you post. 

Thank you.

**Comment by Rhyrem** [comment]
Well, I searched in the Priest label and didn't see any of those bugs reported, that's why I opened them, It might be because I just made the account today and I'm not used to Github. My apologies, I'll try
