### ISSUE TITLE
dh veng artifact spell

### ISSUE THREAD

**Issue by yebadal** [Valhalla-Gaming/Tracker#7690]
**Describe the issue you're having**:

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. spell artifact traits (Defensive Spikes) is not working at all
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=212829/defensive-spikes

**Comment by Analog-Valhalla** [comment]
Duplicate report #8801
