### ISSUE TITLE
[Protection Paladin] Tyr's Enforcer (Artifact Elite Trait)

### ISSUE THREAD

**Issue by Tolno** [Valhalla-Gaming/Tracker#7691]
**Describe the issue you're having**: It procs on every damaging ability, even each tick of [Consecration](url)

**Explain how you expect it work**: It should only add an aoe effect to _Avenger's Shield_

**Steps to reproduce the problem**:

1. Grind artifact path to unlock the elite trait **Tyr's Enforcer**
2. Go pull a pack of mobs, or even try a BG, and use your normal abilities, like _Consecration_, _Judgment_...
3. Look the raining damage everywhere around your ennemies, and in your combat log

**Links to Wowhead, YouTube, etc**:
[http://www.wowhead.com/spell=209474/tyrs-enforcer](url)

**Comment by Zulbox** [comment]
High priority on this, please. Too overpowered.

**Comment by Moustachos** [comment]
Ref #5979
