### ISSUE TITLE
Warrior Fury Whirlwind damage is broken 

### ISSUE THREAD

**Issue by bewilder1** [Valhalla-Gaming/Tracker#7694]
**Describe the issue you're having**:
So i just got instantly annihilated just by 2 times whirlwind cast. I assume the person took the talent.
**Explain how you expect it work**:
Well obviously, it should not deal this much of damage. The talent is wrecking ball which is increasing 200% of whirlwind damage but it felt like increased 20000% damage. 
**Steps to reproduce the problem**:

1. Meet a fury warrior
2. Let him spam whirlwind
3. Rekted in no time 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=215569/wrecking-ball

This is the screenshot, cropping to avoid name shaming 
![screenshot_5](https://cloud.githubusercontent.com/assets/23197198/20388059/b59e1962-acf5-11e6-8a75-12b5d204cbb7.png)

**Comment by Sabakyo** [comment]
The issue appears to be that the proc should be a chance to proc, currently it appears to be procing 100% of the time and lasts 10 seconds rather than being turned off after use of Whirlwind. - Submitted by player.

**Comment by Mr-Rager** [comment]
#7700

**Comment by bewilder1** [comment]
well yea thats the problem too. but will it be like that forever ? well i guess pvp will be full of fury warrior, palladin protection, brewmaster, sub rogue, outlaws, marksman hunter, survival hunter. easy win. you'll get annihilated by just 2 times whirlwind with battle cry up if you are not a class that use plate armour.

**Comment by Moustachos** [comment]
Ref #5979
