### ISSUE TITLE
Utgarde Pinnacle 

### ISSUE THREAD

**Issue by darkomkd** [Valhalla-Gaming/Tracker#7696]
**Describe the issue you're having**:
when u get to second boss the harpoons dont work there buged
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Traveler-Valhalla** [comment]
#4884

**Comment by darkomkd** [comment]
skadi dosent work
