### ISSUE TITLE
Monk / Mistweaver / Mastery: Gust of Mists

### ISSUE THREAD

**Issue by MrNonameNo3** [Valhalla-Gaming/Tracker#7700]
Not working

Wowhead description: "Effuse, Renewing Mist, Enveloping Mist, and Vivify also cause a gust of healing mists, instantly healing the primary target for (0.01% of Spell power)."

http://www.wowhead.com/spell=117907/mastery-gust-of-mists

**Comment by cesium136** [comment]
this is a big issue because master provides a big source of healing, it usually is in the top 3 abillities that did the most healing

**Comment by Moustachos** [comment]
Ref #5979
