### ISSUE TITLE
Habilidades bugs Chami Mejora

### ISSUE THREAD

**Issue by MyJ3** [Valhalla-Gaming/Tracker#7702]
**Describe the issue you're having**:
1. La habilidad no funciona porque dice que necesitas tener equipada un arma cuerpo a cuerpo, cosas que tengo las 2 del chami mejora equipadas.
2. La habilidad del talento no funciona porque no carga contra el enemigo pero si lo llama, es decir, no se activa la habilidad pero si lo provoca.
3. Como se puede apreciar en las fotos no sale la barra de voragine cosa que en el elemental si sale y no desaparece.

**Links to Wowhead, YouTube, etc**:
http://es.wowhead.com/spell=187874/estallido-de-relampagos
http://es.wowhead.com/spell=202498/embestida-feral
 
![1](https://cloud.githubusercontent.com/assets/23507886/20437421/2f1f7812-adb4-11e6-956c-534f61314f1c.jpg)
![2](https://cloud.githubusercontent.com/assets/23507886/20437422/2f220064-adb4-11e6-9d12-4ac08e1a585b.jpg)

#6754

**Comment by Mr-Rager** [comment]
#6754 The issue has already been addressed, thank you for your report. 
Please report issues in English, as is the standard language.
