### ISSUE TITLE
[Blood Death Knight] Icebound Fortitude (Ability)

### ISSUE THREAD

**Issue by Tolno** [Valhalla-Gaming/Tracker#7707]
**Describe the issue you're having**: Not even present in speelbook

**Explain how you expect it work**: It should be there, and it's a pretty important defensive cooldown for Blood DKs

**Steps to reproduce the problem**:

1. Spec to blood DK
2. Open Spellbook
3. Look for _Icebound Fortitude_

**Links to Wowhead, YouTube, etc**:
[http://www.wowhead.com/spell=48792/icebound-fortitude](url)

**Comment by llamalama** [comment]
This is not currently an issue. This was only added to blood spec in 7.1 and we are still on 7.0.3

http://us.battle.net/wow/en/game/patch-notes/7-1-0

**Comment by Moustachos** [comment]
Ref #5979
