### ISSUE TITLE
The Nexus Raid bug

### ISSUE THREAD

**Issue by dark1166** [Valhalla-Gaming/Tracker#7711]
In Northrend, in the raid The Nexus where you fight Malygos I get to the last stage where I need to ride a dragon to kill Malygos. the dragon ,that I need to ride, doesnt spawn and I fall to my death.   

Here is a youtube video of the fight: https://www.youtube.com/watch?v=blhbenESBFk

**Comment by Traveler-Valhalla** [comment]
#2865

**Comment by Mr-Rager** [comment]
The issue has already been identified. Thank you for your report.
