### ISSUE TITLE
Tyr's Enfocer Palladin Protection Trait

### ISSUE THREAD

**Issue by bewilder1** [Valhalla-Gaming/Tracker#7714]
**Describe the issue you're having**:
It hits multiple times with single cast of avenger shield
**Explain how you expect it work**:
Should not be like that
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=209474/tyrs-enforcer
![screenshot_1](https://cloud.githubusercontent.com/assets/23197198/20458743/9740d888-aedf-11e6-8777-793638fc0905.png)

**Comment by Tolno** [comment]
I already issued that, it's still in the same page... FFS use your eyes. 
And btw, it's not that it hits several times with on avenger shield, it's that it actually hits and aoe with every single damaging ability, even consecration ticks. So if you are 5 players close to each other, every consecration tick will add 5x Tyr's Enforcer damage... That's insane, yep.

**Comment by Moustachos** [comment]
Ref #5979
