### ISSUE TITLE
[Monk][Brewmaster] Fortifying Brew

### ISSUE THREAD

**Issue by Hemoglobine-Valhalla** [Valhalla-Gaming/Tracker#7719]
**Describe the issue you're having**:
Fortifying Brew does not increase the health by 20%
**Explain how you expect it work**:
Turns your skin to stone for 15 sec, increasing your current and maximum health by 20%, increasing the damage you delay with Stagger by an additional 20%, and reducing all damage you take by 20%.
**Steps to reproduce the problem**:

1.  Use Fortifying Brew.
2.  Notice your Health did not get increased as the buff and spell says it should.

**Links to Wowhead, YouTube, etc**:

http://www.wowhead.com/spell=120954/fortifying-brew

**Comment by Nightcap** [comment]
The other effects seem like they are not working as well.

**Comment by Moustachos** [comment]
Ref #5979
