### ISSUE TITLE
Rogue / Outlaw / Alacraty (lvl 90 Talent)

### ISSUE THREAD

**Issue by MrNonameNo3** [Valhalla-Gaming/Tracker#7724]
It should have a 20% chance per Combo Point to stack once.
No matter what, it doesnt proc more than once at all.

http://www.wowhead.com/g00/spell=193539/alacrity

**Comment by Moustachos** [comment]
Works just fine.

**Comment by MrNonameNo3** [comment]
No its not. it should have a chance per combo point to proc. which is not the case
