### ISSUE TITLE
Rite of the Winds quest in Mulgore

### ISSUE THREAD

**Issue by Lassittor** [Valhalla-Gaming/Tracker#7725]
**Describe the issue you're having**: You're supposed to drink the water, turn into a bird, and fly to Bloodhoof Village. But you drink it, a bird briefly appears, and then nothing happens. The quest continues to say to drink the water. You can physically run to Bloodhoof Village and turn it in, thankfully, if you figure out you can do that. It took me a while.

Rite of Vision is also broken. The Ghost Wolf appears but does not run off to lead you to your destination.

**Explain how you expect it work**: You should turn into a bird and fly to the next questing area. Then the ghost wolf should run to the quest turn in NPC but just stands there.

**Steps to reproduce the problem**: Try to do the quest Rite of the Winds in Mulgore, around level 5. Then try to do Rite of Vision.

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7087
