### ISSUE TITLE
DK - Starting zone quest bugged

### ISSUE THREAD

**Issue by senprom** [Valhalla-Gaming/Tracker#7730]
**Describe the issue you're having**:
The quest "Death Comes From On High" where you go to the village and burn the houses is bugged, you have no abilities as the eye and there is no way to complete the quest
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Mr-Rager** [comment]
The issue has already been taken notice of. Thank you for you're report
