### ISSUE TITLE
Rogue / Alacraty (lvl 90 Talent)

### ISSUE THREAD

**Issue by MrNonameNo3** [Valhalla-Gaming/Tracker#7733]
http://www.wowhead.com/spell=193539/alacrity

//
OK, next try.

Its supposed to have a chance per combo point to proc 1 Stack of Alacraty.
Means that you have the chance to stack up to 5 Alacraty or even 6 Alacraty with the lvl 45 Talent Deeper Stratagem when using any finisher move.
Currently you can only get 1 stack of Alacraty per finisher move. No matter how many combo points your finisher move consumes.
//
Ok shame on me. Thats not how it works.
But still: it should have a chance to proc 2 stacks which is not the case right now.

**Comment by Guybrush-VR** [comment]
> But still: it should have a chance to proc 2 stacks which is not the case right now.
7.1.5 though

**Comment by Moustachos** [comment]
Closing this issue, reporting issues for future builds is irrelevant.

**Comment by Moustachos** [comment]
Ref #5979
