### ISSUE TITLE
Resto Druid/ Talent/ Soul Of The Forest

### ISSUE THREAD

**Issue by Milofajjour** [Valhalla-Gaming/Tracker#7734]
**Describe the issue you're having**:
when i get soul of the forest proc from my swiftmend and cast wild growth its not taking the 75% increased healing its staying the same.
**Explain how you expect it work**:
cast swiftmend get the SOTF proc and cast wild growth with huge increased healing.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=158478/soul-of-the-forest

**Comment by Mr-Rager** [comment]
The issue has already been addressed. Thank you for your report. #7547
