### ISSUE TITLE
spell shear demon hunter veng

### ISSUE THREAD

**Issue by yebadal** [Valhalla-Gaming/Tracker#7739]
**Describe the issue you're having**:

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. shear
2. when i used spell shear i must see soul fragments buf and getting one big orb not little one 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=203782/shear

**Comment by Mr-Rager** [comment]
Please re-submit the issue with more details. Shear has a *chance* to shatter the enemy soul, and does not generate in one big orb, but scattered fragments around the mob.
