### ISSUE TITLE
Firestone Point

### ISSUE THREAD

**Issue by AuraChan** [Valhalla-Gaming/Tracker#774]
There are serveral NPC's missing or phasing out at this location. The missing NPC's are:
Tauna Skychaser  http://www.wowhead.com/npc=37834/tauna-skychaser
Mahka  http://www.wowhead.com/npc=37812/mahka
Larhasha  http://www.wowhead.com/npc=37836/larhasha
Zang'do  http://www.wowhead.com/npc=37817/zangdo
Norn Redearth  http://www.wowhead.com/npc=37835/dorn-redearth

Area Details:
http://wow.gamepedia.com/Firestone_Point

**Comment by Tregeta** [comment]
fixed next update
