### ISSUE TITLE
Destruction Warlock : Rain of Fire

### ISSUE THREAD

**Issue by Zenii** [Valhalla-Gaming/Tracker#7742]
**Describe the issue you're having**: Rain of Fire

**Explain how you expect it work**: Not working.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=196914/rain-of-fire

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7108
