### ISSUE TITLE
Destruction Warlock : Chanell Demonfire

### ISSUE THREAD

**Issue by Zenii** [Valhalla-Gaming/Tracker#7747]
**Describe the issue you're having**:  Chanell Demonfire tallent
**Explain how you expect it work**: Not Working

**Steps to reproduce the problem**: Not working

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=196447/channel-demonfire

**Comment by Mr-Rager** [comment]
The issue has already been addressed. Thank you for your report. #6319
