### ISSUE TITLE
Destro lock : Dimensional Rift Artifact spec

### ISSUE THREAD

**Issue by Zenii** [Valhalla-Gaming/Tracker#7752]
**Describe the issue you're having**: Dimensional Rift Artifact Spec

**Explain how you expect it work**: Not working

**Steps to reproduce the problem**: Not working

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=196586/dimensional-rift

**Comment by Mr-Rager** [comment]
The issue has already been addressed. Thank you for your report. 
#6832
