### ISSUE TITLE
Sludge Blecher

### ISSUE THREAD

**Issue by aetoni** [Valhalla-Gaming/Tracker#7754]
**Describe the issue you're having**: sludge blecher talent does not work

**Explain how you expect it work**: raise dead should raise abomination instead of a ghoul however nothing happens

**Steps to reproduce the problem**:

1. pick sludge blecher talent
2. use raise dead
3. abomination appears instead of a ghoul

**Links to Wowhead, YouTube, etc**:

**Comment by Mr-Rager** [comment]
The issue has already been taken notice of. Thank you for your report.
#6991
