### ISSUE TITLE
Death Knight / Unholy / Talents / Bursting Sores

### ISSUE THREAD

**Issue by aetoni** [Valhalla-Gaming/Tracker#7755]
**Describe the issue you're having**:
bursting sores talent does no damage to the nearby enemies
**Explain how you expect it work**: use scourge strike on the enemy with festering wound on it and it deals right amount of damage to the nearby enemies
![screenshot_2](https://cloud.githubusercontent.com/assets/22433174/20596046/e0b7c174-b23c-11e6-9016-c59948bbf76c.png)

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by MrNonameNo3** [comment]
Demon Hunter? Death Knight?! OMG WHAT IS IT!!! NOBODY KNOWS!

**Comment by theprototyze** [comment]
Please verify the 50% more damage as well when fixing this.

**Comment by Moustachos** [comment]
Ref #5979
