### ISSUE TITLE
Death Knight / Unholy / Talent / Epidemic 

### ISSUE THREAD

**Issue by aetoni** [Valhalla-Gaming/Tracker#7756]
**Describe the issue you're having**: epidemic talent does no damage to the targets infected with virulent plague 

**Explain how you expect it work**: epidemic does right amount of damage to all enemies with virulent plague and also do right amount of damage to nearby targets 
![screenshot_3](https://cloud.githubusercontent.com/assets/22433174/20596142/486b066e-b23d-11e6-8d54-7b965cfed310.png)

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by VictorTyne** [comment]
Epidemic also affects (and thus taunts) all enemies within its range. So using it causes every mob within 100 yards to come attack you.

Epidemic should only affect targets affected by Virulent Plague.

**Comment by Moustachos** [comment]
Ref #5979
