### ISSUE TITLE
Hunets articaft Legacy of windrunners is bugged 

### ISSUE THREAD

**Issue by darkomkd** [Valhalla-Gaming/Tracker#7757]
**Describe the issue you're having**:
![wowscrnshot_112416_131704](https://cloud.githubusercontent.com/assets/23524357/20598261/9b81f578-b248-11e6-8197-5c3871d33ec0.jpg)
![wowscrnshot_112416_131746](https://cloud.githubusercontent.com/assets/23524357/20598265/a25ca1b8-b248-11e6-8611-636c66773b27.jpg)
Pls fix this cuz i do 200k dps on dolls in sw and here i do this pathtic dps
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Hemoglobine-Valhalla** [comment]
If you hit a lower level dummy you will do higher damage, plus the dummy doesnt have armor while mobs does, that decrease your damage, since they reduce physicall damage, which is what you do with arrows.

**Comment by darkomkd** [comment]
dude still 4k dps with artifact

**Comment by MrNonameNo3** [comment]
50k dps with lvl 100, 372 ilvl.
Doing that with my lvl 110 810 ilvl ele shammy LOL
