### ISSUE TITLE
Rogue / Outlaw / Greed (Artifact Trait)

### ISSUE THREAD

**Issue by MrNonameNo3** [Valhalla-Gaming/Tracker#7759]
- Does not heal the correct amount

**Comment by Moustachos** [comment]
Healing amount is just fine.

**Comment by Moustachos** [comment]
Ref #5979

**Comment by Moustachos** [comment]
My bad, there was indeed something off with the amount, it will be fixed (increased) on next update.

**Comment by MrNonameNo3** [comment]
thx mate <3
