### ISSUE TITLE
Zone and Class

### ISSUE THREAD

**Issue by AngryWolf123** [Valhalla-Gaming/Tracker#7764]
NorthWatch Supply Crate and the Northrend lugs arent moving in the north watch foothold in duroter, also arms warrior generate like 50 rage per hit 

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
No multiple issues in the same report, also please check for duplicates.
