### ISSUE TITLE
Puddle Stomping

### ISSUE THREAD

**Issue by raafif** [Valhalla-Gaming/Tracker#7767]
**Describe the issue you're having**:
Tidal Strider not scripted
**Explain how you expect it work**:
Tidal Striders to spawn
**Steps to reproduce the problem**:

1.  Start Quest
2. Arrive at location
3.  No Tidal Striders

**Comment by Cidragon** [comment]
There are plenty of them.

![Tidal Strider](http://i.imgur.com/yUdfln4.png)
