### ISSUE TITLE
Twilight of the Dawn Runner

### ISSUE THREAD

**Issue by AuraChan** [Valhalla-Gaming/Tracker#777]
When selecting dialog for Ithania to escape nothing happens. She should try to escape once you click on the dialogue.

Quest Details:
http://www.wowhead.com/quest=9437/twilight-of-the-dawn-runner

**Comment by Cidragon** [comment]
It's working for me :)

**Comment by VictorTyne** [comment]
Confirmed the quest works. You have to follower Ithania out to the road once you trigger her in order to get the quest ping.

**Comment by Cidragon** [comment]
Thanks you very much!
