### ISSUE TITLE
Obsidian Nightwing Mount

### ISSUE THREAD

**Issue by B4RdF0X** [Valhalla-Gaming/Tracker#7770]
**Describe the issue you're having**: When I mount onto the Obsidian Nightwing, it's mounted to itself and other players can't get on it. Also it seems to be bigger than normal.

**Explain how you expect it work**: I want that it's the normal size and speed, and others can get on it.

**Steps to reproduce the problem**: 

1. I just need to summon the mount. The problem appears every time.

Here's a screenshot of how it looks like:
![wowscrnshot_112316_204325](https://cloud.githubusercontent.com/assets/23732031/20613552/6ee590e2-b2c5-11e6-9828-6a05713d5024.jpg)

**Comment by GM-Pyromanic** [comment]
Duplicate report 

#7668
