### ISSUE TITLE
Apocalypse [unholy death knight artifact spell]

### ISSUE THREAD

**Issue by aetoni** [Valhalla-Gaming/Tracker#7773]
**Describe the issue you're having**: apocalypse deals damage but it doesnt burst festering wounds and it does not summon army of the dead members

**Explain how you expect it work**:use the apocalypse , it deals right amount of damage to the target and bursts all festereing wounds then summon the right amount of army of the dead members depens on how much festering wounds did burst durring the attack
![screenshot_4](https://cloud.githubusercontent.com/assets/22433174/20621481/f85db442-b2fe-11e6-9d23-e9f772107016.png)

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7062
