### ISSUE TITLE
Warlock Spell: Drain Soul

### ISSUE THREAD

**Issue by ATalisan** [Valhalla-Gaming/Tracker#7774]
Drain Soul does not work to grant a Soul Shard when the target dies while you are draining it.

Tested with an Affliction Warlock at level 33.

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6739

**Comment by VictorTyne** [comment]
#6739 is not the same issue. 6739 is "Drain Soul deals abnormally low damage". This one is "Drain Soul does not give you soul shards." Affliction warlocks don't have any other way to get soul shards at lower levels, so this bug is a huge problem. This thread should not have been closed.

**Comment by VictorTyne** [comment]
Okay, so that issue got added to the other thread too. Hopefully that won't make it less searchable or just bury the problem under a misleading title.
