### ISSUE TITLE
Resto Druid Cannot Use Prowl.

### ISSUE THREAD

**Issue by avaksx** [Valhalla-Gaming/Tracker#7775]
**Describe the issue you're having**: As Resto Druid I Cannot Use Prowl..

**Explain how you expect it work**: Working Prowl in Resto Spec.

**Steps to reproduce the problem**: Fix it.

1. Fix.
2. 
3.

**Links to Wowhead, YouTube, etc**:

**Comment by Milofajjour** [comment]
Ive already reported this long time ago

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7158
