### ISSUE TITLE
Feral Druid Artifact Weapon.

### ISSUE THREAD

**Issue by avaksx** [Valhalla-Gaming/Tracker#7776]
**Describe the issue you're having**: Nothing Happens When I Click Feral Artifact Spell. It Isn't even going on cooldown. Like it's frozen. About a month ago on changelog it said it is scripted but it isn't.

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. Try.
2. See it's not working.
3. Fix it.

**Links to Wowhead, YouTube, etc**:

**Comment by Moustachos** [comment]
It works just fine.

**Comment by avaksx** [comment]
It doesn't work for me and for 2 more feral i contacted in game. So please make sure it works or Re-review this issue.
