### ISSUE TITLE
Anzu Sethekk Halls

### ISSUE THREAD

**Issue by RishkaM** [Valhalla-Gaming/Tracker#7777]
**Describe the issue you're having**:
In the Sethekk Halls (on heroic) Anzu (the raven boss) should be in his chamber without the need to summon him. 

**Explain how you expect it work**:
During BC times he needed to be spawned through an item only obtainable by druids, however, since WOTLK this should no longer be necessary. Right now it's still asking for the item to spawn him.

http://www.wowhead.com/npc=23035/anzu#comments

**Comment by Traveler-Valhalla** [comment]
#4908
