### ISSUE TITLE
Sudden Doom

### ISSUE THREAD

**Issue by GeneralCaveman** [Valhalla-Gaming/Tracker#778]
http://www.wowhead.com/spell=49530/sudden-doom

The effect seems to activate outside of unholy presence and when it does activate, it still consumes/requires runic energy.

**Comment by Tregeta** [comment]
Copy/Paste from @CorentinDodon report.

This effect activates every autoattacks.
This effect activates regardless of the active presence.
This effect works and makes the next Death Coil free.

**Comment by Moustachos** [comment]
Ref #2266
