### ISSUE TITLE
Marked for Death , and Assassination Artifact Trait

### ISSUE THREAD

**Issue by bewilder1** [Valhalla-Gaming/Tracker#7783]
**Describe the issue you're having**:
Marked for Death doesn't reset when the target effected by MoD dies.
Urge to Kill artifact trait does not work, using vendetta doesn't refill your energy
**Explain how you expect it work**:
MoD should be reseted when the target dies
Vendetta should be refilling your energy when urge to kill artifact trait taken
**Steps to reproduce the problem**:

1. Cast MoD, kill the target. Take urget to kill, use vendetta
2. MoD still on CD when the target dies, vendetta does not refill your energy
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=137619/marked-for-death
http://www.wowhead.com/spell=192384/urge-to-kill

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7158
