### ISSUE TITLE
Assassination Rogue/ Trait/ urge to kill

### ISSUE THREAD

**Issue by Milofajjour** [Valhalla-Gaming/Tracker#7784]
**Describe the issue you're having**:
Urge to kill is bugged again after the update it is not refilling my entire energy anymore.
**Explain how you expect it work**:
Using vendetta refills your energy.
**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=192384/urge-to-kill

**Comment by Moustachos** [comment]
Nothing changed with the update.

**Comment by Moustachos** [comment]
Will be hotfixed soon.

**Comment by Moustachos** [comment]
Ref #5979
