### ISSUE TITLE
Assassination Rogue/ Trait/ From The Shadows

### ISSUE THREAD

**Issue by Milofajjour** [Valhalla-Gaming/Tracker#7785]
**Describe the issue you're having**:
Fromthe shadows is not working anymore after activating my vendetta. It's bugged after the patch update.
**Explain how you expect it work**:
Use vendetta on the target and From Shadows yrait should activate dealing alot of damage to the target
**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=192428/from-the-shadows

**Comment by Moustachos** [comment]
Nothing changed with the update.

**Comment by Moustachos** [comment]
Will be hotfixed soon.

**Comment by Moustachos** [comment]
Ref #5979
