### ISSUE TITLE
Patch 7.1 Afflock UNSTABLE AFFLICTION - literally broken

### ISSUE THREAD

**Issue by Usernameisntalreadytaken** [Valhalla-Gaming/Tracker#7788]
http://www.wowhead.com/spell=30108/unstable-affliction

Cast the spell, it eats up a soul shard, no DoT is applied on your target.
100% broken

"Afflicts the target with (386.4% of Spell power) Shadow damage over 8 sec. You may afflict a target with up to 5 Unstable Afflictions at once.

If dispelled, deals [(96.6% of Spell power) * 400 / 100] damage to the dispeller and silences them for 4 sec.

Affliction (Level 26)
Refunds 1 Soul Shard if the target dies while afflicted."

This is the main afflock DoT and the basis for ALL warlock synergies - be it talent or artifact skills.

**Comment by Mr-Rager** [comment]
The issue has already been addressed. Thank you for your report. #6383 #7275

**Comment by Moustachos** [comment]
Ref #5979
