### ISSUE TITLE
Outlaw Rogue" Marked for Death"

### ISSUE THREAD

**Issue by SanDrilLa187** [Valhalla-Gaming/Tracker#7797]
"Marked for Death" should be reset, when i kill somone within a minute, that don´t happen.
Thank you.

**Comment by bewilder1** [comment]
Its already been addressed. Not only for outlaw, but assassination too.

**Comment by GM-Pyromanic** [comment]
Duplicate report please use the search function to make sure no report has already been created on the issue.

#7778
