### ISSUE TITLE
Bugged Quest "Solanian's Belongings"

### ISSUE THREAD

**Issue by Yeowza** [Valhalla-Gaming/Tracker#7800]
**Describe the issue you're having**:
I can't finish Quest , When i press "complete quest nothing happend"
**Explain how you expect it work**:
This button should react
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by GM-Pyromanic** [comment]
Fixed after next restart.
