### ISSUE TITLE
Artifact weapons

### ISSUE THREAD

**Issue by salfjiorejgioe** [Valhalla-Gaming/Tracker#7802]
Well normally you must make a class hall quest when you get to dalaran some mob will appear to be your minion / guardian and it has a quest this quest is going to take you to one of your trainers in dalaran when u give the quest back you will have to choose one of the artifact weapons you'll get , then you will go to the flight master's place krasus's landing to give the flight master a quest back and you'll get a new one then another npc will rise and he'll fly with you to your class hall and there you will go through a scenario with diferent stages once u finish it u get the artifact weapon

**Comment by Redrian-Valhalla** [comment]
You can get your artifact weapon from the NPC in your capital city, we're already aware of the rest.
