### ISSUE TITLE
[Quest] Show Gnomercy

### ISSUE THREAD

**Issue by SunRaysFalls** [Valhalla-Gaming/Tracker#7803]
Draenei race/ Hunter class 
Quest: Show Gnomercy 
After i do what quest say and return to quest giver, after i select reward and press Complete quest, nothing happens. 
Things i tried so far: Relog on character, Redo quest few times, Disabled/deleted Addons. (None helped) .

**Comment by GM-Pyromanic** [comment]
http://www.wowhead.com/quest=9537/show-gnomercy

**Comment by SunRaysFalls** [comment]
looked there and will try see if can complete it.  Thank you for reply.

**Comment by GM-Pyromanic** [comment]
Fixed after next restart.
