### ISSUE TITLE
Resto Druid - Overgrowth

### ISSUE THREAD

**Issue by avaksx** [Valhalla-Gaming/Tracker#7804]
**Describe the issue you're having**: Honor level 50 Talent "Overgrowth" Doesn't work.

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. fix
2. fix
3. fix

**Links to Wowhead, YouTube, etc**:

**Comment by GM-Pyromanic** [comment]
Duplicate report please use the search feature before opening a new report to make sure there is not already a report on the issue.

#7546
