### ISSUE TITLE
Updateing

### ISSUE THREAD

**Issue by ghabhy** [Valhalla-Gaming/Tracker#7805]
**Describe the issue you're having**:
i cant open vallhala wow after this new update
**Explain how you expect it work**:
when i try to open the game it says EVERYTIME that it had an update to make.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Zulbox** [comment]
Post a screenshot, please.

**Comment by ghabhy** [comment]
![image](https://cloud.githubusercontent.com/assets/23580541/20640966/22fa7a4e-b3f6-11e6-8062-894a00ae053e.png)

**Comment by ghabhy** [comment]
there it is

**Comment by SunRaysFalls** [comment]
get Battle.net app and locate your game path. After locating game path let Battle.net update your game to latest version (7.1.0 xxxxx). after that use the new launcher released yesterday and replace old launcher. Now you should be able enter game. (servers down for the moment.

**Comment by ghabhy** [comment]
where can i get the new laucher?

**Comment by SunRaysFalls** [comment]
http://d.valhalla-realms.com/Valhalla_Launcher.7z

**Comment by ghabhy** [comment]
thank you :)

**Comment by SunRaysFalls** [comment]
You''re welcome. Hope your problems are fixed

**Comment by GM-Pyromanic** [comment]
Please use the forums for issues like this the tracker is for in game bugs only not updating issues for the client.
