### ISSUE TITLE
Legion Dalaran empty.

### ISSUE THREAD

**Issue by pekacmarko** [Valhalla-Gaming/Tracker#7807]
Dalaran is empty. No Khadgar on Krasus landing in Legion Dalaran and i cant finish quest.

![bez naslova](https://cloud.githubusercontent.com/assets/24192370/20641863/97e84966-b401-11e6-9b28-040240798d26.png)

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6009
