### ISSUE TITLE
Vindictive Combatant's Insignia of Victory and other Vindictive trinkets with procs don't work.

### ISSUE THREAD

**Issue by Bloodshade** [Valhalla-Gaming/Tracker#7810]
Legion Season 1 trinkets with procs don't work

Steps to reproduce the problem:

1. Get a Vindictive trinket with a proc
2. Hit stuff
3. Doesn't proc

http://www.wowhead.com/item=135928/vindictive-combatants-insignia-of-victory

**Comment by MrNonameNo3** [comment]
Can't confirm. Got on with Agility proc. works there
