### ISSUE TITLE
Fury Warrior Talent: Endless Rage

### ISSUE THREAD

**Issue by VictorTyne** [Valhalla-Gaming/Tracker#7815]
**Describe the issue you're having**:
Fury warriors generate no rage from auto attacks.

**Explain how you expect it work**:
Fury warriors should generate rage from auto attacks. If the talent Endless Rage is selected, they should generate 30% more rage from auto attacks.

**Steps to reproduce the problem**:

1. Make a Fury Warrior and select Endless Rage talent.
2. Attack something.
3. Observe lack of rage generation.

**Links to Wowhead, YouTube, etc**:

**Comment by Moustachos** [comment]
Works just fine.
