### ISSUE TITLE
Druid Feral : Regrowth with Predatory Swiftness

### ISSUE THREAD

**Issue by medulla9324** [Valhalla-Gaming/Tracker#7821]
Should be only castable once but instead it does not use acquired charge of Predatory Swiftness and u can heal ally then when using it again on friendly target it targets to enemy and u can use it many times until Predatory Swiftness buff time expires.

**Comment by Djurdjevdan** [comment]
just posted it 1 minute ago

https://github.com/Valhalla-Gaming/Tracker/issues/7817

**Comment by Mr-Rager** [comment]
The issue has already been addressed. Thank you for the report. #7817
