### ISSUE TITLE
Prot Warrior Bugs till now

### ISSUE THREAD

**Issue by Lexppd** [Valhalla-Gaming/Tracker#7829]
**Describe the issue you're having**:
I am leveling now as a prot warrior, i have reached lvl 40 and till now here are the bugs i see, Focused Rage doesn't buff the hits at all, and the main of all, as a prot warrior my Charge changes to Intercept, Intercept doesn't change at all. Oh i almost forgot, and also the talent Shockwave doesn't work at all too
**Explain how you expect it work**:
Intercept should charge, Focused Rage should buff our next Shield Slam and Shockwave should stun and damage enemies in a frontal cone
**Steps to reproduce the problem**:

1. Take a warrior
2. Spec him as prot
3. Take Shockwave as first talent
4. Try all the spells i just told you

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=198760/intercept
http://www.wowhead.com/spell=204488/focused-rage
http://www.wowhead.com/spell=46968/shockwave

**Comment by GM-Pyromanic** [comment]
Intercept already reported #7482
Focused rage already reported #7586
Shockwave already reported #6850
Please use the search function when reporting issues also please create a new report for each issue.
