### ISSUE TITLE
Enhancement Shaman - Chain Lightning

### ISSUE THREAD

**Issue by FixDruid** [Valhalla-Gaming/Tracker#7830]
**Describe the issue you're having**:
Chain Lightning on enhancement shamans hits like 500 times
**Explain how you expect it work**:
Don't know. Just don't expect it to hit 50 times 200k damage.
**Steps to reproduce the problem**:

1. Cast Chain Lightning

Screenshot
http://imgur.com/a/QfS8e

**Comment by Zulbox** [comment]
Same as your Coldrinn Fang.

**Comment by FixDruid** [comment]
Yea it's already getting fixed ^^

**Comment by FixDruid** [comment]
Hense 'fix druid'

**Comment by Moustachos** [comment]
Does it only happen in PvP / specific conditions? Because my Chain Lightning deals normal damage.

Also, I assume you're talking about Elemental specialization? Enhancement shamans don't have Chain Lightning.

**Comment by MrNonameNo3** [comment]
my assumütion is 
http://www.wowhead.com/spell=204357/ride-the-lightning

43 Honor Talent

**Comment by Moustachos** [comment]
Thanks for the precision, it was indeed caused by Ride the Lightning and will be fixed on next update.

**Comment by Moustachos** [comment]
Ref #5979
