### ISSUE TITLE
Out of Range

### ISSUE THREAD

**Issue by avaksx** [Valhalla-Gaming/Tracker#7831]
**Describe the issue you're having**: Almost every time i try to attack someone in pvp game i get "out of range" and im literally standing in the enemy,also happens to ranged attack such as throw knife at rogue. Tested this on rogue and feral happens the same.

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. fix
2. fix
3. fix

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
May be related to https://github.com/Valhalla-Gaming/Tracker/issues/7825
