### ISSUE TITLE
Mage Talent: Ice Floes

### ISSUE THREAD

**Issue by llamalama** [Valhalla-Gaming/Tracker#7834]
http://www.wowhead.com/spell=108839/ice-floes

This talent is not working with channeled spells correctly.
If you cast it before casting a channeled spell, it uses up the charge but the spell is still interrupted when you move.
If you cast it while casting a channeled spell, it will not use up a charge, but it does let you move while casting. This enables you to use that charge for a 2nd spell. This is also causing you to become stuck in casting animation and unable to use the esc key until you do cast a 2nd spell or relog.

http://www.wowhead.com/spell=5143/arcane-missiles
http://www.wowhead.com/spell=12051/evocation

**Comment by Guybrush-VR** [comment]
This spell has been removed in 7.1.5.
