### ISSUE TITLE
Shaman : Tidal Wave doesn't stack

### ISSUE THREAD

**Issue by Analog-Valhalla** [Valhalla-Gaming/Tracker#7835]
**Describe the issue you're having**:
Tidal wave works great for the bonus but only is applied to the next spell.
**Explain how you expect it work**:
It should be applied to the next 2 spells.
**Steps to reproduce the problem**:

1. Cast Riptide.
2. Cast Healing surge
3. Cast Healing surge but notice the buff is gone previously to cast.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=53390/tidal-waves

**Comment by Moustachos** [comment]
1 stack of Tidal Waves applies to 1 cast (of Healing Surge or Healing Wave), that's the intended behavior.

Or do you mean that you had two stacks of Tidal Waves active and they were both gone after 1 cast?

**Comment by kpurc** [comment]
Both are gone after 1 cast

**Comment by MrNonameNo3** [comment]
Both getting consumed by 1 Cast yes. Thats not how its supposed to be.

**Comment by sprmk** [comment]
fix??

**Comment by kpurc** [comment]
There's nothing too major we have to heal yet, let's not stress the developers by being ungrateful. Let them finish warriors and we can see what happens from there. Btw Happy holidays !

**Comment by Moustachos** [comment]
Ref #5979
