### ISSUE TITLE
[Monk] Paralysis (Ability all spec) / Gladiator's Medallion

### ISSUE THREAD

**Issue by Tolno** [Valhalla-Gaming/Tracker#7838]
**Describe the issue you're having**: I can't use Gladiator's Medallion when I'm under the effect of Paralysis from a monk (happened already several times in BG)

**Explain how you expect it work**: I should be able to trinket any loss of control

**Steps to reproduce the problem**:

1. Try to trinket while Paralysed by a monk
2. If it works, try again in random BG

**Links to Wowhead, YouTube, etc**:

**Comment by FixDruid** [comment]
Also, you can't use the trinket if you're under the effect of a Demon Hunter's Imprisonment

**Comment by Moustachos** [comment]
Ref #5979
