### ISSUE TITLE
[Profession] [Cooking] Spell: Cooking Fire

### ISSUE THREAD

**Issue by VictorTyne** [Valhalla-Gaming/Tracker#7839]
**Describe the issue you're having**:
Using the spell: Cooking Fire does nothing.

**Explain how you expect it work**:

The spell should create a cooking fire, allowing Cooking.

**Steps to reproduce the problem**:

1. Train Cooking.
2. Attempt to use the ability "Cooking Fire".
3. Observe the lack of a cooking fire.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=818/cooking-fire

**Comment by Traveler-Valhalla** [comment]
also it should have a new visual/texture ;p

**Comment by RishkaM** [comment]
This is working fine for me

**Comment by Hemoglobine-Valhalla** [comment]
It doesn't work.

**Comment by VictorTyne** [comment]
Looks like this issue got a stealth fix. As of the Jan 22 patch, the Cooking Fire both works as intended and sports the new model with frying pan and fork.

**Comment by Guybrush-VR** [comment]
:clinking_glasses:
