### ISSUE TITLE
demon hunter Vengeanc spell (Soul Carver)

### ISSUE THREAD

**Issue by yebadal** [Valhalla-Gaming/Tracker#7842]
**Describe the issue you're having**:

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. Soul Carver spell does not drop 2 lesser soul fragments (big orbs) when use it with finisher
2. when u killed someone with Soul Carver spell that must drop 2 lesser soul fragments (big purple orbs)
or when that buff after using Soul Carver  yet on target and when you kill the target must drop 2 lesser soul fragments too
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=207407/soul-carver

**Comment by Moustachos** [comment]
Works just fine, no matter if the target dies from damage or not.

**Comment by Moustachos** [comment]
Ref #5979
