### ISSUE TITLE
Divine Judgement - Retribution mastery

### ISSUE THREAD

**Issue by MethalorMD** [Valhalla-Gaming/Tracker#7883]
**Describe the issue you're having**:
Cannot tell if damage of judgement is any different.
Debuff showing mastery is in effect is not applying to target - x amount of damage increase for holy power spenders does not increase depending on amount of mastery.
**Explain how you expect it work**:
increases judgement damage by x% (double of mastery %, 20% mastery = 40% judgement damage for example)
Judgement applies a debuff which increases damage of Holy power spenders by X amount ( % of mastery)

**Comment by Zealotry** [comment]
Re-Up of this issue. We rets really need this in bg it's almost impossible against locks or priests without the judgement working properly.

Here is a wowhead link: http://www.wowhead.com/spell=76672/mastery-divine-judgment

**Comment by Analog-Valhalla** [comment]
Does not represent 7.1.5. accurately. Thank you for your report. Closing Duplicates #8919
