### ISSUE TITLE
New Dalaran, Hunt-Class-Hall Transporter attacking me

### ISSUE THREAD

**Issue by MrNonameNo3** [Valhalla-Gaming/Tracker#7888]
Was casually standing in new Dalaran, krasus landing with pvp active. When an ally hunt came and tried to fly to his class hall with his eagle, the eagle attacked me. (I'm horde)

**Comment by llamalama** [comment]
http://www.wowhead.com/npc=108687/great-eagle
http://www.wowhead.com/npc=108868/talua

It doesn't matter if you are pvp flagged or not, it will attack anyone who is an opposite faction member who is nearby the eagle. I do not know if it attacks alliance as I have only seen it attack horde so far. 
It will not stop attacking until it runs out of nearby players to kill or the player riding it relogs.

**Comment by MrNonameNo3** [comment]
Thought it was one of the reasons since short before that i was in Val'sharah killing a guy who was killing my low lvl twink *.*

As i said: was in dala close to the eagle when a hunt was trying to get to his class hall and the eagle attacked me.
