### ISSUE TITLE
Warlock ROOTING spell spam till u die and its more like stun then rooting.

### ISSUE THREAD

**Issue by Nemanjagligic** [Valhalla-Gaming/Tracker#7892]
![wowscrnshot_113016_221023](https://cloud.githubusercontent.com/assets/24189853/20790038/a4b3c228-b7c7-11e6-9a9f-79ffd7d77af3.jpg)
![wowscrnshot_113016_221024](https://cloud.githubusercontent.com/assets/24189853/20790037/a4b3c444-b7c7-11e6-8efa-c51ad230a37c.jpg)
![wowscrnshot_113016_221025](https://cloud.githubusercontent.com/assets/24189853/20790039/a4b5d5ea-b7c7-11e6-8418-723309305d2a.jpg)

**Comment by Redrian-Valhalla** [comment]
Not enough info.

**Comment by Traveler-Valhalla** [comment]
It's this: http://www.wowhead.com/spell=233581/entrenched-in-flame
