### ISSUE TITLE
sigil of silence dh veng

### ISSUE THREAD

**Issue by yebadal** [Valhalla-Gaming/Tracker#7894]
**Describe the issue you're having**:

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. sigil of  silence does not silence the target
2. sigil of silence must silence the target and lock all of their spells for 6 sec
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=202137/sigil-of-silence

**Comment by Moustachos** [comment]
Works just fine.

**Comment by Moustachos** [comment]
Ref #5979
