### ISSUE TITLE
Artifact traits dont give stamina bonus

### ISSUE THREAD

**Issue by miloskovac** [Valhalla-Gaming/Tracker#7895]
After leveling my Artifact weapon, it should give stamina for every lvl, it doesnt.

Every lvl of artifact should give a bonus to stamina and/or dmg.

Like said above, artifact should give bonuses on leveling

http://www.wowhead.com/artifact-weapon-basics-guide look on the TRAITS section

**Comment by kpurc** [comment]
I dont believe you are right, They fixed this, plus ive had 1.3 mil health since they fixed it, and I still have 1.3 mil health.

**Comment by kpurc** [comment]
Maybe it is class specific, I have people tell me Demon Hunters get no bonus.

**Comment by MrNonameNo3** [comment]
i got the 0.75%(!!!) stamina on all my classes

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6564
