### ISSUE TITLE
Cinidaria, the Symbiote - legendary waist 895ilvl

### ISSUE THREAD

**Issue by spraypaint1993** [Valhalla-Gaming/Tracker#7897]
**Describe the issue you're having**:
Cinidaria, the Symbiote  (http://www.wowhead.com/item=133976/cinidaria-the-symbiote) -Equip: Your attacks cause an additional 30% damage as Physical to enemies above 90% health.
 The passive dont work.Here is the spell (http://www.wowhead.com/spell=207692/cinidaria-the-symbiote#used-by-item)

**Explain how you expect it work**:
Here is a discription of the spell i copy from wowhead
Spell Details
Duration	n/a
School	Physical
Mechanic	n/a
Dispel type	n/a
GCD category	n/a
Cost	None
Range	0 yards (Self)
Cast time	Instant
Cooldown	n/a
GCD	0 seconds
Aura proc chance	100%
Effect #1	Apply Aura: Dummy
Value: 30
Server-side script
Effect #2	Apply Aura: Dummy
Value: 90
Server-side script
Flags	
Passive spell

**Steps to reproduce the problem**:
As i write up there there is 2 effects which must be fixed:
1. Effect #1 calculating the damage (30% of the attacks as psyhical)
2. Effect #2 calculating the % health points of the target ( only when target is above 90%)
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/item=133976/cinidaria-the-symbiote - the legendary item
http://www.wowhead.com/spell=207692/cinidaria-the-symbiote#used-by-item - the spell that legendary item produce

I hope this information is enough.I will be pleased if i see that fixed sood , thanks for your time :)

**Comment by Analog-Valhalla** [comment]
Duplicate #9008
