### ISSUE TITLE
[Interface] Action bars

### ISSUE THREAD

**Issue by foxnstuff** [Valhalla-Gaming/Tracker#7905]
Sometimes when you log off the server, the action bars you put out and the skills you put on them do not save.

Everytime you relog it should save your previous interface options.

1. Open interface in settings, add action bars
2.  Tick always on
3.  Add Skills
4. Relog

*issues*

Action bar is always HIDING regardless if you have always show on or off. *they will re-appear when a skill is put on them*

Skills will not save to action bar on relogging [SOMETIMES].

This issue does NOT happen every time you relog, but does however happen often, especially if it's a new skill/talent you selected.

[ISSUE LEVEL] Minor.

**Comment by Redrian-Valhalla** [comment]
We need more info about this "sometimes", how do you usually log out?

**Comment by foxnstuff** [comment]
usually either afk time out or exit game client forcefully.

**Comment by Redrian-Valhalla** [comment]
Not closing the client properly is responsible for unsaved data, there's nothing to fix server side.
