### ISSUE TITLE
Proving Pit

### ISSUE THREAD

**Issue by Yeowza** [Valhalla-Gaming/Tracker#7906]
**Describe the issue you're having**:
Quest bugged, Darkspear jailor don't react.
**Explain how you expect it work**:
Darkspear jailor should react
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Traveler-Valhalla** [comment]
#981
#1203
#4263
#4598

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/981
