### ISSUE TITLE
Not On My Watch!

### ISSUE THREAD

**Issue by GeneralCaveman** [Valhalla-Gaming/Tracker#792]
http://www.wowhead.com/quest=9918/not-on-my-watch
http://www.wowhead.com/npc=18351/lump

There is no way to "interrogate" Lump, you can kill him but no credit is given.

**Comment by silverjade** [comment]
When I did this just now I smacked him around until he 'gave' up and then I was able to talk normally "interrogate" him. It didn't let me kill him.

**Comment by Cidragon** [comment]
This quest is working as intented (even when probably this is a retail bug but hey "it's a feature"). Don't kill it.
