### ISSUE TITLE
"Mastery: Divine Judgment" ret paladin mastrey passive

### ISSUE THREAD

**Issue by roguetwinky** [Valhalla-Gaming/Tracker#7953]
**there is no passive in spell book**:

**it should increase holy skills damge on enemy by % of mastrey**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**http://www.wowhead.com/spell=76672/mastery-divine-judgment#comments**:

**Comment by Analog-Valhalla** [comment]
Does not represent 7.1.5. accurately. Thank you for your report. Closing Duplicates #8919
