### ISSUE TITLE
Time-Lost Proto-Drake Nagrand

### ISSUE THREAD

**Issue by Sontrar** [Valhalla-Gaming/Tracker#7956]
**Describe the issue you're having**:
You can not kill in Nagrand "You cannot attack that target"
**Explain how you expect it work**:
Should be flying and be able to kill to get his booty
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/npc=32491/time-lost-proto-drake
![sin titulo](https://cloud.githubusercontent.com/assets/24320449/20842443/e3bd0646-b8b7-11e6-994f-8e773d54d51b.png)

**Comment by Traveler-Valhalla** [comment]
No. Killable drake is in storm peaks. This one in nagrand is correctly dead. It's just an easter egg.
