### ISSUE TITLE
Resto Druid cannot use Shadowmeld - Night Elf Racial

### ISSUE THREAD

**Issue by avaksx** [Valhalla-Gaming/Tracker#7988]
**Describe the issue you're having**: Title pretty much explains it all.

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. Fix.
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7464
