### ISSUE TITLE
Rogue Talent - Internal Bleeding Isn't Working

### ISSUE THREAD

**Issue by avaksx** [Valhalla-Gaming/Tracker#7990]
**Describe the issue you're having**: Whenever I use Kidney Shot with Combo Points it says "Suffering 0 Damage every 2 sec".

**Explain how you expect it work**:

Kidney Shot also deals (124.2% of Attack power) Bleed damage per combo point over 12 sec.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=154904/internal-bleeding

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7592
