### ISSUE TITLE
Stuck on Rolling For Dice!

### ISSUE THREAD

**Issue by segomaster** [Valhalla-Gaming/Tracker#7992]
**Describe the issue you're having**:
With a group, when a rare item drop comes, its stuck on rolling for dice, so the item is impossible to get.
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. Create a group
2. slay a Boss, or a rare drop from enemy
3. get rare item drop

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7748
