### ISSUE TITLE
Priest spell - Mind Control

### ISSUE THREAD

**Issue by forstix** [Valhalla-Gaming/Tracker#7993]
**Describe the issue you're having**:
Mind Control last for 30 sec in pvp combat so it kinda force trnket :-P

**Explain how you expect it work**:
Mind Control should last just 8 sec in pvp combat  

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=605/mind-control#comments

**Comment by Doriathrim** [comment]
Are you sure? i seen them lasting 8 secs.

**Comment by forstix** [comment]
maybe ithis problem with my cast bar addon then? It show me 30 sec when i used it in arena yesturday

**Comment by forstix** [comment]
i'm able to play only on weekend so i'll just close it and check it later
