### ISSUE TITLE
Death Knight: Mooyy

### ISSUE THREAD

**Issue by sweetchilisauce** [Valhalla-Gaming/Tracker#8001]
**Describe the issue you're having**:
My Heart strike damaging me for 15% health every time i use it .. maybe its because of the honor talent on the last patch.. now i cant change it at all.. please help..
**Explain how you expect it work**:

http://www.wowhead.com/spell=79885/heart-strike

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7908
