### ISSUE TITLE
Flying mounts

### ISSUE THREAD

**Issue by Syrune** [Valhalla-Gaming/Tracker#8024]
**Describe the issue you're having**:
When you mount on your flying mount while you're swimming you still cannot fly out of the water, even when you swim to the shore you still cannot fly, you have to remount to be able to fly.
When you mount your flying mount in your garrison you still cannot fly out of it, you have to run out of your garrison remount and then you can fly.
**Explain how you expect it work**:
You should be able to mount your flying mount and fly if you're allowed by zone/spells.
**Steps to reproduce the problem**:

1. Mount up your flying mount while in water/while in your garrison (prerequisite you can fly in draenor).
2. Try to fly out of the water to see it doesn't work. Reach the nearest shore to see you still cannot fly.
Mount up your flying mount in your garrison and try to fly out of it to see you cannot once you get out of your garrison you still cannot fly.
3. Re-mount [at the nearest shore/out of the garrison] the same mount and now you can fly again.

**Links to Wowhead, YouTube, etc**:

**Comment by Traveler-Valhalla** [comment]
#7787 mounting in water

#3913 mounting in garrison
#6077
