### ISSUE TITLE
Dark heart

### ISSUE THREAD

**Issue by sprmk** [Valhalla-Gaming/Tracker#8028]
**Describe the issue you're having**: Quest Dark Heart in Ferals isn't working properly. After using horn near stones it says you have to be near them, what exactly i am.
**Explain how you expect it work**: After getting Horn of Hatetalon from NPC around zone, you have to use it near Hatetalon Stones to summon "Edana Hatetalon" to kill her and get her heart for finishing the Q

**Steps to reproduce the problem**:

1. Take quest
2. Kill NPC for Horn of Hatetalon
3. Go to hatetalon Stones and try to use the horn

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/quest=3062/dark-heart

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/1877
