### ISSUE TITLE
Double Artifact skills

### ISSUE THREAD

**Issue by Nienz** [Valhalla-Gaming/Tracker#8033]
**Describe the issue you're having**: 
When using survial artifact and then switching to another spec, the artifact skill for survival is still in spellbook and is usable as well, currently i can use it with beastmastery

**Explain how you expect it work**:
When switching specialization the current artifact skill should be replaced with the proper artifact weapon

**Steps to reproduce the problem**:

1. take all 3 artifact weapons, switch to survival
2. look in spellbook and see two artifact skills
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by llamalama** [comment]
This also happened on my monk while I was in Brewmaster spec. They went away when I relogged and they never came back though.  My hunter does not have the bug with multiple artifact skills. This seems to be a more random bug, or triggered by something we didn't realize caused it.

**Comment by MrNonameNo3** [comment]
Got that when i switched from Enhancer to Resto shaman.

**Comment by Moustachos** [comment]
Ref #5979
