### ISSUE TITLE
demonology warlock/improved dreadstalkers

### ISSUE THREAD

**Issue by cesium136** [Valhalla-Gaming/Tracker#8040]
**Describe the issue you're having**:does nothing

**Explain how you expect it work**:summon dreadstalkers also summons two wild imps riding the dreadstalkers

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:http://www.wowhead.com/spell=196272/improved-dreadstalkers

**Comment by Traveler-Valhalla** [comment]
i think its working now
