### ISSUE TITLE
Fire mage  [Dragon's Breath] is broken. 

### ISSUE THREAD

**Issue by Nemanjagligic** [Valhalla-Gaming/Tracker#8045]
**Describe the issue you're having**:
 [Dragon's Breath] is not DISORIENTING target fo 4 sec.
****Explain how you expect it work**:
To disorient.
**Steps to reproduce the problem**:

1. Make mage.
2. Go pvp or on some npc and use  [Dragon's Breath].
3. It will make dmg but not disorient target for 4 sec

**Links to Wowhead, YouTube, etc**:
![wowscrnshot_120616_161006](https://cloud.githubusercontent.com/assets/24189853/20926842/947751ca-bbcf-11e6-8dc1-3e2fec80c80e.jpg)

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7847
