### ISSUE TITLE
[Monk] [Ability] Fists of Fury can flag you PvP

### ISSUE THREAD

**Issue by VictorTyne** [Valhalla-Gaming/Tracker#8053]
**Describe the issue you're having**:

If a PvP-Flagged NPC joins combat with you and you use Fists of Fury, you may end up flagged for PvP. This happens upon the enemy's death.

Tested outside Honor Hold with Honor Hold reputation at Neutral (may be affecting this).

**Explain how you expect it work**:

Casting AoE spells around PvP targets while not flagged PvP should not affect them.

**Steps to reproduce the problem**:

1. Get a monk.
2. Engage a mob.
3. Drag the engaged mob in range of PvP-flagged guards.
4. Kill the mob using Fists of Fury.
5. Observe newfound PvP-flagged status.

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6603
