### ISSUE TITLE
Resto Druid/ Artifact Trait/ Mark of Shifting

### ISSUE THREAD

**Issue by Milofajjour** [Valhalla-Gaming/Tracker#8054]
**Describe the issue you're having**:
Mark of Shifting is not working at all.
**Explain how you expect it work**:
when i go to any form( bear, cat or travel or even boomkin) i should take the buff mark of shifting which heals me 1% if my maximum health every 3 sec
**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=186372/mark-of-shifting

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7060
