### ISSUE TITLE
Artifact ranking up didnt give me increase in my HP

### ISSUE THREAD

**Issue by Milofajjour** [Valhalla-Gaming/Tracker#8055]
**Describe the issue you're having**:
so i recently just leveled up my artifact wep from 20 to 21. At 20 my HP was 1434k after i ranked up my artifact from 20 to 21 i didn't get the bonus 0.75% stamina. 
**Explain how you expect it work**:
This shouldn't happen at all the stamina 0.75% bonus should stop at 34 artifact rank not 20.
**Steps to reproduce the problem**:

1. I don't know if its a common bug or not but this happened with my Restoration Druid.
2. And i hope after the fix i get the bonus stamina i lost back. 
3. Good luck.

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6564
