### ISSUE TITLE
Quest Bugs Sholazar basin

### ISSUE THREAD

**Issue by MyJ3** [Valhalla-Gaming/Tracker#8062]
http://www.wowhead.com/faction=1104/frenzyheart-tribe#quests

The npcs of this tribe give no mission except http://www.wowhead.com/quest=12534/the-sapphire-queen and http://www.wowhead.com/quest=12529/the-ape-hunters- Slave possibly with the oracles will do the same http://www.wowhead.com/faction=1105/the-oracles#quests
@Cidragon

**Comment by Cidragon** [comment]
No enough information, I understand the issue but I can't handle it with the current information. The next time please say which quest is missing.
