### ISSUE TITLE
quest Failed Apprentice for Horde and Alliance

### ISSUE THREAD

**Issue by pekacmarko** [Valhalla-Gaming/Tracker#8066]
Quest not work for both factions.
- Free Deema for Alliance missing.
-Torag Stonefury Freed for Horde missing. 

http://www.wowhead.com/quest=36313/failed-apprentice#see-also

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/5793
