### ISSUE TITLE
Paladin Missing Board not working

### ISSUE THREAD

**Issue by braebrook** [Valhalla-Gaming/Tracker#8068]
**Once I hit level 100 I selected my weapon in Stormwind and it sent me to the old Dalaran, when I go to the class order hall and I go all the way to accept my first quest, I accept it from my mission board and I go to Kraus's Landing but Khagdar is not there so I cannot continue in Legion**:

**I expect Khagdar to be there so I can hand in the quest, other guild members online said that mission boards were broke.  Unless that is not the first quest to accept I'm not sure what to do**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by MethalorMD** [comment]
All quests in Broken isles do not work, as they have not been scripted yet.

**Comment by braebrook** [comment]
How do I actually start questing in Legion if those are broken?  There are
no other quests available to pick up in Dalaran.  I'm level 100 Paladin and
I have chosen my weapon and got the Dalaran hearthstone, am I stuck now
until that is fixed?

**Comment by Redrian-Valhalla** [comment]
This has already been reported multiple times, legion questlines will be released soon.
