### ISSUE TITLE
Outlaw rogue honor talent Plunder armor and control is king

### ISSUE THREAD

**Issue by bewilder1** [Valhalla-Gaming/Tracker#8070]
**Describe the issue you're having**:
Spells are just not working. Plunder armor when used show its debuff but you are not getting the benefits from it.
Control is king does not grants you 3 seconds of adrenaline rush whenever there are enemies that are stunned, polymorphed or silenced in 40yd radius. 
**Explain how you expect it work**:
self explanatory
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=198529/plunder-armor
http://www.wowhead.com/spell=212217/control-is-king

**Comment by Redrian-Valhalla** [comment]
Please make individual issues for each spell.
