### ISSUE TITLE
Sub Rogue/Spell/Eviscerate

### ISSUE THREAD

**Issue by Milofajjour** [Valhalla-Gaming/Tracker#8081]
**Describe the issue you're having**:
Eviscerate has a bugged damage. For an example my Eviscerate with 5 combo points should do 220,330 as written on the spell. But when i cast it(For an example the 5 combo) its doing 160k or 170k. Its damage is getting decreased. And if it crits it does 220k which is wrong. This happens with all the kinds of combo points im using it with from 1 to 5 or even 6 with the Deeper Stratagem talent.( All the damage is tested on dummies first before i made this post, so its not getting reduced from armor type.)
**Explain how you expect it work**:
cast Eviscerate with any combo from 1 to 5 or 6 and get the damage output its written on the spell not more or reduced.
**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=196819/eviscerate

**Comment by Moustachos** [comment]
Eviscerate's damage are legit and FYI dungeon training dummies do have armor, so what you see are the damage reduced by armor.
