### ISSUE TITLE
Sub Rogue/Spell/Eviscerate

### ISSUE THREAD

**Issue by Milofajjour** [Valhalla-Gaming/Tracker#8085]
**Describe the issue you're having**:
Eviscerate is doing less damage then it should be. Eviscerate is my only instant big damage combo. For my item level Eviscerate shows me that it must do 220k damage with 5 combo consumed, but here comes the problem. When i use any combo ponints on Eviscerate its doing less damage for an example if i use eviscerate with 5 combos its doing 150k instead of 220k damage. And when it crits its doing between 220k-270k these number with crits should be like 300k and above. Please fix the damage its reall important.
**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=196819/eviscerate

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/8081
