### ISSUE TITLE
Sub Rogue/Spell/Backstab

### ISSUE THREAD

**Issue by Milofajjour** [Valhalla-Gaming/Tracker#8086]
**Describe the issue you're having**:
Backstab is doing less damage. it must do with my item level 46k without crit and without the 30% increased damage(if behind the target) it is doing instead 26k damage which is so wrong and so low. When it crits it does 46k... i want to see big numbers not like these
**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=53/backstab

**Comment by Moustachos** [comment]
Works as intended, see #8081

**Comment by Moustachos** [comment]
Ref #5979
