### ISSUE TITLE
Protection warrior Damage bug.

### ISSUE THREAD

**Issue by MethalorMD** [Valhalla-Gaming/Tracker#8087]
**Describe the issue you're having**:
Almost every one of the offensive abilities for Protection warriors deal half of what their tooltip states when used in pve environments. (pvp not yet tested)
abilities are:
Devastate, Shield Slam, Revenge, Thunder clap, Shockwave, Impending Victory, Heroic Throw.
**Explain how you expect it work**:
Abilities to deal the same amount (unless altered via Critical strikes) as tooltip states.

**Comment by MrNonameNo3** [comment]
"Physical dmg" is reduced by armor value. so the numbers you see in the tooltips are not correct, only for targets with 0 armor.
