### ISSUE TITLE
"You've reached level <>" message not fading

### ISSUE THREAD

**Issue by llamalama** [Valhalla-Gaming/Tracker#8093]
If you click on the level you reached in chat, it will pop up a message on screen telling you what you unlocked that should fade after a few seconds but it does not. It will stay until you level up again or you relog.

![wowscrnshot_120816_210048](https://cloud.githubusercontent.com/assets/13492760/21035112/b225f764-bd8a-11e6-95ce-890a1db014d4.jpg)

**Comment by Moustachos** [comment]
All you have to do is click again on the level link.
