### ISSUE TITLE
Vindictive Gladiator's Insignia of Dominance Trinket

### ISSUE THREAD

**Issue by Milofajjour** [Valhalla-Gaming/Tracker#8104]
**Describe the issue you're having**:
Vindictive Gladiator's Insignia of Dominance Trinket when it procs its giving me 900 intellect instead of 3033 intellect.
**Explain how you expect it work**:
when i heal or damage a target it should proc giving me 3,033 intellect not 900.
**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/item=135812/vindictive-gladiators-insignia-of-dominance

**Comment by Analog-Valhalla** [comment]
Works as intended. Thank you for the report. :D
