### ISSUE TITLE
Engineering proff Tinkers: Goblin Glider

### ISSUE THREAD

**Issue by Zenii** [Valhalla-Gaming/Tracker#8110]
**Describe the issue you're having**: Tinkers: Goblin Glider

**Explain how you expect it work**:  working 

**Steps to reproduce the problem**: not fly 

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**: 
![wowscrnshot_121016_075238](https://cloud.githubusercontent.com/assets/23402884/21071811/b9af470a-bead-11e6-903b-2658915b8068.jpg)
 http://www.wowhead.com/spell=126392/goblin-glider

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/5095
