### ISSUE TITLE
[Fury Warrior] talents

### ISSUE THREAD

**Issue by AngryWolf123** [Valhalla-Gaming/Tracker#8112]
**Describe the issue you're having**:
Furious Charge doesnt work.
**Explain how you expect it work**:
http://www.wowhead.com/spell=202224/furious-charge
**Steps to reproduce the problem**:
http://www.wowhead.com/spell=202224/furious-charge
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7965
