### ISSUE TITLE
Rogue: Immune to falling damage

### ISSUE THREAD

**Issue by kpurc** [Valhalla-Gaming/Tracker#8113]
**Describe the issue you're having**:
When a player uses stealth and falls a distance they take zero damage as a result of it
**Explain how you expect it work**:
The rogue should take damage upon falling
**Steps to reproduce the problem**:

1. Fly up really high. 
2. Fall a great distance
3. Notice you take no damage

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=31209/fleet-footed

**Comment by llamalama** [comment]
I tested this and it worked perfectly fine. Rogues do take less fall damage by default from a passive effect (Fleet Footed) so they can fall farther before they take damage at all. If you go up high enough, you'll still take damage. 
http://www.wowhead.com/spell=31209/fleet-footed

**Comment by kpurc** [comment]
Fine by me thank you, wasn't aware of the talent

**Comment by Milofajjour** [comment]
Well if you are sub rogue u won't take falling damage if you have the trait for that

**Comment by kpurc** [comment]
Are you serious? How did I overlook that, mind to tell me which trait?

**Comment by llamalama** [comment]
http://www.wowhead.com/spell=197241/catlike-reflexes

**Comment by kpurc** [comment]
Thank you. I forget artifacts do cool stuff or stuff at all. Have a great
one and thank you for the help.
