### ISSUE TITLE
Engineering drop: Schematic: Chief Engineer Jard's Journal 

### ISSUE THREAD

**Issue by Zenii** [Valhalla-Gaming/Tracker#8114]
**Describe the issue you're having**: Schematic: Chief Engineer Jard's Journal 600skill

**Explain how you expect it work**: not work

**Steps to reproduce the problem**: not work

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/item=100910/schematic-chief-engineer-jards-journal

**Comment by Traveler-Valhalla** [comment]
#1410
#3832
