### ISSUE TITLE
The Emerald Dreamcatcher

### ISSUE THREAD

**Issue by GeneralCaveman** [Valhalla-Gaming/Tracker#812]
http://www.wowhead.com/quest=2438/the-emerald-dreamcatcher

The chest related to this quest does not open.

**Comment by GeneralCaveman** [comment]
A lot of quests seem to do this, but it shows that you should get 1 silver as a reward but the 1 silver disappears when you accept the quest.

Is this is a known bug? Because there are a lot of quests I discovered that don't reward money when they should and I can't imagine someone not creating a post on it.

**Comment by Max-Hellscream** [comment]
Can you create a separate issue for both of these? That second one is not known and should be marked with high priority.

**Comment by GeneralCaveman** [comment]
Will do.

**Comment by GeneralCaveman** [comment]
I will delete the post above you and this issue will be just about the chest itself.

**Comment by Sonofsven** [comment]
Completed It Today,
