### ISSUE TITLE
Exploring Razorven Kraul

### ISSUE THREAD

**Issue by Plasmatexx87** [Valhalla-Gaming/Tracker#8124]
**Exploring Razorven Kraul**:

**Standing in front of the dungeon-entrance should pop up the achievement**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Maldazar-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/233
