### ISSUE TITLE
Resto Druid Prowl Not Working .

### ISSUE THREAD

**Issue by EvanovicH** [Valhalla-Gaming/Tracker#8130]
**Describe the issue you're having**:
When i Use Prowl With My Restoration Druid i got message ( You Cant Do that yet )
**Explain how you expect it work**:
It should Work Like Other Spec  ( activate Cat Form And Prowl ( Stealth ) )
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Maldazar-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7158

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7158
