### ISSUE TITLE
Ragnaros Molten core broken!

### ISSUE THREAD

**Issue by SloppyPuppy** [Valhalla-Gaming/Tracker#8132]
My issue is that nobody adressed this problem yet...

Its supposed to let me kill ragnaros after finishing the molten core,but nope,ragnaros is just targetable and you can not attack him,so yesterday when the problem accured ,i just gave up and i left the game,when i came back,i was still in molten core,all mobs restored except for the majordomo executus that your supposed to talk to,to be able to start the fight with ragnaros,and i talked to him once more and the only thing he said was the first dialog bit,and ive been waiting for 10 minutes seeing if its just not showing the rest text,also relogged several times,seeing if that would fix the problem,but nope. And i have not reloged during his dialog,just to be clear. 

**Steps to reproduce the problem**
1. Enter Molten Core
2. Kill of all the bosses,except for ragnaros (obviously)
3. Talk to Majordomo Executus,and see ragnaros appear infront of your eyes,except your not able to fight him.

Btw just done the Black temple and Illidans blade dropped,if it was only on a retail XDD these drop rates are same as retail right ,(except for xp which can be altered 0,5-5).I would say i was lucky but im unlucky i cant afford a subscripition right now :(

Heres a youtube video of ragnaros being summoned by majordomo executus:
https://www.youtube.com/watch?v=TflRQdFliVY

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/5303
