### ISSUE TITLE
Warlock Drein Life , Drein Soul heals too much, in 2 sec fro 1% hp to full... 

### ISSUE THREAD

**Issue by Nemanjagligic** [Valhalla-Gaming/Tracker#8137]
**Describe the issue you're having**:
Warlock Drein Life heals too much, in 2 sec fro 1% hp to full and eaven without shield he is not absorbing spells he is doing block.... 
![wowscrnshot_121116_120618](https://cloud.githubusercontent.com/assets/24189853/21137920/c9b909a6-c13c-11e6-9048-20e1a74c094d.jpg)

**Comment by Traveler-Valhalla** [comment]
He has Soul Leech there in his buffs and that's for absorb. **I guess** that there's a visual bug or something.

**Comment by Nemanjagligic** [comment]
What visual dud?
He just block all my spells, full burst, everithing blocking....

**Comment by Bombrick** [comment]
it's his shield it's supposed to say absorb instead of block but it says blocked sometimes instead of absorbed

**Comment by Nemanjagligic** [comment]
Greetings!
Mhmmm, tajhnks a lot. And what about warlock heals? And is there any
information about mage fixing? I have made a lot of issues?

**Comment by Bombrick** [comment]
I think drain life is blizzlike however on retail it's healing and dps is high too not sure if it's the same here in the exact amount.

**Comment by kpurc** [comment]
I know for a fact it heals 2X per tick on what its supposed to heal. Ex. is should go like 125k (cant remeber the exact number) but actually heals 250k per tick (not sure it this number is the correctone but a demonstation)

**Comment by Moustachos** [comment]
Ref #5979
