### ISSUE TITLE
Dungeonfinder not working

### ISSUE THREAD

**Issue by Soulclaw** [Valhalla-Gaming/Tracker#8141]
**Describe the issue you're having**:
when i Press the button it dont work, nothing happened
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/2436
