### ISSUE TITLE
Paladin (Retribution) Abilities that Don't Work

### ISSUE THREAD

**Issue by UmbraUnda** [Valhalla-Gaming/Tracker#8142]
**Describe the issue you're having**:

Many abilities + artifact perks don't work for paladins.  There are too many to list, so I'll just cover Retribution for now.  I'll do Protection and Holy at a later date when I have more free time, but I will say this; Protection is broken in an OP way and needs to be nerfed.  They have more dps than Retribution.

**Explain how you expect it work**:

All abilities + artifact perks should be working.

**Steps to reproduce the problem**:
(Not gonna put steps cause it's just broken abilities so instead I'll list each ability.)
1.  Echo of the Highlord & Ashes to Ashes (artifact perks) don't work.  Haven't tested Divine Tempest but it probably doesn't work either.
2.  Vengeance Aura (Passive)
3.  Retribution (Passive)
4.  Paladin Artifact armor "Justice Gaze" 's effect does not work.  
5.  Heart of the Crusader (Passive)
6.  Wake of Ashes appears 2 times in spellbook.
7.  Judgement 's 2nd effect/Mastery's 2nd effect

Thanks & appreciate all the work that goes into Valhalla.

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
Please report each issue separately, it's harder to fix them when they are all mixed up in a list, thank you.
