### ISSUE TITLE
icc 25 gunship

### ISSUE THREAD

**Issue by alucula** [Valhalla-Gaming/Tracker#8143]
**Describe the issue you're having**:
no Npc's on the gunship and no cannons, so it's unstartable
**Explain how you expect it work**:
https://www.youtube.com/watch?v=PulGeTbRzEo
**Steps to reproduce the problem**:

1. do first 2 boss
2. delete cache if the ship is not spawned
3. and here you are without npc

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/4554
Not exactly the same issue, but the instance would be fixed anyway with the same old report.
