### ISSUE TITLE
World bosses

### ISSUE THREAD

**Issue by alucula** [Valhalla-Gaming/Tracker#8144]
**Describe the issue you're having**:
this is not an issue but a missing. The World bosses didn't spawn.
**Explain how you expect it work**:
They should be up
**Steps to reproduce the problem**:

1. Look on wowhead the location
2. search in that location
3. and u will not be able to find it

**Links to Wowhead, YouTube, etc**:

**Comment by MrNonameNo3** [comment]
Theyre bit scripted yet. i guess the devs wont release them till theyre fully scripted or you can basically solo them and get the loot for "free"

**Comment by Redrian-Valhalla** [comment]
World bosses will be implemented when ready, not really classifiable as bug unless they were part of something essential.
