### ISSUE TITLE
Hit Level 100 now what?

### ISSUE THREAD

**Issue by braebrook** [Valhalla-Gaming/Tracker#8146]
**I hit level 100 and I put in a request last week where the first quest I get from the Paladin order hall mission board but Khagdar is not at Kraus's Landing in Dalaran to hand it in, how do I start my leveling in Legion if the mission board quest is not working, or is there any other quests I'm able to pick up?  Not sure what to do now or am I just stuck at 100 until this is fixed?**:

**Not sure if there is another quest to pick up or if Khagdar is supposed to be in Dalaran at the flight path so I can hand it in and continue to Aszuna**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by forstix** [comment]
This is not th right place for this post u can always ask in world channel or even the forum,
Anyway u can farm eggs in val' at broken isle
untill 110. Good luck

**Comment by braebrook** [comment]
I posted it here since they said mission boards were broken.  How do I get to an area to farm eggs, right now I hit 100 and picked my weapon and it gave me the old Dalaran hearthstone but I don't have any flight paths or any way to get anywhere.

**Comment by forstix** [comment]
Jump to the sea ans start swiming :)
