### ISSUE TITLE
Mage / Fire / Ignite dmg...

### ISSUE THREAD

**Issue by MrNonameNo3** [Valhalla-Gaming/Tracker#8150]
You should take a look at firemages ignite dmg..

![wowscrnshot_121416_203528](https://cloud.githubusercontent.com/assets/23424577/21197995/d64bb252-c23d-11e6-8045-782be9c4e62c.jpg)

![wowscrnshot_121416_203453](https://cloud.githubusercontent.com/assets/23424577/21198022/f1ebe3e2-c23d-11e6-937a-32ec94065bfd.jpg)

Something is fishy there :^)

**Comment by forstix** [comment]
I think this npc is just bugged 
Or maybr he low level compare to the mage so he hit higher then his normal dmg (like when u hit low level dummy)

**Comment by MrNonameNo3** [comment]
the NPC is a Legion world boss and guaranteed not to low lvl.

**Comment by MrNonameNo3** [comment]
...can you wait with the fix till my mage is lvl 110 ^^

**Comment by avaksx** [comment]
As a fire mage myself i can say that in 110 mobs in Broken Isles and in PVP, ignite isnt doing that much damage. 
Maybe it is world boss related since he isnt scripted fully.

**Comment by Nemanjagligic** [comment]
As Terrorwofl my self i wanna tell thet this bug is only at this boss, i was testing on others npcs and its normaly work, and in pvp too....

**Comment by Nemanjagligic** [comment]
This Boss is buging thet dmg buy him self somehow.

**Comment by MrNonameNo3** [comment]
Does Ignite do like % max health dmg maybe? I mean i really dont care much. But If it does that dmg to all bosses, Raids will be stacked with fire mages which makes it pretty boring... And Server first clears just unnecessary because our dmg will be so abnormal high that we oneshot everything with some fire mages.

**Comment by Nemanjagligic** [comment]
Nop. Its not based on %. I have tryed other NPCs and for them its work just
nice, somehow only this boss bugging thet ignity and he just grow up, dmg
just somehow grow up. Others with igniti i cannot hit more then 21k- thets
max i have made on my tests. So only this boss is buging thet dmg of igniti.

**Comment by theprototyze** [comment]
I'm suspecting the issue is related to the Critical of the mage, added to (probably) a combination between all or some of these traits: http://www.wowhead.com/spell=194331/pyretic-incantation http://www.wowhead.com/spell=215773/phoenix-reborn http://www.wowhead.com/spell=194314/everburning-consumption

**Comment by Moustachos** [comment]
What are your talents?

**Comment by Moustachos** [comment]
Ref #5979
