### ISSUE TITLE
Lava Surge not working

### ISSUE THREAD

**Issue by MCardan** [Valhalla-Gaming/Tracker#8151]
Lava surge spell not proc since Update on 2016.5.12.073000 

Should proc on Flame shock and reset cooldown:
{Class-Shaman}

**Comment by MrNonameNo3** [comment]
Wouw. didnt know Valhalla was on patch 7.1.5 already. . .

**Comment by Redrian-Valhalla** [comment]
Lava Surge works this way since Cataclysm, so it's a valid issue.

**Comment by MrNonameNo3** [comment]
I play Ele and Resto. Both proc Lava surge which resets the cooldown of Lava burst AND makes it instant. Works for me
