### ISSUE TITLE
Survival Hunter/Honor talent/ Catlike Reflexes

### ISSUE THREAD

**Issue by Milofajjour** [Valhalla-Gaming/Tracker#8152]
**Describe the issue you're having**:
Catlike Reflexes procs on every attack not only critical attacks. And it keeps getting refreshed until the enemy stop attacking. This honor talent is infinite starts from the starting of the fight until your enemies are dead.
**Explain how you expect it work**:
This Should proc only on critical melle attacks not all kinds of attacks and it can only be refreshed if the target takes another critical melle attack.
**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=202624/catlike-reflexes

**Comment by forstix** [comment]
Ty for the report funny how everyone play hunter and no1 report it yet...

**Comment by Moustachos** [comment]
Ref #5979
