### ISSUE TITLE
Paladin (Retribution) Mastery Half Broken

### ISSUE THREAD

**Issue by UmbraUnda** [Valhalla-Gaming/Tracker#8156]
**Describe the issue you're having**:

Mastery's 2nd effect/Judgement 's 2nd effect not working.

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Analog-Valhalla** [comment]
Fixed in previous updates
