### ISSUE TITLE
Six-feather-fan

### ISSUE THREAD

**Issue by MyJ3** [Valhalla-Gaming/Tracker#8158]
El objeto http://www.wowhead.com/item=141585/six-feather-fan  cuando lo has usado y solo has matado un enemigo, el resto de las cargas te hacen daño a ti y te ralentiza.

The object http://www.wowhead.com/item=141585/six-feather-fan when you have used it and you have only killed one enemy, the rest of the charges hurt you and slows you down.

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7823
