### ISSUE TITLE
diminishing returns for stuns

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#8159]
**Describe the issue you're having**:
all stuns have their full duration
**Explain how you expect it work**:
duration should be reduced with each stun till u get immune to them for few seconds
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://wow.gamepedia.com/Diminishing_returns

**Comment by Traveler-Valhalla** [comment]
I'm 100% sure I never got immune to stuns (nor their duration was reduced) after chains like fist of justice, dhs chaos nova or fel erruption and rogues between the eyes.

**Comment by MrNonameNo3** [comment]
Works only for a few. Thought it was reported long ago tho...

Another topic is that you cant trinket Monk incap, DH incap, Druid Cyclone

**Comment by Bombrick** [comment]
note: it was working in wod for all stuns.

**Comment by Traveler-Valhalla** [comment]
all new or changed in legion stuns and silence effects have no dr :<
