### ISSUE TITLE
Rogue / Assa / Seal Fate 

### ISSUE THREAD

**Issue by MrNonameNo3** [Valhalla-Gaming/Tracker#8162]
http://www.wowhead.com/spell=14190/seal-fate

Not working on Mutilate.
Base Combo Points gained from Mutilate is 2. If offhand and/or mainhand crit with mutilate it should generate one additional Combo Point, For a maximum of 3 Combo Points per Mutilate.
It Currently doesn't.

**Comment by forstix** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7612 reported already
