### ISSUE TITLE
Mages Dragons Breth is not disorenting target for 4 sec. 

### ISSUE THREAD

**Issue by Nemanjagligic** [Valhalla-Gaming/Tracker#8163]
**Describe the issue you're having**:
This spell is not disorenting target for 4 sec. When i use this spell its brok casters cast but disorent him for 4 sec it doesnt doing. Disorent geting broken right after u use dragons breth in 1 sec.
**Explain how you expect it work**:
To disorent target for 4 sec.
**Steps to reproduce the problem**:

1. make mage and use this spell in pvp.
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=31661/dragons-breath 
(Dragon's Breath	Magic
Disoriented.
4 seconds remaining)

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7847
