### ISSUE TITLE
Divine Steed - dwarf paladin

### ISSUE THREAD

**Issue by enslaver3** [Valhalla-Gaming/Tracker#8171]
**Describe the issue you're having**:
The spell that summons a Holy mount to ride for 3 seconds shows only the end/start animation excluding the image of the actual horse and the speed buff.
**Explain how you expect it work**:
A golden charger should boost your speed up for 3 seconds (100% increase)
**Steps to reproduce the problem**:
P.S.: At least on the blood elves this spell works, i haven't verified with other races.

**Links to Wowhead, YouTube, etc**:
https://www.youtube.com/watch?v=frj0mw5tgMg

**Comment by Redrian-Valhalla** [comment]
I've seen the spell working on almost every race supported by paladins.
