### ISSUE TITLE
Demon hunter Crashed (multiple occasions)

### ISSUE THREAD

**Issue by VexiraSioux** [Valhalla-Gaming/Tracker#8173]
When a demon hunter jumps twice then uses the ability "Fel Rush" it causes a crash with an error message. (WOW51900319) Also occures when a player double jumps and attacks with any ability.

Not crash.

**Steps to reproduce the problem**:

1. Jump twice,
2. Attack with an ability OR
3. Use fel Rush

**Links to Wowhead, YouTube, etc**:

**Comment by Maldazar-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7393
https://github.com/Valhalla-Gaming/Tracker/issues/7203

**Comment by VexiraSioux** [comment]
Fix it -.-
