### ISSUE TITLE
Druids/Honor talent/ Cyclone

### ISSUE THREAD

**Issue by Milofajjour** [Valhalla-Gaming/Tracker#8176]
**Describe the issue you're having**:
when i cast cyclone on someone they cant remove it by gladiators.
**Explain how you expect it work**:
Cyclone should be able to be removed by the gladiator.
**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/search?q=cyclone

**Comment by Chipslover** [comment]
Cyclone can't be displled.

**Comment by Moustachos** [comment]
Ref #5979
