### ISSUE TITLE
Archeology artifacts can't be Solved!

### ISSUE THREAD

**Issue by Psychadelic** [Valhalla-Gaming/Tracker#8181]
**Describe the issue you're having**:

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. Artifacts can not be solved.
2.  I have more then enough artifacts to solve it but it says you do not have enough artifacts.
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Redrian-Valhalla** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6977
