### ISSUE TITLE
DCED 

### ISSUE THREAD

**Issue by Ezikeal** [Valhalla-Gaming/Tracker#8182]
**Describe the issue you're having**:
okay so everytime i charge or heroic leap on my warr i dc on bgs or arenas but if i do it on mobs i dont

**Explain how you expect it work**:
when ever you cast charge or heroic you shouldnt get dced.

**Steps to reproduce the problem**:

1. cast charge or heroic leap
2. disconnect
3. sometimes i use charge or heroic leap in pvp i dont dc
**Links to Wowhead, YouTube, etc**:

**Comment by Maldazar-Valhalla** [comment]
Refered to https://github.com/Valhalla-Gaming/Tracker/issues/7480

**Comment by Ezikeal** [comment]
FIXED: all you need to do is delete cache and wtf folder
