### ISSUE TITLE
BUGGED Spells Balance Druid

### ISSUE THREAD

**Issue by kinnloria** [Valhalla-Gaming/Tracker#8205]
**Describe the issue you're having**:
The spell "Starfall" and "Starsurge" will not cast at all

**Explain how you expect it work**:
The spell to cast and do damage :D

**Steps to reproduce the problem**:

1. Cast
2. Damage
3. MORE DAMAGE

**Links to Wowhead, YouTube, etc**:

**Comment by MrNonameNo3** [comment]
It's a bug with the Moonkin resource. Already has been reported

**Comment by Guybrush-VR** [comment]
Indeed, here too #8169. Thanks for your report though!
