### ISSUE TITLE
Conjure Refreshment not working

### ISSUE THREAD

**Issue by Kezeal** [Valhalla-Gaming/Tracker#8207]
**Describe the issue you're having**:
Casting Conjure Refreshment has no effect
**Explain how you expect it work**:
Castin Conjure Refreshment conjures refreshment
**Steps to reproduce the problem**:

1. Conjure Refreshment

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=42955/conjure-refreshment

**Comment by avaksx** [comment]
Just tested it on my mage level 110.
Works perfect. It conjures 20x and they restore your mana points and health point normally.

**Comment by Guybrush-VR** [comment]
This might be a level issue, as stated here #7570. Thank you for your report though. :+1: 
Closing it to prevent duplicates.
