### ISSUE TITLE
Mage: Dragon Breath

### ISSUE THREAD

**Issue by Djurdjevdan** [Valhalla-Gaming/Tracker#8209]
**Describe the issue you're having**:
Spell Dragon Breath only deals damage and dosen't stun target.
**Explain how you expect it work**:
Dragkn Breath should disorient and deal small damage. If target takes damage while disoriented, effect is broken.
**Steps to reproduce the problem**:
Since I saw thia on issue tracker before and it was said it's fixed, I belive one of the updates messed this up.
**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=161792/dragons-breath

**Comment by avaksx** [comment]
Just tested it on my mage level 110.
Works perfect. It conjures 20x and they restore your mana points and health point normally.

**Comment by avaksx** [comment]
#7847 

But now after 7.1 it is not applying dissorient effect.

**Comment by Guybrush-VR** [comment]
As avaksx states, this has already been reported multiple times. Thank you for your report though: :+1: 
Closing it to prevent duplicates.
