### ISSUE TITLE
Warlock/ Drain Life

### ISSUE THREAD

**Issue by Milofajjour** [Valhalla-Gaming/Tracker#8210]
**Describe the issue you're having**:
Drain Life is healing more than it should. This was already reported but you closed the issue and didn't believe them. It's healing X2 per tick even of you do 1M crit on him hos life doesn't drop while he is using drain life. Please if you didn't believe is just check in game and you will see that its bugged.

**Comment by Traveler-Valhalla** [comment]
its closed cuz itll be fixed in next update

**Comment by Milofajjour** [comment]
Ty 😎
