### ISSUE TITLE
The Drogbar

### ISSUE THREAD

**Issue by nibbyy** [Valhalla-Gaming/Tracker#8226]
**Describe the issue you're having**:
_-After the Underking Cinematic occurs, the Drogbars are not spawning around the village, which are required to be slain to beat the quest.-_
^ Partially fixed. The Drogbars are supposed to spawn in the village as well, **but currently only spawn to the left of the cave.**
Update 2: Those Drogbars next to the cave did not respawn.

**Explain how you expect it work**:
After the Underking Cinematic, Drogbars should start spawning

**Steps to reproduce the problem**:

1. Get the quest The Drogbars
2. Wait for the cinematic to end

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=39026

**Comment by nibbyy** [comment]
Update: The Drogbars do not spawn in the village, only to the left of the cave.

**Comment by Lhyron** [comment]
After questing in the new zone, 2 of my characters can't go further in the quest line because The drogbars are not spawn if you finished [http://www.wowhead.com/quest=42590/moozys-reunion](url) before finishing [http://www.wowhead.com/quest=42104/the-underking-comes](url).
