### ISSUE TITLE
Grasp of the Underking

### ISSUE THREAD

**Issue by nibbyy** [Valhalla-Gaming/Tracker#8227]
**Describe the issue you're having**:
Warbrave Oro does not spawn, who is the receipt to turn in this quest.

**Explain how you expect it work**:
Warbrave Oro should be in front of the cave entrance to turn in this quest.

**Steps to reproduce the problem**:

1. Get Grasp of the Underking Quest
2. Complete it, try to turn it in
3. The NPC will not spawn

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=39025/grasp-of-the-underking

**Comment by Aprophys** [comment]
You need to comlete this quest http://www.wowhead.com/quest=42590/moozys-reunion
