### ISSUE TITLE
Quest: The Lone Mountain

### ISSUE THREAD

**Issue by llamalama** [Valhalla-Gaming/Tracker#8228]
http://www.wowhead.com/quest=39733/the-lone-mountain

This quest cannot be completed by rogues.

**Comment by Lhyron** [comment]
Can't be completed too as a troll hunter

**Comment by llamalama** [comment]
If you have problems as other classes, you probably didn't use the portal to Dalaran from your class hall. You need to do this or the quest will not complete. If you did this and still have problems, abandon it, clear your cache and try again.

**Comment by Guybrush-VR** [comment]
I fixed it on local. If you didn't get credit by teleporting to Dalaran, you'll now get credit by getting near Archmage Khadgar & Warbrave Oro. Fix is coming soon.
