### ISSUE TITLE
Shadow Priest Void Eruption/Voidform Broken Via Recent Update

### ISSUE THREAD

**Issue by DerpyDooHooves** [Valhalla-Gaming/Tracker#8229]
**Describe the issue you're having**:
Starting just today, last night it was working alright, the Void Eruption ability for Shadow Priest was able to be cast upon reaching 100 Insanity. Now, the tooltip states it requires 101 insanity and it refuses to toggle. The cap is 100 insanity, so this makes the spell and mechanic completely unusable.
**Explain how you expect it work**:
Void Eruption should be able to be activated at 100 Insanity. The tooltip states it requires 101 insanity now, which is impossible to achieve.

**Links to Wowhead, YouTube, etc**:
[https://i.gyazo.com/660a7fb3da181bf81102d3a82ccceeb4.png](https://i.gyazo.com/660a7fb3da181bf81102d3a82ccceeb4.png)
http://www.wowhead.com/spell=228260/void-eruption

**Comment by nibbyy** [comment]
I've heard of this issue being had on other players. I know there is a talent that reduces the cost of Void Eruption to 75, try that?

**Comment by forstix** [comment]
Only when you are 100 u can take this tallent so level as shadow is kinda lame atm

**Comment by DerpyDooHooves** [comment]
It just happened so recently, still. I'm not certain, but it probably shouldn't be that hard to fix! At least, I can only guess so. Not sure how they broke it, but to adjust the resource cost of the spell slightly so it goes back to 100. Dunno exactly.

**Comment by Traveler-Valhalla** [comment]
This bug affects other classes aswell.

**Comment by Analog-Valhalla** [comment]
Fixed in 7.1.5. Thank you! :D
