### ISSUE TITLE
[Quest][Highmountain] That guy in the costume

### ISSUE THREAD

**Issue by Aprophys** [Valhalla-Gaming/Tracker#8232]
**Describe the issue you're having**:
You cant talk to the flighmaster who bring u to Shipwreck cove
**Explain how you expect it work**:
Take the quest talk to the flightmaster and he brings to to Shipwreck Cove
**Steps to reproduce the problem**:

1. Take the quest
2. Click on the Npc 
3. and it open only the flypath map

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=40244/that-guy-in-the-costume
how should it work:
https://www.youtube.com/watch?v=GX3uTVW51Lw

**Comment by Guybrush-VR** [comment]
Yep, I didn't script it just yet! I forgot to remove it from your quests though!
Closing it for now!
