### ISSUE TITLE
fury Warrior massacre talent bug!

### ISSUE THREAD

**Issue by Ezikeal** [Valhalla-Gaming/Tracker#8233]
**Describe the issue you're having**:
alright so if you use any spells as a fury warrior if you pick the massacre talent and use any spells rampage will proc every second and it's op it should only proc after execute criticals or you need 85 rage if execute doesnt crit
**Explain how you expect it work**:
if you pick the massacre talent rampage should only proc if execute criticals

**Steps to reproduce the problem**:

1. cast any spell
2. Rampage procs every second and its op
3. 

ALSO a lot of warriors dont talk about this bug cause its op

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=184367/rampage
http://www.wowhead.com/spell=206315/massacre

**Comment by Aprophys** [comment]
Allready reported https://github.com/Valhalla-Gaming/Tracker/issues/7964
