### ISSUE TITLE
GLOOMSCALE AFK XP

### ISSUE THREAD

**Issue by Ezikeal** [Valhalla-Gaming/Tracker#8235]

**Comment by Lhyron** [comment]
It happens everywhere.

**Comment by Traveler-Valhalla** [comment]
i got honor for standing still in azsuna ;d

**Comment by Ezikeal** [comment]
dame this needs to get fixed soon lol

**Comment by garynewberg** [comment]
The experience is gained because they are in a group. This is a normal game mechanic that cannot be fixed, without breaking blizzards design. In fact this thread should be disregarded.

**Comment by GM-Pyromanic** [comment]
Exp is randomly given while not in a group also.

**Comment by Guybrush-VR** [comment]
Fixed.

**Comment by Ezikeal** [comment]
yeah
