### ISSUE TITLE
Quest Riding the Skies

### ISSUE THREAD

**Issue by pekacmarko** [Valhalla-Gaming/Tracker#8250]
quest not work 
- Join the Order of the Cloud Serpent
need reputation for the quest to join.
http://www.wowhead.com/quest=30188/riding-the-skies

**Comment by Aprophys** [comment]
if get revered, then hunting onyx eggs to get exalted and end up wondering why this quest isn't popping up: You must have done Flight Training: Full Speed Ahead and Flight Training: In Due Course to make Elder Anli give you this quest.
