### ISSUE TITLE
Golem Training Quest

### ISSUE THREAD

**Issue by XIXDeadeye** [Valhalla-Gaming/Tracker#8263]
The golems are not responding 
Click the golems, chat with them and start training 

**Steps to reproduce the problem**:

1. Take the quest http://www.wowhead.com/quest=28227/golem-training
2. try doing it.

http://www.wowhead.com/quest=28227/golem-training

**Comment by Aprophys** [comment]
Reported https://github.com/Valhalla-Gaming/Tracker/issues/1975
