### ISSUE TITLE
A perfect costume Quest

### ISSUE THREAD

**Issue by XIXDeadeye** [Valhalla-Gaming/Tracker#8264]
I can't take any materials of the table 

The table is not responding in any way 

**Steps to reproduce the problem**:

1. Take the quest http://www.wowhead.com/quest=28428/a-perfect-costume
2. try doing it 
3. you can't 

http://www.wowhead.com/quest=28428/a-perfect-costume

**Comment by Aprophys** [comment]
Reported https://github.com/Valhalla-Gaming/Tracker/issues/1974
