### ISSUE TITLE
dk unholy pandemic honor talent

### ISSUE THREAD

**Issue by ixodan** [Valhalla-Gaming/Tracker#8269]
**Describe the issue you're having**:
when u use outbreak pandemic hits all nearby enemies 3 times
**Explain how you expect it work**:
it should hit them only 1 time
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by theprototyze** [comment]
Note: Pandemic also activates outside PvP environments whenever you exit an arena/ battleground.
Effect gets removed after a duel or logout.
Pandemic also triggers from other abilities besides Outbreak (rune-spending abilities)

**Comment by Moustachos** [comment]
Ref #5979
