### ISSUE TITLE
dk frost armor bugged

### ISSUE THREAD

**Issue by ixodan** [Valhalla-Gaming/Tracker#8270]
**Describe the issue you're having**:
death knights frost have bugged armor dont reduce the dmg u take in pvp 
**Explain how you expect it work**:
a class like dk have 2800 armor in pvp should have like 22% reduce dmg
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Analog-Valhalla** [comment]
Armor fixed many updates ago. :D
