### ISSUE TITLE
Hunter 

### ISSUE THREAD

**Issue by Maracuchote300** [Valhalla-Gaming/Tracker#828]
Pets are unable to have any spec, once you click learn then yes, nothing happens. "Kill command" doesn't work either http://www.wowhead.com/spell=34026/kill-command it takes the focus but it doesn't do any damage. The pet spell "Prowl" http://www.wowhead.com/spell=24450/prowl doesn't work. The pet goes into stealth mode but comes out of it when it nears the hostile npc. Also when right clicking the ability, the pet will go into stealth mode and not come out of it at all, even when not in a fight.

**Comment by Reloque** [comment]
Pets cannot specialize #257
Kill Command #346 as a side note this requires beastmaster specialization

I couldn't find anything on the Prowl issue for pets, so thanks.

**Comment by Maracuchote300** [comment]
Yeah, I have BM as spec. As for the Prowl issue, no problem, glad to help.

**Comment by zwei7** [comment]
I noticed the kill command does jack all. I have to arcane bolt verything.

**Comment by Moustachos** [comment]
Prowl is removed when your pet is spotted by an hostile unit, and that's intended.

The other bugs have been fixed in previous updates.

**Comment by Moustachos** [comment]
Ref #2266
