### ISSUE TITLE
Warrior revenge spell

### ISSUE THREAD

**Issue by Leondezwart** [Valhalla-Gaming/Tracker#8281]
**Describe the issue you're having**:

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1.  Does not reset/3 second cooldown reduction when a parry or dodge happens
2.  parry/dodge should reset the cooldown
3.  fix it :D

Revenge: Revenge
Melee Range
Instant	9 sec cooldown
Requires Warrior (Protection)
Requires level 22
Requires One-Handed Melee Weapon
Swing in a wide arc, dealing (340.2% of Attack power) damage to all enemies in front of you.

Your successful dodges and parries reset the remaining cooldown on Revenge up to once per 3 sec.

Generates 5 Rage.

**Links to Wowhead, YouTube, etc**:

**Comment by Aprophys** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7614

**Comment by Moustachos** [comment]
Ref #5979
