### ISSUE TITLE
Warrior focused rage

### ISSUE THREAD

**Issue by Leondezwart** [Valhalla-Gaming/Tracker#8282]
**Describe the issue you're having**:

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1.  Focused Rage dissapears after you use  any spell/ability and doesnt seem to give 51% extra dmg on shield slam.
2.  spend rage on focused rage to get more dmg of shield slam and kill an enemy
3.  fix it that it wont just dissapear when using an ability

**Links to Wowhead, YouTube, etc**:

**Comment by Aprophys** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7351
