### ISSUE TITLE
Warrior intervene/intercept

### ISSUE THREAD

**Issue by Leondezwart** [Valhalla-Gaming/Tracker#8283]
**Describe the issue you're having**:

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. intervene/intercept does not work on enemy nor on a friendly target.
2. it should kinda be like an charge but it does nothing.
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Aprophys** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/6861
