### ISSUE TITLE
Warrior heroic leap

### ISSUE THREAD

**Issue by Leondezwart** [Valhalla-Gaming/Tracker#8285]
**Describe the issue you're having**:

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. Heroic leap  works ok but it also should do some damage.
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Aprophys** [comment]
Reported https://github.com/Valhalla-Gaming/Tracker/issues/8147
