### ISSUE TITLE
Warrior storm bolt

### ISSUE THREAD

**Issue by Leondezwart** [Valhalla-Gaming/Tracker#8286]
**Describe the issue you're having**:

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. STorm bolt does not work it only stuns the target, but it does damage
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Ezikeal** [comment]
storm bolt works but it damages the target and stuns them but if u hit them again the stun will go away

**Comment by forstix** [comment]
that doesn't even stun tested many times

**Comment by spenzostolen** [comment]
The stun does not work, but it deals damage.

**Comment by Ezikeal** [comment]
hmm probably just someone else stunning them xD thinking it was the storm bolt that stuns them

**Comment by Moustachos** [comment]
Ref #5979
