### ISSUE TITLE
Warrior inspiring precense

### ISSUE THREAD

**Issue by Leondezwart** [Valhalla-Gaming/Tracker#8287]
**Describe the issue you're having**:

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. This talent should heal the warrior for 3% of the dmg done by himself, but it doesnt heal himself nor an ally
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by MrNonameNo3** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7854

**Comment by Moustachos** [comment]
Ref #5979
