### ISSUE TITLE
Warrior impending victory

### ISSUE THREAD

**Issue by Leondezwart** [Valhalla-Gaming/Tracker#8288]
**Describe the issue you're having**:

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. Impending victory.
2. does dmg but doesnt heal for the amount is says
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Aprophys** [comment]
Reported https://github.com/Valhalla-Gaming/Tracker/issues/6852
