### ISSUE TITLE
Quest Highmountain Amateur Hour

### ISSUE THREAD

**Issue by Lhyron** [Valhalla-Gaming/Tracker#8291]
**Describe the issue you're having**:
NPCs are hostile, you can't talk to them. 

**Explain how you expect it work**:
They should be neutral and have a dialogue to trigger and validate the quest.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=40170/amateur-hour
https://www.youtube.com/watch?v=6UgNVcjM4N0

PS: I did it with my mage 2 days ago and it was perfectly working. I suppose ppl didn't kill NPCs this could explain why they are stuck in hostile mode.

**Comment by Guybrush-VR** [comment]
What happens if you kill them? Do they come back to their initial behaviour or still stuck as hostile?

**Comment by Guybrush-VR** [comment]
Fixed.

**Comment by Lhyron** [comment]
I'm sorry I forgot to mention that the NPCs can't be kill: "the target can't be attacked". The update hasn't fixed the bug.
