### ISSUE TITLE
arcane missiles

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#8308]
**Describe the issue you're having**:
arcane missiles always proc after casting... arcane missiles. so u can spam it forever
**Explain how you expect it work**:
"Each damaging spell cast has a 15% chance to activate Arcane Missiles. Chance doubled for Arcane Blast."
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=5143/arcane-missiles

**Comment by spraypaint1993** [comment]
Now Arcane missiles can be activate by casting arcane missiles, this shouldnt be right casting arcane missiles CANT activate another arcane missiles!

**Comment by Analog-Valhalla** [comment]
Does not represent 7.1.5 Issue. Closing this to prevent duplicates. Thank you :D #8916
