### ISSUE TITLE
Flare

### ISSUE THREAD

**Issue by Reloque** [Valhalla-Gaming/Tracker#833]
The hunter ability [Flare](http://www.wowhead.com/spell=1543)(1543) may not work: it does send a flare out but the flare which persists for the correct duration, but does not reveal [stealthed](http://www.wowhead.com/spell=20540)(20540) [Ashenvale Outrunners](http://www.wowhead.com/npc=12856)(12856) to my level 41 huntress.

Notably, [Track Hidden](http://www.wowhead.com/spell=19885)(19885) does reveal these on the map.

**Comment by Collector-Valhalla** [comment]
It also applies that flare debuff on you instead of enemies.

**Comment by Moustachos** [comment]
Ref #2266

**Comment by Trekex** [comment]
It works with rogues, but not with mage invisibility. I have no idea if it should

**Comment by Moustachos** [comment]
Ref #2266
