### ISSUE TITLE
Shadow Priest Spell - Void Eruption

### ISSUE THREAD

**Issue by mnahirnyy** [Valhalla-Gaming/Tracker#8330]
**Describe the issue you're having**:
 http://www.wowhead.com/spell=228260/void-eruption
 This spell is not able to cast when your character gain 100 insanity.
**Explain how you expect it work**:
  http://www.wowhead.com/spell=228260/void-eruption should be able to cast and activate the voidform(http://www.wowhead.com/spell=194249/voidform) for your character
**Steps to reproduce the problem**:

1. Cast all the spells as shadow priest which generate insanity. Make sure you gain 100 insanity. 
2. In case you gain 100 insanity the spell "Void Eruption" will be highlighted.
3. Try to click on it or press the appropriate button to cast Void Eruption and nothing happens.

**Links to Wowhead, YouTube, etc**:
Sorry, don't have the recorded video. Wowhead spells links are mentioned previously.

**Comment by forstix** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/8229 ?

**Comment by mnahirnyy** [comment]
probably - yes. 
Dublicate.

**Comment by Aprophys** [comment]
Ref https://github.com/Valhalla-Gaming/Tracker/issues/8229
