### ISSUE TITLE
Paladin avenger shield not working

### ISSUE THREAD

**Issue by braebrook** [Valhalla-Gaming/Tracker#8331]
**Describe the issue you're having**:
Avenger shield not working or doing any damage
**Explain how you expect it work**:
Should hit multiple mobs and do damage
**Steps to reproduce the problem**:

1. Pulled multiple mobs but doesn't do any damage or hit mobs, it wS always hitting mobs during questing 1-100.
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Aprophys** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7762

**Comment by braebrook** [comment]
Is this fixed I can test it later today

**Comment by GM-Pyromanic** [comment]
@braebrook No it was closed as it is a duplicate report of #7762
