### ISSUE TITLE
Endora Moorehead outdated

### ISSUE THREAD

**Issue by Kezeal** [Valhalla-Gaming/Tracker#8333]
**Describe the issue you're having**:
Endora Moorehead in Dalaran has her old inventory.
**Explain how you expect it work**:
She should have Mystical Tome: Illusion and Mystical Tome: Arcane Linguist, but instead she has Tome of Dalaran Brilliance which appears as Magic Consumed Book, because it no longer is a thing in the game.
**Steps to reproduce the problem**:

1. Go to Dalaran
2. Speak to Endora Moorehead
3. Lower your head in sadness

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/npc=28715/endora-moorehead
http://www.wowhead.com/item=136799/mystical-tome-illusion
http://www.wowhead.com/item=136797/mystical-tome-arcane-linguist

**Comment by malex1024** [comment]
Thanks for your report! I've written the fix, and her vendor table should be updated...eventually. 👍

**Comment by Kezeal** [comment]
Her vendor table is now updated, this can be closed.
