### ISSUE TITLE
Frost Death Knight Bugs

### ISSUE THREAD

**Issue by MagvinCZ** [Valhalla-Gaming/Tracker#8334]
- [ ] 1) My runes replenish one by one ( Instead of three at once )
- [ ] 2) Sometimes I can´t use Obliterate ( I must use another ability, and then it works for a while )
- [ ] 3) Talent Icy Talon doesn´t give attack speed
- [ ] 4) Talent Frozen Pulse doesn´t do anything
- [ ] 5) Talent Hungering Rune Weapon doesn´t give rune power and runes overtime
- [ ] 6) Talent Gathering Storm doesn´t increase damage and duration of Remorseless Winter
- [ ] 7) Talent Glacial Advance doesn´t do anything...
- [ ] 8) Ability of DK´s  artifact weapon doesn´t work
- [ ] 9) Honor talent Cadaverous Pallor doesn´t work

Links on wowhead: 
http://www.wowhead.com/spell=194909
http://www.wowhead.com/spell=20712
http://www.wowhead.com/spell=19491
http://www.wowhead.com/spell=19491327
http://www.wowhead.com/spell=1948786
http://www.wowhead.com/artifact-calc/death-knight/frost/HkUDIMAGwDBuAwcQMHUDB3AQeAEHoBB7AQfAFEIDU0AQ

**Comment by theprototyze** [comment]
Frozen Pulse works as of 7.1.5.

**Comment by Moustachos** [comment]
Ref #5979
