### ISSUE TITLE
Missing Arcane Relic

### ISSUE THREAD

**Issue by xKillBornx** [Valhalla-Gaming/Tracker#8363]
I have farm arcane relic in all the place that i know they drop ...and i get none ..i am farming by more then 1 weeak

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by DiamondStud** [comment]
They do drop, I have gotten them myself in Suramar. Also they are pretty common on the AH although quite expensive.
