### ISSUE TITLE
Quest NPC - general workings - dialog not closing

### ISSUE THREAD

**Issue by tstki** [Valhalla-Gaming/Tracker#8371]
**Describe the issue you're having**:
Accepting a quest from a NPC with multiple quests, leaves the quest dialog open.

**Explain how you expect it work**:
After accepting a quest, the dialog should close, and the next one should open,. or back to the main selection window.

**Steps to reproduce the problem**:

1. Accept a quest
2. Wait for the quest dialog to close
3. nothing happens
4. decline the quest, or press [X] (the quest will still be accepted)
5. accept the next quest available by this npc.
6. repeat

**Links to Wowhead, YouTube, etc**:
Example:
- http://www.wowhead.com/npc=41949/dark-ranger-alina

**Comment by GM-Pyromanic** [comment]
This happens on retail also.
