### ISSUE TITLE
Unable to learn second gathering profession as new character.

### ISSUE THREAD

**Issue by tstki** [Valhalla-Gaming/Tracker#8372]
**Describe the issue you're having**:
- I learned skinning
- I try to learn Herbalism. Did not work.
- I try to learn Mining. Did not work.

**Explain how you expect it work**:
- Go to the proper npc to learn any 2 professions, and be able to learn them.

**Steps to reproduce the problem**:
1. See above

**Workaround**:
- Unlearned skinning
- Learned Mining
- Learned Herbalism

The sequence in which you learn professions should have no impract on it succeeding or not, as you may already have a skill that you leveled to 300 or up.

**Comment by GM-Pyromanic** [comment]
Known issue please use search feature before reporting a issue to see if a report has already been made.

#6295
