### ISSUE TITLE
DH BUG abusing in BG, Jumping huge distances with Flag! + screenshots

### ISSUE THREAD

**Issue by Psychadelic** [Valhalla-Gaming/Tracker#8379]
**Describe the issue you're having**: 

This dh - snip- is bug abising at this very moment at the Bgs, He found some way to jump Huge distances. It is somehow related with the Methamorphosis skill on Havoc.  In 1 of the pics you can see 1 of the players explaining how does this occur. I didn't really understand. But this dude is cheating in Bgs.. He gets the Flag and jumps the whole map. I think he must be banned asap!? In the pics you can see how HUge the chain is. That is not possible in normal gameplay. IF it is so long that means he must of basically have ported himself to the other side of the map.

**Explain how you expect it work**:

Cant jump such distances. 

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by GM-Pyromanic** [comment]
Issue tracker is not the place to report players abusing the issue tracker is for reporting spells ect that need to be fixed OP is snipped of all images and name of the player as it is considered naming and shaming which is against the rules set by the Valhalla team please open a new report for the spell that needs to be fixed without naming and shaming players for abusing
