### ISSUE TITLE
[Monk][Brewmaster][Artifact Trait] Obstinate Determination

### ISSUE THREAD

**Issue by Hemoglobine-Valhalla** [Valhalla-Gaming/Tracker#8387]
**Describe the issue you're having**:
Only reporting this so once Gift of the Ox get fixed it can be looked and fixed if needed.
**Explain how you expect it work**:
Gift of the Ox summons an additional Healing Sphere when your health drops below 35%.
**Steps to reproduce the problem**:

1.  Get the trait
2.  Let your health drop below 35%

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=216424/obstinate-determination

**Comment by cesium136** [comment]
this trait can be considered important because it always the monks health to dance around 35% and key for there survival.

**Comment by Moustachos** [comment]
Ref #5979
