### ISSUE TITLE
scarlet monastery

### ISSUE THREAD

**Issue by Primeribb** [Valhalla-Gaming/Tracker#8388]
**Describe the issue you're having**:
no armory key in the box after the last boss in library
**Explain how you expect it work**:
you are supposed to get the armory key out of the box after you kill the last boss in library 
**Steps to reproduce the problem**:

1. I ran it 3 times me and the guy I ran neither 1 got the key
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by GM-Pyromanic** [comment]
Scarlet Monastery: Revamped in Mists of Pandaria to replace the Armory and Library wings of the Scarlet Monastery. It's new name is the Scarlet Halls. This is why there is a door that is no longer accessible. This single instance is not part of the core game any longer.

Scarlet Halls: Revamped in Mists of Pandaria to replace the Graveyard and Cathedral wings of the old Scarlet Monastery,

#1856
