### ISSUE TITLE
paladin ret eye for an eye talent not working

### ISSUE THREAD

**Issue by ixodan** [Valhalla-Gaming/Tracker#8395]
**Describe the issue you're having**:
dont reduce dmg and dont couterattacks enemies 
**Explain how you expect it work**:
it should reduce dmg taken by 35% and counterattack all enemies striking u in melee combat
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by forstix** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7876

**Comment by GM-Pyromanic** [comment]
Duplicate report #7876
