### ISSUE TITLE
Hae'Wilani limited supply

### ISSUE THREAD

**Issue by Reloque** [Valhalla-Gaming/Tracker#840]
Axecrafter [Hae'Wilani](http://www.wowhead.com/npc=12045)(12045) in Shadowprey Village, Desolace sells unlimited [Midnight Axe](http://www.wowhead.com/item=12250)s(12250) which should have a stock of one, and she doesn't sell [Merciless Axe](http://www.wowhead.com/item=12249)s(12249) at all (should also have a stock of one).

**Comment by Tregeta** [comment]
fixed
