### ISSUE TITLE
DK frost howling blast

### ISSUE THREAD

**Issue by ixodan** [Valhalla-Gaming/Tracker#8401]
**Describe the issue you're having**:
it doesnt do 300% dmg to the secondary targets when rime is on
**Explain how you expect it work**:
howling blast should do 300% more dmg to all targets
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=49184/howling-blast
http://www.wowhead.com/spell=59052/rime

**Comment by Moustachos** [comment]
Works just fine on current version.

**Comment by Moustachos** [comment]
Ref #5979
