### ISSUE TITLE
Shadowmoon Valley (Outland) --> Divination: Gorefiend's Truncheon

### ISSUE THREAD

**Issue by MyJ3** [Valhalla-Gaming/Tracker#8402]
**Describe the issue you're having**:
No se encuentran por las zonas que indica la misión a los npcs http://www.wowhead.com/npc=21784/ghostrider-of-karabor que lleva el objeto http://www.wowhead.com/item=30800/gorefiends-truncheon

They are not found by the areas indicated by the mission to the npcs http://www.wowhead.com/npc=21784/ghostrider-of-karabor bearing the object http://www.wowhead.com/item=30800/ Gorefiends-truncheon
**Explain how you expect it work**:
Deberían aparecer por alguna parte de la zona indicada por la misión los npcs http://www.wowhead.com/npc=21784/ghostrider-of-karabor y y entregar el objeto http://www.wowhead.com/item=30800/gorefiends-truncheon 

They should appear for a part of the area indicated by the mission of the nicks http://www.wowhead.com/npc=21784/ghostrider-of-karabor and and deliver the object http://www.wowhead.com/item= 30800 Gorefiends-truncheon

**Links to Wowhead, YouTube, etc**:
https://www.youtube.com/watch?v=ixjLdun9xUg
http://www.wowhead.com/quest=10636/divination-gorefiends-truncheon
@Cidragon

**Comment by GM-Pyromanic** [comment]
Duplicate report #4409
