### ISSUE TITLE
Quest Bug Highmountain -->That guy in the costume

### ISSUE THREAD

**Issue by MyJ3** [Valhalla-Gaming/Tracker#8407]
**Describe the issue you're having**:
Al hablar con el npc http://www.wowhead.com/npc=94973/tamara-sigmund te debe dar la opción de volar a una ubicación a poder hablar co un npc y mostrarte todos los vuelos a los que puedes volar.

When speaking with npc http://www.wowhead.com/npc=94973/tamara-sigmund you should give the option to fly to a location to be able to talk to a npc and show you all flights that you can fly.
**Explain how you expect it work**:
cuando hablas con el npc http://www.wowhead.com/npc=94973/tamara-sigmund te sale las 2 opciones. 1. la de poder volar a tus vuelos y 2. la de poder volar a la ubiación donde te mand a ac

When you talk to npc http://www.wowhead.com/npc=94973/tamara-sigmund you get the 2 options. 1. to be able to fly to your flights and 2. to be able to fly to the place where you have to complete the missionompletar la misión

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=40244/that-guy-in-the-costume
https://www.youtube.com/watch?v=c-OXQkxmrSk
@Guybrush-VR

**Comment by Guybrush-VR** [comment]
Not an issue per se as I didn't script it yet! I'll close it for now, the script will come in an upcoming update! :smile: 
Thanks for your report.
