### ISSUE TITLE
Human Starting Zone "Northshire Valley"

### ISSUE THREAD

**Issue by phikaro** [Valhalla-Gaming/Tracker#8409]
**Describe the issue you're having**:
The Stormwind Infantry NPCs at the starting zone of Humans race "Northshire Valley " do not have the fight animation, they just stay on one place, while they should pretend fighting with Blackrock Worgs. Also the npc Brother Paxton should heal the surrounded Stormwind Infantry npcs when they get damaged from the Blackrock Worgs, also when getting near the NPC Brother Paxton, it does not buff my character with power word fortitude.
**Explain how you expect it work**:
The Stormwind Infantry NPCs are supposed to have animation fight with Blackrock Worgs, but not really damaging them. The npc Brother Paxton should heal the surrounded Stormwind Infantry npcs when they get damaged from the Blackrock Worgs, also when getting near the NPC Brother Paxton, it should buff my character with power word fortitude.

**Links to Wowhead, YouTube, etc**:
http://wowwiki.wikia.com/wiki/Northshire_Valley

http://wow.gamepedia.com/Stormwind_Infantry

http://www.wowhead.com/npc=49871/blackrock-worg

http://www.wowhead.com/npc=951/brother-paxton

**Comment by GM-Pyromanic** [comment]
Npc's are working correctly as of the latest update

![5e96e205642b4548ba57d081d390cb7a](https://cloud.githubusercontent.com/assets/20587569/21744687/a55ee38e-d512-11e6-95d7-5875337f8109.png)

**Comment by phikaro** [comment]
Ah ok, guess I had to delete cache folder, now is ok.
