### ISSUE TITLE
Flying Carpet Bug

### ISSUE THREAD

**Issue by garynewberg** [Valhalla-Gaming/Tracker#8411]
The Flying carpet doesn't work. 

In the collections tab, the icon is disabled and the hover over text says "You do not meet the requirements". After learning the carpet for the first time the carpet does works, but after logging out and then logging in again the carpet is disabled in the collections tab. 

Steps to reproduce: 
1. Level tailoring skill above 300 
2. Gather materials and create the carpet
3. Mount the carpet and fly around. 
4. Log out
5. Log in.
6. Open Collections tab and note the carpet is now disabled.

**Links to Wowhead, YouTube, etc**:

**Comment by GM-Pyromanic** [comment]
Duplicate report #8186
