### ISSUE TITLE
Shadowmoon Valley (Outland) --> The Cipher of Damnation - Ar'tor's Charge

### ISSUE THREAD

**Issue by MyJ3** [Valhalla-Gaming/Tracker#8412]
**Describe the issue you're having**:
Al ir acompañado del espiritu de Ar'tor's y pasar por la zona indicada por la misión, no aparece el npc http://www.wowhead.com/npc=20427/veneratus-the-many para obtener http://www.wowhead.com/item=30453/second-fragment-of-the-cipher-of-damnation.

When accompanied by the spirit of Ar'tor's and pass through the area indicated by the mission, npc does not appear http://www.wowhead.com/npc=20427/veneratus-the-many to obtain http: // www. Wowhead.com/item=30453/second-fragment-of-the-cipher-of-damnation.
**Explain how you expect it work**:
Al ir acompañado del espiritu de Ar'tor's y pasar por la zona indicada por la misión, debe aparece el npc http://www.wowhead.com/npc=20427/veneratus-the-many entregar el objeto http://www.wowhead.com/item=30453/second-fragment-of-the-cipher-of-damnation.

When accompanied by the spirit of Ar'tor's and passing through the area indicated by the mission, must appear the npc http://www.wowhead.com/npc=20427/veneratus-the-many deliver the object http: // www .wowhead.com / item = 30453 / second-fragment-of-the-cipher-of-damnation.

**Links to Wowhead, YouTube, etc**:
https://www.youtube.com/watch?v=FKNCSAbTRtQ
http://www.wowhead.com/quest=10540/the-cipher-of-damnation-artors-charge

**Comment by GM-Pyromanic** [comment]
Duplicate report #2172
