### ISSUE TITLE
hunter survival wat of the Mok'Nathal bugged

### ISSUE THREAD

**Issue by ixodan** [Valhalla-Gaming/Tracker#8414]
**Describe the issue you're having**:
all attacks procs way of the mok'nathal
**Explain how you expect it work**:
it should procs off raptor strike only
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by GM-Pyromanic** [comment]
duplicate report #7128
