### ISSUE TITLE
Shadowmoon Valley (Outland) --> The cipher of damnation

### ISSUE THREAD

**Issue by MyJ3** [Valhalla-Gaming/Tracker#8415]
**Describe the issue you're having**:
Cuando usas el objeto http://www.wowhead.com/item=30657/the-cipher-of-damnation cerca del altar de Gul'dan se mueve la pantalla, pero no ocurre nada no se invoca al npc http://www.wowhead.com/npc=21181/cyrukh-the-firelord

When you use the object http://www.wowhead.com/item=30657/the-cipher-of-damnation near the altar of Gul'dan the screen moves, but nothing happens the npc is not invoked http: // Www.wowhead.com/npc=21181/cyrukh-the-firelord
**Explain how you expect it work**:
Cuando usas el objeto http://www.wowhead.com/item=30657/the-cipher-of-damnation cerca del altar de Gul'dan se debe mover la pantalla, y se debe invocar al npc http://www.wowhead.com/npc=21181/cyrukh-the-firelord

When you use the object http://www.wowhead.com/item=30657/the-cipher-of-damnation near the Gul'dan altar you should move the screen, and invoke the npc http: // www. Wowhead.com/npc=21181/cyrukh-the-firelord

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=10588/the-cipher-of-damnation
![imagen](https://cloud.githubusercontent.com/assets/23507886/21741720/39a13b66-d4df-11e6-930a-8c76779940af.png)

**Comment by GM-Pyromanic** [comment]
Duplicate report #2235
