### ISSUE TITLE
[Arms Warrior] Intercept (Honor Talent)

### ISSUE THREAD

**Issue by Tolno** [Valhalla-Gaming/Tracker#8419]
**Describe the issue you're having**: It replace _Charge_ even when I'm not flagged for PvP. And as it's an honor talent, it refuses to work if I'm not in a BG / Arena or a duel. No more _Charge_ for my arms warrior until I reach honor level 25 to get rid of that talent, I'm 8 now...

**Explain how you expect it work**: It should only replace charge when I'm in BG / Arena or duelling

**Steps to reproduce the problem**:

1. Take an Arms Warrior, with honor lvl 8 at least
2. Learn **_Intercept_**
3. Try to charge outside of pvp

**Links to Wowhead, YouTube, etc**:
[http://www.wowhead.com/spell=198758/intercept](url)

**Comment by forstix** [comment]
Same with every honor talent that replace regular spell and reported here https://github.com/Valhalla-Gaming/Tracker/issues/8316
