### ISSUE TITLE
Mai'Lahii limited supply

### ISSUE THREAD

**Issue by Reloque** [Valhalla-Gaming/Tracker#842]
Fishing Supplies vendor [Mai'Lahii](http://www.wowhead.com/npc=12031)(12031) in Shadowprey Village, Desolace sells unlimited [Strong Fishing Pole](http://www.wowhead.com/item=6365)s(6365) which should have a stock of one. She also doesn't sell any [Aquadynamic Fish Attractor](http://www.wowhead.com/item=6533)s(6533), which should be sold with a stock of two.

**Comment by Tregeta** [comment]
fixed
