### ISSUE TITLE
Arcane mage : Artifact spell dont work 

### ISSUE THREAD

**Issue by UnicornOfDeathBG** [Valhalla-Gaming/Tracker#8426]
**Describe the issue you're having**:
when you use (mark of aluneth) nothing is happening 
**Explain how you expect it work**:
i expect to see kind of mark on the target which is doing 185,904 arcane damage over 6.1 and detonationg for arcane damage equal 15 % of my maximum mana 
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by mrmoobles** [comment]
i thought this also at first it has a cast time whereas i'd simply assumed it was instant cast but it works fine for me ^^

**Comment by UnicornOfDeathBG** [comment]
I tried but it isnt working . There are visual effects(bcs before there weren't )but there isnt damage

**Comment by Lhyron** [comment]
[8337](https://github.com/Valhalla-Gaming/Tracker/issues/8337) already reported

**Comment by Guybrush-VR** [comment]
Thanks Lhyron.
