### ISSUE TITLE
 [Scales of Earth]

### ISSUE THREAD

**Issue by neano300** [Valhalla-Gaming/Tracker#8427]
**Describe the issue you're having**:
The spell when you block don't hit or just dont work.
**Explain how you expect it work**:
Critical blocks have a chance to cause an eruption from Scale of the earth-Warden, increasing your armor by 30% and dealing X physical damage to all enemies in front of you
**Steps to reproduce the problem**:

1.  Learn it
2.  Block it
3.  Do not hit or work

**Links to Wowhead, YouTube, etc**:
Pics from my last Bg. the spell don't appear because do not work.
[img]http://i.imgur.com/w6cvL9d.jpg[/img]
[img]http://i.imgur.com/tGEFz7I.jpg[/img]
[img]http://i.imgur.com/6ti32bi.jpg[/img]

WowHead Link: http://www.wowhead.com/spell=189059/scales-of-earth

**Comment by Moustachos** [comment]
Works just fine.

**Comment by Moustachos** [comment]
Ref #5979
