### ISSUE TITLE
Intercept Protection warrior 

### ISSUE THREAD

**Issue by neano300** [Valhalla-Gaming/Tracker#8428]
**Describe the issue you're having**:
Sometimes when you use intercept you don't Charge to your enemy.
**Explain how you expect it work**:
Run at high speed toward an ally or enemy.
**Steps to reproduce the problem**:

1.  Use intercept
2.  Sometimes work 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=198304/intercept#changelog

**Comment by Moustachos** [comment]
Will be fixed on next update.
