### ISSUE TITLE
Bolt of mageweave

### ISSUE THREAD

**Issue by Mistwarrior** [Valhalla-Gaming/Tracker#8430]
**I kept wondering why i never had enough mageweave for tailoring. so i gathered 400 mageweave and turned it into bolts of magweave. However after i finished, i opened my inventory, and there was no mageweave at all, bolts or cloth.**:

**It should have been 100 bolts of mageweave in my inventory**:

**make bolts of mageweave in large quantities. some or all of it comes up missing**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by forstix** [comment]
Did u check your regant bank?

**Comment by Mistwarrior** [comment]
Ok that's just strange, it was in my reagent bank. Please tell me the game isn't supposed to work like this?

**Comment by forstix** [comment]
I dont think this is how it should works but tbh i like the idea to be able to farm without spending bag place :)

**Comment by BeyondSteaLikez** [comment]
#7891

**Comment by Guybrush-VR** [comment]
As BeyondSteaLikez said, already reported!
Thanks for your report though, I'll close it now to prevent duplicates. :smile:
