### ISSUE TITLE
[Mage] hit chance issues in Legion areas

### ISSUE THREAD

**Issue by mrmoobles** [Valhalla-Gaming/Tracker#8433]
so when levelling my mage the hit chance would be at a guess 10%, extremely low when fighting legion mobs, seems fine at 110 but up to about 107 i was still missing a majority of attacks even with 810 green gear and have spoken to another mage who is having similar issues, this problem happens with all specs, thanks ^^

**Comment by forstix** [comment]
Know issue with scaling problem every class have them and caster even more

**Comment by Guybrush-VR** [comment]
As forstix said, it is a scaling issue. Already reported here: #6781. 
Thanks for your report, I'll close it now to prevent duplicates! :+1:
