### ISSUE TITLE
[NPC] Burning Blade Cultist drops

### ISSUE THREAD

**Issue by Enay** [Valhalla-Gaming/Tracker#8434]
**Issue**:

[Burning Blade Cultist](http://www.wowhead.com/npc=3199/burning-blade-cultist) in Durotar (Dustwind Cave) is dropping level 60+ gear. For me he dropped 2x [Garrote-string Necklace](http://www.wowhead.com/item=24073/garrote-string-necklace) at once and a few level 60 uncommon items.

**How it should work**:

He shouldn't be dropping these items.

**Steps to reproduce the problem**:

1.  Kill **Burning Blade Cultist**
2.  Check the loot

**Comment by malex1024** [comment]
Thanks for the report! 👍 We'll work on removing all improper items ASAP!
