### ISSUE TITLE
Disconnection when pressing space bar two or more times

### ISSUE THREAD

**Issue by davidosky101** [Valhalla-Gaming/Tracker#8436]
I have a demon hunter, and at the moment of wanting to do the dobe jump and later to plan (I press the space bar 3 times) the server disconnects me, and no matter the place where this, always disconnects me.
I consulted several people and they tell me that it is a bug, so you should wait about 2 seconds to be able to press the space bar again.
Please be able to fix this error, since being a demon hunter is very difficult to play without using the double jump or plan, since until arriving at the headquarters of classes is an ordeal.

It should be possible to use a double jump and plan without waiting for the fact that this will cause a disconnection

**Steps to reproduce the problem**:

1. Press spacebar three times consecutively
2. Press spacebar three times consecutively
3. Press spacebar three times consecutively

**Links to Wowhead, YouTube, etc**:

**Comment by Guybrush-VR** [comment]
Already reported here: #7393.
Thanks for your report, I'll close it to prevent duplicates. :dancer:
