### ISSUE TITLE
[class] warrior - Revenge

### ISSUE THREAD

**Issue by ticklex** [Valhalla-Gaming/Tracker#844]
How it should work: Instantly attack an enemy and two additional enemies, dealing (352.8% of Attack power) damage to the primary target and 50% damage to the secondary targets, and generating 20 Rage. Your successful dodges and parries reset the cooldown on Revenge.
How it works: Doesnt reset Cooldown when dodge or parry.
http://www.wowhead.com/spell=6572/revenge

**Comment by Tregeta** [comment]
@miloskovac
> 
Warrior revenge ablitiy does way too much dmg. Hitting ppl with 60k in bgs

**Comment by Leondezwart** [comment]
this spell still does not reset when a warrior parries or dodges

srry for bad post :(
