### ISSUE TITLE
Monk>Brewmaster>Tiger Palm's Brew CD reduction

### ISSUE THREAD

**Issue by Nightcap** [Valhalla-Gaming/Tracker#8442]
**Describe the issue you're having**: Using Tiger palm does not lower the CD of Brews

**Explain how you expect it work**: Remaining recharge times of your Purifying Brew and Ironskin Brew (and the remaining cooldown of Fortifying Brew) are reduced by 1 second each time you use Tiger Palm and by 4 seconds each time you use Keg Smash.

**Steps to reproduce the problem**: Use a Brewmaster's Tiger palm while brews are on CD and notice how the CD's don't lower by one second on use of Tiger palm.

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=100780/tiger-palm

**Comment by cesium136** [comment]
this is rather important since ironskin brew and purifing brew have 21 sec cooldown and lowing that cooldown is essential for brewmaster. i would also like to note that keg smash also does not reduce of brews.

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #5979
