### ISSUE TITLE
Fetid Corspe, item drops every time. (Mob in Duskwood)

### ISSUE THREAD

**Issue by donnieyt** [Valhalla-Gaming/Tracker#8448]
**Describe the issue you're having**:
Fetid Corpse (Mob in Duskwood) is dropping the same item for everytime you kill them. The same item 100% droprate for every mob and they sell for quite alot.
**Explain how you expect it work**:
That the droprate should be lowered so it doesn't drop on every mob, because it sure ain't supposed to drop every time.
**Steps to reproduce the problem**:
1. Find the mob in Duskwood.
2. Kill it, sword drops, go vendor it.
3. ??????
4. Profit.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/npc=1270/fetid-corpse
http://www.wowhead.com/item=2014/black-metal-greatsword

**Comment by malex1024** [comment]
Once implemented, the drop rate on the item should be corrected. I appreciate the report! 👍
