### ISSUE TITLE
Venture Co. Miner (Mob in Northern Stranglethorn Vale) is dropping an item 100% all of the time.

### ISSUE THREAD

**Issue by donnieyt** [Valhalla-Gaming/Tracker#8449]
**Describe the issue you're having**:
Venture Co. Miner (Mob in Northern Stranglethorn Vale) is dropping a item called [Goblin Power Shovel] and it's not supposed to drop from every single mob.
**Explain how you expect it work**:
They're dropping the same item over and over again, every mob drops the item so I'm guessing the droprate is too high.
**Steps to reproduce the problem**:

1.  Find the mob in Northern Stranglethorn Vale
2.  Kill the mob, loot the [Goblin Power Shovel], sell it to a vendor for 83 silver
3.  ??????????
4. Profit.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/npc=1094/venture-co-miner
http://www.wowhead.com/item=1991/goblin-power-shovel

**Comment by malex1024** [comment]
I like the top comment on the [Goblin Power Shovel](http://www.wowhead.com/item=1991/goblin-power-shovel). Great stuff.

The drop rate is definitely too high; in fact, it shouldn't be dropping at all. Thank you for the report. :)
