### ISSUE TITLE
[Monk][Brewmaster] Stagger

### ISSUE THREAD

**Issue by Hemoglobine-Valhalla** [Valhalla-Gaming/Tracker#8459]
**Describe the issue you're having**:
Currently Stagger doesn't seems to work, it doesn't look like it actually does decrease 40% physical + half magical which would be 20% damage you take, plus the honor talent that adds half amount as magic staggered damage, it only adds the amount of staggered damage as stagger debuff, plus the own damage of the stagger does boost the damage staggered, so basically sometimes is just an endless stagger debuff, hitting you.
**Explain how you expect it work**:
You shrug off attacks, delaying 40% of Physical damage, instead taking it over 10 sec. Affects magical attacks at 50% effectiveness. + 
![new](https://cloud.githubusercontent.com/assets/16792371/21987882/887f33dc-dc05-11e6-928d-ed09ca37f091.jpg)

**Steps to reproduce the problem**:

1.  Make a monk
2.  Roll Bm
3.  Put that honor talent
4.  Let something hit you
5.  Change to Mistweaver, notice damage received is basically the same amount but without stagger debuff.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=115069/stagger
http://www.wowhead.com/spell=205147/eerie-fermentation

**Comment by Moustachos** [comment]
Stagger works just fine on its own.

You're right about Eerie Fermentation though: it doesn't work (yet).

**Comment by Moustachos** [comment]
Closing since Eerie Fermentation's effect changed in 7.1.5 (and is properly supported).

**Comment by Moustachos** [comment]
Ref #5979
