### ISSUE TITLE
Anub'ar Cultist (Mob in Dragonblight) is dropping Season 1 WotLK Arena gear and other things.

### ISSUE THREAD

**Issue by donnieyt** [Valhalla-Gaming/Tracker#8460]
**Describe the issue you're having**:
A mob in Dragonblight called Anub'ar Cultist is dropping season 1 WotLK Arena Gear for shamans and other things, but they're also dropping level 1-20 items from Quests around the world.
**Explain how you expect it work**:
They are obviously not meant to drop Arena gear as they're just a normal quest mob.
**Steps to reproduce the problem**:

1. Find the mob
2. Kill it.
3. Get random arena gear aswell as low level quest rewards for some reason.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/npc=26319/anubar-cultist

**Comment by Guybrush-VR** [comment]
Fixed!

**Comment by Traveler-Valhalla** [comment]
that was fast lol

**Comment by Guybrush-VR** [comment]
We're about to update, I'm pushing some last minute fixes. :-D
