### ISSUE TITLE
 [Monk] Transcendence

### ISSUE THREAD

**Issue by Luthienne88** [Valhalla-Gaming/Tracker#8466]
**Describe the issue you're having**:
Transcendence leaves spirit behind, but it doesn't stay in same place. It follows you, so you can't swap at long distance.
**Explain how you expect it work**:
"Split your body and spirit, leaving your spirit behind for 15 min. Use Transcendence: Transfer to swap locations with your spirit." Works at any distance, maximum 40 yd range.
**Steps to reproduce the problem**:

1. Use Transcendence from your spellbook on a monk character.
2. Take a few steps in any direction.
3. See that your spirit form follows you.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=101643/transcendence
http://www.wowhead.com/spell=119996/transcendence-transfer

**Comment by Nightcap** [comment]
Confirmed, worked before last update and now it's broke.

**Comment by Moustachos** [comment]
Fixed in previous update.

**Comment by Moustachos** [comment]
Ref #5979
