### ISSUE TITLE
Highmountain Quest: "Rite of Blood"

### ISSUE THREAD

**Issue by Lhyron** [Valhalla-Gaming/Tracker#8467]
**Describe the issue you're having**:
Marakhan appears when you approach Navarrogg. However, he doesn't kill Oakin Ironbull and can't be attacked and killed. It says "unvalid target".

PS: The recent crash has unbugged the quest.

**Explain how you expect it work**:
Marakhan should be killable once Oakin Ironbull is dead.

**Steps to reproduce the problem**:

1. Take the quest
2. Go next to Navarrogg
3. Wait & See if Marakhan can be attacked

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=39860/rite-of-blood
https://www.youtube.com/watch?v=O4GuHUJ-8sE
http://www.noelshack.com/2017-03-1484610052-capture-d-ecran-2017-01-16-a-23-25-21.png

**Comment by Guybrush-VR** [comment]
I see that you managed to finish it. For the others, if you're experiencing this issue, try to abandon and take the quest again. That should solve it!
I'll close this issue, don't hesitate to create a new one if this issue persists.
