### ISSUE TITLE
Arcane Mage Spell: "Presence of Mind"

### ISSUE THREAD

**Issue by Lhyron** [Valhalla-Gaming/Tracker#8468]
**Describe the issue you're having**:
The spell grants unlimited instant Arcane Blast since the last update.
EDIT: **The effect never consumes itself granting instant Arcane Blasts forever.**

**Explain how you expect it work**:
The talent should grant only 2 instant Arcane Blast.

**Steps to reproduce the problem**:

1. Cast Presence of mind
2. Spam instant Arcane Blast !!!
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Guybrush-VR** [comment]
Removed with 7.1.5.

**Comment by Lhyron** [comment]
It is removed in 7.1.5 as a talent but is now an active spell. It still doesn't work as expected.

**Comment by Guybrush-VR** [comment]
Thanks, you're right.  It's now a level 54 ability for Arcane Mage!

**Comment by Lhyron** [comment]
You should probably put a high priority to it as it is a gamebreaking issue especially in pvp...

**Comment by Moustachos** [comment]
Ref #5979
