### ISSUE TITLE
Main hand weapon gone on Protection Paladin

### ISSUE THREAD

**Issue by braebrook** [Valhalla-Gaming/Tracker#8473]
**Describe the issue you're having**:
I was killing mobs in highmountain and I obtained a scroll for 75 artifact power.  I right clicked on it in my bag and it said "I must equip an artifact weapon" .  I had my Truthguard and my main hand weapon both on.  When I moved my Truthguard to my bag it deleted my main hand weapon as well.  This was the weapon you got when starting Legion in Stormwind.  It was up to 782 item level, I need to get that back and it is not in my bag or anything.  I ended up buying Blade of the Silverhand from the quartermaster in my order hall just to get by.  Is there anyway to get that back, this has to be a bug I didn't delete anything all I did was move my Truthguard to my bag and on the character screen the main hand weapon was gone.

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by braebrook** [comment]
For some reason when I put the Truthguard back in my bags and then equipped it again my main hand weapon came back Oathseeker.

**Comment by Guybrush-VR** [comment]
Since it looks to be resolved, I'll close this issue.
