### ISSUE TITLE
New Tinkertown: [Down With Crushcog!] Quest

### ISSUE THREAD

**Issue by Hemabody** [Valhalla-Gaming/Tracker#8475]
Ah Gnomes, the most comical race in wow that makes you feel like Blizzard made them just to be a joke race. Just kidding, Gnomes have their own contributions and their own whole history (which is the less eventful between all the playable races) and of course, their own starting zone. I was playing with my newly rolled Gnome Hunter, and was surprised that all of these "special" quests were working, but found that the final one wasn't. That was quite the let down, however I am supposed to meet Mekkatorque at a certain area near the boss, where I talk to him and together we take down Crushcog, but the problem is that Mekkatorque doesn't spawn there, instead he spawns near the quest giver, and nothing happens when I talk to him.

Wowhead: http://www.wowhead.com/quest=26364/down-with-crushcog

Youtube: http://www.youtube.com/watch?v=ll45Sb1C3IY

**Comment by Guybrush-VR** [comment]
Could you provide a screenshot? This quest has been fully scripted and Mekkatorque should be at his right location.

**Comment by Hemabody** [comment]
![screenshot 2](https://cloud.githubusercontent.com/assets/24903222/22085506/0a431eb4-dddd-11e6-9a1d-ae087ceb13b5.png)
![screenshot 3](https://cloud.githubusercontent.com/assets/24903222/22085524/0fd3d828-dddd-11e6-93e7-6a7f901f4308.png)
 
The one with the warlock is from the youtube link, while the one with the rogue is me. For some reason he wasn't at the quest giver's place when I got back, but he surely isn't where he is supposed to be

**Comment by Guybrush-VR** [comment]
That is one weird issue, I'll look into it.

**Comment by Guybrush-VR** [comment]
Okay I checked on live and he is spawned apparently. Could you confirm that the quest is still working?

**Comment by Hemabody** [comment]
It worked

**Comment by Guybrush-VR** [comment]
Excellent! I'll close this issue then! :dancer:
