### ISSUE TITLE
Death Knight Passive: "Dark Succor"

### ISSUE THREAD

**Issue by Lhyron** [Valhalla-Gaming/Tracker#8476]
**Describe the issue you're having**:
The passive provide unlimited use of Death Strike for all its duration.

**Explain how you expect it work**:
It should be only for a single use.

**Steps to reproduce the problem**:

1. Kill a mob
2. Spam Death Strike with Dark Succor
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=178819/dark-succor

**Comment by theprototyze** [comment]
This issue doesn't exist anymore.

**Comment by Moustachos** [comment]
Ref #5979
