### ISSUE TITLE
Wall of steel Artifact Talent Protection Warrior.

### ISSUE THREAD

**Issue by neano300** [Valhalla-Gaming/Tracker#8486]
**Describe the issue you're having**:
Only redirect 1 hit.
**Explain how you expect it work**:
When you target an ally with Intercept, it redirects 2 additional attacks, and the damage you take from those attacks is reduced by 10%
**Steps to reproduce the problem**:

1.  Learn it.
2.  Use it on friendly target.
3. 

**Links to Wowhead, YouTube, etc**:
WoWhead: http://www.wowhead.com/spell=203261/wall-of-steel
Pic: [img]http://i.imgur.com/LsW4SOo.jpg[/img]

**Comment by Moustachos** [comment]
Works as intended, it's just that the tooltip of Intervene isn't updated when you pick up this trait (just like on retail).

**Comment by Moustachos** [comment]
Ref #5979
