### ISSUE TITLE
Druid talent Warrior of Elune.

### ISSUE THREAD

**Issue by Chipslover** [Valhalla-Gaming/Tracker#8496]
**Describe the issue you're having**:
After using Warrior of Elune (talent) it gives you 2 Lunar Strikes without casting it, but instead you can cast it unlimited times.
**Explain how you expect it work**:
You should get only 2 Lunar Strikes without casting
This also works with mage's talent which let's you use Arcane Blast 2 times without casting it.
**Steps to reproduce the problem**:

1. Learn the talent 
2. Use it
3. Spam Lunar Strike

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=202425/warrior-of-elune

**Comment by Lhyron** [comment]
Gamebreaking issue especially in pvp. Should have a high priority.

**Comment by Moustachos** [comment]
Ref #5979
