### ISSUE TITLE
Arcane Mage Spell: "Arcane Barrage"

### ISSUE THREAD

**Issue by Lhyron** [Valhalla-Gaming/Tracker#8503]
**Describe the issue you're having**:
Sometimes Arcane barrage deals damage but doesn't take into consideration the Arcane charges. Hence, even if enemies are packed, the spell will only target 1 enemy instead of the primary target and 4 others within 10 yards.

**EDIT** **After many tries, I noticed the spell, somehow, isn't instant. There may be a second or two for the spell to be cast especially when the Arcane barrage has to hit several targets.**

**Explain how you expect it work**:
Arcane barrage should deal damages correctly according to the number of Arcane charges and reach the secondary targets within 10 yards of the primary target.

**Steps to reproduce the problem**:

1. Spam Arcane barrage with 4 Arcane charges
2. Check damages
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=44425/arcane-barrage

**Comment by Moustachos** [comment]
Works just fine.

**Comment by Moustachos** [comment]
Ref #5979
