### ISSUE TITLE
Paladin - Protection  [Fist of Justice]

### ISSUE THREAD

**Issue by hackvice** [Valhalla-Gaming/Tracker#8520]
**Describe the issue you're having**:
Judgment does not reduce the cooldown on Hammer of Justice.
**Explain how you expect it work**:
Judgment reduces the remaining cooldown on Hammer of Justice by 10 sec.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=198054/fist-of-justice

**Comment by tribaljet** [comment]
Despite the previous update indicating that diminishing returns would've been fixed, Judgment still doesn't reduce the cooldown of Hammer of Justice.

**Comment by Moustachos** [comment]
Ref #5979
