### ISSUE TITLE
Paladin - Protection  [Crusader's Judgment]

### ISSUE THREAD

**Issue by hackvice** [Valhalla-Gaming/Tracker#8522]
**Describe the issue you're having**
Judgment must have 2 charges. 
**Explain how you expect it work**:
Judgment now has 2 charges, and Grand Crusader now also grants a charge of Judgment.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=204023/crusaders-judgment

**Comment by Moustachos** [comment]
Works just fine.

**Comment by Moustachos** [comment]
Ref #5979
