### ISSUE TITLE
Paladin - Protection  [Bastion of Light]

### ISSUE THREAD

**Issue by hackvice** [Valhalla-Gaming/Tracker#8523]
**Describe the issue you're having**:
Does not give 3 charges on Shield of the Righteous
**Explain how you expect it work**:
Immediately grants 3 charges of Shield of the Righteous.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=204035/bastion-of-light

**Comment by Moustachos** [comment]
Works just fine.

**Comment by Moustachos** [comment]
Ref #5979
