### ISSUE TITLE
Holy Paladin 60 talents dosen't working.

### ISSUE THREAD

**Issue by Sungoddess26** [Valhalla-Gaming/Tracker#8525]
Holy paladin's 60 talent , all of 60 talents vanishing after relog or after reviving from spirit angel in battlegrounds or in regular zones and until you rechange your talent , it won't working.

http://data.korkad.nu/f/wowscrnshot_012317_153240.jpg

**Comment by Sungoddess26** [comment]
Using empowered buffs like avenger wrath or holy avenger also deleting talent efect.

**Comment by Sungoddess26** [comment]
Entering battlegrounds arenas deleting talent efect.

**Comment by Sungoddess26** [comment]
We tested 60 level talents ( auras ) with different holy paladin and his auras didin't goes off after joining bgs or arenas or enrage buffs. However my paladin '' sungoddess '' loses all the buff when i enter arenas or battlegrounds or using enrage buffs. Wtf ?

**Comment by Sungoddess26** [comment]
Spell dosen't showup in my spellbook as '' passive ''

**Comment by Valhalla-Gaming** [comment]
Note: [Vindicator](http://www.wowhead.com/spell=200373) causes loss of Devotion Aura.

**Comment by Moustachos** [comment]
Ref #5979
