### ISSUE TITLE
Demon Hunter Honor Talent 24 Cleansed By Flame Bug

### ISSUE THREAD

**Issue by garynewberg** [Valhalla-Gaming/Tracker#8528]
The demon hunter honor talent 24 cleansed by flame does not work.

Immolation Aura should dispel all magical effects on you when cast.

**Steps to reproduce the problem**:

1. 
2. 
3. 

http://www.wowhead.com/spell=205625/cleansed-by-flame

**Comment by BeyondSteaLikez** [comment]
Also its Bugged it cleanse everything "magic" debuff when you pass over a soul (To get it)

**Comment by Moustachos** [comment]
Ref #5979
