### ISSUE TITLE
Legion Battleground/Arena PvP Buff ilvl 

### ISSUE THREAD

**Issue by hackvice** [Valhalla-Gaming/Tracker#8530]
**Describe the issue you're having**:
The is not Ilvl buff in Battlegrounds/Arena
**Explain how you expect it work**:
legion PVP lvl 110 players will have a base ilvl of 800, and for each extra 10 ilvls on your gear you would gain like 1% stats.The only contribution your gear will make to your overall power is through a small modifier based on your average item level.For every point that your average item level increases, your pre-determined PvP stats will increase by 0.1%. That means a 25 item level difference between two players only results in a 2.5% difference in stats, compared to the 25% difference it makes today.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
https://www.youtube.com/watch?v=g-yW-2Wnvyo

**Comment by forstix** [comment]
It call template and the dev are working on that issue atm

**Comment by Guybrush-VR** [comment]
forstix is right! I'll close this issue and link it to the one already existing about this matter to prevent duplicates.
Thank you for your report though! :smiley: 
#7461
