### ISSUE TITLE
Paladin - Protection [Hand of the Protector]

### ISSUE THREAD

**Issue by hackvice** [Valhalla-Gaming/Tracker#8532]
**Describe the issue you're having**:
heal a friendly target for 6-16% of the target's missing health.
**Explain how you expect it work**:
Calls down the Light to heal a friendly target for 30% of the target's missing health.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=213652/hand-of-the-protector

**Comment by Nightcap** [comment]
Hand of the Protector	Talent
Replaces Light of the Protector
40 yd range
Instant	10 sec recharge
1 Charges
Requires Paladin (Protection)
Requires level 75
Calls down the Light to heal a friendly target for 30% of the target's missing health.

Protection
While you are standing in your Consecration, Hand of the Protector's healing is increased by 20%

**Comment by Moustachos** [comment]
Works just fine.

**Comment by Moustachos** [comment]
Ref #5979
