### ISSUE TITLE
Paladin - Protection [Seraphim]

### ISSUE THREAD

**Issue by hackvice** [Valhalla-Gaming/Tracker#8533]
**Describe the issue you're having**:
Seraphim does not  Consume charges of Shield of the Righteous, and does not lasts 8 sec per charge.
**Explain how you expect it work**:
**Light temporarily magnifies your power, increasing your Haste, Critical Strike, Mastery, and Versatility by 5500.Consumes up to 2 charges of Shield of the Righteous, and lasts 8 sec per charge.**
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=152262/seraphim

**Comment by Moustachos** [comment]
Works just fine.

**Comment by Moustachos** [comment]
Ref #5979
