### ISSUE TITLE
Archeology Cannot solved (missing to solve)

### ISSUE THREAD

**Issue by BeyondSteaLikez** [Valhalla-Gaming/Tracker#8540]
**Describe the issue you're having**:
Open Archeology Go in craft tab See nightelf and old kingdom  Fragment's missing And theres no progress
**Explain how you expect it work**:
Open archeology Go in craft and you able to see progress and you can add keystones and etc,
**Steps to reproduce the problem**:

**Links to Wowhead, YouTube, etc**:
http://prntscr.com/dzq145

**Comment by BeyondSteaLikez** [comment]
Thanks

**Comment by Moustachos** [comment]
Will be fixed on next update.
