### ISSUE TITLE
Dungeons

### ISSUE THREAD

**Issue by braebrook** [Valhalla-Gaming/Tracker#8548]
**Describe the issue you're having**:
I am level 110 but cannot get into any regular dungeons.  It says on dungeon finder that "I am already locked to all instances".  I would think I would be able to run at least normal level dungeons.
**Explain how you expect it work**:
I would be able to queue for regular normal dungeons.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by 90isti90** [comment]
if u read forums  u see thet  the legion dungeons ar not opend yet  thay ar  in work for scripting

**Comment by Guybrush-VR** [comment]
90isti90 is right. We blocked all 110 dungeons for now and will open them one by one. Neltharion's Lair is coming soon, I'm working on it atm! :smile:
