### ISSUE TITLE
Player name Sungoddess Holy pala talent problem

### ISSUE THREAD

**Issue by Sungoddess26** [Valhalla-Gaming/Tracker#8549]
We tested 60 level talents ( auras ) with different holy paladin and his auras didin't goes off after joining bgs or arenas or enrage buffs. However my paladin '' sungoddess '' loses all the buff when i enter arenas or battlegrounds or using enrage buffs. Wtf ?

**Comment by Guybrush-VR** [comment]
Duplicates #8525
