### ISSUE TITLE
Fishing Areas In legion not working Correctly and as intended

### ISSUE THREAD

**Issue by BeyondSteaLikez** [Valhalla-Gaming/Tracker#8550]
**Describe the issue you're having**:
Went to Legion zone for Fishing and getting Old kingdom Fish (Plus this Occurs everywhere draenor/pandaria)
**Explain how you expect it work**:
Go to legion Area's Fish and get Legion areas fish.
**Steps to reproduce the problem**:

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/item=124107/cursed-queenfish             Azsuna
http://www.wowhead.com/item=124109/highmountain-salmon     Highmountain
http://www.wowhead.com/item=124108/mossgill-perch                  Val'sharah
http://www.wowhead.com/item=124110/stormray                          StormHeim
http://www.wowhead.com/item=124111/runescale-koi                    Suramar
http://www.wowhead.com/item=124112/black-barracuda             -The Great Sea	(open water around the broken isle)
http://www.wowhead.com/item=133607/silver-mackerel                   All above areas

http://prntscr.com/e09h1o

**Comment by forstix** [comment]
same with draenor, all i get is Raw Bristle Whisker Catfish over and over again and i level up there from 1-100 and no scroll drop  idk if i'm just unlucky as always...
