### ISSUE TITLE
Charred Warblades Weapon Artifact Talent (aldrachi warglaives)

### ISSUE THREAD

**Issue by garynewberg** [Valhalla-Gaming/Tracker#8552]
Charred Warblades doesnt work.

it should heal you for 15% of all Fire damage you deal.

**Steps to reproduce the problem**:

1. 
2. 
3. 
http://www.wowhead.com/spell=213010/charred-warblades

**Comment by Moustachos** [comment]
Works just fine.

**Comment by Moustachos** [comment]
Ref #5979
