### ISSUE TITLE
[Quests] Window not closing when accepting/turn in

### ISSUE THREAD

**Issue by phikaro** [Valhalla-Gaming/Tracker#8562]
**Describe the issue you're having**:
Ever since the legion expansion, some quests do not close their window when accepting them or completing them. for example Nature's Reprisal, does not close when I accept it, there's many  more like this quest around the world of the game. 
**Explain how you expect it work**:
It's supposed to close the window when accepting/completing the quest.
**Steps to reproduce the problem**:

1. Accept/complete the quest
2. Window will not close

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=13946/natures-reprisal

**Comment by Guybrush-VR** [comment]
This is a retail issue.
