### ISSUE TITLE
[Spells] Twice glitch

### ISSUE THREAD

**Issue by phikaro** [Valhalla-Gaming/Tracker#8563]
**Describe the issue you're having**:
When playing as a new character, and I level up, at level 5 and after when I receive new spell it appears doubled on the action bar. (Any class and race)
**Explain how you expect it work**:
The spell should not be doubled.
**Steps to reproduce the problem**:

1. Make a new character
2. level up till level 5
3. receiving double spells

**Comment by Analog-Valhalla** [comment]
Thank you for your report, but unfortunately its already reported. I'll close it now to prevent duplicates #5951

**Comment by phikaro** [comment]
Oh ok, didn't find it.
