### ISSUE TITLE
bug in load warrior

### ISSUE THREAD

**Issue by Pelete89** [Valhalla-Gaming/Tracker#8567]
**Describe the issue you're having**:

The ability to load the warrior sometimes fails to the first, and to the second works well
**Explain how you expect it work**:

Load has to work well regardless of uneven obstacles etc.
**Steps to reproduce the problem**:

1. 
The first attempt stays bug
2. 
The second attempt already works well
3. 

**Links to Wowhead, YouTube, etc**:
http://es.wowhead.com/spell=100/cargar

**Comment by Analog-Valhalla** [comment]
Thank you for your report, but unfortunately its already reported. I'll close it now to prevent duplicates #7588
