### ISSUE TITLE
LVL 100 BOOST 

### ISSUE THREAD

**Issue by Gotashado** [Valhalla-Gaming/Tracker#8571]
So , i boost my priest for 15$ and i was suppose to get mount , lvl 100 and 5k golds.

Lvl 100 was great to be , But - NO MOUNT AND NO 5K.

Please , try to fix that.

**Comment by forstix** [comment]
i think the shop need an update there is a forum post about how it should really works  
link - https://valhalla-realms.com/forum/viewtopic.php?f=41&t=8319

**Comment by Gotashado** [comment]
Alright that means you will give me the mount and the 5k I didnt get? I
dont understand that answer.

**Comment by GM-Pyromanic** [comment]
The text on the web store needs to be changed is all boosts from the store do not give you gold or a mount of your choosing anymore the system is exactly how retail has the boost system more info can be found in the link provided above.

**Comment by Gotashado** [comment]
Well , you should change it then.
Is not professtional to write something that you know you wont do.
Update or not , I paid 15$ because what I saw and what I suppose to get.

I still think I deserve that , It was wrriten and I guess its still what
makes others pay and get an Email " update suppose to be , you wont get
more - keep paying for NONE"

What ever ..
