### ISSUE TITLE
[Talents] MfD and MfS

### ISSUE THREAD

**Issue by Soze1** [Valhalla-Gaming/Tracker#8572]
Talents: 
Marked for Death and Master of Shadows doesn't work

MfD does not reset after killing an enemy within 1min

MfS doesn't grant 30 energy whenever  i enter Stealth or cast Shadow Dance

**Comment by forstix** [comment]
Marked of Death - https://github.com/Valhalla-Gaming/Tracker/issues/7778
Master of Shadows - https://github.com/Valhalla-Gaming/Tracker/issues/8046
both already reported.

**Comment by GM-Pyromanic** [comment]
Duplicate reports please check to make sure a issue has already not been created before making a new report. Also please report each issue in a report on their own so that when one issue is fixed the report can be closed and not left open while the other issues in the report are fixed also.
