### ISSUE TITLE
Rogue Talent (Subtlety): Death from Above

### ISSUE THREAD

**Issue by cyxyc** [Valhalla-Gaming/Tracker#8576]
Describe the issue you're having:
Only the first part of the talent works. You jump, deal first dmg, but thats all. You dont do the second part - eviscerate (increased by 50%) after landing. 
PS: this is different issue than the one which is reported in issue tracker. 
Explain how you expect it work:
jump, deal aoe dmg, land on the ground and cast boosted eviscerate
Links to Wowhead, YouTube, etc:
http://www.wowhead.com/spell=152150/death-from-above

**Comment by Analog-Valhalla** [comment]
Thank you for your report, but unfortunately its already reported. I'll close it now to prevent duplicates #8075
