### ISSUE TITLE
Death Knight

### ISSUE THREAD

**Issue by Gandoer** [Valhalla-Gaming/Tracker#8577]
**Describe the issue you're having**:
I can´t complete the Quest "Death Comes from On High
**Explain how you expect it work**:
You have abilitys in the eye
**Steps to reproduce the problem**:

1. create a Death Knight
2. go for the quest "Death comes from on high"
3. go into the eye and you have no abilitys

**Links to Wowhead, YouTube, etc**:
normally it should be this: https://www.youtube.com/watch?v=NFAUNWvgBzg

**Comment by forstix** [comment]
already reported https://github.com/Valhalla-Gaming/Tracker/issues/6501

**Comment by Analog-Valhalla** [comment]
Thank you for your report, but unfortunately its already reported. I'll close it now to prevent duplicates #6501
