### ISSUE TITLE
 [Ranger's Net] Hunter Survival

### ISSUE THREAD

**Issue by neano300** [Valhalla-Gaming/Tracker#8579]
**Describe the issue you're having**:
This spell can be spammeable to make an infinite CC.
**Explain how you expect it work**:
The root duration decrease in each net.
**Steps to reproduce the problem**:

1.  Learn it
2.  spam it
3.  

**Links to Wowhead, YouTube, etc**:
 WoW Head: http://www.wowhead.com/spell=200108/rangers-net 
Youtube: https://www.youtube.com/watch?v=UGqaZvOqhJM&feature=youtu.be

**Comment by Moustachos** [comment]
Will be fixed on next update.

**Comment by Moustachos** [comment]
Ref #5979
