### ISSUE TITLE
Demon Hunter Spell Darkness Bug

### ISSUE THREAD

**Issue by garynewberg** [Valhalla-Gaming/Tracker#8582]
The demon hunter darkness spell does not work properly.

It should summon a darkness around you a 8 second yd radius cloaking friendly targets and granting a 20% to avoid all damage from an attack. lasts 8 seconds.

It does not cloak friendlys or add an avoidance buff to them.

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Analog-Valhalla** [comment]
Can you provide a link to wowhead or the name of the spell please. :D

**Comment by Moustachos** [comment]
Works just fine.

**Comment by Moustachos** [comment]
Ref #5979
