### ISSUE TITLE
Demon Hunter Vengence Talent Razor Spikes

### ISSUE THREAD

**Issue by garynewberg** [Valhalla-Gaming/Tracker#8583]
If you get the razor spikes talent , it will work on the enemy but the debuff will also be applied to the caster

It does not affect the caster.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=209400/razor-spikes

**Comment by Analog-Valhalla** [comment]
Updated wowhead link into post. :D

**Comment by Moustachos** [comment]
Can't reproduce this issue.

**Comment by Moustachos** [comment]
Ref #5979
