### ISSUE TITLE
{Profession - Legion Mining} Ores are "lost" when collected

### ISSUE THREAD

**Issue by tomariuspelaez** [Valhalla-Gaming/Tracker#8589]
**Describe the issue you're having**:

When I use mining on a Leystone (Or another stone) in broken island, The mineral that should receive (In the first bag) disappears from my inventory, but in window of the work of jewelcrafting / mining says that I have it.

**Explain how you expect it work**:

After using mining on a stone I should receive and view the mineral in my inventory

**Steps to reproduce the problem**:

1. Use mining on a Leystone
2. The mineral that should receive (In the first bag)
3. Disappears

**Comment by forstix** [comment]
They're in your regant bank and this bug already reported somewhere

**Comment by forstix** [comment]
https://github.com/Valhalla-Gaming/Tracker/issues/7891

**Comment by Analog-Valhalla** [comment]
Thank you for your report, but unfortunately its already reported. I'll close it now to prevent duplicates #7891
