### ISSUE TITLE
Havoc Demon Hunter Honor Talent "Glimpse" Bug

### ISSUE THREAD

**Issue by garynewberg** [Valhalla-Gaming/Tracker#8592]
the demon hunter honor talent glimpse does not work properly, it does not apply blur for 3 seconds after using vengeful retreat.

you should automatically gain Blur for 3.0 sec after using Vengeful Retreat.

**Steps to reproduce the problem**:

1. 
2. 
3. 

http://www.wowhead.com/spell=203468/glimpse

**Comment by Analog-Valhalla** [comment]
Thank you for your report, but unfortunately its already reported. I'll close it now to prevent duplicates #7488
