### ISSUE TITLE
Havoc Demon Hunter Honor Talent "Rushing Vault" Bug

### ISSUE THREAD

**Issue by garynewberg** [Valhalla-Gaming/Tracker#8593]
the demon hunter honor talent rushing vault does not work properly, it should grant an additional fel rush after using vengeful retreat.

Vengeful Retreat should grant a charge of Fel Rush.

**Steps to reproduce the problem**:

1. 
2. 
3. 

http://www.wowhead.com/spell=205601/rushing-vault

**Comment by Analog-Valhalla** [comment]
Thank you for your report, but unfortunately its already reported. I'll close it now to prevent duplicates #7490
