### ISSUE TITLE
Demon Hunter Honor Talent "Reinforced Armor" Bug

### ISSUE THREAD

**Issue by garynewberg** [Valhalla-Gaming/Tracker#8594]
health is not increased by reinforced armor.

Health should be increased by 10%.

**Steps to reproduce the problem**:

1. 
2. 
3. 
http://www.wowhead.com/spell=195282/reinforced-armor

**Comment by Moustachos** [comment]
Works just fine, remember that Honor Talents are only enabled in PvP combat.

**Comment by Moustachos** [comment]
Ref #5979
