### ISSUE TITLE
Demon Hunter Honor Talent "Sparring" Bug 

### ISSUE THREAD

**Issue by garynewberg** [Valhalla-Gaming/Tracker#8595]
sparring does not make phyical melee attacks have a to be blunted, nor give the 50% reduced damage.

Physical melee attacks should have a 20% chance to be blunted, dealing 50% reduced damage.

**Steps to reproduce the problem**:

1. 
2. 
3. 
http://www.wowhead.com/spell=195425/sparring

**Comment by forstix** [comment]
same with Fdruid

**Comment by Moustachos** [comment]
Ref #5979
