### ISSUE TITLE
Havoc Demon Hunter Honor Talent "Rain from Above" Bug

### ISSUE THREAD

**Issue by garynewberg** [Valhalla-Gaming/Tracker#8596]
The talent semi works, it brings you into the air out of harms way, but would does very minimal damage (1-6) damage also the model for that form is only female even on my male night elf demon hunter.

Rain from Above's damage and model should be fixed.

**Steps to reproduce the problem**:

1. 
2. 
3. 
http://www.wowhead.com/spell=206803/rain-from-above

**Comment by Analog-Valhalla** [comment]
Thank you for your report, but unfortunately its already reported. I'll close it now to prevent duplicates #7491
