### ISSUE TITLE
Demon Hunter Talent "Fel Blade" Bug 

### ISSUE THREAD

**Issue by garynewberg** [Valhalla-Gaming/Tracker#8597]
fel blade does not work. you should charge to your target and deal damage.it does not do either.

you should charge to your target and deal 560% Fire damage.
and also
if  Vengeance 
Shear has a chance to reset the cooldown of Felblade.

if Havoc
Demon's Bite has a chance to reset the cooldown of Felblade.

**Steps to reproduce the problem**:

1. 
2. 
3. 
http://www.wowhead.com/spell=213241/felblade

**Comment by yebadal** [comment]
as i said we reported all of this bug and alot of more

BUT NO ONE CARE ABOUT DH MAN THIS MOTHERFUCKER ONLY KNOW HOW FIX PVE AND SOMETHING BULLSHIT LIKE BATTLE PET,,, SO?
I THINK FUCK THAT GO IN ANOTHER SERVER

**Comment by Analog-Valhalla** [comment]
Thank you for your report, but unfortunately its already reported. I'll close it now to prevent duplicates #7849
