### ISSUE TITLE
Demon Hunter Spell "Vengeful Retreat" Bug 

### ISSUE THREAD

**Issue by garynewberg** [Valhalla-Gaming/Tracker#8598]
vengeful retreat does not remove all snares when cast. the 3 second debuff seems to work.

 vengeful retreat should remove all snares and vault away.  nearby enemies should take 100% physical damage and have their movement speed reduced by 70% for 3 sec.

**Steps to reproduce the problem**:

1. i tried to cast it while entangled by druid roots.(not removed)
2. i tried to cast while slowed by a mage. (not removed)
3. 

http://www.wowhead.com/spell=198793/vengeful-retreat

**Comment by Moustachos** [comment]
Vengeful Retreat is meant to remove **snares**, not root effects (and it works just fine).

For example, it _can_ remove Warrior's Hamstring, but it _can't_ remove Druid's Entangling Roots.

**Comment by Moustachos** [comment]
Ref #5979
