### ISSUE TITLE
Vengence Demon Hunter Artifact Talent "Siphon Power"(aldrachi warblades)

### ISSUE THREAD

**Issue by garynewberg** [Valhalla-Gaming/Tracker#8599]
the demon hunter artifact talent siphon power does not work.

it should when you empower wards increase your agility by 15% for 10 sec, based on magic damage you take while it is active.

**Steps to reproduce the problem**:

1. 
2. 
3. 

http://www.wowhead.com/spell=218910/siphon-power

**Comment by yebadal** [comment]
dude who's fucking care about dh?

stop playing here its not worthy to playe include with dh veng

**Comment by Analog-Valhalla** [comment]
Thank you for your report, but unfortunately its already reported. I'll close it now to prevent duplicates #7098
