### ISSUE TITLE
Demon Hunter disconnection issues

### ISSUE THREAD

**Issue by garynewberg** [Valhalla-Gaming/Tracker#8600]
Whenever demon hunters do things outside of the anti cheat systems parameters they get kicked.

I would like the anti cheat modified so demon hunters do not get kicked whenever they fel rush, glide or double jump in a quick succession or combination.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Analog-Valhalla** [comment]
Thank you for your report, but unfortunately its already reported. I'll close it now to prevent duplicates #7393
