### ISSUE TITLE
Redridge Mountains: [Tuning The Gnomecorder] Quest

### ISSUE THREAD

**Issue by Hemabody** [Valhalla-Gaming/Tracker#8603]
In this quest, all I am supposed to do is stand at the graveyard outside Lakeshire then the quest will be automatically completed and I get another quest immediately, unfortunately nothing happens when I do that. The bigger problem here is that I can't do any later quest unless I finish this one, so questing further in redridge is impossible. More details in the links below:

Wowhead: www.wowhead.com/quest=26512/tuning-the-gnomecorder

Youtube: https://www.youtube.com/watch?v=jG6yZWX8KOU

**Comment by Analog-Valhalla** [comment]
Thank you for your report, but unfortunately its already reported. I'll close it now to prevent duplicates #8084
