### ISSUE TITLE
Logged in and all gold is gone

### ISSUE THREAD

**Issue by braebrook** [Valhalla-Gaming/Tracker#8604]
**Describe the issue you're having**:
I just loggged in this morning and all my gold is gone.  I had around 140,000 on my character and it was down to 0 copper.  I don't know what happen, I just played on Sunday.
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by braebrook** [comment]
Just checked and it's like that for all characters

**Comment by braebrook** [comment]
Is there something that can be done, I'm not sure why everything is gone.  I just played on Sunday around 3pm USA time or is there a log that someone can check.

**Comment by GM-Pyromanic** [comment]
PM [Doriathrim](https://valhalla-realms.com/forum/memberlist.php?mode=viewprofile&u=99421) on the forums he will be able to explain to you what happened.
