### ISSUE TITLE
Incompatible on Asgard

### ISSUE THREAD

**Issue by habagatamihan** [Valhalla-Gaming/Tracker#8610]
**Describe the issue you're having**: Unable to login to Realm, says incompatible.

![error](https://cloud.githubusercontent.com/assets/17206201/22477977/10de98de-e823-11e6-8840-a7a042f01912.jpg)

**Comment by BeyondSteaLikez** [comment]
Have you updated the client to 7.1.5? Please read forums for more info!

**Comment by habagatamihan** [comment]
I was downloading the updated client while trying to login, then I read the forum!! ALL GOOD NOW. 废话！！
