### ISSUE TITLE
Arcane Mage Talent: "Quickening"

### ISSUE THREAD

**Issue by Lhyron** [Valhalla-Gaming/Tracker#8616]
**Describe the issue you're having**:
Quickening procs for every damage dealt.

**Explain how you expect it work**:
Quickening has disappeared from mage talents in 7.1.5.

**Steps to reproduce the problem**:

1. Deal damage in Arcane spec
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=198923/quickening

**Comment by Guybrush-VR** [comment]
Quickening has been replaced with Temporal Flux and should not be available to player anymore.

**Comment by Moustachos** [comment]
Ref #5979
