### ISSUE TITLE
Arcane Mage Talent: "Overpowered"

### ISSUE THREAD

**Issue by Lhyron** [Valhalla-Gaming/Tracker#8617]
**Describe the issue you're having**:
In addition to increase damages dealt and reduce the cost of mana, casting arcane missiles extend the duration of Arcane Power.

**Explain how you expect it work**:
Arcane Power should only increase damage dealt and reduce the cost of mana. The extension of the duration of Arcane Power when casting Arcane missiles has disappeared in 7.1.5.

**Steps to reproduce the problem**:

1. Select talent Overpowered
2. Cast Arcane Power
3. Cast Arcane missiles

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=155147/overpowered

**Comment by Lhyron** [comment]
**EDIT: It's a gamebreaking issue as it provides 70% increased damage forever if well used.**

**Comment by alucula** [comment]
quote

**Comment by Moustachos** [comment]
Ref #5979
