### ISSUE TITLE
Sephuz's Secret

### ISSUE THREAD

**Issue by Traveler-Valhalla** [Valhalla-Gaming/Tracker#8619]
**Describe the issue you're having**:
issue #8148 is back. ring procs all the time and in pvp.
**Explain how you expect it work**:
shouldnt proc all the time and shouldnt proc is pvp
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/item=132452/sephuzs-secret
https://github.com/Valhalla-Gaming/Tracker/issues/8148

**Comment by prideoverall** [comment]
this completely ruins pvp as the players with the item appears to be teleporting all over the place, thus untargetable by melee attacks.

**Comment by Moustachos** [comment]
Will be fixed on next update.
