### ISSUE TITLE
Can't post to auction house or sell to vendors

### ISSUE THREAD

**Issue by braebrook** [Valhalla-Gaming/Tracker#8622]
**Describe the issue you're having**:
I cannot post anything to auction and I cannot sell items to vendors in Stormwind.  This seemed to work before the update.
**Explain how you expect it work**:
Before the 7.1.5 update I was able to sell to vendors and post to auction house.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Valhalla-Gaming** [comment]
We confirm, the auction house is broken since the update. We're working on it now. However, vendors are working fine on our end. Allow your client to patch fully, run a repair or delete your cache to resolve that issue.
