### ISSUE TITLE
[ Human Zones ] NPCs say Greetings

### ISSUE THREAD

**Issue by phikaro** [Valhalla-Gaming/Tracker#8625]
**Describe the issue you're having**:
After the new 7.1.5 patch, all the npcs in Human zones say Greetings "Name", and the guards in Stormwind lost their gossip for locations, they only say greetings "name".
**Explain how you expect it work**:
NPCs should be having the proper retail text when talking to them.
**Steps to reproduce the problem**:

1. Got to any human zone like Stormwind, Elwynn Forest, Northshire etc...
2. Talk to npcs
3. They only say greetings "name"

**Comment by Valhalla-Gaming** [comment]
We are not able to reproduce this issue. All npcs which had working gossips, are still working after the 7.1.5 upgrade. Please make sure that you're client is up to date. You could also try deleting your cache.

![Gossip](http://image.prntscr.com/image/185996fcb4ca407f83d7d69a4de02e01.png "Optional title")
![Gossip](http://image.prntscr.com/image/a93eb27adebf4c0a842a9e78d3f65233.png "Optional title")

**Comment by phikaro** [comment]
Well in Stormwind got fixed when I deleted cache folder, but in Elwynn Forest and Northshire npcs still say greetings "Name".

[](http://store.picbg.net/pubpic/75/36/09ee48be31d77536.jpg)

[](http://store.picbg.net/pubpic/D2/10/c8d772b1b237d210.jpg)
