### ISSUE TITLE
Rupture Rogue 

### ISSUE THREAD

**Issue by neano300** [Valhalla-Gaming/Tracker#8627]
**Describe the issue you're having**:
Sometimes (80%) of the times the rupture hits 700-800k.
**Explain how you expect it work**:
This spell can't do 800k because is a dot.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=1943/rupture
Photo: http://imgur.com/a/MJKT6

**Comment by cyxyc** [comment]
well mine does only 200k. those numbers are from your wet dreams

**Comment by cyxyc** [comment]
but yeah lol its almost like half of a shield slam. lets ban all rogues for this. lets make sure theres nothing to kill mr. osmons in bg so he can feel like a man

**Comment by prideoverall** [comment]
rupture dmg is not bugged.
I did this dmg with this because i used these dmg modifiers:
battleground berserker buff 30%
blood of the assassinated 100%
blood fury 
trinket proc
Hemorrhage 25%
vendetta 30%
gushing wounds 6%
tricks of the trade
prey on the weak 15%

if anything is bugged, its hemo or blood fury

**Comment by Focuslow** [comment]
Stupid kid osmons doesn't even know how keybinds and macros work worst player in game using all possible abusable bugs at the same time just to be "best" cry more kiddo bcs one rogue killed you wow you must have sad life that you gotta abuse all warrior bugs also trinket with no ICD and ring with 70% mov speed and 20%haste with no ICD as well you better get banned or smt for being idiotic creature like that.

**Comment by Maldazar-Valhalla** [comment]
Legit damage, same as your Shield Slam.

**Comment by Guybrush-VR** [comment]
Gents, let's keep this civilized, shall we?

**Comment by Uncool1** [comment]
No xD

**Comment by Analog-Valhalla** [comment]
This issue occurs when combinding a talent thats allows more combo points to deal more damage. The numbers go from 200k over a few second (5 combo points) to hitting 700k-800k almost every tic (6-7 combo points).

**Comment by Moustachos** [comment]
Ref #5979
