### ISSUE TITLE
Warlock bug

### ISSUE THREAD

**Issue by Holybeams** [Valhalla-Gaming/Tracker#8629]
**Describe the issue you're having**:
The cause was combining conflagration immolate and incinerate seems to cause warlocks trouble. Combination of this seems to cause warlocks to not be able to cast spells again. (Others may cause it too)
**Explain how you expect it work**:
Any combo should be able to make warlocks cast spells
**Steps to reproduce the problem**:

1. For now people should not use this combo
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Moustachos** [comment]
Will be fixed on next update.

**Comment by Moustachos** [comment]
Ref #5979
