### ISSUE TITLE
 Quickening Mage Arcane

### ISSUE THREAD

**Issue by neano300** [Valhalla-Gaming/Tracker#8645]
**Describe the issue you're having**:
This pasive increase the buff in every spell the mage use increasing his haste lots.
**Explain how you expect it work**:
Arcane Blast and Arcane Explosion grant 5% Haste and increase the mana cost of your spells by 3% for ## 10 sec.
This effect stacks, and is cleared when you cast Arcane Barrage.

Spam any spell and the passive will appear.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=198923/quickening#changelog
Photo: http://imgur.com/a/5Gr5w

**Comment by Analog-Valhalla** [comment]
Duplicate post #8616
