### ISSUE TITLE
Death Knight / Blood / Blooddrinker 

### ISSUE THREAD

**Issue by prideoverall** [Valhalla-Gaming/Tracker#8647]
**Describe the issue you're having**:
Deals too much damage (over 1 million in pvp without any burst cd)
**Explain how you expect it work**:
Drains 0 health from the target over 3 sec.

You can move, parry, dodge, and use defensive abilities while channeling this ability.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=206931/blooddrinker

**Comment by Aival94** [comment]
Test the damage again if it do 3000% of Strenght you have as Wowhead have totally wrong description. Furthermore some are complaining about its huge damage on Blizzard forums so i believe the damage is not 0. https://eu.battle.net/forums/en/wow/topic/17614692343?page=1

[Blooddrinker](http://wow.gamepedia.com/Blooddrinker)

**Comment by Analog-Valhalla** [comment]
Blooddrinker is supposed to steal health from the target to heal the caster. Works as intended. Thank you for your report. :D

[url=http://imgur.com/PPJitku][img]http://i.imgur.com/PPJitku.jpg[/img][/url]
