### ISSUE TITLE
Auction house

### ISSUE THREAD

**Issue by PortRoyale153** [Valhalla-Gaming/Tracker#8650]
Issue : after the 7.1.5 update auction house just dont work for me when i try to sell something there it just do the sound and dont give the items there (i hope its not just me ) 

**Steps to reproduce the problem**:

1. go to auction house
2. try to sell there item

Edit : and also i think other ppl have this problem too cuz ive dont seen there a single item

**Comment by braebrook** [comment]
I put in a ticket for this a couple of days ago, they said they are working on it and confirmed the auction house is broke.

**Comment by Moustachos** [comment]
Will be fixed on next update, that's why I closed the previous issue.
