### ISSUE TITLE
PvP Trinkets.

### ISSUE THREAD

**Issue by neano300** [Valhalla-Gaming/Tracker#8652]
**Describe the issue you're having**:
The pvp trinkets can't be used in Arenas/ Battlegrounds
**Explain how you expect it work**:
The pvp items can be usable in Arenas/battlegrounds
**Steps to reproduce the problem**:

**Links to Wowhead, YouTube, etc**:
http://imgur.com/a/042lw

**Comment by Moustachos** [comment]
No trinkets are supposed to be usable in BG, see https://www.reddit.com/r/wow/comments/513jry/pvp_trinkets_not_usable_in_battlegrounds/
