### ISSUE TITLE
Mage Quickening

### ISSUE THREAD

**Issue by Kezeal** [Valhalla-Gaming/Tracker#8654]
**Describe the issue you're having**:
Quickening is gone.
**Explain how you expect it work**:
In 7.1.5 quickening should be an arcane mage passive.
**Steps to reproduce the problem**:

1. Use Arcane Missile or Arcane Explosion
2. See no quickening

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=198923/quickening#changelog

**Comment by Moustachos** [comment]
This talent was removed in 7.1.5 and replaced by Temporal Flux, see http://wow.gamepedia.com/Quickening
