### ISSUE TITLE
Outlaw Rogue Bugs

### ISSUE THREAD

**Issue by MagvinCZ** [Valhalla-Gaming/Tracker#8676]
**Mastery:Main Gauche** 
       Procs from ALL attacks, It should proc just from meele main-hand attacks

**Between the Eyes** 
       Stun from this spell isn´t lowered when used multiple times in row

**Death From Above (talent)** 
       Deals initial damage, but has no animation and the attack isnt followed by Run Trough

**Cannonball Barrage (talent)**
        Has bugged hitbox or something like that.... in some situations it just doesnt hit enemies even when            they stay in it

**Cheap Tricks (honor talent)**
        Procs from normal Pistol Shots and the effect isn´t consumed on cast

**Blunderbuss (artifact trait)**
         Doesn´t work

**Turn the Tables (honor talent)**
         Doesn´t work

**Take Your Cut (honor talent)**
         Doesn´t work

**Comment by Analog-Valhalla** [comment]
I appreciate the report. Can you report these individually. Thank you :)

**Comment by Moustachos** [comment]
Between the Eyes's issue will be fixed on next update.

Turn the Tables works just fine.

For the other issues, please report them individually.
