### ISSUE TITLE
 [Hit Combo]

### ISSUE THREAD

**Issue by neano300** [Valhalla-Gaming/Tracker#8677]
**Describe the issue you're having**:
When use Palm of tiger reset the combos.
**Explain how you expect it work**:
Each successive attack that triggers Combo Strikes in a row grants 2% increased damage, stacking up to 8 times
**Steps to reproduce the problem**:

1.  Do a normal rotation to stack this buff 
2.  only can be stackable 3 times because you can't generate more chi because when use Palm of tiger restart it all.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=196740/hit-combo

**Comment by Uncool1** [comment]
u felt abused? :D

**Comment by Analog-Valhalla** [comment]
Duplicate report #7528
