### ISSUE TITLE
Parry BUG Palladins

### ISSUE THREAD

**Issue by MscleMike** [Valhalla-Gaming/Tracker#8689]
**Describe the issue you're having**:
When dueling in arena with Paladins (i am a Rogue subtelty) I keep getting insanely parries from him without him having any buffs or shields
**Explain how you expect it work**:
I am sure that this is not normal...
**Steps to reproduce the problem**:

**Comment by avaksx** [comment]
Also parries stuns not only melee damage.

**Comment by Hemoglobine-Valhalla** [comment]
this also happens to warlocks, warriors, dks, monks, almost every class, thing is they shouldn't parry stuns, not evade them, just in case of immunity to stun then yes, but not in any other kind of case, also same happens with charge or intercept as warrior, you can fail it and you shouldn't, hope this get fixed fast.

**Comment by yebadal** [comment]
they can even block spells

**Comment by yebadal** [comment]
even block stuns

**Comment by Moustachos** [comment]
Ref #5979
