### ISSUE TITLE
Six-Feather Fan passive bug

### ISSUE THREAD

**Issue by Eastwud** [Valhalla-Gaming/Tracker#8692]
**Describe the issue you're having**:
The trinked Six-Feather Fan has a passive it has a chance to strike a target with 6 wind bolts for X amount of nature damage and slow them. The problem is, the passive also applies to me as well(the slow and also 6*X nature damage).

**Explain how you expect it work**:
The passive should only apply to my target(s), not me.

**Steps to reproduce the problem**:
1. Equip Six-Feather Fan
2. Shoot mobs
3. Look at your debuffs

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/item=141585/six-feather-fan

**Comment by Analog-Valhalla** [comment]
Duplicate report #7823
