### ISSUE TITLE
Sephuzs Secret procs all the time still

### ISSUE THREAD

**Issue by Analog-Valhalla** [Valhalla-Gaming/Tracker#8695]
**Describe the issue you're having**:
This was fixed in pvp but not in the world. it still can proc forever.
**Explain how you expect it work**:
Should have a cooldown on the proccing.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/item=132452/sephuzs-secret

**Comment by Moustachos** [comment]
There is a 30 seconds CD on the proc and it works as intended.
