### ISSUE TITLE
Double Jump + Glide

### ISSUE THREAD

**Issue by Lhyron** [Valhalla-Gaming/Tracker#8703]
**Describe the issue you're having**:
The combo double jump + glide always cause a disconnection.

**Explain how you expect it work**:
It should work without disconneting

**Steps to reproduce the problem**:

1. Double Jump
2. Glide
3. Dc

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=131347/glide
http://www.wowhead.com/spell=196055/double-jump

**Comment by Traveler-Valhalla** [comment]
no dc for me

**Comment by Lhyron** [comment]
I close this since I doesn't happen anymore.
