### ISSUE TITLE
Fire Mage Passive: "Hot Streak"

### ISSUE THREAD

**Issue by Lhyron** [Valhalla-Gaming/Tracker#8707]
**Describe the issue you're having**:
The effect doesn't consume itself after one use. Flamestrike/Pyroblast are instant and can be spammed **for the whole duration of the effect**.

**Explain how you expect it work**:
Hot Streak should only grant **1** Flamestrike/Pyroblast to be cast instant. The effect should be consumed after one use.

**Steps to reproduce the problem**:

1. Deal 2 consecutive critical strikes
2. Get Hot Streak
3. Spam instant Flamestrike & Pyroblast

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=48108/hot-streak

**Comment by Moustachos** [comment]
Ref #5979

**Comment by Analog-Valhalla** [comment]
Occurs with Flamestrike, either that Flamestrike procs off of its self.

**Comment by Moustachos** [comment]
Ref #5979
