### ISSUE TITLE
warlock chaos bolt

### ISSUE THREAD

**Issue by yebadal** [Valhalla-Gaming/Tracker#8712]
**Describe the issue you're having**:
probelm is: when you cast a chaos bolt its hit the target for 2 time (2000k) not one time and its damage must be less you cant reduced it damage even with anti spell damage done or every thing
**Explain how you expect it work**:
must be 500kor600k in pve and in pvp 300or400 not 1000k or 2000k or 1456k 
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://imgur.com/a/r5cg3

**Comment by Analog-Valhalla** [comment]
This issue occurs from Backdraft. Will be fixed nexted update. :D Duplicate post #8793
