### ISSUE TITLE
Outlaw Rogue Spell [Mastery:Main Gauche]

### ISSUE THREAD

**Issue by MagvinCZ** [Valhalla-Gaming/Tracker#8713]
Procs from all main-hand attacks ( ranged aswell )

It should proc only from meele main-hand attacks

http://www.wowhead.com/spell=76806/mastery-main-gauche

**Comment by Lhyron** [comment]
[8405](https://github.com/Valhalla-Gaming/Tracker/issues/8405)

**Comment by Analog-Valhalla** [comment]
Duplicate post #8405
