### ISSUE TITLE
Outlaw Rogue Artifact Trait [Blunderbuss]

### ISSUE THREAD

**Issue by MagvinCZ** [Valhalla-Gaming/Tracker#8715]
It never procs

When Saber Slash strikes an aditional time, it has 33% chance to replace Pistol Shot with Blunderbuss ( deals way more damage and slow )

http://www.wowhead.com/spell=202897/blunderbuss

**Comment by Lhyron** [comment]
[8069](https://github.com/Valhalla-Gaming/Tracker/issues/8069)

**Comment by Analog-Valhalla** [comment]
Duplicate post #8069
