### ISSUE TITLE
Mastery: Hunting Companion 

### ISSUE THREAD

**Issue by Keilik** [Valhalla-Gaming/Tracker#8735]
Survival Hunter
Mastery: Hunting Companion dont work 

hunter pet nee to have 
*chance to grant you an additional charge of Mongoose Bite

1. 
2. 
3. 
http://www.wowhead.com/spell=191334/mastery-hunting-companion

**Comment by Proklet** [comment]
In the last three months that I had this mastery available on my hunter, I paid great attention, but I failed to notice it even once working. I never got any additional charges of Mongoose Bite.

**Comment by Traveler-Valhalla** [comment]
#7255 reported already

**Comment by Analog-Valhalla** [comment]
Duplicate #7255
