### ISSUE TITLE
Dungeon Bosses Mythic.

### ISSUE THREAD

**Issue by neano300** [Valhalla-Gaming/Tracker#8741]
**Describe the issue you're having**:
The dungeon bosses can be Silenced by spells like normal mobs  same thng with stuns. On mythics.
**Explain how you expect it work**:
A boss can't be stunned or silenced by normal spells.
**Steps to reproduce the problem**:

1.  wait for casting any spell
2.  silence him or stun

**Comment by Guybrush-VR** [comment]
Oops!

**Comment by Guybrush-VR** [comment]
Fixed, should be live soon. Thanks for the report, I forgot to make them immune in heroic/mythic!
