### ISSUE TITLE
Npc Patricia Egan <Alchemy Supplies> and item bug -->forgotten-formulas-of-the-broken-isles

### ISSUE THREAD

**Issue by MyJ3** [Valhalla-Gaming/Tracker#8744]
**Describe the issue you're having**:
Este npc no vende ninguna de las recetas que debería vender, unicamente vende los frascis de cristal y el libro que no funciona correctamente.
This npc does not sell any of the recipes that should sell, only sells the glass frascis and the book that does not work properly.
**Explain how you expect it work**:
Este npc debería vender las recetas de alquimia de legión y el libro debería volver a enseñarte todo loq ue tenías aprendido si has olvidado la profesión.
This npc should sell legion alchemy recipes and the book should re-teach you everything that you had learned if you have forgotten the profession.
**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/npc=92457/patricia-egan
http://www.wowhead.com/item=139492/forgotten-formulas-of-the-broken-isles

**Comment by GM-Pyromanic** [comment]
Recipes are unlocked via quest chains which will be added at a later date.

**Comment by MyJ3** [comment]
@GM-Pyromanic If the recipes go for missions as is that alchemy is the only profession, (removing the secondary) have legion recipes up to level 2 and people can learn them and create those objects?

**Comment by Guybrush-VR** [comment]
I'm going to work on professions after dungeons/raids. Don't worry, it'll soon be fixed! :smile:

**Comment by MyJ3** [comment]
@Guybrush-VR I know that they will be fixed when all the mazmoras are repaired but right now all the first professions except alchemy have the recipes of up to level 2 so you can do legume stuff and you can do things, but alchemy is the only one that your salesman does not sell Recipes so you have to go to wod expansion and farm there. My report is more than anything is in case you can put the recipes to not be changing so much of expansion thing that it becomes something unpleasant in everything that is done in the area of ​​legion. 

Se que seran arregladas cuando todas las mazmoras esten reparadas pero ahora mismo todas las profesiones primerias excepto alquimia tienen las recetas de hasta nivel 2 por lo que se pueden farmear cosas de legio y puedes hacer cosas, pero alquimia es la unica que su vendedor no vende recetas por lo que hay que ir a la expansion de wod y farmear alli. Mi report es mas que nada es por si podeis poner las recetas para no estar cambiando tanto de expansion cosa que se hace algo desagradable estanto todo lo que se hace en la zona de legion.
