### ISSUE TITLE
Broken Isles Start Quest Bug

### ISSUE THREAD

**Issue by Vossie20** [Valhalla-Gaming/Tracker#8746]
**Describe the issue you're having**:
Good day, My two characters both got the same problem. On level 98 the quest for the Broken Isles came up but it did not allowed me to accept it. I was in the middle of getting attacked when it pop up. I had to close it. Now I can't get it back. How can I get to the Broken Isles now?
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Guybrush-VR** [comment]
Only Highmountain is scripted so far. You need to pick up the first quest in your Class Halls (name should be "The Lone Mountain").

**Comment by Vossie20** [comment]
I'm sorry, this does not help me. I'm not Alliance so I can't get that quest. Where can I go for Horde Warrior  to get to the Broken Isle?

**Comment by Guybrush-VR** [comment]
You need to go to Orgrimmar, there is an NPC here called "Marius Felbane". He'll give you your artifact and port you to the New Dalaran. From here, you need to move towards Krasus' Landing, to the glowing area. You'll have to click on the spell and you'll be ported to your Class Halls. After that, pick up the first quest of Highmountain to your Scouting Map (Should look like a globe or something for warriors).
Note: This is for warrior, if you have another classes, you need to go to their respective class halls.

**Comment by Vossie20** [comment]
Thanks for all your hard work.

**Comment by Guybrush-VR** [comment]
Thanks man, glad it helped. :smile:
