### ISSUE TITLE
PvP Templates - Item Level Scaling

### ISSUE THREAD

**Issue by avaksx** [Valhalla-Gaming/Tracker#8749]
**Describe the issue you're having**: PvP Template Item Level scaling isn't working.

**Explain how you expect it work**: For each level range, there is an optimal PvP item level (ie: 800 for level 110), every average item level above this value will grant +0.1% to these stats (ie: a 850 average item level will provide +5% to all stats)
**Steps to reproduce the problem**:

1. Enter PVP Area with different ilvl's and see you have same stats on both ilvl's.
2. Look at the pictures.

![1](https://cloud.githubusercontent.com/assets/22096253/22664623/c2acca9e-ecb1-11e6-9807-f7d7431c7b28.jpg)
![2](https://cloud.githubusercontent.com/assets/22096253/22664625/c33af8a0-ecb1-11e6-836c-02276aafa9a1.jpg)

**Comment by Moustachos** [comment]
Not a bug (according to your screenshots), you see the same values due to rounding.

837 ilvl would give 3.7%, 841 would give 4.1%, both are rounded to 4%, hence the identical stats.

**Comment by avaksx** [comment]
@Moustachos Okay, I just tested it out in arenas with all kinds of different item levels and I can say that it is rounding just like you said, 815 = 2% ; 825 = 3% ; 835 = 4% 

I tought it will scale on each **ilvl for 0,1% stats increase** just like it was on the PvP Template post.

I apologize for misunderstood issue.
