### ISSUE TITLE
G'Hanir, the Mother Tree - Druid Artifact

### ISSUE THREAD

**Issue by avaksx** [Valhalla-Gaming/Tracker#8750]
**Describe the issue you're having**: G'Hanir, the Mother Tree (Druid Artifact) Has stopped working after recent updates. It literaly doesn't do anything except it goes on cooldown.
Even if the buff says heals every "2.6 sec" and after I use spell it says "1.3 sec"( it still does every 2.6)
Measured with in-game stopwatch- might not not be 0.01 exact but I can tell the different between 1,3 and 2.6.

**Explain how you expect it work**:
"Grants the Essence of G'Hanir ability, which greatly increases the effects of your other healing spells."

Which means it should increase the frequency that all my healing over time spells effects heal 100% faster in next 8 seconds.

**Steps to reproduce the problem**:

1. Make Restoration Druid
2. Put some HoT's up.
3. Use Artifact spell.
4. Start stopwatch and measure time.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/item=128306/ghanir-the-mother-tree&bonus=0

**Comment by 90isti90** [comment]
this spel newer workd since  legion came,and its one of the  importand druid spels ,the artifact for others  workd ,but thay forgot  to fix it for resto

**Comment by Moustachos** [comment]
Ref #5979
