### ISSUE TITLE
Restoration Druid UI Frame - Efflorescence Indicator

### ISSUE THREAD

**Issue by avaksx** [Valhalla-Gaming/Tracker#8752]
**Describe the issue you're having**: Efflorescence spell isn't showing up at character frame which will indicate the remaining time or Efflorescence spell.

**Explain how you expect it work**: Show up little icon with timer. -picture below.
This is pretty usefull because as a druid I never know when will my efflorescence expire. 
**Steps to reproduce the problem**:

1. Make restoration druid.
2. Use Efflorescence.
3. See that indicator is not there.

**Links to Wowhead, YouTube, etc**: 
![2](https://cloud.githubusercontent.com/assets/22096253/22666476/fa5d60c8-ecb8-11e6-97a6-abe4cfbc4b1b.jpg)
 http://www.wowhead.com/spell=145205/efflorescence

**Comment by 90isti90** [comment]
yes  that is a problem ,i had to make a weak aura  to be abel to folow its  time up

**Comment by Moustachos** [comment]
Ref #5979
