### ISSUE TITLE
Outlaw Rogue Spell [Between The Eyes]

### ISSUE THREAD

**Issue by MagvinCZ** [Valhalla-Gaming/Tracker#8753]
After last update, this spell doesn´t give stun..... :/ Also critical strikes aren´t multiplied ( it should deal 4x more damage on crit )

http://www.wowhead.com/spell=199804/between-the-eyes

**Comment by Moustachos** [comment]
The increased critical strike damage part works just fine.

The stun part will be fixed (for good) on next update.
