### ISSUE TITLE
[Talent][Paladin] Divine Purpose

### ISSUE THREAD

**Issue by Lebiedz** [Valhalla-Gaming/Tracker#8755]
**Describe the issue you're having**: Divine Purpose does not work as intended. I've picked this talent at lvl 100, raised my lvl to 104 now and had 0 procs from it so far. I know there is already an issue (#6008) on the tracker about it, but it states that the problem is the opposite and may be out of date.

**Explain how you expect it work**: This talent should provide me with 20% chance that my Holy Power spenders (e.g. Templar's Verdict, Divine Storm) make my next Holy Power spender free.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=223817/divine-purpose
http://www.wowhead.com/spell=85256/templars-verdict

**Comment by Moustachos** [comment]
Works fine.
