### ISSUE TITLE
[Talent][Paladin] Fist of Justice

### ISSUE THREAD

**Issue by Lebiedz** [Valhalla-Gaming/Tracker#8756]
**Describe the issue you're having**: Talent does not work as intended. Holy power spenders don't reduce cooldown on Hammer of Justice. Previous posts about this issue are out of date, since this spell changed in current patch - 7.1.5

**Explain how you expect it work**: With this talent chosen, each holy power spent should reduce remaining (and existing) cooldown on Hammer of Justice

**Steps to reproduce the problem**:

1. Take Fist of Justice talent
2. Use Hammer of Justice
3. Generate some Holy Power and spend it.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=234299/fist-of-justice
http://www.wowhead.com/spell=853/hammer-of-justice

**Comment by Zealotry** [comment]
Nothing on this?

**Comment by Lebiedz** [comment]
I kinda wonder if it makes any sense to post these reports, since they get out of date (by Blizzard messing with skills in patches and Valhalla implementing them) quicker than they get fixed... Maybe we should just wait for the final Legion patch and then start fixing the spells? Because they will get broken after every patch.

**Comment by Moustachos** [comment]
Ref #5979
