### ISSUE TITLE
Paladin missing spell [Blessing of Might]

### ISSUE THREAD

**Issue by pekacmarko** [Valhalla-Gaming/Tracker#8757]
Missing spell I can not click.
is not in spellbook.
http://wowwiki.wikia.com/wiki/Blessing_of_Might

**Comment by Lebiedz** [comment]
It was removed in patch 7.1.5

**Comment by Zealotry** [comment]
https://us.battle.net/forums/en/wow/topic/20752576418 

It was removed indeed, but Ret Paladins should 12% increase in damage. In Valhalla, I don't feel it's the case. I urge developers to correct that if possible.

Thanks.

**Comment by Zealotry** [comment]
Should have*

**Comment by Moustachos** [comment]
The 12% damage buff is live on Valhalla.

**Comment by Zealotry** [comment]
To be honnest, Moustachos I really don't feel that my dps has had so much buff. Not that I am doubting your word, would it be too much to ask to verify that? Thank You.
