### ISSUE TITLE
Shadowy Inspiration

### ISSUE THREAD

**Issue by Keilik** [Valhalla-Gaming/Tracker#8758]
Shadowy Inspiration demonology warlock talant 

it need to make  the next shadow bolt demonbolt instant cast but now  the buff is not consume and you can cast non stop instant cast shadow bolts 

1. 
2. 
3. 

http://www.wowhead.com/spell=196269/shadowy-inspiration

**Comment by Analog-Valhalla** [comment]
Duplicate post #8497
