### ISSUE TITLE
Nergal doesn't sell Devilsaur Patterns

### ISSUE THREAD

**Issue by Reloque** [Valhalla-Gaming/Tracker#876]
General Goods vendor [Nergal](http://www.wowhead.com/npc=12959)(12959) at Marshal's Stand, Un'Goro Crater does not sell his world-famous limited-supply Devilsaur Armor patterns. Both should have a stock of 1 and a respawn timer somewhere between a half hour and three hours.

[Pattern: Devilsaur Leggings](http://www.wowhead.com/item=15772)(15772) for 3 gold. Also available as an extremely rare drop from slimes in the region.
[Pattern: Devilsaur Gauntlets](http://www.wowhead.com/item=15758)(15758) for 2 gold 20 silver. Not available from anywhere except Nergal.

Note that the [Devilsaur Armor](http://www.wowhead.com/itemset=143)(143) set is a formal set consisting of these two items, with a set bonus `+20 critical strike`.

**Comment by Tregeta** [comment]
fixed
