### ISSUE TITLE
Personal Loot.

### ISSUE THREAD

**Issue by neano300** [Valhalla-Gaming/Tracker#8763]
**Describe the issue you're having**:
Sometimes the personal loot give you items what do you dont need.
**Explain how you expect it work**:
Only give items of your spec or class.

**Links to Wowhead, YouTube, etc**:
Photo: http://imgur.com/a/h0i6d

This happends me two times (now and when I did it with a group)

**Comment by Analog-Valhalla** [comment]
Is that personal loot or trash loot? Personal loot should take spec, class, and if locked to determine the gear obtained.

**Comment by Nightcap** [comment]
Interesting, I'd like to add that in this same dungeon on mythic, Turning on Group loot still behaves like it is on Personal loot on boss loot. And that once you get a item you can get the same item again, which should be prevented on Legion boss loot. This system provides you with a different item from the loot table every time you kill the same boss.

**Comment by neano300** [comment]
@Analog-Valhalla, is not from trash drop  the item was dropped by the boss. 
http://imgur.com/a/JvdLa

**Comment by Guybrush-VR** [comment]
Thanks for the report. I made a mistake with these loots (set them for plate classes instead of cloth classes)! Most of them should be alright though but I'll go over them one more time to check the ones that aren't.

**Comment by Guybrush-VR** [comment]
Okay fixed two items, that should be all. I'll close this topic now as it'll be fixed with the BRH release. If you find more items, be sure to report them back and I'll fix those as well! :tropical_drink:
