### ISSUE TITLE
Survival Instincts

### ISSUE THREAD

**Issue by orelwc** [Valhalla-Gaming/Tracker#8767]
**Describe the issue you're having**: No working, not give 50% reduces, only visual effects.

**Explain how you expect it work**: Reduces all damage you take by 50% for 6 sec.  Max 2 charges.

**Steps to reproduce the problem**: 
1.  use spell
2. check damage given

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=61336/survival-instincts

**Comment by Analog-Valhalla** [comment]
Note: Added priority high. Needed for tanking in raids

**Comment by Moustachos** [comment]
Ref #5979
