### ISSUE TITLE
Focused Rage. (tank)

### ISSUE THREAD

**Issue by neano300** [Valhalla-Gaming/Tracker#8770]
**Describe the issue you're having**:
My character warrior tank have the spell Focused rage from arms.
**Explain how you expect it work**:
The spec. Tank don't have anymore the spell Focusd Rage.

**Links to Wowhead, YouTube, etc**:
WoWHead: http://www.wowhead.com/spell=207982/focused-rage#comments

Photo: http://imgur.com/a/HD5wf

**Comment by Moustachos** [comment]
Fixed in last update.
