### ISSUE TITLE
Ashes to Ashes Arti Trait

### ISSUE THREAD

**Issue by Zealotry** [Valhalla-Gaming/Tracker#8776]
**Describe the issue you're having**:
Arrived at the trait Ashes of Ashes and by using the arti spell Wake of ashes it does not generate 5 holy power as it says.

**Explain how you expect it work**:
As soon as you use Wake Ashes on a Target, 5 holy powers are generated.

**Steps to reproduce the problem**:

1. Go to Mannequin, try... does not work
2. Duel, try...does not work
3. Bg, try...doesn't work either

**Links to Wowhead, YouTube, etc**:
None

**Comment by narodigg** [comment]
Duplicate issue logged under: [#8153](https://github.com/Valhalla-Gaming/Tracker/issues/8153) via [Valhalla's Ultimate Legion Spell Tracker #5979](https://github.com/Valhalla-Gaming/Tracker/issues/5979)

**Comment by Zealotry** [comment]
Is it gonna be fixed?

**Comment by Zealotry** [comment]
Was this fixed?
