### ISSUE TITLE
Vengeance Warrior Tank talent

### ISSUE THREAD

**Issue by neano300** [Valhalla-Gaming/Tracker#8793]
**Describe the issue you're having**:
The spell reduce the cost or your ignore pain but give a shield buff of 100-200k with 39 rage when my shields are of 900k. 

Pic: http://imgur.com/a/BkiFP

So for logic if you use 39 rage you recive a buff of 900k.

**Comment by Moustachos** [comment]
Will be fixed on next update.

**Comment by Moustachos** [comment]
Ref #5979
