### ISSUE TITLE
Worgen Death knight Flyng bug since legion realise

### ISSUE THREAD

**Issue by alltobe** [Valhalla-Gaming/Tracker#8794]
**Describe the issue you're having**: I have all flyng from flight trainer but every time i log in i need to buy again flyng or i cant fly. its wery expensiv and cost me lot of gold already! 

**Explain how you expect it work**: I have playd since wod realise and bought all flyng from trainer. so i should be abel to fly with my flyng mounts, not to buy everytime againe when i log in.

**Steps to reproduce the problem**:

1. Make me fly againe
2. fix my flyng masteris
3. refund some gold back to me

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/riding

Thankyou!. Valhalla is still best server in world. even better then retail!

**Comment by alltobe** [comment]
My char is Surm

**Comment by Analog-Valhalla** [comment]
Duplicate post #7286
