### ISSUE TITLE
[Profession][Fishing] loot tables for Draenor and Broken isles

### ISSUE THREAD

**Issue by lavalampe77** [Valhalla-Gaming/Tracker#8797]
**Describe the issue you're having**:
Draenor and Broken isles got only 1 item in their fishing loot tables: http://www.wowhead.com/item=6308/raw-bristle-whisker-catfish
**Explain how you expect it work**:
Every Area should have its own fishing loot table like for example azsuna: http://www.wowhead.com/azsuna#fishing

**Steps to reproduce the problem**:

1. Try to catch a fish in draenor or legion areas
2. Note, only that catfish can be caught
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Analog-Valhalla** [comment]
Duplicate #8550
