### ISSUE TITLE
[Demon Hunter] [Talent] Burning Alive

### ISSUE THREAD

**Issue by theprototyze** [Valhalla-Gaming/Tracker#8799]
**Describe the issue you're having**: Fiery Brand is supposed to go forward to another enemy each 2 seconds. The Damage over Time is working as intended though.

**Explain how you expect it work**: Fiery Brand needs to spread.

**Steps to reproduce the problem**:

1. Pick Burning Alive
2. Get 3 mobs close to you
3. Cast Fiery Brand
4. Deals DoT, doesn't spread

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=204021/fiery-brand

**Comment by Analog-Valhalla** [comment]
Duplicate #8612
