### ISSUE TITLE
[Demon Hunter] [Honor] Illidan's Grasp

### ISSUE THREAD

**Issue by theprototyze** [Valhalla-Gaming/Tracker#8802]
**Describe the issue you're having**: Illidan's Grasp can't throw the enemy after strangulating him

**Explain how you expect it work**: You should be able to cast it once more in 6 seconds (strangulating period) to throw the affected enemy somewhere in a 40yd radius and stun everything for 3 seconds while also dealing damage

**Steps to reproduce the problem**:

1. Cast on enemy
2. Try throwing him
3. No

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=205630/illidans-grasp

**Comment by Analog-Valhalla** [comment]
Duplicate #8662
