### ISSUE TITLE
[Demon Hunter] Metamorphosis Sever

### ISSUE THREAD

**Issue by theprototyze** [Valhalla-Gaming/Tracker#8803]
**Describe the issue you're having**: Metamorphosis should transform Shear (7.1.5) into a stronger spell (Sever) which always creates a Lesser Soul Fragment on use

**Explain how you expect it work**: Metamorphosis should transform Shear (7.1.5) into a stronger spell which always creates a Lesser Soul Fragment on use

**Steps to reproduce the problem**:

1. Metamorph
2. Makes it Sever
3. But only creates Souls sometimes

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=235964/sever

**Comment by Analog-Valhalla** [comment]
Duplicate #8659
