### ISSUE TITLE
[Mage] Flurry

### ISSUE THREAD

**Issue by theprototyze** [Valhalla-Gaming/Tracker#8804]
**Describe the issue you're having**: Flurry doesn't deal damage on World Bosses (and probably all the other bosses with the immune flag)

**Explain how you expect it work**: It should deal damage

**Steps to reproduce the problem**:

1. Flurry
2. Immune
3. No damage

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=228354/flurry

**Comment by neano300** [comment]
:D you can't abuse from flurry in pve? :D nice :3

**Comment by Analog-Valhalla** [comment]
Lets stay civilized here. Thank you :D
