### ISSUE TITLE
Melee classes keep parrying my attacks

### ISSUE THREAD

**Issue by spenzostolen** [Valhalla-Gaming/Tracker#8813]
**Describe the issue you're having**:
Melee classes keep parrying my attacks like crazy
**Explain how you expect it work**:
I am tired of having to only attack from the back, that's silly. I am not parrying any of their attacks while they parry every attack, wether it's basic, special, or my Artifact's abillity. [http://www.wowhead.com/spell=209577/warbreaker]
**Steps to reproduce the problem**:

1. Fight melees
2. Get parried
3. Report

**Links to Wowhead, YouTube, etc**:
http://wowwiki.wikia.com/wiki/Parry

**Comment by neano300** [comment]
This happends more with Paladin Retry and Dk frost

**Comment by Traveler-Valhalla** [comment]
something like that was reported **long ago** in wod times #4781

**Comment by spenzostolen** [comment]
It's possible that it's my luck to enjoy these fights with being parried but I dunno

**Comment by Moustachos** [comment]
Ref #5979
