### ISSUE TITLE
Warlock/Skill/Unstable Affliction

### ISSUE THREAD

**Issue by Uncool1** [Valhalla-Gaming/Tracker#8814]
**Describe the issue you're having**:
UA doesn't deal dmg and doesn't silence for 4 sec when dispelled!!
**Explain how you expect it work**:
UA should deal dmg and should silence the dispeller for 4 sec
**Steps to reproduce the problem**:

1. cast UA
2. Feel disappointed by watching UA getting dispelled without any consequences

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=30108/unstable-affliction

**Comment by Traveler-Valhalla** [comment]
mine deasl dmg but indeed theres no dmg and silence after dispell.

hmmmm. maybe new locks after updating to 7.1.5 have something wrong ???

**Comment by Uncool1** [comment]
Well... the issue is about "dispelling" problem that when UA is dispelled it doesn't deal dmg and doesnt silence the dispeller making UA a standard curse like Corruption or Agony etc. U can watch priests, rogues and dudes and maybe others dispelling the UA with (i bet) grin in their face...

**Comment by Uncool1** [comment]
On top of that... Every UA u stacked on enemy should deal dmg and put the opponent in the consideration whenever he should dispell the UA (condemning himself to death) or not

**Comment by Moustachos** [comment]
Just tested it and it works.

**Comment by Uncool1** [comment]
Wait a minute? like how? on who u tested that? i tested that just minute ago on a rogues Cloak of Shadows
and 0 DMG FROM DISPELLING!!!!!!!!
