### ISSUE TITLE
7.1 And 7.1.5 Class buffs and nerfs

### ISSUE THREAD

**Issue by Nightcap** [Valhalla-Gaming/Tracker#8815]
**Describe the issue you're having**: I've not noticed any of the patch changes for classes take effect on Valhalla from 7.1 or 7.1.5 working. There were both buffs and nerfs in both patches.

**Explain how you expect it work**: There are several tweaks I'll give links below.

**Steps to reproduce the problem**: Compare patch notes from retail to Valhalla.

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**: 7.1 Tweaks : https://worldofwarcraft.com/en-us/news/20335228/patch-notes-world-of-warcraft-7-1-return-to-karazhan

7.1.5 Tweaks :  http://www.wowhead.com/news=259219/patch-7-1-5-upcoming-class-tuning-hotfixes

**Comment by Moustachos** [comment]
Most of the effect buffs / nerfs (ie: damage or healing %), are already live on Valhalla.

More complex changes (ie: mechanics changes on some spells) will be supported gradually.
