### ISSUE TITLE
Rogue/Talents/Exsanguinate

### ISSUE THREAD

**Issue by Uncool1** [Valhalla-Gaming/Tracker#8816]
**Describe the issue you're having**:
Exsanguinate doesn't make bleed effects to bleed out 100% faster
**Explain how you expect it work**:
Exsanguinate should make bleed effects to bleed out 100% faster
**Steps to reproduce the problem**:

1. Take Exsanguinate as a talent choice
2. Apply the bleed effects into an enemy
3. cast Exsanguinate

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=200806/exsanguinate

**Comment by Moustachos** [comment]
Works just fine.
