### ISSUE TITLE
Demonhunter talents that aren't working

### ISSUE THREAD

**Issue by SweggieDh** [Valhalla-Gaming/Tracker#8818]
So I made an issue asking devs to fix dh talents, and got a mail telling me to report what talents I wanted fixed.

Vengeance Honor/Talents:
Fel Blade 
Flame Crash
Spirit Bomb - Frailty doesn't heal you.
Demonic Infusion - Doesn't restore 2 charges of demonic spikes.
Eye of Leotheras
Jagged Spikes

Havoc Honor/Talents:
Fel Blade
Fel Barrage
Cover of Darkness
Demonic Origins - Lasts 15 secs, but is still on a 4 min cooldown
Mana Rift
Awaken the Demon Within - Doesn't proc 
Rain from Above - Flies into the air, but only does 8 damage
Mana Break - Does 20 damage.

Fix them pls?

I'm too lazy to get a wowhead link for each talent. Just google them you have fingers.

**Comment by BeyondSteaLikez** [comment]
Those are reported. please Check issue tracker do a search before report a issue!

**Comment by Moustachos** [comment]
> I'm too lazy to get a wowhead link for each talent. Just google them you have fingers.

Check recently closed issues, many DH spells will be fixed on next update.

No need to open new issues if you can't properly format them (one issue per spell with wowhead link etc.).
