### ISSUE TITLE
 [Tactical Advance] Trait Warroir

### ISSUE THREAD

**Issue by neano300** [Valhalla-Gaming/Tracker#8819]
**Describe the issue you're having**:
When use Heroic leap don't give 30% armor and 30% parry how the talent said.
**Explain how you expect it work**:
When use heroic leap give 30% armor and 30% parry
**Steps to reproduce the problem**:

1.  Learn it
2.  Use heroic leap
3.  Nothing happends.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=209483/tactical-advance

**Comment by Kiratay** [comment]
This actually works perfectly... It's not supposed to give the bonus buffs unless you LAND it. Land doesn't mean when the animation lands... Landing means landing the attack. You're supposed to hit something with it.

**Comment by Moustachos** [comment]
Works just fine.

**Comment by Moustachos** [comment]
Ref #5979
