### ISSUE TITLE
 [QUEST] - Thirst Unending

### ISSUE THREAD

**Issue by Awkakelen** [Valhalla-Gaming/Tracker#882]
QUEST- [Thirst Unending] doesnt work properly. It should be checked on quest log when i use Arcane Torrent on Mana Wyrm but when I do that nothing happens.

**Comment by MirrorWraith** [comment]
i think you should wait for specific starting area fix in changelog, the lastest fix is on red cloud mesa

**Comment by Vasharij** [comment]
I'am still having this issue.

**Comment by Awkakelen** [comment]
Still having.

**Comment by Pure-Valhalla** [comment]
http://www.wowhead.com/quest=8346/thirst-unending

Quest is fixed

**Comment by Tregeta** [comment]
fixed next update
