### ISSUE TITLE
Execute Warrior Arms

### ISSUE THREAD

**Issue by neano300** [Valhalla-Gaming/Tracker#8821]
**Describe the issue you're having**:
This spell Doing really low Damage on pvp when is a spell who finishing the enemy. hits 60k-100k with burst.
**Explain how you expect it work**:
this spell can hits 300k-400k to finishing the enemy.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=163201/execute

**Comment by Moustachos** [comment]
There's nothing wrong with this spell's damage.
