### ISSUE TITLE
Bladestorm Warrior Arms.

### ISSUE THREAD

**Issue by neano300** [Valhalla-Gaming/Tracker#8822]
**Describe the issue you're having**:
This spell doing Low damage on pvp  like 40-50k with burst.
**Explain how you expect it work**:
Of course this spell can't do 40-50k per hit with burst. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=46924/bladestorm

**Comment by Moustachos** [comment]
There's nothing wrong with this spell's damage.
