### ISSUE TITLE
Expel Harm 7.1.5.

### ISSUE THREAD

**Issue by neano300** [Valhalla-Gaming/Tracker#8826]
**Describe the issue you're having**:
The spell do not do anything.
**Explain how you expect it work**:
Draw in the positive chi of all your Healing Spheres, and expel negative chi, damaging the nearest enemy for 10% of the amount healed.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=115072/expel-harm

If going to fix any dodge of the monk first fix the heal. thanks.

**Comment by theprototyze** [comment]
I think the first thing that should get fixed is the broken 100%+ dodge. Priorities are made by them not by you.

**Comment by neano300** [comment]
you talking about abusers make me and everyone laught lol.

**Comment by Hemoglobine-Valhalla** [comment]
what 100%+ dodge you talk about? elusive brawler works that way, read it then talk.
