### ISSUE TITLE
[Deathknight] Marrowrend Haste Stacks

### ISSUE THREAD

**Issue by Analog-Valhalla** [Valhalla-Gaming/Tracker#8830]
**Describe the issue you're having**:
Using Marrowrend increases haste by 11% each stack
**Explain how you expect it work**:
Should only be a 10% increase in total
**Steps to reproduce the problem**:

1. Look at haste before Boneshield stacks
2. Marrows rend to 10 Boneshield stacks
3. Notice haste values not right

**Links to Wowhead, YouTube, etc**:
<a href="http://imgur.com/4A6125C"><img src="http://i.imgur.com/4A6125C.jpg" title="source: imgur.com" /></a>
<a href="http://imgur.com/ZOwFLfs"><img src="http://i.imgur.com/ZOwFLfs.jpg" title="source: imgur.com" /></a>
http://www.wowhead.com/spell=195182/marrowrend
http://www.wowhead.com/spell=195181/bone-shield

**Comment by Moustachos** [comment]
This isn't a bug, haste bonuses are multiplicative, not additive.

In this case, you have the following:
1.13 (base haste) * 1.1 (one stack of Bone Shield) = 1.21

However there is indeed another bug: haste bonus provided by Bone Shield isn't supposed to increase with stacks (should be 10%, no matter if you have 1 stack or 10), that part will be fixed on next update.

**Comment by Moustachos** [comment]
Ref #5979
