### ISSUE TITLE
[Demon Hunter] Tormentor

### ISSUE THREAD

**Issue by theprototyze** [Valhalla-Gaming/Tracker#8832]
**Describe the issue you're having**: Tormentor changes the Torment in PvP, but the debuff doesn't apply

**Explain how you expect it work**: Tormentor Debuff should apply

**Steps to reproduce the problem**:

1. PvP
2. Tormentor
3. Just a fake Torment

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=207029/tormentor

**Comment by Traveler-Valhalla** [comment]
#8660 already reported
