### ISSUE TITLE
[Profession][Skinning] Legion Mobs Skinning

### ISSUE THREAD

**Issue by theprototyze** [Valhalla-Gaming/Tracker#8833]
**Describe the issue you're having**: You cannot skin any legion mobs

**Explain how you expect it work**: You should be able to

**Steps to reproduce the problem**:

1. Get skinning
2. Get skinning knife
3. Kill mobs
4. No skinning

**Links to Wowhead, YouTube, etc**: -

**Comment by Nightcap** [comment]
Fixed in previous update.
