### ISSUE TITLE
[Shaman] Stormkeeper Artifact Ability

### ISSUE THREAD

**Issue by Analog-Valhalla** [Valhalla-Gaming/Tracker#8836]
**Describe the issue you're having**:
Stormkeeper allows Chain lightning/Lighting Bolt to be spammed more than 3 times. Chain lightning/Lightning Bolt will be instant cast until Stormkeeper buff expires.
**Explain how you expect it work**:
Should only be able to cast Chain lightning/Lightning Bolt 3 times.
**Steps to reproduce the problem**:

1. Cast Stormkeeper
2. Spam Chain Lightning

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=205495/stormkeeper

**Comment by Moustachos** [comment]
Can you confirm that this bug didn't occur before 7.1.5?

**Comment by Analog-Valhalla** [comment]
Before 7.1.5. the issue with this ability was limited to not being able to fully cast 3 Lightning Bolts in a row. Everything else seemed to be fine. Yes I can confirm it did not happen before 7.1.5.
