### ISSUE TITLE
[Demon Hunter] Empower Wards

### ISSUE THREAD

**Issue by theprototyze** [Valhalla-Gaming/Tracker#8838]
**Describe the issue you're having**: Doesn't reduce any damage

**Explain how you expect it work**: It should reduce all damage by 30%

**Steps to reproduce the problem**:

1. Get autoattacked normally
2. Empower Wards
3. Get attacked again and see if anything

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=218256/empower-wards

**Comment by Moustachos** [comment]
This spell isn't meant to reduce physical damage so it won't work on autoattacks.

No bug here, closing.
