### ISSUE TITLE
Rogue/Subtlety/Honor Talent/Thief's Bargain

### ISSUE THREAD

**Issue by Uncool1** [Valhalla-Gaming/Tracker#8839]
**Describe the issue you're having**:
Thief's Bargain doesn't work at all.....
**Explain how you expect it work**:
http://www.wowhead.com/spell=212081/thiefs-bargain
**Steps to reproduce the problem**:

1. Be Subtlety and take Thief's bargain as a honor talent choice
2. Look at health pool/do some dmg while stealthed/ cast Vanish and look at its cooldown
3. Be greatly dissapointed, cuz no fixes for subtlety talents was ever made...

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=212081/thiefs-bargain

**Comment by Uncool1** [comment]
This spec is truly unplayable and reports of its bugged talents was made last year before update and after update still: NO fixes.

at all....

**Comment by Traveler-Valhalla** [comment]
#8079 yes it was already reported........... i feel like half of reports here are duplicates.

**Comment by Analog-Valhalla** [comment]
Duplicate as said above

**Comment by Uncool1** [comment]
Well still no fixes, even when theyre duplicated
and that was last year.... besides report 8079 say something about reducing hp, mine thiefs of bargain doesnt even reduce the hp pool

**Comment by Uncool1** [comment]
here are the pics 
[http://imgur.com/8DtNwBm](url)
