### ISSUE TITLE
Proving Pit quest bug

### ISSUE THREAD

**Issue by Azotherian** [Valhalla-Gaming/Tracker#8840]
**Describe the issue you're having**: I am trying to continue the mage quest "The Proving Pit". I cannot get the option by the Darkspear Jailor to open the cage.

**Explain how you expect it work**: I need to talk to a Darkspear Jailor to open the cage that a naga is being held in. I need to kill the naga to continue the quest.

**Steps to reproduce the problem**: 

1. Talk to Zen'tarba to get the quest
2. Talk to a Darkspear Jailor and not get the option to open the cage.
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=24768/proving-pit

**Comment by Traveler-Valhalla** [comment]
#981
#1203
reported already

**Comment by GM-Pyromanic** [comment]
Duplicate report
