### ISSUE TITLE
Retribution Paladin Talent: "Divine Purpose"

### ISSUE THREAD

**Issue by Lhyron** [Valhalla-Gaming/Tracker#8841]
**Describe the issue you're having**:
Divine Purpose makes all the techniques using Holy Power **FREE FOR ITS WHOLE DURATION**. Shame on Paladins retribution that used this bug in combination with [Justicar's Vengeance](http://www.wowhead.com/spell=215661/justicars-vengeance) to do massive damage and heal themselves in the meantime and never reported it in the issue tracker.

**Explain how you expect it work**:
Divine Purpose has 20% to proc from Holy Power abilities and makes free you **NEXT** ability using Holy Power.

**Steps to reproduce the problem**:

1. Take Divine Purpose as a talent
2. Divine Purpose procs
3. Spam Free Templar Verdict, Divine Storm or Justicar's Vengeance for 10sec.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=223817/divine-purpose

**Comment by Moustachos** [comment]
Can you confirm that this bug didn't occur before 7.1.5?

**Comment by Lebiedz** [comment]
It's kinda weird that for me this talent has never procced - check #8755

**Comment by Moustachos** [comment]
> It's kinda weird that for me this talent has never procced - check #8755

I can confirm that this talent properly procs (but 20% chance is pretty low).

However, I can also confirm that it grants an unlimited amount of casts, I'll fix it soon.

**Comment by Lhyron** [comment]
I never tested it before 7.1.5. I was very suspicious when some pallys ret were spamming Justicar's Vengeance without loosing life in BG.
