### ISSUE TITLE
Warlock/Honor Talent/Nether Ward

### ISSUE THREAD

**Issue by Uncool1** [Valhalla-Gaming/Tracker#8844]
**Describe the issue you're having**:
Nether Ward reflects crowds control abilities like fear
**Explain how you expect it work**:
Nether Ward shouldn't reflect cc cuz any kind of crowd control ability isnt't a **harmful spell**
**Steps to reproduce the problem**:

1. Take Nether Ward
2. Tell ur friend to cast fear on you while Nether Ward is on
3. Watch ur friend running in fear for 20 sec

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=212295/nether-ward

**Comment by BeyondSteaLikez** [comment]
i hope you read the "effects" in wowhead  Apply Aura: Reflect All Spells This means every spell that exists

**Comment by Uncool1** [comment]
fine then
