### ISSUE TITLE
[Quest] Hags of a Feather

### ISSUE THREAD

**Issue by Sozeone** [Valhalla-Gaming/Tracker#8858]
**Describe the issue you're having**:
Quest Hags of a Feather cannot be accomplished : http://imgur.com/a/NJ5mL
**Explain how you expect it work**:
http://www.wowhead.com/quest=39373/hags-of-a-feather
**Steps to reproduce the problem**:

1. Take the quest Hags of a Feather
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=39373/hags-of-a-feather

**Comment by Guybrush-VR** [comment]
Remove two from your bags.
