### ISSUE TITLE
[Warlock] Backdraft or Chaos bolt

### ISSUE THREAD

**Issue by Sozeone** [Valhalla-Gaming/Tracker#8860]
**Describe the issue you're having**:
Idk if its normal but Chaos Bolt consumes only 1 charge of Backdraft. On top of that along with Reverse Entropy and Soul Conduit sometimes [if Soul Conduit procs] im able to shot 3-4 bolts in a row
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. take Reverse Entropy 
2. take Soul Conduit 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=117828/backdraft

**Comment by Analog-Valhalla** [comment]
Edit done to add Wowhead link. Please provide Wowhead links in the future. Thank you :D

**Comment by Sozeone** [comment]
http://imgur.com/a/R7PcG
http://imgur.com/a/OPA5b

**Comment by Sozeone** [comment]
The thing is: i didn't post any wowhead links cuz im not sure which one doesn't work; cbolt of backdraft. Maybe thats how it should work but for me being able to shot 4 bolts that hits 1-1,5 mln dmg its op

**Comment by Moustachos** [comment]
Chaos Bolt is meant to consume only 1 charge of Backdraft per cast.
