### ISSUE TITLE
FargoDeep Mine problem

### ISSUE THREAD

**Issue by heavybassX** [Valhalla-Gaming/Tracker#8865]
**Describe the issue you're having**: The mission is bugged, I can't get a completed and I went through the mine 2-3 times and with a party member too.

**Explain how you expect it work**: You go through the mine and then the quest is then checked when you get into a certain place in the mine, even in the highlighted area.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Analog-Valhalla** [comment]
Duplicate report #8541
