### ISSUE TITLE
[Druid] Ysera's Gift

### ISSUE THREAD

**Issue by Analog-Valhalla** [Valhalla-Gaming/Tracker#8870]
**Describe the issue you're having**:
This ability heals all party members for 3% of the druid's health, regardless of anyone being full health.
**Explain how you expect it work**:
Should only heal one injured party member
**Steps to reproduce the problem**:

1. Select Ysera's Gift as a Talent
2. Passive Heals will come in 5 seconds

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=145108/yseras-gift

**Comment by Analog-Valhalla** [comment]
Note: Should behave similar to Healing Stream Totem.
http://www.wowhead.com/spell=5394/healing-stream-totem

**Comment by Moustachos** [comment]
Ref #5979
