### ISSUE TITLE
[Mage] Arcane Barrage

### ISSUE THREAD

**Issue by Analog-Valhalla** [Valhalla-Gaming/Tracker#8891]
**Describe the issue you're having**:
Arcane barrage deals normal damage, BUT occasionally when a critter is nearby the target the Arcane Barrages damage scales off the critters critters level to be doing over 2 million on a single cast to critter and player or mob
**Explain how you expect it work**:
This should not occur
**Steps to reproduce the problem**:

1. Ensure critter is next to player
2. Begin duel with player
3. Gain charges to make barrage multi-target by using Arcane Blast
3. Arcane barrage and 1 shot both.

**Links to Wowhead, YouTube, etc**:
<a href="http://imgur.com/bYTNYX3"><img src="http://i.imgur.com/bYTNYX3.jpg" title="source: imgur.com" /></a>
<a href="http://imgur.com/T3KPjiH"><img src="http://i.imgur.com/T3KPjiH.jpg" title="source: imgur.com" /></a>
http://www.wowhead.com/spell=44425/arcane-barrage

**Comment by Sozeone** [comment]
Hotfix this fast cuz i see mages abusing it a lot

![](http://i.imgur.com/80N8QEl.jpg)

**Comment by Analog-Valhalla** [comment]
Note: This issue is confirmed to occur in Battlegrounds

**Comment by Sozeone** [comment]
yeah i kno i just posted another proof of that

**Comment by Moustachos** [comment]
Ref #5979
