### ISSUE TITLE
[Warrior][Protection] Critical Block

### ISSUE THREAD

**Issue by lavalampe77** [Valhalla-Gaming/Tracker#8899]
**Describe the issue you're having**:
Somehow prot warriors block never critical, what makes mastery and at least 1 elite trait of protection legendary weapon useless.
**Explain how you expect it work**:
When you fight mobs and look into your combat log there should be sometimes a "(Crititcal)" behind "(Block)". Because this never happens... https://github.com/Valhalla-Gaming/Tracker/issues/8427  doesnt work.
**Steps to reproduce the problem**:

1. Fight a couple of Mobs
2. Take a look at your Combat Log
3. Notice not a single Critical Block

**Links to Wowhead, YouTube, etc**:

**Comment by Moustachos** [comment]
Critical Block mechanic works fine, it's just that it doesn't show up in combat log (you won't see a "Critical Block" message).

However, you can see when a block is critical by the amount of blocked damage, if blocked damage are higher than taken damage, then it's a critical block.
