### ISSUE TITLE
[Hunter][Survival] Mastery: Hunting Companion

### ISSUE THREAD

**Issue by Proklet** [Valhalla-Gaming/Tracker#8901]
**Describe the issue you're having**:
The mastery does not trigger under any circumstance.

**Explain how you expect it work**:
[Mastery: Hunting Companion](http://www.wowhead.com/spell=191334/mastery-hunting-companion) should make pet attacks regain a single charge of [Mongoose Bite](http://www.wowhead.com/spell=190928/mongoose-bite) in a similar fashion to how [Snake Hunter](http://www.wowhead.com/spell=201078/snake-hunter) restores all of the charges.
I have to note that there are many spells and talents that should allow the Hunter to regain charges of Mongoose Bite in similar fashion or increase the chance of Mastery: Hunting Companion proccing, but none of them manage to grant any charges ever, except Snake Hunter talent.

**Steps to reproduce the problem**:
1. Make your pet attack a target for a period of time
2. Make sure you have expended all of your Mongoose Bite charges.
3. Observe if any charges are restored earlier than it's natural cooldown (they won't be)

**Links to Wowhead, YouTube, etc**:
The issue has been reported here: #8735 ; I am just elaborating in detail so you could fix it.

**Comment by Traveler-Valhalla** [comment]
#7255
#8735
already reported

**Comment by Analog-Valhalla** [comment]
Duplicate #7255
