### ISSUE TITLE
[Hunter][Survival][Talent] Trailblazer

### ISSUE THREAD

**Issue by Proklet** [Valhalla-Gaming/Tracker#8903]
**Describe the issue you're having**:
The talent [Trailblazer](http://www.wowhead.com/spell=199921/trailblazer) does not work.

**Explain how you expect it work**:
It should give you a buff that increases your movement speed by 30% as long as you or your pet did not attack within 3 seconds, without difference if you are in or out of combat.

**Steps to reproduce the problem**:
1. Pick the talent Trailblazer
2. Run around while not attacking anybody
3. Check if your movement speed has changed (it won't as you won't get the buff)

**Links to Wowhead, YouTube, etc**:

**Comment by Traveler-Valhalla** [comment]
#7779 already reported

**Comment by Analog-Valhalla** [comment]
Duplicate #7779
