### ISSUE TITLE
[Quest] Basic botany (Sunflower pet questline)

### ISSUE THREAD

**Issue by Aprophys** [Valhalla-Gaming/Tracker#8905]
**Describe the issue you're having**:
The whole event is not scripted for all these quests for the sunflower pet.

**Explain how you expect it work**:
If you take a quest you get automaticly in the plant vs. zomie mode but here still nothing happend.
**Steps to reproduce the problem**:

1. Taked quest
2. Nothing happend
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=28733/basic-botany
http://www.wowhead.com/quest=28617/flower-power
http://www.wowhead.com/quest=28617/flower-power
http://www.wowhead.com/quest=28747/someone-setup-the-pumpkin-bomb
http://www.wowhead.com/quest=28748/lawn-of-the-dead

**Comment by Traveler-Valhalla** [comment]
#2437
#2587
reported

**Comment by Analog-Valhalla** [comment]
Duplicate
