### ISSUE TITLE
Fire Mage Honor Talent: "Tinder"

### ISSUE THREAD

**Issue by Lhyron** [Valhalla-Gaming/Tracker#8906]
**Describe the issue you're having**:
Reduce permanently the cd of Fireball by 50% and increase its damage by 30%

**Explain how you expect it work**:
If you have not cast Fireball for 8 sec, your next Fireball will deal 30% increased damage with a 50% reduced cast time.

**Steps to reproduce the problem**:

1. 1 second cast Fireballs !!
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=203275/tinder

**Comment by Traveler-Valhalla** [comment]
#7978 already reported

**Comment by Analog-Valhalla** [comment]
Duplicate

**Comment by Lhyron** [comment]
#7978 it is said that the Honor Talent doesn't work.
In my issue, the talent does work, granting **50% reduced cast time for all fireballs** !
