### ISSUE TITLE
[Mage] Arcane Missiles indefinitely

### ISSUE THREAD

**Issue by Analog-Valhalla** [Valhalla-Gaming/Tracker#8914]
**Describe the issue you're having**:
Arcane mages can cast Arcane Missiles indefinitely due to arcane missilies being spamming and granting multiple stacks of more Arcane Missiles
**Explain how you expect it work**:
Arcane missiles should not proc this often, or be used as often

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=5143/arcane-missiles
https://youtu.be/jxcYINNMpwU?t=9m11s   (Example from Blizz)

**Comment by Traveler-Valhalla** [comment]
#8308

**Comment by theprototyze** [comment]
Think it was done again to be prioritised (?)

**Comment by Analog-Valhalla** [comment]
Duplicate. Oops
