### ISSUE TITLE
[Mage] Arcane Missiles

### ISSUE THREAD

**Issue by theprototyze** [Valhalla-Gaming/Tracker#8916]
**Describe the issue you're having**: Each Arcane Missile projectile has a HIGH (75%~) chance of triggering one more stack of Arcane Missile to be possibly cast.

**Explain how you expect it work**: Arcane Missiles should only have a 15% Chance to have stacks triggered by ALL spells. Arcane Missiles should only trigger Arcane Missiles stacks once (not each projectile having its own chances)

**Steps to reproduce the problem**:

1. Arcane Missile
2. Each Projectile has its own chance of adding stacks
3. It should only be a 15% chance (which is not, it procs almost 75% of the time for each projectile) and 30% for Arcane Blast

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=5143/arcane-missiles
https://www.youtube.com/watch?v=jxcYINNMpwU&feature=youtu.be&t=9m11s

**Comment by theprototyze** [comment]
Note: I am not sure if Arcane Missiles is even supposed to grant charges to itself, that needs to be checked. In any case all said above this are certain.

**Comment by Moustachos** [comment]
Ref #5979
