### ISSUE TITLE
Paladin Retribution Mastery issue

### ISSUE THREAD

**Issue by Zealotry** [Valhalla-Gaming/Tracker#8919]
**Describe the issue you're having**: Well this issue was posted in an older post back in December. As you know mastery is almost inactive with the Retribution Paladin, this factor increases our dps considerably. This will be our only defense which is an offense for killing high dps caracs, or at least have a considerable weight against healers. If possible, please fix it ASAP.

**Explain how you expect it work**: All you need is in the wowhead link

**Steps to reproduce the problem**: No need the issue is known

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=76672/mastery-divine-judgment

Thank You

**Comment by Analog-Valhalla** [comment]
Note: Marked High Priority due to being Class Mastery.

**Comment by Zealotry** [comment]
I hope a fix will be implemented soon

**Comment by Moustachos** [comment]
Ref #5979
