### ISSUE TITLE
[Destruction Warlock] [Backdraft] talent 

### ISSUE THREAD

**Issue by Happyburstday** [Valhalla-Gaming/Tracker#8920]
**Describe the issue you're having:** When using Backdraft talent, Warlocks gain 2 stacks of Backdraft buff, which allows them to cast 2 Incinerates or Chaos Bolts 30% faster. The problem is that Backdraft buff is consumed when Chaos Bolt or Incinerate hits the target, allowing players to cast up to 3 or 4 of those spells instead of actual 2.

**Explain how you expect it work:** Backdraft should be consumed whenever player casts those spells, not when it hits the the target.

**Steps to reproduce the problem:**
1.  Cast Conflagrate when you have selected Backdraft talent.
2.  Cast as many Chaos Bolts or Incinerates as possible (having bigger range between the target allows to cast more of those spells.

**Links to Wowhead, YouTube, etc:** https://www.youtube.com/watch?v=syJF9NEUoSY  0:30

**Comment by Analog-Valhalla** [comment]
Are you saying that Backdraft never consumer charges after casting chaos bolt to hitting or that chaos consumes not enough stacks of Backdraft?

**Comment by Happyburstday** [comment]
I'm saying that the buff should be consumed instantly when you cast those spells, not when it hits the target. This bug allows the player to cast more of those spells than intented.

**Comment by Moustachos** [comment]
Ref #5979
