### ISSUE TITLE
[Trait][MM Hunter] Legacy of the Windrunners

### ISSUE THREAD

**Issue by Eastwud** [Valhalla-Gaming/Tracker#8927]
**Describe the issue you're having**:
I just unlocked the trait in my artifact weapon "Legacy of the Windrunners" (this is the same name as the weapon, but **the problem is with the trait**). It has a 15% chance to proc 6 wind arrows when casting aimed shot that deal damage to the target but it doesn't.

As you can see in the image below I did 10M damage to a target without the passive ever being triggered

**Explain how you expect it work**:
When casting aimed shot, there is a 15% chance 6 wind arrows to be released at the target.

**Steps to reproduce the problem**:
1. Unlock the trait "Legacy of the Windrunners"
2. Cast aimed shot on a target for a while
3. Notice that there are no wind arrows that deal additional damage

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=190852/legacy-of-the-windrunners
http://imgur.com/a/lN8Pr

**Comment by Traveler-Valhalla** [comment]
#7225 already reported

**Comment by Analog-Valhalla** [comment]
Duplicate
