### ISSUE TITLE
[Quest] Hags of a Feather - Quest Item Loot Issue

### ISSUE THREAD

**Issue by VictorTyne** [Valhalla-Gaming/Tracker#8931]
**Describe the issue you're having**:

When doing the quest "Hags of a Feather" in Highmountain, if you attempt to loot a number of Hag Feathers that would put you over the 50 required for the quest, you get a "You cannot carry any more of those items." error.

Attempting to destroy a Hag Feather gives you the warning message "Destroying this item will abandon related quests". However you can destroy an amount of feathers without the quest abandoning itself, making the quest -technically- possible to complete.

**Explain how you expect it work**:

Either you should loot the entire number and the extras should disappear when you complete the quest or you should loot a partial stack to bring you up to the appropriate number.

**Steps to reproduce the problem**:

1. Go to Highmountain.
2. Start quests "Hags of a feather"
3.  Collect ~45 Hag Feathers
4. Attempt to loot a stack of 6 or more feathers.

**Links to Wowhead, YouTube, etc**:

**Comment by Analog-Valhalla** [comment]
This is a result of the AOE looting with the loot from multiple mobs having more than the amount of feathers needed
