### ISSUE TITLE
[Item] Foxflower Flux not sold by proper vendors

### ISSUE THREAD

**Issue by Analog-Valhalla** [Valhalla-Gaming/Tracker#8933]
**Describe the issue you're having**:
Not sold by any vendors
**Explain how you expect it work**:
Should be sold by 3 vendors.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/item=124436/foxflower-flux
http://www.wowhead.com/npc=92184/imindril-spearsong
http://www.wowhead.com/npc=92245/thala-steeltotem
http://www.wowhead.com/npc=92265/urael

**Comment by GM-Pyromanic** [comment]
Items are not sold until you complete a certain quest in the blacksmith quest chain. So the vendors are work ING as they should be until the quest is repaired.
