### ISSUE TITLE
[Deathknight] Bonestorm

### ISSUE THREAD

**Issue by Analog-Valhalla** [Valhalla-Gaming/Tracker#8946]
**Describe the issue you're having**:
Bonestorm heals at a standard rate per second. Damage being done does not trigger the healing, like its supposed to. Heals the caster with out having mobs taking damage or even there.
**Explain how you expect it work**:
Deals shadow damage every 1 sec, and healing you for 2% of your maximum health every time it deals damage. It should be able to do more healing per target hit. 
**Steps to reproduce the problem**:

1. Get 100 runic power
2. Stand far from mobs/ target dummy
3. Use Bonestorm and observe healing patterns

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=194844/bonestorm

**Comment by Moustachos** [comment]
> It should be able to do more healing per target hit.

This is a 2% of max health heal no matter how many targets are hit, but you're right about the fact that it shouldn't trigger if it doesn't deal any damage, going to fix it.

**Comment by Moustachos** [comment]
Ref #5979
