### ISSUE TITLE
[Death Knight] [Honor] Decomposing Aura

### ISSUE THREAD

**Issue by theprototyze** [Valhalla-Gaming/Tracker#8949]
**Describe the issue you're having**: It should deal damage to everybody around the user, stacking up to 5 times to a maximum of 15% each 2 seconds and lasting for 6 seconds even if the target isn't in the range anymore.

**Explain how you expect it work**: ^

**Steps to reproduce the problem**:

1. Decomposing Aura
2. PvP
3. Nothing
4. Cry

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=199720/decomposing-aura

**Comment by Analog-Valhalla** [comment]
Duplicate #8911
