### ISSUE TITLE
Warlock (Destruction) Mastery: Chaotic Energies

### ISSUE THREAD

**Issue by Nienz** [Valhalla-Gaming/Tracker#8950]
ive been looking on alot of videos and checking on how it works, for me the high damage output seems to be alot more frequent on valhalla, as an example: on pvp chaos bolt damage is 700k.
im not 100% ofc but to me the mastery seems to "proc" on maximum output more frequent then it should

http://www.wowhead.com/spell=77220/mastery-chaotic-energies

Reference video: https://www.youtube.com/watch?v=qN5O4RTuUT0

**Comment by theprototyze** [comment]
Higher damage procs should be extremely rare, unlike how it seems to be happening most of the time.

**Comment by Moustachos** [comment]
Ref #5979
