### ISSUE TITLE
PROFFESION

### ISSUE THREAD

**Issue by sasakibara1** [Valhalla-Gaming/Tracker#8955]
PROFESSION ON LEGION MAP IS NOT WORKING AND TRAINERS TOO AND VENDORS :D I BUY SKINING AND LEATHERWORKING RECIPES IN DALARAN ( LEGION DALARAN) KLIK BUT NOT WORKING . AND I CANT PLAYNG IF PROFFESION IS NOT WORKING PLEASE FIX . AND NOT WORKING ON WOD MAP TOO PROFFESION .

**Comment by theprototyze** [comment]
PLEASE FIX YOUR TEMPLATE

**Comment by Analog-Valhalla** [comment]
Hello there! Can you report what specific issues you are having, a link to this feature from wowhead, and maybe ways to replicate it. Thank you :D
