### ISSUE TITLE
Protection Paladin Spell: "Judgement"

### ISSUE THREAD

**Issue by Lhyron** [Valhalla-Gaming/Tracker#8960]
**Describe the issue you're having**:
Shield of the Righteous' CD isn't reduced when casting judgement.

**Explain how you expect it work**:
Judgment reduces the remaining cooldown of Shield of the Righteous by 2 sec, or 4 sec on a critical strike.

**Steps to reproduce the problem**:

1. Cast Judgement
2. Check Shield of the Righteous CD
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=231657/jugement

**Comment by Analog-Valhalla** [comment]
Similar #7952

**Comment by Moustachos** [comment]
Ref #5979
