### ISSUE TITLE
I'm stuck at level 95. Can't go back to Draenor please help

### ISSUE THREAD

**Issue by mazzmariello** [Valhalla-Gaming/Tracker#8961]
**Describe the issue you're having**:

So i completed the WoD starting quest, went through the portal and all until the un-scripted garrison part. Went back to Azeroth but now there's no way for me to go to Draenor again.
- Tried the Dark portal, if i take the quest from Khadgar again i actually reach draenor on the other side but im stuck in the "Assault on the  dark portal" scenario with no friendly npcs around so i can just wander around and kill mobs. 
If I enter the portal right away, it will lead me to Hellfire Peninsula.
- Tried to use the portals in Orgrimmar and Undercity to Warspear they dont work. 
- Tried my mage Teleport spell, not working.
- Tried Garrison Hearthstone, not working.

I asked around and it seems I'm the only one on Asgard server to have this problem, whats wrong with me? :) Character name: Zizou

**Comment by Analog-Valhalla** [comment]
A GM will be on shortly to assist you on this matter.
