### ISSUE TITLE
Disc Priest Spell power bug.

### ISSUE THREAD

**Issue by Sungoddess26** [Valhalla-Gaming/Tracker#8964]
Disc priest spells doing pve dmg in pvp. Wich slipt away from templates.

**Comment by Aprophys** [comment]
I can deny it im disc and my dmg is lower in pvp.

**Comment by Analog-Valhalla** [comment]
25% damage reduction is as stands. Thank you for the report. :D

**Comment by Sungoddess26** [comment]
Ur spec holy not even disc in those ss's. Jesus..
