### ISSUE TITLE
[Death Knight] Unholy Mastery

### ISSUE THREAD

**Issue by theprototyze** [Valhalla-Gaming/Tracker#8989]
**Describe the issue you're having**: Unholy Mastery isn't increasing any Shadow Damage

**Explain how you expect it work**: -

**Steps to reproduce the problem**: -

1. 55% more Shadow Damage
2. or 40% more Shadow Damage
3. same

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=77515/mastery-dreadblade

**Comment by Moustachos** [comment]
Works just fine.
