### ISSUE TITLE
Archaeology Highmountain No rares after 40 Commons

### ISSUE THREAD

**Issue by BeyondSteaLikez** [Valhalla-Gaming/Tracker#8992]
**Describe the issue you're having**:
Solved many Commons (40 in total) In highmountain still no Rare
**Explain how you expect it work**:
After few Commons it should give a rare To craft (Solve)
**Steps to reproduce the problem**:

**Links to Wowhead, YouTube, etc**:

**Comment by Moustachos** [comment]
Not a bug, in Legion rare projects are granted through quests and we don't support this yet.
