### ISSUE TITLE
Death Knight Starting zone Quest

### ISSUE THREAD

**Issue by Malthaell** [Valhalla-Gaming/Tracker#8993]
**Describe the issue you're having**: I can´t complete the Quest "Death Comes from On High

**Explain how you expect it work**: There are no abilitys in the eye.

**Steps to reproduce the problem**:

1. Create a Death Knight
2. Go for the quest "Death comes from on high
3. Enter the eye and you have no abilitys
How are you suposed to complete the story line when you have a bugged quest so early on?And this quest was reported in 10 September 2016 and today is 27 Feb 2017.Almost 6 moths and its not fixed? I Herd this realm is well scripted and in the first10 minutes of the game im already disappointed with it.Can't weit to se what other quests are bugged for half a year.
Links to Wowhead, YouTube, etc**:  https://www.youtube.com/watch?v=NFAUNWvgBzg

**Comment by Analog-Valhalla** [comment]
Duplicate #6501

**Comment by Malthaell** [comment]
Then explain to me why the quest is till not fixed?
