### ISSUE TITLE
[Death Knight] Diseases getting Blocked

### ISSUE THREAD

**Issue by theprototyze** [Valhalla-Gaming/Tracker#9002]
**Describe the issue you're having**: Diseases get sometimes Blocked

**Explain how you expect it work**: Diseases should not get Blocked (I understand Immune... but Block?)

**Steps to reproduce the problem**:

1. Unholy/ Frost DK
2. Disease this one annoying Monk (or anybody else, really)
3. See him BLOCK your Diseases
4. Ragequit

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=191587/virulent-plague http://www.wowhead.com/spell=55095/frost-fever

**Comment by Moustachos** [comment]
There is a visual bug causing absorbed damage to be displayed as "blocked" for the opponent.

That's what you see here, and absorbing a disease's damage is perfectly legit.
