### ISSUE TITLE
''Stormheim'' quest

### ISSUE THREAD

**Issue by Hemowow** [Valhalla-Gaming/Tracker#9003]
**Soo,I leveled up a DH to lvl100. Got my artifact,got to my class hall and decided to start questing in Storheim.However the NPC ''Sky Admiral Rogers'' didn't appear were it's supposted to be in Violet Citadel.Please help.

**I expect the NPC ''Sky Admiral Rogers'' to be there in the Violet Citadel.

![wowscrnshot_022817_142335](https://cloud.githubusercontent.com/assets/21905285/23406902/8bdc9dc0-fdc1-11e6-854f-5bdec87ab31a.jpg)
also pay attention on the map,you can see the question mark but no npc.

**Comment by Guybrush-VR** [comment]
Stormheim quests are not available yet. You can head to Highmountain for now!

**Comment by Hemowow** [comment]
Good to know!Thank you for sharing your information.I shall go to Highmountain!
