### ISSUE TITLE
Quest , General Bug

### ISSUE THREAD

**Issue by TfzGG** [Valhalla-Gaming/Tracker#9006]
2 Major issues

1) I made a new troll hunter and the second quest is not working (Proving Pit). 
2) After I made the new character (Troll Hunter) I had to relog for a second, I was lvl 1 with a pet raptor. When I logged back in my pet was nowhere to be found, I tried to call it but nothing happened.

**Comment by Analog-Valhalla** [comment]
Duplicate #981 #7159

**Comment by TfzGG** [comment]
@Analog-Valhalla do we have any idea when will it be fixed? what should I do from now on?
