### ISSUE TITLE
Symbols of Death - Rogue Sub

### ISSUE THREAD

**Issue by MscleMike** [Valhalla-Gaming/Tracker#9013]
****Describe the issue you're having**:**
Symbol of Death only stays on for 4-5 sec
****Explain how you expect it work**:**
It is supposed to stay on for 35sec
****Steps to reproduce the problem**:**
Enter stealth, activate SoD and it fades away after 5 sec...
http://www.wowhead.com/spell=212283/symbols-of-death

**Comment by Sozeone** [comment]
Duplicate
