### ISSUE TITLE
(Resto Druid) Mastery : Harmony

### ISSUE THREAD

**Issue by Fdistvan** [Valhalla-Gaming/Tracker#9026]
**Describe the issue you're having**:
The more hot`s has a player on the bether heal he shuld get,when hot`s ar on the heal dos not get bigger. Whitout it we berly can heal dungeons,the NL dungeon  on mityc  we canot iven heal. its themost important spels for the druid cuz  it has a woking sinergy whit all the druid spels,once the raid is coming out  we wont be abel to go  as  healers  cuz of this  spel not working.
**Explain how you expect it work**:
When ther ar  hots on a player  the healing on that player shuld be  bigger
**Steps to reproduce the problem**:

1.hot ppl up 
2. cast a healing tuch  
3. the healing is  usualy the same sa when ther ar no hot`s  on

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=77495/mastery-harmony

**Comment by Moustachos** [comment]
Fixed by latest update.
