### ISSUE TITLE
(Resto Druid) Artifact Wepon Spell Essence of G`Hanir

### ISSUE THREAD

**Issue by Fdistvan** [Valhalla-Gaming/Tracker#9027]
**Describe the issue you're having**:
It shuld speed up the tick time of the hot`s of the druid,when activated it dos noting.This is  one of the 2 burst healing spels and mana saving spel  whitout it we can berly  burst heal.In DT dungeon on mityc  we can berly heal the 1st boss  fight once the tank gets  the bleed on himself,we  canot  heal back to  90% hp  to be abel to  take of the bleed,we have to  let the tank died and then reberth him,bu once the boss  bleeds him agan  we wipe.so this spel iss needed wery much for the raid

**Explain how you expect it work**:
When activating spell the hot`s on  the player shuld tick  much faster
**Steps to reproduce the problem**:

1. cast hot`s on player
2. use spell
3. same ticking time 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=208253/essence-of-ghanir

**Comment by Analog-Valhalla** [comment]
Duplicate #6066 Will be fixed in next update

**Comment by Fdistvan** [comment]
O nice so next update.Ty for the intel
