### ISSUE TITLE
(Resto Druid) Spell Regrowth

### ISSUE THREAD

**Issue by Fdistvan** [Valhalla-Gaming/Tracker#9028]
**Describe the issue you're having**:
The spell shuld have a 40% chance of criting but it dos not have that chance its way lower.It has the crit chance around the same  as  all the other spels.

**Explain how you expect it work**:
When casting  Regrowth it shuld have a 40% chance  of criting
**Steps to reproduce the problem**:

1. Cast  Regrowth multipel times 
2. Folow the spel healing  numbers 
3. see how low the chance is 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=8936/regrowth

**Comment by Moustachos** [comment]
Fixed by latest update.
