### ISSUE TITLE
(Resto Druid) Talent Cultivation

### ISSUE THREAD

**Issue by Fdistvan** [Valhalla-Gaming/Tracker#9029]
**Describe the issue you're having**:
It shuld apply a hot on the player once he gets heald whit a rejuvination below 60% helth.It dos not apply it ath all. This spell is an important one  for druids to be abel to heal and not strugle like we do now 

**Explain how you expect it work**:
when casting rejuve on a player hos below 60% health it shuld ad  the cultivation hot on the player to 
**Steps to reproduce the problem**:

1. let player  go below 60% health
2. cast rejuve
3. no hot  of cultivation is put on player

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=200390/cultivation

**Comment by Moustachos** [comment]
Fixed by latest update.
