### ISSUE TITLE
(Resto Druid) Artifact Talent Dreamwalker

### ISSUE THREAD

**Issue by Fdistvan** [Valhalla-Gaming/Tracker#9030]
**Describe the issue you're having**:
When used Wild Growth spell ther is a 50% chance of instantly healing all allies affected by your Rejuvenation for (250% of Spell power), atm the chance is ath 0% . It is a wery needed  talent  for druids to be abel to heal the raids.

**Explain how you expect it work**:
Cast Wild Growth multiple time and  it shuld have a 50% chance of healing all allies affected by your Rejuvenation for (250% of Spell power)
**Steps to reproduce the problem**:

1. hot up whit rejuve  all party mambers 
2. cast Wild Growth multiple times 
3. not geting the  50%  instant heal prock

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=189849/dreamwalker

**Comment by Moustachos** [comment]
Fixed by latest update.
