### ISSUE TITLE
[Druid] Dash usable outside Catform

### ISSUE THREAD

**Issue by Analog-Valhalla** [Valhalla-Gaming/Tracker#9032]
**Describe the issue you're having**:
Dash can be used out side of cat form and the speed can stack (ex. Stag form).
**Explain how you expect it work**:
Dash should only be usable in cat form. Should not stack with stag form
**Steps to reproduce the problem**:

1. Cast Dash
2. Switch into Stag Form
3. Run the flag uninterrupted at a high speed.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=1850/dash

**Comment by Moustachos** [comment]
Works as intended (no boost out of Cat Form).
