### ISSUE TITLE
Black ox brew

### ISSUE THREAD

**Issue by Jijing01** [Valhalla-Gaming/Tracker#9033]
**Describe the issue you're having**: Cd of black ox brew is not reduced by keg smash and tiger palm.

**Explain how you expect it work**: It is considered as brew in terms of keg smash and tiger palm cd reduction and those spells should reduce its cd.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/brewmaster-talent-guide

**Comment by Nightcap** [comment]
Thats right, but it doesn't work at all last I checked. And I haven't seen it get fixed in the update. I can't wait to have it, That talent really makes us shine as a tank.

**Comment by Jijing01** [comment]
This is still not fixed...
