### ISSUE TITLE
Parry

### ISSUE THREAD

**Issue by Lhyron** [Valhalla-Gaming/Tracker#9040]
**Describe the issue you're having**:
Strength increases greatly parry chances leading to high parry rates (60%) for Death Knights, Paladins and Warriors.

**Explain how you expect it work**:
Strength increases parry but the rates are way too high

**Steps to reproduce the problem**:

1. Remove strength stuff
2. Check parry chances
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=82246/parry
http://www.wowhead.com/spell=82242/parry
http://www.wowhead.com/spell=3127/parry

**Comment by Lhyron** [comment]
This also concernes PVE as Dk, Pallys and Wars tanks don't take much damages in dungeons.

**Comment by Moustachos** [comment]
> Strength doesn't increase parry anymore.

Could you provide an official source for that part? (like patch notes or something)

**Comment by Lhyron** [comment]
My bad, Strength does increase Parry in legion as well as Agility increases Dodge. 
http://blue.mmo-champion.com/topic/409203-theorycrafting-questions/#post351

However, with Palatank I can do some bosses in mythic without a healer. Would it be possible that diminishing returns don't apply correctly ? So that tanks reach high parry rate.

**Comment by GM-Pyromanic** [comment]
Parry from strength was reduced in WoD by 25% and same for dodge from Agility but it does still increase it .

here are some screens from my retail fury warrior showing how much parry increases with strength.
Before using strength Trinket.
![wow-64_2017-03-03_18-21-46](https://cloud.githubusercontent.com/assets/20587569/23563415/7e78ecae-003e-11e7-8135-898b45908208.png)

After using strength trinket to increase it by 4449 which results in a 2.01% increase in parry.
![wow-64_2017-03-03_18-22-31](https://cloud.githubusercontent.com/assets/20587569/23563437/972e252a-003e-11e7-9cd0-4099bf2ac4fb.png)

**Comment by Lhyron** [comment]
Please we need a quick fix ! There is a pally that solo Worldbosses...
