### ISSUE TITLE
Foul Bulwark

### ISSUE THREAD

**Issue by twoinchknife** [Valhalla-Gaming/Tracker#9043]
**Describe the issue you're having**:

Foul Bulwark is not raising max health 2% per bone shield charge, currently it only gives 2% total.

**Explain how you expect it work**:

Foul Bulwark is suppose to increase max health 2% per shield charge.

**Links to Wowhead, YouTube, etc**:

http://www.wowhead.com/spell=206974/foul-bulwark

**Comment by Analog-Valhalla** [comment]
Duplicate report #9042. Before posting please look on the Issue Tracker for duplicates in the future. Thank you. :D
