### ISSUE TITLE
(Quest)Tuning the Gnomercorder

### ISSUE THREAD

**Issue by Fdistvan** [Valhalla-Gaming/Tracker#9044]
**Describe the issue you're having**:
When u take the  quest it send us to the graveyard to thest   the gnomecorder  but noting is ther
**Explain how you expect it work**:
go to the gravyard  and  us the ithem ther 
**Steps to reproduce the problem**:

1. take quest
2. got to place indicated
3. no device ther

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=26512/tuning-the-gnomecorder

**Comment by Analog-Valhalla** [comment]
Duplicate #8084
