### ISSUE TITLE
line quest "Death Comes From On High" not works

### ISSUE THREAD

**Issue by angi89v** [Valhalla-Gaming/Tracker#9050]
**Describe the issue you're having**:
the line quest "Death Comes From On High" of the death Knight not works and not auto completes 
If you accept the quest and use "Eye of Acherus Control Mechanism" the eye don't have the skills "siphon of acherus ", "Shroud", "Summon ghouls on scarlet crusade" and gives max speed to walk.

**Explain how you expect it work**:
The "Siphon of Acherus" ability should work so that you can complete the quest.
The "Summon ghouls on Scarlet Crusade" ability should work so that you can defend the eye.

**Steps to reproduce the problem**:
1. Start a fresh Death knight
2. Quest up to the Lich King
3. Began "Death comes from on high" quest
4. Use the eye control mechanism.
5. Used "Siphon of Acherus" to scan the buildings.
6. Complete the quest.

**Links to Wowhead, YouTube, etc**:
 Quest: http://www.wowhead.com/quest=12641/death-comes-from-on-high
Skill of eye : http://www.wowhead.com/spell=51859/siphon-of-acherus
                   http://www.wowhead.com/spell=51904/summon-ghouls-on-scarlet-crusade
                   http://www.wowhead.com/spell=52006/shroud

**Comment by Analog-Valhalla** [comment]
Duplicate #6501

**Comment by Malthaell** [comment]
Then fix the god damn quest if its "duplicate"!Some ppl like me wants to play only as a dk and this quest dosen't allow us to do so!!
