### ISSUE TITLE
 Monk-Fortifying Brew

### ISSUE THREAD

**Issue by Nightcap** [Valhalla-Gaming/Tracker#9069]
**Describe the issue you're having**: This spell is not fully scripted, it only gives a HP bonus. none of the other effects work.

**Explain how you expect it work**: Turns your skin to stone for 15 sec, increasing your current and maximum health by 20%, increasing the damage you delay with Stagger by an additional 20%, and reducing all damage you take by 20%.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=115203/fortifying-brew

**Comment by Moustachos** [comment]
All the effects work just fine.
