### ISSUE TITLE
Paladin Tank Spells and Mob Behavoir

### ISSUE THREAD

**Issue by ticklex** [Valhalla-Gaming/Tracker#907]
Tank Paladin damage spells are all school holy-that means pure spells. So it should be impossible for mobs to parry, dodge or decrease them with resistance. Holy spells are the only spell school in wow resists never existed for. Spells can only be parried by players with special skilled abilies but not by mobs.
http://www.wowhead.com/spell=53600/shield-of-the-righteous  for example were dodged 3,5% and parried 1% by mobs (checked on mobs +/- 2 lvl of me)

**Comment by Malae1** [comment]
To further go in to this, 

All players now have a 100% chance to hit, 0% chance to be dodged, 3% chance to be parried, and 0% chance to glance, when fighting creatures up to 3 levels higher (bosses included).

    Tank specializations receive an additional 3% reduction in chance to be parried, so tank attacks have a 0% chance to be parried vs. creatures up to 3 levels higher.

    Creatures 4+ levels higher than you still have a chance to avoid your attacks in various ways, so as to discourage you from attempting to fight enemies that are much stronger than you.

    Dual Wielding still imposes a 17% chance to miss, so as to balance it with two-handed weapon use.
