### ISSUE TITLE
[Death Knight][Artifact] Scourge of Worlds

### ISSUE THREAD

**Issue by theprototyze** [Valhalla-Gaming/Tracker#9071]
**Describe the issue you're having**: Scourge of Worlds triggers from multiple attacks (rune-spending abilities), not only Death Coils. Also, it triggers more often from the other attacks than the Death coil, which is scary.

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=191747/scourge-of-worlds

**Comment by Moustachos** [comment]
Will be fixed on next update.
