### ISSUE TITLE
Quest - Highmountain - The guy in the costume

### ISSUE THREAD

**Issue by hlk2005** [Valhalla-Gaming/Tracker#9074]
**Describe the issue you're having**:
When you go to Tamara Sigmund, she doesn't have the option "Send me to Shipwreck Cove, Please". Even if you walk up there to turn in the quest at the murloc, he just has a grey question mark above his head. I tried to abandon the quest next to him, and see if I could pick up his part. But, you cannot. Which is awful. This is a very fun, and long quest. WIth a lot of nice exp, and rewards. Also, you aren't able to unlock any of the other quests in the area becuase of it.
**Explain how you expect it work**:
(Copied the discription from Wowhead.com) In Nesingwary's Retreat at 40.2, 52.7 in Highmountain, talk to the flightmaster, Tamara Sigmund, and choose "Send me to Shipwreck Cove, please". Once you land, learn the new flightpoint, and turn in the quest about 50 yards to the east.
**Steps to reproduce the problem**:

1. Not a clue how you would fix it. Just putting it out there, maybe you can look into it and see if it would be fixable. I am sure it is. 
2. 
3. 

**Links to Wowhead, YouTube, etc**: https://youtu.be/c-OXQkxmrSk (Not my vid)

**Comment by BeyondSteaLikez** [comment]
Duplicate #8407
