### ISSUE TITLE
Item: Six-Feather Fan targets wearer

### ISSUE THREAD

**Issue by Fayetallity** [Valhalla-Gaming/Tracker#9082]
**Describe the issue you're having**: I have above mentioned item equipped and it keeps targetting me. Both during combat or right after the last mob died.
Unless the self heal ability of a DH works as a targetself mechanism I cannot see why this item would target me.  Especially not when I have 5+ mob on me constantly

**Explain how you expect it work**: I'm sure it's supposed to only taget enemies

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/item=141585/six-feather-fan

**Comment by BeyondSteaLikez** [comment]
Duplicate #7823
