### ISSUE TITLE
[Druid guardian] Spell: "Lightning Reflexes"

### ISSUE THREAD

**Issue by alucula** [Valhalla-Gaming/Tracker#9099]
**Describe the issue you're having**:
Lightning Reflexes covert less Crit in Dodge then it should be
**Explain how you expect it work**:
It should convert 100% of Crit from gear in Dodge
**Steps to reproduce the problem**:

<img width="446" alt="schermata 2017-03-05 alle 20 47 38" src="https://cloud.githubusercontent.com/assets/23052761/23590688/213a38ba-01e5-11e7-93ed-4436e0b33234.png">

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=231065/lightning-reflexes

**Comment by Moustachos** [comment]
Works just fine.
