### ISSUE TITLE
Everything bugged

### ISSUE THREAD

**Issue by Phychoblaze** [Valhalla-Gaming/Tracker#9100]
tried to do some instances and half of them were bugged (nexus, lady vashj, kael'thas maybe some others too ) and half the quests in every area don't work. honestly it would take a lot of time to sit and find each one of them but at least do something about the dungeons.

**Comment by Analog-Valhalla** [comment]
Hello there! Can you report what specific issues you are having, a link to this feature from wowhead, and maybe ways to replicate it. Individual reports appreciated. Thank you :D
