### ISSUE TITLE
[Rogue Outlaw] Artifact trait: "Blunderbuss" Still not working

### ISSUE THREAD

**Issue by alucula** [Valhalla-Gaming/Tracker#9101]
**Describe the issue you're having**:
Blunderbuss not working
**Explain how you expect it work**:
"When Saber Slash strikes an additional time, there is a 33% chance that your next Pistol Shot will be replaced with Blunderbuss.
 -Blunderbuss-
Draws a concealed blunderbuss and fires a quick shot at the target, dealing ((121% of Attack power) * 7) damage and reducing movement speed by 50% for 6 sec.]

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=202897/blunderbuss

**Comment by Sozeone** [comment]
duplicate ref  #8069
