### ISSUE TITLE
[Rogue Outlaw]Artifact trait : "Ghostly  Shell" not working

### ISSUE THREAD

**Issue by alucula** [Valhalla-Gaming/Tracker#9102]
**Describe the issue you're having**:
Ghostly shell don't heal you for 6%
**Explain how you expect it work**:
It should heal for 6% of my health each effect cleared

**Links to Wowhead, YouTube, etc**:
<img width="335" alt="schermata 2017-03-06 alle 03 29 27" src="https://cloud.githubusercontent.com/assets/23052761/23594802/2de09306-021d-11e7-8c6e-26bee648cf8b.png">

**Comment by Sozeone** [comment]
duplicate ref#8717
