### ISSUE TITLE
Shaman (Enhancement) - Talent - Crashing Storms

### ISSUE THREAD

**Issue by DiamondStud** [Valhalla-Gaming/Tracker#9103]
**Describe the issue you're having**:

Crashing Storms does not leave an electrical field on the ground where Crash Lightning is used.

**Explain how you expect it work**:

When using Crash Lightning with this talent, a patch should be left on the ground where Crash Lightning was used doing damage to those within it for 6 seconds.

**Steps to reproduce the problem**:

1.  Take Crashing Storms
2.  Use Crash Lightning
3. 

**Links to Wowhead, YouTube, etc**:

http://www.wowhead.com/spell=192246/crashing-storm

**Comment by Analog-Valhalla** [comment]
Duplicate #7790
