### ISSUE TITLE
Warrior Arms Artifact skill  Tactical Advance

### ISSUE THREAD

**Issue by Kazakon** [Valhalla-Gaming/Tracker#9108]
**Describe the issue you're having**:
increased armor and chance to parry dont work after leap.
**Explain how you expect it work**:
heroic leap must give 30% increased armor and chance to parry for 4 sec after the leap.

**Links to Wowhead, YouTube, etc**:
http://prntscr.com/egp7yz

**Comment by Moustachos** [comment]
It works, if you hit anything when you land.
