### ISSUE TITLE
[Warlock] [Demonology] Demonwrath

### ISSUE THREAD

**Issue by Happyburstday** [Valhalla-Gaming/Tracker#9114]
Demonwrath sometimes consumes too much mana (for example over 50% of mana)

Demonwrath should consume 27,500 mana per second

**Steps to reproduce the problem**:

1. Cast Demonwrath
2. Watch mana bar
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Lhyron** [comment]
Duplicate #8481
