### ISSUE TITLE
Fire Mage Tier 5 talent: Frenetic Speed

### ISSUE THREAD

**Issue by Ayfee** [Valhalla-Gaming/Tracker#9116]
**Describe the issue you're having**:
Frenetic Speed activates upon dealing damage with any damaging spell, _not only fire spells._
**Explain how you expect it work**:
It should only activate upon casting Scorch.
**Steps to reproduce the problem**:

1. Choose Frenetic Speed as a tier 5 talent.
2. Deal damage with any one of your ability.
3. See your movement speed getting increased by Frenetic Speed. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=236058/frenetic-speed

**Comment by Lhyron** [comment]
It's a duplicate #8635
