### ISSUE TITLE
[Legion Loot] Skinning Loot  [Oddly-Shaped Stomach] You can't open it never

### ISSUE THREAD

**Issue by BeyondSteaLikez** [Valhalla-Gaming/Tracker#9118]
**Describe the issue you're having**:
Oddly-Shaped Stomach You can't open it 
**Explain how you expect it work**:
You should able to open it to get Various of items
 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/item=129746/oddly-shaped-stomach#contains

**Comment by Nightcap** [comment]
Confirmed, most of the time it wont loot. 3/13/17
