### ISSUE TITLE
[Legion] Stonehide Leather Sample (Quest for Skinning Not working)

### ISSUE THREAD

**Issue by BeyondSteaLikez** [Valhalla-Gaming/Tracker#9119]
**Describe the issue you're having**:
It does not drop at all from skinning it should be 32% that is very %
**Explain how you expect it work**:
It should drop normaly from Manastalkers 32% drop rate with skinning

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/npc=107746/manastalker#skinning

**Comment by Nightcap** [comment]
Dropped for me today, but increased skill to 750.

**Comment by Guybrush-VR** [comment]
It does drop from a variety of creatures.
