### ISSUE TITLE
Quests in Teldrassil.

### ISSUE THREAD

**Issue by Fizwa** [Valhalla-Gaming/Tracker#912]
I know there have been previous posts about it, just an updated one.
Teldrassil: passing awareness- druid quest to talk to Corthas Moonrage. he isn't spawned

Nature's reprisal- the item works to kill the grelkins but the deaths do not count toward quest

The emerald Dreamcatcher. Item is not spawned in the hut to the east

A lot of the quest items that are required for the quests in this area that need to be picked up off a corpse are bugged, it says you have already looted them and wont let you pick them up. 

there should also be more quests available here, like the harpy quest and the demon (i believe) quest to the southwest near the edge of the trees. I know you havent scripted it yet so i understand. Thanks

Estel & Arborian

**Comment by Sonofsven** [comment]
Nature's reprisal Works
The emerald Dreamcatcher Works,

**Comment by Cidragon** [comment]
everything is working now :)
