### ISSUE TITLE
[Prestigue reward quest] A Royal Audience

### ISSUE THREAD

**Issue by Sozeone** [Valhalla-Gaming/Tracker#9120]
**Describe the issue you're having**:
after achieving prestigue lvl 2 and using [High Warlord's Medal of Valor] the quest doesn't work
**Explain how you expect it work**:
http://www.wowhead.com/quest=42985/a-royal-audience
**Steps to reproduce the problem**:

1. get prestigue lvl 2 and use [High Warlord's Medal of Valor]
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=42985/a-royal-audience

**Comment by Analog-Valhalla** [comment]
#7498 Duplicate
