### ISSUE TITLE
Highmountain quest lines

### ISSUE THREAD

**Issue by KOCOZAN** [Valhalla-Gaming/Tracker#9125]
![adsiz](https://cloud.githubusercontent.com/assets/26047142/23690303/7f4d63da-03d1-11e7-8ad9-f8fb6305c34b.png)
I don't know if it is a bug or they are disabled to be scripted for full function, though my question is "are those quest,marked with red arrows, functional now? or I am missing something to start them?"

This would be useful to know for anybody on the same line of quests.

Thanks.

**Comment by Lebiedz** [comment]
Only half or so of Highmountain has been scripted so far.

**Comment by Analog-Valhalla** [comment]
Will be scripted in future updates.
