### ISSUE TITLE
Archaeology Map Blobs

### ISSUE THREAD

**Issue by Drakensin** [Valhalla-Gaming/Tracker#9126]
**Describe the issue you're having**: Cant see the areas for Archaeology

**Explain how you expect it work**: When you open the map, you should be able to see the red blobs of where you can find the artifacts.

**Steps to reproduce the problem**:

1. Open Map when you get archaeology, and go to one of the continents that has the shovel Icon
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Moustachos** [comment]
Works for me, try to clear your cache and disable your addons, then retry.
