### ISSUE TITLE
Legion Mythic Dungeons Loot in General

### ISSUE THREAD

**Issue by Nightcap** [Valhalla-Gaming/Tracker#9134]
**Describe the issue you're having**: Initially I thought the boss looting issue was just in Neltharions Lair, But it's all Mythics where Personal loot is forced. Bosses often drop no loot to anyone in the party, at random.

**Explain how you expect it work**: People should get loot from Mythic bosses every time the are killed. 

**Steps to reproduce the problem**: Kill mythic bosses 

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by UmbraUnda** [comment]
Mythics are supposed to be that way - FYI tho, try relogging just before each boss to reset the loot %s.

**Comment by Nightcap** [comment]
Only mythic +, which we do not have access to yet is that way. Mythic normal has loot per boss. 

**Loot**
Loot is ilvl 805 in Normal mode for level 110 players, ilvl 825 on Heroic and ilvl 840 on Mythic.

For Mythic+ Dungeons, loot does not drop per boss. At the end of the dungeon, a special chest will spawn that contains loot from the dungeon, for which the base ilvl increases based on the Mythic Keystone level. The loot is personal, so each player should loot it to see what their reward is. Two pieces of loot are guaranteed and the items will be appropriate to the player's class/spec.

In addition, all loot in Legion is on an ilvl spectrum. Loot has a base ilvl and a progressively smaller chance to appear as a Warforged version, increasing in intervals of +5 ilvls. The maximum cap is ilvl 895. Learn more about loot in the Early Legion Gearing Guide.
I pulled this from wowhead HERE: http://www.wowhead.com/black-rook-hold-dungeon-strategy-guide

If you can back up your claims please do. Otherwise you are not helping.

**Comment by Analog-Valhalla** [comment]
Currently the personal loot system is working, and loot is dropping as intended by the system in use. This system will be upgraded to match legion changes in the future. If you are locked from loot from that boss you will not receive loot fomr that same boss until raid resets.
