### ISSUE TITLE
Getting Disconnected when im About to Level Up!

### ISSUE THREAD

**Issue by Kadriag** [Valhalla-Gaming/Tracker#9138]
**Describe the issue you're having**:
When I try To Gain the Last Amount of Expirience to Reach Lvl 70 I Get Kicked Out of the Server...
In one of my Attempts to Level Up  I Reached the Achievment ( Got to Level 70) ...Got Kicked Out Inmediatly...And when I Went Online Again I Was 69.........
**Explain how you expect it work**:
Well...Gain the Amount of Expirience Needed and Level Up!
**Steps to reproduce the problem**:

1. Kill a Mob or Finish a Quest That Grants me Enough Expirience to Level Up!
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Analog-Valhalla** [comment]
These disconnects were not related to your leveling. The issue as been fixed.
