### ISSUE TITLE
Hobart Grapplehammer

### ISSUE THREAD

**Issue by Lzeir** [Valhalla-Gaming/Tracker#9139]
**Describe the issue you're having**: Hobart Grapplehammer is missing some of the items he should be selling 

**Explain how you expect it work**: He should sell Felgibber Shotgun, "Twirling Bottom" Repeater, Surface-to-Infernal Rocket Launcher and Chaos Blaster

**Steps to reproduce the problem**:

1. go to new dalaran
2. try to buy stuff from Hobart Grapplehammer
3. things arent there 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/npc=93539/hobart-grapplehammer
![wowscrnshot_031017_183406](https://cloud.githubusercontent.com/assets/26330506/23803776/406e431e-05c0-11e7-8daa-a738b5f54a94.jpg)
![wowscrnshot_031017_183408](https://cloud.githubusercontent.com/assets/26330506/23803777/4074c0fe-05c0-11e7-90e0-ebb849aae8c6.jpg)
![wowscrnshot_031017_183409](https://cloud.githubusercontent.com/assets/26330506/23803778/4077d186-05c0-11e7-9291-221249402253.jpg)

**Comment by Analog-Valhalla** [comment]
These items arent missing they should be gated behind quests. After completing certain quests they appear and are purchaseable. Thank you for the report. :D
