### ISSUE TITLE
Arcane mages Prismatic Barrier now working

### ISSUE THREAD

**Issue by jocawow** [Valhalla-Gaming/Tracker#9141]
**Describe the issue you're having**:
On the tool tip of the spell it says shields you for 1 min and absorbs X amount of magic dmg. But when I cast then spell it says absorbs 0 magic dmg. I tried too see if it was a bug and it didn't absorb any dmg.
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Lhyron** [comment]
Already reported #8613

**Comment by Analog-Valhalla** [comment]
Duplicate
