### ISSUE TITLE
[Deathknight][Frost] Death Strike healing affected by another ability

### ISSUE THREAD

**Issue by Analog-Valhalla** [Valhalla-Gaming/Tracker#9147]
**Describe the issue you're having**:
Using Icebound Fortitude + Death strike results in healing different than intended.
**Explain how you expect it work**:
There should be no healing decrease or increase when using these abilities together
**Steps to reproduce the problem**:
1. Cast Icebound Fortitude
2. Cast Death Strike
**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=48792/icebound-fortitude
http://www.wowhead.com/spell=49998/death-strike

**Comment by llamalama** [comment]
Are you sure it isn't the Frost artifact trait Ice in Your Veins?
http://www.wowhead.com/spell=189154/ice-in-your-veins

**Comment by Analog-Valhalla** [comment]
Thank you, forgot talents like these exist.
