### ISSUE TITLE
cant connect

### ISSUE THREAD

**Issue by Dethvitch** [Valhalla-Gaming/Tracker#9150]
**Describe the issue you're having**:
I have the launcher and patched but when i log into the game i cant acess the server
**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Analog-Valhalla** [comment]
What exact error are you getting? Also, are you using the client provided by Blizzard or another server?
