### ISSUE TITLE
Sidewinders - Hunter MM talent skill

### ISSUE THREAD

**Issue by Rattoy** [Valhalla-Gaming/Tracker#9165]
**Describe the issue you're having**:
hunter MM talent skill - Sidewinders should replace only arcane shot, but its also replace multishot , and cant use multishot anymore while learn this talent.

**Explain how you expect it work**:
It should only disable arcane shot.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Lhyron** [comment]
http://www.wowhead.com/spell=214579/sidewinders. Not a bug. Read the description of the spell. It replaces both Arcane shot and Multi-shot
