### ISSUE TITLE
[Death Knight][Scenario Quest:Death Comes From On High]

### ISSUE THREAD

**Issue by Malthaell** [Valhalla-Gaming/Tracker#9188]
Describe the issue you're having:
the line quest "Death Comes From On High" of the death Knight not works and not auto completes
If you accept the quest and use "Eye of Acherus Control Mechanism" the eye don't have the skills "siphon of acherus ", "Shroud", "Summon ghouls on scarlet crusade" and gives max speed to walk.

Explain how you expect it work:
The "Siphon of Acherus" ability should work so that you can complete the quest.
The "Summon ghouls on Scarlet Crusade" ability should work so that you can defend the eye.

Steps to reproduce the problem:

Start a fresh Death knight
Quest up to the Lich King
Began "Death comes from on high" quest
Use the eye control mechanism.
Used "Siphon of Acherus" to scan the buildings.
Complete the quest.

Some ppl might apreciate if you would stop beeing lazzy and complete a broken scenario quest.The Dk class is literaly broken just from this quest beeing unnable to do anything until you complete it.If you guiz know the development is lazzy at least make the quest insta complete to avoid serious problems as this.And not to mention the fact that this quest was reported several times in the last 6 or more months and i know,its a duplicate.I will continue making new issues regarding this quest once i se some develpment regarding the bugged quests.

Links to Wowhead, YouTube, etc:
Quest: http://www.wowhead.com/quest=12641/death-comes-from-on-high
Skill of eye : http://www.wowhead.com/spell=51859/siphon-of-acherus
http://www.wowhead.com/spell=51904/summon-ghouls-on-scarlet-crusade
http://www.wowhead.com/spell=52006/shroud

**Comment by Analog-Valhalla** [comment]
Duplicate #6501
