### ISSUE TITLE
[Druid guardian talent] Galactic guardian 

### ISSUE THREAD

**Issue by alucula** [Valhalla-Gaming/Tracker#9198]
**Describe the issue you're having**:
Galactic guardian return less rage than it should do
**Explain how you expect it work**:
It should return 8 rage and it return from 2 to 6(usually 4)
**Steps to reproduce the problem**:

1. when Galactic guardian is active put moonfire on a mob and check the rage

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=203964/galactic-guardian

**Comment by Analog-Valhalla** [comment]
That 4-6 Rage you are seeing is from auto attacks. This Ability does not generate rage. Thank you for the report. Duplicate #9166
