### ISSUE TITLE
[Druid Guardian passive/stats]Lightning reflexes/Crit and Dodge

### ISSUE THREAD

**Issue by alucula** [Valhalla-Gaming/Tracker#9201]
**Describe the issue you're having**:
I gather two screenshot, one from valhalla and one from a youtube channel from a guardian druid in offy

Focus on the Druid crit and dodge because the passive [lighting reflexes] should take 100% of crit and put on dodge. the first screen is from official w0w server, the second one is from valhalla.

<img width="580" alt="schermata 2017-03-17 alle 16 03 07" src="https://cloud.githubusercontent.com/assets/23052761/24071151/a5651a16-0bcb-11e7-9ead-f205c5347524.png">
<img width="491" alt="schermata 2017-03-18 alle 11 06 27" src="https://cloud.githubusercontent.com/assets/23052761/24071156/b2ffdfc6-0bcb-11e7-89ba-ffaf4e8d346e.png">

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=231065/lightning-reflexes

**Comment by Moustachos** [comment]
This passive works just fine.
