### ISSUE TITLE
Death Knight; Adventure Guide

### ISSUE THREAD

**Issue by WarcraftAcc** [Valhalla-Gaming/Tracker#9204]
**Describe the issue you're having**:
Adventure guide says "this feature's is not yet available"
**Explain how you expect it work**:
I should be able to open adventure guide

**Comment by Analog-Valhalla** [comment]
As a temporary work around, here is a macro you can use to open the Adventure Guide:
/run if not EncounterJournal then EncounterJournal_LoadUI() end ToggleFrame(EncounterJournal)

Thank you for the report. Unforunatelt this is a duplicate. Please check if other reports like this exist before psting. Thank you :D #9011
