### ISSUE TITLE
Death Knight; bugged abilities

### ISSUE THREAD

**Issue by WarcraftAcc** [Valhalla-Gaming/Tracker#9205]
These are some abilities that are bugged:
### Unholy spec:
**[All Will Serve]** - only removes cooldown but doesn't spawn additional skeleton
**[Epidemic]** - hits everyone around you but does nothing but aggro
**[Sludge Belcher]** - nothing happens when activated
**[Defile]** - nothing happens when activated
**[Apocalypse]** - doesn't burst "festering wounds" nor summoning member of the "army of the dead"
**[Sudden Doom]** - does not turn on by auto attacks
**[Corpse Shield]** - doesn't reduce damage
### Blood spec:
**[Crimson Scourge]** - stays active even when activate 1 death and decay
- That bug when i can't activate any ability...

this one on all specializations **[Dark Succor]**  - turns on after any kill, not only pvp target

**Comment by theprototyze** [comment]
Everything besides the Dark Succor (killing minions in pvp enables it) is reported.

**Comment by Analog-Valhalla** [comment]
Duplicate thread
