### ISSUE TITLE
Legion Trinket Effects

### ISSUE THREAD

**Issue by UmbraUnda** [Valhalla-Gaming/Tracker#9207]
**Describe the issue you're having**:
Many ilvl 810 trinket effects don't work - example Eyasu's Mulligan.

**Explain how you expect it work**:
Effect should trigger a buff +stats noticed in character stats.

**Steps to reproduce the problem**:

1. Use Eyasu's Mulligan
2. Green aura appears
3. Nothing else happens - no buff or anything- not even proper cooldown.

**Links to Wowhead, YouTube, etc**:

**Comment by avaksx** [comment]
#7378

**Comment by Analog-Valhalla** [comment]
Duplicate #7378
