### ISSUE TITLE
Paladin Legendary Armor: Justice Gaze

### ISSUE THREAD

**Issue by UmbraUnda** [Valhalla-Gaming/Tracker#9208]
**Describe the issue you're having**:
Justice Gaze's Effect not working.
**Explain how you expect it work**:
Effect: Hammer of Justice deals 600% Holy damage and has 75% reduced cooldown when used against an enemy above 75% health.
http://www.wowhead.com/spell=211557/justice-gaze
**Steps to reproduce the problem**:
n/a
1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/item=137065/justice-gaze

**Comment by Analog-Valhalla** [comment]
Hello there! Can you elaborate on what exact legendary item you are using?

**Comment by UmbraUnda** [comment]
Paladin Legendary : Justice Gaze
http://www.wowhead.com/item=137065/justice-gaze

**Comment by Analog-Valhalla** [comment]
Thank you for editing this post. :D
