### ISSUE TITLE
Frost DK Artifact gives no off-hand

### ISSUE THREAD

**Issue by Usernameisntalreadytaken** [Valhalla-Gaming/Tracker#9213]
**Describe the issue you're having & Explain how you expect it work**:
I should get both a main hand and an off-hand weapon from the artifact.
I'm stuck with only the main-hand right now, and I'm not the only one with this issue it seems (talked to some other DKs)
**Steps to reproduce the problem**:

1. Get the artifact
2. Right click it with both a main-hand and an off-hand equipped for the first time you equip it
3. ???
4. Weep as you're forced to play any other spec than frost.

**What I have tried so far to fix it**:
- Talked to GMs in-game (lol)
- Relogged
- Emptied both hands then cleared my cache, relogged and re-tried equipping it by right click
- Every single combination of moving items in and out of my hands to try and somehow get the artifact to spawn an off-hand

**Comment by Analog-Valhalla** [comment]
Hello there, If you fill in a ticket via our website, we can address this further. Please include your In Game Name in the ticket. Thank you :D https://en.valhalla-realms.com/account/tickets
