### ISSUE TITLE
[Deathknight] Rune Regeneration

### ISSUE THREAD

**Issue by Analog-Valhalla** [Valhalla-Gaming/Tracker#9218]
**Describe the issue you're having**:
There are many occasions where this problem feels evident. It affects the DK class as a whole and extremely hurts tanking. The regeneration feels very clunky as though it might be a visual bug or a resource bug. When trying to use an ability even with multiple runes up its impossible until after all of the old runes have been used. A player can have 5 runes up and not able to used them until all are refreshed.
**Explain how you expect it work**:
Runes should be fluid and be able to be used directly off cooldown.
**Links to Wowhead, YouTube, etc**:
https://www.youtube.com/watch?v=JHp7TbF2WyQ
I apologize for this video already. But heres another one. Keep track of the runes not being clunky and being useless.
https://www.youtube.com/watch?v=bBM4wm6SZMo

**Comment by WarcraftAcc** [comment]
I would make this high priority, it makes whole class unplayable, blood spec especially

**Comment by Analog-Valhalla** [comment]
If there is an issue trying to test this try using this add-on to track runes easier.
https://mods.curse.com/addons/wow/compact-runes

I think Issue could be linked with the amount of runes regenerating at the same time, it should be a max of three. There might be a Visual Bug to make it look as though three are regenerating even though they are not. Try using Marrowrend or Obliterate to test these interactions. Thank you :D
http://www.wowhead.com/spell=195182/marrowrend
http://www.wowhead.com/spell=49020/obliterate
