### ISSUE TITLE
Fury warrior with second wind

### ISSUE THREAD

**Issue by Ezikeal** [Valhalla-Gaming/Tracker#9221]
**Describe the issue you're having**:
was using fury spec in arenas and for some reason i had second wind while i'm on fury spec it heals me for 100k-250k
**Explain how you expect it work**:
the second wind talent is for arms not fury and it kept healing me every second.
**Steps to reproduce the problem**:
arms only spec...
1. when your health goes down to 50% i think the second wind will pop and it only heals for 6% 
**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=29838/second-wind

**Comment by Analog-Valhalla** [comment]
Duplicate #9220
