### ISSUE TITLE
[Draenor Profession Books]

### ISSUE THREAD

**Issue by SL-Starcaller** [Valhalla-Gaming/Tracker#9225]
The various books that should learn you surten Draenor skills for all the professions do not yield anything.
example: http://www.wowhead.com/item=111921/draenor-engineering

They worked during the wod expansion.

This makes it pretty damned hard to get professions up in order to learn for example pandaria or cata recipes.
One has to level from 1 all the way up, since starting with Legion materials is absolutely unbeneficial due to the lack of proper implementation of said professions.

**Comment by avaksx** [comment]
#8203 Already reported more than one time, it's on high priority for quite some time now.

**Comment by SL-Starcaller** [comment]
Thank you, I couldn't locate it, but it seems this makes sense since this issue is reported last year(!!!!)
