### ISSUE TITLE
Cave of the Blood Trial

### ISSUE THREAD

**Issue by Penoxgames** [Valhalla-Gaming/Tracker#9229]
**Describe the issue you're having**: I'm unable to defeat Bloodtotem Warmonger in quest Cave of the Blood Trial on Broken Isles. Almost every hit I did to him was missed or gave him almost no damage. When i look on videos about this quest they are able to defat him and they give him more damage than I do.

**Explain how you expect it work**: I should be able to defeat him even after using items lvl. 700.

**Steps to reproduce the problem**:

1. Go to the Highmountain -> Clif's Edge
2. Takte quest Cave of the Blood Trial
3.  Try to defeat him.

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=39455/cave-of-the-blood-trial

**Comment by Analog-Valhalla** [comment]
Duplicate #8925
