### ISSUE TITLE
[Druid][Spell]  Shred - Incorrect Damage Numbers

### ISSUE THREAD

**Issue by avaksx** [Valhalla-Gaming/Tracker#9230]
**Describe the issue you're having**: Feral druids spell Shred doesn't do correct damage numbers as you can see from the photos. First screenshot is from battleground and second one is from training dummies.

**Explain how you expect it work**: It should do correct damage which says upon highlighting spell from spell book.

**Steps to reproduce the problem**:

1. Play Feral Druid.
2. Cast Shred on target.
3. See that damage doesn't match spell text.

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=5221/shred

![1](https://cloud.githubusercontent.com/assets/22096253/24084004/86414fb6-0ce2-11e7-9867-adca110be046.jpg)
![1 2](https://cloud.githubusercontent.com/assets/22096253/24084005/864f7cc6-0ce2-11e7-8988-aef2b0155504.jpg)

**Comment by MrZlim** [comment]
Physical damage is always affected by armour. The tooltip shows you the right damage if your target has 0 armour.

**Comment by Analog-Valhalla** [comment]
I can agree to this, Target dummies are not the best place to test tool-tips. Working as intended.
