### ISSUE TITLE
[Druid][Talent] Brutal Slash - Incorrect Damage Numbers

### ISSUE THREAD

**Issue by avaksx** [Valhalla-Gaming/Tracker#9231]
**Describe the issue you're having**: Feral druids talent Brutal Slash doesn't do correct damage numbers as you can see from the photo. Photo is from the training dummies, but same thing happens in PvP as well.
**Explain how you expect it work**: It should do correct damage which says upon highlighting spell from spell book.
**Steps to reproduce the problem**:

1. Play Feral Druid.
2. Choose Brutal Slash talent.
3. See that damage doesn't match spell text.

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=202028/brutal-slash
![1 3](https://cloud.githubusercontent.com/assets/22096253/24084067/75cd13bc-0ce3-11e7-978e-8f8a5a70f237.jpg)

**Comment by MrZlim** [comment]
Physical damage is always affected by armour. The tooltip shows you the right damage if your target has 0 armour.

**Comment by Analog-Valhalla** [comment]
I can agree to this, Target dummies are not the best place to test tool-tips. Working as intended.
