### ISSUE TITLE
[Druid][Spell] Rake - Incorrect Damage Numbers

### ISSUE THREAD

**Issue by avaksx** [Valhalla-Gaming/Tracker#9232]
**Describe the issue you're having**: Feral druids spell Rake doesn't do correct damage numbers as you can see from the photo.

**Explain how you expect it work**: It should do correct damage which says upon highlighting spell from spell book.

**Steps to reproduce the problem**:

1.  Play Feral Druid.
2.  Cast Rake Spell.
3. See that damage doesn't match spell text.

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=1822/rake

![wowscrnshot_031917_203549](https://cloud.githubusercontent.com/assets/22096253/24084101/48fee828-0ce4-11e7-9c41-710435316595.jpg)

**Comment by MrZlim** [comment]
Physical damage is always affected by armour. The tooltip shows you the right damage if your target has 0 armour.

**Comment by Analog-Valhalla** [comment]
I can agree to this, Target dummies are not the best place to test tool-tips. Working as intended.

**Comment by avaksx** [comment]
Okay, mo apologies for that. But why in this case the damage is bleed damage not physical? 

@Analog-Valhalla @MrZlim
