### ISSUE TITLE
[Druid][Spell] Thrash - Incorrect Damage Numbers

### ISSUE THREAD

**Issue by avaksx** [Valhalla-Gaming/Tracker#9233]
**Describe the issue you're having**: Feral druids spell Thrash doesn't do correct damage numbers as you can see from the photo.

**Explain how you expect it work**:  It should do correct damage which says upon highlighting spell from spell book.
 
**Steps to reproduce the problem**:

1. Play Feral Druid.
2. Cast Thrash spell.
3. See that damage doesn't match spell text.

**Links to Wowhead, YouTube, etc**: http://www.wowhead.com/spell=77758/thrash
![wowscrnshot_031917_203657](https://cloud.githubusercontent.com/assets/22096253/24084116/89101a9a-0ce4-11e7-9355-a5fc6b3b8ed8.jpg)

**Comment by MrZlim** [comment]
Physical damage is always affected by armour. The tooltip shows you the damage if your target has 0 armour.

**Comment by Analog-Valhalla** [comment]
I can agree to this, Target dummies are not the best place to test tool-tips. Working as intended.
