### ISSUE TITLE
fatigue

### ISSUE THREAD

**Issue by Phychoblaze** [Valhalla-Gaming/Tracker#9251]
i get fatigue almost everywhere in vashj'ir
 go there and you'll see, it's not only in the air above it but in the water too with some exceptions near the bottom.
i haven't even been able to go from the first posts to the horde ones due to fatigue and i can't even go retrieve my corpse due to fatigue too.

also i should be able to breathe underwater in certain places near the bottom and that is not the case either.

**Comment by Analog-Valhalla** [comment]
Duplicate #4422
