### ISSUE TITLE
[Quest] Cave of the Blood Trial

### ISSUE THREAD

**Issue by Fayetallity** [Valhalla-Gaming/Tracker#9260]
**Describe the issue you're having**: The quest NPC you have to defeat hits way too hard. On my warrior I even switched to prot and stood no chance at all. 

I have the feeling that only his visual level scales with mine, but not his stats or damage. I'm lvl 101 and he hits me like a lvl 110 would do.

**Explain how you expect it work**:
Place the Witch of the Wood's carcass on the altar and defeat a Warmonger in single combat. 

**Steps to reproduce the problem**:

1. Follow Oakin Ironbull to the cave
2. Place harpy corpse on altar
3. defeat warmonger

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/quest=39455/cave-of-the-blood-trial

quest npc: http://www.wowhead.com/npc=97544/bloodtotem-warmonger

**Comment by Analog-Valhalla** [comment]
Duplicate #8925

**Comment by Analog-Valhalla** [comment]
Currently this quest is achieveable, but harder than it should be for new players. There is a report already on the Issue Tracker, so I must close this one to prevent duplicates. Currently there is one work around players with lower survivability have used. If a friend or player heal the quester while attempting this boss, success is usually inevitable.

**Comment by Fayetallity** [comment]
I'm having the same issue with the quest after this. can it be that because I took a lvl 100 boost on my char the level scaling is not working correctly?
