### ISSUE TITLE
Rite of Blood

### ISSUE THREAD

**Issue by Crandalius** [Valhalla-Gaming/Tracker#9265]
Hi all, I've stumbled on a quest where it's really important to fix. Within this quest you should be assisted be Noltharok not sure how you spell his name but let's not judge on that. So during this fight he must taunt Marakhan the entire time due to him being a elite would make it extremely hard to face at whichever level you are i mean you need to actually group up to kill him regardless of that i noticed that as soon you die on this npc he would flag himself as non attackable i assume that the dummy doesn't respond or something i dunno anycase if we can get this fixed that would be great

**Comment by Ardente47** [comment]
This has been reported already. Please use the search function.
It actually is possile to solo it. My tank dh i.e did it solo. Well, dh tank is op with the massive heals, anyways.

https://github.com/Valhalla-Gaming/Tracker/issues/8926

**Comment by Fayetallity** [comment]
I cannot kill this guy on my warrior. not even as prot.  not even with the assistance of someone else. Someone who soloed it himself when he was on the quest.
I had the same issue with the quest prior to this one.    Can it be becasue my char was lvl 100 boosted the level scaling does not work?

**Comment by Analog-Valhalla** [comment]
Duplicate #8926
