### ISSUE TITLE
 Binding Shot & Explosive Shot broken AF

### ISSUE THREAD

**Issue by Crandalius** [Valhalla-Gaming/Tracker#9266]
Hi all,

Binding shot is broken as hell instead of stunning npc's it would stun yourself if that makes sense then lastly explosive shot does the visual but it freezes in mid air i need to actually stack all my npc's to ensure i hit them all (not as good as it sounds i end up dying) please guys these seem pretty minor but i mean it should also be easy to fix

Lots of love

**Comment by Analog-Valhalla** [comment]
Report invalid. Reason: 
-Multiple Issues in one report
-Duplicate reports already in the Issue Tracker
-No Wowhead link submitted
Please submit individual reports, check if the issues are already reported, and provide wowhead links in the report.
