### ISSUE TITLE
MM hunter - talent bugged (Binding shot)

### ISSUE THREAD

**Issue by Rattoy** [Valhalla-Gaming/Tracker#9301]
**Describe the issue you're having**:
When u use Binding shot it will stun you instead the enemy.
**Explain how you expect it work**:
When u use Binding shot it will stun you instead the enemy.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=109248/binding-shot

**Comment by Analog-Valhalla** [comment]
Duplicate #7901
