### ISSUE TITLE
MM hunter talent bug - Explosive shot

### ISSUE THREAD

**Issue by Rattoy** [Valhalla-Gaming/Tracker#9303]
**Describe the issue you're having**:
Explosive shot isnt launch, just stand in place without doing nothing not even moving.

**Explain how you expect it work**:
should launch to some distance straight.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/spell=212431/explosive-shot

**Comment by Analog-Valhalla** [comment]
Duplicate #9014 Please check if reports exist before making more that are duplicates. Thank you :D
