### ISSUE TITLE
Death Knight Talent: All Will Serve

### ISSUE THREAD

**Issue by llamalama** [Valhalla-Gaming/Tracker#9309]
http://www.wowhead.com/spell=194916/all-will-serve

The minion this summons only does 1-2 damage per attack.

**Comment by VictorTyne** [comment]
http://www.wowhead.com/spell=194916/all-will-serve#comments

The Risen Skulker is supposed to have the following stats relative to the summoner:
Risen Skulker: 100% AP->SP, 100% AP, 125% Armor, 20% Health.

It is also supposed to have two abilities:
Skulker Shot (http://www.wowhead.com/spell=212423/skulker-shot)
Arrow Spray (http://www.wowhead.com/spell=207260/arrow-spray)

**Comment by Moustachos** [comment]
Note: Risen Skulker no longer uses Arrow Spray (for a while now).
