### ISSUE TITLE
[Profession][Item] Foxflower flux

### ISSUE THREAD

**Issue by WarcraftAcc** [Valhalla-Gaming/Tracker#9314]
**Describe the issue you're having**:
Foxflower flux can't be bought or rewarded from a quest.
**How should it work**:
They should be buyable at 3 vendors and by quest, more info on wowhead.
**Links to Wowhead, YouTube, etc**:
http://www.wowhead.com/item=124436/foxflower-flux#reward-from-q

**Comment by Analog-Valhalla** [comment]
This item is gated off by the Blacksmithing quest chain. "Nature Provides" is the Blacksmithing quest, once you have completed said quest, the npc over in new Dalaran sells you the Foxflower Flux. This is the first quest in the quest chain, http://www.wowhead.com/quest=38501/hatecoil-hammerwork.
