### ISSUE TITLE
Early Spring Honor Talent ( Druid class) is not working !

### ISSUE THREAD

**Issue by jamil142** [Valhalla-Gaming/Tracker#9315]
**Describe the issue you're having**:

**Explain how you expect it work**:

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by Analog-Valhalla** [comment]
Invalid report. Please provide more information and a wowhead link to the spell.

**Comment by jamil142** [comment]
YEA IT is 2 Hard to understand Nice server my friend

**Comment by jamil142** [comment]
http://www.wowhead.com/spell=203624/early-spring
