### ISSUE TITLE
honor talent bugs ( rogue sub )

### ISSUE THREAD

**Issue by saeedelahe** [Valhalla-Gaming/Tracker#9323]
**Describe the issue you're having**:
Phantom Assassin 
**Explain how you expect it work**:
that that should be active automatically but its not
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Links to Wowhead, YouTube, etc**:

**Comment by saeedelahe** [comment]
I lost 10 percent damage bonus cuz of this bug

**Comment by Traveler-Valhalla** [comment]
#8309 already reported
