### ISSUE TITLE
Vek=Analog

### ISSUE THREAD

**Issue by Zealotry** [Valhalla-Gaming/Tracker#9326]
**Describe the issue you're having**: Vek is a GM

**Explain how you expect it work**: Vek is a traitor

**Steps to reproduce the problem**:

1. Curse Vek
2. Slap Vek
3. Kill Vek
4. Repeat

**Links to Wowhead, YouTube, etc**: Server Error 404

**Comment by Analog-Valhalla** [comment]
Issue Invalid. Duplicate #1
