### ISSUE TITLE
(QUEST) Heroes of Darrowshire - Eastern Plaguelands

### ISSUE THREAD

**Issue by Kelpo122** [Valhalla-Gaming/Tracker#934]
http://www.wowhead.com/quest=27388/heroes-of-darrowshire

NPC Carlin Redpath (http://www.wowhead.com/npc=11063/carlin-redpath) doesn't give Extended Annals of Darrowshire (http://www.wowhead.com/item=13202/extended-annals-of-darrowshire)

**Comment by Tregeta** [comment]
Should be working now
