### ISSUE TITLE
(QUEST) Amidst Death, Life - Eastern Plaguelands

### ISSUE THREAD

**Issue by Kelpo122** [Valhalla-Gaming/Tracker#941]
http://www.wowhead.com/quest=27421/amidst-death-life

Using Rayne's Seeds (http://www.wowhead.com/item=61036/raynes-seeds) on any Ziggurat displays the message "Requires fungal vale Necropolis". I tried it exactly where the scourge guy was before i killed it and still the same.

Also, probably not related, the 3 Ziggurats are filled with miniature untargetable goblins with 2 bigass rockets each.

**Comment by Valhalla-Gaming** [comment]
Will be fixed next update
