### ISSUE TITLE
Agility does not increase enhancement shaman's spell power

### ISSUE THREAD

**Issue by Reloque** [Valhalla-Gaming/Tracker#943]
As the title says, agility does not increase an enhancement shaman's spell power. Although wikis say agility only increases melee and ranged attack power, the in-game tooltip on the paper doll is very clear that agility increases spell power:

    Increases Attack Power and Spell Power by [Agility]

Since intellect has no effect on enhancement shamans (the tooltip says so), agility is the primary source of spell power. I would guess the server is still using intellect to calculate spell power.

**Comment by Reloque** [comment]
May be the source of some issues in #764

**Comment by Moustachos** [comment]
Fixed in a previous update.
