### ISSUE TITLE
Holy Power - Visual

### ISSUE THREAD

**Issue by Tregeta** [Valhalla-Gaming/Tracker#980]
Crusader Strike/Judgment are visually applying more holy power than suggests causing a bug. Due to this, it may sometimes show 3 holy power when in fact there is only truly 2 present.

**Comment by manic17** [comment]
Issue is still present in-game and is rather annoying to have to manually when i have gained a HP in order to use abilities that require 3 or more HP

**Comment by Tregeta** [comment]
Does this issue still persist?

**Comment by Luminescent-Hellscream** [comment]
I will check later tonight if this issue still present in-game or not

**Comment by Moustachos** [comment]
This problem doesn't seem to persist on current version, closing the issue.

If you still experience it, please provide a way to reproduce the bug (which spell, which conditions etc.).

**Comment by Moustachos** [comment]
Ref #2266
