### ISSUE TITLE
Druid - Spell - Wrath

### ISSUE THREAD

**Issue by MirrorWraith** [Valhalla-Gaming/Tracker#989]
http://www.wowhead.com/spell=5176/wrath
wrath didnt need mana

**Comment by MirrorWraith** [comment]
still the same right now

**Comment by skorge1** [comment]
atm wrath on balance spec costs no mana. That is not the case on retail. It is only suppose to cost no mana in restoration specialization.

**Comment by Moustachos** [comment]
Ref #2266
